
---
title: 'Helping Africa'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1924
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 28
  issue: 3
  page: 106
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There is one thought in our will to help Africa that continually recurs. We think again and again of going over there and taking charge and helping people to do things better, leading them as we are overfond of saying, "from darkness into light." Let us curb this custom of thinking with one or two after-thoughts.

First, Africa is full; not perhaps full to the extent that Belgium is, or the Rheinpfalz, but it is full to the capacity of its present industrial development. It is not, save in a few places, an empty land inviting immigrants. Secondly, the Africans are not asleep. They are awake. Not as wide awake or as well-acquainted with modern civilization as many groups, but nevertheless awake and awakening, thrilling with new spirit and new determination. Thirdly, Africa belongs to the Africans. They have not the slightest intention of giving it up to foreigners, white or black. They propose to develop their own country and to be citizens thereof. They resent that attitude that assumes that other folk of any color are coming in to take and rule their land.

Liberia for instance has held and defended her country with blood and tears for a hundred long and weary years. She is not going to allow American Negroes to assume control and to direct her government. Liberia, in her mind, is for Liberians.

