
---
title: 'Attention'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 15
  issue: 6
  page: 267-268
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Field Artillery has become a highly specialized instrument of great precision. Front line trenches are frequently less than a hundred yards apart and nothing discourages your own infantry more than to receive a shell that was intended for the next trench. When the men of the 92nd Division go "over the top" they will frequently follow an accompanying barrage as close as a hundred yards.

Now that "curtain of fire" behind which colored soldiers will move to the assault of brutal German lines will be laid down by the first field guns ever manned by colored American soldiers. Every Negro in the United States is deeply interested in seeing that the artillery of the 92nd Division becomes as efficient an organization as the Tenth Cavalry, for instance, of which every colored American is justly proud.

The 167th Field Artillery Brigade is tremendously handicapped today because the draft has failed to bring in a sufficient number of educated and technically trained men to fill the special details and assume the responsibilities of Non-Commissioned Officers. The Commanding General of the Artillery Brigade desires at once to secure the following specialists:

* Forty-four *Telephone* men who have had experience at installing and operating telephones, with a knowledge of elementary electricity.
* Sixty-one *Instrument* men with at least a high school education. They will be trained to use the Battery Commander's telescope, aiming circle, range finder, and other instruments similar to surveyors' and engineers' instruments. Civil engineers are particularly desired for this work.
* Forty-four *Scouts*, high school graduates, if possible, who have had some instruction in drafting and mapping and can learn to do reconnaissance work.
* Forty-six *Typists* and 12 *Stenographers* to do clerical work in Brigade and Regimental headquarters, and Battery offices.
* Thirty-one *Mechanics* who can keep the guns and motors in repair, men with experience as machinists or millwrights.
* Eighteen *Saddlers* to repair harness and saddles.
* Forty-seven *Horse-shoers*.
* Ten *Radio or Telegraph Operators*.
* Three hundred and twenty-three men of good education and mature years who can work into the responsible positions of *First Sergeants, Mess Sergeants, Supply Sergeants, Sergeants*, and *Corporals*.

To all of the above who prove competent, positions are open carrying the rank or the pay of Non-Commissioned Officers: $36-$38 a month and support.

In addition there are needed:
* Forty *Hospital attendants*, men having a knowledge of first aid or previous hospital experience.
* Thirteen *Truck drivers* who understand automobile repairs.

Commanding General,    
167th Field Artillery Brigade,    
92nd Division,    
Camp Dix, New Jersey    

stating age, education, and experience in the class applied for. Those who are already registered in the draft will, if accepted, be enlisted at once in the National Army; those not registered will be enlisted in the Regular Army and assigned to the 167th Field Artillery Brigade.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Soldiers (1920)](/Volumes/20/03/soldiers.html)
* [The Negro Soldier (1919)](/Volumes/19/02/negro_soldier.html)
* [To the Rescue (1916)](/Volumes/12/01/rescue.html)
* [Officers (1917)](/Volumes/14/02/officers.html)
* [Baker (1917)](/Volumes/15/02/baker.html)

<!-- Similar articles end here -->