
---
title: 'The Elections'
author: Du Bois, W.E.B.
date: Jun. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 2
  page: 70
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



In the general results of last month's elections there is not much to interest the American Negro but there are several significant points. First, the Vote for Woman Suffrage: There is no doubt of the decisive part which the Negro vote played in New Jersey and in Pennsylvania. In New Jersey, as the Philadelphia *North American* says: "The Negro vote defeated the Woman Suffrage amendment in New Jersey. This assertion is made without qualification by suffrage workers and others who have studied the returns of last Tuesday's balloting." On the other hand, in Pennsylvania with its 50,000 Negro voters the woman's cause must have gained a very large proportion of this vote. What made the difference between New Jersey and Pennsylvania? The answer is simple. Pennsylvania took special pains to educate Negro voters on Woman Suffrage. New Jersey did practically nothing. What other result could you expect?

A very excellent lesson was taught the Republican party in New York City. In spite of desperate efforts of politicians to gerrymander Harlem the Negro has a large vote in the 21st and 31st assembly districts. In each one of these the colored people put up candidates. In the 31st district Mr. John M. Royal polled 878 votes against 760 for the Republican candidate allowing the Democratic candidate to win by a minority vote. This puts the proposition squarely up to the Republican party in Harlem: If the Negro voter stands firm and the Republicans want to win them they must win with a Negro candidate.

