
---
title: 'Haiti'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 2
  page: 80-81
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



At first, inquiries at the White House concerning the intentions of the United States in Haiti were appeased by reference to the proclamation of the southern-born admiral, who is now ruling that island as conqueror. This proclamation contains certain smooth
promises of benevolent guardianship in Haiti with no intention to
interfere with the political integrity in Haiti. Recently, however, the
veil of the State Department has been partially withdrawn and inquirers
are now told by letter over the signature of A.A. Adee, the second
assistant secretary of State: "In reply to your request for a statement
of our purposes in Haiti, the Department begs to inform you that it has
refrained, for the time being, from making public any statement
regarding its policy in Haiti."
We notice, too, that a southern white
man has been appointed American minister to Haiti. His name is Blanchard
and we believe that he is from Louisiana. We would like to know if
this Blanchard is related to the Blanchard who signed the following
advertisement in the Shreveport, La., *Times,* January 10, 1908.

> To the Colored Citizens of the Parish of Caddo    
> &nbsp;
> We notice at a meeting of the colored citizens at the Antioch Baptist Church a few evenings ago, that they passed resolutions endorsing the prohibition movement in the parish of Caddo, and have pledged themselves to aid in the moral wave, which they claim is now sweeping the country. So far we have no objection, but we wish to say to the colored voters of Caddo parish that the present prohibition contest is a white man's tight, and that they must not take part in it. *We have had various offers of assistance from the colored voters* for the anti-prohibition cause, and our answer to them has been that *they should not attempt to vote* in the coming election on January 14th.    
> &nbsp;
> We do this in all kindness to the colored man, believing that he should
not attempt to obtrude himself in this tight, which is *purely a contest between the white citizens of this parish.* We do it because of the
memory which we have of the dark days of Reconstruction when one race
was arrayed against the other, and when no man's life was safe in the
state of Louisiana. We do not wish to appear dictatorial in this matter,
but we are *determined that this question shall be settled by the intelligent white voters of the parish of Caddo,* and our colored
friends may resolute as much as they please, but we warn them now, once
and for all, that they *must not attempt to vote either for one side or the other.* We do not believe in Negro domination on either side of this
question, and while we are sure that more colored people would vote for
prohibition, yet as *white men,* believing in the *rule* of the *Caucasian,* we *cannot tolerate their interference* in this election. Respectfully submitted.    
> &nbsp;    
> J D. Wilkinson<br>Ashton Blanchard,<br>Andrew Querbes<br>For Citizens' Committee.

It will be remembered that the parish of Caddo has lynched more Negroes
than any single county in the United States.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Haiti (1921)](/Volumes/22/06/haiti.html)
* [Haiti (1920)](/Volumes/19/06/haiti.html)
* [Naval Ruler (1917)](/Volumes/14/01/naval_ruler.html)
* [Presidential Candidates (1920)](/Volumes/20/02/presidential-candidates.html)
* [Soldiers (1919)](/Volumes/17/01/soldiers.html)

<!-- Similar articles end here -->