
---
title: 'La Follette'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1924
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 28
  issue: 4
  page: 154
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Let Negroes read with thoughtful care and deep understanding the manifesto of the Third Party. It makes no direct reference to our problems. But what are our problems? They are the world's problems and something more. That something more is color prejudice and that is our immediate problem. But back of that and even with that solved are problems as pressing, as imperative, as tremendous for us as for any working people. These we cannot neglect. Simultaneously with our peculiar problems,  these others call for solution. They cannot be postponed.

What are they? They rise according to La Follette's Cleveland program from the effort of organized force and greed to destroy liberty; and that program therefore proposes

1.	The crushing of private monopoly by Federal power.
2.	Freedom of speech.
3.	Public ownership of natural resources.
4.	Taxation of wealth.
5.	Public control of credit.
6.	Collective bargaining for farmers and laborers.
7.	Public marketing of farm products.
8.	Legislation to aid industrial coöperation.
9.	International action to help the world.
10.	Public ownership of railroads.
11.	Abolition of the tyranny of the courts,
12.	Abolition of child labor.
13.	A deep waterway from the lakes to the sea.
14.	The outlawing of war.

For the uplift of the world this is one of the best programs ever laid down by a political party in America. It can be carried out and still leave black folk and brown and yellow disinherited from many of its benefits. It can triumph and by its very triumph bring new tyrannies upon hated minorities. And yet despite this it will be far better than the present America.

This program then is so good in fact that it is most disheartening to find Mr. LaFollette deliberately dodging two tremendous issues---the Ku Klux Klan and the Negro. This is inexcusable. These matters were forced on his attention by this Association and by others. He and his platform are silent. Wherefore we must conclude that Robert LaFollette has no opinion so far as the Secret Mob to Foster Race and Religious Hate is concerned and no convictions as to the rights of Black Folk.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Socialism and the Negro (1921)](/Volumes/22/06/socialism_and_the_negro.html)
* [Our Economic Peril (1930)](/Volumes/37/03/our_economic_peril.html)
* [Our Program (1930)](/Volumes/37/05/our_program.html)
* [Toward a New Racial Philosophy (1933)](/Volumes/40/01/toward_a_new_racial_philosophy.html)

<!-- Similar articles end here -->