
---
title: 'Curtains of Pain'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 13
  issue: 4
  page: 162
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Above the Hill where St. John's Divine Cathedral raises its bald and mighty arch, hang the Curtains of Pain, grey and purplish as they sweep the Hill, but glowing above with rare and tender radiance save where the massive shadow falls athwart—the shadow from the Valley of the Shadow.

There is moaning here and writhing and now and then a cry, and yet less, infinitely less, than one expects. There is silence and deep-pulsing stillness---all that and more. But above all there sits a mighty Brotherhood. We are all initiated into the Secret of Life beneath the flowing grace of the Curtains of Pain. All little distinctions flee; there is no Race; there is no Age; there is but one language. There is a certain softness of speech---we lift up gladly helping hands and offer every kindness of the softened word and touch of sympathy—while through the great window pours the winter's warm sun and the light music of the world comes faintly down in song.

It is a very beautiful place. I am glad I am here.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Forward (1920)](/Volumes/20/05/forward.html)
* [Unrest (1920)](/Volumes/19/05/unrest.html)
* [The Burden of Black Women (1914)](/Volumes/09/01/burden_of_black_women.html)
* [Chamounix (1921)](/Volumes/23/02/chamounix.html)
* [Peace (1919)](/Volumes/17/02/peace.html)

<!-- Similar articles end here -->