
---
title: 'Egypt and India'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 2
  page: 62
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The sympathy of Black America must of necessity go out to colored India and colored Egypt. Their forefathers were ancient friends, cousins, bloodbrothers, in the hoary ages of antiquity. The blood of yellow and white hordes has diluted the ancient black blood of India, but her eldest Buddha still sits black, with kinky hair; the Negro who laid the founding stones of Egypt and furnished some of her mightiest thinkers, builders and leaders has mingled his blood with the invader on so vast a scale that the modern Egyptian mulatto hardly remembers his descent. But we are all one---we the Despised and Oppressed, the "niggers" of England and America.

We of America fight the great fight of Peace---we agitate, we petition, we expose, we plead, we argue. It is a long, slow, humiliating path, but for us War, Force, Revolution are impossible, unthinkable. For anybody the costs of bloody uprising are so vast and uncounted that they must bring pause to the wildest. Yet, who can judge others? Who sitting in America can say that Revolution is never right on the Ganges or the Nile? Who of us who suffer can judge how unbearable is the suffering of unknown friends? We bow our heads and close our aching ears. Only our hearts pray that Right may triumph and Justice and Pity over brute Force and Organized Theft and Race Prejudice, from San Francisco to Calcutta and from Cairo to New York.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)
* [India (1930)](/Volumes/37/08/india.html)
* [The Strength of Segregation (1913)](/Volumes/07/03/strength_of_segregation.html)
* [The Durbar (1912)](/Volumes/03/04/durbar.html)
* [Listen, Japan and China (1933)](/Volumes/40/01/listen_japan_and_china.html)

<!-- Similar articles end here -->