
---
title: 'London'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 4
  page: 159
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There is in the world no city like London. Nor is its distinction merely a matter of size. To be sure, it is a vast aggregation of men---it gives the visitor a curious sense of endlessness by its very disorganization, by the fact that one can find center after center of busy running life stretching away mile after mile and yet all is London. London has no beauty that will compare it to Paris, no blare and flare like New York.

Yet London has an individuality, a tradition and an importance that make it the capital of the world in a sense, true of no other center since the days of imperial Rome. The individuality is peculiar, subtle, striking---yet difficult to express. One sees a busy mart of endless interests, worldwide ramifications, tremendous power. One sees a tradition, a memory clothed in living flesh and word, and a power which makes this city an expression of the empire on which the sun never sets.

This empire is a colored empire. Most of its subjects---a vast majority of its subjects---are colored people. And more and more the streets of London are showing this fact. I seldom step into the streets without meeting a half dozen East Indians, a Chinaman, a Japanese or a Malay, and here and there a Negro. There must be thousands of colored people in the city. They do not, of course, color the world so obviously as in an American city, but one senses continually the darker world.

No pageant to-day in London is complete without the colored representatives. In the two great coronation processions it was the black and brown and yellow Indian princes in the brilliant magnificence of their silk and jewels who shared the plaudits of the crowds with the king himself, and the black Prince of Abyssinia rode among the royal guests.

London is polite and considerate to her darker brothers. There is color prejudice and aloofness undoubtedly here, but it does not parade its shame like New York or its barbarity like New Orleans. Hotel, theater and restaurant stand not only open, but studiously attentive and polite. The courtesies of the street and the tram-car are thoughtfully passed, and in the highest social life colored men and women at the last days of festivity sat at the tables of the highest in the land.

Yet London is uneasy. London is sensing the strength and determination in the darker world and is wondering what it all portends in the future. The unrest in India and Egypt causes deep and widespread apprehension in all England, and the situation in South Africa is being narrowly watched.

What more fitting center then than London for the coming together of the first world conference of the races and peoples of the world! They are to meet not as master and slave, missionary and heathen, conqueror and conquered---but as men and equals in the center of the world, and the meeting will be watched with intense interest and remembered for many a long day.

