
---
title: 'Anarchism'
author: Du Bois, W.E.B.
date: Feb. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 4
  page: 182
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



<span class = "small-caps">The Crisis</span> has continually insisted that peonage, false arrest and
injustice in the Southern courts were responsible for the mass of
so-called Negro crime. The testimony to this comes continually from
white Southerners themselves. In nearly every Southern State this has
been asserted from time to time in official reports, but perhaps the
latest and strongest of these confessions comes from Alabama. The
Federal grand jury of Jefferson County says that justices and constables
are deliberately enriching themselves by a system of extortion and
intimidation:

> For victims, whether male or female, it singles out, in every
instance, those too poor or ignorant, too humble or frightened to
protect themselves. *A very large majority are Negroes.* Were they not
Negroes, but *members of a more resentful race, anarchism would be prevalent.*

*WERE THEY NOT NEGROES!*

