
---
title: 'Politics'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 4
  page: 180-181
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The colored voter now stands face to face with the great question of the proper use of his electoral franchise. Under normal conditions 2,000,000 of the 20,000,000 votes which might be cast at a presidential election would belong to the race, and some day, despite every effort of fraud and race prejudice, those votes are going to be cast.

To-day, however, of the 15,000,000 or more votes which will actually be cast for President, some 500,000 will be black men's votes.

What shall we do with these 500,000 ballots?

First of all we must teach ourselves to regard them seriously. The Negro-American is not disfranchised; on the contrary, he is a half million votes this side of disfranchisement and that is a long, long way. There have been but two or three presidential elections since the war which have not been settled by a margin of less than a half million votes, and in every single election since the proslavery compromise of 1850 such a number of votes distributed at strategic points would easily have decided the presidency.

The votes of black Americans are today at strategic points. We may, of course, leave the South out of account: on account of illegal enactments and brazen fraud, democratic government exists in the South only in inchoate and incomplete form. The presidential election is probably going to be decided by the Middle West and the States of New York and New Jersey. New York and

Ohio have each between 40,000 and 50,000 colored votes; New Jersey, Illinois and Indiana have each 30,000 or more. Is there any political prophet who would risk his reputation on the possibility of any one of these States being carried by more than 20,000 majority? There may be majorities of 50,000 or 100,000 in one or two of the States, but the chances are that the colored voters hold the balance of power in every one of their States and thus have the power to say whether William Howard Taft or Woodrow Wilson shall be the next President.

If colored America had long political experience and wide knowledge of men and measures, it would organize the black voters of each State into a solid phalanx. It would say to this phalanx: white and colored voters in this land are selling their votes too cheaply. By the use of a "slush fund" of $3,000,000 Theodore Roosevelt was able almost to split the Republican party. You could easily sell your votes next November for one or two millions of dollars, but that is too cheap. You could easily sell your votes for an Assistant Attorney General, a Register of the Treasury, a Recorder of Deeds and a few other black wooden men whose duty it is to look pleasant, say nothing and have no opinions that a white man is bound to respect. This also is too cheap---it is dirt cheap.

What price should you ask for 500,000 votes, black America? You should ask this:

1. The abolition of the interstate "Jim Crow" car.  
2. The enforcement of the Thirteenth Amendment by the suppression of peonage.
3. The enforcement of the Fourteenth Amendment by cutting down the representation in Congress of the rotten boroughs of the South.  
4. National aid to elementary public schools without class or racial discrimination.

Is this price too much to pay for a presidency? It is not if you dare ask it.

Who then would pay it? Would William Howard Taft pay it? There has not been in the presidential chair for fifty years a man so utterly lacking in initiative and ideal as Mr. Taft. His abject surrender to Southern prejudice and reaction has been simply pitiable: He began his career by defending disfranchisement; he followed this by promising to appoint no black man to office if any white man protested; and in spite of the fact that over 200 Negroes have been publicly murdered without trial during his administration, the utmost that 10,000,000 black men have elicited from his lips is a hesitating statement that he is sorry---and helpless. Any colored man who votes for Mr. Taft will do so on the assumption that zero is better than minus one.

As to Mr. Wilson, there are, one must confess, disquieting facts: he was born in Virginia and he was long president of a college which did not admit Negro students and yet was not honest enough to say so, resorting rather to subterfuge and evasion. A man, however, is not wholly responsible for his birthplace or his college. On the whole, we do not believe that Woodrow Wilson admires Negroes. Left to himself, we suspect he would be like Mr. Johnson, the new dean of Yale. Mr. Johnson is a Southerner, and recently told a colored applicant that Yale did not want "Chinese, Jews or Negroes." The ideal of such folk would be a world inhabited by flaxen-haired wax dolls with or without brains.



Notwithstanding such possible preferences, Woodrow Wilson is a cultivated scholar and he has brains. We know that there are several hundred millions of "Chinese, Jews and Negroes" who have to be reckoned with, and that the date at which the "blond beast" will inherit this earth has been, to put it mildly, indefinitely postponed. We have, therefore, a conviction that Mr. Wilson will treat black men and their interests with farsighted fairness. He will not be our friend, but he will not belong to the gang of which Tillman, Vardaman, Hoke Smith and Blease are the brilliant expositors. He will not advance the cause of oligarchy in the South, he will not seek further means of "Jim Crow" insult, he will not dismiss black men wholesale from office, and he will remember that the Negro in the United States has a right to be heard and considered; and if he becomes President by the grace of the black man's vote, his Democratic successors may be more willing to pay the black man's price of decent travel, free labor, votes and education.



Outside of these two men, what else? We thank God that Theodore Roosevelt has been eliminated. How many black men, with the memory of Brownsville, could support such a man passes our comprehension. Of Eugene V. Debs, the Socialist candidate, we can only say this frankly: if it lay in our power to make him President of the United States we would do so, for of the four men mentioned he alone, by word and deed, stands squarely on a platform of human rights regardless of race or class.

