
---
title: 'The Pan-African Congresses: The Story of a Growing Movement'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Oct. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 8
  page: 263--264
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The *first Pan-African Congress* was held February 19-21, *1919*, in the Grand Hotel, Paris. The executive committee consisted of M. Blaise Diagne, President; Dr. W. E. B. Du Bois, Secretary; Mrs. Ida Gibbs Hunt and Mr. M. E. F. Fredericks. Fifty-seven delegates representing fifteen countries were present and among the speakers were members of the French Parliament, the President of Liberia, a former Secretary of State of Portugal and several other distinguished persons.

The *second Pan-African Congress* met in London August 28 and 29, *1921*, in Brussels, Belgium, August 31, and September 1 and 2, *1921*, and in Paris, France, September 4 and 5, *1921*, with M. Blaise Diagne as President and W. E. B. Du Bois as Executive Secretary. A special committee visited the Assembly of the League of Nations with a petition, September 6. There were present one hundred and ten delegates representing thirty-three different countries and the sessions were attended by about a thousand visitors. Among the speakers were Florence Kelley of America, Norman Leys of England, Senator LaFontaine and Professor Otlet of Belgium, Blaise Diagne and M. Barthèlemy of the French Chamber of Deputies, General Sorelas of Spain, M. Paul Panda of the Belgian Congo and others. The European press of England, Scotland, France, Belgium, Germany and Italy took wide notice of the Congress.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

The *third Pan-African Congress* was held November 7 and 8, *1923*, in London and November 25, *1923* in Lisbon. There was a small number of delegates to these sessions as the Congress had not been properly worked up by the French secretary. The Circle of Peace and Foreign Relations under Mrs. A. W. Hunton as Chairman finally sent Dr. Du Bois to hold the Congress. There were some distinguished people as speakers including Sir Sidney, now Lord Olivier, Mr. H. G. Wells and Mr. Harold Lasky; and Mr. Ramsey McDonald would have been present had it not been for the sudden crisis of the general election. In Lisbon there were present the Minister of Colonies and one former minister and several members of parliament.

It was planned to have the *fourth Pan-African Congress* meet in the West Indies in 1925 but the plans miscarried on account of the difficulty of transport. Finally, the Circle of Peace and Foreign Relations, under the Chairmanship of Mrs. A. W. Hunton, came forward and undertook to assemble the Fourth Congress in New York City, August 21, 22, 23 and 24, 1927. The Circle raised nearly Three Thousand Dollars to finance the Congress and made all the arrangements. Dr. W. E. B. Du Bois acted as General Chairman and Mr. Rayford W. Logan as Secretary and interpreter. An exhibition of fifty-two maps and charts illustrating the condition of peoples of African descent was arranged by Dr. Du Bois and was on exhibition at headquarters.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

The program included an opening meeting with history of the Pan-African Congresses and greetings by delegates from West Africa, several of the West Indian Islands, including Haiti, and the East Indies. To this Mr. William Pickens added a report of the Brussels Conference for Oppressed Races. On the following three days, sessions were held morning, afternoon and night, taking up African missions, the history of Africa, the history and present conditions of the West Indies, the economic development of Africa and the political partition of Africa. The closing meeting dealt with education in Africa and African art and literature.

Among the chief speakers during the sessions were M. Dantes Bellegarde, former Minister of Haiti to France, former Member of the Assembly of the League of Nations and Commander of the French Legion of Honor; Dr. Charles H. Wesley, of Howard University; Professor Melville Herskovits of Columbia; Professor L. W. Hansberry of Howard; Chief Amoah III of the British Gold Coast; Mr. Leslie Pinkney Hill and Mr. H. H. Phillips of Cheyney; Dr. Wilhelm Mensching of Germany; and Mr. John Vandercook. All the sessions were well attended and the evening sessions often crowded. The total attendance aggregated five thousand persons. There were 208 paid delegates, representing 22 states and the District of Columbia; Haiti, the Virgin Islands, the Bahamas and Barbadoes; South America; the Gold Coast, Sierra Leone, Nigeria and Liberia, West Africa; Germany and India. The following resolutions were adopted:

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

The Fourth Pan-African Congress, assembled in New York City, August 21, 22, 23 and 24, 1927, with representatives from twenty-three American states, from nearly all of the West Indian Islands, from South America, Liberia, and British West Africa adopts this statement to express the legitimate aims and needs of the peoples of Negro descent. 

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*In General*

Negroes everywhere need: 
1. A voice in their own government.
2. Native rights to the land and its natural resources.
3. Modern education for all children.
4. The development of Africa for the Africans and not merely for the profit of Europeans.
5. The re-organization of commerce and industry so as to make the main object of capital and labor the welfare of the many rather than the enriching of the few.
6. The treatment of civilized men as civilized despite differences of birth, race or color.

Specifically and in particular we stress the need of reform in the following countries: 

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*Haiti*

In accordance with the report of the Committee of Six disinterested Americans we demand: the withdrawal from *Haiti* of all military forces of the United States and all officers, military, naval or otherwise, except only regularly accredited diplomatic representatives or consular agents. We demand that actual self-government be restored. In 1928 Haitian elections should be held. We demand that the American Receiver General of Customs be replaced by equitable agreement with the bond holders and that in general the attempt of American capital to dominate the industry and monopolize the land of Haiti be decisively checked and turned into such channels as will encourage industry and agriculture for the benefit of Haitian people. 

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*Africa*

The attitude of all the imperial powers who own Africa is fundamentally wrong. They are seeking profit, not men; they want trade and industry more than civilization and spiritual uplift. This attitude is a menace, not simply to Africans, but to modern democratic culture. It must and will be changed. 

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*British Africa* 

We congratulate Great Britain on granting increased political power to the four colonies of *British West Africa*. We urge an extension of this policy so that Africans may control their own legislative councils. 

We urge the restoration of their land and the granting of a voice in the government to the natives of *Kenya* and of *Northern* and *Southern Rhodesia*. 

We are alarmed at the attempt of the white minority in the *Union of South Africa* to monopolize the land of the black Aboriginees; to exclude them from profitable labor; to maintain, in effect, their present disfranchisement and to reduce them to impotent serfdom. We regard the reactionary program of the Herzog government as the greatest challenge to decent race relations in our day. 

In all *British Africa* it is lamentable to note how little is being done to educate the natives despite the founding of Achimota College.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*French Africa*

We urge in French Africa a further development of their admirable scheme of native education and an extension of political rights for a larger number of natives. We ask protection for the natives against the exploitation by French industry and commerce of the resources of this great colony.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*The Belgian Congo*

We still await in the *Belgium Congo* real evidence of a movement on the part of Belgium to restore land ownership to the natives; to give them some voice in their own government and to restrain the effort to make the Belgium Congo merely a profitable investment for European industry, with almost no concerted effort to uplift and develop the natives and conserve the natural resources for them. We are glad to see an increase in the appropriation for education in the Congo, but it is still far below the amount needed.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*Abyssinia*

We demand the continued independence of *Abyssinia*, coupled with international movements on the part of philanthropists to bring modern education to the people of that land and modern industry planned for the benefit of the Abyssinians and not simply for the European trade.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*Liberia*

We congratulate *Liberia* upon her improved financial position, but we are alarmed at the increasing power and influence of the owners of the Firestone rubber concession. We urge the authorities of Liberia and the Negro voters in the United States to be vigilant lest this industry's concession encroach upon the political independence of Liberia. We believe that the solution of Liberia's problems lies in the establishment of a strong system of universal education for all Liberians of both native and American descent.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*Portugal*

We demand for *Portugal* and her African colonies a curbing of that financial and industrial power which is forcing her into bankruptcy and making her colonies the property of slave-driving concessionaires, despite the liberal and far-sighted colonial legislation of Portugal.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*Missions*

We believe in missionary effort but in missionary effort for health, morals and education and not for military aggression and sectarian superstitions.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*The West Indies*

We urge the peoples of the *West Indies* to begin an earnest movement for the federation of these islands; the reduction of their present outrageous expenses of government; the broadening of educational facilities on modern lines and labor legislation to protect the workers against industrial exploitation. We regard the first step towards this to be an utter erasing of that color line between mulattoes and blacks, which sprang from slavery and is still being drawn and encouraged by those who are the enemies of Negro freedom.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*United States*

We believe that the Negroes of the United States should begin the effective use of their political power and instead of working for a few minor offices or for merely local favors and concessions, they should vote with their eyes fixed upon the international problems of the color line and the national problems which effect the Negro race in the United States. Only independent votes for candidates who will carry out their desires regardless of party will bring them political and economic freedom. 

The economic situation of American Negroes is still precarious. We believe that along with their entry into industry as skilled and semi-skilled workers and their growing ownership of land and homes they should especially organize as consumers and from co-operative effort seek to bring to bear upon investors and producers the coercive power which co-operative consumption has already attained in certain parts of Europe and of America. Lynching, segregation and mob violence still oppress and crush black America but education and organized social and political power begin to point the way out.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

*Other Peoples*

Upon matters that lie outside our own problems, we must also express our thought and wish because the narrow confines of the modern world entwine our interests with those of other peoples. We desire to see freedom and real national independence in Egypt, in China and in India. We demand the cessation of the interference of the United States in the affairs of Central and South America. 

We thank the Soviet Government of Russia for its liberal attitude toward the colored races and for the help which it has extended to them from time to time.

We urge the white workers of the world to realize that no program of labor uplift can be successfully carried through in Europe or America so long as colored labor is exploited and enslaved and deprived of all political power.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

A committee to call a Fifth Pan-African Congress and to present to it a plan of permanent organization was appointed. It consisted of Dr. W. E. B. Du Bois, chairman, Mrs. A. W. Hunton, M. Dantes Bellegarde, Mr. H. H. Phillips, Mr. Rayford W. Logan, Mr. F. Eugene Corbie, Mr. Otto E. Huiswoud, Mrs. B. Cannady and Bishop R. C. Ransom. This committee has power to enlarge its number. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Memorandum to M. Diagne and Others on a Pan-African Congress to be held in Paris in February, 1919 (1919)](/Volumes/17/05/memorandum_to_m_diagne_and_others_on_a_panafrican_congress.html)
* [Pan-Africa (1921)](/Volumes/21/05/pan-africa.html)
* [Robert R. Moton (1919)](/Volumes/18/01/robert_moton.html)
* [Patient Asses (1930)](/Volumes/37/03/patient_asses.html)
* [Inter-Racial Comity (1922)](/Volumes/22/01/inter-racial_comity.html)

<!-- Similar articles end here -->