
---
title: 'Wallace Battle, the Episcopal Church and Mississippi: A Story of Suppressed Truth'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Oct. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 8
  page: 261--262, 282--283
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



May 20, 1925, was commencement day at Okolona Institute. This is a colored school, supported by the Episcopal Church, in northeastern Mississippi, in and near a small Mississippi town of four thousand inhabitants. The plant is valued at about a quarter of a million dollars and the school has been established twenty-five years. The Governor of the state, H. L. Whitfield, was expected to speak on this occasion. The Episcopal Bishop of Mississippi was to be present and many white and colored notables. 

Early in the morning, Ulysses S. Baskin, a graduate of the school and of Tuskegee, a world war veteran and for seven years superintendent of mechanical industries, was milking in the pasture ten rods from his home. He saw a white man looking about the pasture, who quickly disappeared. After he had turned his cow back to the pasture and started home, two white men, H. Anderson and his son, came from behind the trees and told him to stop. They asked if he knew anything about the killing of their dog. Mr. Baskin replied that a week before, three dogs had gotten into the pasture and killed a goat. He had shot at the dogs and killed one. The men said that they did not want an explanation; that they wanted to know if he killed the dog. Baskin repeated his story saying he did not know whose dogs they were, but if they were theirs he was ready to adjust the matter to their satisfaction. Immediately the two men shot him eight times, on the side of the head and in Baskin's left thigh. All this was plainly seen by two colored men, by Baskin's wife and by several visitors and teachers at the superintendent's house. The superintendent lived two days after he was shot and then died leaving a widow, three children and a fourth born after his death. The Andersons took the pistol which they found on him with them and went home.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

There seems to be no dispute about the above facts. They have been well known to the authorities of the Episcopal Church and to the trustees of the school. The story of the conversation is from Baskin's antemortem statement. Of his death from the gun shot wounds by the Andersons there is no question. 

Wallace Battle, founder and principal of the school, demanded the arrest of the Andersons. The Grand Jury was about to adjourn, but was held over for a day and the Andersons were arraigned before it. Not a single witness appeared against them. The only witnesses at the trial were the Andersons themselves. Their story was that when they asked Baskin about their dog, he drew a revolver and shot at them twice and that they killed him in self-defense. They had handed Baskin's revolver with two cartridges exploded to the chief of police after the murder. They were freed and have not been arrested since. 

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

Wallace Battle has at various times and in various places declared that the above facts are by no means the whole of the story; that the Andersons had a bad reputation and had been in shooting scrapes before and had at least one other murder to their credit; that there were witnesses to the murder of Baskin, colored and white, but that the mob spirit was such in the town, and the feeling against a school for Negroes so strong, that these witnesses dare not testify; that the shooting was a merciless assassination for which no possible excuse could be given; that after the elder Anderson had shot this teacher to death he took from Baskin's pocket a revolver from which no shells had been fired, carried it into the Anderson's garden and within the sight of a white lady, fired two shots so as to make it appear that their story of self-defense was creditable. 

Mr. Battle declares that for some time he had seen the mob spirit forming in Okolona. He believes that seventy-five per cent of the white people of the town and vicinity are his firm friends. Many white people say that Battle was the best loved Negro in Mississippi. White Mississippians have given money to the school; have acted upon the Board of Trustees; and have on many occasions, protected the institution.

But these friends find themselves helpless apparently before the other twenty-five per cent, consisting of some poor, illiterate whites, some rich men, some preachers and politicians who were determined the school should go. Mr. Battle declares that twice recently his own life has been threatened and that once he strongly suspected an effort to burn down the school. With his wife and family he was once waylayed in August, 1924, by an automobile full of white men who went by him at great speed and then blocked his road. He escaped by backing his car and fleeing to his campus at the rate of fifty miles an hour. Two weeks later, on a public street opposite the post office, this same H. Anderson stopped Battle and threatened to kill him if he approached the mayor about the case of a Negro whom Anderson had nearly beaten to death. Battle offered to prove that he had said nothing to the mayor about the matter by going with Anderson to the mayor. He afterward tried to get the trustees to take up the matter, but they thought it best to let it die down. 

In March, white Mississippi ladies planted two magnolias on the highway in front of the campus. In May these magnolias were pulled down and one of the gate posts of the campus injured. On Tuesday night, May 19, just before commencement the water supply of the school was cut off. Then came the tragedy of commencement day. 

Wallace Battle, the principal of the school, declared that if these murderers were to go unpunished or if at least they were not compelled to leave town, he could not continue to remain as head of Okolona Institute. 

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

To realize just what this statement meant, one must know something of Wallace Battle. To American Negroes, Battle represents the extreme type of the so-called "white folk's nigger"; but he was undoubtedly sincere about it. He believed in Southern white people; he believed that their hearts were in the right place; he believed that if a Negro tried hard and did his duty he had nothing to fear from the Southern mob; or if he was threatened with mob violence and had the right sort of reputation and friends that the good white people would come to his defense. Battle thought that he had proven his thesis by establishing and maintaining the school at Okolona. There was bitter opposition at first against such a Negro school, but it had been overcome and few colored men stood so high in any Southern community as Wallace Battle. He was a clean, honest, sincere man, but Negroes considered him lacking in backbone and self-assertion. They accused him of going out of his way to condemn black men who stood up for manhood rights and to excuse the South on every occasion. Battle was one of those who criticized the Booker Washington luncheon at the White House and recently condemned Tuskegee for her determination to maintain the great Government hospital with black employees. Battle certainly served the white people well and in turn they helped him.

To Battle this sudden and wanton murder of his friend and employee came as a terrible blow. He demanded justice and confidently expected it. He expected the best elements of the white community and the whole church to stand back of the demand that these murderers be arrested and punished. When this seemed improbable he demanded that at least public opinion should compel their withdrawal from the community and when slowly it began to dawn upon him that nothing was going to be done, he declared that if this were the case he could no longer serve as principal of Okolona. 

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

In the meantime, it looked as though the church was up in arms about this outrage. Prominent officials considered this murder as not simply the killing of an individual, but as a wanton affront to the Episcopal Church, to education and to civilization in Mississippi. They determined to demand redress. If it was impossible to secure the legal punishment of the Andersons it was proposed that the church make an open and clear appeal to the civilized world. They determined to ask the white president of the Board of Trustees, Captain A. T. Stovall of Okolona, to arrange for a mass meeting of the citizens of Okolona so that representatives of the church and of the school could lay the matter frankly before them and ask them to take action. Beyond this, they proposed to appeal to the whole church. It happened that the General Convention of the Episcopal Church was to be held in New Orleans in the fall of 1925. The argument for bringing the convention to New Orleans was that the North and West would thus be able to learn more of the South. Wallace Battle was on the program to speak of educational efforts among Negroes. It was proposed that Mr. Battle tell the church and the world the story of the murder of Baskin by the Andersons and of the failure of the state of Mississippi to punish the murderers. 

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

Further than this, friends of Okolona and of the National Association for the Advancement of Colored People appealed to the Association to take legal steps. One distinguished citizen of Philadelphia wrote: "In my judgment the only way to stop such horrible outrages . . . is by sending a resolute and trained man or woman to the spot getting the evidence and then trying to secure convictions, to be followed by the infliction of extreme penalty of the law. We could not have better cases to work upen. If you take up these cases with the same vigor and discretion that you showed in other like cases you will probably put a stop forever to such lynchings. I have, unfortunately, no money to spare, but I will help you in any other way I can. I think you and your organization are doing a splendid and much needed work. I would not for a moment consider that time-serving X----- of the Okolona School. I have letters from Superintendent Battle that will start you finely in your God-given work at any rate."

Our legal committee began to look into the matter when suddenly they received another letter from Philadelphia saying that: "It is urged that any airing of such a matter would immediately bring down upon the colored people who run this school the wrath of the surrounding white neighbors. When I wrote to Mr. Battle asking him why he had not fulfilled his promise I learned from him that his Board of Trustees had refused to allow him to say anything in the matter." 

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

Meantime, what had happened? The officers of the Church Institute had set forth their plan of protest and publicity. The Bishop of Mississippi and the Presiding Bishop of the Church had consented to it. Many others had expressed strong sympathy, but Captain Stovall of Okolona had strongly disagreed. He refused to call the local meeting but arranged for a meeting at Memphis where the Bishop of Mississippi, Mr. Bolton Smith, Mr. Wallace Battle and others were present. Captain Stovall insisted that this was not a clear case of race hatred or of enmity to the school; that Baskin was armed; that no witnesses had appeared against the murderers. He persuaded the members of the Council that it was a sign of guilt for a black man in Mississippi, protecting his flocks from dogs and himself from something worse, to carry a pistol. He persuaded them to assume that the absence of witnesses was not a proof of any mob spirit in Okolona, but simply because there really were no witnesses; and he told Wallace Battle that he believed Battle's mind to be a little unhinged by the sad event and advised him to take a vacation.

With such pressure put upon him, Battle backed down, shut his mouth and went off on a vacation. He spoke later at the church Convention but said nothing about the murder. At the end of the vacation he went back to the school and tried to work but he was still so upset that he could not stay. He finally and definitely resigned July 20, 1927, saying: "I have now finished twenty-five years at Okolona with the most sympathetic and lovable Board of Trustees in the world. In this I am including all former members of the Board—Messrs. Walter McDougall, Edwin R. Embree and others, including the late Dr. Joseph French Johnson, Messrs. George W. Cable, Phil McIntosh, Moses Williams and B. J. Abbott.

"My calm and deliberate judgment, after prayers and tears, is that a quarter of a century completes my task at Okolona. I, therefore, in final decision tender my resignation to take effect at once."

This for the public; but in a private letter to a friend, which we have seen, he adds: *"I found that I was stifling in the South!"* 

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

Where now is the real trouble in this astonishing case of murder and the practical suppression of all publicity concerning it for nearly two years? It lies in the fact that the Episcopal Church is at a serious disadvantage when it tries to deal with the Negro problem. It is the one great church in America which did not split on the subject of slavery. Often it boasts of this fact; and unity is a thing to boast of. Nevertheless this very fact of union spells paralysis on the Negro problem. The Episcopal Church, although the richest in the United States and the first Protestant church among Negroes, has done least for the Negro in America. It has repudiated all efforts to increase its Negro membership and it has until recently supported few Negro schools. Whenever Episcopalians try to take a high moral stand on any phase of the race problem they find themselves blocked by their Southern white constituents.

This does not mean that the white Episcopal South believes in lynching, mob violence and ignorance for Negroes. It does mean that these Southern white churchmen still cling to the old idea of speaking for Negroes and working for them and preventing all self-assertion on their part. They still refuse to permit any criticism of the action of the white South toward Negroes and they are determined to pretend that Southern civilization in its attitude toward black folk is the best in the United States if not in the world.

When now the church faces such an episode as the Okolona murder it suffers moral paralysis. This murder in broad daylight was an affront to the Episcopal Church as well as white civilization and the acquittal of the murderers for lack of evidence in the face of that cold dead corpse was an outrageous travesty on justice. The pretense of self-defense was shameless. Despite this every pressure has been brought to bear by the officials of the Episcopal Church; first, to keep the facts of this case from being known; second, to keep them from being published; third, to keep any outside person or organizations from trying to secure justice or publicity; fourth, to compel Battle to keep silent and to induce him to go back to his work at the school.

<span class="small-caps">The Crisis</span> in its endeavor to tell a straight, unvarnished tale has submitted this article to the persons chiefly concerned, except Wallace Battle. They have all agreed that nothing should be published. What do you think, Gentle Reader? 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The White Church (1917)](/Volumes/14/01/white_church.html)
* [The Tragedy of ''Jim Crow'' (1923)](/Volumes/26/04/tradgedy_of_jim_crow.html)
* [Crime (1918)](/Volumes/15/05/crime.html)
* [The White Primary (1911)](/Volumes/01/05/white_primary.html)
* [Peonage (1927)](/Volumes/34/09/peonage.html)

<!-- Similar articles end here -->