
---
title: 'A Quarter Million'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 21
  issue: 5
  page: 213
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Year before last the N.A.A.C.P. counted 90,000 members; last year because of the assault on our secretary in Texas and the post-war slump in all united effort we had about 88,000 members. This year, recovered and alive, with a new secretary and new assistants, with our hands so full of work and the field so ripe for harvest that we scarcely know where to begin, we are launching a spring drive. We are going to find 250,000 red-blooded black and white men and women who believe in freedom and in the methods which we have proven worth fighting with.

If you belong to us, renew your membership now and bring a brother. If you have been sitting on the sidelines, cheering, get into the game. If you have been standing outside criticizing and doubting and hesitating, read our record printed in these pages, and get busy. Do something. Join us! Help us! We have not all the wisdom, but we have some. We have not yet created a new heaven and a new earth, but we have done more than talk and gesticulate. Members of the N.A.A.C.P. pay from $1 to $10 or more a year.

<span class="small-caps">The Crisis</span> costs $1.50 a year. Spend at least $2.50 now on freedom for your children.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Help Us to Help (1918)](/Volumes/16/04/help_us.html)
* [Thirteen (1918)](/Volumes/15/03/thirteen.html)
* [The Congressmen and the NAACP (1914)](/Volumes/09/02/congressmen_and_the_naacp.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Of Cold Feet (1921)](/Volumes/22/05/of_cold_feet.html)

<!-- Similar articles end here -->