
---
title: 'Bleeding Ireland'
author: Du Bois, W.E.B.
date: Mar. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 21
  issue: 5
  page: 213
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



No people can more exactly interpret the inmost meaning of the present situation in Ireland than the American Negro. The scheme is simple. You knock a man down and then have him arrested for assault. You kill a man and then hang the corpse for murder. We black folk are only too familiar with this procedure. In a given city, a mob attacks us unprepared, unsuspecting, and kills innocent and harmless black workingmen in cold blood. The bewildered Negroes rush together and begin to defend themselves. Immediately by swift legerdemain the mob becomes the militia or a gang of "deputy sheriffs". They search, harry and kill the Negroes. They disarm them and loot their homes, and when the city awakes after the "race riot", the jail is filled with Negroes charged with rioting and fomenting crime!

So in Ireland! The Irish resist, as they have resisted for hundreds of years, various and exasperating forms of English oppression. Their resistance is called crime and under ordinary conditions would be crime; in retaliation not only the "guilty" but the innocent among them are murdered and robbed and public property is burned by English guardians of the Peace!

All this must bring mingled feelings of dismay to Irishmen. No people in the world have in the past gone with blither spirit to "kill niggers" from Kingston to Delhi and from Kumassi to Fiji. In the United States, Irish influence not only stood behind the mob in Cincinnati, Philadelphia and New York, but still stands in the American Federation of Labor to keep out Negro workingmen. All this contains no word of argument against the ultimate freedom of Ireland---which God speedily grant!---but it does make us remember how in this world it is the Oppressed who have continually been used to cow and kill the Oppressed in the interest of the Universal Oppressor.

