
---
title: 'Scottsboro'
author: Du Bois, W.E.B.
date: Jan. 1934
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 41
  issue: 1
  page: 21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Some one sat in our office the other day and said "why doesn't <span class = "small-caps">The Crisis</span> say more about Scottsboro?" and I answered, "Why indeed!" There are some things so painfully obvious, that it seems almost futile to write words about them. Lynching is an unspeakable blot upon America. We are the only nation in the civilized world that burns human beings alive as a public spectacle. And yet beyond this is a national habit and custom which is far worse, and that is the using of the legal processes of law for profit and prejudice and revenge. It is doubtful if a single person in the United States including the judge and jury in Alabama, has any thought that the black victims who are being tried at Scottsboro, have committed any crime that deserves punishment. Nevertheless, they have already been terribly punished and they are going to be further punished. They are going to be punished because an uncivilized community and a brutal judicial system cannot do anything else and be true to its past history and its present constitution. The State of Alabama, together with most of the states of the Southern South, for fifty years has invested in crime. They have used crime for private profit. They have bought and sold criminals. They have built their prosperity and private fortunes upon a treatment of the unfortunate which is contemptible, and in addition to this they have tried through their treatment of Negroes, to satisfy the blood lust of a sadistic people. They are going to continue this. They are going to continue it until the South becomes civilized, and no one living is going to see that day.

