
---
title: 'Dodging the Issue'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 2
  page: 45-46
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The  only comment which the Atlanta Commission on Interracial Cooperation has on the tragedy of the share-croppers of Alabama is a quotation from a Negro newspaper against "militant resistance":

> Interviews with representative Negro leaders here and in Alabama reveal the fact that they are in complete agreement with the views expressed. Being a minority group in numbers, resources, and power, the Negro has nothing to gain by violence, they hold, but, on the contrary, everything to lose, including his life. What is even more tragic, they point out, is the fact that violence inevitably brings suffering and peril to multitudes in no way responsible. They believe communist organizers are seeking to use the Negro merely as a fagot to light the fires of political revolution, and that Negroes should be too wise to let themselves be sacrificed.

 This is a pitiful dodging of the issue. When in God's name did American Negroes need to have non-resistance preached to them?

The point that the decent white South must face is: How long is the sheriff's posse, recruited from the white mob, going to be permitted to be the willing and pliant tool of Southern Capital, Credit, Extortion and Graft? And how long are black men going to be shot in the back running for the "crime" of defending their own homes against legal thieves and marauders?

What has this elementary matter of simple justice and decency to do with Communism or Methodism or the Integral Calculus? Why dodge and hide behind Russia every time a cowardly Southern mob kills a black man? I believe in Peace. I shudder at Revolution. But when in 1906 the Atlanta mob began killing Negroes wholesale, I went and bought a repeating shot-gun and loaded it with buckshot. I have got it yet.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [The Liberal South (1921)](/Volumes/21/06/liberal-south.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [The Immediate Program of the  American Negro (1915)](/Volumes/09/06/immediate_program.html)
* [Southern Papers (1911)](/Volumes/01/04/southern_papers.html)

<!-- Similar articles end here -->