
---
title: 'It is a Girl'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 2
  page: 45
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Anent my December editorial one writes:

> A daughter, our only child in seven years of marriage was born December 9th. My wife read your editorial so many times in the last week before going to hospital that she had memorized most of it. Both of us thank you, and wish for you long years of happiness.

I am minded, therefore, to add: Do your friends all say. "Too bad it wasn't a boy?" If they do, listen and reply:

The ancient idea that boys are intrinsically and naturally better than girls is a relic of barbarism that dies a hard death. We must, however, insist on reminding ourselves that the idea is uncivilized and pre-historic and rooted in a day when women were owned and men their owners by force or theft. Many things still remind us of that stage of culture: the loss of a woman's name by her marriage; the persistent idea that a married woman should not have a career; and the older opposition to woman suffrage. In other words, the continued inferiority of women in work and wage and certain phases of social esteem is at the bottom of this supposed preference for boy children. And this is especially pronounced among primitive and ignorant people.

On the other hand there are certain distinct advantages in girls. They contribute to the home, in the first ten or fifteen fateful years, far more than boys. They become the intimate and loving part of its organism, its work and play and decoration. They are educated and trained in the home by parents and chosen guests, while the boy, despite every effort, gets his chief training on the streets and even in the gutter. The girl stays tame while the boy wanders wild and even in the re-creation of life, it is the Mother not the Father who counts most and this all ancient civilizations---Egypt, India and West Africa---knew.

Be glad it's a girl and make life wider and safer and more equal in burden for all girls because of this one.

