
---
title: 'Our Health'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 2
  page: 44
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Our death rate is without the slightest doubt a death rate due to poverty and discrimination.

What little racial factor is present is too small to be taken into account. The scientific validity of such studies is utterly vitiated by ignoring not only the social condition and environment of those measured, but by classing all persons of Negro descent as belonging to the "Negro" race no matter what their percentage of white or Indian blood. Moreover, the majority of such "scientists" has been distinctly prejudiced and determined to prove an already assumed case.

As a problem of poverty our death rate can ultimately be brought down to normal size only as our income is increased. There are no reliable figures as to the average income of Negro families but it is certain that their average is far below the minimum which social agencies have from time to time established. What shall we do about our low wage? Our inadequate income?

Meantime, there are certain matters we can stress even in our poverty:

1. Fresh air.
2. More nourishing food with less hot bread and fried greasy meat; with more vegetables, eggs, milk and greens.
3. Cleanliness in body and in crowded homes; in clothes.
4. Sleep, adequate in length and quiet.
5. The systematic use of physicians, dentists and hospitals; not simply to recover from disease but to prevent illness; especially the use of hospitals for births, severe illnesses and necessary operations.

On the other hand, an improvement in our present habits with regard to air, sleep, food, clothes and medical attention, and even increased income will not entirely settle our problem of sickness and death, so long as race discrimination continues on the lines in which we see it today. Even for those of us who are able to pay, hospital doors are today half-closed in our faces; parks, swimming pools and recreation centers often will not admit us; projects for improved housing seldom include us; and available food supply, particularly in cities, is vitiated by the custom of dumping the worst food at the highest prices into Negro districts; and police and sanitary control of our dwelling districts is universally neglected.



Finally, there can be no doubt that the atmosphere of discrimination and insult and dislike acts as a general depressant, particularly on the young people of the Negro race. In such competitions as the Atwater-Kent auditions and the national oratorical contests and the competitions for scholarships and prizes, Negroes are continually made to realize that merit with a dark skin has great difficulty in winning. The resultant inferiority complex and even counsels of despair make for lack of stamina and resistance. 

Here, then, is our problem: Better *income*; better *use* of our present income; a frontal act upon *race discrimination* and a gospel of *defiant hope*.

