
---
title: 'Little Portraits of Africa'
author: Du Bois, W.E.B.
date: Apr. 1924
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 27
  issue: 6
  page: 272-274
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



## The Place, The People

Africa is vegetation. It is the riotous, unbridled bursting life of leaf and limb. It is sunshine---pitiless shine of blue rising from morning mists and sinking to hot night shadows. And then the stars--- very near are the stars to Africa, near and bright and curiously arrayed. The tree is Africa. The strong, blinding strength of it---the wide deep shade, the burly lavish height of it. Animal life is there wild and abundant---perhaps in the inner jungle I should note it more but here the herb is triumphant, savagely sure---such beautiful shrubbery, such splendor of leaf and gorgeousness of flower I have never seen.

And the people! Last night I went to Kru-town and saw a Christmas masque. There were young women and men of the color of warm ripe horse chestnuts, clothed in white robes and turbaned. They played the Christ story with sincerity, naiveté and verve. Conceive "Silent Night" sung in Kru by this dark white procession with flaming candles; the little black mother of Christ crossing with her baby, in figured blue, with Joseph in Mandingan fez and multi-colored cloak and beside them on her worshipping knees the white wreathed figure of a solemn dark angel. The shepherds watched their flocks by night, the angels sang; and Simeon, raising the baby high in his black arms, sang with my heart in English Kru-wise, *"Lord now lettest thou thy servant depart in peace for mine eyes have seen thy salvation!"* 

Liberia is gay in costume---the thrifty Krus who burst into color of a holiday; the proud Veys always well-gowned; the Liberian himself often in white. The children sometimes in their own beautiful skins. 

## Sunday, January 13, 1924 

I have walked three hours in the African bush. In the high bush mighty trees arose draped, with here and there the flash of flower and call of bird. The monkey sentinel cried and his fellows dashed down the great tree avenues. The way was marked---yonder the leopard that called last night under the moon, a bush cow's hoof; a dainty tread of antelope. We leaped the trail of driver ants and poked at the great houses of the white ants. The path rose and wound and fell now soft in green glow, now golden, now shimmery through the water as we balanced on a bare log. There was whine of monkey, scramble of timid unseen life, glide of dark snake. Then came the native farms---coffee, cocoa, plantain, cassava. Nothing is more beautiful than an African village---its harmonious colorings---its cleanliness, its dainty houses with the kitchen palaver place of entertainment, its careful delicate decorations and then the people. I believe that the African form in color and curve is the beautifulest thing on earth; the face is not so lovely---though often comely with perfect teeth and shining eyes,---but the form of the slim limbs, the muscled torso, the deep full breasts! 

The bush is silence. Silence of things to be, silence vocal with infinite minor music and flutter and tremble---but silence, deep silence of the great void of Africa. 

And the palms; some rose and flared like green fine work; some flared before they rose; some soared and drooped; some were stars and some were sentinels; then came the ferns---the feathery delicate things of grottos and haunts with us, leapt and sang in the sun---they thrust their virgin tracery up and out and almost to trees. Bizarre shapes of grass and shrub and leaf greeted us as though some artist all Divine was playing and laughing and trying every trick of his bewitched pencil above the mighty buildings of the ants. 

I am riding on the singing heads of black boys swinging in a hammock. The smooth black bodies swing and sing, the neck set square, the hips sway. O lovely voices and sweet young souls of Africa! 

## Monrovia

Monrovia is a city set upon a hill. With coy African modesty her face is half turned from the bold and boisterous ocean and her wide black eyes gaze dreamfully up the Stockton and St. Paul. Her color is white and green and her head of homes rises slowly and widely in spacious shading verandah toward the great headland of Mesurado where the lighthouse screams to wandering ships. Her hair is plaited decently on mighty palm leaves and mangoes; her bare feet, stained with travel, torn with ancient cicatriced wounds drabble in the harbor waters down on Water Street and shun the mud town Plymouth Rock which is Providence Island. Her feet are ugly and old, but oh her hands, her smooth and black and flying hands are beautiful and they linger on roof and porch, in wide-throated grassy street and always they pat and smooth her hair, the green and sluggish palms of her heavy beautiful hair. And there is gold in her hair. 

## Africa

The spell of Africa is upon me. The ancient witchery of her medicine is burning my drowsy, dreamy blood. This is not a country, it is a world---a universe of itself and for itself, a thing Different, Immense, Menacing, Alluring. It is a great black bosom where the Spirit longs to die. It is life so burning, so fire encircled that one bursts with terrible soul inflaming life. One longs to leap against the sun and then calls, like some great hand of fate, the slow, silent crushing power of almighty sleep---of Silence, of immovable Power beyond, within, around. Then comes the calm. The dreamless beat of midday stillness at dusk, at dawn, at noon, always. Things move---black shiny bodies, perfect bodies, bodies of sleek unearthly poise and beauty. Eyes languish, black eyes---slow eyes, lovely and tender eyes in great dark formless faces. Life is slow here. Impetuous Americans quiver in impetuous graves. I saw where the ocean roars to the soul of Henry Highland Garnet. Life slows down and as it slows it deepens; it rises and descends to immense and secret places. Unknown evil appears and unknown good. Africa is the Spiritual Frontier of human kind---oh the wild and beautiful adventures of its taming! But oh! the cost thereof---the endless, endless cost! Then will come a day---an old and ever, ever young day when there will spring in Africa a civilization without coal, without noise, where machinery will sing and never rush and roar, and where men will sleep and think and dance and lie prone before the rising sons, and women will be happy. 

The objects of life will be revolutionized. Our duty will not consist in getting up at seven, working furiously for six, ten and twelve hours, eating in sullen ravenousness or extraordinary repletion. No---We shall dream the day away and in cool dawns, in little swift hours, do all our work.

_____
*Citation:* Du Bois, W.E.B. 1924. "Little Portraits of Africa." *The Crisis*. 27(6):272&ndash;274.