
---
title: 'Schools'
author: Du Bois, W.E.B.
date: Jan. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 13
  issue: 3
  page: 111-112
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



What is to become of the secondary and higher Negro schools that are
not smiled upon by the ring of rich
philanthropists represented by the General Education Board and like
agencies? These excluded schools are undoubtedly in many cases poorly
equipped and indifferently managed. At the same time they are doing and
have done the real work of the education of the Negro race. Their
accomplishment both in volume and in real efficient result has been ten
times that of Hampton and Tuskegee Institutes for the simple reason that
they outnumber these schools 100 to 1 and deal with by far the greater
number of the children of ten millions.

Instead then of being sneered at and discouraged, they ought to be
encouraged, and it is little less than a shame that the United States
government with the aid of Thomas Jesse Jones is (as we are assured)
about to issue a definitive report recommending all sorts of things
tending to extinguish these struggling institutions.

We are glad, however, that the National Training School, of Durham,
North Carolina, despite this handicap, has paid her debt and has just held a conference of far-reaching
importance on the subject of Negro education. Representatives of
Negroes, South and North, and of white men, North and South, were on the
program and all the visitors were firmly impressed with the wide
influence of this school as a center of good work and with the
indefatigable work of her president.

In the same way Atlanta University, long frowned upon because she
persistently stood for the bigger things, is trying to raise on her
fiftieth anniversary, a fund of $500,000. No school in the South has
done a work for Negro uplift that can for a moment be compared with that
of Atlanta University.

Fisk University, which has fortunately reached the edge of the approval
of Organized Philanthropy, asks for a conservatory of music in memory of
the Fisk Jubilee Singers. The response to this appeal should be
immediate and generous and should come from black people and white.
We must rally to the defense of our schools. We must repudiate this
unbearable assumption of the right to kill institutions unless they
conform to one narrow standard.

