
---
title: 'The Single Tax'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 6
  page: 248
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Negro radicals com­paratively little has been said of the Single Tax, and we take it that few of our colored readers know much of Henry George's "Progress and Poverty" and its after­ math. There are, however, many signs that the economic thought of the world is turning increasingly to­ ward this rather awkwardly named method of righting economic wrong. The basic thought which Henry George and his followers laid for the world was that the sum of economic villanies is monopoly and that monop­oly always in the last analysis rests on the land and the produce of land; that so long as it is possible and legal to own land, to own mines, to own oil wells, to own "rights of way," it will be possible to lay upon the pub­ lic an enormous tax which labor must pay and which will in the end defeat democracy.

None can doubt but that this is true. They may doubt if the single and simple expedient of a tax on land values will remedy the growing difficulty, but even this is arguable. At any rate, monopoly of land and its products is the most sinister thing that faces modern industrial progress the rise of laboring classes, and the emancipation of the Darker World.

