---
title: 'Thomas Jesse Jones'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Oct. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 6
  page: 252-256
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

Thomas Jesse Jones was born in Wales, in 1873, and came to America when he was 11 years old. He was educated in Virginia, Ohio, and New York, and received the degree of Doctor of Philosophy from Columbia in 1899. He has been a social settlement worker, a teacher in Hampton Institute, a statistician in the United States Census Bureau, and at present he is Director of Research of the Phelps-Stokes Fund.

Mr. Jones' career would call for no special notice were it not that it illustrates in a peculiar way the present transition period of the Negro problem.

For many years after the Civil War, the Negro as a matter of fact could not "come into court"---that is, into the organized life and customs of the world of politics and culture---unless he was represented by some white man who vouched for his character and undertook a certain responsibility for his actions. This was, of course, the old Roman idea of the patron and client and out of this it has been the determined effort of the free Negro to work until he could appear *in propria persona*, speaking for himself and being recognized on his individual merits.

At first these pretensions were utterly denied despite the letter of the law. Afterward they were admitted only in case the Negro who was recognized as spokesman should say, on the whole, the things that the white community wanted him to say. It was by this path that the late Booker Washington rose to his pre-eminence and secured so great an influence that he could at times speak independently for the Negro. On the whole, however, he had to say what the white South allowed him to say. Since his death, there has been no Negro spokesman whom the white South could trust to voice its demands for the Negro and the result is that unconsciously it has reverted to the older idea, that the spokesman must be a white man and that all real power over the Negro group must be in the hands of white men.

It was during this time of development that Mr. Thomas Jesse Jones came upon the stage. When he went to Hampton, in 1902, he had an opportunity to meet and become personally acquainted with an unusually large number of colored leaders of all types. His settlement training led him to take advantage of this opportunity and his natural gift for securing the confidence of men increased his opportunities. For a long time he was looked upon as a sympathetic white man who had unusual and minute knowledge of the current inner gossip of the Negro world. It was also felt by most of us that he sympathized with the aspirations of Negroes for leadership and self-determination rather than with the idea of a close-corporation of guiding philanthropists, which was dominant at Hampton.

Then gradually there came a change as Mr. Jones left Hampton, in 1909, and began to cast about for other work. Just what the reason of the change was, is not clear. Perhaps Mr. Jones lost confidence in colored leadership and did not believe that colored men could ever guide themselves out of their present wilderness. Perhaps, on the other hand, the pressure from the white South and the white North, upon a man in Mr. Jones' position, was too strong, and he found that if he was willing to make terms with them and get a chance to work at the Negro problem, he must first of all assent to the proposition that Negroes must be kept from the leadership of their group; that to allow them to lead was ineffective if they were incompetent and dangerous if they were competent, because in the latter case no matter how reasonable their demands from the point of view of a white race, they could not for a moment be admitted in the case of a colored race.

It does not matter greatly by which of the paths above indicated Mr. Jones came to his conclusion. The point is that he did come to the place where he definitely and persistently began to work so as to displace Negro leaders, and gather into his own hands such an amount of information and power as would gradually give him the position of arbiter and patron of the Negro race in America.

I do not for a moment suppose that this plan was clear in Mr. Jones' mind at first, but certainly more and more in the last 12 years he has worked toward it. The proof of this lies in several incidents, which may be here adduced:

A) *The Y.W.C.A.* About 1917, a grave problem of procedure had come to a head in the National Y.W.C.A., and that was the question as to how far the colored local branches of the Y.W.C.A. were to be responsible to the city and state organizations in the South. To put them on the same plane of responsibility as the white organizations meant that they would be ruled by the white South and that they would not be allowed adequate representation on the ruling boards. On the other hand, if they were made special cases this would mean the building up of a colored organization from top to bottom, as is the case in the Y.M.C.A. The Y.W.C.A. hesitated between these two extremes, regarding the latter alternative as a complete surrender to color caste, and hoping to secure just recognition and representation in the South. The result was that they had a partly colored organization, with a colored secretary at National Headquarters who was practically in charge of the city Y.W.C.A.s in the South, and who sent out traveling secretaries to student bodies.

    At Louisville, in 1917, for some unknown reason Mr. Jones was brought in as arbiter. He immediately recommended that the colored woman who was at the head of the colored work in the national organization be displaced and that in her stead a white woman be appointed. He gave the impression that he favored in this and in other cases always the appointing of white persons to places of authority and the bringing in of colored persons as their helpers and assistants. His recommendation in this case raised such a cloud of opposition that the advice was not followed and he seemed to acquiesce.

B) *The investigation of colored schools.* Meantime, Mr. Jones had become an employee of the Phelps-Stokes Fund and a nominal expert in the United States Bureau of Education. The Phelps-Stokes Fund was established by the bequests of two gentle ladies who for years had given to Negro education and who wanted to perpetuate this help. The trustees of the Fund, however, conceived that the best help for the Negro in the South was to secure the greatest amount of co-operation between the races; and beyond this they gradually took the position that co-operation between the races meant the doing of what the white people demanded. They, therefore, established fellowships in white colleges to study the Negro problem but made no attempt to do similar work in colored colleges, and they started Mr. Jones on his investigation with the assumption that there was a great deal of begging for funds for Negro education which was unjustifiable.

    Of the general results of Mr. Jones' investigation <span class="crisis-title">The Crisis</span> has already spoken, but one point must here be emphasized, and that is that almost without exception Mr. Jones' report took the stand that Negro education directed by Negroes was a failure and that Negro education to succeed must be directed by white people. In one or two cases he went so far as to take a high hand and order a colored president to resign if he wished his school to receive any favorable report, and in many other cases he caused especial astonishment and chagrin among his numerous colored friends because of the singular way in which he treated their educational work.

C)  *The Y.M.C.A.* The Y.M.C.A. had gone to the extreme position of separating absolutely colored and white work and putting the colored work in the hands of a strong corps of secretaries who had their headquarters with the National Board.

    While this arrangement was not ideal because it recognized color caste in Christian work---a contradiction in terms---notwithstanding it did at least give the colored people a voice in their own government and the result was an astonishing and gratifying growth in the colored Y.M.C.A. When the war came and the United States entered, Mr. Jones rather suddenly went into this field and before the colored secretaries realized it, the question of the personnel of colored men who were to be appointed to represent the Y.M.C.A. overseas was being referred to Mr. Jones by the white heads of the Y.M.C.A. He was selecting men, rejecting others, and tendering advice in all directions. His advice was usually followed without reference to the colored secretaries.

    When the colored secretaries protested, some form of recognizing their authority was instituted; but in the six months before the Armistice and afterward, Mr. Jones was practically in control of the selection of colored secretaries abroad. He went abroad himself, ostensibly for the Y.M.C.A., but did no especial work. He kept his eye on the colored troops, accompanied Dr. Moton closely on his trip, and was in cable communication with the Y.M.C.A. headquarters, who referred to him questions which ought to have gone to the Colored Department for decision.

D) *The American Negro in Africa.* One of the great ideals gradually shaping itself in America is that American Negroes have before them the duty of helping to civilize and redeem Africa. This was first felt among the churches and for more than 50 years a few missionaries, representing colored churches, have been working in Africa. Recently, however, the movement has taken broader shape and it was given its greatest and most interesting impetus by the work of Mr. Max Yergan, in East Africa, in 1916. The work of this young colored man of fine character, college training and unusual ability, has thus been characterized in a previous <span class="crisis-title">Crisis</span> article:

    > One night in May, 1915, the National Secretary of War Work in the Far East made an appeal for 40 men to go into parts of the world where soldiers were fighting, surrounded with every conceivable danger to men known to man. The reward for service offered them was most likely a body broken with disease and maybe death. However, the tremendous needs made the challenge attractive to redblooded men. Max Yergan, the youngest member of my staff, student secretary from the Southwest, a graduate of Shaw University, only 25 years old, strong, courageous, devout, faithful in caring for every detail of responsibility entrusted to him, heard that call and went out to India. Not a question was raised by our committee regarding his race. The reports of his service to troops and of his splendid addresses at mission stations in India are most encouraging. After some months, at his own request, he went with a number of troops to British East Africa, where he has been serving East Indian troops, West Indian troops, British troops, South African troops, and native troops from many parts of Africa, rendering a service which almost parallels the labors of the Apostle Paul himself. He has suffered the fever, he has been surrounded with every danger known to man in that region. He is now broken in health and is on his way home; but his story will be like that of Livingstone. Last Christmas day he had only palm-trees for Christmas-trees and the sands of the desert for presents, but he told the Christmas story to more than 3,000 men who had never heard of Christmas. He went from hospital to hospital in his little "Ford" machine and from camp to camp in the spirit of Christ---sometimes near the coast and at others far in the interior, under the shadow of Kilima Njaro, the tallest mountain in Africa, whose summit is covered with eternal snow; many nights he was without shelter, with small quantities of unwholesome food---yet the ring of his letters never showed any sign of dissatisfaction with the discomforts, but joy at the privilege of service. It was not long after his arrival in Africa, before we were cabled to send six more men to join him in his work. To the colleges we went for these men, and the young men of this promising race were willing to consider the claims of this great need.

     The work of Mr. Yergan and his colleagues came to the attention of the world. Great Britain and her colonies began to consider this new type of American Negro and entered into negotiations to have Y.M.C.A. work under Mr. Yergan begun in Africa. To American Negroes this seemed to mark an epoch.

     Meantime, however, Mr. Jones entered the field. He arranged for a survey of South Africa, financed by the Phelps-Stokes Fund and with the co-operation of various English missionary associations. The English associations got the idea that Mr. Jones represented expert scientific opinion in America and are placing great faith in his decisions. No sooner had Mr. Jones reached South Africa, than preparations for the coming of Mr. Yergan were halted. The English authorities had previously written, up until the end of 1920, assuring the Y.M.C.A. that an invitation to Yergan to come and begin work in South Africa would undoubtedly go forward soon.

     Time passed and Mr. Yergan did not go. Finally, in self-defense, Mr. Yergan sent out a letter of explanation to a few friends, one of whom has sent a copy to <span class="crisis-title">The Crisis</span>. This letter says, among other things:

      I feel that I should no longer defer sending to you an explanation of the delay in my going out to the foreign field. You should also be informed with reference to other developments pertaining to association work in Africa. I am taking this opportunity of accomplishing both of these ends. It is not necessary for me to relate here in detail the developments which brought the Foreign Work Department of the International Committee to the point of committing itself to work for the native people of Africa. Let it suffice to say that the committee is definitely decided on this course. With this decision it was necessary to fix on a portion of the continent where work should be begun. In the light of correspondence which had passed between the International Committee and representative persons in South Africa, and because of the well developed student group and the larger centers of native population, it was thought best that I be sent first to South Africa. The replies to cablegrams concerning the possibility of beginning work there and the information which came in other correspondence led us to believe that I should sail early this year, as I had informed you and my friends there. I have many reasons for believing that I should be in South Africa today, doing the work all of you wish to have done, had it not been for that which I relate below.

      As a complete surprise, because it was so contrary to the other information which we have had, a letter which arrived a few weeks ago expressed doubt about permission to enter the country being granted to me by the Government of South Africa. A cablegram, which came a few days later, stated that permission had been refused. Along with this, however, we were informed of what had largely caused this position on the part of the Government. That was as follows:

      > Dr. Thomas Jesse Jones is in Africa, heading an educational commission of American and British Missionary Societies and the Phelps-Stokes Foundation, cooperatively. This Commission, I understand, has the endorsement of the British and Belgian Colonial Offices. In conference with high Government officials (you understand that these are all European) the letter informs us that Dr. Jones expressed himself as doubtful about colored American Association leadership. In view of the fact that there is already a strong prejudice in South Africa against the coming in of colored people from America, and because of their state of mind over newspaper reports on Marcus Garvey, it is easy to see how the added opposition of Thomas Jesse Jones caused the Government to take the position it did. I might add here, that it appears that Dr. Jones is attempting to do in Africa precisely what it is claimed he did in America, namely, to assign all colored people to one of the two so-called schools, and then to say that those of one of those schools cannot undertake to minister to the needs of the race. But his action goes further, for it will tend to prevent any colored man serving in a missionary capacity in Africa. I recently heard one of our newly made Bishops of the Methodist Episcopal Church say, "If we cannot serve in Africa, then where can we serve?"  
      &nbsp;  
      I want to take this opportunity of letting you know that the Foreign Work Department of the International Committee does not feel disposed to let this matter rest here, but is reopening the whole question.  
      &nbsp;  
      In the meantime, I am fully mindful of the necessity of our keeping alive the interest and enthusiasm of our constituency. The hearty support was given because our people wish to see the work of the Association carried to the people of Africa. Therefore, pending the settlement of the South African situation, I am recommending to the committee the plan of having me go out to Liberia, in response to requests which have come to us from that place.

E) *Other Missionary Work.* Colored missionaries have for a long time had difficulty in Africa. The Baptists write, saying "Our trouble in getting missionaries to all parts of Africa ... is alarming." The Lott Carey Convention says, "Our workers are evidently not wanted there." Bishop Vernon of the A.M.E. Church has suffered great inconveniences. These difficulties for the most part antedate Mr. Jones' journey, but Mr. Jones' attitude, added to this state of mind among the authorities, has held up some pressing work on the American side. For instance, Mrs. Camphor, wife of a former colored Methodist Bishop of Liberia, made a strong plea eight months ago to the Y.W.C.A. to begin work in Liberia. They considered it and decided to send a secretary this fall. In April, however, the Board suddenly decided that they must await the report of Thomas Jesse Jones on conditions in Liberia before beginning Y.W.C.A. work.

      This decision to wait on Mr. Jones seemed moreover to be not simply the voluntary decision of the Y.W.C.A. Board, but it was learned that practically all the missionary boards in America, working in Africa, had been induced to make similar postponements of decision as to their African program; so that today we face the astonishing fact that a large part of the missionary and social uplift work in Africa, so far as America is concerned, rests upon the coming word of Thomas Jesse Jones.

This is the serious situation that confronts colored people. It is not simply the question of one man nor is it a matter of considering the honesty or motives of Mr. Jones. It is a much broader and more important problem that faces us. *First*, are we going to consent to have our interests represented in the important councils of the world---missionary boards, educational committees, in all activities for social uplift---by white men who speak for us, on the theory that we cannot or should not speak for ourselves? And if after 60 years of freedom this is necessary, is it to go even further? And *second*, must the selection of the white man who is to represent us be taken entirely out of our own hands? If, as is inevitable, we resent either of these two conclusions, what is the next step which we must take? Simply make it clear to the world that while we have no enmity against Mr. Jones and are not stopping to question his motives or purposes, as American Negroes, and as men, we propose to speak for ourselves and to be represented by spokesmen whom we elect; and whenever in any case this policy is contravened we are going to fight that decision in every civilized way, and to the last ditch.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Light (1912)](/Volumes/03/04/light.html)
* [The Name Negro (1928)](/Volumes/35/03/name_negro.html)
* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)
* [Schools (1917)](/Volumes/13/03/schools.html)
* [The White Church (1917)](/Volumes/14/01/white_church.html)

<!-- Similar articles end here -->