---
title: 'Books'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1926
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 33
  issue: 2
  page: 81-82
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Carl Van Vechten's "Nigger Heaven" is a blow in the face. It is an affront to the hospitality of black folk and to the intelligence of white. First, as to its title: my objection is based on no provincial dislike of the nickname. "Nigger" is an English word of wide use and definite connotation. As employed by Conrad, Sheldon, Allen and even Firbanks, its use was justifiable. But the phrase, "Nigger Heaven," as applied to Harlem is a misnomer, "Nigger Heaven" does not mean, as Van Vechten once or twice intimates, (pages 15, 199) a haven for Negroes---a city of refuge for dark and tired souls; it means in common parlance, a nasty, sordid corner into which black folk are herded, and yet a place which they in crass ignorance are fools enough to enjoy. Harlem is no such place as that, and no one knows this better than Carl Van Vechten. 

But after all, a title is only a title, and a book must be judged eventually by its fidelity to truth and its artistic merit. I find this novel neither truthful nor artistic. It is not a true picture of Harlem life, even allowing for some justifiable impressionistic exaggeration. It is a caricature. It is worse than untruth because it is a mass of half-truths. Probably some time and somewhere in Harlem every incident of the book has happened; and yet the resultant picture built out of these parts is ludicrously out of focus and undeniably misleading. 

The author counts among his friends numbers of Negroes of all classes. He is an authority on dives and cabarets. But he masses this knowledge without rule or reason and seeks to express all of Harlem life in its cabarets. To him the black cabaret is Harlem; around it all his characters gravitate. Here is their stage of action. Such a theory of Harlem is nonsense. The overwhelming majority of black folk there never go to cabarets. The average colored man in Harlem is an everyday laborer, attending church, lodge and movie and as conservative and as conventional as ordinary working folk everywhere. 

Something they have which is racial, something distinctively Negroid can be found; but it is expressed by subtle, almost delicate nuance, and not by the wildly, barbaric drunken orgy in whose details Van Vechten revels. There is laughter, color and spontaneity at Harlem's core, but in the current cabaret, financed and supported largely by white New York, this core is so overlaid and enwrapped with cheaper stuff that no one but a fool could mistake it for the genuine exhibition of the spirit of the people.

To all this the author has a right to reply that even if the title is an unhappy catch-phrase for penny purposes and his picture of truth untruthful, that his book has a right to be judged primarily as a work of art. Does it please? Does it entertain? Is it a good and human story? In my opinion it is not; and I am one who likes stories and I do not insist that they be written solely for my point of view. "Nigger Heaven" is to me an astonishing and wearisome hodgepodge of laboriously stated facts, quotations and expressions, illuminated here and there with something that comes near to being nothing but cheap melodrama. Real human feelings are laughed at. Love is degraded. The love of Byron and Mary is stark cruelty and that of Lasca and Byron is simply nasty. Compare this slum picture with Porgy. In his degradation, Porgy is human and interesting. But in "Nigger Heaven" there is not a single loveable character. There is scarcely a generous impulse or a beautiful ideal. The characters are singularly wooden and inhuman. Van Vechten is not the great artist who with remorseless scalpel probes the awful depths of life. To him there are no depths. It is the surface mud he slops about in. His women's bodies have no souls; no children palpitate upon his hands; he has never looked upon his dead with bitter tears. Life to him is just one damned orgy after another, with hate, hurt, gin and sadism. 

Both Langston Hughes and Carl Van Vechten know Harlem cabarets; but it is Hughes who whispers 

<div class="poem">
<p class="verse">One said he heard the jazz band sob</p>
<p class="verse">When the little dawn was grey.</p>
</div>

Van Vechten never heard a sob in a cabaret. All he hears is noise and brawling. Again and again with singular lack of invention he reverts to the same climax of two creatures tearing and scratching over "mah man"; lost souls who once had women's bodies; and to Van Vechten this spells comedy, not tragedy. 

I seem to see that Mr. Van Vechten began a good tale with the promising figure of Anatol, but that he keeps turning aside to write in from his notebook every fact he has heard about Negroes and their problems; singularly irrelevant quotations, Haitian history, Chesnutt's novels, race-poetry, "blues" written by white folk. Into this mass he drops characters which are in most cases thin disguises; and those who know the originals have only to compare their life and this death, to realize the failure in truth and human interest. The final climax is an utterly senseless murder which appears without preparation or reason from the clouds. 

I cannot for the life of me see in this work either sincerity or art, deep thought, or truthful industry. It seems to me that Mr. Van Vechten tried to do something bizarre and he certainly succeeded. I read "Nigger Heaven" and read it through because I had to. But I advise others who are impelled by a sense of duty or curiosity to drop the book gently in the grate and to try the Police Gazette. <span class="right">--W. E. B. D.</span>