---
title: 'Eugene Debs'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1926
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 33
  issue: 2
  page: 72-75
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Eugene Debs was one of the few leaders of organized labor in the United States who realized that a large part of the laboring force in this country is of Negro descent. Most labor leaders are either too ignorant or too prejudiced to acknowledge this. Debs knew that no real emancipation of laboring classes in the United States can come as long as black laborers are in partial serfdom. He realized that that emancipation called for effort on the part of both black people and white; that black people must recognize that their future lies not on a foundation of wealth and luxury but with the people who work and save; that only by a united effort on the part of labor can organized wealth be kept from autocracy and the degradation of vast portions of mankind. On the other hand, unless white labor recognizes the brotherhood of man, it becomes the helpless tool of modern industrial imperialism. 

The death of so great a mind and so brave a heart as that of Eugene Debs is a calamity to this poor nation. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)
* [The Negro and Labor (1922)](/Volumes/25/06/negro_and_labor.html)
* [Our Economic Peril (1930)](/Volumes/37/03/our_economic_peril.html)
* [The Migration (1917)](/Volumes/14/01/migration.html)
* [To the American Federation of Labor (1924)](/Volumes/28/04/american_federation_of_labor.html)

<!-- Similar articles end here -->