
---
title: 'Hawaii'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1932
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 39
  issue: 3
  page: 93
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The assault on a white woman in Hawaii brings this whole volcanic structure to the world's notice. Hawaii is a volcano and a series of volcanoes in more senses of the word than one. It is near the exact center of the Pacific Ocean. It was settled in prehistoric times by dark Mongolians with many evidences of a strong Negro strain. It was discovered by Captain James Cook in 1778. A company of missionaries landed there in 1820 and in 1823 came the great revival when the Queen and one-fifth of the population were converted to Christianity.

Troubles with foreigners ensued, culminating in a revolution in 1893, which deposed the native Queen and made a missionary's son President. Hawaii was annexed to the United States in 1898. But the real conquest of Hawaii was the investment there of millions of dollars to raise pineapples, sugar, coffee, bananas, and other merchandise. Nearly eight hundred thousand tons of sugar are annually exported and two hundred and thirteen million cans of pineapples. To raise this produce, the exploiters of Hawaii encouraged an immigration which has resulted in the most astonishing mixture of races known to the modern world.

When the missionaries arrived, there were 142,000 Hawaiians. Christianity reduced them to only 57,000 in 1872. Large numbers of Chinese, Japanese, Koreans, together with many Philippinos, Porto Ricans and Portuguese, were brought into the country to work the plantations. Today, there are 255,ooo inhabitants, of whom half are of Japanese and Chinese descent, 8% Philippinos, 18% Hawaiians or part Hawaiian, and 21% Caucasians.

Here in itself is a problem, because the new generation of Japanese, Chinese and Philippino-Hawaiians, are American citizens and voters, having been born in the Islands. We must add to this the fact that Hawaii is a naval base and has usually over fifteen thousand United States soldiers and sailors in the forts. And finally, there land in Hawaii each year 17,500 tourists to loll and play and spend.

Heretofore, there has been little racial antagonism. Inter-marriage among all the races, even the few Negroes, has gone on. But the great fact and menace remains. Big business owns Hawaii, and its five main groups are the real Kings. They control the land and they own investments totalling over $300,000,000. They are there to make money. They are backed by the military power of the United States, and the threat of racial antagonism between white and colored, is thus ever in the air.

We must watch Hawaii, and in the present turmoil, remember two significant facts: First, laws against rape are not severe in Hawaii because they were originally framed to make the seduction of native girls easy by white men. Not long ago, an appeal was broadcast in American papers to support the thousands of illegitimate children there left helpless by white soldiers and marines. Secondly, a society lady and her accomplices, who killed a. Hawaiian in cold blood, are today free on nominal bail, and in all probability will never be punished.

Watch Hawaii.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [John Brown (1932)](/Volumes/39/01/john_brown.html)
* [The Rise of the West Indian (1920)](/Volumes/20/05/rise_of_the_west_indian.html)
* [An Amazing Island (1915)](/Volumes/10/02/amazing_island.html)
* [Westward Ho (1934)](/Volumes/41/05/westward_ho.html)
* [I Go A-Talking (1913)](/Volumes/06/03/i_go_a_talking.html)

<!-- Similar articles end here -->