
---
title: 'To Your Tents, Oh Israel!'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1932
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 39
  issue: 3
  page: 93-94
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


With twelve million Negroes in America and at least ten millions in the adjacent West Indies, is the black race economically helpless? These two groups as consumers must at the very lowest estimate spend ten billion dollars a year. Perhaps the larger part of this expenditure is compulsory, and we have small choice as to where and how it should be spent. But there must be hundreds of millions where we do have choice in the direction of its expenditure. This expenditure can and must, if we survive in America, be so directed as to employ our own muscle and brains in the production of the goods and services which we need. Such production demands skill, but what skill, and how shall we gain this skill?

The way is clear. Our colleges are or may be centers of information and learning. They should study the facts concerning the consumption of goods by American Negroes and West Indians. They should measure and make clear our economic demands. We have industrial schools. Those industrial schools should train young people, so that they would have skill to do the kind of work which is necessary to satisfy our demands. Their aims should not be simply to do the work and make the goods which white folks demand. Their aim should not be simply to train for decadent and outworn trades where there is a lessening demand for workers. Their main object should be to train Negroes to supply Negroes' needs.

When we know just what our demand for goods and services is and when we have people trained in modern technique to furnish these things, we in turn can furnish the capital. That capital is simply a part of the money which we spend. We furnish such capital today to the white industrial world. There is no reason on earth why it should not be spent to establish a black industrial world.

There are wise and careful students who claim that no such racial economy is possible. I take no stock in their pessimism. It not only is possible but it is already beginning and it only needs scientific guidance and technical skill to make it spread. What has been done by separate nations, protected by tariffs, can be done by separate groups, protected by a vast sense of desperate need.

When these goods are made, they can be distributed by Negro business, built up like the C.M.A. stores. Such stores will meet increasing competition from white stores, and they are at the mercy of the owners of white capital. Nevertheless, they can meet this competition, and they can substitute colored capital for white capital, if they will start upon one path and that path demands the abolition absolutely of private profit: the willingness of young Negro managers of brains and skill to work for low, definite wage, instead of trying to emulate the whites' desire for millions. We must embrace the ideal of poverty---not poverty that calls for dirt, disease and pain, but poverty that definitely and decisively puts aside the ideal of luxury, waste and inordinate wealth. To the ideal of poverty, we must add that of service, dedicated to the rescue of twenty-two millions of human beings who are bound to us by blood and tradition. Here is an economic program for times of depression, and it will work, if we work it.

To Your Tents, Oh Israel!

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Philanthropy and Self Help (1918)](/Volumes/16/03/philanthropy_and_self_help.html)
* [Education (1930)](/Volumes/37/02/education.html)
* [Our Economic Future (1928)](/Volumes/35/05/our_economic_future.html)
* [Employment (1932)](/Volumes/39/09/employment.html)
* [Our Class Struggle (1933)](/Volumes/40/07/our_class_struggle.html)

<!-- Similar articles end here -->