
---
title: 'Thirteen'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 15
  issue: 3
  page: 115
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Efficiency

The National Association for the Advancement of Colored People has, in its comparatively brief career, dealt Bourbonism in the United States three telling blows. First: by helping to secure the celebrated Grandfather Decision before the Supreme Court, it began the overthrow of Disfranchisement and secured the first official affirmation of the validity of the Fifteenth Amendment. Second: it dealt Caste in the Nation a telling blow when it secured the admission of nearly seven hundred Colored Officers of the United States Army. Third: in securing the Segregation Decision before the Supreme Court, it stopped the most outrageous invasion of the Negro's rights yet attempted.

In addition to these three blows, it has fought for Civil Rights, encouraged ability through the Spingarn Medal, defeated Anti-Intermarriage Laws, watched Legislation, made Lynching a National question, and published the Truth.

It did not do these things single-handed but has worked always with all persons minded to work with it. In each case, however, it has furnished suggestion, encouragement, funds, and active organization.

This is surely a record which proves The National Association for the Advancement of Colored People the only national organization in the field today which can fight efficiently for the rights of the Negro and the one on which twelve million Negroes should concentrate with membership, encouragement and funds.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Next Step (1913)](/Volumes/06/02/next_step.html)
* [We Should Worry (1917)](/Volumes/14/02/we_should_worry.html)
* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)
* [Muddle (1916)](/Volumes/13/02/muddle.html)
* [The Proper Way (1913)](/Volumes/05/05/proper_way.html)

<!-- Similar articles end here -->