---
title: Thirteen
description: 'In The Crisis (1918), W.E.B. Du Bois condemns racial injustice: thirteen Black soldiers executed while white perpetrators go free, attacking American justice.'
author:
- name:
    given: W.E.B.
    family: Du Bois
date: Jan. 1918
subjects:
- Military discrimination
- Extrajudicial killings and racial violence
- Discrimination in the American criminal justice system
- African American military service and civil rights
people:
- W. E. B. Du Bois
- Woodrow Wilson
places:
- Houston, Texas
- United States
organizations:
- United States Army
- The Crisis (NAACP publication)
events:
- Camp Logan Mutiny / Houston Riot (1917)
citation:
  type: article-journal
  container-title: The Crisis
  volume: 15
  issue: 3
  page: 114
google-scholar: true
format:
  html:
    toc: false
    appendix-cite-as: display

categories:
  - "Racial Violence"
  - "War & Military"
---

The have gone to their death. Thirteen young, strong men; soldiers who have fought for a country which never was wholly theirs; men born to suffer ridicule, injustice, and, at last, death itself. They broke the law. Against their punishment, if it was legal, we cannot protest. But we can protest and we do protest against the shame­ful treatment which these men and which we, their brothers, receive all our lives, and which our fathers received, and our children await; and above all we raise our clenched hands against the hundreds of thousands of white murderers, rapists, and scoundrels who have oppressed, killed, ruined, robbed, and debased their black fellow men and fellow women, and yet, today, walk scot-free, unwhipped of justice, uncondemned by millions of their white fellow citizens, and unrebuked by the President of the United States.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Martyrs (1920)](/Volumes/21/02/martyrs.html)
* [Heroes (1919)](/Volumes/19/01/heroes.html)
* [Returning Soldiers (1919)](/Volumes/18/01/returning_soldiers.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)

<!-- Similar articles end here -->