---
title: '''Ashamed'''
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1911
categories: 
  - Racial pride
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 3
  page: 21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Any colored man who complains of the treatment he receives in America is apt to be faced sooner or later by the statement that he is ashamed of his race.

The statement usually strikes him as a most astounding piece of illogical reasoning, to which a hot reply is appropriate.

And yet notice the curious logic of the persons who say such things. They argue:

White men alone are men. This Negro wants to be a man. Ergo he wants to be a white man.

Their attention is drawn to the efforts of colored people to be treated decently. This minor premise therefore attracts them. But the major premise---the question as to treating black men like white men---never enters their heads, nor can they conceive it entering the black man's head. If he wants to be a man he must want to be white, and therefore it is with peculiar complacency that a Tennessee paper says of a dark champion of Negro equality: "He bitterly resents his Negro blood."

Not so, O Blind Man. He bitterly resents your treatment of Negro blood. The prouder he is, or has a right to be, of the blood of his black fathers, the more doggedly he resists the attempt to load men of that blood with ignominy and chains. It is race pride that fights for freedom; it is the man ashamed of his blood who weakly submits and smiles.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [On Being Ashamed of Oneself (1933)](/Volumes/40/09/on_being_ashamed.html)
* [Precept and Practice (1910)](/Volumes/01/02/precept_and_practice.html)
* [Race Pride (1920)](/Volumes/19/03/race_pride.html)
* [Separation (1911)](/Volumes/01/04/separation.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)

<!-- Similar articles end here -->