
---
title: 'Jesus Christ in Baltimore'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1911
categories: 
  - Segregation
  - Religion
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 3
  page: 21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



It seems that it is not only Property that is screaming with fright at the Black Spectre in Baltimore, but Religion also. Two churches founded in the name of Him who "put down the mighty from their seats and exalted them of low degree" are compelled to move. Their palatial edifices filled with marble memorials and Tiffany windows are quite useless for the purposes of their religion since black folk settled next door. Incontinently they have dropped their Bibles and gathered up their priestly robes and fled, after selling their property to colored people for $125,000 in good, cold cash.

Where are they going? Uptown. Up to the wealthy and exclusive and socially select. There they will establish their little gods again, and learned prelates with sonorous voices will ask the echoing pews: "How can the Church reach the working man?" Why not ask the working man? Why not ask black people, and yellow people, and poor people, and all the people from whom such congregations flee in holy terror? The church that does not run from the lowly finds the lowly at its doors, and there are some such churches in the land, but we fear that their number in Baltimore is not as great as should be.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Church (1916)](/Volumes/11/06/church.html)
* [Steal (1920)](/Volumes/20/06/steal.html)
* [The Negro Church (1912)](/Volumes/04/01/negro_church.html)
* [Crime (1918)](/Volumes/15/05/crime.html)
* [The Church and the Negro (1913)](/Volumes/06/06/church_negro.html)

<!-- Similar articles end here -->