
---
title: 'Envy'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 3
  page: 16
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



It is unfortunate that in the recent newspaper discussion of an Appeal to Europe sent out not by this Association but by a number of colored men of influence and standing, reference was constantly made to the lowest personal motives and seldom to the arguments presented.

It is true that with all peoples, and especially with a race in the throes of birth-pain, personal likes and jealousies play a wretchedly large, part. But it does not follow that they explain all the struggle and difference of opinion. It is true that the rise of a man like Mr. Booker T. Washington to a place of commanding influence has made him an object of envy to many narrow souls. But it does not follow that the thousands of intelligent people who differ with Mr. Washington are all actuated by such motives, or are unable to distinguish great and vital principles apart from personal feeling.

When, therefore, such differences of opinion arise, as it is natural and healthy that they should arise, it is both wrong and unjust to assume the motive to be necessarily low. Particularly is this true when adequate causes of deep and compelling importance are openly and honestly given as the cause of this difference.

Are such causes sufficient to sustain the complainers? That is a matter of argument, not of innuendo or abuse. No man and no cause are above the careful scrutiny and criticism of honest men, and certainly to-day there is in the United States a very large field for argument as to the proper attitude of colored leaders toward the race problem.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Starvation and Prejudice (1911)](/Volumes/02/02/starvation_and_prejudice.html)
* [Prejudice (1927)](/Volumes/34/09/prejudice.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)

<!-- Similar articles end here -->