
---
title: 'The Old Story'
author: Du Bois, W.E.B.
date: Jan. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 3
  page: 20
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




There is without doubt a large criminal and semi-criminal class among colored people. This is but another way of saying that the social uplift of a group of freedmen is a serious task. But it is also true, and painfully true, that the crime imputed carelessly and recklessly against colored people gives an impression of far greater criminality than the facts warrant.

Take, for instance, a typical case: A little innocent schoolgirl is brutally murdered in New Jersey. A Negro vagabond is arrested. Immediately the news is heralded from East to West, from North to South, in Europe and Asia, of the crime of this black murderer. Immediately a frenzied, hysterical mob gathers and attempts to lynch the poor wretch. He is spirited away and the public is almost sorry that he has escaped summary justice. Without counsel or friends, the man is shut up in prison and tortured to make him confess. "They did pretty near everything to me except kill me,' whispered the wretched man to the first friend he saw.

Finally, after the whole black race in America had suffered aspersion for several weeks, sense begins to dawn in Jersey. After all, what proof was there against this man? He was lazy, he had been in jail for alleged theft from gypsies, he was good natured, and he drank whiskey. That was all. Yet he stayed in jail under no charge and under universal censure. The coroner's jury found no evidence to indict him. Still he lay in jail. Finally the National Association for the Advancement of Colored People stepped in and said, "What are you holding this man for?" The Public Prosecutor got red in the face and vociferated. Then he went downtown, and when the habeas corpus proceedings came and the judge asked again: "Why are you holding this man?" the prosecutor said chirpily, "For violating election laws," and brought a mass of testimony. Then the judge discharged the prisoner from the murder charge and congratulated the National Association for the Advancement of Colored People---but the man is still in jail.

Such justice is outrageous and such methods disgraceful. Black folk are willing to shoulder their own sins, but the difference between a vagabond and a murderer is too tremendous to be lightly ignored.

