
---
title: 'A Winter Pilgrimage'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1911
categories: 
  - Travel
  - 
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 3
  page: 15
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The race problem is not one problem. It differs not only in time, but in place. Therefore I always go to different groups of colored people in this land with much of interest and curiosity, knowing that each will present its peculiar phase of relationship between the white and colored group. 

I have just come back from such a journey, and its scenes and lessons are filling my thought. 

There was Toledo, with its colored group a little pushed aside and half forgotten in the onward rush of the growing city till the group gripped itself and awoke and said: "We are a part of Toledo---you may not forget us." So now slowly comes the push forward and upward. 

In Cleveland it is far different---it is not so much a matter of gaining civic recognition as men and women---that battle was fought by worthy men long years ago. It is the deeper problem of holding the ground gained; of not letting theatres and restaurants and hotels inaugurate a new discrimination which had once disappeared. This is a difficult battle of the new economic rise of the Negro; when few Negroes applied or had money to apply it was easy to say theoretically, "Live where you will, go where you please." But when a group of black folk growing in power put a $75,000 church on your corner---that is a phase of the race problem that hadn't struck you before. 

Between these cities of past and present lies the mystic city of the future, with its great cloud walls. 

In Oberlin there are nearly two thousand young folk at study and at play. Working and playing beside them are a hundred colored boys and girls, and they all walk on sacred ground, on ground long since consecrated to racial equality and hatred of caste and slavery. Yet among these venerable ideals obtrudes the Present and it, with all its odd corners, must be builded into the future city. 

The present holds not only the problem of the treatment of ten million black folk elsewhere, but of the hundred colored boys and girls right there in Oberlin. It presents a tremendous moral dilemma to frank young souls. When these children came from anti-slavery homes they found it easy and natural to treat black men as men. But coming now from a world that thinks God made a big mistake in ever creating black folk---coming from such social teaching, they hesitate. Once in a while a black student (or rather a yellow one) may be elected a society, but usually no desert in character or scholarship avails. 

Yet this fact brings no mental peace or moral satisfaction. The spirit of democracy is strong, the influence of the faculty is righteous, and I came from five hours' earnest conference with these young folk with a sense of seeing a mighty battle for righteousness, and a belief that somehow, sometime, justice would prevail. 

But after all it was the men I met that meant most. Could I introduce them? Let me see. There was the young lawyer who burned to awaken a sleeping city to its duties and rights; there was the brown physician who is one of the leading surgeons in the city, and his knife finds no color line. Then the girl who ran a political campaign last month had a father who was director in a white bank and one of the solid business men of the town. In their parlor gathered a brown father, a yellow mother, the white pastor and the white girl chum---but why should we catalog the colors of their skins and not those of their clothes? In Oberlin the chief book store is "colored," and the chief paper hanger and the chief building contractor. Elsewhere I sat with the man who had just been elected a member of a leading white city club and heard how the second highest mechanic in the Peerless motor factory wore "the shadowed livery of the sun." 

Therefore, all is well? Therefore, all is not well. Here are a climbing people. The hardiest and most talented and the pushing are literally forcing a way. But against them and against the ordinary black man the bonds of medievalism are drawn and ghettos and sumptuary laws are encompassed in the color line.

*W. E. B. D.*

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Y.M.C.A (1914)](/Volumes/09/02/ymca.html)
* [Unity (1924)](/Volumes/28/03/unity.html)
* [Correspondence (1926)](/Volumes/31/05/correspondence.html)
* [Separation (1911)](/Volumes/01/04/separation.html)
* [World War and the Color Line (1914)](/Volumes/09/01/worldwar.html)

<!-- Similar articles end here -->