
---
title: 'Grand Jury Adjourns: Laurens County Fails to Indict Dendy Lynchers'
author: Boardman, Helen
date: May 1934
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 41
  issue: 5
  page: 140
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




After the lynching of Norris Dendy on the Fourth of July, 1933, two detectives came to Clinton, South Carolina. Within an hour of their arrival the interested citizens knew that they were the state investigators from Columbia who were working on the Dendy lynching case. Not a move they made went unnoticed and unreported. Persons whom they interviewed knew well that no privacy attended their utterances; and when such persons were colored, no overt threat was needed to make them guard their words with the utmost discretion. After the investigators had made their report, Governor Blackwood stated his belief that Norris Dendy had been murdered (not lynched) by persons unknown; and added that the state would endeavor to find and prosecute the criminals.

In South Carolina, there is a law by which the family of a man who is lynched is entitled to damages of not less than $2,000. A lynching is death caused by violence committed by an unlawful assembly. When a prisoner in custody is seized through the neglect or connivance of an officer by an unlawful assembly, the officer shall be deposed from office and shall henceforth be ineligible for office unless pardoned. For murder, of course, there is no compensation.

After the two detectives, Richardson and Newman, returned to Columbia, nothing further happened. It is likely that the case would have been dropped had it not been for the determination and perseverance of the brother of the lynched man, Mr. Robert Dendy of New York. Mr. Dendy went to Clinton and endeavored to learn the facts and to arouse interest among the better class white people. He finally obtained an audience for himself and his mother with Governor Blackwood at Columbia which resulted in further gestures on the part of the state investigators. Seeing that this line was accomplishing nothing, he returned to New York. There, after some delay, his attorney, William T. Andrews, obtained an investigator through the N.A.A.C.P. who went to South Carolina in September.

The report of this investigator was too voluminous for publication. It included accounts by eye-witnesses of the events at the jail, with the names of many of the participants. One of the leading white citizens stated as a matter of common knowledge that most, if not  all, of the police force took part in the lynching. The same person said he had gone to the jail immediately after the lynching and examined the lock on the door of the cell which had been occupied by Norris Denby. He found no sign of the lock having been forced or changed---"it was the same lock that had been there for years."

On the advice of his attorney and of Secretary Walter White of the N.A.A.C.P., Mr. Dendy brought three of the colored witnesses to New York in order that they might testify without personal risk. One of these witnesses, Mr. William Crawford, had already been compelled, by threats of violence by members of the mob, to leave Clinton. The other two were Mr. Ernest Mims, of Washington, D. C., and Miss Clara Belle Peak of Clinton. These three people made affidavits fully describing the events they had witnessed. Their statements, with the other information were sent by Walter White to Governor Blackwood who was urged in the name of the National Association to take immediate action.

Governor Blackwood sent Detectives Newman and Cannon to New York where they conferred with Mr. White and Mr. Dendy and arranged for the witnesses to return to South Carolina to testify. There, after a preliminary interview with the Governor they, with Mr. Robert Dendy and his mother, went to Laurens, county seat of Laurens County, with an escort of State highway patrolmen. That this protection was necessary, and that the coroner's jury was secretly called, is evidence of the tense feeling in the community. The jury was composed of close friends of the men who were named as members of the mob. It met on February 17, 1934.

In addition to the three witnesses named above, Mrs. Martha Dendy, mother of Norris and his wife Mrs. Amanda Dendy testified. More than a dozen members of the mob were named, including officers of the law. A sensational surprise was the testimony of a white man, Mr. F. A. Gedeist, that he had seen Norris Dendy taken from the jail by Hubert Pitts and J. Pitts Ray, and placed in an automobile driven by P. M. Pitts.

Mr. William Crawford stated that while in his father's car, which was parked near the jail, he heard Mrs. Dendy "pleading with Policeman McMillan saying that she would pay the fine if they would only let Norris Dendy out, and Policeman McMillan replied that he could not pay out of this and Pack Pitts reiterated that statement." Later his affidavit reads, "while deponent was parked at... Pitt and Wall Streets deponent estimated that the crowd he saw in front of the jail consisted of more than one hundred people. That of these he recognized Pack Pitts, Officer Henry Young, Roy Pitts, Marvin Lollis, Hubert Pitts and Chief of Police George Holland; that the conduct of ali of these persons indicated that they were part of what was going on." He testified further that he saw someone taken from the jail and placed in the automobile belonging to Pack Pitts, who was in the front seat, "and in the back seat was Marvin Lollis and others who were active and deponent could see their arms being raised and going down as if they were beating someone, and deponent heard cries from the back seat." In the cars following he saw Hubert Pitts and others whose names he does not know but whom he could identify on sight.

Mr. Ernest Mims testified, after a detailed account of Norris Dendy's efforts to get bail, that he had seen Hubert Pitts get out of his car with a rope and go into the jail; that there were many people around the jail among whom he saw "Red Watkins, Marvin Stewart, Pack Pitts, Roy Pitts, Roy (Bob) Tucker, Gus Blakely, Ray Pitts and L. L. Copeland." Mr. Mims went into an alley from which he could look through a back door into the jail. He saw "the crowd standing with sticks, brooms and all sorts of weapons and Policeman Weir unlocked the door to Norris' cell." He described the struggle which began as the crowd tried to force Norris from his cell. He then went away from that place and shortly after he saw Pack Pitts' car pass with Norris in the back seat.

Much additional and corroborative testimony was given. When it had been heard the jury decided that Norris Dendy had come to his death at the hands of "a party or parties unknown."

On February 19th, murder indictments against five Clinton men were drawn and presented to the grand jury by Solicitor Homer S. Blackwell. They were Marvin Lollis, P. M. Pitts, Hubert Pitts, Roy Pitts and J. Pitts Ray. After considering the case and hearing the witnesses the grand jury adjourned without action. It will meet again in June. Will it then resume the consideration of this case? To date this is just another lynching, with the South running true to form. Another insufferable crime has been committed and the perpetrators are being shielded by the silence and passivity of the "better element."

