
---
title: 'Segregation'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1934
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 41
  issue: 5
  page: 147
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


A girl with brown and serious face, came to me after a lecture. She was not satisfied with what I had said, nor to my answer to her questions from the floor. She said: "It seems to me you used to fight Segregation, and that now you are ready to compromise." I answered: If you mean by fighting Segregation, fighting with fists, this is a thing I have never advocated, because it seems to me that such a policy always loses more than it gains. I have fought Segregation and other evils with reason, with facts, and with agitation. In this way, I'm still fighting. I said in the past that Segregation is wrong. I am still saying it.

As to my willingness to compromise, that depends upon what you mean by compromise. If you mean by compromise, taking less than you want, but not wanting less, then I do compromise. I take what I can get, as I always have in the past. Yet I want all. And if in this matter of taking what I can get, I compromise, so do you, and so must you.

Moreover, and beyond this, I fight Segregation with Segregation, and I do not consider this compromise. I consider it common sense.

Out beyond me, where I write, lies a slum, Beaver Slide; named after an Atlanta Chief of Police, who went that way hurriedly one night because of certain dark dangers. I have seen this slum now and again for thirty years: Its drab and crowded houses; its mud, dust and unpaved streets; its lack of water, light and sewage; its crowded and unpoliced gloom. Just now, it seems certain, that the United States Government is going to spend $2,000,000 to erase this slum from the face of the earth, and put in its place, beautiful, simple, clean homes, for poor colored people, with all modern conveniences.

This is Segregation. It is Segregation by the United States Government. These homes are going to be for Negroes, and only for Negroes; and yet I am a strong advocate for this development. If this is compromise with Segregation; I am compromising. Not only that, but strange enough, I hear no opposition even from the Washington Brain Trust. Dr. George Haynes has uttered no word of protest. The embattled Youth of Washington have not gone on record, and why? Is it because they or I like the necessity of having public development for social uplift divided along an artificial Color Line? Certainly not. But it's because I have sense enough to know, and I hope they have, that either we get a segregated development here, or we get none at all; and the advantage of decent homes for five thousand colored people, outweighs any disadvantage which will come from this development.

I say again, if this is compromise; if this is giving up what I have advocated for many years; the change, the reversal, bothers me not at all. But Negro poverty and idleness, and distress, they bother me, and always will.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Segregation (1934)](/Volumes/41/01/segregation.html)
* [Counsels of Despair (1934)](/Volumes/41/06/counsels_of_despair.html)
* [The Strength of Segregation (1913)](/Volumes/07/03/strength_of_segregation.html)
* [Separation and Self-Respect (1934)](/Volumes/41/03/separation_and_selfrespect.html)
* [Segregation (1910)](/Volumes/01/01/Segregation.html)

<!-- Similar articles end here -->