
---
title: 'William Monroe Trotter'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1934
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 41
  issue: 5
  page: 134
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Monroe Trotter was a man of heroic proportions, and probably one of the most selfless of Negro leaders during all our American history. His father was Recorder of Deeds for the District of Columbia, at the time when Recorders were paid by fees; and as a result, he retired from office with a small fortune, which he husbanded carefully. Thus, his son was born in comfortable circumstances, and with his talent for business, and his wide acquaintanceship with the best class of young Massachusetts men in his day, might easily have accumulated wealth. 

But he turned aside. He had in his soul all that went to make a fanatic, a knight errant. Ready to sacrifice himself, fearing nobody and nothing, strong in body, sturdy in conviction, full of unbending belief. 

I remember when I first saw him as a student at Harvard. He was several classes below me. I should liked to have known him and spoken to him, but he was curiously aloof. He was even then forming his philosophy of life. Colored students must not herd together just because they were colored. He had his white friends and companions, and they liked him. He was no hanger-on, but a leader among them. But he did not seek other colored students as companions. I was a bit lonesome in those days, but I saw his point, and I did not seek him. 

Out of this rose his life-long philosophy: Intense hatred of all racial discrimination and segregation. He was particularly incensed at the compromising philosophy of Booker T. Washington; at his industrialism, and his condoning of the deeds of the South. 

In the first years of the 20th Century, with George Forbes, Monroe Trotter began the publication of *The Guardian*. Several times young men have started radical sheets among us, like *The Messenger*, and others. But nothing, I think, that for sheer biting invective and unswerving courage, ever quite equaled the Boston *Guardian* in its earlier days. Mr. Washington and his followers literally shriveled before it, and it was, of course, often as unfair as it was inspired. 

I had come to know Trotter, then, especially because I knew Deenie Pindell as a girl before they were married. We were to stop with them one summer. Mrs. Du Bois was already there when I arrived in Boston, and on the elevated platform, I learned of the Zion Church riot. It was called a riot in  the newspapers, and they were full of it. As a matter of fact, Trotter and Forbes had tried to ask Booker T. Washington certain pointed questions, after a speech which he made in the colored church; and immediately he was arrested, according to the careful plans which William L. Lewis, Washington's attorney, had laid. I was incensed at Trotter. I thought that he had been needlessly violent, and had compromised me as his guest; but when I learned the exact facts, and how little cause for riot there was, and when they clapped Trotter in the Charles Street Jail, all of us more conservative, younger men rose in revolt. 

Out of this incident, within a year or two, arose the Niagara movement, and Trotter was present. 

But Trotter was not an organization man. He was a free lance; too intense and sturdy to loan himself to that compromise which is the basis of all real organization. Trouble arose in the Niagara movement, and afterward when the Niagara movement joined the new N.A.A.C.P., Trotter stood out in revolt, and curiously enough, did not join the new organization because of his suspicion of the white elements who were co-operating with us. 

He devoted himself to *The Guardian*, and it became one of the first of the nation-wide colored weeklies. His wife worked with him in utter devotion; giving up all thought of children; giving up her pretty home in Roxbury; living and lunching with him in the *Guardian Office*, and knowing hunger and cold. It was a magnificent partnership, and she died to pay for it. 

The Trotter philosophy was carried out remorselessly in his paper, and his philosophy. He stood unflinchingly for fighting separation and discrimination in church and school, and in professional and business life. He would not allow a colored Y.M.C.A. in Boston, and he hated to recognize colored churches, or colored colleges. On this battle line he fought a long, exhausting fight for over a quarter of a century. What has been the result? There are fewer Negroes in Boston churches today than when Trotter began a crusade, and colored people sat in the pews under Phillips Brooks' preaching. There may be more colored teachers in the schools, but certainly they are playing no such part as Maria Baldwin did, as principal of the best Cambridge Grammar School. 

When Trotter began, not a single hotel in Boston dared to refuse colored guests. Today, there are few Boston hotels where colored people are received. There is still no colored Y.M.C.A., but on the other hand, there are practically no colored members of the white "Y," and young colored men are deprived of club house and recreational facilities which they sorely need. In the professions, in general employment, and in business, there is certainly not less, and probably more discrimination than there used to be. 

Does this mean that Monroe Trotter's life was a failure? Never. He lived up to his belief to the best of his ability. He fought like a man. The ultimate object of his fighting was absolutely right, but he miscalculated the opposition. He thought that Boston and America would yield to clear reason and determined agitation. They did not. On the contrary, to some extent, the very agitation carried on in these years has solidified opposition. This does not mean that agitation does not pay; but it means that you cannot necessarily cash in quickly upon it. It means that sacrifice, even to blood and tears, must be given to this great fight; and not one but a thousand lives, like that of Monroe Trotter, is necessary to victory.

More than that, inner organization is demanded. The free lance like Trotter is not strong enough. The mailed fist has got to be clenched. The united effort of twelve millions has got to be made to mean more than the individual effort of those who think aright. Yet this very inner organization involves segregation. It involves voluntary racial organization, and this racial grouping invites further effort at enforced segregation by law and custom from without. Nevertheless, there is no alternative. We have got to unite to save ourselves, and while the unbending devotion to principle, such as Monroe Trotter shows, has and must ever have, its value, with sorrow, and yet with conviction, we know that this is not enough. 

&nbsp;

I can understand his death. I can see a man of sixty, tired and disappointed, facing poverty and defeat. Standing amid indifferent friends and triumphant enemies. So he went to the window of his Dark Tower, and beckoned to Death; up from where She lay among the lilies. And Death, like a whirlwind, swept up to him. I shall think of him as lying silent, cold and still; at last at peace, dreamless and serene. Let no trump of doom disturb him from his perfect and eternal rest.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [William Monroe Trotter (1914)](/Volumes/09/02/trotter.html)
* [Tillman (1918)](/Volumes/16/04/tillman.html)
* [On Being Ashamed of Oneself (1933)](/Volumes/40/09/on_being_ashamed.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Heroes (1919)](/Volumes/19/01/heroes.html)

<!-- Similar articles end here -->