
---
title: 'Westward Ho'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1934
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 41
  issue: 5
  page: 148
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


In recent years, it has been my custom to visit Chicago and regions about it, at least once a year, and to use the excuse of lecturing in order to become acquainted again, at first hand, with the great Middle West. It is painfully easy in the United States for a great metropolis to mistake itself for the nation. This was once true of Boston. In some respects, it is true of Washington. Nearly always, it is true of New York; and the great difficulty of argument and understanding for the nation today, is that with the concentration of power and brains in New York, it is so easily assumed that there is no power, that there are no centers of thought and development outside of Manhattan Island.

This year and last, I have not only viewed the national scene from Georgia, but also gone for brief visits into Alabama, Louisiana, Tennessee and Texas. And finally, I took a trip West in March.

I went to Indianapolis, after a lapse of seven years. A pause had come in my activities there, caused by the fact that in my last visit, I took occasion to preach to the white ministers of that city on the text: "Of All Forces for Social Uplift, I have Least Faith in White Christian Ministers."

I am afraid that I did not quite convince my auditors, although, personally, I was sincere. At any rate, the white man who then headed the city Y.M.C.A., refused to sanction further lectures from me. When I came back this year, I asked after him. It seems that he is retired, and living in New York.

I had an excellent audience of six or seven hundred people, and talked about segregation. I did not have time to see much of the city, or note its changes. I hurried on, then, to what proved to be the central point of my trip. And that was, the experiment in Adult Education at Des Moines, Iowa.

I am a firm and even extreme believer in Adult Education. The curious assumption that a child, after learning to read, write and count, can, in a four years' high school course, or none at all, apprehend the knowledge and experience of the world, is silly. All life should be education, and there should be enough time and opportunity to let every human being study from grammar school to grave.

Moreover, the place of Adult Education is in the public school system. It was a grave mistake in New York City, and elsewhere, to try to ingraft Adult Education upon the Library. If the Library had been, as it might be, a part of an educational system, instead of an institution catering to the select few, there would have been better argument, but not good argument, even in that case.

In Des Moines, a city of a hundred thousand people, an organization of Adult Education through neighborhood and city-wide lectures, with the use of lecturers from all lands, and all walks of life, has actually reached thirty thousand people. The lectures have become widely attended public institutions. No wonder that race prejudice in Des Moines plays a small role. I stayed in an excellent hotel, and ate in the public dining room. There were, so far as I have heard, no deaths.

Kansas City shows progress. In my first visit there, over a quarter of a century ago, I saw the results of bomb-throwing, to keep colored people from living on decent streets. Later, I remember a stone wall built to mark the dead-line between white and black habitants. Today, there are evident changes. I spoke at a dinner of social workers, where nearly half the diners were white. That would have been impossible in Kansas City ten years ago. I visited the city hospital. It is a segregated racial institution; but it is large, well-built, and commodious. It is manned with Negro physicians and nurses, from top to bottom, and I am glad it is there. There may be some people who would prefer to have colored patients subordinated and mistreated in the city hospital by white physicians and white nurses. But I'm not among these people. If a city hospital were possible without discrimination as to physicians or patients, that would be ideal. But that is unthinkable today in Kansas City.

I saw Lincoln University at Jefferson City, with an astonishing young and new faculty, from the President down. It has, both advantages and disadvantages. There is a certain lack of tradition and experience; a sort of terrible newness; and on the other hand, everything seems possible. What more can one ask?

Then I went to Chicago, and spoke to some young people, who evidently had the idea that they were going to force me into a corner and make rational defense of what I believed quite impossible. It was just a bit funny.

The subject which they chose for me was, "Resolved, That the Negro Should Seek a Separate Culture in the United States." The defenders of the "49th State" were there in force, and the embattled opponents of segregation. My answer was, naturally, that the Negro should *not* seek a separate culture in the United States. And that segregation was evil, and should be systematically fought.

And then, I turned to my thesis; namely, that the members of that audience were segregated, even in the case of my lecture, and they were going to be segregated as long as they lived. And that fight as they would or ought, they had got to arrange to make the best of their life in a segregated world, and that was our present job.

I came down to Cincinnati to hear Dabney play "The Spanish Fandango," a ceremony, which, for my soul's good, I repeat as often as the Lord lets me. It was quite perfect as usual. Incidentally, I lectured in old Allen Chapel, and spoke again on Segregation.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [My Mission (1919)](/Volumes/18/01/my_mission.html)
* [The House of Jacob (1920)](/Volumes/19/04/house-of-jacob.html)
* [Y.M.C.A (1914)](/Volumes/09/02/ymca.html)
* [Brothers, Come North (1920)](/Volumes/19/03/brothers_come_north.html)
* [Segregation in the North (1934)](/Volumes/41/04/segregation_in_the_north.html)

<!-- Similar articles end here -->