
---
title: 'The Gospel According to Mary Brown'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 2
  page: 41-43
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


She was very small and pretty and black and lived in the cabin beyond the Big Road and down the lane by the creek, where one field on field of green cotton was flowering in the spring. And one night as she sat there all alone and wistful, watching the stars, a woman passed by and hailed her. She shrank back in the shadows, but the woman smiled and said full softly:

"Fear not, Mary: for thou hast found favor with God."

And then Mary knew, and she brought out the Old Book and read the lines aloud, following them with her little dark finger:

"My soul doth—magnify the Lord. ..."

"For He hath regarded the low—estate of his handmaiden, for behold from—henceforth all—generations shall call me blessed..."

Even as she read the door flew wide, and Pain stood beside her. He thrust and threw her poor little body and wracked and burst her thews in sunder. She moaned, but did not scream,---and thus at last, in years of hours, she brought forth her first---born son; and she called his name Joshua.

Day after day she sat and watched his perfect little form. Was he not a beautiful baby? His skin was black velvet; his eyes were star---sewn midnights, set in milk; his tiny teeth, white pearls; and his hair all tender tendrils of silk.

Sometimes—some very little times—a pain caught her as she cuddled him close. Would it not be better for him if he were whiter? Brown, or yellow, or dusky cream? Then she would say fiercely: No! No! Is not Love, who is God, his Father? And would his Father send a black baby to this world just to make him suffer?

And so each night after work she took him out beneath the stars, and the glory of the Lord shone round about them, and she heard the angels singing:

"Glory to God in the highest and on earth Peace, good---will toward men."

Thus did Mary, the mother, begin to dream dreams. And the child grew and waxed strong in spirit, filled with wisdom, and the grace of God was upon him.

Now his mother went to town every Christmas to settle for her crops, but it was not until he was twelve years old that he went with her, and saw town for the first. How marvelous and wonderful to him was the revelation.

Mary finished her work and started home, but Joshua tarried behind.
When Mary found him not, she turned back seeking him. After three days she found him in a church, sitting in the midst of the deacons, both hearing them and asking them questions:

Why were colored folk poor?  

Why were they afraid?  

Whose father was God?  

Did the deacons know God? Well, he did. God was his own Father.  

And all that heard him were astonished at his understanding and answers.  

But his mother said unto him:  

"Son, why did you do me this-a-way?"  

And he answered: "Wist ye not, that I must be about my Father's business."

And Mary caught her breast in pain, for how may a father he mentioned  
when one's father is only God? But she kept all his sayings in her heart.

So Joshua went back to the plantation and worked. He ploughed and  
picked cotton and hoed and drove mules and, finally, learned to be a carpenter; and always he increased in wisdom and stature and in favor with God and man.

But not, alas! with all white men. Most of them mistrusted him. They  
could not place him. He was neither sullen nor impudent. But he looked at  
them with a certain, clear understanding and calm sense of authority; he carried himself like a man, and this they resented.

"Is not this the carpenter, the son of Mary?" they asked. "Didn't we  
keep him on the plantation and out of school? And yet, he's strutting and  
talking and preaching; he's putting ideas into niggers' heads." And they  
slipped down to the old wooden church by the creek and listened to him  
preach.

The people were scattered on the green under the trees, eating their lunch  
out of baskets. And Joshua opened his mouth and taught them, saying:  

"Blessed are the poor; blessed are they that mourn; blessed are the meek;  
blessed are the merciful; blessed are they which are persecuted. All men are  
brothers and God is the Father of all."

Then all the multitude lifted up their voices and sang: "Good news, the  
Chariot's a comin'."

"What kind of talk is this?" said the White Folk, "Behold, he stirreth up  
the people."

Whereupon they took counsel together. They stopped his preaching and  
doubled his work. They cursed and drove his hearers; they warned and beat  
them.

Mary watched all this in mounting terror. She saw the hurt in Joshua's  
eyes and the bitterness in his heart. She knew that he suffered, not simply in  
himself, but with every other sufferer. That he was wounded by every sin and  
bruised by every injustice. He was oppressed and he was afflicted, yet he  
opened not his mouth. She saw him walk daily, despised and rejected of men,  
a man of sorrows and acquainted with grief. The world hid its face from him  
and esteemed him not.

Bitter, ever more bitter, grew the White Folk at his silent protest—his  
humble submission to wrong. They seized him and questioned him.  

"What do you mean by this talk about all being brothers---do you mean  
social equality?"  

"What do you mean by 'the meek shall inherit the earth'---do you mean  
that niggers will own our cotton land?"  

"What do you mean by saying God is you-all's father---is God a nigger?"

And Joshua flamed in mighty anger and answered and said: "Woe unto you, Scribes and Pharisees, hypocrites! Fill ye up then the measure of your fathers. Ye serpents, ye generation of vipers, how can ye escape the damnation of hell?"

In wild fury the mob seized him and haled him before a judge. 

The Judge---he was from the North---was sorely puzzled. "What shall I do with him?" he asked helplessly.

"Kill the nigger," yelled the mob.

"Why, what evil hath he done?"

But they cried out the more, saying: "Let him be crucified."

Thereupon the Judge washed his hands of the whole matter, saying: "I am innocent of his blood."

And so swiftly he was sentenced for treason and inciting murder and insurrection; quickly they hurried him to the jail---yard, where they stripped him, and spit upon him, and smote him on the head, and mocked, and lynched him. And sitting down, they watched him die.

And Joshua said: "Father, forgive them, for they know not what they do."

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Drama Among Black Folk (1916)](/Volumes/12/03/drama_among_black_folk.html)
* [The White Church (1917)](/Volumes/14/01/white_church.html)
* [Steve (1919)](/Volumes/17/02/steve.html)
* [The Church and the Negro (1913)](/Volumes/06/06/church_negro.html)
* [Easter-Emancipation 1863-1913 (1913)](/Volumes/05/06/easter-emancipation.html)

<!-- Similar articles end here -->