
---
title: 'The Negro Soldier'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 2
  page: 45-46
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The carefully arranged attack on the Negro soldier, delayed and somewhat disarranged by <span class="crisis-title">The Crisis</span>' revelation in May and June, was at last launched in *Harvey's Weekly*. The article consisted of a series of falsehoods and half-truths.

> The Ninety-Second Division---was the only Negro division sent to France.

This is not true. The Ninety-Third Division was also sent to France. Its organization as a division was never completed, but its four Negro regiments were the first American Negro combat troops to arrive and saw more fighting than any American units. The reason for ignoring them was because they were brigaded with the French, trained and treated like men, covered themselves with glory and returned with nearly four hundred citations for bravery.

> Negro officers in the Artillery and Engineer regiments were relieved by white officers because of inefficiency.

This is untrue. No training for Artillery or Engineering was given Negro officers in the Des Moines' training camp. When it was decided to equip a complete Negro division, naturally, there were no Negro officers trained. After repeated refusals a few received training later under great difficulties and some of these served with their troops.

> The average period allotted for training white troops in France was four weeks. The Ninety-Second was kept in the training area and seven weeks.

This is true, but the reason is tactfully omitted; the white troops were assembled and trained as full divisions in the United States before embarking; the Negroes were never assembled until they reached France and certain units, like the Artillery, were held back by War Office intrigue among persons who were determined not to let the division function. In the French training schools Negro officers made as good and better record than the whites, while Negro artillerymen held the record with seventy-fives!

The meat of this attack lies in the paragraph which asserts that in the Argonne the 368th "refused to obey orders" and "did not go forward" to attack.

To this scurrilous attack the Secretary of War has himself replied, quoting the Inspector-General who examined forty-four witnesses. The conclusions are:

1. That the 368th regiment was not assigned as an attacking force in the Argonne battle.
2. That the ground was extremely difficult and the regiment only partially equipped for battle.
3. There was no artillery support and the advance met heavy machine-gun and rifle fire.

> The circumstances disclosed by a detailed study of the situation do not justify many of the highly colored accounts which have been given of the behavior of the troops in this section, and they afford no basis at all for any of the general assumptions, with regard to the action of colored troops in this battle or elsewhere in France. On the contrary, it is to be noted that many colored officers, and particularly three in the very battalion here under discussion, were decorated with Distinguished Service Crosses for extraordinary heroism under fire.

A detailed description of this battle can be found in <span class="crisis-title">The Crisis</span>, June, 1919.

I have heard the story of this battle from the mouths of Negro officers and soldiers fresh from the hell of war and I am convinced that of all the regiments in France, black and white, none made a more desperate fight or stood a finer test of Negro manhood and leadership than the Three Hundred and Sixty-Eighth.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Soldiers (1920)](/Volumes/20/03/soldiers.html)
* [Officers (1917)](/Volumes/14/02/officers.html)
* [We Should Worry (1917)](/Volumes/14/02/we_should_worry.html)
* [To the Rescue (1916)](/Volumes/12/01/rescue.html)
* [The War History (1919)](/Volumes/18/06/the_war_history.html)

<!-- Similar articles end here -->