
---
title: 'Shillady and Texas'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 6
  page: 283-284
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There was once a man who said that if he owned Hell and Texas, he would prefer to rent out Texas and live in Hell. He may have exaggerated, but he had some supporting facts: Texas was settled by white Southerners in order to extend slave territory; it was forcibly stolen from Mexico in 1837, largely because Mexico tried to abolish slavery in 1829. Thereupon Texas became a center of the African slave trade and the "most shameful violations" of United States slave trade laws were perpetrated through Texas. During the years of Texan independence slaves were rushed in at the rate of 15,000 or more a year and the annexation of Texas and the Mexican War were movements to extend Negro slavery.

Out of this past has risen the present Texas. In that state the first public burning alive of a Negro took place, at Paris. Since 1889 Texas has lynched 338 human beings---standing second only to Georgia and Mississippi in this horrible eminence.

Notwithstanding this, the Texas Negro has forged forward. Encouraged by his first great leader, Norris Wright Cuney, he has bought 21,182 farms with nearly two million acres of land, worth $25,000,000. Starting with nothing fifty years ago nearly one-third of these black folk are now land owners.

To reward the Negroes for their thrift and struggles Texas gives them no voice in their own government, taxes them without representation and enforces "Jim-Crow" travel, more irksome than in any other state because of the immense Texas distances. The Negro schools of Texas are better than in many Southern States and there are forty-four high schools for the 690,049 Negroes of the state, but 25 per cent of the Negro population is still absolutely illiterate and according to the white Houston *Post*: "The rural schools for Negro children where they exist at all are a joke."

Is it not natural for the Negroes of such a state to endeavor to escape slavery?

 They turned to the N.A.A.C.P. quite without solicitation. We made no special effort to organize branches in Texas, but 7,000 black Texans joined us to help make twelve million Americans "physically free from peonage, mentally free from ignorance, politically free from disfranchisement and socially free from insult."

Is this revolution? Is this "stirring up trouble?" It is---in Texas, and to stop it a number of Texas gentlemen leaped on one unsuspecting, unarmed man and beat him nearly into unconsciousness, because he had come to their state to confer with colored and white people in the interests of this organization.

Mr. Shillady is a gentleman of training and experience, known to social workers all over the land. He was set upon by a judge, a constable and other officials, who have openly boasted their lawlessness and have been upheld by the Governor of the State.

This is Texas. This is the dominant white South. This is the answer of the Coward and the Brute to Reason and Prayer. This is the thing that America must conquer before it is civilized, and as long as Texas is this kind of Hell, civilization in America is impossible.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Prejudice (1911)](/Volumes/02/01/prejudice.html)
* [Slavery (1922)](/Volumes/24/01/slavery.html)
* [Houston (1917)](/Volumes/14/06/houston.html)
* [Murder Will Out (1920)](/Volumes/20/05/murder_will_out.html)
* [Carrizal (1916)](/Volumes/12/04/carrizal.html)

<!-- Similar articles end here -->