
---
title: 'The True Brownies'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 6
  page: 285-286
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The Children's <span class = "small-caps"> Crisis</span> has been published annually for nine years and is easily the most popular number of the year---that is, it makes the widest appeal to our readers. This is as it should be. Of course, we are and must be interested in our children above all else, if we love our race and humanity.

But in the problem of our children we black folk are sorely puzzled. For example, a little girl writes us---we remember her as red-bronze and black-curled, with dancing eyes---"I want to learn more about my race, so I want to begin early. … *I hate the white man just as much as he hates me and probably more!*"

Think of this from twelve little years! And yet, can you blame the child? To the consternation of the Editors of <span class = "small-caps">The Crisis</span> we have had to record some horror in nearly every Children's Number---in 1915, it was Leo Frank; in 1916, the lynching at Gainesville, Fla.; in 1917 and 1918, the riot and court martial at Houston, Tex., etc.

This was inevitable in our rôle as newspaper---but what effect must it have on our children? To educate them in human hatred is more disastrous to them than to the hated; to seek to raise them in ignorance of their racial identity and peculiar situation is inadvisable---impossible.

There seems but one alternative: We shall publish hereafter not ONE Children's Number a year, but TWELVE! Messrs. Du Bois and Dill will issue in November, in co-operation with <span class = "small-caps">The Crisis</span>, but as an entirely separate publication, a little magazine for children---for all children, but especially for ours, "the Children of the Sun."

It will be called, naturally, *The Brownies' Book*, and as we have advertised, "It will be a thing of Joy and Beauty, dealing in Happiness, Laughter and Emulation, and designed especially for Kiddies from Six to Sixteen.

> It will seek to teach Universal Love and Brotherhood for all little folk---black and brown and yellow and white.  <p> Of course, pictures, puzzles, stories, letters from little ones, clubs, games and oh---everything!

Deftly intertwined with this mission of entertainment will go the endeavor:
<ol type="a">
<li> To make colored children realize that being "colored" is a normal, beautiful thing.  
<li>   To make them familiar with the history and achievements of the Negro race.  
<li>   To make them know that other colored children have grown into beautiful, useful and famous persons.  
<li>  To teach them delicately a code of honor and action in their relations with white children.  
<li>  To turn their little hurts and resentments into emulation, ambition and love of their own homes and companions.  
<li> To point out the best amusements and joys and worth-while things of life.  
<li>  To inspire them to prepare for definite occupations and duties with a broad spirit of sacrifice.  
</ol>

This is a great program---a tremendous task. We want the advice of all mothers and fathers, of all men and women and children in helping us accomplish it. We can conceive of no more splendid duty at this critical hour.

Write us in care of *The Brownies' Book*, 2 West Thirteenth Street, New York City, and---incidentally---send a One Dollar subscription for a year.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [A Little Play (1914)](/Volumes/07/05/a_little_play.html)
* [Prejudice (1927)](/Volumes/34/09/prejudice.html)
* [The Name Negro (1928)](/Volumes/35/03/name_negro.html)
* [The New Crisis (1925)](/Volumes/30/01/new_crisis.html)
* [Counsels of Despair (1934)](/Volumes/41/06/counsels_of_despair.html)

<!-- Similar articles end here -->