
---
title: 'Officers'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 2
  page: 60-61
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Give us Negro officers for Negro troops. This is the slogan and let no specious argument turn us from it. Liars tell us that only white men can lead black men, and they tell us this in the face of the record of Sonni Ali, Touissaint L'Ouverture, General Dodd, Charles Young, and Frank Dennison. Give us Negro officers for Negro troops. 

Justice and right calls for the admission of Negroes to the civilian training camps on the same terms as white men. This right the <span class="crisis-title">Crisis</span> and Dr. Spingarn demanded from the first and we were refused. 

As the next best thing, Dr. Spingarn said: "If colored men cannot be admitted to Plattsburg and similar camps give them a camp of their own." 

<span class="crisis-title">The Crisis</span> advocated and strongly advocated this alternative. Moreover, the <span class="crisis-title">Crisis</span> wonders how on earth the wild and dapper advocates of "Jim Crow" regiments can somersault into opponents of the training of Negro officers in separate camps? 

Do they want "Jim Crow" regiments? No, but they want black soldiers and they accept separate regiments rather than forego military training. Do Dr. Spingarn and Dr. Du Bois and thousands of level-headed colored folk want a "Jim Crow" training camp? No, but they want black officers and they advocate a separate camp rather than see Negro regiments officered solely by white men. 

How easily some of us are beguiled. We are assured that the General Staff will not refuse Negro troops. It may not, but there is every evidence that it intended to in the plan drafted previous to the declaration of war which did not become law. We are told to "wait" for our camp until after all white officers are trained, and some colored papers actually rejoice at this, unable to grasp the clear fact that once enough whites are trained for all regiments, no Negroes need apply. 

Where in heaven's name do we Negroes stand? If we organize separately for anything---"Jim Crow!" scream all the Disconsolate; if we organize with white people---"Traitors! Pressure! They're betraying us!" yell all the Suspicious. If, unable to get the whole loaf we seize half to ward off starvation---"Compromise!" yell all the Scared. If we let the half loaf go and starve---"Why don't you do something?" yell those same critics, dancing about on their toes. 

It is simply silly to talk about pressure being brought to bear on the editor of the <span class="crisis-title">Crisis</span> or on anyone else to back this demand. The only "pressure" brought is the pressure of common sense. Mr. Storey, Mr. Villard, Dr. Spingarn, Mr. Loud, Mr. Kennaday, Mr. Russell, Mr. Walling, Miss Ovington, and Mr. Nash and dozens of other white men are working shoulder to shoulder in the NAACP with us black men and treating us as comrades in a great fight for human rights. It is beneath contempt for the Cleveland, Ohio, *Gazette* to suggest that their motives are not above suspicion or that the editor of the <span class="crisis-title">Crisis</span> has ever been asked by them to advocate that which he did not sincerely believe was right. Just now we demand Negro officers for Negro regiments. We cannot get them by admission to the regular training camps because the law of the land, or its official interpretation, wickedly prevents us. Therefore, give us a separate training camp for Negro officers. 

LATER: We have won! The camp is granted; we shall have 1,000 Negro officers in the United States Army! Write us for information. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Soldiers (1920)](/Volumes/20/03/soldiers.html)
* [The Negro Soldier (1919)](/Volumes/19/02/negro_soldier.html)
* [To the Rescue (1916)](/Volumes/12/01/rescue.html)
* [We Should Worry (1917)](/Volumes/14/02/we_should_worry.html)
* [Presidential Candidates (1920)](/Volumes/20/02/presidential-candidates.html)

<!-- Similar articles end here -->