
---
title: 'Resolutions of the Washington Conference'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 2
  page: 59-60
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The representatives of Negro organizations embracing many millions of men, together with their friends and fellow workers of other races, deem it fitting at this critical time in the history of our country and the world to express the attitude and aspirations which they think fitting for the twelve million Americans of Negro descent and for many other millions resident in America, in Africa, and in the islands of the sea.

We trace the real cause of this world war to the despising of the darker races by the dominant groups of men, and the consequent fierce rivalry among European nations in their effort to use darker and backward people for purposes of selfish gain regardless of the ultimate good of the oppressed. 

We see permanent peace only in the extension of the principle of government by the consent of the governed, not simply among the smaller nations of Europe but among the natives of Asia and Africa, the Western Indies and the Negroes of the United States. 

Despite the unfortunate record of England, of Belgium, and of our own land in dealing with colored peoples, we earnestly believe that the greatest hope for ultimate democracy, with no adventitious barriers of race and color, lies on the side of the Allies, with whom our country has become companion in arms. In justification of this belief we point on the one hand to the splendid democracy of France, the recent freeing of our fellow-sufferers in Russia, and the slow but steady advance of principles of universal justice in the British Empire and in our own land; and on the other hand we point to the wretched record of Germany in Africa and her preachment of autocracy and race superiority.

We, therefore, earnestly urge our colored fellow citizens to join heartily in this fight for eventual world liberty; we urge them to enlist in the army; to join in the pressing work of providing food supplies; to labor in all ways by hand and thought in increasing the efficiency of our country. We urge this despite our deep sympathy with the reasonable and deep-seated feeling of revolt among Negroes at the persistent insult and discrimination to which they are subject and will be subject even when they do their patriotic duty. 

Let us, however, never forget that this country belongs to us even more than to those who lynch, disfranchise, and segregate. As our country it rightly demands our whole-hearted defense as well today as when with Crispus Attucks we fought for independence and with 200,000 black soldiers we helped hammer out our own freedom. 

Absolute loyalty in arms and in civil duties need not for a moment lead us to abate our just complaints and just demands. Despite the gratuitous advice of the white friends who wish us to submit uncomplainingly to caste and peonage, and despite the more timid and complacent souls in our own ranks, we demand and of right ought to demand: 

1. The right to serve our country on the battlefield and to receive training for such service; 
2. The right of our best men to lead troops of their own race in battle, and to receive officers' training in preparation for such leadership; 
3. The immediate stoppage of lynching; 
4. The right to vote for both men and women; 
5. Universal and free common school training; 
6. The abolition of Jim Crow cars; 
7. The repeal of segregation ordinances; 
8. Equal civil rights in all public institutions and movements. 

These are not minor matters. They are not matters that can wait. They are the least that self-respecting, free, modern men can have and live. In asking these rights we pretend to no extraordinary desert. We are ordinary men, trained in ignorance, forced sometimes to crime, kept in poverty. Yet even so, we have blazed a great red trail to freedom, stained with our blood and sweat and a proof of our earnestness. Modern political and social rights are not rewards of merit. They are measures of protection and prerequisites to uplift. The denial of them is death and that our enemies and some of our false friends well know. 

Let our action, then, include unfaltering loyalty to our country, unbounded effort toward realizing the larger, finer objects of this world battle of America and her allies; simultaneous with this and in further, stronger determination to realize world peace and self-government, let us insist that neither the world nor America can be happy and democratic so long as twelve million Americans are lynched, disfranchised, and insulted---so long as millions of other darker folk are exploited and killed. 

In earnest confirmation of this thought and action, we call on the twelve million Negro Americans to unite with us in a great and solemn festival beginning in August, 1919, which will be three hundred years after the permanent settlement of Negroes on the American mainland. On that occasion, without exultation in the beginning of a shameful slavery, but with thankfulness for the partial fall of its shackles, let us meet and think and rejoice and solemnly resolve on the threshold of our fourth century in America to go forward toward Freedom without hesitation or compromise. 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Just Like---Folks (1920)](/Volumes/19/05/just_like_folks.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [The Strength of Segregation (1913)](/Volumes/07/03/strength_of_segregation.html)
* [The Immediate Program of the  American Negro (1915)](/Volumes/09/06/immediate_program.html)
* [Inter-Racial Comity (1922)](/Volumes/22/01/inter-racial_comity.html)

<!-- Similar articles end here -->