
---
title: 'We Should Worry'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 2
  page: 61-62
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The American Negro more unanimously than any other American group has offered his services in this war as officer and soldier. He has done this earnestly and unselfishly, overlooking his just resentment and grievous wrongs. 

Up to the present his offer has been received with sullen and ungracious silence, or at best in awkward complaisance. 

Nevertheless, the offer stands as it stood in 1776, 1812, 1861, and 1898. 

But &#11834;

Certain Americans,---Southern Bourbons, and Northern Copperheads---fear Negro soldiers. They do not fear that they will not fight---they fear that they WILL fight and fight bravely and well. Just as in Reconstruction days, it was not bad Negro voters they feared but good, intelligent ones. 

Selah! 

These Bourbons and Copperheads know that if Negroes fight well in this war they will get credit for it. They cannot "Carrizal" the news and boost the white putty-head who blundered, forgetting the very name of the brave black subalterns. No! those fool French will tell the truth and the Associated Press will not be able to edit "Niggers"; so the Copperheads and Bourbons do not want Negro soldiers. They think they can trust Southern state officers to juggle that little "agricultural laborer joker" and keep us out of the ranks. 

Very good. 

"We should worry." 

If they do not want us to fight, we will work. We will walk into the industrial shoes of a few million whites who go to the front. We will get higher wages and we cannot be stopped from migrating by all the deviltry of the slave South; particularly with the white lynchers and mob leaders away at war. 

Will we be ousted when the white soldiers come back? 

THEY WON'T COME BACK! 

So there you are, gentlemen, and take your choice, 

We'll fight or work. 

We'll fight and work. 

If we fight we'll learn the fighting game and cease to be so "aisily lynched." 

If we don't fight we'll learn the more lucrative trades and cease to be so easily robbed and exploited. 

Take your choice, gentlemen. 

"We should worry." 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Loyalty (1917)](/Volumes/14/01/loyalty.html)
* [Votes for Negroes (1921)](/Volumes/21/03/votes-for-negroes.html)
* [Officers (1917)](/Volumes/14/02/officers.html)
* [Our Special Grievances (1918)](/Volumes/16/05/our_special_greivances.html)
* [The Reward (1918)](/Volumes/16/05/reward.html)

<!-- Similar articles end here -->