---
title: 'Manifesto to the League of Nations'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: November 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 23
  issue: 1
  page: 18
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

The second Pan-African Congress which met in London, Brussels and Paris, August 28, 29 and 31 and September 2, 3, 5 and 6, represented 26 different groups of people of Negro descent: namely, British Nigeria, Gold Coast and Sierra Leone; the Egyptian Sudan, British East Africa, former German East Africa; French Senegal, the French Congo and Madagascar; Belgian Congo; Portuguese St. Thomé, Angola and Mozambique; Liberia; Abyssinia; Haiti; British Jamaica and Grenada; French Martinique and Guadeloupe; British Guiana; the United States of America, Negroes resident in England, France, Belgium and Portugal, and fraternal visitors from India, Morocco, the Philippines and Annam.

The Congress adopted two sets of resolutions differing somewhat in detail but essentially identical. The first set of resolutions (adopted unanimously at London) is presented in its original English text; the second set (discussed at Brussels and adopted unanimously at Paris) is presented in its original French text.

The Congress directed its executive officers to approach the League of Nations with three earnest requests, believing that the greatest international body in the world must sooner or later turn its attention to the great racial problem as it today affects persons of Negro descent.

First: The second Pan-African Congress asks that in the International Bureau of Labor a section be set aside to deal particularly and in detail with the conditions and needs of native Negro labor especially in Africa and in the Islands of the Sea. It is the earnest belief of the Congress that the labor problems of the world cannot be understood or properly settled so long as colored and especially Negro labor is enslaved and neglected, and that a first step toward the world emancipation of labor would be through investigation of native labor.

Secondly: The second Pan-African Congress wishes to suggest that the spirit of the modern world moves toward self-government as the ultimate aim of all men and nations and that consequently the mandated areas, being peopled as they are so largely by black folk, have a right to ask that a man of Negro descent, properly fitted in character and training, be appointed a member of the Mandates Commission so soon as a vacancy occurs.

Thirdly and finally: The second Pan-African Congress desires most earnestly and emphatically to ask the good offices and careful attention of the League of Nations to the condition of civilized persons of Negro descent throughout the world. Consciously and unconsciously, there is in the world today a widespread and growing feeling that it is permissible to treat civilized men as uncivilized if they are colored and more especially of Negro descent. The result of this attitude and many consequent laws, customs and conventions is that a bitter feeling of resentment, personal insult and despair is widespread in the world among those very persons whose rise is the hope of the Negro race.

We are fully aware that the League of Nations has little if any direct power to adjust these matters, but it has the vast moral power of world public opinion and of a body conceived to promote peace and justice among men. For this reason we ask and urge that the League of Nations take a firm stand on the absolute equality of races and that it suggest to the Colonial Powers connected with the League of Nations the forming of an International Institute for the study of the Negro Problems, and for the Evolution and Protection of the Negro Race.


[W.E. Burghardt DuBois]{.small-caps}<br>
Geneva, September 15, 1921<br>
*Secretary*

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Second Pan-African Congress (1921)](/Volumes/21/06/second-pan-african-congress.html)
* [Memorandum to M. Diagne and Others on a Pan-African Congress to be held in Paris in February, 1919 (1919)](/Volumes/17/05/memorandum_to_m_diagne_and_others_on_a_panafrican_congress.html)
* [The Pan-African Congresses: The Story of a Growing Movement (1927)](/Volumes/34/08/panafrican_congresses.html)
* [Pan-Africa (1921)](/Volumes/21/03/pan-africa.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)

<!-- Similar articles end here -->