
---
title: 'Augustus G. Dill'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 3
  page: 96
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


It is with deep regret that <span class="small-caps">The Crisis</span> announces the withdrawal with this issue of Mr. Augustus G. Dill as Business Manager. For nearly fifteen years Mr. Dill has given us loyal and efficient service. He was by nature and training the sensitive artist and musician rather than the business man and it was with hesitation that I asked him to leave his chosen vocation of teaching at Atlanta University and throw in his lot with a cause of precarious prospects. He came to The Crisis at a sacrifice and the multitudinous and often petty details of a business office in a cold and selfish city made hard demands upon his time and strength. He stuck to his job and saw its success and growth. He leaves it today with the good wishes of all his fellow workers who will always remain his sympathetic and admiring friends.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Vital Statistics (1912)](/Volumes/04/06/vital_statistics.html)
* [Marcus Garvey and the NAACP (1928)](/Volumes/35/02/marcus_garvey.html)
* [Our Economic Future (1928)](/Volumes/35/05/our_economic_future.html)
* [Marcus Garvey (1921)](/Volumes/21/03/marcus_garvey.html)
* [A Lunatic or a Traitor (1924)](/Volumes/28/01/lunatic_or_a_traitor.html)

<!-- Similar articles end here -->