
---
title: 'Augustus G. Dill'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 3
  page: 98
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


John Hays Hammond of the National Civic Federation admitted failure in his "get-out-the-vote" campaign of November, 1926. Twenty-four states fell behind the voting record of 1922 and forty-one fell far behind the record of 1924; and this happened despite a non-partisan movement backed by the largest and most powerful general organizations in the land. Twenty-one millions voted in 1922, thirty millions in 1924 and less than twenty-two millions in 1926. The eligible vote in 1926 was sixty-two millions. Only one citizen in three thought voting worth while. Americans think baseball is worth while; they think prize fighting is important; they think divorce trials and crime headlines news; but for fifty years, since the Negro was enfranchised, he and the American world have been taught that voting is a failure and democracy unequal to the task of efficient government. American after American, of wide power and influence, comes home from abroad lauding autocracy; a persistent campaign against state ownership and control of industry has had astonishing success; popular primary elections—once a triumph of democracy—are being laughed and shamed out of court.

And what does all this failure and reaction prove? It proves simply that democracy cannot function without intelligent voters who stand with the Negro in regarding the right to vote as the one great weapon and prerogative of free manhood.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Negro Voter (1928)](/Volumes/35/08/negro_voter.html)
* [Political Straws (1923)](/Volumes/26/03/political_straws.html)
* [The Campaign of 1928 (1928)](/Volumes/35/12/campaign_of_1928.html)
* [Disenfranchisement (1925)](/Volumes/30/02/disenfranchisement.html)
* [Votes (1919)](/Volumes/19/02/votes.html)

<!-- Similar articles end here -->