
---
title: 'Robert E. Lee'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 3
  page: 97
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Each year on the 19th of January there is renewed effort to canonize Robert E. Lee, the great confederate general. His personal comeliness, his aristocratic birth and his military prowess all call for the verdict of greatness and genius. But one thing---one terrible fact---militates against this and that is the inescapable truth that Robert E. Lee led a bloody war to perpetuate human slavery. Copperheads like the New York *Times* may magisterially declare: "of course, he never fought for slavery." Well, for what did he fight? State rights? Nonsense. The South cared only for State Rights as a weapon to defend slavery. If nationalism had been a stronger defense of the slave system than particularism, the South would have been as nationalist in 1861 as it had been in 1812.

No. People do not go to war for abstract theories of government. They fight for property and privilege and that was what Virginia fought for in the Civil War. And Lee followed Virginia. He followed Virginia not because he particularly loved slavery (although he certainly did not hate it), but because he did not have the moral courage to stand against his family and his clan. Lee hesitated and hung his head in shame because he was asked to lead armies against human progress and Christian decency and did not dare refuse. He surrendered not to Grant, but to Negro Emancipation.

Today we can best perpetuate his memory and his nobler traits, not by falsifying his moral debacle, but by explaining it to the young white South. What Lee did in 1861, other Lees are doing in 1928. They lack the moral courage to stand up for justice to the Negro because of the overwhelming public opinion of their social environment. Their fathers in the past have condoned lynching and mob violence, just as today they acquiesce in the disfranchisement of educated and worthy black citizens, provide wretchedly inadequate public schools for Negro children and endorse a public treatment of sickness, poverty and crime which disgraces civilization.

It is the punishment of the South that its Robert Lees and Jefferson Davises will always be tall, handsome and well-born. That their courage will be physical and not moral. That their leadership will be weak compliance with public opinion and never costly and unswerving revolt for justice and right. It is ridiculous to seek to excuse Robert Lee as the most formidable agency this nation ever raised to make 4 million human beings goods instead of men. Either he knew what slavery meant when he helped maim and murder thousands in its defense, or he did not. If he did not he was a fool. If he did, Robert Lee was a traitor and a rebel---not indeed to his country, but to humanity and humanity's God.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Lee (1912)](/Volumes/03/05/lee.html)
* [Remember (1920)](/Volumes/19/06/remember.html)
* [Emancipation (1913)](/Volumes/05/03/emancipation.html)
* [Tillman (1918)](/Volumes/16/04/tillman.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)

<!-- Similar articles end here -->