
---
title: 'Chicago'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 4
  page: 131
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




The late Chicago election was a serious misfortune. The Democratic mayor had previously made overtures to colored people. He had even spoken at the annual N.A.A.C.P. Conference. Thompson, the Republican, is a well-known demagogue, who represents open house to gamblers, bootleggers and prostitutes. Wise white Americans would have advised colored people in a campaign of this sort to vote for the Democrats. If they had been permitted, many far-sighted Negroes would have taken this advice. Indeed the most astute Negro politician in Chicago fought Thompson to the last in the Republican Primary and lost his city patronage when Thompson won.

The silly Democrats of Chicago did not think that the intelligent Negro vote would be as valuable to them as the votes of the Negro haters and the Ku Klux Klan. They therefore flooded the city with anti-Negro propaganda; they sang "Bye-Bye, Blackbirds" everywhere. They sent out placards saying: "Don't vote yourselves Nigger wages"; they distributed cartoons of a train loaded with Negroes and the legend: "Big Bill's express will start for Chicago April 6th unless you stop it April 5th"; and then they asked white voters if they wanted Negro teachers to teach their children; if they wanted Negroes to work in the stock yards and the factories; if they could stand a colored judge, two colored aldermen, a colored Senator and 6 colored representatives. They pointed to 300 colored policemen and 200 colored firemen and other colored civilian employees. They issued dodgers showing Mayor Thompson kissing a black baby and bearing the statement: "Thompson, Africa first."

What was the result of this campaign? It resulted in bringing in race and national propaganda of other sorts: attacks upon England; appeals to the bitter memories of Germans and the like. But above all, it forced every Negro voter, no matter what his attitude toward Thompson was, to vote for Thompson and against Dever. He did not even dare throw his vote away on a third candidate. He was compelled to deliver himself bound hand and foot to one of the worse representatives of the Republican machine.



All of which brings us to remark: that for bull-headed asininity, commend us to the Democratic party; only in New York City and in Tammany Hall does it appear to have glimmerings of common sense.

