
---
title: 'The Lynching Industry'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 4
  page: 196,198
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



<span class="small-caps">The Crisis</span> is interested to report that the standard American industry
of lynching colored men has flourished during the year 1914. There is,
of course, the usual difference of opinion ns to the number of its
victims. Tuskegee reluctantly admits 52; the Chicago *Tribune* notes 54;
<span class="small-caps">The Crisis</span> finds 74, of whom 69 were colored and 5 white. Of the 69,
four were colored women. The following is a list of the lynchings and
those starred are unrecorded in the Chicago *Tribune* list; with regard
to five of these of unknown name there is it bare possibility of
duplication or mistake, but this does not seem probable:

## **COLORED MEN LYNCHED IN 1914**

Jan.
* Okla.---Dickerson, murder.
* N. C.---Wilson, murder.
* Fla.---Peck, assault.
* Fla.---James, assault.
* Tex.---Lee, assault.
* Ga.---Harris, murder.

Feb.
* Miss.---Petty, murder.
* Miss.---Johnson, murder.

March
* Mo.---Shields, murder.
* Miss.---Unknown, murder.
* Ala. Young, rape.
* Okla.---Scott, murder

April
* Miss.---Turner, assault.
* Miss.---Unknown, race riot.
* Miss.---Unknown, race riot.
* Tex.---Morgan, assault

May
* La.---Washington, murder.
* Ga.---Jones, theft.
* La.---Hamilton, rape.
* Fla.---Woodsome, unlawful entry.

June
* Miss.---Smith, robbery.
* Miss.---Collins, resistance.

July
* Miss.---Bailey, theft.
* S. C.---Carson, murder.

August
* Okla.---Williams, murder.
* La.---Griffin, murder.
* La.---Hall, murder.
* La.---Holmes, murder.
* La.---Unknown, murder.
* La.---Romeo, murder.
* Miss.---Robinson, murder.
* Ala.---Unknown, "running amuck."

Sept.
* Ala.---Baines, robbery.
* Ga.---Brown, murder.

Oct.
* Fla.---Junior, rape.
* Miss.---Miller, rape.
* Ark.---Davis, murder.
* Ala.---Unknown, assault.
* Ark.---Unknown, murder.
* Ark.---Unknown, murder.
* Tex.---Durfee, murder.

Nov.
* Miss.---Burns, assault.
* Ky.---10 unknown Negroes by night-riders.
* Fla.---Evans, rape.
* Ky.---Allen, by night-riders.
* S. C.---Wilson, murder.
* Miss.---Sullivan, arson.
* Miss.---Sullivan, arson.

Dec.
* La.---McKnight, murder.
* La.---T. Lewis, murder.
* La.---Dirden, murder.
* La.---W. Lewis, murder.
* La.---Washington, murder.
* La.---Henderson, murder.
* Ala.---Jones, unlawful entry.
* R. C.---Green, intent to steal.
* S. C.---Seymour, rape.
* Miss.---Williams, assault.

**Total**--- 69

## **NUMBER BY MONTHS**

|       |    |
|-------|---:|
| Jan.  |6   |
| Feb.  | 2  |
| Mch.  | 5  |
| Apr.  | 4  |
| May   | 4  |
| June  | 3  |
| July  | 2  |
| Aug.  | 8  |
| Sept. | 2  |
| Oct.  | 7  |
| Nov.  | 16 |
| Dec.  | 10 |

## **NUMBER BY STATE**

|       |    |
|-------|---:|
| Miss. | 15 |
| La.   | 13 |
| Ky.   | 11 |
| Fla.  | 5  |
| Tex.  | 5  |
| Ala.  | 5  |
| S. C. | 4  |
| Ark.  | 3  |
| Okla. | 3  |
| Ga.   | 3  |
| N. C. | 1  |
| Mo.   | 1  |

## **NUMBER BY CRIMES**

|                                                     |    | Percentage |
|-----------------------------------------------------|---:|-----------:|
| Murder                                              | 30 | 44         |
| By rioters and nightriders                          | 13 | 19         |
| Personal assaults                                   | 10 | 14         |
| Rape,attempts to rape and presence in women's rooms | 8  | 11.5       |
| Robbery and theft                                   | 5  | 7          |
| Arson                                               | 2  | 3          |
| Resistance to search                                | 1  | 1.5        |

## **LYNCHED BY YEARS, 1885-1914**

| &nbsp;    |  &nbsp;  |
|------|----:|
| 1885 | 78  |
| 1886 | 71  |
| 1887 | 80  |
| 1888 | 95  |
| 1889 | 95  |
| 1890 | 90  |
| 1891 | 121 |
| 1892 | 155 |
| 1893 | 154 |
| 1894 | 134 |
| 1895 | 112 |
| 1896 | 80  |
| 1897 | 122 |
| 1898 | 102 |
| 1899 | 84  |
| 1900 | 107 |
| 1901 | 107 |
| 1902 | 86  |
| 1903 | 86  |
| 1904 | 83  |
| 1905 | 61  |
| 1906 | 64  |
| 1907 | 60  |
| 1908 | 93  |
| 1909 | 73  |
| 1910 | 65  |
| 1911 | 63  |
| 1912 | 63  |
| 1913 | 79  |
| 1914 | 69  |

**Total**--- 2,732

These lynchings produce the usual little pleasantries with which the
American nation is so familiar. Murder, for instance, sounds very awful
and yet we must remember that one of those lynched for murder was killed
in defence of a colored woman's honor. In another case a marshal had
already shot a man whom he was about to arrest. The man then killed
him and was promptly lynched. In two Florida cases proof that the
lynched men were innocent came after they were dead. Blood hounds and
posses have been responsible for desperate resistance on the part of men
afterward lynched, and in one case the man who had been respited on
account of doubt of his gruilt was promptly killed by the mob.

The so-called assaults were to a considerable extent fights where the
white man was worsted. One constable received a flesh wound and his
assailant was lynched, whereupon the constable promptly recovered.
Another white man suffered the indignity of being struck by a hoe, and
still another of having his chin bitten off. The assailants in both
cases were killed with great enthusiasm.

Attacks on property are most irritating, and one boy who stole a pair of
shoes suffered the same fate as a man who stole a
couple of mules. Mules are quite valuable in Mississippi. In the very
recent lynchings in Louisiana it would seem that the search for a
missing $500 was the chief motive. The burning of a barn in Mississippi
resulted in two lynchings.

The chivalry of southern white manhood toward colored women has been
particularly conspicuous this season. Two men raped a colored girl in
Oklahoma. One was killed by her brother and their friends thereupon
*lynched the girl!* A Mississippi mob killed a wife along with her
husband, leaving a four-year-old child motherless, while in another case
a colored woman who had the impudence to refuse to allow her home to be
searched was summarily dealt with.

On the other hand, white womanhood received its usual protection. An
impudent porter pushed a white woman off the sidewalk and was lynched.
In two cases colored men were found in white women's rooms. They were
immediately charged with "attempted" rape and killed.

Human bonfires have been made in three or four cases: one in Georgia,
one in Mississippi, and one in Louisiana. In Louisiana the victim was a
nice old man of the "uncle" type which the white South particularly
loves. A theatrical company playing "Potash and Perlmutter" made an
excursion to the entertainment and several society women were present.

All this goes to show how peculiarly fitted the United States is for
moral leadership of the world; for putting to shame the dreadful people
who are fighting in Europe and seem quite lost to decency. It is a fine
thing to have under these circumstances the stern cool leadership of
President Wilson, who has recently raised his finger and with a sad look
on his benevolent face told the South "as a Southerner" that they must
"know the needs of the Negro and sympathetically help him in every way
that is possible for his good and for our good." The President ended
with a charming story from Charles Lamb.

