
---
title: 'The President'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 4
  page: 181
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



It is difficult to see how any clear-minded American can longer doubt the
insincerity of President Wilson so far as the American Negro is
concerned. With those of us who were most determined to keep our faith
in the President the doubt has been growing steadily. At first, with
his clear utterances to colored delegations and his letters during the
campaign, it seemed impossible that so high-minded and scholarly a man
could repudiate these plain, straightforward words. If they had been
voiced by the ordinary type of politician we should justly have regarded
them with suspicion; but here was a man who, despite his southern birth,
his academic exclusiveness, and his presidency of a Negro-hating
institution, nevertheless seemed so fine a type of cultured and honest
American that there appeared absolutely no reason for doubting that he
would fulfill his word to the letter and treat the Negro with absolute
fairness.

When, at the very outset of his administration he failed to do this, we
put the blame on his southern subordinates and pressed him for some
clear, outward sign or word which would prove his honesty of purpose. We
were fed on quiet assurances of good will, unaccompanied by any
supporting action. Finally, we had the extraordinary declaration of
national "Jim-Crow" policy made to Mr. Trotter, but made as we hoped
under such stress of feeling as to be not altogether taken at face
value.

When, however, Mr. Wilson, after careful thought and preparation summons before him The University Commission on -Southern Race Questions and gives utterances to the utterly banal assertion that we must "know the needs" of the Negro and
"sympathetically help him" with the amazing qualification of restricting
help to "sensible" lines---all this shows neither the statesman nor the
sincere man, but the man who either not daring or not caring to utter
clear, strong words for or against ten million people, contents himself
with shifty and unmeaning platitudes. The whole affair is one of the
most grievous disappointments that a disappointed people must bear.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Presidential Candidates (1916)](/Volumes/13/01/presidential_candidates.html)
* [William Monroe Trotter (1914)](/Volumes/09/02/trotter.html)
* [Mr. Taft (1911)](/Volumes/02/06/taft.html)
* [An Open Letter to Woodrow Wilson (1913)](/Volumes/05/05/open_letter.html)
* [Letters (1919)](/Volumes/17/01/letters.html)

<!-- Similar articles end here -->