
---
title: 'Suffrage and Women'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 4
  page: 192
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The woman suffrage movement this year needs special protection against
its fool friends. One friend of suffrage has issued a circular asking if
the New York electorate would be improved if the women voted. She proves
that it would be improved to her own satisfaction by showing that it
would increase the native-born white vote, decrease the foreign-born
white vote, leave the colored vote the same and not increase the vote of
criminals. We assume that the author will circulate this remarkable
leaflet on the East side and in Harlem.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Woman''s Suffrage (1913)](/Volumes/06/01/womans_suffrage.html)
* [Votes for Women (1918)](/Volumes/15/01/votes_for_women.html)
* [Woman Suffrage (1915)](/Volumes/11/01/woman_suffrage.html)
* [The Risk of Woman Suffrage (1915)](/Volumes/11/01/risk_of_woman_suffrage.html)
* [Woman Suffrage (1915)](/Volumes/09/06/womansuffrage.html)

<!-- Similar articles end here -->