---
title: 'Cowardice'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 6
  page: 270-271
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


No colored man can read an account of the recent lynching at Gainesville, Fla., without being ashamed of his people.

The action was characteristic. White officers, knowing themselves in the wrong and afraid of the resistance of colored men, sneaked in at midnight to serve a warrant on a person who they hoped would be helpless and ignorant of their intentions. Two of them seized the man in his house and after the melee one of the white men was dead and the other seriously wounded. Of the right and wrong of this no one will ever be really sure. There is no proof that the black man was guilty; there is no proof that he knowingly resisted arrest. There is proof, on the other hand, that after this extraordinary attack his colored fellows acted like a set of cowardly sheep. Without resistance they let a white mob whom they outnumbered two to one, torture, harry and murder their women, shoot down innocent men entirely unconnected with the alleged crime, and finally to cap the climax, they caught and surrendered the wretched man whose attempted arrest caused the difficulty.

No people who behave with the absolute cowardice shown by these colored people can hope to have the sympathy or help of the civilized folk. The men and women who had nothing to do with the alleged crime should have fought in self-defense to the last ditch if they had killed every white man in the county and themselves been killed. The man who surrendered to a lynching mob the victim of the sheriff ought himself to have been locked up.

In the last analysis lynching of Negroes is going to stop in the South when the cowardly mob is faced by effective guns in the hands of the people determined to sell their souls dearly.


::: epigraph

It may be a good thing to forget and forgive; but it is altogether too easy a trick to forget and be forgiven.

-- G.K. Chesterton
:::

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Mob Tactics (1927)](/Volumes/34/06/mob_tactics.html)
* [Peonage (1916)](/Volumes/11/06/peonage.html)
* [The Challenge of Detroit (1925)](/Volumes/31/01/challenge_of_detroit.html)
* [The Old Story (1911)](/Volumes/01/03/old_story.html)
* [Crime (1920)](/Volumes/19/04/crime.html)

<!-- Similar articles end here -->