
---
title: 'Migration'
author: Du Bois, W.E.B.
date: Apr. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 6
  page: 270
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


It has long been the custom of colored leaders to advise the colored people to stay in the South. This has been supplemented by the startling information on the part of southern whites
that they are the "best friends of the colored people," etc.

We might as well face the facts squarely: If there is any colored man in the South who wishes to have his children educated and who wishes to be in close touch with civilization and who has any chance or ghost of a chance of making a living in the North it is his business to get out of the South as soon as possible. He need not seek for reasons for so doing. The same reasons that drive the Jew from Russia, the peasants from Austria, the Armenians from Turkey and the oppressed from tyranny everywhere should drive the colored man out of the land of lynching, lawlessness and industrial oppression.

It would, of course, be foolish for a man to give up a good chance of making a living and migrate to a country where he had little or no chance. But we are speaking of the case where men have an opportunity. These opportunities at present are widening in the North. Every single colored man who can should take advantage of it. The only effective protest that the Negroes en masse can make against lynching and dis­franchisement is through leaving the devilish country where these things take place.

The colored people of the North on the other hand, should welcome their escaping fellows. It means, undoubtedly, increased hardships for them; it will be proscription and temporary difficulties, but anything that means freedom to black slaves should be welcomed by their free northern brothers.

