
---
title: 'The Negro Party'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 6
  page: 267-268
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There is for the future one and only one effective political move for colored voters. We have long foreseen it, have sought to avoid it. It is a move of segregation, it "hyphenates" us, it separates us from our fellow Americans; but self-defense knows no nice hesitations. The American Negro must either vote as a unit or continue to be politically emasculated as at present.



Miss Inez Milholland, in a recent address, outlined with singular clearness and force a Negro Party on the lines of the recently formed Woman's Party. Mr. R. R. Church, Jr., of Tennessee, and certain leading colored men in New Jersey, Ohio and elsewhere have unconsciously and effectively followed her advice.

The situation is this: At present the Democratic party can maintain its ascendency only by the help of the Solid South. The Solid South is built on the hate and fear of Negroes; consequently it can never, as a party, effectively bid for the Negro vote. The Republican party is the party of wealth and big business and, as such, is the natural enemy of the humble working people who compose the mass of Negroes. Between these two great parties, as parties there is little to choose.

On the other hand, parties are represented by individual candidates. Negroes can have choice in the naming of these candidates and they can vote for or against them. Their only effective method in the future is to organize in every congressional district as a Negro Party to endorse those candidates, Republican, Democratic, Socialist, or What-not, whose promises and past performances give greatest hope for the remedying of the wrongs done the Negro race. If no candidate fills this bill they should nominate a candidate of their own and give that candidate their solid vote. This policy effectively and consistently carried out throughout the United States, North and South, by colored voters who refuse the bribe of petty office and money, would make the Negro vote one of the most powerful and effective of the group votes in the United States.

This is the program which we must follow. We may hesitate and argue about it, but if we are a sensible, reasonable people we will come to it and the quicker the better.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Negro in Politics (1929)](/Volumes/36/11/negro_in_politics.html)
* [The Republican Party (1918)](/Volumes/15/06/republican_party.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [How Shall We Vote (1920)](/Volumes/20/05/how_shall_we_vote.html)
* [The Next Step (1913)](/Volumes/06/02/next_step.html)

<!-- Similar articles end here -->