
---
title: 'The Presidential Campaign'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 6
  page: 268
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The Negro voter enters the present campaign with no
enthusiasm. Four years ago the intelligent Negro voter tried a great and
important experiment. He knew that the rank and file of the Bourbon
democracy was without sense or reason, based on provincial ignorance and
essentially uncivilized, but he saw called to its leadership a man of
high type and one who promised specifically to American Negroes,
justice---"Not *mere grudging justice, but justice executed with liberality and cordial good feeling."* They have lived to learn that
this statement was a lie, a peculiarly miserable campaign deception.
They are forced, therefore, to vote for the Republican candidate, Mr.
Hughes, and they find there little that is attractive.

Mr. Hughes is a northern man of sterling honesty, but he knows nothing
about Negroes and he has neither time nor inclination to learn. His
final conclusions concerning them were made twenty or thirty years ago.
Since that time he has neither examined these conclusions nor is there
any reason to suppose that he will. Under ordinary circumstances the
Negro must expect from him, as chief executive, the neglect,
indifference and misunderstanding that he has had from recent Republican
presidents. Nevertheless, he is practically the only candidate for whom
Negroes can vote. We say nothing concerning the Socialist candidate.
They are excellent leaders of an excellent party; God send them success!
But the effective voter has a choice between two parties, the vote for
the third party is at least temporarily thrown away.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Negro in Politics (1929)](/Volumes/36/11/negro_in_politics.html)
* [Mr. Hughes (1916)](/Volumes/13/01/mr_hughes.html)
* [The Strategy of the Negro Voter (1933)](/Volumes/40/06/strategy_of_the_negro_voter.html)
* [Presidential Candidates (1916)](/Volumes/13/01/presidential_candidates.html)
* [Votes (1919)](/Volumes/19/02/votes.html)

<!-- Similar articles end here -->