
---
title: 'In Black'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 20
  issue: 6
  page: 263-266
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


It was in Chicago. John Haynes Holmes was talking.

He said: "I met two children---one as fair as the dawn---the other as beautiful as the night." Then he paused. He had to pause for the audience guffawed in wild merriment.
Why?

It was a colored audience. Many of them were black. Some black faces there were as beautiful as the night.

Why did they laugh?

Because the world had taught them to be ashamed of their color.

Because for 500 years men had hated and despised and abused black folk.

And now in strange, inexplicable transposition the rising blacks laugh at themselves in nervous, blatant, furtive merriment.

They laugh because they think they are expected to laugh---because all their poor hunted lives they have heard "black" things laughed at.

Of all the pitiful things of this pitiful race problem, this is the pitifulest. So curious a mental state tends to further subtleties. Colored folk, like all folk, love to see themselves in pictures; but they are afraid to see the types which the white world has caricatured. The whites obviously seldom picture brown and yellow folk, but for five centuries they have exhausted every ingenuity of trick, of ridicule and caricature on black folk: "grinning" Negroes, "happy" Negroes, "gold dust twins," "Aunt Jemimas," "solid" headed tacks---everything and anything to make Negroes ridiculous. As a result if <span class="crisis-title">The Crisis</span> puts a black face on its cover our 500,000 colored readers do not see the actual picture---they see the caricature that white folks intend when *they* make a black face. In the last few years a thoughtful, clear eyed artist, Frank Walts, has done a number of striking portraits for <span class="crisis-title">The Crisis</span>. Mainly he has treated black faces; and regularly protests have come to us from various colored sources. His lovely portrait of the bright-eyed boy, Harry Elam, done in thoughtful sympathy, was approved by few Negroes. Our photograph of a woman of Santa Lucia, with its strength and humor and fine swing of head, was laughed at by many.

Why?

"O---er---it was not because they were black," stammer some of my office companions, "but they are *too* black. No people were ever so------"

Nonsense! Do white people complain because their pictures are too white? They ought to, but they do not. Neither do we complain if we are photographed a shade "light".

No. It is not that we are ashamed of our color and blood. We are instinctively and almost unconsciously ashamed of the caricatures done of our darker shades. Black *is* caricature in our half conscious thought and we shun in print and paint that which we love in life. How good a dark face looks to us in a strange white city! How the black soldiers, despite their white French sweethearts, yearned for their far-off "brown-skins". A mighty and swelling human consciousness is leading us joyously to embrace the darker world, but we remain afraid of black pictures because they are the cruel reminders of the crimes of Sunday "comics" and "Nigger" minstrels.

Off with these thought-chains and inchoate soul-shrinkings, and let us train ourselves to see beauty in black.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Precept and Practice (1910)](/Volumes/01/02/precept_and_practice.html)
* [The True Brownies (1919)](/Volumes/18/06/true_brownies.html)
* [The Colored Audience (1916)](/Volumes/12/05/coloured_audience.html)
* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)
* [Triumph (1911)](/Volumes/02/05/triumph.html)

<!-- Similar articles end here -->