---
title: 'Steal'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Oct. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 20
  issue: 6
  page: 261-262
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

We trust the Negro world has watched with intelligent comprehension the extraordinary conjunction of Church and Steel in recent events. When the Interchurch movement came <span class="crisis-title">The Crisis</span> was dumb with astonishment. Was it possible that the white followers of Jesus Christ were actually going to forget Infant Damnation and Justification by Faith long enough to work together for education, the abolition of child labor, opposition to race prejudice, co-operation in national missionary effort, social uplift and fair wages? As the survey progressed and the Negro and Africa were included and, too, not in the appendix, it looked as though the Christian Church was about to be reborn.

Of course, we expected the white southern Baptists to refuse co-operation. They are too much interested in lynching and immersion to heed the call of the black and the poor. But the movement grew and swelled and swept until it struck hard Steel. Until it struck Steal.

Rich holders of steel securities in northern churches were exactly like hirers of black and disfranchised Negro peons in southern churches. "Hands off" is their common cry when you touch "wages and unions" or "the Negro problem". These two things have "nothing to do with religion".

So when the Interchurch movement investigated the Steel strike, where Negroes, underpaid and disfranchised in the South, were induced to "scab" in Pennsylvania and Ohio and break the ranks of Union labor, and when it was proven that Mr. Gary or somebody lied and lied roundly and extensively --- this was too much. The Interchurch movement was suddenly found extravagant. First, the perfect Presbyterians withdrew their spotless skirts and then in a weird procession followed criticism, rumor and withdrawal until at last the white Church shrank in horror from this smoking Hell of Steel. Christianity again was crucified. How long, O Lord, how long!
