---
title: 'Triumph'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Oct. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 20
  issue: 6
  page: 261
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

# Triumph

At last the work of Susan B. Anthony and Frederick Douglass is crowned. From this day on in the United States a grown human being has the right to a voice in his own government, even if he is a woman.

Who oppose Woman Suffrage? With but few exceptions those states which oppose the abolition of child labor, the raising of the age of consent and universal education; those which advocate and practice lynching, mob violence and government by minority. These states are: 

|              |            |
|--------------|------------|
| Alabama      | Virginia   |
| Georgia      | Maryland   |
| Mississippi  | Delaware   |
| South Carolina | North Carolina |
|              | Louisiana  |

How slowly the world moves in the commonest matters of elementary righteousness. To think that we had to wait until 1920 for Woman Suffrage and then got it by two votes! Yet in this very fact lies hope for us: A civilization that required nineteen centuries to recognize the Rights of Women can confidently be expected some day to abolish the Color Line.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Woman Suffrage (1920)](/Volumes/19/05/woman_suffrage.html)
* [Woman Suffrage (1915)](/Volumes/11/01/woman_suffrage.html)
* [Woman Suffrage (1915)](/Volumes/09/06/womansuffrage.html)
* [Our Program (1930)](/Volumes/37/05/our_program.html)
* [Suffering Suffragettes (1912)](/Volumes/04/02/suffering_suffragettes.html)

<!-- Similar articles end here -->