
---
title: 'The Cause of Lynching'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 8
  issue: 3
  page: 126-127
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


It is exceedingly difficult to get at the real cause of lynching but <span class = "small-caps">The Crisis</span> is more and more convinced that the real cause is seldom the one In the barbaric Oklahoma case of the lynching of a woman, the press despatches made it a quarrel in a "redlight" district, but two private letters in our hands from apparently trustworthy persons declare that it was the case of a seventeen-year-old girl defending her own honor.

From Shreveport there are newspaper accounts of a horrible lynching of a Negro boy for attacking a ten-year-old child. But again a private letter tells us that the girl was old enough to be ticket seller in a theatre; that she was not injured in the slightest degree, but was found "hale and hearty and singing" the day after; and that, as a matter of fact, the boy was lynched because of his relations with another and older white woman.

We have no way of proving these assertions; but they have many ear-marks of truth and their very assertion is an astounding indictment of modern American barbarism. <span class = "small-caps">The Crisis</span> knows that Negroes are human and it does not for a moment presume that every Negro accused of a horrible crime is innocent. It wants, and wants for the sake of colored people even more than of others, that colored criminals be treated so as to decrease crime, whatever that treatment may be. It is painfully significant that of all methods of suppressing crime lynching has certainly failed in Shreveport; in that city and parish seven Negroes have been lynched in two years, not counting ordinary murders.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Lynching (1914)](/Volumes/07/05/lynching.html)
* [Lynchings and Mobs (1921)](/Volumes/22/04/lynchings.html)
* [Lynchings (1932)](/Volumes/39/02/lynchings.html)
* [Scottsboro (1934)](/Volumes/41/01/scottsboro.html)
* [Crime and Lynching (1912)](/Volumes/03/03/crime_and_lynching.html)

<!-- Similar articles end here -->