
---
title: 'College Education'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 8
  issue: 3
  page: 128
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The training of youth---the revelation of life, its present technique and
its future possibilities to growing young people---is a matter of
intricacy and difficulty to any people. But it is peculiarly difficult
to colored Americans who must, in addition, teach of invisible bonds and
concealed social barriers, of worlds within worlds and dangerous waste
places, of subtle temptations and unnatural restraints. Every
artificially increased difficulty that surrounds colored children to-day
should be additional incentive to make their education and mental
development the highest possible. Only in the higher intellectual life
of to-day can they hope to find that freedom, fellowship and joy which
fiendish ingenuity cuts out of so much of their work, their amusements
and their daily walks.

The colored people should strain every nerve to send their children
through the best colleges. No matter what avenues of employment may be
closed to them, give them thorough intellectual training according to
their very best standards; then let them dig. cook and sew. Make them
men even if they have to be menials. In the long run they will burst
their bonds and be modern free men. But train them so that in the day of
sundered bonds they can take their place beside their fellows and not be
held back then by ignorance as they are now by prejudice.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Reconstruction (1919)](/Volumes/18/03/reconstruction.html)
* [Education (1911)](/Volumes/01/04/education.html)
* [The Common School (1918)](/Volumes/16/03/common_school.html)
* [Counsels of Despair (1934)](/Volumes/41/06/counsels_of_despair.html)
* [Philanthropy and Self Help (1918)](/Volumes/16/03/philanthropy_and_self_help.html)

<!-- Similar articles end here -->