
---
title: 'Real Estate in New York'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 8
  issue: 3
  page: 128
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



If the Negroes are to keep what little they have gained in the right to occupy decent dwelling places on the island of Manhattan, they would better be up and doing.

For a long time the widespread conspiracy of real-estate agencies has been seeking to attack the dwelling places of colored people in Harlem. Every effort has been made artificially to depress the value of real estate in that section, and financial institutions, including those which carry thousands of dollars belonging to colored people on deposit, have refused to renew the most reasonable mortgage propositions. If the Negro was a large capitalist like the Jew he could reap great advantage from this campaign by simply buying up this depressed property. Some day, through widespread co-operation, colored people will learn to do this.

To-day the real-estate sharks know that this is impossible and they are counting on this fact. Lately a second step has been taken which is to organize a holding company to control the mortgages and sometimes the property of such owners as are willing to eject Negro tenants. Of course, a little salve of hypocrisy was needed to help in the bolting of this morsel. Consequently, the white Y.M.C.A. was found ready to furnish a hall for the meeting of these philanthropists and the scheme of "Negro uplift" was announced with a flourish, a part of which proposed the colonization of all colored people in New York on the pestilential mud flats of Harlem, where with all the city's crowding no one up to this time has been willing to live.

But the 100,000 colored people of New York still have the whip hand if they will only remember this: It is simply necessary for colored families and institutions to hold the property now occupied not everywhere but at certain strategic points. Of course the matter of holding property at such strategic points is difficult but possible. If the property of the Negro churches is held and the Y.M.C.A. really intends to put its building in a decent site in Harlem and the Y.W.C.A. follows suit, and if the Colored Music School Settlement buys a home---all this and other possible co-operative effort will settle the matter for a long time.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Tenements (1916)](/Volumes/12/02/tenements.html)
* [Homes (1912)](/Volumes/03/05/homes.html)
* [Investments (1921)](/Volumes/22/05/investments.html)
* [Hyde Park (1920)](/Volumes/19/06/hyde_park.html)
* [Work for Black Folk in 1914 (1914)](/Volumes/07/04/work_for_black_folk.html)

<!-- Similar articles end here -->