# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Dare You Fight&#58;<br/>W.E.B. Du Bois<br/>in The Crisis
#title: Dare you Fight - W.E.B. Du Bois in The Crisis
author: William E. Burghardt Du Bois
logo: logo.png

exclude_patterns: ["*.ipynb", "background.md"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
parse:
  myst_enable_extensions:
    - smartquotes


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/nealcaren/fightordie   # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  extra_navbar: ""
  favicon: favicon.ico
  extra_footer: "Edited by Neal Caren"

sphinx:
  config:
    language: en
    html_show_copyright: false
