project:
  type: website

website:
  title: "Dare You Fight"
  navbar:  
    logo: Images/logo.png
    href: https://www.dareyoufight.org
    right:
    - about.qmd
    - listing.qmd
    - covers.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    fontsize: 1.25em
    mainfont: 'Roboto'


