#!/bin/bash

conda run -n crisis  jupyter-book clean  .
#conda run -n crisis jupyter-book build ./

#conda run -n tmwp jupyter nbconvert --to notebook --execute clean.ipynb

#git add .
#git commit -m 'new articles'
#git push
#conda run -n crisis ghp-import -n -p -f _build/html -c www.dareyoufight.org
conda run -n crisis jupyter-book build ./  --builder pdflatex
