
---
title: 'Divine Right'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 5
  page: 197
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


We would like to know what rights the white people of this land are going to be able to retain? Step by step their dearest and most cherished prerogatives are being invaded, and <span class="small-caps">The Crisis</span> wants to say right here and now that it does not countenance oppression of the downtrodden whites by arrogant black folk. A few years ago the right to kick a darky off the sidewalk was unquestioned in the most devout circles, and yet to-day they actually complain at being called by their front names.

Everybody knows that for three hundred years the most jealously guarded right of white men in this land and others has been the right to seduce black women without legal, social or moral penalty. Many white mothers and daughters of the best families have helped to maintain this ancient and honored custom by loading the victims of their fathers' and husbands' lust with every epithet of insult and degradation. Thus has the sweet cleanness of their own race virtue shone holier and higher.

Yet what do we see to-day? The black husbands and brothers are beginning to revolt. In three separate cases, in three consecutive months and in three localities of the southern South have these blind and ignorant fellows actually killed white men who were demanding these ancient rights, and have compelled the chivalry of the land to rise and lynch the black defenders of defenceless virtue; also two strangely illogical black women have been simultaneously killed and a dark and whimpering little girl burned to a quivering crisp.

What does all this mean? Does it portend an unthinkable time when the white man can only get his rights by lynching impudent black husbands and squeamish sweethearts? If so, then, by the Great Jehovah, we can depend on the best friends of the Negro to vindicate the ancient liberties of this land! Anglo-Saxon freedom seems safe at least in the hands of most leaders of Southern society, not to mention the blue blood of Pennsylvania.

Meantime, dear colored brethren, we confess to the error of our ways. We have steadfastly opposed lynching on all occasions, but the South is converting us. We acknowledge our fault. Hereafter we humbly pray that every man, black or white, who is anxious to defend women, will be willing to be lynched for his faith. Let black men especially kill lecherous white invaders of their homes and then take their lynching gladly like men.

It's worth it!

