
---
title: 'Homes'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 5
  page: 200-201
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The injustice toward colored people who want decent living conditions is almost unbelievable unless one comes face to face with the facts. The New York *Times*, which spares few opportunities to treat black folk unjustly, says in an editorial:



> It is becoming necessary in the upper resident part of New York for the property owners in neighborhoods to enter into agreements to prohibit the occupancy of their dwellings by Negroes. This departure is not due to race prejudice or hatred for the Negro but for the protection of the neighborhood values against designing or ugly white men.

Not a word for the colored family seeking a decent home; but if that family live in the slums and purlieus and let the surroundings teach their children crime and prostitution, then the holy horror of the *Times* and its ilk! If black folk rush for decent homes at exorbitant rents is there sense or decency in trying to stop this by frantic appeals to race prejudice? In other and perfectly parallel cases the property owner suffers the inevi­table without thought of appeal to human hatred. If property in Fifth Avenue becomes more valuable for business than for dwellings then the dwellings must go. If people indulge in senseless prejudice against their fellows and find real-estate men coining this prejudice into gold, they have no right to blame the unhappy victims of their barbarism, but they must blame that barbarism misnamed race pride.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Tenements (1916)](/Volumes/12/02/tenements.html)
* [Segregation (1934)](/Volumes/41/01/segregation.html)
* [Work for Black Folk in 1914 (1914)](/Volumes/07/04/work_for_black_folk.html)
* [Real Estate in New York (1914)](/Volumes/08/03/real_estate_in_new_york.html)
* [Hyde Park (1920)](/Volumes/19/06/hyde_park.html)

<!-- Similar articles end here -->