
---
title: 'Lee'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 5
  page: 200-201
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


In a recent review of Mr. Thomas Nelson Page's life of Robert E. Lee in the New York *Times* we find the following sentence: "Of all the figures in history, it is he (Lee) who most nearly approaches Washington; in fact, there is little or nothing to choose between them except the fact that Lee failed."


This statement is worth noting because it expresses a sentiment not uncommon to-day. Here are two gen­erals, both well born, scrupulously honorable, brave and efficient. The only difference between them is that one was victorious, while the other was obliged in the end to surrender. One won, the other lost; that is all.


In Memorial Hall, at Harvard University, are the names of the college graduates who fell in battle for the cause of the Union. Again and again has come the demand that with these names there be placed the names of the graduates who fell defending the Confederacy. Both were brave youths, the argument goes, both fought unselfishly. Why not give honor to both, since they only differed in that one lost and the other won in battle?

Now, what is the significance of this doctrine which many Americans believe should be preached in literature and history and on the walls of a noble building erected in memory of the heroic dead? This, that if the youths who go forth into the world, fight honorably; if they bear defeat bravely, it makes no difference what side they take in the battle. They may fight for the right of the individual to control the natural resources of the earth, to destroy the forests, to impoverish the land, or they may fight for the conservation of such resources; no matter, so that they fight well. Like Washington, their choice may be to lead the army of republicanism, or like Lee, they may choose to lead the aristocracy to battle for the right of one man to hold another as his chattel; the wisdom of their choice is of no importance; "there is little or nothing to choose between the two;" both are singularly alike, both are worthy of equal praise.

At this time of year, when we celebrate the birthdays of our two most famous Americans, let us denounce this philosophy in no uncertain terms. The choice that a man makes is his life. The present crisis faces every youthful spirit, and life for him is a failure or a success as he chooses "the good or evil side;" the side of spiritual, human progress, or the side of material, brutal enslavement. No sentiment can keep alive for long the names of those, however honorable, who chose to fight with the forces of darkness. If they live, they live in opprobrium. Washington lives and Lincoln lives because each, at The Crisis of his life, chose the side of progress and civilization. Lincoln saw the "irrepressible conflict" and stood for freedom; otherwise he would be as great a nonentity as his rival, Stephen A. Douglas. Washington lives because he believed that taxation without representation was tyranny; otherwise he would have been forgotten like---but who remembers the name of one of the gentlemen who drew their swords for King George?

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Robert E. Lee (1928)](/Volumes/35/03/robert.html)
* [The Election (1928)](/Volumes/35/12/election.html)
* [Allies (1911)](/Volumes/02/03/allies.html)
* [Starvation and Prejudice (1911)](/Volumes/02/02/starvation_and_prejudice.html)
* [On the Fence (1928)](/Volumes/35/11/on_the_fence.html)

<!-- Similar articles end here -->