
---
title: 'The Blair Bill'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 5
  page: 16--17
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There is living to-day in the city of Washington a white-haired man of towering physique who was born in New Hampshire in 1834. He was admitted to the bar in 1859 and became a Lieutenant-Colonel in the Civil War. On December 6, 1875, he was elected a representative in the United States Congress, and from June, 1879, to March, 1891, was United States Senator from New Hampshire; and his name is Blair.

On July 29, 1876, Henry William Blair delivered a speech on "Free Schools" in the House of Representatives which marked the beginning of his career. In 1881 as Chairman of the Committee on Education and Labor in the United States Senate, Mr. Blair introduced the celebrated Blair bill.

The Blair bill was discussed for ten years, passed the Senate of the United States three times, commanded at least twice a majority in the House of Representatives, although it was not permitted to come to a vote, and was finally defeated in the United States Senate in 1890 by a combination of New England and Middle West votes.

The Blair bill as reported to the 48th Congress provided:

> That for ten years after the passage of this act there shall be annually appropriated from the money in the Treasury the following sums, to wit:	The	first year the sum of $15,000,000; the second year, the sum of $14,000,000: the third year the sum of $13,000,000. and thereafter a sum diminished $1,000,000 yearly from the sum last appropriated until ten annual appropriations shall have been made, when all appropriations under this act shall cease; which several sums shall be expended to secure the benefits of common-school education of all children of the school age mentioned hereafter living in the United States.
> &nbsp;
> Sec. 2. That such money shall annually be divided among and paid out in the several States and Territories in that proportion which the whole number of persons in each, who, being of the age of ten years and over, cannot read and write bears to the whole number of such persons in the United States; and until otherwise provided such computation shall be made according to the official returns of the census of 1880.
> &nbsp;
> Sec. 5. That the instruction in the common schools wherein these moneys shall be expended shall include the art of reading, writing and speaking the English language, arithmetic, geography, history of the United States and such other branches of useful knowledge as may be taught under local laws, and shall include, whenever practicable, instruction in the arts of industry, and the instruction of females in such branches of technical or industrial education as are suited to their sex, which instruction shall be free to all, without distinction of race, color, nativity or condition of life:	Provided, that
nothing herein shall deprive children of different races, living in the same community, but attending separate schools, from receiving the benefits of this act the same as though the attendance therein were without distinction of race.

The sentiment in favor of this bill was tremendous. Garfield mentioned it in his inaugural address, the Peabody trustees favored it, Dr. J.L.M. Curry spoke for it, the American Missionary Association, the Baptist, Methodist, and Presbyterian Missionary and Educational Societies sent in memorials signed by men like Michael Striebv and Samuel C. Armstrong of Hampton; State school superintendents from Georgia, Maryland, and South Carolina sent in letters; W.T. Harris, of the Bureau of Education, was "heartily in favor" and Southern Congressmen like Wade Hampton, Vance of North Carolina, Brown and Colquit of Georgia, Lamar and George of Mississippi, Call of Florida, Pugh of Alabama, Bayard of Delaware and Beck of Kentucky, voted for the bill.

There was, however, opposition from influential quarters, an opposition not to education but to Federal aid. It was feared that local responsibility would be weakened and the federal power unduly extended. So the bill died.

What has been the result? In 1870 there were seven and a half million illiterates over ten years of age in the United States. Forty years later there are over six million illiterates. Moreover, these six million illiterates are those who admit that they are illiterate. How many more millions have deceived the census takers? Then, too, the ability to read and write does not spell intelligence.

In other words, we have to-day in the United States a staggering problem of sheer ignorance. Can we found democratic government on such a basis? REVIVE THE BLAiR BILL.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Intentions (1923)](/Volumes/25/03/intentions.html)
* [The Election (1910)](/Volumes/01/02/election.html)
* [Byrnes (1919)](/Volumes/18/06/byrnes.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [The South in the Saddle (1914)](/Volumes/07/04/south_in_saddle.html)

<!-- Similar articles end here -->