
---
title: 'The Methodist Church, North'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 5
  page: 17
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



In 1844 the general conference of the Methodist Church sitting in New York City, by a vote of 110 to 68, suspended from his functions Bishop Andrew who had come into possession of slaves through marriage.

The result was the forming of the Methodist Church, South, in 1845. After emancipation this latter church set off its former slave members into a separate church. The Methodist Church of the North having in a previous century and later lost the colored members of the African and Zion Methodist Churches, began to welcome the freedmen to its doors
and to help in their education. The result is that this church to-day has over 300,000 colored members.

Questions concerning the treatment of these members have continually arisen. So long as they could be treated as objects of purely missionary effort there was much enthusiasm. More and more, however, these colored men demanded recognition as men. In 1848 the general conference allowed itinerant colored ministers; in 1852 a colored conference was erected; in 1856 the first colored missionary bishop went to Africa. In 1860 the colored conferences were raised to full power and eight years later Negro delegates sat in the general convention. From 1872 until to-day the question of a black bishop has bothered the conference and several candidates have been voted for. Colored men have been elected to general offices in seven cases, but always with authority over Negro affairs.

Here at last the church stands. But a new question appears. Gradually a better feeling has grown up between the Northern and Southern white sections of the church and many dream of reuniting the two halves. But---and here's the rub---the price of amalgamation is for the Northern branch to give up their principles on the Negro question. Southern white servants of Christ will hardly sit in general conference with black men and certainly Negro presiding elders and bishops would be unthinkable.

Therefore (and is not this characteristically American?) the Methodist Church is here and there quietly and cautiously suggesting to its black members: "Would you not like to withdraw and be separate and have your own bishops?"

"Come unto Me, all ye that labor and are heavy laden and I will give you rest!"

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Crime (1918)](/Volumes/15/05/crime.html)
* [The Negro Church (1912)](/Volumes/04/01/negro_church.html)
* [Missionaries (1929)](/Volumes/36/05/missionaries.html)
* [The Church and the Negro (1913)](/Volumes/06/06/church_negro.html)
* [Three Churches (1916)](/Volumes/11/06/three_churches.html)

<!-- Similar articles end here -->