
---
title: 'Politeness'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 5
  page: 21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There are two situations where it is hard to be courteous: when courtesy involves public condemnation; and when courtesy demanded by the discourteous. The first is the problem of the white American, the second is the dilemma of the black American. Shall you rise in the street car and give that colored woman a seat, Mr. O'Brien, despite the grins and comments of your fellows? And you, Mr. Johnson, shall you surrender your seat to the white woman whose manner toward you is a personal insult? Yes---yes, in both cases, and yes, with a full realization, a personal realization, of the cost. A raised hat, or a title of courtesy in the South by any white man to any colored woman usually means severe social condemnation. For a Negro to offer courtesies to white people usually means that the courtesy will be snatched as a right, or angrily refused; even if it is graciously accepted there remains in the Negro's breast the knowledge that he is giving what he, his wife or his child would never receive under reversed circumstances, and he half despises himself for being a gentleman.

Such feelings explain much apparent discourtesy. White men, particularly Southern white men, are often more harsh, sharp and insulting to colored people than they would dream of being were it not for the battle between instinctive courtesy and fear of public opinion which is raging in their own hearts. They resent passionately the false position to which they are thus forced and the victim suffers.

So, too, black men are often rudely and impudently impolite, truculent even toward friends and well-wishers because they are blindly and instinctively throwing up defenses against possible insult or taking present revenge for past discourtesy.

All this is wrong. No black man can afford to be less than studiously polite even in the face of possible insult. And the white man, North or South, whose courtesy does not extend to the weak, the helpless and the black, is not a gentleman, no matter whose grandson he may be.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [A Matter of Manners (1933)](/Volumes/40/12/matter_of_manners.html)
* [A Matter of Manners (1920)](/Volumes/19/04/matter-of-manners.html)
* [Separation (1911)](/Volumes/01/04/separation.html)
* [Veiled Insults (1914)](/Volumes/07/06/veiled_insults.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)

<!-- Similar articles end here -->