
---
title: 'The White Primary'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 5
  page: 20--21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Any well-intentioned American cans argue this way: the present disfranchisement laws of the South are unfair, but in time, after the special exemptions under the grandfather clause have run out, justice will prevail and all men will vote under educational and property restrictions. 

The prospect for this outcome is not reassuring, because few people realize that even the colored voters of States like Virginia, North Carolina, South Carolina, Georgia, Alabama, Mississippi and Louisiana, who pass the present restrictions, are disfranchised again by the white primary. 

It is this fact, which has been seldom discussed, that explains many contradictions. Senator Percy, of Mississippi, says, for instance, "There is no such thing as Negro suffrage in Mississippi and never will be as long as the white men of the State stand together." The Atlanta *Constitution* said repeatedly in the first Hoke Smith campaign: 

Negroes are already disfranchised in Georgia---why pass a constitutional amendment? A judge on the bench of another State said in a decision: 

"Negroes do not vote in this State and ought not to, but they ought to get justice." At the same time white Southerners declare that in every Southern State the Negro who complies with the law can vote. 

What is the answer to this paradox? It is simple: the "White Primary." 

Professor Macy, of Iowa, one of the foremost students of our politics, says: 

> The Democratic party in the Southern States has thus come to be an aggregation of white citizens organized to maintain continued ascendency in State and local government. It lacks an essential characteristic of political parties in a free democracy, in that it does not rest its claim to such dominion upon the unrestrained choice of a free voting constituency. It is organized, not to debate, but to govern. As a political party, it makes and enforces party rules which have the force of law, and the power of the State is thus made to contribute to the strengthening of the party's hold upon the State. … So it happens that the primary election, which, in legal form merely nominates Democratic candidates for office, is, from the standpoint of the voter, the real election whereby local, State, and congressional officers are placed in positions of responsibility and power. It is, in fact, the one election of importance in the State, and the law leaves entirely to the decision of party officers the question who shall be considered qualified to cast a vote. … Party officials have entire charge of registration, the preparation of ballots, and the receiving and counting of votes.

Two quotations will confirm this statement. The constitution of the Democratic party in South Carolina says of the primary election: 

> At this election only Democratic white voters who have been residents of the State twelve months and the county sixty days preceding the next general election, and such Negroes as voted the Democratic ticket in 1876, and as have voted the Democratic ticket continuously since, to be shown by the certificates of ten white Democratic voters, who will pledge themselves to support the nominee of such elections, may vote.

The Georgia Democrats declare: 

> All white electors, who have duly registered according to law, irrespective of past political affiliations, and who intend in good faith to abide by the result of the party primary and support the nominations thereby, are hereby declared qualified, and are invited to participate in said primary election.

A friend of mine asked a prominent Florida white man in 1910: 

"Are there any Negro Democrats?" 

He answered with the utmost surprise: 

"Why, we wouldn't let a Negro vote the Democratic ticket." 

In other words, by erecting a single party as a State within a State and giving it absolute private control of primary elections and the absolute right to say who shall vote in the election there arises the complete disfranchisement of any group the majority wills. For instance, Louisiana disfranchises all of her Negro voters except 1,743, and then by the "White Primary" system she disfranchises the rest. Such a system must, of course, be backed by a strong invincible public opinion to be successful. It involves two elections---the second merely a formal registering of the decision of the first. Since, however, the first election is a party affair there can be no official returns. Moreover, the State cannot vote upon the great questions of the day that divide the nation into parties. Secondly, the official election becomes simply an unimportant and perfunctory thing. 

How long before this curious combination of law and mob rule, backed by class and race hatred, will be used in other parts of this nation?

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Truth (1911)](/Volumes/01/03/truth.html)
* [The Negro and the Land (1914)](/Volumes/07/04/negro_land.html)
* [Disenfranchisement (1926)](/Volumes/32/01/disenfranchisement.html)
* [Senators'' Records (1914)](/Volumes/08/02/senators_records.html)
* [Remember (1920)](/Volumes/19/06/remember.html)

<!-- Similar articles end here -->