
---
title: 'Pink Franklin'
author: Du Bois, W.E.B.
date: Feb. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 4
  page: 17
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The commutation of the death sentence of Pink Franklin, of South Carolina, to imprisonment for life is the latest step in an astounding American tragedy, but not, please God! the last.

Here is a colored boy, the son of a Southern white man, a boy with a fair common school education, good-tempered, pleasant to look upon and a regular worker. He is arrested under a law the essential principle of which has since been declared unconstitutional by the Supreme Courts of
both South Carolina and the United States.

His plea of self-defense in killing an armed and unannounced midnight intruder into the very bedroom of himself and his wife, after he himself had been shot, would have absolutely freed any white man on earth from the slightest guilt or punishment. Yet it could not free a colored man in South Carolina. It brought a sentence of murder in the first degree.

Governor Ansell in commuting his sentence to imprisonment for life did a brave thing. Why was it brave? Because it was just? No, it was unjust. To punish this innocent man with a terrible sentence---one almost worse than death, were it not for the hope ahead---is a terribly unjust deed. Yet Governor Ansell's act was brave because of public opinion in South Carolina; because the dominant public opinion of that State demanded this boy's blood; because Governor Ansell took his political future in his hands when he defied this opinion. Honor, then, to Governor Ansell and to strong papers like the *Columbia State*; but what shall we say of the civilization of a community which makes moral heroism of the scantiest justice?

