
---
title: 'Rampant Democracy'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 4
  page: 21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There is an artist in New York who rose from the humblest circumstances and now lives in a suburb of the city. In his rise he has evidently learned the essentials of democracy, for his wife in an interview says that they want separate Negro schools in that suburb. They need to have them, but a very foolish law interfered, she laments: 

> We got along here very well with our separate Negro school. At the same time the Catholic Church maintained a parochial school, to which most of the Italian children went, so that public schools had practically no problem to solve at all as to the commingling of children of different races.

Exquisite! Add to this the demand for separate Asiatic schools in California and we have a splendid start; we have but to demand, then, separate public schools for the rich and cultured. Why should Reginald De Courcey sit in school with Skinny Flynn and Isaac Baumgarten? Perish the thought! Then, too, we must in time distinguish between the Rich and the New Rich, the Real Thing and the Bounder. For instance, why should a Kentucky drummer presume to school his children with the lineal descendant of a patroon—but, noticing a deep red flush on the cheek of the artist's wife, we forbear to push this point. We merely pause to ask: What is democracy anyhow?

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Segregation (1910)](/Volumes/01/01/Segregation.html)
* [Reconstruction (1919)](/Volumes/18/03/reconstruction.html)
* [Negro Education (1918)](/Volumes/15/04/negro_education.html)
* [Education (1911)](/Volumes/01/04/education.html)
* [Employment (1932)](/Volumes/39/09/employment.html)

<!-- Similar articles end here -->