
---
title: 'Separation'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 4
  page: 20-21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



It is a cruel mental strain to which honest colored men are being put to-day, particularly in the South. They want to come to terms with their neighbors. They are being urged to do this---urged by black leaders and white and by strong public opinion. The South sometimes is represented as aggressively friendly. They are seeking piteously, therefore,
to agree wjth the dominant race and yet preserve something of their self-respect. It is very difficult. Take, for instance, the letter of an honest colored man in the New Orleans *Times-Democrat*. He says:

> Whatever may be the opinion of others concerning the drawing of the color line in the South, the thoughtful Negro has accepted it as a fixed principle, realizing that the race has absolutely nothing to fear or lose by social separation. Social intermingling has always meant social degradation to the less advanced element. It may set the minds of many people at rest to know that the Negro is willing and ready to meet the the most advanced thought of the South on its own ground.

He then swallows segregation whole; he would accept separate stores, separate physicians and lawyers, separate schools, separate school superintendents, separate street cars--all and complete, because, as he concludes: "The Negro does not desire racial intermingling. All he wants is a square deal before the law."

Precisely. But the thing that this black man would better ask himself good and hard is this: Is such separation physically and politically possible, and under it is there the slightest likelihood of the segregated getting "a square deal"? No. Such counsellors of surrender stand willing to sacrifice the foundations of democracy for peace. Why does the world ask equality? Out of personal bravado and impudence? No, but for self-protection. If you can separate people by color, you can separate them by birth, by wealth, by ability and any accident. This once done and democracy is dead before Privilege.

Or turn to the other side: the white South does not want Separation, but Subordination. They do not want separate Negro schoojs, but Negro schools under the control of white superintendence who hold the purse strings. They do not want separate cars, but cars which Negroes may not enter save as servants. They do not want to stop social intermingling, but they do want to prescribe the conditions.

In other words, the separation of the races which would involve political, economic and social independence in the South would be as hateful to them as social intermingling. Every man, then, that bows to the dogma of race separation must accept subordination and humiliation along with the destruction of the best ideals of democracy.

Those who persist in opposition to it need not be scared by bugbears of possible intermarriage. In a true democracy and there alone are sexual relations regulated by giving to all the right to choose their consorts. Only in an oligarchy like Louisiana is race intermingling so endless that they cannot enforce their own race segregation laws.
	

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [The Strength of Segregation (1913)](/Volumes/07/03/strength_of_segregation.html)
* [Inter-Racial Comity (1922)](/Volumes/22/01/inter-racial_comity.html)
* [Intermarriage (1913)](/Volumes/05/04/intermarriage.html)

<!-- Similar articles end here -->