
---
title: 'Southern Papers'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 4
  page: 21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There are reasons why certain white Southern papers should be classed with *Life* when they speak on the race problem. *Life* is not as funny as it used to be, and these papers are a good deal funnier. This brings the two types into something like competition at times. Take, for instance, the Charleston *News and Courier*. On most matters it is a sane and able newspaper, but let it approach the Negro problem and directly it begins to strut and darken in a way that would surely excite a smile did it not touch so vast a tragedy. When the late Alabama peonage cases reached the Supreme Court the *News and Courier* lifted a portentously warning finger. Look out, it shouted in calmly dignified tones, look out! Do not interfere with the divinely established economic harmony of the rural South. The Negro must be made to work. Our methods may lack delicacy and ease, but---and the editor spread his hands---what is peonage between friends? We are sure, he continued, that the Supreme Court will hesitate long before disturbing laws on which Southern prosperity depends.

The Supreme Court calmly overthrew the law. The *News and Courier* did not wink an eye or turn an eyelash. It simply revolved toward
the Negroes and delivered itself of this inimitable bit of reflection: This is a hard blow for you black folk---you'll get no more money advanced to you as farmhands and you'll probably starve. On the other hand, this decision is a blessing for us landlords.

All of which leads us to ask: Is the dominant, implacable portion of the white South, which speaks so loudly and incessantly on this race problem and with such perfect and breathless assurance---is it joking on this vast problem, or is it talking for effect?

And this again, as we said in the beginning, makes us wild for the last copy of *Life*, *Puck* or *Judge*.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Macon Telegraph (1920)](/Volumes/19/03/macon_telegraph.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [The Newest South (1913)](/Volumes/06/03/newest_south.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [Separation (1911)](/Volumes/01/04/separation.html)

<!-- Similar articles end here -->