
---
title: 'The Chicago Debate'
author: Du Bois, W.E.B.
date: May 1929
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 36
  issue: 5
  page: 167
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




There was held in the Coliseum in Chicago in March a debate between Lothrop Stoddard and the Editor of <span class = "small-caps">The Crisis</span> on the question "Should the Negro be Encouraged to Seek Cultural Equality?" The debate was notable; first, because of the popular interest which it aroused. Every one of the four thousand seats was taken and several hundred persons were unable to gain entrance. Probably one-third or more of the audience was white. Secondly, one noted the apparent disinclination of Mr. Stoddard frankly to state his position. This is symptomatic of a widespread change in the attitude of white Americans. It is becoming more and more difficult for them to state frankly the case against the Negro. The reason for this is that the main facts upon which they have been relying are no longer plausible and the thesis without them is barbarous, unscientific and unchristian.

The Editor asked Mr. Stoddard in the debate: "Why should not all people be encouraged to seek and reach the highest human culture?" And he intimated that the only plausible reason for denying them this privilege was the assumption that their inferiority was so great that they could never hope to reach the goal and would simply be made unhappy by striving. The obvious answer to this would be to say Yes and then to prove this inferiority of the Negro. This, Mr. Stoddard did not do and did not attempt to do. The reason probably was that he realized that such attempted proof would not only lose him the sympathy of his black audience, but gain no particular enthusiasm from a thousand whites who themselves belonged mostly to laboring classes just as "inferior" to Mr. Stoddard's Nordic superman as the average American Negro.

Mr. Stoddard, therefore, took refuge in two contentions: That differences between races should be maintained by a "bi-racial" arrangement, and that the social equality which would follow cultural equality could not be countenanced. The Editor's rejoinder was that "Bi-racialism" could not and would not work in a modern world where the whites themselves had been foremost in breaking down race barriers; and that social equality was civilized, inevitable and desirable among social equals, and not compulsory among others.


It was an interesting occasion; but the white man's presentation of his side of the controversy was much weaker than it need have been. On the other hand, if it had been stronger, it would have been a public confession of a determination to stop human progress. This is what the present dominant majority of white folk propose to do. But naturally they do not care to say so, openly, publicly and plainly.

_____

*Citation:* Du Bois, W.E.B. 1929. "The Chicago Debate." *The Crisis*. 36(5):167.