
---
title: 'Civil Rights'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 4
  page: 186
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The sweeping away of the last vestiges of Charles Sumner's civil-rights bill by the Supreme Court leaves the Negro no worse off, but it leaves the nation poor, indeed. Charles Sumner tried to do, right on the heels of emancipation, that which must be done before emancipation is complete. As long as a single American citizen, be he poor or black or ill born, can be publicly insulted by common carriers and public servants, just so long is democracy in the United States a contradiction and a farce.


The civil-rights law has long been a dead letter. First it was declared unconstitutional, as far as the States were concerned, in that series of astounding decisions of the Supreme Court, which turned the Fourteenth Amendment from its true purpose as a protector of men into a refuge for corporations. The law, however, still stood as applying to territories, the District of Columbia and the high seas. In the latest decision this vestige goes, but the Negro is by no means left without civil remedy. He is still a citizen and still has a right under common law, the Constitution and general legislation to appeal against discrimination. Let him neglect no opportunity to do that.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [Political Rebirth and the Office Seeker (1921)](/Volumes/21/03/political-rebirth.html)
* [Social Equality (1919)](/Volumes/19/01/social_equality.html)
* [Emancipation (1913)](/Volumes/05/03/emancipation.html)

<!-- Similar articles end here -->