
---
title: 'Orphans'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 4
  page: 184--186
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There is no doubt that the condition of affairs at the Colored Orphan Asylum of New York City is not what it should be. One may pass over the charges of incompetency and favoritism on the part of the superintendent, of rank color prejudice in the teaching ranks and cruelty to the children. These matters may be exaggerated, and certainly only searching investigation can establish their truth.

One thing, however, is certain beyond all reasonable doubt: this institution is not well run, the children and their guardians are not happy, the teaching force certainly lacks efficiency and the governing board seems helpless.

This is too bad. The Colored Orphan Asylum is an historic institution. It was founded before the war, burned in the draft riots, well endowed by unselfish friends of the race, white and black, and is beautifully housed on the banks of the Hudson. It has everything needed by an institution --- land, houses, income, hundreds of children, and yet it is not a successful institution. Why? The answer is not far to seek --- the white teachers do not as a rule love or sympathize with their poor little black charges; the colored teachers are not as a rule the best that could be procured.

This is in a sense natural or at least explicable: the white teachers are selected from the ordinary social workers of the day. They come to the work not prejudiced exactly, but with the general attitude of the white world toward the black. They shrink from colored folk; they feel a strangeness and aloofness; their social code leads them to ask that they neither eat nor sleep with their charges nor have any considerable personal contact. This demand, being exactly what the general public approves of, is easily granted, and thus the opportunities of personal contact and real acquaintanceship are reduced to the lowest notch. The children, preternaturally quick to sense the color bar afar, see this attitude; they become stubborn and resentful. This but widens the breach, for the white teachers are scarcely conscious of their unsympathetic attitude, since their action has the sanction of the whole white world.

On the other hand, in choosing colored teachers the board of control and the superintendent sometimes consciously, sometimes unconsciously, demand utterly inconsistent qualifications in colored candidates; they want educated persons of good, general training and perfect technique, but they want this coupled with humility, submissiveness and a willingness to keep in what white folk consider a Negro's place. In other words, they openly or tacitly ask that the educated and competent Negro accept the very caste system which his training and ambition justly lead him to rebel against. To be sure, it is true that the educated black man is apt to be supersensitive and oversuspicious, but surely this is less of a fault than incompetency and far less of a hindrance than color prejudice in a colored institution.

When an institution demands education, ability and submissiveness it gets submissiveness. It gets the kind of Negro who smiles and cringes and does his work in a slipshod manner. He is then charged with incompetency and put to menial tasks as the helper of some white person in authority. This is exactly what has happened at Riverdale and at a dozen similar institutions. Competent colored men and women who were self-assertive and demanded wages, treatment and promotion have been dismissed as impudent and insubordinate. White workers have been brought in for the same work, with less duties and higher wages, and allowed to indulge their racial consciousness to such an extent us almost to ruin the morale of the institution.

What is the remedy! There are two paths. One is that of the Lincoln Home and Hospital in New York, which will employ no Negro in any but a menial position, although it is an endowed school and charity especially for Negroes. No colored physician can practice on the colored patients of the hospitals; no colored pharmacist may work there; even the chaplain is white; in short, the color line is drawn relentlessly and shamelessly. This is a solution, but it is a thoroughly contemptible one.

The other path is to require of all workers, white or black, education and thorough competency for their tasks; then the white workers should understand that persons in colored institutions must work and associate with colored folk on terms of perfect equality and mutual respect; that these children are their little brothers and sisters, and if such relationship is repugnant to them their services are undesirable. The colored workers should be warned that competency, not color, is the passport to salary, promotion and authority, and that a spirit of good will without hypersensitiveness is the thing most needful.

Is such a solution Utopian? It is not. It is plain common sense, and if the board of control of the Colored Orphan Asylum cannot carry it out they would better give place to others.

Finally, it is a great mistake to have a governing board over an institution for colored people on which the Negro race is not represented. There is no argument of social compatibility, wealth or education which should for a moment defend such an anomaly and injustice.

