
---
title: 'Slavery'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 4
  page: 186
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The civilization of South Africa, by means of theft, disfranchisement and slavery, goes on apace. Recently the better-paid white workingmen who have long been attempting to climb to affluence and democracy on the necks of black slaves have been led to strike. London papers thus detail their reasons:

> The mining of gold in South Africa produces an appalling death roll.    
> &nbsp;
> The white underground workers in the South African mines number between 10,000 and 12,000. It is stated that there are 4,000 new cases of miner's phthisis among them annually     
> &nbsp;
> Last year more than 1,000 of the 3,000 men examined by the medical commission were found to have phthisis. No rock driller could work in the mines for sixteen years and escape it. Death takes place, as a rule, before the age of 40. After two and one-half years' service 25 per cent, of the men are affected, and the proportion increases till after fifteen and one-half years' service the percentage affected is 100.    
> &nbsp;
> Furthermore, the death rate from accidents in South African mines is
 the highest in any part of the world. The accident death rate in 1910 was 10 1/4 per thousand. Not less than 10,000 men die in these mines every year.

If this is true of South African white men, with a vote and a voice and high wages, what, in the name of a merciful God. can be the condition of the voteless and voiceless blacks who toil for dividends to support luxurious restaurants and churches and automobiles in London and New York!

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Dives, Mob, and Scab (1920)](/Volumes/19/05/dives.html)
* [Slavery (1922)](/Volumes/24/01/slavery.html)
* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)
* [Knowledge (1911)](/Volumes/02/06/knowledge.html)
* [Labor Omnia Vincit (1919)](/Volumes/18/05/labor_omnia_vincit.html)

<!-- Similar articles end here -->