
---
title: 'Our Economic Peril'
author: Du Bois, W.E.B.
date: Mar. 1930
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 37
  issue: 3
  page: 101
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Fortunately, the attention of thinkers, black and white, is being drawn to the economic crisis which faces the American Negro. Norman Thomas, the white leader of American Socialists, writing in the *New Leader*, said recently:

> Jim Crow cars, poor schools, segregation, bad housing and exclusion from industrial opportunity make up the tale of the Negroes' woes against which there is a rising tide of justifiable resentment. If anything, lack of economic opportunity in trades is growing worse and not better. This is in part a byproduct of technological unemployment which increases the pressure for jobs; in part it is due to racial prejudice. There is, for instance, a shift in the South from colored to white barbers and waiters. I have previously referred to the outrageous action of a local of the Upholsterers' Union here in New York in refusing a card to a Negro carpet layer on account of his color. Unions that follow this practice kill their own soul.    
&nbsp;    
> It does not take much of a prophet to foresee the coming of a time when at last the white mill hands will strike against intolerable conditions. In the South many of the mills, especially those owned by Northern capital, will turn to Negroes. Economic war will be heightened by racial feeling. The only way to avert such fate is to organize Negro workers as well as white workers and to assert an economic solidarity now before it is too late.

George S. Schuyler, writing in the *New York Times*, says, on the other side:

> Comforting as is the idea of a self sufficient group economy for the Negro to white people wedded to the ideal of racial separatism, we must face the facts of the situation. What the Negro needs now is not for a few philanthropists to give money to Negro schools and stop there, but for these same philanthropists, who own and control the industry and commerce of the country, to lower the color bars in their stores, factories, mills, warehouses and so forth, thus enabling the Negroes whom they have helped to educate to make a decent living and advance in the social and economic scale, not as Negroes but as Americans.

Meantime, neither the Trade Unionists nor the Philanthropists are making any real movement to lift the Negro permanently away from starvation. The only way that the Negro can accomplish this through his own efforts is to begin with consumers' co-operation. This is the reason that we have been devoting so much space lately in <span class = "small-caps">The Crisis</span>to explaining this road to economic independence. Negroes have tried it several times and have failed or succeeded for obvious reasons. Chain grocery stores in Memphis failed because they were not really co-operative; they became organized for private profit and could not meet the competition of white chain stores. Efforts in Philadelphia for the purchase of coal or other articles failed.

On the other hand, the students' cooperative store at Bluefield has been extraordinarily successful, not simply as a store, but as a school of business training. In New York City, there has been widespread buying of multiple homes on a co-operative basis. Some have failed; some have had fair success; a few have been very successful. There is no reason why with thought and study a large measure of success can not be obtained.

Meantime, educated Negroes should listen carefully to the words of two men: Benjamin Stolberg, a white man, has recently emphasized the fact that the Negro problem is essential and primarily a labor problem and the next steps must be in the direction of labor organization. Abram Harris, a colored professor of Howard University, emphasizes in this number of <span class = "small-caps">The Crisis</span> the attitude of trade unions and the clear path which Negro labor must follow.

