
---
title: 'Education'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 2
  page: 79
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The Democratic party has been in power three months and the colored population is still free. Only one Negro official has been summarily, and rather rudely, dismissed from office and no "Jim Crow" legislation seems in immediate sight. 

On the contrary, every single bill for the prostitution of colored women introduced into a half dozen different legislatures has so far been either defeated or postponed, and this by the help of Democrats as well as men of other parties. 

Thus the situation is not discouraging. Of course, the real trouble is that President Wilson may not realize the danger points of the Negro problem and may continue to think that the Tariff and Corporate control and China are the only pressing questions in National politics. <span class="crisis-title">The Crisis</span> is here to emphasize the fact that Lynching, Disfranchisement, Peonage and Discrimination in Civil Rights are just as large and in many respects larger questions, and that no party that ignores these questions can long retain control of the government. Does this sound like an overstatement? 

It is not. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Political Rebirth and the Office Seeker (1921)](/Volumes/21/03/political-rebirth.html)
* [Letters (1919)](/Volumes/17/01/letters.html)
* [The Next Step (1913)](/Volumes/06/02/next_step.html)
* [Votes (1919)](/Volumes/19/02/votes.html)
* [The Negro in Politics (1929)](/Volumes/36/11/negro_in_politics.html)

<!-- Similar articles end here -->