
---
title: 'Logic'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 2
  page: 81
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The logical end of hatred is murder. Race prejudice is traditional hatred of human beings. Its end is lynching, war and extermination.

To say this thus bluntly and brutally is to invite strong denial. Race prejudice has often been professed by men of highest ideal and motive who would shrink at violence of any kind. But this is because such men are deliberately illogical, and their followers in the long run are not illogical, but carry their leaders' doctrine to the bitter end. For instance, it is said this group of people are inferior to my group. Therefore, they are not entitled to the same privileges. But suppose they demand rights beyond their desert; then refuse them; if they keep demanding, silence them by law; if legal means do not keep them in their place, mob law is justifiable.

Thus the doctrine of race inferiority runs down to murder. Let us trace it in this country since the war. Negroes, being inferior, ought not to vote, said the reconstruction protesters. The nation, therefore, consented to their disfranchisement with the distinct understanding that all their other rights and privileges were to be preserved.

But if a man is not fit to vote why educate him and make him discontented? Consequently there was a movement against education which was so successful that to-day there are 2,000,000 Negroes not even enrolled, and practically half the Negro children in the land are not being decently trained in elementary schooling.

True, but one will give them good industrial training, make them skilled workmen, so that they can save their money and buy property. No, answers the white workman, they will compete with me and lower my wages. No, cries the white home owner, I don't want Negroes in my block.

Very well, says the compromiser, segregate Negroes in a Ghetto. But, answers the Negro, the Ghetto is in the worst part of the city, is unhealthy, ill-cared for, filled with prostitutes whom you segregate with us, and we can't better our condition because we cannot vote.

What then is the next step? Are we not harking right back to slavery? Is there any logical resting place on this downward path between a theory of inferiority and a theory of mob violence and extinction?

No. The man who begins by saying "This man is not entitled to equal rights with me," ends by either himself saying or letting others say "Lynch the Nigger."

The new step which attacks the property of Negroes comes at this time because of the advance of the Negro in economic lines. Let us note this advance in a single State like Virginia with 670,000 Negro inhabitants. The Negroes cultivate 48,114 farms and the value of the farms which they own and rent increased from $24,529,016 in 1900 to $54,748,907 in 1910, or 123 per cent. Or if we would have figures covering simply ownership we find that

In 1891 Negroes owned $12,089,965
In 1900 Negroes owned 15,856,570
In 1911 Negroes owned 32,944,336

This astounding advance of over 100 per cent. in property holding in a decade is the real reason for the attack on Negro property rights in Virginia, where three cities have tried to erect Negro Ghettos.

What lies beyond if the nation allows this last attack to succeed?


::: epigraph
"The ray of hope for justice to the Negro in the South is like the shadow of the dawn. We have caught such glimpses of it as to indicate to us that the morning of our future has not yet appeared."

-- Harrisburg, Pa., *Advocate Verdict.*
:::

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Crime (1920)](/Volumes/19/04/crime.html)
* [Let us Reason Together (1919)](/Volumes/18/05/let_us_reason_together.html)
* [N.A.A.C.P. (1910)](/Volumes/01/02/NAACP.html)
* [Mob Tactics (1927)](/Volumes/34/06/mob_tactics.html)

<!-- Similar articles end here -->