
---
title: 'The Next Step'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 2
  page: 79
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The vicious attempts to degrade colored women in Washington, Iowa,
Kansas, Michigan, Wisconsin, Ohio, Pennsylvania, New York and the
District of Columbia have been killed by the defeat of the intermarriage
bills.

But let no Negro be deceived. This is but the first step and the Negro
haters may congratulate themselves on the good showing made in the
North. They will hasten to try again.

For this we must be prepared. Do not let the organized effort so well
shown be lost. Make the organization permanent. Make it a branch of the
National Association for the Advancement of Colored People if possible.
Then proceed to systematic work.

Get the records of the men who introduced these bills and supported
them. Find out their future intentions. If they propose to persist, go
to the party leaders. Put the argument strongly before them. If they
cannot dissuade the men from their purpose, then make every effort to
defeat them at the *primaries.* Do not wait for elections, but defeat
them at the primary elections.

If the vicious, promoters of race hatred succeed in being nominated,
then use every effort to defeat them. No matter what parties they belong
to, it is our duty to vote for the opposite party.

Here then is two years' work for an organization. Only in this way can
we win our battle. Will you do it?

You will, if you love this land, for the greatest menace to the
well-being of the United States lies in the fact that there are ten
millions of people in this country who can be treated in certain
unreasonable and uncivilized ways without arousing in the minds of the
mass of the people of the United States any thought of protest.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [Political Rebirth and the Office Seeker (1921)](/Volumes/21/03/political-rebirth.html)
* [The Negro Party (1916)](/Volumes/12/06/negro_party.html)
* [The Present (1917)](/Volumes/14/04/present.html)

<!-- Similar articles end here -->