
---
title: 'Education'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 2
  page: 78-79
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Some folks are mental ostriches. We are not referring to their intellectual digestions, although there we realize is room for a whole. We are referring now to the method of mind that is able to persuade itself that the unseen is non-existent. An astounding number of people rushing through earth's deserts escape the evil that haunts them by sticking their heads in a hole in the ground and saying insistingly: "I don't believe it, and even if it is true I won't regard it."

Now the world is without doubt full of things, incidents, thoughts, men that are best disregarded; that are best unheard, unseen, ignored. But make no mistake, friend of the unseeing eye, for there is evil in the world which may not be ignored and that cannot be escaped by sticking our heads in the ground and closing our eyes. 

Face the race problem like men, frankly and carefully, but none the less determinedly. Let your children face it. Don't seek to sneak away from the evil and forget the poor suffering brothers and sisters who cannot escape, who must work and writhe and fight. Remember that bad as the truth is, it is a little better than the apprehension; and devilish as the situation in certain parts of the South is, it is just a little better than the Negro in the North pictures it---particularly in that part of the North which wishes to hide its head. 

There is absolutely nothing in the race problem to-day which is insoluble by peaceful human endeavor. The world has cured worse ill than it faces to-day, and the Negro race has triumphantly survived worse oppression than that which it suffers here and now. Why then hide our discouraged heads? Why seek to escape that which true manhood must know, if it will fight intelligently? All things are bad? Very well; let's first know just how bad they are, and then let's make them better. Social reform without knowledge is futile. Knowledge without attempted betterment is criminal. The complacency of the donkey is annoying, but the cowardice of the ostrich is dangerous. 

