
---
title: 'Muddle'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 13
  issue: 2
  page: 61
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Nothing can better illustrate our meaning when we spoke last month of the need of political education among colored people, than the attitude of a few Negroes toward the political mission of the NAACP. It goes without saying that this association is, and has been from the beginning, a political organization, in the best and broadest sense of that term. It takes part in politics, and sees and knows no disgrace therefrom. It maintains that in any republic, except a dead one, there is no greater mission for citizens and organizations of citizens than wise, honest, determined political activity. 

It is manifestly the business of the NAACP to teach the Negroes of the United States these elementary truths in politics: (1) It is the first duty of candidates for public office to tell their constituents what they stand for. (2) It is the first duty of any person, black or white, to know the attitude of candidates on matters affecting his interests before he votes for or against them. (3) Whenever any man is voting for a candidate whose beliefs and intentions he does not know, that voter not only acts the part of a fool, but he endangers the very foundations of republican government. This Association proposes, in every way possible, to make candidates for public office declare before election their attitude toward the Negro and his needs. 

