
---
title: 'Refinement and Love'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 13
  issue: 2
  page: 63
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


A colored girl writes us from Oswego, N. Y., saying:

> Do you want to know what I like best about <span class = "small-caps">The Crisis</span>? What I enjoy most? What fires my ambition to struggle on? Well, it is just this: The successes of other members of my race and what they are doing in this United States.  <p> And do you want to know what I like least? Just such expressions as these: 'The recent Irish revolt may have been foolish, but would to God some of us had sense enough to be fools!' The great Napoleon realized after all that the use of force was not the best way to achieve one's ends. That sort of a foundation is too weak; it cannot last. So is it not better to keep before our people ideas and thoughts of culture, refinement, service and love and in that way build our progress on a sure foundation?

No one wishes more than <span class = "small-caps">The Crisis</span> that "culture, refinement, service and love" should triumph in the world; but we continually fear lest easy-going young folk should loll in their parlors toasting their toes and expect the horror of the world's blood sacrifice to be accomplished by someone else while they are practising "refinement and love." Terrible as it may be, the awful fact faces the colored races in this world: That no human group has ever achieved freedom without being compelled to murder thousands of members of other groups who were determined that they should be slaves. Let us hope and deeply pray that this may not happen in the case of colored folk; but at the same time let us set our faces grimly toward the fact, with unwinking eyes, that it may be necessary. War is Hell, but there are things worse than Hell, as every Negro knows.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The True Brownies (1919)](/Volumes/18/06/true_brownies.html)
* [The Crisis (1910)](/Volumes/01/01/TheCrisis.html)
* [A Question of Policy and The Philosophy of Mr. Dole (1914)](/Volumes/08/01/question_of_policy.html)
* [Forward (1920)](/Volumes/20/05/forward.html)
* [Prejudice (1927)](/Volumes/34/09/prejudice.html)

<!-- Similar articles end here -->