---
title: 'Phonograph Records'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: February 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 21
  issue: 4
  page: 152
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

We have good authority for stating that 65% of the phonograph records made for the Southern trade by a well-known company are sold to colored people. Nevertheless, this company employs only one colored artist regularly and only occasionally a colored orchestra or quartet. All these musicians are confined strictly to a certain class of music and on no account are they allowed to attempt anything else, no matter what their gifts or ability.

This company, however, is much more liberal than most phonograph companies. They have thousands of white singers under contract and pay them hundreds of thousands of dollars annually, and yet no colored singer may apply even for their Negro music.

Here is a tremendous field. We have some of the finest voices in the world right here in Negro America. Within the past few months one of the smaller, newer phonograph companies experimented by having a colored girl sing “Blues.” The experiment was so successful and the demand for her records among colored folk so great that the company was not able to fill its orders.

They have since signed her to sing for them for two years. Now several other concerns are looking for a colored “Blues” singer, but they make it particularly plain that no others need apply.

Artists like Roland Hayes have gone in vain to the great phonograph companies. One of them offered to let him do “comic darky songs” but nothing else; while men with much inferior voices are allowed daily to sing the finest music and to debase and ridicule the Negro folk song.

Under such discrimination there is but one solution. We have already throughout the land developed a Negro audience to appreciate and pay a dozen or more Negro artists. We have a commendable and growing National Association of Negro Musicians. We must now develop a business organization to preserve and record our best voices; we ought to have records of Burleigh, Hayes, Talbert, Anderson, Johnson, Harrison, Hagan, Dett, Diton and a dozen others to reveal the best music, not only of their own race but of all races and ages.

We are pleased to learn that such a company is now forming with adequate capital and skilled management of guaranteed integrity.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [We Shuffle Along (1922)](/Volumes/24/05/we-shuffle-along.html)
* [Negro Art (1922)](/Volumes/23/03/negro-art.html)
* [Hayes (1927)](/Volumes/33/03/hayes.html)
* [Our Book Shelf (1925)](/Volumes/31/01/our_bookshelf.html)
* [Promoting Race Prejudice (1917)](/Volumes/14/03/race_prejudice.html)

<!-- Similar articles end here -->