
---
title: 'Hayes'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 33
  issue: 3
  page: 129
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


How many of us realize the tremendous propaganda of Roland Hayes? He was at Carnegie Hall last week. He sang with a firmness, control and sweetness that entranced thousands of the most sophisticated music-lovers of America. Black and white sat together in the orchestra. Applauding devotees lingered until the lights went out. He sang old eighteenth century songs; he sang Negro melodies; he sang the dream from Manon "as no living singer sings." Think what it means to every black child in the world to have this black man singing. Let us crowd to hear his every performance. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Promoting Race Prejudice (1917)](/Volumes/14/03/race_prejudice.html)
* [We Shuffle Along (1922)](/Volumes/24/05/we-shuffle-along.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [Our Book Shelf (1925)](/Volumes/31/01/our_bookshelf.html)
* [The Newer South (1926)](/Volumes/31/04/newer_south.html)

<!-- Similar articles end here -->