
---
title: 'Intermarriage'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 33
  issue: 3
  page: 128-129
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


A man named Lawton writing in the *Independent* says that the N.A.A.C.P. "expressly advocates intermarriage" of whites and blacks. It does nothing of the sort. It simply declares that if white folk will have sexual commerce with blacks, this must take place under legal restrictions; that prohibition of such legal marriage is a direct bid for bastards and prostitutes and removes all civilized protection from colored girls and women; and finally that if two grown, sane, healthy persons wish to marry that that is their business and neither Mr. Lawton's nor ours. This is a long way from advocating such marriage. Despite everything we still maintain that English dukes should have the right to marry Americans: But we do not "advocate" it. We have too much respect for Americans. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Intermarriage (1916)](/Volumes/11/06/intermarriage.html)
* [Inter-Marriage (1924)](/Volumes/29/06/inter-marriage.html)
* [Intermarriage (1913)](/Volumes/05/04/intermarriage.html)
* [Decency (1912)](/Volumes/04/02/decency.html)
* [Sex Equality (1920)](/Volumes/19/03/sex_equality.html)

<!-- Similar articles end here -->