
---
title: 'League of Nations'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 33
  issue: 3
  page: 130-131
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Three efforts under the League of Nations are of interest to colored folk. *First*, the system of mandates by which fifteen millions of people occupying an area as large as Europe have been placed under the rule of certain European nations. The Mandates Commission, however, has been repeatedly denied permission to find out at first hand just what the mandatory powers are doing in these territories. This is unfortunate and sometime such power must be granted. *Secondly*, a new Anti-Slavery treaty has been signed by twenty-three nations. The only suspicious thing about this is that apparently it has been aimed at the household service of Abyssinia instead of considering the shameless exploitation of labor in English, French and Belgian Africa. The *third* step is that of the International Labor Organization which proposes for the next two or three years to frame with the help of experts an international treaty covering conditions for the future employment of colored laborers. Here again the misfortune is that apparently few representatives of the colored laborers have been called in council while white capital is there in force. Some time the Negro people of the Americas will realize that they ought to have permanent representation at Geneva. 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The League of Nations (1919)](/Volumes/19/01/league.html)
* [Helping Africa (1924)](/Volumes/28/03/helping_africa.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [The Firing Line (1925)](/Volumes/31/02/firing_line.html)
* [Hayti (1915)](/Volumes/10/05/hayti.html)

<!-- Similar articles end here -->