
---
title: 'Scottsboro'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 5
  page: 117
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Scottsboro is the perfect fruit of a generation of organized lying concerning conditions in the South.

It is doubtful if anybody believes that these young, ignorant Negroes were guilty of any crime; but, on the other hand, in order to defend the judicial system of the South; in order to protect manipulation of juries and political rotten boroughs; in order to uphold the integrity of the white race; it is necessary for public officials to go into court and to swear that Negroes may and do serve on juries in Alabama; that the testimony of a poor social outcast is to be believed to the extent of murdering seven human beings, and that the courts of Alabama seek to give fair and exact justice to colored persons who are arrested!

There isn't a sane person in the United States that believes any one of these allegations, and yet at best these poor boys are going to be imprisoned for life, and it would be simply merciful in Alabama if such a sentence were commuted to hanging.

There is but one remedy for such a situation. The black governed must have a voice in white government. Wholesale disfranchisement in the South must yield to reason. There can be no protection for the disfranchised oppressed against the sadistic mob, even though the better thinking people of the state want justice and mercy. Nothing so nearly as Scottsboro proves the utter futility of the argument, that if political power is taken from the Negro, he will be protected in his rights by the best people of the South. In the face of wholesale disfranchisement, the best people are as helpless as the worst.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Scottsboro (1934)](/Volumes/41/01/scottsboro.html)
* [Anarchism (1912)](/Volumes/04/04/anarchism.html)
* [Deception (1916)](/Volumes/12/02/deception.html)
* [Signs from the South (1919)](/Volumes/18/05/signs_from_south.html)
* [Courts and Jails (1932)](/Volumes/39/04/courts_and_jails.html)

<!-- Similar articles end here -->