---
title: 'Negro Art'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: January 1922
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 23
  issue: 3
  page: 107
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

The Negro race as an interpreter of beauty to the world is gradually coming to its own. Not only are our musicians like Burleigh and Dett pursuing their high and successful career, but we are beginning to be listened to in painting and sculpture. Pageantry is appearing and the white artist and writer is beginning to discover us as human beings and not as conventional lay figures. Recently in New York City there was held in the branch of the public library which is in Harlem, an exhibit of Negro art with specimens of the work of H.O. Tanner, Laura Wheeler, W.M. Farrow, Richard Lonsdale Brown, W.E. Scott, Louise Lattimer, Meta Fuller and many others. The exhibit was a revelation in its accomplishment and a promise in its originality and beauty.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Criteria of Negro Art (1926)](/Volumes/32/06/criteria_of_negro_art.html)
* [Negro Art (1921)](/Volumes/22/02/negro_art.html)
* [DePriest (1929)](/Volumes/36/02/depriest.html)
* [Our Book Shelf (1925)](/Volumes/31/01/our_bookshelf.html)
* [Negro Writers (1920)](/Volumes/19/06/negro_writers.html)

<!-- Similar articles end here -->