
---
title: 'The Capital N'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1930
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 37
  issue: 5
  page: 172
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Recently and with a certain suddenness, the periodical press of the United States has decided to capitalize the word Negro.



Much of the new resolve is due to Roscoe Conklin Bruce, who as editor of the bi-weekly sheet published by the Paul Laurence Dunbar Apartments, has recently carried on a vigorous correspondence, much like a similar effort made by Lester Walton some years ago.

The N.A.A.C.P. also sent out over 700 letters with return postals to publishers all over the country.

Mr. Bruce did not stress the logic of the situation so much as the courtesy. He said repeatedly to editors: the colored people of the United States desire to have the word Negro capitalized, and their wishes ought to be respected.

It was this argument that brought down the *Atlantic Monthly* and the *New York Times*. The Times says: "In our Style Book, Negro is now added to the list of words to be capitalized. It is not merely a typographical change, it is an act in recognition of racial self-respect for those who have been for generations in the `lower case'."

There remains scarcely a respectable periodical in the United States that refuses to capitalize Negro. In fact, the Government Printing Office in Washington and the *Forum* magazine stand almost alone.

