
---
title: 'Negro Education'
author: Du Bois, W.E.B.
date: Feb. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 15
  issue: 4
  page: 173-178
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The casual reader has greeted this study[^fn1] 
of Negro education with pleasure. It is the first attempt to cover the field of secondary and higher education among colored Americans with anything like completeness. It is published with the sanction and prestige of the United States government and has many excellent points as, for instance, full statistics on such matters as.the public expenditure for Negro school systems, the amount of philanthropy given private schools, Negro property, etc.; there is excellent and continued insistence upon the poor support which the colored public schools are receiving today. The need of continued philanthropic aid to private schools is emphasized and there are several good maps. Despite, then, some evidently careless proofreading (pages 59, 129, 157), the ordinary reader unacquainted with the tremendous ramifications of the Negro problem will hail this report with unstinted praise. 

Thinking Negroes, however, and other persons who know the problem of educating the American Negro will regard the Jones' report, despite its many praiseworthy features, as a dangerous and in many respects unfortunate publication. 

## The Thesis of the Report 

This report again and again insists by direct statements, by inference, and by continued repetition on three principles of a thesis which we may state as follows: *First*, that the present tendency toward academic and higher education among Negroes should be restricted and replaced by a larger insistence on manual training, industrial education, and agricultural training; *secondly*, the private schools in the South must "co-operate" with the Southern whites; and, *third*, that there should be more through-going unity of purpose among education boards and foundations working among Negroes. 

## The Negro College

The whole trend of Mr. Jones' study and of his general recommendations is to make the higher training of Negroes practically difficult, if not impossible, despite the fact that his statistics show (in 1914-15) only 1643 colored students studying college subjects in all the private Negro schools out of 12,726 pupils. He shows that there are (in proportion to population) ten times as many whites in the public high schools as there are colored pupils and only sixty-four public high schools for Negroes in the whole South! He shows that even at present there are few Negro colleges and that they have no easy chance for survival. What he is criticising, then, is not the fact that Negroes are tumbling into college in enormous numbers, but their wish to go to college and their endeavor to support and maintain even poor college departments.

What, in fact, is back of this wish? Is it merely a silly desire to study "Greek," as Mr. Jones several times intimates, or is it not rather a desire on the part of American Negroes to develop a class of thoroughly educated men according to modern standards? If such a class is to be developed these Negro colleges must be planned as far as possible according to the standards of white colleges, otherwise colored students would be shut out of the best colleges of the country. 

The curriculum offered at the colored southern colleges, however, brings the author's caustic criticism. Why, for instance, should "Greek and Latin" be maintained to the exclusion of economics, sociology, and "a strong course in biology?"

The reason for the maintenance of these older courses of study in the colored colleges is not at all, as the author assumes, that Negroes have a childish love for "classics." It is very easily and simply explicable. Take, for instance, Fisk University. Fisk University maintained Greek longer than most northern colleges, for the reason that it had in Adam K. Spence not simply a finished Greek scholar, pupil of the great D'Ooge, but a man of singularly strong personality and fine soul. It did not make much difference whether the students were studying Greek or Biology—the great thing was that they were studying under Spence. So, in a large number of cases the curriculum of the southern Negro college has been determined by the personnel of the available men. These men were beyond price and working for their devotion to the cause. The college was unable to call men representing the newer sciences—young sociologists and biologists. They were unable to equip laboratories, but they did with infinite pains and often heartbreaking endeavor keep within touch of the standard set by the higher northern schools and the proof that they did well came from the men they turned out and not simply from the courses they studied. 

This, Mr. Jones either forgets or does not know and is thus led into exceedingly unfortunate statements as when, for instance, he says that the underlying principle of the industrial school "is the adaptation of educational activities whether industrial or literary to the needs of the pupils and the community," which is, of course, the object of any educational institution and it is grossly unfair to speak of it as being the object of only a part of the great Negro schools of the South. Any school that does not have this for its object is not a school but a fraud. 

## The Public Schools

Not only does this report continually decry the Negro college and its curriculum but, on the other hand, it seeks to put in its place schools and courses of study which make it absolutely impossible for Negro students to be thoroughly trained according to modern standards. To illustrate: Mr. Jones shows (page 90) that in Butte, Mont., manual training has been put into the elementary schools at the rate of *half a day* a week during the first six years and *two half days a week* in the seventh and eighth grades. When, however, it comes to the smaller elementary industrial schools of the South Mr. Jones recommends *one-half* day classroom work and one-half practice in the field and shops *every day*. 

What, now, is the real difference between these two schemes of education? The difference is that in the Butte schools for white pupils a chance is held open for the pupil to go through high school and college and to advance at the rate which the modern curriculum demands; that in the colored schools, on the other hand, a program is being made out that will land the boy at the time he becomes self-conscious and aware of his own possibilities in an educational *impasse*. He cannot go on in the public schools even if he should move to a place where there are good public schools because he is too old. Even if he has done the elementary work in twice the time that a student is supposed to it has been work of a kind that will not admit him to a northern high school. No matter, then, how gifted the boy may be he is absolutely estopped from a higher education. This is not only unfair to the boy but it is grossly unfair to the Negro race. 

The argument, then, against the kind of school that is being foisted upon Negroes in the name of industrial education is not any dislike on the part of the Negroes for having their children trained in vocations, or in having manual training used as a means of education; it is rather in having a series of schools established which deliberately shut the door of opportunity in the face of bright Negro students. 

## Industrial Training

With the drive that has been made to industrialize elementary schools before the children have learned to read and write and to turn the high schools to vocational teaching without giving any of the pupils a chance to train for college, it is, of course, beside the mark to criticize the colored colleges because the children that come to them are poorly trained. 

Much of the criticism of colored teachers is also unfair. Even well-trained teachers are having curious pressure put upon them. Here is a teacher with eighty or one hundred pupils trying to teach them three r's in a country district. The Jeanes Fund sends a supervisor and introduces, to quote the report (page 35), "shuck mat work, simple sewing, patch quilting for girls, repair of buildings and woodworking for boys." It *might* be possible with money and teachers so to interlock this work with the teaching of the three r's as to help the net result; but when the stress, the emphasis, and the inspection has to do mainly with the *industrial work as such,* and nobody knows or cares about the chief work for which the school ought to exist; when the white community demands .of these schools servants and laborers and not educated men and women, what is the result bound to be? 

With its insistent criticising of Negro colleges this report touches with curious hesitation and diffidence upon the shortcomings of industrial schools. Their failure to distinguish between general education and technical trade training has resulted in sending out numbers of so-called teachers from educational schools who cannot read and write the English language and who are yet put in public and other schools as teachers. They may show children how to make tin pans and cobble shoes, but they are not the right persons to train youth, mentally or morally. In the second place, most of the trades taught by these trade schools are, because of hostile public opinion and poverty, decadent trades: carpentry, which is rapidly falling below the level of skilled trades; the patching of shoes; blacksmithing, in the sense of repair work, etc. The important trades of the world that are today assembled in factories and call for skilled technique and costly machinery are not taught in the vast majority of Negro industrial schools. Moreover, the higher industrial training calls for more education than the industrial schools give. I remember some ten years ago going into the wheel-wrighting shop at Hampton. I said to the white instructor: "How are your students getting on?" He said: "Fairly well, only *they haven't enough mathematics.*" Yet here is a report that has much to say over the foolishness of teaching mathematics! 

That the course of study in the Southern schools as well as in the schools of the nation has got to be changed and adapted is absolutely true, but the object of a school system is to carry the child as far as possible in its knowledge of the accumulated wisdom of the world and then when economic or physical reasons demand that this education must stop, vocational training to prepare for life work should follow. That some of this vocational training may be made educational in object is true; that normal training may use manual training and even to some extent vocational training is true, but it is not true that the industrializing of any curriculum necessarily makes it better or that you can at one and the same time educate the race in modern civilization and train it simply to be servants and laborers. Anyone who suggests by sneering at books and "literary courses " that the great heritage of human thought ought to be displaced simply for the reason of teaching the technique of modern industry is pitifully wrong and, if the comparison must be made, more wrong than the man who would sacrifice modern technique to the heritage of ancient thought. 

## Cooperation 

The second part of Mr. Jones' thesis lies in an insistence that the private schools of the Negro should "cooperate" with the South. He stresses the adaptation of education to the needs of the "community " (page 18), evidently meaning the *white* community. He quotes on page 25 the resolution of the white Southern Educational Association which deplores that the Negro schools are isolated from the "community," meaning again the white community. He instances Willcox County, Ala., where there are almost no public schools and recommends that the private schools established there be put under "community" authorities (page 149). Now what is this "community" with which the colored people are to cooperate? 

In the first place, Mr. Jones admits (pages 4 and 5), that it is only the progressive few in the white South that care anything at all about Negro schools. He might go even further and acknowledge that if a plebescite were taken tomorrow in the South the popular vote of white people would shut every single Negro school by a large majority. The hostile majority is kept from such radical action by the more progressive minority and by fear of northern interference, but the condition in which they have today left the colored schools is shown by this report to be truly lamentable. 

 Mr. Jones quotes from Southern white men who speak of Negro school houses as "miserable beyond all description," of teachers as "absolutely untrained" and paid "the princely fortune of $80.92 for the whole term." He goes on with fact after fact to show the absolute inadequacy in the provision for colored children in the public schools of the South. On the other hand, he shows the increase in Negro property, the larger and larger amounts which Negroes are contributing to the school funds; and with all this he practically asks that the domination of the Negro private schools, which are now bearing the burden of nearly all the secondary and higher education of the Negro and much of the elementary education—that the domination of these schools be put into the hands of the same people who are doing so little for the public schools! 

There is not in the whole report a single word about *taxation without representation*. There is not a single protest against a public school system in which the public which it serves has absolutely no voice, vote, or influence. There is no defense of those colored people of vision who see the public schools being used as training schools for cheap labor and menial servants instead of for education and who are protesting against this by submitting to double taxation in the support of private schools; who cannot see that these schools should be turned over to people who by their actions prove themselves to be enemies of the Negro race and its advancement. 

Until the southern Negro has a vote and representation on school boards public control of his education will mean his spiritual and economic death and that despite the good intentions of the small white minority in the South who believe in justice for the Negro. It is, therefore, contradictory for this report to insist, on the one hand, on the continuation of northern philanthropy for these schools and, on the other, to command various southern schools in proportion as they have gained the approval of the white community. 

Compare, for instance, Fisk University and Atlanta University. Both Cravath of Fisk and Ware of Atlanta were men radical in their belief in Negro possibility and in their determination to establish well equipped Negro colleges. Cravath, however, lived in a more enlightened community which was earlier converted to his ideals. He did not yield his opinion any more than Ware, but Ware lived in a community that to this day will not furnish even a high school for its colored pupils. To say that Fisk should receive on this account more support than Atlanta is rank injustice; if anything Atlanta deserves the greater credit. 

Cooperation with the white South means in many cases the surrender of the very foundations of self-respect. Mr. Jones inserts in his report one picture of a colored principal and his assistant waiting on table while the white trustees of his school eat. The colored people of the South do not care a rap whether white folks eat with them or not, but if white officials are coming into their schools as persons in control or advisors, then to ask that in those schools and in their homes the colored people shall voluntarily treat themselves as inferiors is to ask more than any self-respecting man is going to do.

The white community, undoubtedly, wants to keep the Negro in the country as a peasant under working conditions least removed from slavery. The colored man wishes to escape from those conditions. Mr. Jones seeks to persuade him to stay there by asserting that the advance of the Negro in the rural South has been greatest (pages 97 and 123), and he refers to the "delusion" of city life even among white people. This may be all good enough propaganda but, in fact, it is untrue. Civilization has always depended upon the cities. The advance of the cities has been greatest for all people, white and colored, and for any colored man to take his family to the country districts of South Georgia in order to grow and develop and secure education and uplift would be idiotic. 

Mr. Jones touches the State schools very lightly. Here are cases where the whites have control and stories of graft and misappropriation of funds and poor organization are well known to everybody with the slightest knowledge of southern conditions. Teachers there and in the public schools are often selected not from the best available, but from the worst or most complacent. In small towns and country districts white trustees may maintain their mistresses as teachers and the protest of the colored people has fallen upon deaf ears. Until, then, colored people have a voice in the community, surrender to the domination of the white South is unthinkable. 

## Norther Philanthropy

This brings us to the third part of Mr. Jones' thesis, namely, that the boards working for southern education should unite as far as possible with one policy. This is an unfortunate and dangerous proposal for the simple reason that the great dominating philanthropic agency, the General Education Board, long ago surrendered to the white South by practically saying that the educational needs of the white South must be attended to before any attention should be paid to the education of Negroes; that the Negro must be trained according to the will of the white South and not as the Negro desires to be trained. It is this board that is spending more money today in helping Negroes learn how to can vegetables than in helping them to go through college. It is this board that by a system of interlocking directorates bids fair to dominate philanthropy toward the Negro in the United States. Indeed, the moving thought back of the present report is the idea of a single authority who is to say which Negro school is right or is wrong, which system is right and which is wrong, etc. 

No one doubts the efficiency of concentration and unity in certain lines of work but always, even in work that can be unified, the question is *whose* influence is going to dominate; it may well be that diversity and even a certain chaos would be better than unity under a wrong idea. This is even more true in educational than in economic matters. Of course, the economic foundation of all recent educational philanthropy, particularly toward the Negro, is evident. Mr. Jones rather naively speaks of the fact that at certain times of the year "it is exceedingly difficult to prevail upon children to attend school" in the colored South which is, of course, another way of saying that bread and butter in the cotton fields is of more importance than trained intelligence. 

Undoubtedly, there has already been a strong public opinion manufactured in the country which looks upon the training of Negroes in the South as cheap, contented labor to be used in emergency and for keeping white union labor from extravagant demands as a feasible and workable program. It is, in fact, one of the most dangerous programs ever thought out and is responsible for much of the lynching, unrest, and unhappiness in the South. Its genesis came easily with the idea of working for the Negro rather than working *with* him, a thing which Mr. Jones condemns, but hardly lives up to his condemnation. 

In this very report the Negro was practically unrepresented. Instead of choosing a strong, experienced colored man to represent the Negro race (like W. T. B. Williams, or President Young of Tallahassee, or President Hope of Morehouse) an inexperienced young man was taken, of excellent character but absolutely without weight or influence. Of course, back of all this is the great difficulty of ordinary social intercourse. The reason that boards of trustees like those that control the Phelps-Stokes Fund find it so much easier to **work** *for* the Negro than *with* him; the reason that forgetting the investigations by Negroes at Atlanta University they turned to white institutions to encourage investigation and neglected established and worthy work is because if they are going to cooperate with the dominant white South and even with certain classes of Northerners they cannot meet Negroes as men. The propaganda that is so largely carried on and the influence that is so often formed through social intercourse must always, at present, be offered with the Negro unrepresented and unheard. 

There follows easily the habit of having no patience with the man who does not agree with the decisions of such boards. The Negro who comes with his hat in his hand and flatters and cajoles the philanthropist—that Negro gets money. If these foundations raise, as they do in this report, the cry of fraud they have themselves to thank. They more than any other agency have encouraged that kind of person. On the other hand, the Negro who shows the slightest independence of thought or character is apt to be read out of all possible influence not only by the white South but by the philanthropic North. 

If philanthropic agencies could unite for certain obvious great movements how splendid it would be! Take, for instance, the duplication of higher educational schools which Mr. Jones repeatedly denounces and which, undoubtedly, is a source of weakness. The General Education Board could settle the matter with the greatest ease. Let it offer in Atlanta an endowment of $500,000 for a single Negro college, provided that there be but one college there for Negroes. The boards of the different schools immediately would have something to act upon. As it is nothing that they can do individually would really better the situation. A new college formed by a federation of colored colleges in Atlanta, Marshall, Texas, and elsewhere, would be easily possible if an endowment was in sight. 

## Summary 

Here, then, is the weakness and sinister danger of Mr. Jones' report. It calls for a union of philanthropic effort with no attempt to make sure of the proper and just lines along which this united effort should work. It calls for cooperation with the white South without insisting on the Negro being represented by voice and vote in such "cooperation," and it calls for a recasting of the educational program for Negroes without insisting on leaving the door of opportunity open for the development of a thoroughly trained class of leaders at the bottom, in the very beginnings of education, as well as at the top. 

[^fn1]: *Negro Education, a Study of the Private and Higher Schools for Colored People in the United States*; prepared in co-operation with the Phelps-Stokes Fund, under the direction of Thomas Jesse Jones, specialist in education of racial groups. Two volumes, 8 vo., 424, 724 pages. Washington 1917.

