
---
title: 'The Railroads'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 15
  issue: 4
  page: 164-165
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The Railroads.

The taking over of the railroads by the United States government is an event of first importance to colored Americans. Not only does it probably mark the ending of a system of private profit, based upon so general and standardized a necessity as travel, but it goes further than that. With the proper administration in Washington, it means the end of the "Jim-Crow" car, for with the government as owner, what state can prescribe conditions of travel?

Moreover, the railway unions have absolutely excluded colored men. Only white men can belong to the conductors' union, the engineers' union, the switchmen's union, the firemen's union, etc. If the government continues to hold the railways after the war, and this is more than probable, these union men will become civil servants. Any person passing the requisite examination, be he white or black, can enter this service, and he cannot be excluded from the unions.

It is, therefore, the business of every black voter to see that the railways of the United States never revert again to private hands; and then to use his growing political power in the North to oust the southern oligarchy from its entrenched power in Washington.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Burleson (1913)](/Volumes/06/04/burleson.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [Does Organization Pay? (1914)](/Volumes/07/06/does_organization_pay.html)
* [Organized Labor (1912)](/Volumes/04/03/organized_labor.html)
* [The "Jim Crow" Argument (1913)](/Volumes/05/06/jim_crow_argument.html)

<!-- Similar articles end here -->