---
title: 'Agitation'
description: "In a 1910 The Crisis essay, W.E.B. Du Bois argues agitation, though painful, is necessary to expose and cure race prejudice and restore justice."
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Nov. 1910
people:
  - W.E.B. Du Bois
places:
  - United States
organizations:
  - The Crisis
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 1
  page: 11
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display

categories:
  - "NAACP & Organizational Strategy"
---

Some good friends of the cause we represent fear agitation. They say: "Do not agitate---do not make a noise; work." They add, "Agitation is destructive or at best negative---what is wanted is positive constructive work."

Such honest critics mistake the function of agitation. A toothache is agitation. Is a toothache a good thing? No. Is it therefore useless? No. It is supremely useful, for it tells the body of decay, dyspepsia and death. Without it the body would suffer unknowingly. It would think: All is well, when lo! danger lurks.

The same is true of the Social Body. Agitation is a necessary evil to tell of the ills of the Suffering. Without it many a nation has been lulled to false security and preened itself with virtues it did not possess.

The function of this Association is to tell this nation the crying evil of race prejudice. It is a hard duty but a necessary one---a divine one. It is Pain; Pain is not good but Pain is necessary. Pain does not aggravate disease---Disease causes Pain. Agitation does not mean Aggravation---Aggravation calls for Agitation in order that Remedy may be found.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Our Own Consent (1913)](/Volumes/05/03/our_own_consent.html)
* [Forward (1920)](/Volumes/20/05/forward.html)
* [The Gall of Bitterness (1912)](/Volumes/03/04/gail_of_bitterness.html)
* [The Class Struggle (1921)](/Volumes/22/04/class_struggle.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)

<!-- Similar articles end here -->