
---
title: 'Baltimore'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Nov. 1910
categories: 
  - Housing
  - Segregation
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 1
  page: 11
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


An inevitable step forward in anti-Negro prejudice is being taken in Baltimore, and threatened elsewhere. The colored folk of that city long ago became dissatisfied with a particularly bad system of alley homes. They saved their money and purchased nearly the whole length of Druid Hill avenue---one of the best colored streets in the world. Then they began to expand into parallel streets, one of which was McCulloh. They had been told that "money talks," and that the surest road to respect in America was financial success. The result was inevitable. The white people of McCulloh street rose in indignation and are importuning the City Council to pass an ordinance prohibiting colored people from "invading" white residential districts, and vice versa. Their argument sounds strong: colored residents bring down the price of property, therefore get rid of colored residents.

Is this the real logic of the situation? Why do colored people depress property values? Because of an exaggerated and persistency encouraged racial prejudice. In the encouragement of such prejudice, Baltimore and Maryland have particularly sinned. Would not an attempt to allay prejudice be wiser than laws against thrift?

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Homes (1912)](/Volumes/03/05/homes.html)
* [Tenements (1916)](/Volumes/12/02/tenements.html)
* [Segregation (1934)](/Volumes/41/01/segregation.html)
* [Real Estate in New York (1914)](/Volumes/08/03/real_estate_in_new_york.html)
* [Work for Black Folk in 1914 (1914)](/Volumes/07/04/work_for_black_folk.html)

<!-- Similar articles end here -->