
---
title: 'The Crisis'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Nov. 1910
categories: 
  - The Crisis
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 1
  page: 10
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The object of this publication is to set forth those facts and arguments which show the danger of race prejudice, particularly as manifested to-day toward colored people. It takes its name from the fact that the editors believe that this is a critical time in the history of the advancement of men. Catholicity and tolerance, reason and forbearance can to-day make the world-old dream of human brotherhood approach realization; while bigotry and prejudice, emphasized race consciousness and force can repeat the awful his tory of the contact of nations and groups in the past. We strive for this higher and broader vision of Peace and Good Will.     

The policy of <span class="crisis-title">The Crisis</span> will be simple and well defined:       

It will first and foremost be a newspaper: it will record important happenings and movements in the world which bear on the great problem of inter-racial relations, and especially those which affect the Negro-American.     

Secondly, it will be a review of opinion and literature, recording briefly books, articles, and important expressions of opinion in the white and colored press on the race problem.      

Thirdly, it will publish a few short articles.

Finally, its editorial page will stand for the rights of men, irrespective of color or race, for the highest ideals of American democracy, and for reasonable but earnest and persistent attempt to gain these rights and realize these ideals. The magazine will be the organ of no clique or party and will avoid personal rancor of all sorts. In the absence of proof to the contrary it will assume honesty of purpose on the part of all men, North and South, white and black.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The New Crisis (1925)](/Volumes/30/01/new_crisis.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Our Special Grievances (1918)](/Volumes/16/05/our_special_greivances.html)
* [The Truth (1912)](/Volumes/05/02/truth.html)

<!-- Similar articles end here -->