
---
title: 'Voting'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Nov. 1910
categories: 
  - Voting
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 1
  page: 11
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


If there is one thing that should be urged upon colored voters throughout the United States this fall it is independence. No intelligent man should vote one way simply from habit. Only through careful scrutiny of candidates and policies can a man put himself in position to help rule one hundred million people. It is because of the suspicion that colored men are not capable of doing this, or are unwilling to do it, that so many American citizens acquiesce in the nullification of democracy known as disfranchisement. Let every colored man who can, vote; and whether he vote the Republican or Democratic or Socialist ticket, let him vote it, not because his father did or because he is afraid, but because after intelligent consideration he thinks the success of that ticket best for his people and his country.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Young Voters (1932)](/Volumes/39/09/young_voters.html)
* [Politics (1912)](/Volumes/04/04/politics.html)
* [The Colored Voter (1919)](/Volumes/17/01/colored_voter.html)
* [The Election (1910)](/Volumes/01/02/election.html)
* [Votes for Women (1912)](/Volumes/04/05/votes_for_women.html)

<!-- Similar articles end here -->