
---
title: 'Pan-Africa and New Racial Philosophy'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Oct. 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 10
  page: 247, 262
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


We have considered all these matters in relation to the American Negro but our underlying thought has been continually that they can and must be seen not against any narrow, provincial or even national background, but in relation to the great problem of the colored races of the world and particularly those of African descent.

There are still large numbers of American Negroes who in all essential particulars conceive themselves as belonging to the white race. And this, not on account of their color, which may be yellow, brown or black, but on account of their history and their social surroundings. They react as white Americans. They have all the racial prejudices of white America, not only against Asiatics and Jews, but even against Mexicans and West Indians. In all questions of human interest, they would flock to white America before they would flock to the brown West Indies or to black Africa or to yellow Asia.

This, of course, is quite natural, and in a sense proves how idiotic most of our racial distinctions are. Here is a boy, born in America, of parents who were born in America, of grandparents and great grandparents born in America. He speaks the American twang; he reads American history, he gets his news from American papers, and he understands American baseball. It is impossible for that boy to think of himself as African, simply because he happens to be black. He is an American. But on the other hand, as he grows up and comprehends his surroundings, he is going to be made to think of himself as at least a peculiar sort of American. Against this, he is going to protest, logically and emotionally, and dwell upon the anomaly of a person being outcast and discriminated against in his own home. Gradually, however, he is going to find that this protest has only limited effect; that to most white Americans of today, Negro prejudice is something that is beyond question and will. It is a stark, true fact and little or nothing can be done about it at present. In the future, the long future, things may change. But they are not going to change in the lifetime of those now living.

So long now as this is an academic question, a matter of attitudes and thoughts and spiritual likes and dislikes, we can leave it there. But when it becomes an economic problem, a stark matter of bread and butter, then if this young, black American is going to survive and live a life, he must calmly face the fact that however much he is an American there are interests which draw him nearer to the dark people outside of America than to his white fellow citizens.

And those interests are the same matters of color caste, of discrimination, of exploitation for the sake of profit, of public insult and oppression, against which the colored peoples of Mexico, South America, the West Indies and all Africa, and every country in Asia, complain and have long been complaining. It is, therefore, simply a matter of ordinary common sense that these people should draw together in spiritual sympathy and intellectual co-operation, to see what can be done for the freedom of the human spirit which happens to be incased in dark skin.

This was the idea that was back of the Pan-African Congresses; started in Paris directly after the war, and carried on for several years. These Congresses brought upon themselves the active enmity and disparagement of all the colony-owning powers. Englishmen, Frenchmen, Belgians and others looked upon the movement as a political movement designed to foment disaffection and strife and to correct abuse by force.

It may be that in the end nothing but force will break down the injustice of the color line. But to us who have seen and known the futility of war, the ghastly paradox of talking about Victor and Vanquished in the last world holocaust, there is a feeling that we must desperately try methods of thought and co-operation and economic re-adjustment before we yield to councils of despair. And in this program, all that has been said about economic readjustment in America for American Negroes can be said with even more emphasis concerning the Negroes of the world and concerning the darker peoples. These people raise everything necessary to satisfy human wants. They are capable of carrying on every process by which material, transported and re-made, may satisfy the needs and appetites of men.

 They are all of them willing and eager to work, and yet because their work is misdirected in order to make a profit for white people, these dark people must starve and be unemployed.

 

Here in the United States the net result of the National Recovery Act so far has been to raise wages for a small number of favored white workers and to decrease wages or push out of employment entirely the Negro. It is possible that this present result may in time be changed, and we note with interest what Secretary Ickes has said to the State Engineers and Public Works Administration:

> It is important to bear in mind that the Public Works Administration is for the benefit of all the people of the country. The established policy in the construction of public buildings and public works under its control is that in the employment of mechanics and labor, preference be given to local labor to the extent that it is available and competent, and that there be no discrimination exercised against any person because of color or religious affiliation.

Nevertheless, this we feel is going to make little difference so long as the American people believe that any white men of whatever character or education is better than any possible colored man.

It is, therefore, imperative that the colored peoples of the world, and first of all those of Negro descent, should begin to concentrate upon this problem of their economic survival, the best of their brains and education. Pan-Africa means intellectual understanding and co-operation among all groups of Negro descent in order to bring about at the earliest possible time the industrial and spiritual emancipation of the Negro peoples.

Such a movement must begin with a certain spiritual housecleaning. American Negroes, West Indians, West Africans and South Africans must proceed immediately to wipe from their minds the preconcepts of each other which they have gained through white newspapers. They must cease to think of Liberia and Haiti as failures in government; of American Negroes as being engaged principally in frequenting Harlem cabarets and Southern lynching parties; of West Indians as ineffective talkers; and of West Africans as parading around in breech-clouts.

These are the pictures of each other which white people have painted for us and which with engaging naiveté we accept, and then proceed to laugh at each other and criticize each other before we make any attempt to learn the truth. There are, for instance, in the United States today several commendable groups of young people who are proposing to take hold of Liberia and emancipate her from her difficulties, quite forgetting the fact that Liberia belongs to Liberia. They made it. They suffered and died for it. And they are not handing over their country to any group of young strangers who happen to be interested. If we want to help Liberia, our business is to see in what respect the Liberians need help, and the person best able to give this information are the Liberians themselves.

It is a large and intricate problem but the sooner we put ourselves in position to study it with a vast and increasing area of fact and with carefully guided and momentarily tested effort, the sooner we shall find ourselves citizens of the world and not its slaves and pensioners.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Correspondence (1926)](/Volumes/31/05/correspondence.html)
* [The Strength of Segregation (1913)](/Volumes/07/03/strength_of_segregation.html)
* [Unity (1924)](/Volumes/28/03/unity.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Jim Crow (1919)](/Volumes/17/03/jim_crow.html)

<!-- Similar articles end here -->