
---
title: 'A Momentous Proposal'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 16
  issue: 5
  page: 215-216
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


A plan of far-reaching constructive effort to satisfy the pressing grievances of colored Americans has been under serious consideration by the military authorities at Washington for two months. On June 15, Dr. Du Bois was called in and asked if he would accept a captaincy in a bureau of the General Staff, if one was established, for the above purposes. Dr. Du Bois replied that he would, provided he could retain general oversight of <span class = "small-caps">The Crisis</span>, and provided that his captain's salary (which was $1,000 less than his present salary) could be supplemented from <span class = "small-caps">The Crisis</span> income, so that he would suffer no financial loss. The military authorities saw no objection to these conditions. Dr. Du Bois then consulted the President of the Board of Directors of the N.A.A.C.P., the chairman and the acting chairman of the Board and several members, including Dr. H. C. Bishop, Bishop Hurst, Dr. Bentley, Mr. A. H. Grimke, Colonel Charles Young, Rev. G. R. Waller, Hon. Charles Nagel and Dr. V. Morton-Jones. All of them, except Mr. Grimke, agreed with the conditions and urged acceptance. Mr. Grimke expressed deep sympathy, but asked more time for consideration. No decision, however, as to establishing the Bureau was arrived at and when the regular July meeting of the Board took place, the priority of the  Government's claim on Dr. Du Bois was recognized, but doubt was expressed as to the advisability of his continuing in charge of <span class = "small-caps">The Crisis</span>.

A puzzling dilemma between devotion to his life work and duty to his country in time of war was thus forced upon Dr. Du Bois. His final conclusion, painful as it had to be, was to accept the commission. When thousands are giving their lives to their country, how could he long hesitate in risking far less? This delicate situation was further complicated by vague rumors which led friends of the Association with more zeal than thought to charge the Government with attempted "bribery" and Dr. Du Bois with being a "traitor." Some who disagreed with the July editorials of <span class = "small-caps">The Crisis</span> saw in them further evidences of a "corrupt bargain," not knowing that those editorials were written two weeks before Dr. Du Bois had the slightest intimation that his services were to be asked, and were in print before he reached Washington.

Finally, the General Staff, after carefully considering the matter from all angles, has decided not to establish the proposed bureau "at present" as its broad scope might lead "beyond the proper limits of military activity."

Here the matter rests. It is deplorable that this splendid and statesmanlike plan has been abandoned and equally unfortunate that any question as to its desirability should have ever arisen among black folk. The personal side of it is of less consequence and has left Dr. Du Bois in unruffiled serenity. No one who essays to teach the multitude can long escape crucifixion.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Our Special Grievances (1918)](/Volumes/16/05/our_special_greivances.html)
* [Robert R. Moton (1919)](/Volumes/18/01/robert_moton.html)
* [Dr. Du Bois Resigns (1934)](/Volumes/41/08/dr_dubois_resigns.html)
* [An Open Letter to Robert Russa Moton (1916)](/Volumes/12/03/open_letter.html)
* [We Come of Age (1915)](/Volumes/11/01/we_come_of_age.html)

<!-- Similar articles end here -->