
---
title: 'The Reward'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 16
  issue: 5
  page: 216-217
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




Certain honest thinkers among us hesitate at that last sentence. They say it is all well to be idealistic, but is it not true that while we have fought our country's battles for one hundred fifty years, we have *not* gained our rights? There is just enough fact in this half truth to make it a whole and a very mischievous lie. No, we have not gained all our rights, but we have gained rights and gained them rapidly and effectively by our loyalty in time of trial.

Five thousand Negroes fought in the Revolution; the result was the emancipation of slaves in the North and the abolition of the African slave trade. At least three thousand Negro soldiers and sailors fought in the War of 1812; the result was the enfranchisement of the Negro in many Northern States and the beginning of a strong movement for general emancipation. Two hundred thousand Negroes enlisted in the Civil War, and the result was the emancipation of four million slaves, and the enfranchisement of the black man. Some ten thousand Negroes fought in the Spanish-American War, and in the twenty years ensuing since that war, despite many set backs, we have doubled our landholding acreage and quadrupled our accumulated wealth. We have established a strong leadership of education and character, we have expanded our business interests and we have established the N.A.A.C.P., with forty thousand members.

God knows we have enough left to fight for, but any people who by loyalty and patriotism have gained what we have in four wars ought surely to have sense enough to give that same loyalty and patriotism a chance to win in the fifth.

And we are winning right now. Since this war began we have won:

<ul style="list-style-type:none;">
 <li>Recognition of our citizenship in the draft;
 <li>One thousand Negro officers;
 <li>Special representation in the War and Labor Departments;
 <li>Higher wages and better employment;
 <li>Abolition of the color line in rail way wage;
 <li>Recognition as Red Cross nurses;
 <li>Overthrow of segregation ordinances;
 <li>A strong word from the President against lynching.</p>
</ul>

Blessed saints! Is this nothing? Should it not discourage slackers and fools? Come, fellow black man, fight for your rights, but for God's sake have sense enough to know when you are getting what you fight for.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [We Should Worry (1917)](/Volumes/14/02/we_should_worry.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [The Negro Soldier (1919)](/Volumes/19/02/negro_soldier.html)
* [Help Us to Help (1918)](/Volumes/16/04/help_us.html)
* [Violence (1934)](/Volumes/41/05/violence.html)

<!-- Similar articles end here -->