
---
title: 'Labor Omnia Vincit'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 5
  page: 231-232
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




Labor conquers all things---but slowly, O, so slowly. Ever the weary worldlings seek some easier, quicker way---the Way of Wealth, of Privilege, of Chance, of Power; but in the end all that they get---Food, Raiment, Palace and Pleasure---is the result of Toil, but not always of their own toil. The great cry of world Justice today is that the fruit of toil go to the Laborer who produces it. In this labor of Production we recognize effort of all sorts---lifting, digging, carrying, measuring, thinking, foreseeing; but we are refusing to recognize Chance, Birth or Monopoly as just grounds for compelling men to serve men.

In this fight for Justice to Labor the Negro looms large. In Africa and the South Seas, in all the Americas and dimly in Asia he is a mighty worker and potentially, perhaps, the mightiest. But of all laborers cheated of their just wage from the world's dawn to today, he is the poorest and bloodiest.

In the United States he has taken his fastest forward step, rising from owned slave to tied serf, from servant to day laborer, from scab to half-recognized union man in less than a century. Armies, mobs, lynchers, laws and customs have opposed him, yet he lurches forward. His very so called indolence is his dimly-conceived independence; his singing soul is his far-flaming ideal; and nothing but organized and persistent murder and violence can prevent him from becoming in time the most efficient laboring force in the modern world.

Meantime, in the world round him, the battle of Industrial Democracy is being fought and the white laborers who are fighting it are not sure whether they want their black fellow laborer as ally or slave. If they could make him a slave, they probably would; but since he can underbid their wage, they slowly and reluctantly invite him into the union. But can they bring themselves inside the Union to regard him as a man---a fellow-voter, a brother?

No---not yet. And there lies the most stupendous labor problem of the twentieth century---transcending the problem of Labor and Capital, of Democracy, of the Equality of Women---for it is the problem of the Equality of Humanity in the world as against white domination of black and brown and yellow serfs.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Future of Africa (1919)](/Volumes/17/03/future-of-africa.html)
* [The Negro and Labor (1922)](/Volumes/25/06/negro_and_labor.html)
* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)
* [Eugene Debs (1926)](/Volumes/33/02/debs.html)
* [The Drive (1922)](/Volumes/22/01/drive.html)

<!-- Similar articles end here -->