
---
title: 'Let us Reason Together'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 5
  page: 231
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Brothers we are on the Great Deep. We have cast off on the vast voyage which will lead to Freedom or Death.

For three centuries we have suffered and cowered. No race ever gave Passive Resistance and Submission to Evil longer, more piteous trial. Today we raise the terrible weapon of Self-Defense. When the murderer comes, he shall not longer strike us in the back. When the armed lynchers gather, we too must gather armed. When the mob moves, we propose to meet it with bricks and clubs and guns.

But we must tread here with solemn caution. We must never let justifiable self-defense against individuals become blind and lawless offense against all white folk. We must not seek reform by violence. We must not seek Vengeance. "Vengeance is Mine," saith the Lord; or to put it otherwise, only Infinite Justice and Knowledge can assign blame in this poor world, and we ourselves are sinful men, struggling desperately with our own crime and ignorance. We must defend ourselves, our homes, our wives and children against the lawless without stint or hesitation; but we must carefully and scrupulously avoid on our own part bitter and unjustifiable aggression against anybody.

This line is difficult to draw. In the South the Police and Public Opinion back the mob and the least resistance on the part of the innocent black victim is nearly always construed as  a lawless attack on society and government. In the North the Police and the Public will dodge and falter, but in the end they will back the Right when the Truth is made clear to them.

But whether the line between just resistance and angry retaliation is hard or easy, we must draw it carefully, not in wild resentment, but in grim and sober consideration; and then back of the impregnable fortress of the Divine Right of Self-Defense, which is sanctioned by every law of God and man, in every land, civilized and uncivilized, we must take our unfaltering stand.

Honor, endless and undying Honor, to every man, black or white, who in Houston, East St. Louis, Washington and Chicago gave his life for Civilization and Order.

If the United States is to be a Land of Law, we would live humbly and peaceably in it---working, singing, learning and dreaming to make it and ourselves nobler and better; if it is to be a Land of Mobs and Lynchers, we might as well die today as tomorrow.

<div class="poem">
<p class="verse"><em>And how can man die better</em>
<p class="verse"><em>Than facing fearful odds</em>
<p class="verse"><em>For the ashes of his fathers</em>
<p class="verse"><em>And the temples of his gods?</em>
</div>

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Thirteen (1918)](/Volumes/15/03/thirteen.html)
* [Crime (1920)](/Volumes/19/04/crime.html)
* [Logic (1913)](/Volumes/06/02/logic.html)
* [Forward (1920)](/Volumes/20/05/forward.html)
* [Awake America (1917)](/Volumes/14/05/awake_america.html)

<!-- Similar articles end here -->