
---
title: 'The Riots: An N.A.A.C.P. Investigation'
author: Johnson, James Weldon
date: Mar. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 5
  page: 241-244
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


I reached Washington early in the evening of July 22. As the train neared the capital I could feel the tenseness of the situation grow. It showed itself in the air of the passengers as they read the newspapers, with their glaring headlines telling of the awful night before and intimating that the worst was yet to come. As I  passed through the cars on my way to the diner and back, men and women glanced up at me with what seemed to be a look with a glance which of mild surprise; seemed to say, "This man must indeed have very important business in Washington."

The porters and waiters plainly showed the strain under which they were doing their work---the strain of suppressed excitement with, perhaps, an added sense of dread of going into something, they knew not what. They moved about quietly, in fact, grimly and entirely without their customary good humor and gaiety. One of the porters who knew who I was questioned the wisdom of my going through with the trip. I may have felt that his question was not absolutely without reason, but I did not admit it. When I left the car he said to me, "Take good care of yourself." I assured him that I would spare no effort to do so.

I had made many trips to Washington---some as a mere visitor, some as a member of the Government's Foreign Service, some for the purpose of placing for the National Association matters affecting the race before men high in authority and position; and so I had experienced varied emotions on making the trip to the Nation's Capital, but none like the emotions experienced on this trip. I knew it to be true, but it was almost an impossibility for me to realize as a truth that men and women of my race were being mobbed, chased, dragged from street cars, beaten and killed within the shadow of the dome of the Capitol, at the very front door of the White House. It was almost an impossibility for me to realize that, perhaps, my own life would not be safe on the public streets.

When we reached the Northwest Section of the city, I found the whole atmosphere entirely different. I had expected to find the colored people excited and, perhaps, panicky; I found them calm and determined, unterrified and unafraid. Although on the night before shots had blazed all through the night at the corners of Seventh and T Streets and Fourteenth and U, I could detect no signs of nervousness on the part of the colored people living in the section. They had reached the determination that they would defend and protect themselves and their homes at the cost of their lives, if necessary, and that determination rendered them calm.

Still, under the outward calm, there was a tautness that could be sensed. Wild rumors had been circulating all day foreboding terrible things; and these things, whatever they might be, the colored people had made up their minds to meet. But as darkness came on, the rain began to fall, and later it fell in torrents; so it may be that the rain had something to do with the things that did not happen.

That evening I met with a half-dozen of the influential colored men of the city. We talked over what had happened and discussed the steps already taken by the authorities and by the colored citizens and such steps as we thought it well to take on the following day.

The next morning Mr. Seligmann and I had a conference with Major Pullman, Chief of Police, regarding the protection of colored citizens. At this interview Mr. Seligmann secured for the information of the National Office and for purposes of publicity data regarding all the alleged cases of attacks on women which had been put forward as the cause of the riots. Our conference with Major Pullman lasted an hour; he expressed a desire to have us talk with Commissioner Brownlow and made an appointment with him for us at two o'clock in the afternoon. Before we left Major Pullman's office a committee consisting of Dr. A. M. Curtis, young Dr. Curtis and Mr. Emmett J. Scott, accompanied by Captain Doyle of the 8th Police Precinct, came to ask that the Police Department swear in a number of colored men as Special Officers to aid in preserving law and order. Mr. Seligmann and I remained and gave our support to the committee. However, it was plain that Major Pullman was not favorable to the plan. He suggested that the committee take the matter up with his superior, Commissioner Brownlow. Mr. Seligmann and I then informed the committee of our appointment with the Commissioner at two o'clock, and invited them to go.

In the afternoon we had a long conference with Commissioner Brownlow. The whole situation was gone over, and the plan of commissioning colored men as Special Officers was brought up. The Commissioner was stronger in his opposition than the Chief of Police.

In the evening I attended a meeting of the Executive Committee of the Washington Branch to learn what the branch had done and was doing, and to offer such suggestions as I might. I found that the branch had been active as far back as July 9, when it sent a strong letter to all four of the Washington daily papers, calling their attention to the fact that they were sowing the seeds of a race riot by their inflammatory headlines and sensational news articles. After the outbreak of the riots a committee had been appointed which went before Commissioners Brownlow and Gardner and before Major Pullman to urge that effective action be taken to prevent assaults upon defenseless colored people who were the victims of the attacks. Members of the Legal Committee had spent considerable time in court in connection with the trials of the men who had been arrested for carrying weapons for their protection. A committee was set at work obtaining affidavits from victims of the riot who had been wounded or injured. And at this meeting the Legal Committee was authorized to interview all colored persons charged with rioting and offer them legal assistance.

On the following morning I went to the Capitol and talked at length with three influential Senators. I went over the whole situation, not only local, but national, with these Senators, and did my best to show them what I considered to be the principal causes of the trouble. I also spoke to each one of them regarding a Congressional investigation of the whole question of mob violence. I was able to secure from one of these Senators, who has been in Congress for twenty-five years and is a member with experience and prestige, and who is also a strong advocate of justice for the Negro, the promise that he would father a resolution calling for such an investigation and a printed report on the same.

In the afternoon I went to the office of the *Washington Post* and talked with the city editor. It was the *Post* which on Monday morning had published the "Mobilization for Tonight" call to the idle service men in Washington to meet near the Knights of Columbus hut on Pennsylvania Avenue, and organize a "clean up." When I handed the city editor my card, he appeared glad to see me. He seemed to be under the impression that I had come down from New York for the express purpose of telling the colored people in Washington to be "good." He called a reporter and asked me to tell him what the Association was doing and proposed to do in the matter.

I lost no time in telling him that the  organization which I represented stood for law and order; that all the fights it had made in behalf of the colored people had been made through and under the law; but that my reason for calling on him was not to discuss that phase of the situation. I then proceeded to tell him frankly and directly how responsible were the *Washington Post* and the other Washington dailies for what had taken place.

I talked with him for, perhaps, half an hour. During the whole time he stood as one struck dumb; at least, he answered not a word. I realized that the man was scared through and through. He asked me before I left if I thought the riots were over. I told him I thought they were, unless the whites again took the aggressive. I was surprised to see the next morning that the *Post* published some of the things I had said.

The next day, accompanied by Mr. R. C. Bruce, I made similar visits to the offices of the *Washington Times* and the *Washington Star*. In the afternoon I talked again with one of my Senators. At night I left for New York.

I returned disquieted, but not depressed over the Washington riot; it might have been worse. It might have been a riot in which the Negroes, unprotected by the law, would not have had the spirit to protect themselves.

The Negros saved themselves and saved Washington by their determination not to run, but to fight---fight in defense of their lives and their homes. If the white mob had gone on unchecked---and it was only the determined effort of black men that checked it---Washington would have been another and worse East St. Louis.

As regrettable as are the Washington and the Chicago riots, I feel that they mark the turning point in the psychology of the whole nation regarding the Negro problem. <span class = "small-caps">James Weldon Johnson</span>.

Major J. E. SPINGARN reached Chicago, on his way to the West, July 30 and for twenty-four hours did active work for the Association. At his suggestion a committee called on Governor Lowden, on July 30, and among other matters discussed the appointment of a commission of five or eight to study race troubles and to formulate a definite program on race relations for the state,

On July 30 Mr. John R. Shillady, Secretary, and Mr. Herbert J. Seligmann, Director of Publicity, reached Chicago and at once plunged into work relating to the riots. A great amount of publicity in the daily press under the Association's name is due to Mr. Seligmann's tireless work. Mr. Shillady sends the following notes:

> There was formed upon my initiative a Joint Emergency Committee to deal with the situation as regards the needs of the colored community, in so far as all elements will work through this committee. This committee is a committee of an executive character, on matters of policy and action, but leaving constituent organizations free to do such part of the work as they may be willing and able to do. The committee consists of one each from the Cook County Bar Association  (colored lawyers' organization), the Urban League, the Y. M. C. A., the N.A.A.C.P. and Ministers-Social Workers Citizens Conference, the last a group which has been meeting daily at Olivet Baptist Church, 31st and South Park Avenue. Further, each representative member is to have an alternative, so that some one will always be available to meet as often as is required.    <p> The lawyers furnish free one of their number to be at each police station and court every morning, to take charge of the legal defense of any colored person needing such service. Headquarters have been arranged for at Olivet Baptist Church, where two lawyers, at least one stenographer, and necessary investigators, paid and volunteer, will be stationed to receive relatives and friends of men in jail and under arrest.

