
---
title: 'Signs from the South'
author: Du Bois, W.E.B.
date: Mar. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 5
  page: 233-234
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There are signs---faint and few, but hopeful---that the South is slowly learning the inevitable lesson that no true democracy can be confined to a sex or a race and live.

In Putnam County, Ga., because a Negro made "some insulting remarks about serving white people and not serving a Negro," the enraged whites burned five Negro churches, two Negro schools and one schoolhouse. Immediately the more decent whites offered $1,100 reward for the criminals and started a fund of $5,000 toward rebuilding. Of course, no one will ever be punished for the arson, but the community did speak out in clear condemnation.

In Alabama, twelve men have been convicted as lynchers---two to long jail terms. This is excellent, but we must add that the victim was a white foreigner and the lynchers were ignorant fishermen without wealth or influence.

Finally, in Washington County, Miss., Sheriff Alexander writes to the public concerning a colored prisoner: 

> I have been asked by the Governor of the State if I wished to remove Williams from the county for safekeeping, or if I desired assistance from him in the protection of him. I have replied that I did not wish to remove the Negro and that I needed no outside help to protect him. ...   
> &nbsp;    
> No friends of mine, and I count the citizens of Washington County my
friends, will attempt to take a prisoner out of my hands, and no man who
is not a friend of mine and of law and order can do it.

