
---
title: 'Arkansas'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 4
  page: 169-170
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



A desperate attempt is being made by white people in Arkansas, to prove their love and care for the Negro and to deny that the lawlessness in Phillips County was a "race riot." Evidence, however, comes to us from another source, showing the Arkansas state of mind. Two prominent Negroes in that state, brothers, applied for life insurance. The company to which they applied, following the usual custom of life insurance companies, secured a confidential report from a leading white bureau of investigation. This bureau reported confidentially as follows: that these colored men were worth $30,000 in property, with an annual income of $4,800; that they were in healthful occupations and were good risks, "except as noted below." One of the notations is as follows:

> This is one of the ------ family, that is supporting equal rights for Negroes,---voting, railroad, hotel, and anti-lynching, etc. This does not sit well in the South and will not be tolerated, as stated on other application. The feeling is already pretty strong against the family for that reason, and a continuance by them is likely to lead to something bad. I feel it my duty to make mention of these facts, which can be easily substantiated by most of white people in the county; otherwise, the boy is all right from insurance standpoint.

This in Arkansas, in the Year of Grace 1919, and of the Independence of the United States, the One Hundred and Forty-Third!

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Information Wanted (1920)](/Volumes/19/05/information_wanted.html)
* [Flood (1927)](/Volumes/34/05/flood.html)
* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)
* [Knowledge (1911)](/Volumes/02/06/knowledge.html)
* [Death Rates (1927)](/Volumes/34/08/death_rates.html)

<!-- Similar articles end here -->