
---
title: 'Danger'
author: Du Bois, W.E.B.
date: Feb. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 4
  page: 169
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



*The Sterling Bill (S 3,317) has passed the Senate and is before the House. The Graham Bill, (H.R. 11,430), has been favorably reported by the House Committee. Both bills are before the Committee on Rules, and before this reaches our readers, may be before the House. Section 6 of the Graham Bill is as follows:*

> That every book, magazine, newspaper, document, handbill, poster, or written pictorial, or printed matter, memorandum, sign, symbol, or communication of any form ... wherein and whereby an appeal is made to racial prejudice, the intended or probable result of which appeal is to cause rioting or the resort to force and violence within the United States or any place subject to the jurisdiction thereof, is hereby declared to be non-mailable, and the same shall not be deposited in any post office for mailing.

This section is designed primarily to stop <span style="font-variant:small-caps;">The Crisis</span> magazine and other leading Negro periodicals. Every honest man knows that far from advocating violence, it is precisely violence, lynching, disfranchisement, and lawlessness that <span style="font-variant:small-caps;">The Crisis</span> was founded to oppose, but under such a law, a list of lynchings might be judged as "appealing to racial prejudice."

*Wire, therefore, IMMEDIATELY to your Congressman and Senator and oppose this Section of the bill, unless it is amended so as to allow "any and all agitation or propaganda to enforce law by Constitutional methods."*

