
---
title: 'Leadership'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 4
  page: 173
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Many a good cause has been killed by suspected leadership. For a thousand years, the world had dreamed of a Nation of Nations. Ever since the fall of Imperial Rome, the need of a united world organization of culture has been felt. The greatest thinkers, the greatest leaders, have dreamed and sung and prophesied of this Empire of All.

Today the reality comes---but who leads it? England and Woodrow Wilson. England who has, with cold blood and calculating selfishness, reaped from the war:

1.  Unhampered dominion of the seas, which she refuses even to argue
2.  Two-thirds of Africa
3.  The final conquest of Egypt
4.  The domination of Persia
5.  Six votes in the League of Nations
6.  The domination of Arabia.

Woodrow Wilson, in following a great ideal of World Unity, forgot all his pledges to the German people,  forgot all his large words to Russia, did not hesitate to betray Gompers and his Unions, and never at any single moment meant to include in his Democracy twelve million of his fellow-Americans, whom he categorically promised "more than mere grudging Justice," and then allowed 350 of them to be lynched during his presidency.

Under such leadership, what cause could succeed? Not even the opposition of a copperhead reactionary, like Lodge, or a Negro hater, like Borah, could arouse the suspicion of real men when a great cause was championed by a selfish Imperialism and a selfish Egotism. Yet the League of Nations is a fact and must succeed, for civilization needs it; and this, despite itg present champions and enemies.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Flaming Arrows (1919)](/Volumes/17/01/flaming_arrows.html)
* [The League of Nations (1919)](/Volumes/19/01/league.html)
* [Listen, Japan and China (1933)](/Volumes/40/01/listen_japan_and_china.html)
* [Close Ranks (1918)](/Volumes/16/03/close_ranks.html)
* [The World in Council (1911)](/Volumes/02/05/world.html)

<!-- Similar articles end here -->