
---
title: 'A Matter of Manners'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 4
  page: 170
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



At the time of the Chicago riots, Medill McCormack, United States Congressman from Illinois, was reported as follows in an interview:

> Thousands of these colored boys came to Chicago from the South. They were used to being handled without concern down there, and when they came to Chicago, they had a kind of an idea that they could sit in your lap, or do anything they pleased.    
> &nbsp;    
> I can best define the situation here by an instance that happened in Washington, the other day. A colored boy, carrying a package under his arm, got into the elevator, where we were followed by a white woman. The men have a habit of taking off their hats in an elevator when women enter.   
> &nbsp;    
> All took off their hats, but the Negro. I said to him, "Why don't you take off your hat?" He said, "I don't have to, do I?" I told him, "No, you don't have to, but that is the custom of the city." He said, "Well, there is no law against it. Is there?" I told him there was no law against it.   
> &nbsp;    
> As we got off the elevator, a southern gentleman said: "That's the way with darkies that come from the North now. Unless they are compelled to comply with customs, they will not do so."   
> &nbsp;    
> And that is about the situation here. And I am afraid that this will spread all over the country. It looks very serious.

In other words, bad manners or bumptiousness or excessive egotism on the part of a young colored boy, is serious enough to lead to murder, riot, and social upheaval. While, on the other hand, the treating of that same colored boy "without concern down South," is a matter of no concern up North. Here lies the very meat of the Negro problem.

Moreover, there is another and more subtle thing that must be considered. Whether it played a part in this case or not, one cannot know. If colored men are polite to white women, their efforts are easily liable to the most outrageous misconstruction. Rather, then, than appear to want in the slightest degree to approach white women, they adopt an attitude, not only indifferent, but hostile. It is because of this, that many colored men do not give their seats to white women in street cars and studiously avoid the little courtesies which would be their natural reaction. Too many of them have at some time been rewarded for such efforts by a stare, an insulting word, or even a blow from some passer-by.

Even worse may happen: In Roanoke, Va., a black boy and a white girl were crossing a bridge, in opposite directions. Just as the girl was opposite the boy, she slipped and fell. The boy stretched out his hand to help her. He was promptly lynched by a mob, despite the vehement protest of the white State's Attorney. American white women are, in numbers of cases, used to treating Negroes publicly as the dirt beneath their feet. Very well, says the Negro, courtesy is not expected of dirt. We are not defending this attitude; we are merely explaining it.

