
---
title: 'The Unfortunate South'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 4
  page: 169
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Mankind at best is poor, ignorant, and disappointing. He falls so far below his own ideals that he easily loses faith in himself when he looks squarely into his own eyes. This is a universal truth; but the white South is curiously blinded from seeing it. To it, it is not mankind, but Negro mankind that is poor, ignorant, disappointing, and criminal. There is no use trying to uplift Negroes. Whatever good one may learn and hear of them, is vastly overbalanced by the bad one may learn. If the whites, too, are disappointing, this is because of the presence of the blacks, etc.

Small wonder that the average half-educated Southerner can see no social problem in the world, but the Negro problem,---and no solution to that. Small wonder that out of this mental attitude, there is arising in the South, no literature or art, except that based on the Negro,---and that only serious and great when it edits purely Negro matter, as in the case of Joel Chandler Harris.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Light (1912)](/Volumes/03/04/light.html)
* [The Newer South (1926)](/Volumes/31/04/newer_south.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Suffrage (1920)](/Volumes/21/01/suffrage.html)
* [Education (1911)](/Volumes/01/04/education.html)

<!-- Similar articles end here -->