
---
title: 'Again Howard'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1932
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 39
  issue: 4
  page: 131
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




We trust that none of the friends of Negro education will be disconcerted at the smoke-screen now being industriously spread over the situation at Howard University. Despite widespread and anonymous accusations printed in the Negro and white press, neither the ability nor integrity of the president of Howard University is at all in question. The real question is the conduct of the office of the secretary-treasurer and the plans of the Washington Real Estate Trust. Despite three years' effort, Dr. Mordecai Johnson has not been able to get a modern budget system established at Howard University. His every effort in this line has been balked and sabotaged, and it is as true today as it was when he came to the presidency, that, the trustees do not know and do not attempt to find out just what the income of Howard University is, and exactly how it is spent.

No president, with his hands thus tied, can succeed. When, in addition to that, the white real estate interests of Washington, together with their colored tools, attempt to force the executive to buy factory sites and apartment houses out of funds appropriated by the General Education Board for other areas, the situation becomes a crying shame and calls for reform. It is natural, then, that the rats in the hulk of this great vessel should scamper to cover and endeavor to make the public believe that the trouble at Howard centers in the question of a young engineer's appointment or some petty official's dismissal. The real center is the question as to whether the secretary-treasurer can be forced to install a modern budget system or to let someone else install it who has the will and ability; and the further question, as to the purging out of the present Board of Trustees certain white elements whom the highest officials of the District of Columbia know to be untrustworthy and dishonest.

__________
*Citation:* Du Bois, W.E.B. 1932. "Again Howard." *The Crisis*. 39(4):131.