
---
title: 'Blaine of Maine'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Aug. 1932
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 39
  issue: 8
  page: 267
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The semi-secret and persistent propaganda on the history and meaning of the Civil War still keeps up to an astonishing degree. No book or article can get even a respectful hearing among the leading reviewers of the nation unless it subscribes fully to this thesis:
1. The cause of the Civil War was not slavery.
2. The South would have emancipated the Negroes of its own accord.
3. There was no cruelty or essential degradation in the slave system.
4. The enfranchisement of Negroes was a mistake.
5. The evils of Reconstruction were mainly the result of emancipating slaves and making them citizens and voters.
6. The Negro officials of the South were venal and ignorant and Negro rule had to be put down by force and fraud.
7. The radicals of the North were inspired by spiteful hatred and sought to punish and humiliate the white South.
8. The white Southerners received their defeat in good faith, bore no animosity toward the North, and were disposed to treat the Negroes with fairness and even kindness.

This thesis was begun by Dunning of Columbia, carried out in a series of monographs by young students at Columbia and Johns Hopkins University, sanctified by James Ford Rhodes, and lately has received new life and extraordinary emphasis in such books as "The Tragic Era," by Claude Bowers, "Carl Schurz," by Fuess "The Rise of American Civilization," by Charles and Mary Beard, Milton's "Age of Hate," Carpenter's "The South as a Conscious Minority," and numbers of others widely advertised and highly praised volumes. On the other hand, books that dare differ in any way with this thesis are killed by silence or denunciation.  Frederick Bancroft's "Slave Trading in the Old South," Stewart's "Reward of Patriotism," Skagg's "The Southern Oligarchy," and last and first, Charles Edward Russell's "Blaine of Maine," are books that dare to take the Opposite stand and have been railed at or ignored.

Charles Edward Russell's "Blaine of Maine" is a splendid biography and would have been universally hailed as such if Mr. Russell had acquiesced in the philosophy of the Southerners. But imagine a book written today affirming Andrew Johnson when he took his oath as Vice President of the United States was so drunk that he could not repeat the sentences that Hamlin read! When he was President, "Delegations of colored men came to see him with appeals in behalf of their people, now faced with an economic crisis in the South. He contented himself with vague and rambling expressions of a general good will but nothing to show what he intended to do for them. He had always been their friend; all his career had shown that, he reminded them. Beyond this, nothing. Frederick Douglass was one of the speakers for one of these delegations and made an eloquent and logical plea. It was no more productive than the others had been."

 Or take this uncontrovertible statement of the problem of Reconstruction:

 > Who were to be voters at these elections in lately revolted states? The same classes of persons that had voted before the war? What was to be done about men of the South that had stood by the Union, that had been driven from their homes and were now returning there? Nothing. What was to be done about the four million emancipated Negroes? Nothing. Let all these shift for themselves. The main thing was apparently to get into Congress representatives from these states and restore there the pre-war status. <p> For what followed, blame has been laid heavily upon both sides, according to the prejudices, antecedents or ancestry of the writer. As a matter of fact, the results were probably inevitable. The most liberal minds in the North could hardly be expected to accept such a doctrine after the struggles and sacrifices of such a war. The men of the South, released from all danger of punishment and suddenly elevated to their old station in the government, could hardly be blamed for the conclusions they formed. In the war the decision had gone against them. They were now in effect assured by the President that they had done no wrong in waging that war. If they had done no wrong they must have been right. If the war was right the slavery for which alone they made the war must have been right also. And slavery being right as well as advantageous for many reasons, they proceeded to reenact it throughout the South.

This is the kind of book that Russell has written. It is not a volume of hero worship. He puts before us the picture of a man of rare ability, with many foibles, riding triumphantly on the current of his times. Russell refuses to falsify the facts. He declares that the convention elections which reconstructed the South were in every state "fair and honest elections." And that the corruption of the South after the war was not the corruption of black people or of white people, but the corruption of America, and the corruption which engulfed and ruined James T. Blaine.

This is a big book of nearly 450 pages, but for those who want to escape from the morass of propaganda which has been deliberately trying for fifty years to lie about slavery and the Civil War, it is the kind of book to be bought and read and handed along.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [An Open Letter (1915)](/Volumes/10/03/an_open_letter.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Socialism and the Negro (1921)](/Volumes/22/06/socialism_and_the_negro.html)
* [Emancipation (1913)](/Volumes/05/03/emancipation.html)
* [Loyalty (1917)](/Volumes/14/01/loyalty.html)

<!-- Similar articles end here -->