
---
title: 'Amity'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 3
  page: 101
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



A convention of colored and white people took place in Washington, D.C., in May, which deserves thought. The programs carried these words: 

> Half a century ago in America slavery was abolished.     <p> Now there has arisen need for another great effort.    <p>Correction of the present wrong requires no army, for the field of action is the hearts of our citizens. The instrument to be used is kindness; the ammunition, understanding of all by all. The actor in this engagement for right is every inhabitant of these United States.    <p>The great work we have to do and for which this convention is called is the establishment of amity between the white and colored people of our land.    <p> When we have put our own house in order, then we may be trusted to carry the message of universal peace to all mankind.

There were white and colored people present and their speeches were not all "problem" but carried poetry and music. 

Some folks seem to think that because <span class="small-caps">The Crisis</span> and the N.A.A.C.P. preach continually the gospel of fighting for your rights and standing up against oppression we mean by this that the Negro is to gain his place in the world by blood and conquest, God forbid! If the rights of the darker races can only be bought by brute force, then we face the saddest future that ever the world looked upon. But what we and what all thinking men mean by self-assertion and fighting is that when human beings insistently and even obtrusively succeed in putting their case before the world, they gain so great a multitude of allies that their cause is bound to succeed. The only difficulty is that such persons are so easily persuaded not to cry out, not to complain, not to disturb the world. Complaint, agitation, insistence day in and day out upon the wrong of evil, is a civilized and justifiable program; but after all its greatest effect must be upon the hearts and thoughts of men, and if in meetings of amity and friendship white and colored people in this land can sit together and talk frankly, the Negro problem is solved.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Present (1917)](/Volumes/14/04/present.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [An Open Letter to Woodrow Wilson (1913)](/Volumes/05/05/open_letter.html)
* [Divine Right (1912)](/Volumes/03/05/divine_right.html)
* [Muddle (1916)](/Volumes/13/02/muddle.html)

<!-- Similar articles end here -->