
---
title: 'Libelous Film'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 3
  page: 102
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---





Last month "The Birth of a Nation" with its cruel and indefensible libel of the Negro and glorification of the mob in the Ku Klux Klan was revived in several eastern cities. In Boston it was suppressed; in New York the N.A.A.C.P. planned a public protest. We secured former service men and women Y.M.C.A. secretaries who had served abroad, to march before the Capitol Theatre and distribute bills and carry placards. They were arrested. The first judge was vociferous and wanted to charge them with inciting riot. The second judge was calmer and offered to let them go if they would promise not to do it again. This they refused to do and were released on suspended sentence. They appealed the case. The names of these public servants are: Mrs. Helen Curtis, Mrs. Laura Jean Rollock, Miss Katherine Johnson, Edward F. Frazier and Llewelyn Rollock. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Coffeeville, Kanasas (1927)](/Volumes/34/05/coffeville_kansas.html)
* [Deception (1916)](/Volumes/12/02/deception.html)
* [Mob Tactics (1927)](/Volumes/34/06/mob_tactics.html)
* [Lynchings and Mobs (1921)](/Volumes/22/04/lynchings.html)
* [Tulsa Riots (1921)](/Volumes/22/03/tulsa_riots.html)

<!-- Similar articles end here -->