---
title: 'Optimism'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 33
  issue: 4
  page: 182-183
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Nothing is more dangerous than unintelligent optimism, childish faith in the triumph of good, the "God's-in-His-heaven" attitude assumed because one is too lazy to be worried. On the other hand, the worst moral dyspepsia must face facts; and looking back on the history of the Negro race in America for the last few years one cannot help feeling a sense of tremendous encouragement.

The legal defense of black men instead of being sporadic and occasional is taking definite, determined form and it is becoming increasingly difficult to cheat and oppress and mob colored people simply because they are colored.

But this, after all, is merely negative. Yet on the positive side there is even greater cause for self-congratulation. There is a new self-assertion which is not merely empty impudence. Quietly and unswervingly Negroes have laid down the law that their higher institutions of learning can no longer be run regardless of colored folks' ideals and desires. Again Negroes have begun to undertake their own self-interpretation and are no longer content merely to sit by, smiling delightedly when some white outsider carelessly evaluates their history, their songs, their hopes, their personal appearance.

Following a rather sudden, almost hysterical renaissance of art among them, there is slowly coming a determined Will-to-Create. Self-expression wells up among us. Even though it is not all of the highest order and often lacks careful finish, it is nevertheless a true and sincere mirroring of new souls and valuable because of its sincerity and newness.

In the economic field one senses in every part of the country better home life, larger incomes and more careful spending. The old ideal of imitating the extravagance of the rich whites has not altogether passed but it is evidently passing. One finds little homes of cultured colored folk who are quite willing to admit that they are living on one hundred dollars a month and really living. Children are crowding into high schools and colleges not simply because it is the thing to do, but because their parents are getting clear ideas of just what education is for. There is a small new army of colored artisans who know the technique of their work and the labor movement. And finally, in the dull brain of white America, it is beginning to become clearly evident that the most virile future force in this land, certainly in art, probably in economics and possibly in science, is the Negro.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Optimism (1929)](/Volumes/36/05/optimism.html)
* [The Immediate Program of the  American Negro (1915)](/Volumes/09/06/immediate_program.html)
* [Counsels of Despair (1934)](/Volumes/41/06/counsels_of_despair.html)
* [Fraud and Imitation (1912)](/Volumes/04/03/fraud_and_imitation.html)
* [The White Church (1917)](/Volumes/14/01/white_church.html)

<!-- Similar articles end here -->