
---
title: 'I Go A-Talking'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 3
  page: 130--132
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


I have made a great journey to three of the four corners of this Western world, over a distance of 7,000 miles, and through thirty States; and I am overwhelmed almost to
silence over the things I have seen, the persons I have known and the forces I have felt.

First, of course, and foremost, comes a sense of the vastness of this land. The sheer brute bigness of its distances is appalling. I think of the endless ride of three days and four nights from the silver beauty of Seattle to the sombre whirl of Kansas City. I think of the thousand miles of California and the empire of Texas, the grim vastness of the desert, the wideness of the blue Pacific at San Diego—but all, is it not all typified at the Grand Canyon?

## The Grand Canyon

It is a cruel gash in the bosom of the earth down to its very entrails --- a wound where the dull titanic knife has turned and twisted in the hole, leaving its edges livid scarred, jagged and pulsing over the white and red and purple of its mighty flesh, while down below, down, down below, in black and severed vein, boils the dull and sullen flood of the Colorado.

It is awful. There can be nothing like it. It is the earth and skies gone stark and raving mad. The mountains up-twirled, disbodied and inverted stand on their peaks and throw their bowels to the skies. Their earth is air --- their ether blood-red rock engreened. You stand upon their roots and fall into their pinnacles a mighty mile.

Behold this mauve and purple mocking of time and space. See yonder peak! No human foot has trod it. Into that blue shadow only the eye of God has
looked. Listen to the accents of that gorge which mutters: "Before Abraham was, I am." Is yonder wall a hedge of black, or is it the rampart between Heaven and hell? I see greens --- is it grass or giant pines? I see specks that may be boulders. Ever the winds sigh and drop into those sun-swept silences. Ever the gorge lies motionless, unmoved, until I fear. It is an awful thing, unholy, terrible. It is human --- some mighty drama unseen, unheard, is playing there its tragedies or mocking comedy and the laugh of endless years is shrieking onward from peak to peak, unheard, unechoed and unknown.

## The Talks

Through such a gateway I came out to the cities of men and in these I made twenty-eight talks to audiences aggregating 18,000 human souls.

What wonderful and varied audiences they were: there was the vast theatre in Los Angeles where I strained to reach the last dim gallery rows; there was the little group of a hundred or so in Stockton, and the thoughtful half thousand down in San Diego and over in Indianapolis. Most of all, perhaps, I felt the throb of personal appreciation and understanding in St. Louis and Oakland, while the stillness of a deep earnestness, almost tragedy, lay on the audiences in Fort Worth and Atlanta.

At Los Angeles I spoke again and again to audiences that did not seem to tire, while in the wonderful Northwest I met the little group at Portland, the people of Tacoma—so tireless in their thoughtful care --- and crowned it all at Seattle, the wonder city that sits gleaming amid its waters with its face to the great North.

In the eighteen cities where I spoke live 500,000 Americans of Negro descent, and I cannot cease marveling at their grit and energy and alertness. They complain at themselves and criticise, but they are pulsing and alive with a new ambition and determinedness which were to me astounding.

## The Mid West

In Indianapolis, St. Louis and Kansas City strong groups of Negroes are uniting to fight segregation, to improve and defend the schools and to open the gate of opportunity for their children. They are not yet united or agreed, but their steps toward union and agreement in the last ten years have been most encouraging. They welcomed a gospel of fight and self-assertion.

## Southern California

Los Angeles was wonderful. The air was scented with orange blossoms and the beautiful homes lay low crouching on the earth as though they loved its scents and flowers. Nowhere in the United States is the Negro so well and beautifully housed, nor the average of efficiency and intelligence in the colored population so high. Here is an aggressive, hopeful group --- with some wealth, large industrial opportunity and a buoyant spirit.

Down at San Diego, with its bold and beautiful coast on the great Pacific, is a smaller group, but kindly and thrifty, with pushing leaders.

## The Golden Gate

The shadow of a great fear broods over San Francisco. They have not forgotten the earthquake, and the stranger realizes what it was by the awe in their tones., One misses here the buoyancy and aggressiveness of Southern California and yet the fifty-eight leaders who met me at dinner were a fine group of men, and they expect the colored world to greet them in 1915 at the exposition.

This group stands closer to the progressive whites than many others and has a chance to share in the great movements of uplift.

At Sacramento I did not speak, but a little group made my hours of waiting-pleasant --- an unassuming group with, pleasant manners and warm hearts. I shall not forget them.

## The Northwest

Up then I rushed through a rich, green valley and then through high, full-bosomed hills --- through that contrast and astonishment which is California.

Portland is the older Northwest --- staid and quiet, with a certain strength and bigness. The audience was small and the people were not sure of my message and purpose; but they themselves were awakening and they showed new homes and enterprises with pardonable pride.

Tacoma will always seem to me like a place of home coming. I have seldom come to a strange city with so intimate an understanding and sense of fellowship. The audience was white and black and sympathetically blended. The mayor came and spoke and ate and an old Harvard schoolmate introduced me. They gave me a loving cup and it did not seem inappropriate, so that I went away thinking not so much of a separate striving group as of a body of good friends with scant color line.

Then, as I have said, the wonderful Western pilgrimage was crowned at Seattle. The magic city of 300,000 lies on its hills above silvery waters, dream-beautiful and all but uncanny in its unexpectedness. The group of men who welcomed me were unusual in vigor and individuality. There was the lawyer who thoughtfully engineered it all; the young doctor with his cheery face; the droll politician with his reminiscences and strong opinions; the merchant from up country and his little daughter whose beautiful face of the long years ago I remembered suddenly amid the cheer of her perfect little home. There was the caterer, and the minister --- it was a fine group. I have seldom seen its equal.

For one day I turned my back on the perfect memory of this golden journey and sailed out across the seas and thanked God for this the kindliest race on His green earth, for whom I had the privilege of working and to whom I had the pride of belonging.

## Texas

Then I plunged into Texas. One day the white, drifted snows of Montana and then, in less than a week, the sound of the reaper in the golden grain of the Red River valley!

One shivers at the "Jim Crow" cars of Texas. After the luxury of the West and the public courtesy and hospitality, the dirt and impudence of a land where to travel at all meant twelve to twenty-four hours in the most primitive accommodations, was an awful change. For twenty-four hours on one journey I was able to purchase only two musty ham sandwiches to eat, and I sat up three nights in succession to keep engagements.

But what was lacking in public and white courtesy was more than compensated in private and Negro hospitality and appreciation.

At Dallas was one of the strongest, truest religious leaders I have met. At Austin were growing colleges and an audience gathered from thirty miles around. At Marshall was a group of fine men and women, and it all came to climax at Fort Worth.

"Are you going to Fort Worth" everybody asked, knowing of the recent riot. I went. I spoke to 400 Negroes and a handful of leading whites, and I spoke the clear, plain truth as I conceive it. It was received without dissent or protest and its reception gave me deepest hope and satisfaction.

Atlanta is another story; so here let me end and, in ending, let me thank those who welcomed me, who paid my fees willingly and promptly, who were eager to listen to the message which I brought, not because it was wholly to their liking, but because it was sincere.

All this by way of preface. In later numbers of <span class="small-caps">The Crisis</span> I shall take up these groups and cities in greater detail and tell of their meaning and promise.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Westward Ho (1934)](/Volumes/41/05/westward_ho.html)
* [The South (1917)](/Volumes/13/06/south.html)
* [Hail Columbia (1913)](/Volumes/05/06/hail_columbia.html)
* [Forward (1920)](/Volumes/20/05/forward.html)
* [A Crusade (1914)](/Volumes/07/05/crusades.html)

<!-- Similar articles end here -->