
---
title: 'The Newest South'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 3
  page: 130
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


For the first time in history, Southern white men and Southern black men have met under Southern white auspices and frankly discussed the race problems of the South before an audience of both races. At the Southern Sociological Congress the professional Negro lover was absent, and the white demagogue was silent. There was scarcely a word uttered which <span class="small-caps">The Crisis</span> does not cordially endorse.

It was a splendid occasion. It was epoch making, and men like Dillard, Hunley, Branson Morse, Hammond and Scroggs are the real leaders of the newest South.

But the old South is not dead. The Atlanta *Constitution* refused to report the congress. Hoke Smith's *Journal* refused to report the congress and Hearst's *Georgian*, under the disreputable John Temple Graves, did its best to foment lynching a black man since proven innocent, filling its columns with venom and lies and printing scarcely a word concerning the congress. The Bourbon South dies hard, but its doom is written in the stars.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Inter-Racial Comity (1922)](/Volumes/22/01/inter-racial_comity.html)
* [The Newer South (1926)](/Volumes/31/04/newer_south.html)
* [The Macon Telegraph (1920)](/Volumes/19/03/macon_telegraph.html)
* [Remember (1920)](/Volumes/19/06/remember.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)

<!-- Similar articles end here -->