
---
title: 'The Simple Way'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 1
  page: 337-338
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Some  ways of life are so simple. There was, for instance, a few years
ago, a solution of the Negro problem so ridiculously simple that those
who did not receive it as gospel were hooted if not stoned. The gist
was this:

- The Negro must work out his own salvation.
- The Negro must make himself useful to his neighbors.
- The Negro must not complain.
- Duties must be taught Negroes --- never mind their rights.
- Negroes must let politics alone.
- Money talks --- let the Negro get a \$5,000 brick house and his individual
problem is solved.
- Etc., etc.

All this the Negro has done. He has striven to solve his problems
unaided. He is so useful to his neighbors that the problem of to-morrow
will be the Southern millionaire waxed fat on the starvation wages of
black peons.

The mass of Negroes has been so ground down and oppressed that they do
not know what complaint is. If they did, segregation, the "Jim Crow" car
and disfranchisement would disappear to-morrow. We have shivered in the
storm like dumb driven cattle and forgotten our rights before we learned
them. We have "let politics alone" so effectually that we practically
have no voice in our own government, and we have accumulated brick
houses so fast that from Boston to Galveston white nerves are being
strained to drive us out of them.

We are therefore listening to those eminent and distinguished solvers of
the Negro problem, white and black, who, with hat in hand, have in the last twenty years been lulling this nation to sleep and also feathering their own nests; we are listening for further advice and direction along the simple way.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Socialism and the Negro (1921)](/Volumes/22/06/socialism_and_the_negro.html)
* [The Immediate Program of the  American Negro (1915)](/Volumes/09/06/immediate_program.html)
* [Votes (1919)](/Volumes/19/02/votes.html)
* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)
* [Counsels of Despair (1934)](/Volumes/41/06/counsels_of_despair.html)

<!-- Similar articles end here -->