
---
title: 'Listen, Japan and China'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 1
  page: 20
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Colossi of Asia and leaders of all colored mankind: for God's sake stop fighting and get together. Compose your quarrels on any reasonable basis. Unite in self-defense and assume that leadership of distracted mankind to which your four hundred millions of people entitle you.

Listen to a word from twelve little black millions who live in the midst of western culture and know it: the intervention of the League of Nations bodes ill for you and all colored folk. There are philanthropists and reformers in Europe and America genuinely interested in all mankind. But they do not rule, neither in England nor France, not in Germany nor in America. The real rulers of the world today, who stand back of Stimson, Macdonald and Herriot, are blood-sucking, imperial tyrants who see only one thing in the quarrel of China and Japan and that is a chance to crush and exploit both. Nothing has given them more ghoulish glee than the blood and smoke of Shanghai and Manchuria or led them to rub hands with more solemn unction and practised hypocrisy.

Unmask them, Asia; tear apart their double faces and double tongues and unite in peace. Remember Japan, that white America despises and fears you. Remember China, that England covets your land and labor. Unite! Beckon to the three hundred million Indians; drive Europe out of Asia and let her get her own raped and distracted house in order. Let the yellow and brown race, nine hundred million strong take their rightful leadership of mankind. Let the young Chinese and Japanese students and merchants of America and Europe cease debate and recrimination while gleeful whites egg them on. Get together and wire word to Asia. Get together China and Japan, cease quarrelling and fighting! Arise and lead! The world needs Asia.

 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Close Ranks (1918)](/Volumes/16/03/close_ranks.html)
* [N.A.A.C.P. (1910)](/Volumes/01/02/NAACP.html)
* [Just Like---Folks (1920)](/Volumes/19/05/just_like_folks.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [India (1930)](/Volumes/37/08/india.html)

<!-- Similar articles end here -->