
---
title: 'Toward a New Racial Philosophy'
author: Du Bois, W.E.B.
date: Jan. 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 1
  page: 20-22
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


A college graduate came to me yesterday and asked: "What has the N.A.A.C.P. published concerning the present problems of the Negro, and especially of young Negroes just out of college?"

I started to answer with stereotyped remarks; and then I said suddenly, "Nothing."

The N.A.A.C.P., beginning nearly a quarter of a century ago, formulated on the basis of the problems which then faced Negroes, a clear-cut and definite program. This program we have followed ever since with unusual success for it has expressed during these years the aspirations and lines of effort among 12 millions and their friends.

Today the situation has changed enormously in its trend, objects and details, and there is both need and widespread demand for a re-examination of what is called the Negro problem from the point of view of the middle of the 20th Century. <span class = "small-caps">The Crisis</span> realizes this and it proposes during 1933 to discuss the present Negro problems from 12 points of view. Tentatively, these points seem to us now to be something as follows, although we may change many of them:

1. *Birth*. The physical survival of the Negro in America is discussed in this number.

2. *Health*. In February, we shall ask: How can the infant mortality, the great loss from sickness and the general death rate among Negroes, be lowered? What is the duty of colored physicians toward  Negro health? What is the extent of available hospitalization? How can we extend the life term and meet such enemies of our race as tuberculosis, pneumonia, syphilis and cancer.
    <br/><br/>
    Later, we shall treat our problems in something like the following order:
    <br/><br/>

3. *The Home*. Should a Negro family live in the city or in the country, in the North or in the South, in a single house or in an apartment? And on what facts should an individual family base its decision? How can housework be reduced and systematized? Must paid household help be an ideal? Should Negroes seek to live in their own neighborhoods or in white neighborhoods?

4. *Occupations*. What kinds of work do Negroes want to do and what kind can they do and what kinds are they allowed to do? How far shall they be farmers, artisans, artists, professional men, merchants or financiers? What is their relation to the great economic and industrial changes going on now in the world of work? How far are they being displaced by machines and technique and by new organizations of capital? Can they achieve a place of power and efficiency in the present oligarchy of white capital or in the present labor union or in any future industrial democracy?

5. *Education*. Should a colored child be sent to a white school or to a colored school? Should it be educated in the North or South or even abroad? What should be the kind and aim and length of its education? Should the boy or girl go to college? Should they go to technical school? Should they go to professional school? Should they be apprenticed to manual work? Should they depend for their education upon experience? How far is their education dependent upon contact with the white group and its larger opportunities? How shall the cost of education be met?

6. *Income*. What should be the ideal and standards of living among colored people? How much income must the average colored family have and how should it be spent? How early can our young people get married? What things must they regard as luxuries and beyond them and what as necessities? Shall we aim to be rich or make poverty an ideal?

7. *Discrimination*. Accepting race and color discrimination as a fact which despite all effort's bound to last in some form at least through this generation, if not longer, what shall be our general attitude toward it? How can we avoid in its face an inferiority complex? How far must we be belligerent or acquiescent? Can we meet discrimination by ignoring it or by fighting it? When shall we fight and how shall we fight, and what is the cost of effective fighting? What types of organized effort are needed in this fighting? How much of co-operation with the whites must be sought or accepted? How far must we be willing recipients of white co-operation, philanthropy and charity? How can we escape discrimination by emigration to other states, countries or continents?

 8. *Government and Law*. How far must we be obedient to government and law when they are unfair to us? Can we adopt an attitude of defiance? How can we change our legal status or reform evil administration? Is revolution by force advisable, possible or probable? Can we use our right to vote, curtailed as it is, for our emancipation and change of status? Should we vote for the Republican Party or the Democratic Party; or for Socialists or Communists? Or should we adopt a method of independent opportunism in our voting? In states and cases where we are disfranchised, what shall we do about it? Is it worth while to register, even though we cannot vote or cannot vote effectively? Should we join the Democratic White Primary in the South? Should we in our voting keep our racial needs and demands in mind, or should we have an eye upon the good of the majority of the nation? And what shall we do in case these two ideals clash? How far are we criminal and antisocial? What causes and what can prevent crime? How are our criminals treated?

9. *Race Pride*. How far shall American Negroes remember and preserve their history, keep track of their ancestry, build up a racial literature and a group patriotism? What does loyalty to the race mean? How far shall we have distinctively race organizations, and how far shall we seek to join organizations regardless of race? If we do have organizations, what sorts are needed for the various ends we have in view? How far do present organizations fill our need or how shall they be changed and what new ones must come? Shall we imitate and duplicate, on our side of the color line, the organizations that white folk have? Especially, of what use are secret fraternities and how can their functioning be made to help our general uplift? What is our relation to Africa, to the West Indies, to Asia, to the colored world in general? Is it profitable or advisable consciously to build up by race pride a nation within a nation, or races within the world?

10. *Religion*. We are by tradition a religious people and the "old-time religion" still has a strong hold on our masses. The present Negro church more nearly represents the mass of people than any other organization and its ministers are its spokesmen. Nevertheless, the number of colored people who do not go to church is large and growing. Is this right, and if not, what is the remedy? What should be the function of the Negro church? How far should there be churches divided along the color line? What is the present status of creeds? How far do we dare disturb simple religious faith, "evangelical" dogma and ordinary religious superstition? Should a man join a church and work with it if he does not believe completely in its dogma? Can the Negro church be made a center and unit of racial and cultural and social development? Will Creed and Culture, Reason and Faith, Science and Superstition clash as in other groups and ages? What should be the attitude of the Negro church toward white churches? How far should they co-operate in missions and philanthropy? How far is the white church, with its greater wealth and experience, pauperizing certain colored churches? What is the remedy? Will Christianity abolish or emphasize the Color Line? How can we, with or without religion, encourage courtesy, honor, unselfishness, sacrifice, self restraint, the ideals of the higher spiritual life, the recognition of beauty in Art and deed?

 11. *Social Contacts*. Is the method of advance among colored people today a building up of social classes so that the educated, the rich, the well-to-do and the moral can separate themselves from the poor, the ignorant and the criminal? Can this class-building technique of civilization be ignored in our case and something better substituted? How far must colored people try to accumulate wealth and become the employers of other Negroes and even of whites? Must we have a bourgeoisie for defense in a bourgeois world? What should be our social standards in marriage? Should we encourage our children to inter-marry with white folk, or at any rate, to increase the social contacts between colored and white people with the ultimate ideal of marriage? And if not, where can the line be drawn? In the absence of social contact with more favored persons and races, is it possible for culture among us to grow or to grow as fast? Should we demand and practice social equality? Should we regard the development of lower masses among our people as inevitable, and if so, what should be our attitude toward these masses? What should be our attitude toward social questions beyond our own racial orders, toward world problems of peace and war, the labor movement, the status of women, education, health, social and economic reform?

12. *Recreation*. How can we get the relaxation of play and recreation without having it spoiled by discrimination along the color line? Should we travel, and if we travel, should we seek or avoid white people? Where can we spend our vacations? Where can we bathe in the ocean unmolested and not insulted? What should be our attitude toward discrimination in transport, railroad trains, buses and hotels? Where shall we be willing to sit in theatres and at concerts? If we seek recreation only in those places where there is no discrimination, will that help uplift by increasing our pleasure or will it encourage the growth of further discrimination?

The above is a tentative outline of 12 sets of problems. Further reflection will doubtless change and add to them. There are doubtless important omissions. <span class = "small-caps">The Crisis</span> would welcome from readers suggestions as to these heads.

In the meantime, it is our present plan to publish a discussion of one of these subjects in each of the next 12 numbers <span class = "small-caps">The Crisis</span>, which will exhibit different points of view concerning the main problems suggested. We would be glad to have contributions or suggestions as to persons who might contribute to these symposiums. Of necessity, the contributions must be terse and to the point, and, of course, we cannot publish all. Beside the editorial statement of the problem, and papers discussing two or more sides of the problem, we are going to try to get hold of 12 pieces of fiction which will illustrate the problems humanly. We admit it is going to be a hard thing to do this.

What we want is suggested by the story this month---"The Three Mosquitoes." Do you like it? Is it worth while? Such stories must be short,---not more than two pages of <span class = "small-caps">The Crisis</span>,---and they must illustrate the difficulties and contradictions of each of these 12 suggested matters of thought. They must not be "defeatist;" we want them to be artistic; we want them true: but we do not propose to have every story end in a lynching or a suicide, for the simple reason that we do not believe that death is the necessary answer to any of these situations.

Finally, we welcome from everybody, terse, definite and pointed opinions, which we shall try to reflect and quote.

 