
---
title: 'The Census'
author: Du Bois, W.E.B.
date: May 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 1
  page: 24
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



It will be interesting to hear the American chorus when the population figures of the census of 1910 are published. They will show naturally a large increase of whites ard a small increase of colored people. Then we will have a long howl of glee from the Negro baiters, a sigh of delicious content from the North and a puzzled silence from black folk. And why?

The South will say:

> The decreased rate of increase of Negroes during the last decade was lower than ever before. It grows progressively lower. Therefore the Negro is dying out.

The North will say:

> It is providential---the physique of inferior races, etc., etc.

Yet what are the facts? They are as plain as day:

The Negro population is increasing as fast as any normal modern folk. The increase of the whites in the United States is not normal. Their birth rate in every normal white country is decreasing far more rapidly
than that of the Negro. The white American situation is abnormal through an immense immigration. Even the so-called "native whites of native parents" are largely those whose grandparents migrated and those who forgot about the nativity of their parents. The mass of Southern native whites show all the marks of carelessness due to sudden economic affluence. From an economic position below slaves they have in a single generation been raised almost to the modern wage level. The result is big families.

Now, to compare this temporary abnormal increase of whites in America with the more normal increase of colored people is silly. The facts concerning colored folk are well known:

They have practically no immigration.

They are under severe economic repression.

They are under a mental and moral strain such as no group outside the Jews and Finns in Russia are to-day suffering.

Despite this they are increasing as fast as the English, nearly as fast as the Germans and far faster than the French. They are without reasonable doubt increasing much faster than the original New England stock or the Quaker stock or any of the earlier settlers of America.

With this large increase is going an economic betterment which is astounding when we remember the handicap, and is clearly shown in the agricultural and property statistics. And, finally, when all is said, remember that to-day there are ONE MILLION more colored people in America than there were in 1900.

Remember that, allowing for every probable decrease in birth rate in the future, Americans will live to see 15,000,000 of colored people by 1950, and if the present tendencies persist these millions, because of their wealth and intelligence, will be less easily insulted, less easily scared into silence, less easily imposed upon by their own demagogues and, as Mr. Dooley has it, less "aisily lynched."

