
---
title: 'Christianity Rampant'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 1
  page: 25-26
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


How long is practical Christianity going to be able to survive its own hypocrisy? How long is the world going to be able to profess a system of unselfish ethics, of lofty ideal, which it does not pretend to practice? If the augurs of Rome laughed at each other as they passed, how long at the present rate will Christian ministers be able to keep straight faces?

At least we trust for the good of the world that the Christian missionaries who go to the Mohammedan lands in the future will go to learn rather than to teach. What will they say to the latest exhibition of pure Christian brigandage on a weaker people? Why is Europe in general and Italy in particular falling afoul of
Turkey? Is it because of Turkish misrule? No, Europe has been able to stand that a thousand years. No, but as soon as the revolution and uplift came---as soon as the young Turks and the whole Mohammedan world showed signs of regeneration---then it was that the professed followers of the meek and lowly Jesus became shameless highwaymen. Austria seized one juicy bit; Montenegro put her hand on another, but found it too hot. Whereupon her ruler's son-in-law, King of Italy, saw a divine mission. He saw a chance to distract Italians from their own parlous condition by a debauch of conquest. The Jingo yelled, the soldier burnished his tinsel, and the Church, which no Italian blandishments of peace had been able to subdue, hastened to put its divine blessing on murder. There have been some pretty shameless wars in modern history, but Italy's conquest of Tripoli tops them all. Civilization will yet pay for this murderous debauch, and Christianity hang her head in shame.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Church (1916)](/Volumes/11/06/church.html)
* [The Church and Religion (1933)](/Volumes/40/10/church_and_religion.html)
* [The Battle of Europe (1916)](/Volumes/12/05/battle_of_eruope.html)
* [Italy and Abyssinia (1926)](/Volumes/32/02/italy_and_abyssinia.html)
* [Liberia (1927)](/Volumes/34/01/liberia.html)

<!-- Similar articles end here -->