
---
title: '''Ezekielism'''
author: Du Bois, W.E.B.
date: May 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 1
  page: 25
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



We offer no apology for coining a new long needed English word. We simply pause to acknowledge our indebtedness to Miss Pratt and Miss Ovington and to recommend our readers to know the former's stories and to commit to memory the last chapter of "Half-a-Man."

"Ezekielism" is the assumption that the faults of any particular individual are the innate faults of his group and that any virtues he may possess are peculiar to him and quite exceptional so far as his group are concerned.

"Racial" faults and "exceptional" virtues are the rock foundation of "Ezekielism." The person who proposes to "Ezekielize" begins invariably with a phrase. "Now *I* have *no* prejudice." By this phrase ye shall know them---"*I* have *no* prejudice---BUT." That is the main statement and the ending is immaterial. It may be any one of these or a dozen others:

* I know a Negro who steals.
* I know a Jew who cheats.
* I know an Italian "black hander."
* I know a woman who is frivolous. 
* I know a white man who led a mob. 

After that persons afflicted with this form of hysteria proceed to "Ezekielize" and, lo! we learn that:

* Negroes steal.
* Jews cheat.
* Italians murder.
* Irishmen drink.
* Women are silly.
* White folk lynch.

You may expostulate: "But I know one Negro------"

"Exception," whispers your friend and the "Ezekielism" is complete.

Now, such travesty on logic cannot be used on all races with impunity, because some races have sense enough to fight back. When a New York chief of police ventured to charge Jews with a large share of the crime of the city he lost his job. When Louisiana took to lynching Italians the United States Government paid a tidy sum; Boston and New York used to find no words too contemptuous for Irishmen, but the Lord or somebody else has touched their hearts recently; and so forth.

To-day it is only the Negro who is the unquestionable victim of "Ezekielism." I approach a school principal with my child, along with a dozen other races. To the Italian, the Jew, the Irishman, the Yankee, he says: "How is Mabel? What of Bridget's arithmetic? Is Miriam strong? Can Assunta spell?" But, looking my child over, he says, reflectively: "Negroes have never done well in this school." I do not remind him that the school has had but two solitary little black waifs in twenty years. I do not lose my temper, for victims of "Ezekielism" are not responsible and one must allow for them. So I sigh and remark: "Indeed!"

Or I present to a philanthropist the case of a decent woman who is refused food at Shanley's or Childs' or some other restaurant. He looks at me disapprovingly and says, shaking a fat finger:

"I've been trying to get a cook------"

Then I know that he has a case of "Ezekielism" and I go.

