
---
title: 'Negro Art'
author: Du Bois, W.E.B.
date: Jun. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 2
  page: 55-56
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Negro art is today plowing a difficult row, chiefly because we shrink at the portrayal of 
the truth about ourselves. We are so used to seeing the truth distorted to our despite, that whenever we are portrayed on canvas, in story or on the stage, as simply human with human frailties, we rebel. We want everything that is said about us to tell of the best and highest and noblest in us. We insist that our Art and Propaganda be one. 

This is wrong and in the end it is harmful. We have a right, in our effort to get just treatment, to insist that we produce something of the best in human character and that it is unfair to judge us by our criminals and prostitutes. This is justifiable propaganda. 

On the other hand we face the Truth of Art. We have criminals and prostitutes, ignorant and debased elements just as all folk have. When the artist paints us he has a right to paint us whole and not ignore everything which is not as perfect as we would wish it to be. The black Shakespeare must portray his black Iagos as well as his white Othellos. 

We shrink from this. We fear that evil in us will be called racial, while in others it is viewed as individual. We fear that our shortcomings are not merely human but foreshadowings and threatenings of disaster and failure. The more highly trained we become the less can we laugh at Negro comedy---we will have it all tragedy and the triumph of dark Right over pale Villainy. 

The results are not merely negative---they are positively bad. With a vast wealth of human material about us, our own writers and artists fear to paint the truth lest they criticize their own and be in turn criticized for it. They fail to see the Eternal Beauty that shines through all Truth, and try to portray a world of stilted artificial black folk such as never were on land or sea. 

Thus the white artist looking in on the colored world, if he be wise and discerning, may often see the beauty, tragedy and comedy more truly than we dare. Of course if he be simply a shyster like Tom Dixon, he will see only exaggerated evil, and fail as utterly in the other extreme as we in curs. But if, like Sheldon, he writes a fine true work of art like "The Nigger"; or like Ridgely Torrence, a beautiful comedy like "The Rider of Dreams"; or like Eugene O'Neill, a splendid tragedy like "The Emperor Jones"---he finds to his own consternation the Negroes and even educated Negroes, shrinking or openly condemning. 

Sheldon's play has repeatedly been driven from the stage by ill-advised Negroes who objected to its name; Torrence's plays were received by educated blacks with no great enthusiasm; and only yesterday a protest of colored folk in a western city declared that 

> 'The Emperor Jones' is the kind of play that should never be staged under any circumstances, regardless of theories, because it portrays the worst traits of the bad element of both races.

No more complete misunderstanding of this play or of the aim of Art could well be written, although the editors of the *Century* and *Current Opinion* showed almost equal obtuseness. 

Nonsense. We stand today secure enough in our accomplishment and self-confidence to lend the whole stern human truth about ourselves to the transforming hand and seeing eye of the Artist, white and black, and Sheldon, Torrence and O'Neill are our great benefactors---forerunners of artists who will yet arise in Ethiopia of the Outstretched Arm.

