
---
title: 'Mexico'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 8
  issue: 2
  page: 79
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There is, without doubt, a deep hesitancy throughout this nation in the
matter of war with Mexico. This was not true when we gaily Cuba and
benevolently assimilated the Philippines. What did we care for race problems then? We had our problems settled easily and
fluently. All "niggers," "dagoes," "chinks," "Japs" and "mongrels" were
inferiors and consequently easy to whip and keep whipped. We therefore
envisaged millions of additional working slaves to add to the black
peons of our own South and swell the comfortable stream of dividends
flowing into white pockets.

Our plan worked. We have Cuba by the industrial throat and the
Philippines on its knees, albeit squirming. Why not Mexico with its
millions of brown peons? Because the fact is that we, with all our
success, are not only uncomfortable,,but we scent danger. Are there
inferior human beings or only inferior food and opportunity? Can the
white world always hold the black world by the throat and keep it to
work? What are these darker, desperate things thinking of and, thinking,
what will they do when thought comes to action?

And, finally, how much civilization can we teach the world anyway? Are
we civilized? We may blunder into murder and shame and call it a Mexican
war. But it will not be war. It will be crime.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Violations of Property Rights (1911)](/Volumes/02/01/violations.html)
* [Pullman Porters (1926)](/Volumes/31/03/pullman_porters.html)
* [Brazil (1914)](/Volumes/07/06/brazil.html)
* [To the Rescue (1916)](/Volumes/12/01/rescue.html)
* [Violence (1934)](/Volumes/41/05/violence.html)

<!-- Similar articles end here -->