
---
title: 'Senators'' Records'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 8
  issue: 2
  page: 77-78
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



During the debate in the Senate of the United States on the joint
resolution proposing to amend the Constitution by extending the suffrage
to women, the race question obtruded itself and, as a result, many
Senators, by their speeches and votes, put themselves on record. This
record will be of interest to Negro voters throughout the country.

Two amendments to the resolution were offered, both intended to repeal
the Fifteenth Amendment. The first, proposed by Vardaman, of
Mississippi, was to insert after the word "sex" the following:

> But in all other respects the right of citizens to vote shall be
controlled by the State wherein they reside.

The second, offered by Williams, of Mississippi, proposed to amend by
inserting before the word "citizens" the word "white," so that, as
amended, the section would read:

> <span style="font-variant:small-caps;">Section 1. </span> The right of white citizens of the United States to vote
shall not be denied or abridged by the United States or by any State on
account of sex.

Of the Senators from the South the following only signified their
opposition to the repeal of the Fifteenth Amendment: Bradley, of
Kentucky; Du Pont, of Delaware; Chilton, of West Virginia; Fall, of New
Mexico; Catron, of New Mexico; Ashhurst, of Arizona. Thornton, of
Louisiana, opposed the Vardanian amendment, but expressly stated that he
was ready at any time to support a straight resolution repealing the
Fifteenth Amendment. Saulsbury, of Delaware, did not vote, but was
announced as favoring both amendments. Reed, of Missouri, opposed the
Williams amendment, but he had already voted for the Vardanian
amendment. Bankhead, Clark, of Arkansas, Robinson, Culberson, Fletcher,
Goff, Simmons, Smith, of Maryland, Smith, of Arizona, and Stone, of
Missouri, did not vote and were not announced as on either side.

Of the Northern Senators, Meyers, of Montana, voted for both amendments.
Newlands and Pittman, of Nevada, voted for the Williams amendment.

During the debate Pittman, of Nevada, stated that he opposed the
suffrage amendment because he realized that its passage would embarrass
the South in its treatment of the Negro problem, and because he did not
care to endanger the chances of future anti-Japanese legislation by
alienating the South on the Negro question. His colleague. Newlands, in
a speech in support of the woman's suffrage amendment, took occasion to
state his belief in Negro disfranchisement and white supremacy. Borah,
of Idaho, in a long speech and in numerous shorter ones, opposed the
suffrage amendment on the ground that it would not be enforced in the South as to colored
women and that he would not be a party to writing into the Constitution
another provision which he knew would not be enforced. Bryan, of
Florida, and the two Mississippi Senators supported the proposed repeal
of the Fifteenth Amendment by their speeches. This proposition was
opposed by Bristow, Townsend, Gallinger and Clapp.

Of the Senators who by their stand on this question showed themselves as
opposed to the interests of the colored people, only Newlands, of
Nevada, comes up for re-election this year. Unfortunately, the Negro
vote in his State is of slight importance. It should, however, be cast
solidly against the re-election of Senator Newlands. Of Senators who
have on this and other matters shown that they have the interests of the
colored people at heart, the following come up for re-election: Bradley,
of Kentucky; Bristow, of Kansas: Gallinger, of New Hampshire; Jones, of
Washington; Sherman, of Illinois.

In the recent fight for the Jones amendment to the Smith-Lever bill the
issue was not clearly drawn, because the introduction of the Shafrotli
amendment caused persons who otherwise would have voted for the Jones
amendment to oppose it. However, one Republican Senator, Brady, of Ohio,
intimated throughout his debate his opposition. He also comes up for re-
election this fall and should be opposed by the colored voters.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The White Primary (1911)](/Volumes/01/05/white_primary.html)
* [Get Ready (1920)](/Volumes/20/01/get_ready.html)
* [The Truth (1911)](/Volumes/01/03/truth.html)
* [Southern Representatives (1920)](/Volumes/19/06/southern_representatives.html)
* [Sex Equality (1920)](/Volumes/19/03/sex_equality.html)

<!-- Similar articles end here -->