
---
title: 'The National Interracial Conference'
author: Du Bois, W.E.B.
date: Feb. 1929
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 36
  issue: 2
  page: 47, 69-70
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



For a long time national plans have been developing for a National Interracial Conference to meet at Washington, D. C. Sixteen national organizations combined to sponsor this meeting. These organizations were as follows: 

- American Friends Service Committee, Interracial Section.
- American Social Hygiene Association. 
- Commission on Interracial Cooperation. 
- Council of Women for Home Missions.
- Federal Council of Churches, Commission on Race Relations. 
- Fellowship of Reconciliation. 
- Home Mission Council. 
- The Inquiry. 
- National Association for the Advancement of Colored People. 
- National Board Y. W. C. A. 
- National Catholic Welfare Conference. 
- National Council Y. M. C. A. 
- National Federation of Settlements. 
- National Urban League. 
- Phelps Stokes Fund. 
- Protestant Episcopal Church, Department of Christian Social Service. 

In the Conference meeting December 16th to 19th, there were actually present 151 delegates, representing: Organizations, 37; Colleges, 27; Churches, 26; United States Government and State Departments, 17; Endowed Funds, 9; Periodicals, 5; Social Settlements, 4; Labor Organizations, 4; and 22 Members at Large. 

The Committee held morning, afternoon and evening sessions, with the following presiding officers: Mordecai W. Johnson of Howard University; Robert R. Moton, Tuskegee Institute; Mary Van Kleeck, of the Russell Sage Foundation; Dr. George E. Haynes of the Federation of Churches was Executive Secretary. The day sessions were held in the auditorium of the Department of the Interior, and the evening sessions in the auditorium of the Medical School of Howard University. 

Before these meetings the Research Committee, under Charles S. Johnson, of Fisk University laid a digest of 250 typewritten pages. The purpose of it was "to construct a reasonably faithful contemporary picture of Negro life and the status of race relations as revealed in recent social studies and in official statistics." This tremendous piece of compilation was done with unusual completeness and fairness. With this data before them it was the task of the delegates to seek an answer to three questions: 

1. In the light of social research what do we now know about Negro life and race relations as affecting both the white and colored races in the United States? 

2. What significance has this knowledge for the programs of social organizations whose purpose it is to improve these conditions? 

3. What gaps in knowledge are revealed, calling for further study by universities and research organizations? 

 
The subjects taken up were as follows: 

Monday morning, December 17th, "Health," with Louis I. Dublin, Chief Statistician of the Metropolitan Life Insurance Company, and Dr. A. B. Jackson, of Howard University, as speakers. Monday afternoon, "Education," with W. A. Robinson, former Supervisor of Negro High Schools of North Carolina, and Professor Mabel Carney of Columbia University, and Principal James E. Gregg of Hampton, as speakers. On Tuesday morning, "Industry and Agriculture" were discussed by Monroe N. Work of Tuskegee Institute and Niles Carpenter, of the University of Buffalo; on Tuesday afternoon, "Recreation and Housing', by Forrester B. Washington of Atlanta, Ernest T. Attwell of New York, T. J. Woofter of the University of North Carolina, and Roscoe C. Bruce of New York; Wednesday morning, "Law Observance and Administration" by Thorsten Sellin of the University of Pennsylvania, and Lawrence Oxley of North Carolina; Wednesday afternoon, "Citizenship and Race Relations', by W. E. B. DuBois of New York and Herbert A. Miller of Ohio State University. 

These sessions were attended only by delegates. Public sessions were held Monday, Tuesday and Wednesday evening, at which general summaries of the discussions were given. On Monday evening, the speakers were F.O. Nichols, Raymond Pearl of Johns Hopkins University, and the Presidents of Fisk and Morehouse. Tuesday evening, the speakers were Charles Wesley of Howard, Mary E. McDowell of Chicago, R.S. Wallace, and John P. Frey of the American Federation of Labor. The speakers for the final evening were James Weldon Johnson, Clark Foreman, Alain Locke, Julius Rosenwald, John M. Glenn, Edwin R. Embree, Mordecai W. Johnson, R.R. Moton, Mary Van Kleeck and Anson Phelps Stokes. 

It goes without saying that with so ambitious and full a program the Conference left much to be desired. The discussions fell far below possibilities, partly because of lack of time and partly because of a certain timidity and fear of free expression. "There was a good deal of unnecessary repetition: the speakers repeated what the Research Committee had reported, and other speakers summed up what the main speakers had said. The net result often was almost like spoon feeding of children lest they mentally overeat. 

Nevertheless, never before in the history of the United States have so many organizations, representing so diverse points of view and methods of approach, come together in a spirit of tolerance and inquiry to seek out the facts which underlie the relations of races in the United States. 

Of course, conclusions could not be reached; nor were they indeed desired. The object of the meetings was enlightenment, and none could possibly have left without a feeling that he had learned something. In the matter of health, there is no doubt, but what great strides in our knowledge of the condition of the Negro has taken place in the last twenty years. No scientist today doubts but what the American Negro is going to survive and is going to achieve a sound body and has a normal brain. The great need now is physicians and hospitals. 

The advance in *Education* has set to rest all questions of the ability of Negroes to absorb and use modern education. There is still a pressing demand for the eradication of Negro illiteracy; the betterment of Common and High Schools; and the endowment of good colleges. 

*Industry and Agriculture* show the revolution due to the migration of Negroes from South to North, and their entrance into industry as common and semi-skilled laborers. The consequent problems of *Housing and Recreation* are severe and pressing. 

*Crime* was shown not to be racial but the result of changing conditions of living; of poverty and of ignorance; and it is by no means certain that the rate of crime among Negroes is even as large as those among whites. 

In *Citizenship and Race Relations* an insistent demand for the suffrage was made. One speaker said in his climax: "I hold this truth to be evident, that a disfranchised working-class in modern industrial civilization is worse than helpless. It is a menace, not simply to itself, but to every other group in the community. It will be diseased; it will be criminal; it will be ignorant; it will be the plaything of mobs, and it will be insulted by caste restrictions." 

The whole bogie of inherent, ineradicable race distinctions was attacked. "Races that try to be exclusive are both the producers and the consumers of each other's goods. The competition of laborers seems immediate and threatening. However, with a rising tide of economic activity, no race is self-sufficient, and the organization of interracial labor will be just as easily demonstrated and just as necessary as is international banking." 

One comes from a meeting of this sort with a distinct feeling that all of the labor and devotion which was put into this ought not to be lost. There is no need for any super-organization. Agreement is not yet wide enough for a movement of this kind; but THE Crisis suggests that the following program be carried out, to obviate, on one hand, such an impossible crowding of problems and spoiling of real conference and discussion as was inevitable at this meeting; and on the other hand, to widen and deepen our knowledge of facts. 

<span style="font-variant:small-caps;">The Crisis</span> proposes that the sponsoring organizations, and any other organizations that may wish to come in, should arrange a comprehensive program; admission should depend upon willingness to inaugurate, with the cooperation and consent of consulting Committee of experts, a long intensive scientific study of some one phase of the Negro problems; and that there be held each year a meeting at which the result of *one* of these lines of study be reported to the public and adequately and thoroughly discussed. The following year another subject should be taken up, etc. At the beginning, of course, subjects would have to be chosen which had less than ten years' investigation, but it would be easy to do this because, for instance, in matters of health, education, industry and agriculture, recreation and housing, there is already a fairly good beginning of material. In 1929 and 1939, for instance, we might have a meeting devoted entirely to health, in which all of the studies made and available, should be presented and discussed. After that the following problems could be put on: 1930 and 1940, Education; 1931 and 1941, Industry and Agriculture; 1932 and 1942, Housing and Recreation; 1933 and 1943, Law Observance and Administration; 1934 and 1944, Citizenship and the Suffrage; 1935 and 1945, Race and Race Relations. With the year 1936, the question of health could again be taken up with seven years of additional study over 1929, and so on through the program. 

At each of the meetings, while the main topic which had received the intensive study for the period, would receive the main part of the attention, one or two sessions might be given to a general survey of all conditions, in which new studies and new occurrences would be partially reported. The annual meetings could be in charge of the organization making the main study, with financial aid for the meeting from all member organizations. 

This was the plan that was conceived at Atlanta University. It could not be carried out there because we had only an annual appropriation of $5,000, which included our salaries and expenses. The scheme, therefore, had to be given up; but this would seem to be an unusually favorable time for redrafting and improving the scheme and starting a study of group development and relations which would be unique in the history of the world. 

