---
title: Inter-Marriage
description: In 1924 W.E.B. Du Bois in The Crisis denounces KKK-backed anti-miscegenation bills, arguing race laws degrade women, marriage, and democracy.
author:
- name:
    given: W.E.B.
    family: Du Bois
date: Apr. 1924
subjects:
- Anti-miscegenation legislation
- Interracial marriage
- White supremacy
- Ku Klux Klan political activity
- Protection of Black women from sexual exploitation
places:
- Ohio
- Iowa
- Michigan
- Mississippi
- Southern United States
organizations:
- Ku Klux Klan
citation:
  type: article-journal
  container-title: The Crisis
  volume: 291
  issue: 6
  page: 251
google-scholar: true
format:
  html:
    toc: false
    appendix-cite-as: display

categories:
  - "Segregation"
---

The Ku Klux Klan has secured the introduction of bills into certain legislatures, including Ohio, Iowa and Michigan, which should be called proposals "to encourage prostitution and degrade women of Negro descent." These bills have secured the backing of Christian ministers, women's clubs and some prominent citizens, because they prevent legal marriage between persons of different "races."

It is astonishing that muddled thinking will lead to such indefensible and disgraceful proposals. There is nothing to prevent today a white man from refusing to marry a colored woman. There is no law compelling a white woman to take a Negro mate. Decent custom in all civilized communities compels the scoundrel who seduces a girl to marry her no matter what race she belongs to. Does decency ask change in such custom? There are laws which say that if white people wish to consort with colored people they must marry. Can civilization demand less?

Must Nordic culture admit that the only way to prevent intermarriage is to make it illegal and if they admit this can they prove it? Mississippi makes inter-racial marriage illegal and Mississippi has 122,000 acknowledged mulattoes. The whole South refuses to black girls any adequate protection against white brutes or gentlemen and yet the South admits to a million and half mulattoes.

If reason and science, social pressure and parental advice cannot keep white and colored folk from inter-marriage, will law do it? Shame on a race and a people that must stoop to such measures in order to maintain their vaunted superiority.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Decency (1912)](/Volumes/04/02/decency.html)
* [Intermarriage (1916)](/Volumes/11/06/intermarriage.html)
* [Intermarriage (1927)](/Volumes/33/03/intermarriage.html)
* [Intermarriage (1913)](/Volumes/05/04/intermarriage.html)
* [Correspondence (1926)](/Volumes/31/05/correspondence.html)

<!-- Similar articles end here -->