
---
title: 'Emancipation'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 5
  issue: 3
  page: 128-129
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Fifty years ago, on the first day of January, 1863, the American people,
by the hand of Abraham Lincoln, took the first formal and legal step to
remove the unsightly shackles of slavery from the footstool of American
liberty. They did not do this deed deliberately and with lofty purpose,
but being forced into a war for the integrity of the Union, they found
themselves compelled in self-defense to destroy the power of the South
by depriving the South of slave labor and drafting slaves into Northern
armies.

Once having realized that Liberty and Slavery were incompatible, the nation yielded, for a moment, leadership to its highest ideals: it gave black men not simply physical freedom, but it attempted to give them political freedom and economic freedom and social freedom. It knew then, as it knows now, that no people can be free unless they have the right to vote, the right to land and capital and the right to choose their friends. To call a man free who has not these rights is to mock him and bewilder him and debase him. This the nation knew, and for a time it tried to be true to its nobler self. But social reform costs money and time, and if it seeks to right in one generation three centuries of unspeakable oppression it faces a task of awful proportions. Facing this task and finding it hard, the nation faltered, quibbled and finally is trying an actual volte-face. It has allowed the right to vote to be taken from one and a half out of two million black voters. It has allowed growing land monopoly and a labor legislation that means peonage, child labor and the defilement of women. And above all it has insisted on such barriers to decent human intercourse and understanding between the races that to-day few white men dare call a Negro friend.

The result of this silly and suicidal policy has been crime, lynching,
mob law, poverty, disease and social unrest. But in spite of this the Negro
has refused to believe that the present hesitation and hypocrisy of
America is final. Buoyed then by an unfaltering faith, he accumulates
property, educates his children, and even enters the world of literature
and art. Indeed, so firm has been his faith that large numbers of
Negroes have even assented to waive all discussion of their rights,
consent to present disfranchisement and do just as far as possible
exactly what America w^r^ants them to do. But even here let there be no
mistake; with Negro agitators and Negro submissionists there is the one
goal: eventual full American citizenship with all rights and
opportunities of citizens. Remove this hope and you weld ten million
men into one unwavering mass who will speak with one voice.

Yet, after fifty years of attempted liberty, the reactionary South and
the acquiescent North come forward with this program:

1. The absolute disfranchisement of all citizens of Negro descent forever.
2. The curtailment and regulation of property rights by segregation.
3. Strictly limited education of Negro children as servants and laborers.
4. The absolute subjection of Negro women by prohibition of legal marriage between races.
5. The eventual driving of the Negro out of the land by disease, starvation of mob violence.

Every single item in this program has powerful and active support in the
halls of legislatures, in the courts of justice, in the editorial rooms
of periodicals, and in the councils of Southern secret societies.

There are many organizations working against this program, but in most
cases the opposition is not vigorous and direct, but apologetic and
explanatory, and based on temporary philanthropic
relief, rather than eternal justice. We have friends of the Negro who
oppose disfranchisement by a program of partial and temporary and
indefinite disfranchisement; who tell the Negro to buy property and
ignore ghetto legislation; who believe in caste education and hotly
accuse others who do not of being ashamed of work; who would preserve
one foolish white woman if it costs the degradation of ten innocent
colored girls, and who would greet the death of every black man in the
world with a sigh of infinite relief.

The National Association for the Advancement of Colored People almost
alone stands for a frank, open, front, forward attack on the reactionary
Southern program. It demands a nation-wide fight for human rights,
regardless of race and color; it calls for real democracy, social and
economic justice, and a respect for women which is not confined to women
of one privileged class.

In this fight we want your help? We need it desperately. The nation
needs it. How in Heaven's name shall Liberty and Justice survive in this
land if we do not oppose this program of slavery and injustice? Abraham
Lincoln began the emancipation of the Negro-American. The National
Association for the Advancement of Colored People proposes to complete
it.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [An Open Letter (1915)](/Volumes/10/03/an_open_letter.html)
* [Blaine of Maine (1932)](/Volumes/39/08/blaine_of_maine.html)
* [Loyalty (1917)](/Volumes/14/01/loyalty.html)
* [Civil Rights (1913)](/Volumes/06/04/civil_rights.html)
* [An Open Letter to Woodrow Wilson (1913)](/Volumes/05/05/open_letter.html)

<!-- Similar articles end here -->