
---
title: 'Our Own Consent'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 5
  issue: 3
  page: 129
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



We should remember that in these days great groups of men are not long oppressed but by their own consent. Oppression costs the oppressor too much if the oppressed stand up and protest. The protest need not be merely physical---the throwing of stones and bullets---if it is mental and spiritual, if it expresses itself in silent, persistent dissatisfaction, the cost to the oppressor is terrific.

This fact we continually forget. We say: the South is in saddle; what can we do against twenty millions? The white oppressor rules; of what avail is agitation against ninety millions?

If you doubt the efficacy of agitation and protest, ask yourself: Why is the reactionary oligarchic South so afraid of even one protesting voice? Why are the Northern doughfaces, their millionaire backers and their allied teachers in Southern schools so panicstricken at one small voice? Why is the American Negro hater always so anxious to affirm that the Negro assents to his chains and insults, or that the "responsible" Negroes assent, or that the only real Negro leader" assents? Is it because they know that when one protesting voice finds its fellows it may find soon ten millions? And when ten million voices are raised to say:

Disfranchisement is undemocratic; "Jim Crow" legislation adds insult to theft; "color discrimination is barbarism—"

When ten million voices say this they will, they must, be heard. And when their cause is once heard, its justice will be evident and its triumph sure. Agitate then, brother; protest, reveal the truth and refuse to be silenced. The most damnable canker at the heart of America is her treatment of colored folk.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Freedom of Speech (1930)](/Volumes/37/08/freedom.html)
* [Thirteen (1918)](/Volumes/15/03/thirteen.html)
* [Forward (1920)](/Volumes/20/05/forward.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)

<!-- Similar articles end here -->