
---
title: 'The Battle of Europe'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 5
  page: 216-217
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The war is still with us, has almost become a commonplace, and yet there is no thinking man who does not send his mind two years back and remember the assurance with which he said in those bewildering, tumultuous days of August, 1914, "This cannot last, we are too civilized." 

Well, civilization has met its Waterloo. We have read of attacks by gas, of raids on non-fortified towns, of Zeppelins dropping bombs on women and children, and the whole campaign of "frightfulness" which left us at first cold and faint and even yet inspires in us a Sick distaste. What good can come out of it all? Much is still on the knees of the gods; but it takes no prophet to presage the advent of many things---notably the greater emancipation of European women, the downfall of monarchies, the gradual but certain dissolution of caste and the advance of a true Socialism. All this and much more. But for the immediate present and especially for us there is coming a gradual and subtle encouragement to strengthen race predilections and revel in them unashamed. 

The civilization by which America insists on measuring us and to which we must conform our natural tastes and inclinations is the daughter of that European civilization which is now rushing furiously to its doom. This civilization with its aeroplanes and submarines, its wireless and its "big business" is no more static than that of those other civilizations in the rarest days of Greece and Rome. Behind all this gloss of culture and wealth and religion has been lurking the world-old lust for bloodshed and power gained at the cost of honor. 

The realization of all this means for us the reassembling of old ideals. Honor which has had no meaning for us in this land of inconstant laws, takes on a new aspect; mediocrity, so long as it does not mean degradation, is sweet; peace---not "at any price,"---is a precious boon; old standards of beauty beckon us again, not the blue-eyed, white-skinned types which are set before us in school and literature but rich, brown and black men and women with glowing dark eyes and crinkling hair. Music has always been ours; but with the disappearance of those *effete* ideals comes the assurance that the plantation song is more in unison with the "harmony of the spheres" than Wagner's greatest triumph. Life, which in this cold Occident stretched in bleak, conventional lines before us, takes on a warm, golden hue that harks back to the heritage of Africa and the tropics. 

Brothers, the war has shown us the cruelty of the civilization of the West. History has taught us the futility of the civilization of the East. Let ours be the civilization of no *man*, but of *all men*. This is the truth that sets us free. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Close Ranks (1918)](/Volumes/16/03/close_ranks.html)
* [Peace (1933)](/Volumes/40/12/peace.html)
* [A Philosophy in Time of War (1918)](/Volumes/16/04/philosophy_in_time_of_war.html)
* [Forward (1920)](/Volumes/20/05/forward.html)
* [Unrest (1920)](/Volumes/19/05/unrest.html)

<!-- Similar articles end here -->