
---
title: 'The Colored Audience'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 5
  page: 217
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Let us be frank. The colored audience as I have seen it recently in the colored theatres of large cities is not above reproach. We are an appreciative people certainly, but our appreciation need not take the form of loud ejaculations and guffaws of laughter, particularly when that laughter breaks out in the wrong place. Any actor is pleased when the responsiveness of his audience shows him he has got his lines "across," but the most frenzied Othello can hardly conceal his bewilderment when his attempt Desdemona provokes to strangle shouts of merriment. 

Is this state of affairs due to ignorance or thoughtlessness? To a combination of both, I fancy. We cannot afford either. It is true one goes to the theater to be amused, in any event to be diverted, but the establishment and maintenance of the colored theater and the colored actor have at this point of our development a peculiar, though obvious significance. Our actors must be encouraged and not put on a level with mountebanks whose slightest gesture is the signal for laughter. There is no truer encouragement than an intelligent appreciation. We shall have to take lessons in its development. Laughter is desirable, tears also, but each in its place. 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [In Black (1920)](/Volumes/20/06/in_black.html)
* [Precept and Practice (1910)](/Volumes/01/02/precept_and_practice.html)
* [The Inevitable (1910)](/Volumes/01/02/inevitable.html)
* [A Mild Suggestion (1912)](/Volumes/03/03/mild_suggestion.html)
* [A Little Play (1914)](/Volumes/07/05/a_little_play.html)

<!-- Similar articles end here -->