
---
title: 'The Episcopal Church'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 2
  page: 83-84
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



In the red blood-guiltiness of the Christian church in America toward black folk the Episcopal Church has undoubtedly larger share any other group. It was the Episcopal Church that for 250 years made itself the center and bulwark of man stealing and chattel slavery. It was the Episcopal Church that deliberately closed its doors in the face of the praying slave; it was the Episcopal Church that refused after the war to educate the freedmen, and is still refusing, and it is only on the rostrum of the Episcopal Church that such reactionary heathenism could find welcome expression as was uttered by the bishops of Georgia and Tennessee at the last general convention.

The setting was characteristic. In the Cathedral of St. John the Divine were gathered 1,000 persons, three-fourths of whom represented the emancipated and risen race whom the church for two centuries had insulted and spit upon. They were quiet, well bred and earnest people, long suffering and self-sacrificing. They did not complain when the obsequious ushers pushed them to the rear and carried forward the snobs and pretenders—the smug-faced hypocrites who are making the Episcopal Church in America a hissing in the ears of righteous men.

The dark hundreds sat down quietly and listened to—what? To a political screed, to lies that sounded deliberate, and to a wretched carping bitterness which disgraced the anointed prelates who thus fumed and cursed God and insulted their helpless auditors.

It is NOT true that the Fifteenth Amendment is the cause of the problems arising from the presence of the Negro race in America, and no student of American history with an ounce of sense or honesty would affirm this. As a matter of fact it was only the ballot of reconstruction times that kept the freedmen from re-enslavement.

There is not the slightest evidence that the South has spent $165,000,000 for Negro education, and yet this venerable lie, started in the senility of the late Commissioner Harris, was paraded again to salve the conscience of the guilty South.

The Atlanta University conference did NOT affirm the unmorality of most Negro preachers. It affirmed just the opposite, and the bishop of Tennessee made statements which sounded like deliberate falsification of the facts when he twisted a partial quotation out of its context to serve his own ends.

The American Negro does NOT stand in unusual need of moral training. It is the American white man who needs that. The American white man, and especially the white man of the South, is a thief and a libertine to a greater extent than the Negro ever was or ever will be, and it is an impudent thing to preach regeneration to the helpless victims of slavery and lust and stealing.

Why should the Episcopal Church in the day of its dotage thus elaborately set the stage to advertise Southern reactionaries? Why should it thrust forward Nelson and Gailor and leave in the background Dillard, Weatherby, Bishop and Peabody? Is not this but one of many signs which show that this great institution is the church of John Pierpont Morgan and not the church of Jesus Christ?

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Crime (1918)](/Volumes/15/05/crime.html)
* [The Church and the Negro (1913)](/Volumes/06/06/church_negro.html)
* [The Church (1916)](/Volumes/11/06/church.html)
* [The Methodist Church, North (1911)](/Volumes/01/05/methodist_church_north.html)
* [Jesus Christ in Baltimore (1911)](/Volumes/01/03/baltimore.html)

<!-- Similar articles end here -->