
---
title: 'The Three Wise Men'
author: Du Bois, W.E.B.
date: Jun. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 2
  page: 80-82
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The comet was blazing down from the sky on the midnight before Christmas. Three songs were dying away in the East: one from the rich and ornate chapel of the great cathedral on the hills beyond 110th Street—a song of beauty and exquisite finish but coldly and formally sung. Another, a chant from the dim synagogue on the lower East Side—heavy with droning and passionate; the last from West 53d Street—a minor wail of utter melody. The songs had died away and the three priests, looking at the midnight sky, saw the comet at the same moment. The priest in the ornate chapel, gowned in his silken vestments, paused and stared wonderingly at the star; it seemed drawing near to him and guiding him. Almost before he knew it he had thrown a rich fur cloak about himself and was whirling downtown in a taxicab, watching the star with fascinated gaze. The rabbi on the lower East Side no sooner saw that blaze in the heavens than a low cry of joy left his lips and he followed swiftly, boarding a passing Grand Street car and changing up Broadway; he hung on the footboard to watch unmindful of the gibes at his white beard and Jewish gabardine. The old black preacher of 53d Street, with sad and wrinkled face, looked at the moving star thoughtfully and walked slowly with it. So the three men threaded the maize of the Christmas-mad streets, neither looking on the surging crowds nor listening to the shouts of the people, but seeing only the star. The "honk, honk" of the priest's taxicab warned the black priest scarcely too soon, and he staggered with difficulty aside as it whizzed by and made the motorman of the car, which bore the Jew, swear at the carelessness of the chauffeur. One flew, the other whirred swiftly and the third walked slowly; yet because of their differing ways they all came to the steps of the great apartment house at the same moment, and they bowed gravely to each other, yet not without curiosity, as each ascended the steps. The porter was strangely deferential and they rose swiftly to the seventh floor, where a wide hall door flew silently open.

Within and before the wide log fire of the drawing room sat a woman. She was tall and shapely and well gowned. She sat alone. The guests had gone an hour since and the last footsteps of the servants were echoing above; yet she sat there weary, still gazing into the mystery of the fire. She had seen many Christmas Eves and they were growing all to be alike—wretchedly alike. All equally lonely, aimless—almost artificial. She arose once and walked to the window, sweeping aside the heavy curtains, and the brilliancy of the star blazed in upon her. She looked upon it with a start. She remembered how once long, long years ago she had looked upon stars and such things as very real and shining fingers of fate. She remembered especially on a night like this how some such star had told her future. How out of her soul wonderful things were to be born, and she had said unto the star: "How shall this be?" And something had answered: "That holy thing that shall be born of you shall be called the Son of God." And then she had cried in all her maiden faith and mystery: "Behold the hand-maiden of the Lord, be it according to thy word." And the angel departed from her, and it never came back again. Here she was reaching the portals of middle age with no prospects and few ambitions; to live and wait and sleep; to work a soulless work, to eat in some great manger like this—that was the life that seemed stretching before her endless and without change, until the End and the Change of Changing. And yet she had dreamed such dreams and fancied such fair destiny! As she thought of these dreams to-night a tear gathered and wandered down her face. It was then that she became suddenly aware of two men standing on either side of her, and she felt, but did not see, a third man, who stood behind. But for the soft voice of the first speaker she would have sprung up in alarm, but he was an old man and deferential with soft ascetic Jewish face, with white-forked beard and gabardine, and he bowed in deep humility as he spoke, saying:

"Where is He that is born King of the Jews, for we have seen His star in the East, and have come to worship Him?"

The other surpliced figure, who stood upon her right hand, said the same thing, only less:

"Where is He who is born King, for we have seen His star in the East, and have come to worship Him?" And scarcely had his voice ceased than the strong low rolling of another voice came from behind, saying:

"Where is He, for we have seen His star in the East, and have come to worship Him?"

She sank back in her chair and smiled. There was evidently some mistake, and she said to the Jew courteously:

"There is no King here."

"But," said the Jew, eagerly, tremulously, "it is a child we seek, and the star has guided us hither; we have brought gifts of gold and frankincense and myrrh." Still the woman shook her head.

"Children are not allowed in these apartments," she said, "and besides, I am unwed."

The face of the Jew grew radiant.

"The Scriptures say He shall be born of a Virgin," he chanted. But the woman smiled bitterly.

"The children of Virgins are not welcome in the twentieth century, even though they be Sons of God!"

"And in a manger," continued the Jew.

"This is, indeed, a manger," laughed the woman, "but He is not here---He is not here---only---cattle feed here."

Then the silk-robed priest on the left interrupted:

"You do not understand," he said, "it is not a child of the body we seek, but of the Word. The Word which was with God and the Word which was God. We seek the illuminating truth which shall settle all our wild gropings and bring light to this blind world." But the woman laughed even more bitterly.

"I was foolish enough once to think," she said, "that out of my brain would leap some wondrous illuminating word which should give light and warmth to the world, but nothing has been born, save here and there an epigram and the smartness of a phrase. No, He is not here."

The surpliced priest drew back with disappointed mien, and then suddenly, in the face of priest and Jew, as they turned toward the unseen figure at her back, she saw the birth of new and wonderful comprehension—Jew and Gentile sank to their knees—and she heard a soft and mighty voice that came up out of the shadows behind her as she bent forward, almost crouching, and it said:

"Him whom we seek is child neither of thy body nor of thy brain, but of thy heart. Strong Son of God, immortal love. We seek not the king of the world nor the light of the world, but the love of the world, and of all men, for all men; and lo! this thou bearest beneath thy heart, O woman of mankind. This night it shall be born!"

Slowly her heart rose and surged within her as she struggled to her feet; a wonderful revelation lighted in her whirling brain. She, of all women; she, the chosen one—the bride of Almighty God; her lips babbled noiselessly searching for that old and saintly hymn: "My soul doth magnify the Lord, and my spirit hath rejoiced in God, my saviour. For he hath regarded the low estate of his hand-maiden, for behold! from henceforth all generations shall call me blessed." A great new strength gripped her limbs. Slowly she arose, and as she rose, the roof rose silently with her—the walls of the vast room widened—the cold wet pavement touched her satined feet, and the pale-blue brilliance of the star rained on her coiled hair and naked shoulders. The shouting, careless, noisy midnight crowds surged by and brushed her gown. Slowly she turned herself, with strange new gladness in her heart, and the last words of the hymn on her lips: "He hath put down the Mighty from their seats and hath exalted them of low degree; he hath filled the hungry with good things and the rich he hath sent empty away." She turned, and lo! before her stood that third figure, an old, bent black man, sad faced and pitiful, and yet with brilliant caverned eyes and mighty wings that curved to Heaven. And suddenly there was with the angel a multitude of the heavenly host praising God and saying:

"Glory to God in the highest; and on earth peace, good will toward men."

SELAH!
