
---
title: 'Mob Tactics'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Aug. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 6
  page: 204
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There has been developed in the United States a regular technique in matters of mob violence. Matters move somewhat as follows:

A crime is committed. The police hasten to accuse a Negro. This, of course, is popular because the white public readily believes in Negro crime. A Negro is arrested. If he is promptly lynched the police are vindicated and the guilty white persons saved from fear of detection. If lynching is delayed but threatened a mob usually attacks the Negro district. This gives a chance for looting and stealing. If any Negroes defend themselves, immediately the police, often assisted by the militia, promptly disarm all Negroes and charge a number with rioting. If any white people are arrested for rioting nearly all of them are discharged; but the Negroes are held and prosecuted. This serves to intimidate the Negro population and keeps it from attempting any self-defense, however innocent the defenders may be, and in no matter how grave danger to life, limb and property.

The result of all this is to mystify and mislead the public. By the time that the rioting is over, they are under the impression that the Negroes were partially responsible for starting the trouble and that they were armed and conspiring to kill innocent white people. Thus aggression against Negro Americans becomes an exciting form of sport for the lower order of white folk, in which they have practically nothing to lose and little to fear.

The technique of this procedure is, of course, taken from the acts of England and other countries in dealing with their colonies. Whenever the natives are subdued or punished and compelled to bow to the will of white folk, the explanation is that the natives were the aggressors; that the Colonial Power was acting in self-defense and that civilization was in danger.

The only solution to this kind of problem is not simply to permit but to encourage Negroes to keep and use arms in defense against lynchers and mobs.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Crime (1920)](/Volumes/19/04/crime.html)
* [Lynchings and Mobs (1921)](/Volumes/22/04/lynchings.html)
* [Coffeeville, Kanasas (1927)](/Volumes/34/05/coffeville_kansas.html)
* [The Challenge of Detroit (1925)](/Volumes/31/01/challenge_of_detroit.html)
* [The Old Story (1911)](/Volumes/01/03/old_story.html)

<!-- Similar articles end here -->