
---
title: 'Peace'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 1
  page: 26
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



At the coming meeting of the peace societies at St. Louis the question of peace between civilized and backward peoples will not probably be considered. The secretary of the New York Peace Society writes us that "Our peace congresses have not dealt in the past with the relations of civilized and non-civilized people;" and he thinks that largely on this account "our American congresses have been more dignified and more influential than those held abroad."

We are not sure about that word "influential," but there is no doubt about the dignity of the American peace movement. It has been so dignified and aristocratic that it has been often most difficult for the humbler sort of folk to recognize it as the opponent of organized murder.

At a recent meeting of the New York Peace Society the war in the Balkans was eulogized and applauded, and the president stated that "when we advocate peace" it is for nations "worthy of it!" Such a peace movement belies its name. Peace to-day, if it means anything, means the stopping of the slaughter of the weaker by the stronger in the name of Christianity and culture. The modern lust for land and slaves in Africa, Asia and the South Seas is the greatest and almost the only cause of war between the so-called civilized peoples. For such "colonial" aggression and "imperial" expansion England, France, Germany, Russia and Austria are straining every nerve to arm themselves; against such policies Japan and China are arming desperately. And yet the American peace movement thinks it bad policy to take up this problem of machine guns, natives and rubber, and wants "constructive" work in "arbitration treaties and international law." For our part we think that a little less dignity and dollars and a little more humanity would make the peace movement in America a great democratic philanthropy instead of an aristocratic refuge.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [Peace (1915)](/Volumes/10/01/peace.html)
* [Peace (1933)](/Volumes/40/12/peace.html)
* [Just Like---Folks (1920)](/Volumes/19/05/just_like_folks.html)
* [Thirteen (1918)](/Volumes/15/03/thirteen.html)

<!-- Similar articles end here -->