
---
title: 'Again, Social Equality'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1920
categories: 
  - Social Equality
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 5
  page: 236-237
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Mr. Paleface entered his parlor mincingly,---"My dear man," he said, expressively. 

"I am Brownson," said the dark man quietly. 

"Of course---of course---I know you well, and your people. My father was an abolitionist, and I had a black mammy&#11834;"

Mr. Brownson looked out of the window, and said rapidly: 

"I have come to ask for certain rights and privileges. My people&#11834;" 

"&#11834;"suffer; I know it; I know it. I have often remarked what a shame it was. Sir, it is an outrage!" 

"&#11834; yes; we want to ask&#11834;"

Mr. Paleface raised a deprecating finger, 'Not social equality," he murmured,---"I trust you are not asking that." 

"Certainly not," said Brownson. "I think the right of a man to select his friends and guests and decide with whom he will commit matrimony, is sacredly his and his alone." 

"Good---good! Now, my man, we can talk openly, face to face. We can pour out our souls to each other. What can I do? I have already sent my annual check to Hampton." 

"Sir, we want to vote." 

"Ah! That is difficult---difficult. You see, voting has come to have a new significance. We used to confine our votes to politics, but now---bless me!---we are voting religion, work, social-reform, landscape-gardening, and art. Then, too, women are in politics ---you see---well, I'm sure you sense the difficulties. Moreover, what is voting? A mere form---the making and execution of the laws is the thing, and there I promise you that I&#11834;" 

"Well, then; we would help in carrying out the laws." 

"Commendable ambition. Very, very commendable. But this involves even greater difficulties. Administrators and executives are thrown closely together---often in the same room--- at the same desk. They have to mingle and consult. Much as I deplore the fact, it is true, that a man will not sit at a desk or work at a bench with a man whose company at a theatre he would resent." 

"T see," said Brownson, thoughtfully. "I presume, then, it is our business to demand this right to sit in theatres and places of popular entertainment." 

"Good Lord, man, that's impossible! Civil rights like this cannot be forced. Objectionable persons must grow, develop---er wash, before&#11834;"

"Then I am sure you will help me clean and train my people. I want to join in the great movements for social uplift." 

"Splendid! I will have some movements organized for your folks." 

"No, I want to be part of the general movement, so as to get the training and inspiration, the wide outlook---the best plans." 

"Are you crazy? Don't you know that social uplift work consists of a series of luncheons, dinners, and teas, with ladies present?" 

"Um," said Brownson. "I see. I, also, see that in answering your first question, I made a mistake. In the light of your subsequent definition, I see that social equality, far from being what I don't want, is precisely what I do want." 

"I knew it!' screamed Mr. Paleface. "I knew it all the time; I saw it sneaking into your eyes. You want---you dare to want to marry my sister.'

"Not if she looks like you," said  Brownson, "and not if she's as big a liar." 

"Get out---get out---leave my house, you ungrateful&#11834;"

 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [''Social Equality'' (1911)](/Volumes/03/01/social_equality.html)
* [Divine Right (1912)](/Volumes/03/05/divine_right.html)
* [Social Equality (1922)](/Volumes/24/01/social-equality.html)
* [DePriest (1929)](/Volumes/36/02/depriest.html)
* [For What (1919)](/Volumes/17/06/for_what.html)

<!-- Similar articles end here -->