
---
title: 'Dives, Mob, and Scab'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 5
  page: 235-236
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


He sat in a massive arm-chair, before a carved mahogany desk. Beneath him lay a Turkish rug, and behind him, through the window, one saw his steel mills, minting millions. 

"Yes," he said; "I recognize the new power of the Negro in Industry. He broke the steel strike for us!" 

My heart stopped. Merciful God! It is to this, we have come. I saw the squalor and toil and endless hours of the stricken workman. I saw him sink beneath the murk, while at his throat were the hands of my people! 

Then to my heart the blood came surging back. Why were these rivals wallowing in the swill and offal of the Steel Barons? Was the work so lovely and the pay so high? No; but because black peonage of the South is worse than the foreign white slavery of the North; because the black worker has small choice: to be lynched, to work for nothing in Georgia and Arkansas, or to be a scab in Pennsylvania. It's better to be a scab. But who forced on the black man this choice? Two men,---the White Worker and the Steel Baron. The white worker, when he said in the South, "You shan't vote," and when he said in the North, "You shan't join my Union! Or, if you do join, you're still a nigger, and I'm white." 

In part, then, the guilt lies with the worker; but only in part, and, perhaps, when we think of ignorance and poverty,---in smaller part. The deeper, bloodier, guilt lies with those Masters of Industry, who today, yesterday, and tomorrow, plan to make the petty, human jealousies, hatreds, rivalries, and starvations of workingmen, the foundation of their colossal fortunes. They are the breeders-of mobs and lynchings, of unrest and despair, of race war and class struggle. They stand above the squabble, like ringmasters cracking their whips, and at every writhing coil of the long snakelike lash, some white man mobs a nigger," and some black man takes the bread from the white man's mouth. Thus, in vicious, unending circle, the hate and harm rise, mount, and spread. 

 
<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)
* [Heroes (1919)](/Volumes/19/01/heroes.html)
* [Labor Omnia Vincit (1919)](/Volumes/18/05/labor_omnia_vincit.html)
* [The Black Man and Labor (1925)](/Volumes/31/02/black_man_and_labor.html)
* [Precept and Practice (1910)](/Volumes/01/02/precept_and_practice.html)

<!-- Similar articles end here -->