
---
title: 'Information Wanted'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 5
  page: 235
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Last summer, Negro farmers in Arkansas organized the "Progressive
Farmers and Household Union of America," to better their condition.
Robert L. Hill, a farmer, was one of the chief organizers, and the Union
was incorporated under state law. When the trouble occurred in Phillips
County, a thousand Negroes were arrested, over twenty-five murdered,
twelve sentenced to death, and scores to the penitentiary. Among the
victims were four of the most prominent professional colored men in
Helena.

Hill was accused of "instigating" this riot. He fled, protesting his
innocence. Recently he was arrested in Kansas. The N.A.A.C.P., which
is straining every sinew to secure justice in Arkansas, immediately
protested by wire, asserting that Hill could not be fairly tried in
Arkansas. Governor Allen of Kansas is a progressive, humane man, and
listened willingly to the attorneys whom we put on the case---

*But------*

*The sheriff produced a petition signed by three prominent black leaders of Arkansas, asking that Hill be returned to Arkansas!*

These men are:

BISHOP J. M. CONNER, *African Methodist Church*; J.M. COX, President, *Philander Smith College*; JOSEPH A. BOOKER, President, *Arkansas Baptist College*.

<span class="crisis-title">The Crisis</span> wishes to do no man an injustice, and, therefore, we pause one month to ask:

*Bishop Conner, President Cox, and President Booker---did you sign that petition?*

*If you did---why did you?*

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Arkansas (1920)](/Volumes/19/04/arkansas.html)
* [The Real Causes of Two Race Riots (1919)](/Volumes/19/02/real_causes.html)
* [Extradition Cases (1920)](/Volumes/20/01/extradition_cases.html)
* [Coffeeville, Kanasas (1927)](/Volumes/34/05/coffeville_kansas.html)
* [Signs from the South (1919)](/Volumes/18/05/signs_from_south.html)

<!-- Similar articles end here -->