
---
title: 'Just Like---Folks'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 5
  page: 234-235
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The Negroes, in our natural, present state of hyper-criticism say, among ourselves, "just like colored folks" when something is muddled or forgotten or goes distressingly wrong. But let us for a moment look beyond: The best civilized people of the world fought each other for four years, when ninety-nine out of every hundred did not want to fight at all; the Peace Conferences took three months to arrange for stopping the war; the United States filled the circumambient air with ululations at their delay. Thereupon, this same United States proceeded to take nine months to refuse to ratify the Treaty! The war stopped,---the world was at peace, the League of Nations was established, and still the United States was at war with Germany. No amendment of the Peace Treaty could get consideration in the Senate until a foreign statesman showed us how; the Pacifists and the War-to-the-bitter-enders rejoiced together at the delay. Protagonists in the fight for democracy, meantime, turned into heresy hunters, to protect the "sacred" rights of property. Workers were scared, browbeaten, and deported, at the very time when work was the demand of the hour. Just when thinking was necessary, the Attorney General and the United States Congress united to make Thought a Crime. For two years we trained Negoes to fight, and now we are stiff with fright, lest they may fight.

And Lansing, and Fiume---but why add? Isn't it all "just like white folks?"

 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [Close Ranks (1918)](/Volumes/16/03/close_ranks.html)
* [The Present (1917)](/Volumes/14/04/present.html)
* [Amity (1921)](/Volumes/22/03/amity.html)
* [Germany (1916)](/Volumes/11/04/germany.html)

<!-- Similar articles end here -->