
---
title: 'Woman Suffrage'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 5
  page: 234
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Thirty-one states, with a population of 681,325 colored women, 21 years of age and over, in 1910, and at least 750,000 today, have ratified the proposed Woman Suffrage Amendment:

|               |       |               |         |
| ------------- | ----: | ------------- | ------: |
| Maine         | 401   | Arkansas      | 102,917 |
| N. H'sphire  | 176   | Texas        | 161,959 |
| Mass.        | 12,648 | Montana      | 553     |
| New York     | 49,300 | Colorado     | 3,861   |
| Pa.          | 62,949 | Utah         | 313     |
| Ohio         | 33,683 | California   | 6,936   |
| Illinois     | 34,372 | Rhode Island | 3,178   |
| Michigan     | 5,318  | Kentucky     | 73,413  |
| Wisconsin    | 939    | Oregon       | 443     |
| Minnesota    | 2,061  | Indiana      | 18,386  |
| Virginia     | 4,124  | Wyoming      | 494     |
| Missouri     | 48,057 | Nevada       | 202     |
| N. Dakota    | 158    | New Jersey   | 29,866  |
| S. Dakota    | 220    | Idaho        | 187     |
| Nebraska     | 2,369  | Arizona      | 635     |
| Kansas       | 15,289 |              |         |

It seems probable that at the next presidential election, three million Negro women will have the right to vote.

Let them get ready.

North and South, study clubs should be formed, with teachers and reading matter. Know the government of your ward, county, and state. Master the qualification laws. Register, and pay any necessary taxes.

Get ready.

They may beat and bribe our men, but the political hope of the Negro, rests on its intelligent and incorruptible womanhood.

 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Triumph (1920)](/Volumes/20/06/triumph.html)
* [Votes for Women (1914)](/Volumes/08/04/votes_for_women.html)
* [Woman Suffrage (1915)](/Volumes/11/01/woman_suffrage.html)
* [Woman Suffrage (1915)](/Volumes/09/06/womansuffrage.html)
* [Ohio (1912)](/Volumes/04/04/ohio.html)

<!-- Similar articles end here -->