<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.45">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="W.E.B. Du&nbsp;Bois">
<meta name="dcterms.date" content="1928-10-01">

<title>The Possibility of Democracy in America – Dare You Fight</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
<meta name="citation_title" content="The Possibility of Democracy in America">
<meta name="citation_author" content="W.E.B. Du&nbsp;Bois">
<meta name="citation_publication_date" content="1928-10-01">
<meta name="citation_cover_date" content="1928-10-01">
<meta name="citation_year" content="1928">
<meta name="citation_online_date" content="1928-10-01">
<meta name="citation_fulltext_html_url" content="https://www.dareyoufight.org/Volumes/35/10/possible_democracy.html">
<meta name="citation_issue" content="10">
<meta name="citation_volume" content="35">
<meta name="citation_language" content="en">
<meta name="citation_firstpage" content="336, 353">
<meta name="citation_journal_title" content="The&nbsp;Crisis">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../Images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Dare You Fight</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../listing.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../covers.html"> 
<span class="menu-text">Covers</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Possibility of Democracy in America</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>W.E.B. Du&nbsp;Bois </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 1, 1928</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>For several years after the World War I used to talk concerning the results of the War, and to say that notwithstanding the slaughter and the upheaval that always accompany war we were going to have in the world an extension of democracy as a result of the fighting; that the democracy which formerly had ruled in restricted fields - in the election of officials, in the so-called political world - we were going to see extended into industry, so that in regard to work and wages and income, we were going to have democratic control. But I write today to apologize and change my thesis. I was wrong in what I was predicting. I see today without any doubt that instead of the great question of democracy being an extension of democratic control into further territory, the problem that faces us in America and faces the world is the question as to whether we can keep the territory which we thought democracy had already conquered; that, as a matter of fact, in every single culture country there is today a fight to retain democracy, and that reaction and oligarchy are beginning to hold up their heads in the world and to triumph. Moreover, here in the United States, here where we have essayed the greatest experiment in democracy, we have perhaps the greatest failure.</p>
<p>Nothing could show this more than the present presidential campaign. There are momentous questions: the plight of American agriculture, the monopoly of water power, the role of organized wealth in industry, the future of organized labor, the distribution of national income. Most of these important questions we are not facing in this campaign. Why? Because the average voter does not understand how to face them. He finds himself vainly pawing the air in the so-called elections. He finds that he cannot exercise democratic control because he is not free to vote.</p>
<p>In the September <span class="small-caps">Crisis</span> I showed how, where and why American Negroes were not free to vote. But how about white Americans? Are they disfranchised?</p>
<p>It might be assumed that the practical disfranchisement of the great majority of Negroes chiefly by race and not by condition had no effect upon the state and nation, but simply upon them: but the singular thing is, and the point which this paper is seeking to emphasize, that this disfranchisement of the Negro has had an astonishing effect on the voting of other persons in the states concerned and in the whole nation so far as the mass of voters is concerned.</p>
<p><img src="../../../Images/disfranchisement_in_the_south.png" class="img-fluid"></p>
<p>First, in the Southern states it encourages oligarchy. Secondly, it enables cliques to nullify, not simply the 14th and 15th Amendments, but the 19th Amendment, giving the right vote to women, And finally, it entirely vitiates the normal distribution of voting power throughout the nation and makes a third party impossible. Let us take these points up in order.</p>
<p>One of the most interesting statements on clique government in the South comes from Henry W. Anderson, a rich white Virginia politician, who spoke at the Institute of Public Affairs held at the University of Virginia, August 19, 1927:</p>
<blockquote class="blockquote">
<p>The Negroes were disfranchised. The Negro vote has since been so small that it is no longer a material factor in the political situation. But the process of disfranchisement did not stop there. The machinery of discrimination, devised primarily for this purpose, was then employed by the dominant party organization to effect a disqualification of a large proportion of the white population opposed to that organization, while unchallenged control of one political group permitted or encouraged political corruption. As a result of these measures the vote qualified or cast in the Southern States has been so reduced that it includes only a small minority of the population. So small is this vote that the State and local office-holders constitute or easily control a majority. Governors and other state officers are sometimes elected by less than 10 per cent of the population of voting age.</p>
</blockquote>
<p>Let us see how far we can illustrate this state of affairs by figures: we will take eleven Southern states - Virginia, North Carolina, South Carolina, Georgia, Florida, Alabama, Mississippi, Arkansas, Louisiana, Oklahoma and Texas. We have the following facts as to the increase of population and of voting population in the presidential elections.</p>
<p style="text-align:center">
POPULATION
</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1870</td>
<td>8,228,826</td>
<td>1900</td>
<td>17,745,821</td>
</tr>
<tr class="even">
<td>1880</td>
<td>11,457,878</td>
<td>1910</td>
<td>21,884,778</td>
</tr>
<tr class="odd">
<td>1890</td>
<td>14,197,747</td>
<td>1920</td>
<td>24,797,353</td>
</tr>
</tbody>
</table>
<p>The presidential vote during this time has been as follows:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1872</td>
<td>1,238,141</td>
<td>1900</td>
<td>1,572,414</td>
</tr>
<tr class="even">
<td>1876</td>
<td>1,606,230</td>
<td>1904</td>
<td>1,091,679</td>
</tr>
<tr class="odd">
<td>1880</td>
<td>1,555,534</td>
<td>1908</td>
<td>1,302,664</td>
</tr>
<tr class="even">
<td>1884</td>
<td>1,682,314</td>
<td>1912</td>
<td>1,538,386</td>
</tr>
<tr class="odd">
<td>1889</td>
<td>1,808,964</td>
<td>1916</td>
<td>1,857,240</td>
</tr>
<tr class="even">
<td>1892</td>
<td>1,870,948</td>
<td>1920</td>
<td>2,662,588</td>
</tr>
<tr class="odd">
<td>1896</td>
<td>1,945,463</td>
<td>1924</td>
<td>2,865,747</td>
</tr>
</tbody>
</table>
<p>The population in these states increased over 200 per cent since 1870, but the voting population has increased only 131% over 1872, despite woman suffrage. If we compare the population 1890-1920 and the voters 1892-1920, we find the population has increased 75% and the voters 42% despite the doubling of the electorate by woman suffrage. In other words, we have in the South today not only a nullification of the 15th but also of the 19th Amendment.</p>
<p>Moreover, the increase of voting from 1904 to 1924 is mainly in North Carolina, Oklahoma and Texas. If we take the five states of Alabama, Georgia, Louisiana, Mississippi and South Carolina, we have this result:</p>
<p style="text-align:center">
POPULATION
</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1870</td>
<td>4,441,544</td>
<td>1900</td>
<td>8,318,238</td>
</tr>
<tr class="even">
<td>1880</td>
<td>5,871,805</td>
<td>1910</td>
<td>9,716,116</td>
</tr>
<tr class="odd">
<td>1890</td>
<td>6,910,001</td>
<td>1920</td>
<td>10,517,957</td>
</tr>
</tbody>
</table>

<p style="text-align:center">
PRESIDENTIAL VOTE
</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1872</td>
<td>661,770</td>
<td>1900</td>
<td>449,141</td>
</tr>
<tr class="even">
<td>1876</td>
<td>844,001</td>
<td>1904</td>
<td>377,151</td>
</tr>
<tr class="odd">
<td>1880</td>
<td>701,066</td>
<td>1908</td>
<td>424,326</td>
</tr>
<tr class="even">
<td>1884</td>
<td>619,166</td>
<td>1912</td>
<td>433,797</td>
</tr>
<tr class="odd">
<td>1888</td>
<td>629,675</td>
<td>1916</td>
<td>499,434</td>
</tr>
<tr class="even">
<td>1892</td>
<td>693,127</td>
<td>1920</td>
<td>667,406</td>
</tr>
<tr class="odd">
<td>1896</td>
<td>598,092</td>
<td>1924</td>
<td>617,327</td>
</tr>
</tbody>
</table>
<p>We can see here the enfranchisement of the Negro (1872-76). His disfranchisement first by intimidation (1880-84) and then by law (1892-1904); then a slow increase of the white vote, accelerated by the 19th Amendment in 1920 but checked in 1924.</p>
<p>The effect of the 19th Amendment is interesting: not only Negroes but white men of these states gradually stopped voting after Negro disfranchisement: the million voters of 1892 falling to less than 400,000 in 1904. A hundred thousand were added to the polls, 1904-16, although a million and a half had been added to the population. A hundred and fifty thousand women came to the polls right after the adoption of the woman’s suffrage amendment out of a possible two million and 50,000 of these disappeared four years later in spite of a million increase in population.</p>
<p>In other words, in these five states, out of a total of 5,145,282 persons 21 years of age and over, there were 635,512 votes cast in 1920. There were in this election, therefore, disfranchised voluntarily or involuntarily, 4,489,770 persons. Subtracting 19,000 Negroes as actually voting from the total number of Negroes 21 years of age and over, we have 2,215,991 Negroes disfranchised. But we also have 2,297,799 whites disfranchised, which is a fair indication of the cost of Negro disfranchisement in these five states.</p>
<p style="text-align:center">
VOTERS - SOUTH - 1920
</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>White</th>
<th>Negro</th>
<th>Total</th>
<th>Votes</th>
<th>Disfranchised</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>South Carolina</td>
<td>403,061</td>
<td>376,930</td>
<td>779,991</td>
<td>66,150</td>
<td>713,841</td>
</tr>
<tr class="even">
<td>Georgia</td>
<td>846,276</td>
<td>575,330</td>
<td>1,421,606</td>
<td>148,716</td>
<td>1,272,890</td>
</tr>
<tr class="odd">
<td>Alabama</td>
<td>702,265</td>
<td>441,130</td>
<td>1,143,395</td>
<td>241,070</td>
<td>902,325</td>
</tr>
<tr class="even">
<td>Mississippi</td>
<td>422,443</td>
<td>453,663</td>
<td>876,106</td>
<td>82,492</td>
<td>793,614</td>
</tr>
<tr class="odd">
<td>Louisiana</td>
<td>564,993</td>
<td>359,251</td>
<td>924,184</td>
<td>117,084</td>
<td>807,100</td>
</tr>
<tr class="even">
<td></td>
<td>———–</td>
<td>———–</td>
<td>———–</td>
<td>————</td>
<td>—————</td>
</tr>
<tr class="odd">
<td></td>
<td>2,919,038</td>
<td>2,206,304</td>
<td>5,145,282</td>
<td>635,512</td>
<td>4,489,770</td>
</tr>
</tbody>
</table>
<p><br></p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 28%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Estimated Negroes Voting</th>
<th>Negroes Disfranchised</th>
<th>Whites Disfranchised</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>South Carolina</td>
<td>2,000</td>
<td>374,930</td>
<td>337,721</td>
</tr>
<tr class="even">
<td>Georgia</td>
<td>10,000</td>
<td>565,330</td>
<td>703,580</td>
</tr>
<tr class="odd">
<td>Alabama</td>
<td>5,000</td>
<td>436,130</td>
<td>464,191</td>
</tr>
<tr class="even">
<td>Mississippi</td>
<td>1,000</td>
<td>451,130</td>
<td>342,484</td>
</tr>
<tr class="odd">
<td>Louisiana</td>
<td>1,000</td>
<td>358,251</td>
<td>449,849</td>
</tr>
<tr class="even">
<td></td>
<td>——————</td>
<td>———————–</td>
<td>———————-</td>
</tr>
<tr class="odd">
<td></td>
<td>19,000</td>
<td>2,215,771</td>
<td>2,297,799</td>
</tr>
</tbody>
</table>
<p>There is one consideration which, in the opinion of some, modifies these figures. In each one of these states there is practically but one party and a “white primary.” Ostensibly to make the exclusion of the Negro voter doubly sure a system came into vogue by which only white voters are admitted to the dominant party primary and the condition of admittance was a promise to abide by the decision of the primary.</p>
<p>This means that in order to vote at all the white voter must first disenfranchise himself so far as having any voice as to the major principles which form the chief matters of difference between parties. Practically his vote is confined to choosing between individuals who will carry out principles which he must accept before voting at all. If, for instance, a Southern white man wants to vote in the Democratic primary this year, he can only do so if he gives up his right to vote against Al Smith!</p>
<p>In four of the states mentioned, 229,619 people voted in the regular election, while 722,271 voted in the primary election. If it is assumed that participation in the primary is some index of political interest, then the vote of the five states that we are studying ought to be quoted as 1 ⅓ million rather than 600,000. But even this is not more than a third the number of voters that a normal population of 10 ½ millions should furnish under universal suffrage. It shows, not simply the disfranchisement of practically all of the Negro voters, forming 40% of the population in these states, but that even if we give some weight to the “white primary” nearly two million white voters were simultaneously disfranchised.</p>
<p><em>In other words, the effort to disfranchise a million and a half Negro voters has cost the disfranchisement of nearly two million white voters, even if one assumes that the primary election is a fair example of the exercise of political power, which, of course, it is not.</em></p>



<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-du_bois1928" class="csl-entry quarto-appendix-citeas" role="listitem">
Du&nbsp;Bois, W.E.B. 1928. <span>“The Possibility of Democracy in
America.”</span> <em>The&nbsp;Crisis</em> 35 (10): 336, 353--355. <a href="https://www.dareyoufight.org/Volumes/35/10/possible_democracy.html">https://www.dareyoufight.org/Volumes/35/10/possible_democracy.html</a>.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/www\.dareyoufight\.org");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>