
---
title: 'Baker'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 15
  issue: 2
  page: 61-62
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Let us raise our hats to Newton Diehl Baker, Secretary of War. He has not done everything we could wish, but he has accomplished so much more than President Wilson or any other member of this administration that he deserves all praise. He has carried out the draft with absolute fairness, notwithstanding delays. He has put black troops in nearly every cantonment. He has commissioned nearly 700 Negro officers in the United States Army. He has sent black troops to the front. He has made no discrimination in treatment or pay or opportunity. To be sure, we are segregated; but that was according to a foolish law for which the Secretary was not responsible. We are not permitted to volunteer beyond our four regiments but there, again, the authority of the Secretary is, at least, in doubt. Considering his limitations and the tremendous opposition to any act of justice to the Negro, Secretary Baker has done well. And he has crowned his well-doing by appointing an official advisor who belongs to the Negro race.

There remains one more thing for Secretary Baker to do. We have not yet our full quota of Negro officers. There were 86,300 Negroes called in the first draft. Allowing us no officers higher than captain, this would call for a thousand colored officers, and if we furnish 200,000 Negro troops in the second draft, as seems likely, we should have at least three thousand officers. We have at present seven hundred. *We need a second officers' training camp next January.* We can furnish the men; will the Government furnish the instruction? Every reader of <span class="small-caps">The Crisis</span> should urge this upon Secretary Baker and upon his congressmen. *Don't delay. Write immediately.*

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Officers (1917)](/Volumes/14/02/officers.html)
* [Soldiers (1919)](/Volumes/17/01/soldiers.html)
* [Help Us to Help (1918)](/Volumes/16/04/help_us.html)
* [The Negro Soldier (1919)](/Volumes/19/02/negro_soldier.html)
* [The Present (1917)](/Volumes/14/04/present.html)

<!-- Similar articles end here -->