
---
title: 'The Second Coming'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 15
  issue: 2
  page: 59-60
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Three bishops sat in San Francisco, New Orleans and New York, peering gloomily into three flickering fires which cast and recast shuddering shadows on book-lined walls. Three letters lay in their laps and said:

"And thou, Valdosta, in the land of Georgia, art not least among the princes of America, for out of thee shall come a Governor who shall rule my people."

The white Bishop of New York scowled and impatiently threw the paper into the fire.

"Valdosta?" he said, "that's where I go to the Governor's wedding---little Marguerite, my white flower---" Then he forgot the writing in his musing; but the paper flared red in the fireplace.

"Valdosta?" said the black bishop In New Orleans, and turned uneasily in his chair. "I must go down there. Those colored folk are acting strangely. I don't know where all this unrest and moving will lead to. Then, there's poor Lucy---" And he threw the letter into the fire; but eyed it suspiciously, as it flamed green.

"Stranger things than that have happened," he said slowly, "and ye shall hear of wars and rumors of wars..., for nation shall rise against nation and kingdom against kingdom."

In San Francisco the priest of Japan, abroad to study strange lands, sat in his lacquer chair with face like soft yellow and wrinkled parchment. Slowly he wrote in a great and golden book:

"I have been strangely bidden to the Vale of Dosta where one of those religious cults that swarm here will welcome a Prophet. I shall go and report to Kioto."

So, in the dim waning of the day before Christmas, three bishops met in Valdosta and saw its mills and storehouses, its wide-throated and sandy streets in the mellow glow of a crimson sun. The governor glared anxiously up the street as he helped the Bishop of New York into his car and welcomed him graciously.

"I am troubled," he said, "about the Niggers. They are acting queer. I'm not certain but Fleming is back of it."

"Fleming?"

"Yes; he's running against me next term for governor; he's a fire-brand; wants niggers to vote and all that--- Pardon me a moment, there's a darky I know---" and he hurried to the black bishop, who had just descended from the "Jim Crow" car, and clasped his hand cordially. They talked in whispers.

"Search diligently," said the governor in parting, "and bring me word
again." Then returning to his Guest: "You will excuse me, won't you?" he
said, "but I am sorely troubled. I never saw niggers act so. They're leaving
by the hundreds and those who stay are getting impudent. They seem to be
expecting something. What's the crowd. Jim?"

The chauffeur said that there was some sort of Chinese official in town and
everybody wanted to glimpse him. He drove around another way.

It all happened very suddenly. The Bishop of New York, in full canonicals
for the early wedding, stepped out on the rear balcony of his mansion, just as
the dying sun lit crimson clouds of glory in the East and burned the West.

"Fire!" yelled a wag in the surging crowd that was gathering to celebrate
a southern Christmas Eve; all laughed and ran.

The bishop did not understand. He peered around. Was it that dark little
house in the far back yard that flamed? Forgetful of his robes, he hurried
down—a brave white figure in the sunset. He found himself before an old
black rickety stable. He could hear the mules stamping within.

No, it was not fire. It was the sunset glowing through the cracks. Behind
the hut its glory rose toward God like flaming wings of Cherubim. He paused
until he heard the faint wail of a child. Hastily he entered. A white girl
crouched before him, down by the very mules' feet, with a baby in her arms
A little mite of a baby that wailed weakly. Behind mother and child stood a
shadow. The bishop turned to the right, inquiringly, and saw a black man
in bishop's robes that faintly echoed his own. Hastily he turned away to the
left and saw a golden Japanese in golden garb. Then he heard the black man
mutter behind him:

"But He was to come the second time in clouds of glory, with the nations
gathered around Him and angels---" at the word a shaft of glorious light fell full
upon the child, while without came the tramping of unnumbered feet and the
whirring of winds.

The Bishop of New York bent quickly above the baby.

It was black!

The bishop stepped back with a gesture of disgust, hardly listening to and
yet hearing the black bishop who spoke almost as if in apology:

"She ain't really white; I know Lucy---you see, her mother worked for
the Governor---" The bishop turned on his heel and nearly trod on the yellow
priest, who knelt with bowed head before the pale mother and offered incense
and a gift of gold.

Out into the night rushed the bishop. The wings of the Cherubim were
folded back against the stars. As he hastened down the front stair-case the
governor came rushing up the street steps.

"We are late," he cried nervously. "The Bride awaits." He hurried the
bishop to the waiting limousine, asking him anxiously:

"Did you hear anything? Do you hear that noise? The crowd is growing
strangely on the streets and there seems to be a fire over toward the East. I
never saw so many people here---I fear violence---a mob---a lynching---hark!"
What was that which the Bishop, too, heard beneath the rhythm of unnumbered feet? Deep in his heart a wonder grew. What was it? Ah, he knew.
It was music---some strong and mighty chord. It rose higher as the brilliantly-lighted church split the night and swept radiantly toward them. So high and
clear that music flew, it seemed above, around, behind them. The governor,
ashen-faced, crouched in the car; but the bishop said softly as the ecstasy pulsed
in his heart:

"Such music, such wedding music! What choir is it?"

