
---
title: 'Victory'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 15
  issue: 2
  page: 61
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



> Minneapolis Branch and friends of the Northwest join in grateful thanks and congratulations to you, Storey, Spingarn, Villard, and army of leaders, and friends who secured the splendid victory in Segregation fight. It is the most consoling and inspiring news received within a quarter century.    
> &nbsp;     
> The colored citizens of Denver and Colorado desire that the Denver Branch convey to you, Moorfield Storey, and associates their deepest gratitude and appreciation of the noble work and splendid victory won before the United States Supreme Court in the Segregation cases, the most important step toward world democracy since the Civil Rights Bill.

Messages like the above have come to us from many persons and places.

We are thankful; and the National Association for the Advancement of Colored People and <span class="crisis-title">The Crisis</span>, in turn, pause to raise their hats to one man who bore the burden in the heat of the day, initiated the fight against segregation, carried it victoriously up through the state courts, and filed a brief in the Supreme Court case---WILLIAM ASHBIE HAWKINS, the attorney of our Baltimore Branch. Nor do we forget the heroic efforts of our branches in Louisville and St. Louis.

As Moorfield Storey, our honored president says, this is the most momentous utterance of the Supreme Court since the Dred Scott decision.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Our Special Grievances (1918)](/Volumes/16/05/our_special_greivances.html)
* [The Next Step (1913)](/Volumes/06/02/next_step.html)
* [The Present (1917)](/Volumes/14/04/present.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [An Open Letter to Woodrow Wilson (1913)](/Volumes/05/05/open_letter.html)

<!-- Similar articles end here -->