
---
title: 'We Come of Age'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 1
  page: 25
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Five years ago this month the first number of <span class="crisis-title">The Crisis</span>
was issued. It was a very modest little edition consisting of one
thousand copies with twenty pages each. The total cost was fifty
dollars. This issue of <span class="crisis-title">The Crisis</span> consists of 35,000
copies of fifty-two pages each and will cost about two thousand dollars.
Between these two boundaries lies, as one may well believe, a history of
struggle, of hope and fear, of apprehension and triumph. From the
beginning <span class="crisis-title">The Crisis</span> has borne all of its expenses of
publication and paid all salaries except that of the editor. Last year,
when the stringency due to the war put the National Association for the
Advancement of Colored People in serious difficulties, <span class="crisis-title">The Crisis</span> assumed half the salary of the editor who had
hitherto been paid wholly by the Association. Today, on our Fifth
Birthday, we are able to announce with some pride and with genuine
satisfaction that at the beginning of our fiscal year, January 1, 1916,
<span class="crisis-title">The Crisis</span> will become a self-supporting business
institution, paying not only all expenses of publication but the full
salary of the editor. This is no small accomplishment for the
comparatively short period of time and we have to thank first of all not
ourselves, but our readers in every state in this Union and in the lands
oversea.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Truth and Beauty (1922)](/Volumes/25/01/truth_and_beauty.html)
* [Booming The Crisis (1914)](/Volumes/07/05/booming_crisis.html)
* [The New Crisis (1925)](/Volumes/30/01/new_crisis.html)
* [Join or Die (1914)](/Volumes/07/03/fightordie.html)
* [An Open Letter to Robert Russa Moton (1916)](/Volumes/12/03/open_letter.html)

<!-- Similar articles end here -->