
---
title: 'Woman Suffrage'
author: Du Bois, W.E.B.
date: May 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 1
  page: 29-30
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



This month 200,000 Negro voters will be called upon to vote on the
question of giving the right of suffrage to women. <span style="font-variant:small-caps;">The
Crisis</span>sincerely trusts that everyone of them will vote
*Yes.* But <span style="font-variant:small-caps;">The Crisis</span> would not have them go to the polls
without having considered every side of the question. Intelligence in
voting is the only real support of democracy. For this reason we publish
with pleasure Dean Kelly Miller's article against woman suffrage. We
trust that our readers will give it careful attention and that they will
compare it with that marvelous symposium which we had the pleasure to
publish in our August number. Meantime, Dean Miller will pardon us for a
word in answer to his argument.

Briefly put, Mr. Miller believes that the bearing and rearing of the
young is a function which makes it practically impossible for women to
take any large part in general, industrial and public affairs; that
women are weaker than men; that women are adequately protected under
man's suffrage; that no adequate results have appeared from woman
suffrage and that office-holding by women is "risky."

All these arguments sound today ancient. If we turn to easily available
statistics we find that instead of the women of this country or of any
other country being confined chiefly to childbearing they are as a
matter of fact engaged and engaged successfully in practically every
pursuit in which men are engaged. The actual work of the world today
depends more largely upon women than upon men. Consequently this man-ruled world faces an astonishing
dilemma: either Woman the Worker is doing the world\'s work successfully
or not. If she is not doing it well why do we not take from her the
necessity of working? If she is doing it well why not treat her as a
worker with a voice in the direction of work?

The statement that woman is weaker than man is sheer rot: It is the same
sort of thing that we hear about "darker races" and "lower classes."
Difference, either physical or spiritual, does not argue weakness or
inferiority. That the average woman is spiritually different from the
average man is undoubtedly just as true as the fact that the average
white man differs from the average Negro; but this is no reason for
disfranchising the Negro or lynching him. It is inconceivable that any
person looking upon the accomplishments of women today in every field of
endeavor, realizing their humiliating handicap and the astonishing
prejudices which they face and yet seeing despite this that in
government, in the professions, in sciences, art and literature and the
industries they are leading and dominating forces and growing in power
as their emancipation grows,---it is inconceivable that any fair-minded
person could for a moment talk about a "weaker" sex. The sex of Judith,
Candace, Queen Elizabeth, Sojourner Truth and Jane Addams was the merest
incident of human function and not a mark of weakness and inferiority.

To say that men protect women with their votes is to overlook the flat
testimony of the facts. In the first place there are millions of women
who have no natural men protectors: the unmarried, the widowed, the
deserted and those who have married failures. To put this whole army
incontinently out of court and leave them unprotected and without voice in political life is more than unjust, it is a crime. 

There was a day in the world when it was considered that by marriage a woman lost all her individuality as a human soul and simply became a machine for making men. We have out-grown that idea. A woman is just as much a thinking, feeling, acting person after marriage as before. She has opinions and she has a right to have them and she has a right to express them. It is conceivable, of course, for a country to decide that its unit of representation should be the family and that one person in that family should express its will. But by what possible process of rational thought can it be decided that the person to express that will should always be the male, whether he be genius or drunkard, imbecile or captain of industry? The meaning of the twentieth century is the freeing of the individual soul; the soul longest in slavery and still in the most disgusting and indefensible slavery is the soul of womanhood. God give her increased freedom this November! 

Mr. Miller is right in saying that the results from woman suffrage have as yet been small but the answer is obvious: the experiment has been small. As for the risks of allowing women to hold office: Are they nearly as great as the risks of allowing working men to hold office loomed once in the eyes of the Intelligent Fearful? 

