
---
title: 'Smith Jones'
author: Du Bois, W.E.B.
date: Apr. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 6
  page: 22
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



A curious thing happened at Harvard last fall. A boy walked from Mississippi and sought to enter the college because he wanted to learn to write.

"Certainly. Why not?" asks the reader.

Well---he was black.

"Oh," says the reader, as the dean of the college said, "why didn't he go to an industrial school?"

"Because," said Smith Jones, "I want to study literature and become a poet."

"Why not become a carpenter?" 

"Because I don't want to."

"Is not a trade honorable?"

"Yes; but the trade I want is writing in numbers."

"But can you write?"

Now, the strange thing is that Smith Jones has the gift of song. "My song floats softly up to thee,"
he sings to Ethiopia in verses that halt yet have the feel of poetry---not that song is to be compared with potatoes---for potatoes are the end of song (or is song the end of potatoes?). At any rate, why shouldn't such a boy be heralded, pushed onward and encouraged? He aspires. Why does not America cry Hurrah! The reason lies deep, but the reason is there, and it exercises itself again and again. "There is one place in this land for black men. We want no exceptions. Exceptions make the Negro problem." Curious. How like to well-known echoes of the past. How like, too, sounds Smith Jones' life; he was born in a Mississippi cotton field; he supported his mother, sent his sister to school. Then at last came his chance. He got to Louisville and worked at service. Then he printed his Ode to Ethiopia and came to Indianapolis. There the *Star* published his "Ode to the Soldiers' and Sailors' Monument" which James Whitcomb Riley and other writers praised. Yet when they saw the black face of the poet they sighed. It was no use to try there, so the black boy started for Harvard with thirty-four cents in his pocket and a bundle of "Odes to Ethiopia!" He rode on engines, skulked, starved and walked, and finally was arrested in Worcester, Mass., a dirty, black, redeyed vagabond, and sent to the work-house. "I am a poet," he protested, "not a tramp;" but the guard dropped his letter to the editors in the waste paper basket and grinned. Finally, on a dark night he came to Harvard Square. He saw its dim trees and scattered buildings and, venturing in the yard, was promptly arrested again and clapped into jail. Oh! our brave and efficient police!

This time his judge was a man. While his jailers were proving beyond peradventure that any man whose whole luggage consisted of a bag of poems was either a vagabond or a fool, the judge was reading his poems. So he went free, "on probation." At last a man came forward and put Jones into the Boston Latin School, where he is now preparing for Harvard.

