
---
title: 'The Truth'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 6
  page: 21-22
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There is to-day a tendency among colored people and among their earnest friends to tell the half-truth concerning the situation of the colored people and to condemn those who seek to tell the whole truth. Such people rightly herald the recent peonage decision of the Supreme Court, they commend the saving of Pink Franklin's life, they point to many other instances of help and good will on the part of Southern whites.

These things are true and deserve wide currency; to conceal or neglect them would be wrong. But they are not the whole truth, and when by silence or intimation the world is given to believe by such well-meaning persons that they are the whole truth, a great and dangerous injustice is perpetrated. With the peonage decision we must not forget the shame of the Berea decision; with the saving of one life we cannot forget the widespread and crying injustice of Southern courts and methods of punishment; with the fact of the rise here and there of Southern white friends of the black men. it is a dangerous falsehood to overlook the tireless and daily assault of enemies of humanity like Judge Harris Dickson.

But where is the harm?  many think. If we tell the good things, will not the good things multiply and the hateful things die? No. It is a dangerous thing to dally with the truth. Some of the greatest catastrophes in history have come because the mass of men have been deceived and misled as to the truth of conditions by timid, well-meaning persons, who, knowing the awful facts, suppressed them systematically and spread the sweet and gentle lie.

There are friends of black folk in this land. There is continual advance in human sympathy. There is an awakening in the white South on the race problem. All that is true. It is also true that the Negro American today faces The Crisis of his career; race prejudice is rampant and is successfully overcoming humanitarianism in many lines, and the determination of the dominant South to beat the black man to his knees, to make him a docile ignorant beast of burden, was never stronger than to-dav. This is the truth. Let us tell the truth, unpleasant though it be, and through the truth seek freedom. There is no other way.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [A Statement (1919)](/Volumes/19/01/statement.html)
* [The Truth (1912)](/Volumes/05/02/truth.html)
* [Pink Franklin (1911)](/Volumes/01/04/pink.html)
* [Starvation and Prejudice (1911)](/Volumes/02/02/starvation_and_prejudice.html)
* [The Next Step (1913)](/Volumes/06/02/next_step.html)

<!-- Similar articles end here -->