
---
title: 'The Writer'
author: Du Bois, W.E.B.
date: Apr. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 6
  page: 20-21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The death of Frances Watkins Harper calls our attention to the literature of American Negroes. Mrs. Harper was born in Baltimore in 1825. Her active life, beginning with her first published book of poems, covered over sixty years of stirring history, from the Compromise of 1850 down to Mr. Taft's inaugural address. She was associated with all the great leaders of the abolition cause and has lectured to hundreds of audiences throughout the land.

It is, however, for her attempts to forward literature among colored people that Frances Harper deserves most to be remembered. She was not a great singer, but she had some sense of song; she was not a great writer, but she wrote much worth reading. She was above all, sincere. She took
her writing soberly and earnestly; she gave her life to it, and it gave her fair support. She was a worthy member of that dynasty, beginning with dark Phyllis in 1773 and coming on down past David Walker, Wells Brown, Nell, Whitman and Williams, down to Dunbar, Chesnuit and Braithwaite of our day.

To the young colored American Frances Harper leaves a lesson. Here is a nation whose soul is still dumb, yet big with feeling, song and story. What are we doing to develop writers to express this wealth of emotion fitly? Very little. We have among ten millions to-day one poet, one novelist and two or three recognized writers of articles and essays. That is all.

Here is a tremendous field for improvement, and if in the next six months <span style="font-variant:small-caps;">The Crisis</span> receives the same remarkable encouragement as in the past we hope to have ready for the beginning of our second year's work a matured plan for encouraging young writers to follow the hallowed footsteps of Frances Watkins Harper.
