
---
title: 'Employment'
author: Du Bois, W.E.B.
date: Sep. 1932
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 39
  issue: 9
  page: 299
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Our educational problem has two difficulties: first, the great mass of Negroes are not receiving proper and adequate common school training. It means today that we are educating an aristocracy of learning, but we are not using it or allowing it to be used to educate the masses of the people.

In the Northern States, where two million Negroes live, it is difficult for the best trained Negroes to find employment in the public schools unless the Negro community accepts separate and segregated school systems which are usually more poorly equipped and more inefficiently conducted than the white schools, not to mention the grave surrender of principle. In the South, the well-trained Negro teacher has to contend with poorly supported separate schools at low wages, together with a personal treatment that often saps manhood and independent thinking. Thus, a great field of employment into which masses of Negro college men and women with one or more years of technical training could easily be absorbed, actually invites now only a few thousand.

This increases the problem of earning a living for the average college-bred Negro. If he can take a course in professional study, there is a chance for him as physician, dentist, lawyer, pharmacist and engineer. But these fields are limited by the poverty of the Negro masses. These masses are still largely excluded from all but the lower positions in the general technique of industry.

The average Negro college graduate, therefore, is not a man prepared to enter into a paying field of employment. He is simply one who, by his general intelligence, and by his knowledge of modern civilization, is in a better position than most people, resolutely to attack his economic and social problem. He has opportunity to become the trained fighting wedge to advance the place of black folk in modern civilization by using his brains so as to force himself to a position where he can work and achieve and make a place for the millions of his fellows who straggle on behind.

The question is, however, how far is the college which the Negro attends, black and white, arranging its program so as to train men for this kind of work? It must be confessed that the outlook here is poor. The white colleges are not doing it for white men, much less for their Negro students. And the colored colleges, for the most part, continue slavishly to pattern their curricula after the white colleges. So far as they are compelled to do this in order to maintain their academic standing, they have some excuse; but the chance of varying and enlarging their programs has been greatly increased in the last few years. Above all, the opportunity for inculcating spiritual freedom, broad vision, independence of thought and willingness to sacrifice, is as large as it is untouched. We Negroes have got the material for higher training. We have got the will to send it to college and are finding by infinite pains the funds to support it. But we have not yet got the spirit and vision to train it aright.

