
---
title: 'The Last Word in Politics'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 5
  issue: 1
  page: 184-186
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---





Before another number of <span class="crisis-title">The Crisis</span> appears the next President of the United States will have been elected. We have, therefore, but this last word to colored voters and their friends. 

Those who have scanned our advertising pages this month and last have noted an unusual phenomenon: the three great political parties have in this way been appealing to the colored vote for support. They have done this out of no love to this magazine, but because they needed the publicity which this magazine alone could give and because they knew that our news columns and editorial pages were not for sale. We commend these advertisements to our readers' notice. They are the last word of political appeal and they are undoubtedly sincere. 

Taking them now and comparing and weighing them, and what is the net result? The Republican party emphasizes its past relations with the Negro, the recent appointments to office, and warns against the disfranchisement and caste system of the Democratic South. The weak point in this argument is that without the consent of Republican Presidents, Republican Congresses and a Republican Supreme Court, Southern disfranchisement could not survive a single day. 

The Progressive party stresses its platform of social reform, so admirable in many respects, and points to the recognition given in its party councils to the Northern Negro voter. The weak point here is the silence over the fact that Theodore Roosevelt, the perpetrator of the Brownsville outrage, has added to that blunder the Chicago disfranchisement and is appealing to the South for white votes on this platform. 

The Democratic party appeals for colored votes on the ground that other parties have done and are doing precisely the things that the Democratic party is accused of doing against the Negro, and this in spite of the fact that these parties receive the bulk of the Negro vote. If, therefore, the Negro expects Democratic help and support, why does he not give the Democrats his vote? The weak point here is that the invitation is at best negative; the Negro is asked to take a leap in the dark without specific promises as to what protection he may expect after the Democrats are in power.

In none of these cases, therefore, is the invitation satisfactory. Nevertheless, because the Socialists, with their manly stand for human rights irrespective of color, are at present out of the calculation, the Negro voter must choose between these three parties. He is asked virtually to vote. 

1. For a party which has promised and failed. 
2. For a party which has failed and promised. 
3. For a party which merely promises. 
 
We sympathize with those faithful old black voters who will always vote the Republican ticket. We respect their fidelity but not their brains. We can understand those who, despite the unspeakable Roosevelt, accept his platform which is broad on all subjects except the greatest—human rights. This we can understand, but we cannot follow. 

We sincerely believe that even in the face of promises disconcertingly vague, and in the face of the solid caste-ridden South, it is better to elect Woodrow Wilson President of the United States and prove once for all if the Democratic party dares to be Democratic when it comes to black men. It has proven that it can be in many Northern States and cities. Can it be in the nation? We hope so and we are willing to risk a trial. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The N.A.A.C.P. and Parties (1924)](/Volumes/28/05/naacp_and_parties.html)
* [The Election (1914)](/Volumes/09/02/election.html)
* [Mr. Hughes (1916)](/Volumes/13/01/mr_hughes.html)
* [Prejudice (1927)](/Volumes/34/09/prejudice.html)
* [Every Four Years (1920)](/Volumes/19/06/every_four_years.html)

<!-- Similar articles end here -->