
---
title: 'The Second Birthday'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 5
  issue: 1
  page: 27-28
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



It is natural that there should be many misapprehensions concerning the origin of <span class="crisis-title">The Crisis</span> as well as its object. Every man with a cause longs to voice his belief. Most men, however, like the editor of this magazine, are held back by a very genuine doubt as to whether the public will recognize any worth in the proposed message. They know---or they think they know---that when the message is voiced, and the world realizes its full import, it will welcome and help actively in its spread. 

The problem is then how to begin, how first to spread the message. Capital must be had for the launching of such an enterprise, but how may one raise it and whence? It seemed to the editor of <span class="crisis-title">The Crisis</span> in earlier years that the benevolent rich might be approached with such a proposition. He forgot that the benevolent are besieged with schemes of all sorts and have little time or ability to judge a matter the justification of which lies in the far future. They are used to helping the thing that has already proven its worth. 

A second method would be to furnish the necessary capital oneself and thus bridge the starving period. Now the capital that an American colored man, working at "colored" wages, can afford to put into a periodical of purpose is small. <span class="crisis-title">The Crisis</span> is a small magazine run on extremely economical lines with a small---much too small---working force; but <span class="crisis-title">The Crisis</span> costs 
over $1,000 a month to publish and distribute. Persons proposing to start small magazines should remember this. Yet an earnest agent who is about to buy twenty-five copies a month writes us: "I will handle your magazine if you will promise to enlarge it soon!" 

The push of the unspoken thought that demands utterance is strong. So, despite cost and trouble, the editor attempted seven years ago a small magazine-like weekly, published at Memphis, Tenn., and called *The Moon*. The editor gave all his savings, some twelve hundred little dollars, into the hands of an ambitious young printer, turned the whole business responsibility over to him and furnished his services as editor free. The result was a flash of popularity, a year of unsystematic struggle, and then the clear realization that either the editor must give his whole time and help in the business management or give up. Now as the editor was earning his daily bread as well as capital for *The Moon* by his work as teacher, giving this up seemed impossible and the *Moon* set. 

Immediately friends came forward and said: "But we must have such a periodical as you sought to give us. Suppose we help you bear the expense?" The result was a miniature magazine called *The Horizon*, published for nearly three years in Washington, D.C., by men who themselves paid the deficit out of their shallow pockets. 

Here we faced a new problem. Scarcely 500 copies of the magazine were sold monthly, and, as the young manager flatly put it, it seemed as it "the people don't want it." 

The problem was serious. If it was true that 10,000,000 serfs did not want a single untrammeled champion of their larger rights and ambitions, then the problem of those rights and ambitions was even graver than the editor had dreamed. But the editor doubted. Was it proven that the colored folk did not want such a magazine? Had they been given a fair chance to decide? 

While these questions were being pondered the National Association for the Advancement of Colored People was formed and the editor was asked to become director of publicity and research. 

Articles in this number show how difficult it is to try to get publicity on the Negro problem in the regular periodical press unless the black man is vilified and traduced. The editor therefore said to his board of directors: "If we are to have publicity, it must be through an organ of our own." The board hesitated. They knew far better than the editor that magazines cost money, and despite legends to the contrary, they had almost no money. Nevertheless, the necessity of some organ was great, and with many misgivings the board authorized an expenditure of $50 a month for a small monthly. 

The editor will not soon forget that first number of <span class="crisis-title">The Crisis</span>. William English Walling suggested the name; Mary Dunlop Maclean saw to the "makeup;" Robert N. Wood took the printing contract. But it was the editor alone, looking out on the forest of roofs of lower Broadway, who asked and asked again the momentous question: "*Dare I order 500 copies --- or 1,000?" And when in a fit of wild adventure he ordered 1,000 copies printed he felt like Wellington before Waterloo. Month before last <span class="crisis-title">The Crisis</span> in a fit of parsimony ordered but 20,000 copies printed. The result was that orders for over 1,000 copies could not be filled, so that last month we returned to our regular 22,000 edition. When we tell facts like these, people imagine large capital and dividends in connection with our magazine. Not so. Not a cent of capital has been invested in the magazine, except that the National Association for the Advancement of Colored People has furnished the services of the editor free of charge. This means that <span class="crisis-title">The Crisis</span> is not quite paying expenses, for it could not to-day, with its present income and expense, afford to pay an editor. 

Can, now, a magazine like <span class="crisis-title">The Crisis</span> ever become entirely self-supporting? Many of our friends doubt this. They point to the graveyard of ambitious and worthy ventures---the *Colored American* and the *Voice of the Negro* to name the latest---and say the American Negro has not yet reached the place where he appreciates a magazine enough to pay for its support. We doubt this assertion. We actually sell each month over 21,500 magazines. We are sure that if we could get <span class="crisis-title">The Crisis</span> to persons who want it we could to-day sell 50,000. The problem of distribution is, however, extremely difficult. We cannot use the ordinary channels of distribution, but must have our own agents, and these agents must be largely missionaries in a crusade, because it hardly pays them to give their time to one magazine. 

When once <span class="crisis-title">The Crisis</span> can reach a circulation of 50,000 its permanence and independence are assured. Until it can there must always be the element of doubt as to whether such a magazine can command the requisite support. We believe it can. The experience of the first two years is more than encouraging. The Crisis has to-day the largest net circulation of any periodical devoted to the Negro race in America. If the growth in the next two years parallels the past, then one at least of our problems will be solved---the problem of publicity. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Join or Die (1914)](/Volumes/07/03/fightordie.html)
* [Truth and Beauty (1922)](/Volumes/25/01/truth_and_beauty.html)
* [The Gall of Bitterness (1912)](/Volumes/03/04/gail_of_bitterness.html)
* [We Come of Age (1915)](/Volumes/11/01/we_come_of_age.html)
* [Booming The Crisis (1914)](/Volumes/07/05/booming_crisis.html)

<!-- Similar articles end here -->