
---
title: 'Justice'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 3
  page: 112
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



A gentleman, unnamed, but with a card that assured us that he represented the Department of Justice at Washington, has called upon <span class="crisis-title">The Crisis</span>. He said he was looking for "two German girls" said to be employed here, and he incidentally read us a lecture on loyalty and told us that the visit was "confidential." 

We do not know what this gentleman really represents and we do not particularly care, but we do remember with some misgivings that it was the U.S. Department of Justice which discovered that Negroes were migrating from the South in order to vote against Woodrow Wilson in the late election. It was this same Department of Justice which discovered German plots among Negroes of the South, raising a furor which was promptly drowned out by loud reassurances from the white South itself. We also remember with still graver misapprehension that it is this same Department of "Justice" that is unable to find upon the map of the United States certain places called Waco and Memphis, and that it is presumably more interested in Home Rule in Ireland than it is in lynching and disfranchisement in the United States. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Flipper (1922)](/Volumes/24/05/flipper.html)
* [The Liberal South (1921)](/Volumes/21/06/liberal-south.html)
* [Officers (1917)](/Volumes/14/02/officers.html)
* [Our Special Grievances (1918)](/Volumes/16/05/our_special_greivances.html)
* [Help Us to Help (1918)](/Volumes/16/04/help_us.html)

<!-- Similar articles end here -->