
---
title: 'Memphis or East St. Louis?'
author: Du Bois, W.E.B.
date: Jan. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 3
  page: 113-114
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


We seem to hear four voices screaming above the mobs of Memphis and East St. Louis---Why will Negroes be Scabs, Why will Negroes Stay in the South, How Can We Stop Negro Migration, Where Can Negroes Be Treated Justly?

We believe we can answer all these questions and for the first we quote a letter of Charles Augustono, a colored bricklayer of Camden, N. J.:

> I am a member of the Bricklayer, Mason and Plasterers' International Union of America. On May 10, 1917, I was at Glassboro, N.J., to a job contracted by James Steward Company of New York City and secured a position there. I started work at 12:30 P. M. The steward on the job demanded my working card. He looked it over and O. K.'d it, notifying me to pay privilege dues of thirty-five cents as my card was from another local farm, 37 Easton, Pa., Transfer No. 9 of Trenton, N. J. This job is controlled by Union No. 7 of Camden, N. J., B.M. and P.I.U. of America.    <p> When I started to work the rest of the members of the job stopped and refused to work with me. Then the boss handed me my discharge, telling me the men would not work with me, after I had showed the steward a good finance card. The trouble is that I have paid for my rights and am not getting them on account of my color. As you know, color always keeps us from making the living we ought to make.

It is this attitude of many labor unions and Northern working men who make the mobs of East St. Louis, that keeps many Negroes living among Memphis lynchers. But it cannot keep them all. The stream of migration is large. It is going to be larger. The hand of the government can be depended on in East St. Louis to put down mobs; it cannot be depended on in Memphis. If, then, the South wants Negro workingmen, as the Savannah *Morning News* says: "The one sure way to keep them in the South is to accord them better treatment." If it wants food raised in the South it must support agricultural education among Negroes. Yet, as the Colored Workers' Conference at Fort Valley recently said to the state officials:

> It must be known to you, gentlemen, that if the white people need an agricultural school in each of the Congressional districts of Georgia, Negroes who operate half the farms in Georgia, who live in a greater per cent of the population in the country, and who furnish 85 per cent of the farm labor in Georgia, must need such agricultural training a great deal more. Still, regardless of this greater need and regardless of the fact that the support of these eleven white schools comes out of the general coffers of the state to which Negroes contribute in taxes, not one dollar does the state give to such agricultural education for Negroes.

It is characteristic of Georgia to call on the Federal Government to stop migration and for other Southerners to suggest that Negroes drafted for military service be put to farm work.

We warn the South that any attempt to draft the Negroes into the employ of private persons will be disastrous and we call the attention of the U. S. Government to the monstrous discrimination which it is permitting in Charleston, S. C.

Charleston is a city noted for the efficiency of its colored seamstresses. Yet, recently, when the Navy Yard called for 1,000 seamstresses it sought and still seeks to discriminate against colored women.

It is lynching, forced labor, and discrimination that is sending the Negro North. When he comes North he may find mobs and hostile labor unions, but he will also find the law and the law will be enforced.

