
---
title: 'Promoting Race Prejudice'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 3
  page: 112
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Race prejudice is not so much a matter of startling deeds as of petty insinuations. The New York Community Chorus, for instance, has sent broadcast a statement which says that "the chorus has sung every week since its organization, June 9, 1916, and has invited everybody freely to sing with it,"—to which the editor of <span class="crisis-title">The Crisis</span> was forced to reply that the colored people of New York had not been invited nor, indeed, allowed to sing with this chorus.

Mr. Theodore Roosevelt showed his trophies to the Oyster Bay Home Guard recently. Among them were some gifts from the Kaiser. Said Mr. Roosevelt: "I got them when he was a white man." To which Mrs. H. M. Godfrey replies in the New York *Times* that none of the rough-riders "would have ever lived to tell the tale but for the colored 9th and 10th cavalry regiments," who were not "white men."

The *Official Bulletin*, published by George Creel for the government, cannot forget the usual slur when it suggests as a commencement day subject: "The Character of the Negro as a Soldier *When Well Led*."

Finally, note this from the New York *Evening Post*, speaking of the questions in the Draft circular: "As to your race state whether 'Caucasian,' 'Mongolian,' 'negro,' 'Malayan,' or 'Indian.'" Even the *Literary Digest* cannot quite stomach this illogic and prints it this way: "Caucasian, Mongolian, Negro, Malay or Indian."

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Hayes (1927)](/Volumes/33/03/hayes.html)
* [Y.M.C.A (1914)](/Volumes/09/02/ymca.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Promotion of Prejudice (1911)](/Volumes/02/05/promotion.html)
* [Mr. Roosevelt (1912)](/Volumes/04/05/mr_roosevelt.html)

<!-- Similar articles end here -->