
---
title: 'The Black Mother'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 5
  issue: 2
  page: 78
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The people of America, and especially the people of the Southern States,	have felt so
keen an appreciation of the qualities of motherhood in the Negro that they have proposed erecting a statue in the National Capital to the black	mammy. The black nurse of slavery days may receive the tribute of enduring bronze from the master class.

But this appreciation of the black mammy is always of the foster mammy, not of the mother in her home, attending to her own babies. And as the colored mother has retreated to her own home, the master class has cried out against her. "She is thriftless and stupid," the white mother says, "when she refuses to nurse my baby and stays with her own. She is bringing her daughter up beyond her station when she trains her to be a teacher instead of sending her into my home to act as nursemaid to my little boy and girl. I will never enter her street, heaven forbid. A colored street is taboo, and she no longer deserves my approval when she refuses to leave her home and enter mine."

Let us hope that the black mammy, for whom so many sentimental tears have been shed, has disappeared from American life. She existed under a false social system that deprived her of husband and child. Thomas Nelson Page, after---with wet eyelids---recounting the virtues of his mammy, declares petulantly that she did not care for her own children. Doubtless this was true. How could it have been otherwise? But just so far as it was true it was a perversion of motherhood.

Let the present-day mammies suckle their own children. Let them walk in the sunshine with their own toddling boys and girls and put their own sleepy little brothers and sisters to bed. As their girls grow to womanhood, let them see to it that, if possible, they do not enter domestic
service in those homes where they are unprotected, and where their womanhood is not treated with respect. In the midst of immense difficulties, surrounded by caste, and hemmed in by restricted economic opportunity, let the colored mother of to-day build her own statue, and let it be the four walls of her own unsullied home.

