
---
title: 'The Truth'
author: Du Bois, W.E.B.
date: Jun. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 5
  issue: 2
  page: 76--77
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



That this nation and this world needs is a Renaissance of reverence for the truth. If <span style="font-variant:small-caps;">The Crisis</span> stands for one thing above others, it is emphasis of this fact, and it is here that we have to differ with some of our best friends. We are here to tell the essential facts about the condition of the Negro in the United States. Not all the facts, of course—one can never tell everything about anything. Human communication must always involve some selection and emphasis. Nevertheless. in such selection and emphasis there can be two attitudes as different as the poles. One attitude assumes that the truth ought to be as one person or race wants it and then proceeds to make the facts prove this thesis. The other attitude strives without undue assumption of any kind to show the true implication of the existing facts. The first attitude is that of nearly all the organs of public opinion in the
United States on the Negro problem. They have assumed, and for the most part firmly believe, that the Negro is an undesirable race destined to eventual extinction of some kind. Every essential fact and situation is therefore colored and grouped to support this thesis, and when stubborn facts appear that simply will not support this thesis there is almost complete silence.

Few Americans, many Negroes, do not realize how widespread and dangerous this disregard of truth in relation to the Negro has become and how terrible is its influence. Sir Harry Johnston, a great Englishman, was recently invited to furnish his views on the Negro to a popular American magazine. When these articles were written and seemed favorable to the black man the magazine paid for them and suppressed them. Jane Addams was asked to write on the Progressive party for *McClure's Magazine*. Her defense of Negro rights was, with her consent, left out, and appeared in <span style="font-variant:small-caps;">The Crisis</span> last month. Charles Edward Stowe offered his "Religion of Slavery" to the Outlook. It was returned not as untrue but "unwise."

Many persons who know these things defend this attitude toward the truth. They say when matters are bad do not emphasize their badness, but seek the encouraging aspects. If the situation of the Negro is difficult strive to better it, but do not continually harp on the difficulties. The trouble with this attitude is that it assumes that everybody knows the truth; that everybody knows the terrible plight of the black man in America. But how do they know it when the organs of public information are dumb? Would anybody ever suspect by reading the *Outlook* that educated property-holding Negroes are disfranchised? Would any future generation dream by reading the *Southern Workman* that 5,000 Negroes had been murdered without trial during its existence? What right have we to assume intuitive and perfect knowledge of
truth in this one problem, while in myriads of other human problems we bend every energy and strain every nerve to make the truth known to all? Is there not room in the nation for one organ devoted to a fair interpretation of the essential facts concerning the Negro! There certainly is, even if the silence and omissions of the public press were quite unconscious; but how much more is the need when the misrepresentation is deliberate! In the recent Congress of Hygiene in Washington there was sent from Philadelphia a chart alleging in detail the grossest and most unspeakable immorality against the whole Negro race. Colored folk led by F.H.M. Murray protested. The secretary immediately had the offensive lie withdrawn and said: "I am sorry the chart ever found a place there, but I should be more sorry if the colored people had not protested." Here is the attitude of the honest man: "I am sorry that colored Americans are treated unjustly, but I should be more sorry if they did not let the truth be known."

Granted that the duty of chronicling ten mob murders a month, a dozen despicable insults and outrages, is not pleasant occupation, is the unpleasantness the fault of <span style="font-variant:small-caps;">The Crisis</span> or of the nation that perpetrates such dastardly outrages? "Why," said one of our critics, "if I should tell my white guests of the difficulties, rebuffs and discouragements of colored folk right here in Boston, they would go away and never visit us again. If, however, I tell how nicely the Negroes are getting on. they give money." Yes! And if your object is money you do right, but if your object is truth, then you should not only tell your visitors the truth but pursue them with it as they run.

True it is that this high duty cannot always be followed. True it is that often we must sit dumb before the golden calf, but is not this the greater call for a voice to cry in the wilderness, for reiterated declaration that the way of the Lord is straight and not a winding, crooked, cunning thing?

