
---
title: 'K.K.K.'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1922
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 25
  issue: 1
  page: 11
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



> Sept. 15, 1922.<p>Please enter subscription to your magazine <span class="crisis-title">The Crisis</span>for one year, mailing same to address given below. Post Office Money Order for $1.50 enclosed.<p>Yours truly,<p>J.J. Murphy,<p>Kleagle, Knights of the Ku Klux Klan, P. O. Box 612, Birmingham, Ala. 

We have received few subscriptions with more pleasure than this. We have perhaps neglected our offer to comment upon the K.K.K. because it has always seemed to us so ridiculous an organization. But now that we may speak to them, as it were, face to face, we would like to say plain words from time to time. *First*, the Klan is ridiculous; it is Mumbo Jumbo, child's play, silly parading, calculated to attract idiots and criminals. *Secondly*, it is cowardly; it hides and masks and sneaks by night; it does not dare to stand out in the open; it is afraid and ashamed of itself; and there seems to be no connection between what it does and what it says, between what it professes and what it supports. *Thirdly*, it is powerful. Its very appeal and methods give it power in that part of the land where ignorance is most deep seated. It has triumphed in elections, sweeping Texas, electing a governor in Georgia, showing its fangs elsewhere; but notwithstanding all this, it is, for the better South, the most hopeful mob in years. It is going to drive the "best friends of the Negro," the pussyfooters and compromisers, the sincere well-wishers, out into the open. For 50 years the South has tried to build up a civilization on lawlessness and "nigger" hating, and at the same time it has tried by excuses and smooth words to hide its deeds from its own better self, and from the outer world. Today the Ku Klux Klan comes as an open, clear avowal that the Worse South proposes to set up a government ruled by secret midnight marauders whose object is to murder, insult and disfranchise Negroes, Jews, Catholics and anybody else whom any clansman hates or fears. Against this organization, sooner or later, the decent white South must take a stand. It must take it not simply in words with "ifs" and "ands" but with straight-out, manly determination backed, by word and deed, publicly to unmask the cowards, to stop lynching, lawlessness and mobs, and to defend the rights of American citizens. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Ku Klux Klan (1921)](/Volumes/23/01/ku-klux-klan.html)
* [Social Equality (1928)](/Volumes/35/02/social_equality.html)
* [Libelous Film (1921)](/Volumes/22/03/libelous_film.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)

<!-- Similar articles end here -->