
---
title: 'Truth and Beauty'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1922
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 25
  issue: 1
  page: 7-8
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



On November, 1910, <span class="small-caps">The Crisis</span> was born. With this issue, November, 1922, we are completing our twelfth year and we pause to thank all those who have made our long and fairly successful career possible. We have for the future both promises and apologies. First, we want to apologize to the large number of people who subscribe indirectly to <span class="small-caps">The Crisis</span> and either do not get their subscriptions or have them delayed. It can be easily seen that this is not wholly the fault of  <span class="small-caps">The Crisis</span>:  <span class="small-caps">The Crisis</span> cannot fulfil a subscription until it receives it or at least receives notice that it has been paid. On the other hand, many subscriptions are taken in the drives for memberships of the N.A.A.C.P. and this has always been a great and valuable source of support for <span class="small-caps">The Crisis</span>. When, however, subscriptions are paid thus indirectly, first to a solicitor, then handed to a captain, then slowly collected by a local secretary, then forwarded to the national secretary, and finally handed to  <span class="small-caps">The Crisis</span> business manager,---all this involves much delay and several possibilities of mistake. Anyone thus subscribing for  <span class="small-caps">The Crisis</span> indirectly should always and simultaneously notify  <span class="small-caps">The Crisis</span> office of the facts. If there is anyone who having thus subscribed has not received  <span class="small-caps">The Crisis</span> we shall be only too glad to learn the facts and make all reparation. 

So much for apology. Now to our muttons. <span class="small-caps">The Crisis</span> has always stood for Truth,---for the Truth when it is bitter, because we believe this is the only path to reform; for the Truth when it is sweet, for that heartens all. We shall continue to stand thus for the Truth. In addition to this we want to increase that part of our mission which, while not neglected, has had too little attention in the past, and that is the work of propagating and encouraging Beauty. We Negroes have gone fast forward in economic development, in political and social agitation; and we are likely to forget that the great mission of the Negro to America and the modern world is the development of Art and the appreciation of the Beautiful. The esthetic life of black folk is likely to be choked---not by toil, for they are gifted with that divine laziness that will rest and dream in spite of laws and lash and silly money; but with the over-emphasis of ethics to meet the Puritans round about who conceal their little joys and deny them with crass utilitarianism. 

Why even our song---that vivid burst of sorrow burnt with joy---our love of life, the wild and beautiful desire of our women and men for each other---all, all this sinks to being "good" and being "useful" and being "white." 

<span class="small-caps">The Crisis</span> wishes by picture and drawing, by fiction, essays, poetry, by the organization of a Negro Institute of Literature and Art, to increase, nourish and encourage the Beautiful among Negroes and among Americans. As a beginning of this work for our New Year, we have the honor to announce a Christmas cover by Henry O. Tanner. And as a second step the Delta Omega Chapter of the Alpha Kappa Alpha Sorority at Virginia Normal and Industrial Institute, Petersburg, Va., offers through <span class="small-caps">The Crisis</span> a prize of fifty dollars for the best short story written by a Negro student. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Join or Die (1914)](/Volumes/07/03/fightordie.html)
* [We Come of Age (1915)](/Volumes/11/01/we_come_of_age.html)
* [Booming The Crisis (1914)](/Volumes/07/05/booming_crisis.html)
* [The Second Birthday (1912)](/Volumes/05/01/second_birthday.html)
* [The Gall of Bitterness (1912)](/Volumes/03/04/gail_of_bitterness.html)

<!-- Similar articles end here -->