
---
title: 'The House of the Black Burghardts'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 4
  page: 133-134
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


If one slings out the Northern neck of Manhattan and flies to the left of the silver Sound, one swoops in time into the Golden River; and dodging on this sinuously, now right, now left, one comes after a hundred miles of lake, hill and mountain, in the Old Bay State. Then at the foot of the high Metacomet that takes a solemn decision: left is sweet, old Sheffield; but pass it stolidly by and slip gently right into tiny South Egremont which always seems to. There—where right again and slope the Egremont Plain and the House of the Black Burghardts.

It is the first home that I remember. There my mother was born and all her nine brothers and sisters. There perhaps my grandfather was born, although that I do not know. At any rate, on this wide and lovely plain, beneath the benediction of grey-blue mountain and the low music of rivers, lived for a hundred years the black Burghardt clan. Up and to the east on a hill of rocks was Uncle Ira; down and to the south was Uncle Harlow in a low, long, red house beside a pond—seas, house of secret passes, sudden steps, low, narrow doors and unbelievable furniture. And here right in the center of the world was Uncle Waller, as Grandfather Othello was called.

It was a delectable place---simple, square and low, with the great room of the fireplace, the flagged kitchen, half a step below, and the lower wood-shed beyond. Steep, strong stairs led up to Sleep, while without was a brook, a well and a mighty elm. At most was I born there myself—but Alfred Du Bois and Mary Burghardt honeymooned a year in town and then brought me as a baby back to Egremont Plain.

I left the home as a child to live in town again and go to school. But
for furtive glimpses I did not see the house again for more than a quarter century. Then riding near on a chance journey I suddenly was home-sick for that house. I came to the spot. There it stood, old, lonesome, empty. Its windows eyes stared blindly on the broad, black highway into New York. It seemed to have shrunk timidly into itself. It had lost color and fence and grass and its sister left and down the road and to the homes were gone---the right its gone with no stick nor stone to mark their burial.

From that day to this I desperately wanted to own that house for no earthly reason that sounded a bit like sense. It was 130 long miles from my work. It was decrepit almost beyond repair save that into its tough and sturdy timbers the Black Burghardts had built so much of their own dumb pluck that---
"Why the stairs don't even creak!" said She, climbing gingerly aloft.

But I fought the temptation away. Yachts and country estates and limousines are not adapted to my income. Oh, I inquired of course. The replies were discouraging. And once every year or so I drove by and stared sadly; and even more sadly and brokenly the House of the Black Burghardts stared back.

Then of a sudden Somebody whose many names and places I do not know sent secret emissaries to me on a birthday which I had firmly resolved *not* to celebrate. Sent emissaries who showed me all the Kingdoms of this World, including something in green with a cupola; and also The House; and I smiled at the House. And they said by telegram---"The House of the Black Burghardts is come home again---it is yours!"

Whereat in great joy I celebrated another birthday and drew plans. And from its long, hiding place I brought out an old black pair of tongs. Once my grandfather, and mayhap his, used them in the great fireplace of the House. Long years I have carried them tenderly over all the earth. The sister shovel, worn in holes, was lost. But when the old fireplace rises again from the dead on Egremont Plain, its famed eyes shall see not only the ghosts of old Tom and his son Jack and his grandson Othello and his great grandson, me---but also the real presence of those iron tongs resting again in fire worship in The House of the Black Burghardts.

