
---
title: 'Political Straws'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1923
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 26
  issue: 3
  page: 124-126
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



(*From information furnished by Morris Lewis of Chicago and R. McCants Andrews of Durham, N.C.*) 

Next year a new President of the 
United States, new members of the House of Representatives and one-third of the Senators are to be elected. The attitude of Negro voters is important; more Negroes will vote next year than ever before in the history of the United States. The increased migration to the North, the naturalization of foreigners and the small but steady increase by birth will probably add one quarter of a million voters to the rolls, making a total Negro vote in Northern and border states of between three-fourths and one million voters. 

These voters are incensed against both the Republican and Democratic parties. They remember Democrats because of the treatment of black men during the War, the 
segregation in government departments and the continued mob violence, disfranchisement and "Jim Crow" legislation in the "rotten borough" districts of the South. They remember the absolute failure of the Republicans to redeem or seriously try to redeem their campaign pledge to pass federal legislation against lynching, or to recognize in any way the just demands of the Negro constituency. 

Under these circumstances what will the Negro voter do? Is he intelligent enough to guide his political boat in such rough waters? There have been two chances to judge: one in a city election in Baltimore and the other in a city election in Chicago. 

In Chicago, the black man has been counted as the secure appendage of the Republicans: In the second and third wards of Chicago, the large colored vote is registered. 
On the West Side, North Side, in Englewood, Woodlawn, the Hyde Park and old 380th Ward districts, there are also varied numbers of such voters from a few hundred to twenty thousand and more. 

The principal candidates for Mayor in the recent election were Postmaster Arthur Lueder, Republican, and William E. Dever, Judge of the Superior Court, Democrat. Judge Dever was the only candidate of his party in the democratic primaries. Mr. Lueder was one of three candidates of his party in the Republican primaries. He was the choice of the *Chicago Tribune*, of Senator Medill McCormick and of Attorney General Brundage, an agency and individuals bearing the reputation of being lukewarm or unfriendly to the interests of the colored people. It might also be said that in the Republican primaries the colored districts supported the candidacy of Judge Barasa, who had been eminently fair in hearings before him in connection with the race riots of 1919, again demonstrating that the colored voter was doing some thinking. Aside from the election of a Mayor, a City Clerk and City Treasurer were to be elected. 

The election returns show just how discerning was the vote of the second and third wards where so many colored people live. The second ward gave Dever, Democrat, 8,269; Lueder, Republican, 7,119. These two wards contributed over 17,487 of the 108,000 plurality for Dever. And in these two wards the Republican candidates for City Clerk and City Treasurer got more votes than the Democratic candidates for the respective offices, thus showing that the colored voter did not vote a "straight" democratic ticket. 

Aside from reasons already assigned, and of more importance, was the thought on the part of black voters that the Republican party leaders should be taught a lesson before the 1924 elections; also, there was the attitude of resentment on the part of colored voters because Mayor William Hale Thompson was coerced into withdrawing from the mayoralty race; Negroes generally were not unmindful of the fair treatment accorded them by Mayor Thompson. 

As a practical result of the election in Chicago, Major A. E. Patterson and Earl B. Dickerson, both colored lawyers, have been appointed on the staff of Assistant Corporation Counsels of the City of Chicago by the new Democratic Mayor, Hon. William E. 
Dever. Major Patterson says: "If Judge Dever and his political associates give the Negro a square deal, and it is generally believed that they will, there will be little reason to believe the Democratic party will not receive a fair proportion of the Negro votes in future campaigns." 

In Baltimore, the situation was more complicated: the Republican candidate, Broening, then Mayor, was opposed by a former Mayor Preston running as an Independent Democrat and the regular democratic nominee, Jackson. The registered Negro vote in Baltimore is over 30,000, concentrated largely in nine wards. The colored people were against Mayor Broening and issued the following card to show their reasons: 

> *Why we are against Mayor Broening*<p>Because---Mr. Broening permitted the Ku Klux Klan to parade the city when a Democratic Governor refused them the use of the state armories. <p> Because---Mr. Broening takes the credit for opening one new school (colored) which was started by a democratic councilman. <p> Because---Mr. Broening is endeavoring to put the proposed new Colored High School in politics; but the securing of this was the result of long years of protracted effort and the loyal support of our group to all school loans. <p> Because---Mr. Broening and his party leaders double-crossed the Colored Councilmen and their constituency in the famous constable fight; this, we will never forget nor forgive. <p> Because---Mr. Broening and his School Board have refused to equalize the Colored Teachers' salaries for equal service. <p>Vote for Mr. Howard W. Jackson, for Mayor.

On the other hand, Preston took a stand diametrically opposed to the new colored high school on which ground was recently broken and the contract let although the building has not actually been begun. Jews and Catholics turned against Broening on account of the Ku Klux Klan incident. The dilemma before the colored voters was a difficult one. Many of them refused to vote for a Democrat under any circumstances and kept away from the Polls; those who did vote, voted very largely for Jackson. But there again the Maryland ballot is a very complicated affair, and any attempt to vote a "split" ticket usually results in the ballot being thrown out. Those Negroes, therefore, who voted for Jackson did not dare to attempt to "split" their ticket and vote also for their own two colored members of the Council. The result was, that both Broening and the two colored members were defeated and Jackson triumphed over the demagogue Preston. 

When we add these two incidents to the fact that in New York last year Mayor Hylan swept Negro Harlem, we have a pretty clear idea of the strategy of the Negro voter: He is going, *first*, to defeat his 
known enemies, even if that involves voting for a friendly Democrat; he is going, *secondly*, to vote for his friends, whether Democrats or Republicans; *thirdly*, he is going to refuse, unless compelled, to vote the straight ticket of any party. 

Is it not unfortunate that at this critical period in the history of the Negro voter, the Farmer-Labor party is "ducking" all the issues in which black men are primarily interested; and the Socialists are openly refusing to "fraternize" with Negroes? 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Negro Voter (1928)](/Volumes/35/08/negro_voter.html)
* [The Negro in Politics (1929)](/Volumes/36/11/negro_in_politics.html)
* [How Shall We Vote (1920)](/Volumes/20/05/how_shall_we_vote.html)
* [Votes (1919)](/Volumes/19/02/votes.html)
* [The Election (1910)](/Volumes/01/02/election.html)

<!-- Similar articles end here -->