
---
title: 'Brandeis'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 5
  page: 243
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There seems to be a chance to put a modern man on the Bench of the
Supreme Court. We have had some fine Judges there. We have had a few men
like the late Justice Harlan who stood straight as an arrow for human
rights; but there can be no doubt that the deeper causes of human right
and justice as developed in the modern world have received from the
Supreme Court of the United States scant consideration. It looked as
though for a while it was going to be utterly impossible for any Supreme
Court decision to take account of the rights of the Negro as men and as
workingmen; even the "Grandfather" decision was but an inadequate sop.

With the nomination of Mr. Brandeis we have a man who, as a Jew, knows
what it is to be "despised and rejected of men"; and especially as a
friend and advocate of laboring men he knows what the curse of poverty
means and what its abolition involves.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Supreme Court (1914)](/Volumes/09/02/supreme_court.html)
* [Courts and Jails (1932)](/Volumes/39/04/courts_and_jails.html)
* [Frank (1915)](/Volumes/10/04/frank.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Sex Equality (1920)](/Volumes/19/03/sex_equality.html)

<!-- Similar articles end here -->