
---
title: 'The Negro Public School'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 5
  page: 244
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



A phrase in the December <span class="crisis-title">Crisis</span> has led to some inquiry as to what we mean by the "decline" of the Negro public school. Perhaps our meaning can best be illustrated by two or three references. The *Christian Herald,* for instance, says: "It was early recognized by those responsible for the education of the Negro that an education which would fit him to associate with the whites on equal terms was an education which would only disappoint him and which would leave him unfitted for anything. The main effort, therefore, was put upon the development of schools that should give to the Negro an education that would fit him for the occupations and manner of living which he could expect to follow. This meant vocational training."

To this we may add the information from the Charleston (S.C.) *News and Courier* that in Rock Hill has been established a school "for Negro servants" and that the public schools of the town are being used to co-operate in this work. This we maintain points to the decline of Negro schools and it indicates a widespread movement. Whenever a public school system is used not for disseminating intelligence and giving the keys of knowledge, but rather for the establishment of caste, then the school is missing its purpose. It may well be that at a particular time and a particular place the caste feeling is so strong, the race hatred so potent, that the only school possible is a school which will keep the hated in their places; but manifestly under such circumstances there is not only room for but crying need for a propaganda to attack caste; to say that it is not right to build up a public school system in order to furnish menials for the rich. In the schools of no other group in the nation beside Negroes have persons dared to enunciate such an object for the public schools, no matter how much they may have thought it. If we would build real democracy in the United States we must make such daring impossible in the case of Negroes.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Employment (1932)](/Volumes/39/09/employment.html)
* [Education (1911)](/Volumes/01/04/education.html)
* [Schools (1917)](/Volumes/13/03/schools.html)
* [Public Schools (1916)](/Volumes/12/01/public_schools.html)
* [Public Schools (1916)](/Volumes/12/01/salutations.html)

<!-- Similar articles end here -->