
---
title: 'Preparedness'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 5
  page: 242-243
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



In the presence of a world gone stark mad it seems of little use to talk of anything but war. Yet we wonder if a voice out of the South may not possibly call our war-mad President back to the kind of preparedness that some of us expected of him when he took the presidential chair.

The University Commission of Southern Race Problems sends a letter to college men about the horror of lynching. Surely President Wilson has read these paragraphs from a letter signed by white college professors in eleven Southern states:

> These are the terrible facts. Is there no remedy? Have we not sufficient legal intelligence and machinery to take care of every case of crime committed? Must we fall back on the methods of the jungle? Civilization rests on the obedience to law, which means the substitution of reason and deliberation for impulse, instinct and passion. It is easy and tempting to obey the latter, but to be governed by the former requires self-control, which comes from the interposition of thought between impulse and action. Herein lies the college man's opportunity to serve his fellows; to interpose deliberation between their impulses and action, and in that way to control both.    
> &nbsp;    
> Society has a right to expect college men to help in moulding opinion and shaping conduct in matters of this sort. It is their privilege and duty to co-operate with others in leading crusades against crime and mob rule and for law and civilization. The college man belongs in the front rank of those fighting for moral and social progress. For this reason the University Commission makes its first appeal to you and urges you strongly to co-operate with the press, the pulpit, the bar, officers of the law and all other agencies striving to eliminate this great evil, by speaking out boldly when speech is needed and letting your influence be felt against it in decided, unmistakable measure and manner.

Is there any "preparedness" for Christianity, for human culture, for peace or even for war, that is more pressing than the abolition of lynching in the United States? Alas! We have little hope of reaching the ears of the President. He is too busy yelling for the largest navy in the world.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Letters (1919)](/Volumes/17/01/letters.html)
* [Causes of Lynching (1931)](/Volumes/38/04/causes_of_lynching.html)
* [The President (1915)](/Volumes/09/04/president.html)
* [The Liberal South (1921)](/Volumes/21/06/liberal-south.html)
* [Another Open Letter to Woodrow Wilson (1913)](/Volumes/06/05/open_letter.html)

<!-- Similar articles end here -->