
---
title: 'St. Louis'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 5
  page: 240
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Colored St. Louis and its friends are today fighting for life and breath. It has been a fight not simply against the enemy, but also an inner fight. This is as it must be, although most of us forget it. Most of us assume that the colored people know their rights and want them and are ready to fight for them. On the contrary, what slavery means is that its victims should be uncertain as to their place in the world; as to just what they really want; and as to their readiness to strive for the satisfaction of those wants. 

This was the case in St. Louis. When the segregation proposal came up the masses of the colored people were indifferent. "We are already segregated," they said, "and what, pray, is the difference between customary segregation and legal segregation?" A large number of business men openly and publicly favored segregation when they scented a monopoly of colored business.

Only a few, then, were willing to start the active campaign. Most of the ministers came to the rescue and opened their churches; contributions were made to a campaign fund; literature was printed, lawyers hired and by and by headquarters were opened. An auxiliary committee of prominent white people was finally gotten together consisting of a former president of the City Club, a Unitarian pastor, a city judge, a secretary of the City League, several prominent lawyers and the secretary of the City Club. The election was set for February twenty-ninth. The colored people were finally aroused, registered in large numbers and voted against segregation almost to a man. Yet there were only 15,000 colored voters and considerably over 100,000 whites. Thus is the colored American in the hands of his white friends.

The *Post Dispatch* said in a closing editorial:

> Undoubtedly the conditions now existing, in cities particularly, create a problem difficult to deal with. Race prejudice is a fact, not a theory, and some concessions of strict principle have to be made to avoid trouble in emergencies. But serious as the consequences of the mixture of the races sometimes are, we do not believe it to be wise to violate the principles of liberty and justice in order to save a few individuals from loss and trouble. The present conditions entail loss to individuals, but the enforcement of segregation affects fundamental principles and thus may bear upon the welfare of all the people.   
> &nbsp;   
> Self-interest and prejudice may make segregation popular enough to carry, but we do not believe it will survive. We believe that in the long run temporary victory for segregation will end in permanent defeat. Certainly intelligent people who see the significance and the inevitable drift of such a measure should vote against it.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [East St. Louis (1917)](/Volumes/14/05/east_st_louis.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [Separation (1911)](/Volumes/01/04/separation.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Segregation (1934)](/Volumes/41/01/segregation.html)

<!-- Similar articles end here -->