
---
title: 'Allies'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 3
  page: 112-113
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Occasionally we find in
the columns of a national press, which as a rule regards the wrongs of colored citizens as "stale news" not worth printing, some really splendid argument in support
of the militant position taken by this Association. What, for instance, could be more gratifying than this?

It is a reprimand from the Commander-in-Chief of the army, the President himself, to a colonel who failed to advance a man on account of a prejudice against his race:

> The President directs the Secretary of War to inform Col. Garrard that his attitude in this matter is strongly disapproved as contrary to the ideals and principles of this country.
> &nbsp;
> Such procedure indicates not only prejudice that should not be found in an officer of his position and experience, but amounts to a failure to justly and fairly consider the merits and claims of the applicant as shown by his efficient service and excellent standing in the mental examinations.
> &nbsp;
> Col. Garrard has been admonished to avoid a repetition of the action taken in this case.

And read this argument against disfranchisement. Does it not deal clearly and comprehensively with the matter? It is the *Saturday Evening Post* of Philadelphia which speaks:

> For a hundred years they have been demonstrating that they know how to fight; and the last century of history shows that ability to fight, without some political ability, does a people little good. After each victory they remain, as before, subject to whatever mere luck may bring them of good or bad in a ruler. Excluding a people from politics ... because they are politically inexperienced, is of a piece with keeping a child out of the water because he doesn't know how to swim.

How, then, has our cause gained two great allies? Is the fold larger by two wandering sheep? Not so, reader. Be not too lifted up. President Taft was dealing with the case of a Jewish soldier and the *Saturday Evening Post* was speaking of Mexico.

You see, our Jewish citizens have votes, and as to Mexico, does not charity begin abroad? Good luck to the Jews---they are our best friends, and we rejoice to see them getting out of the Ghetto the Negro is just getting into. Good luck to our Indian brother in Mexico---may he find friends on every side. But it does seem odd that the rules of justice and logic should never apply in the case of the colored man right here in the United States.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [A Statement (1919)](/Volumes/19/01/statement.html)
* [The Present (1917)](/Volumes/14/04/present.html)
* [Mr. Roosevelt (1912)](/Volumes/04/05/mr_roosevelt.html)
* [Prejudice (1927)](/Volumes/34/09/prejudice.html)
* [Officers (1917)](/Volumes/14/02/officers.html)

<!-- Similar articles end here -->