
---
title: 'Discrimination'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 3
  page: 114
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Northern paper defends race discrimination in this wise:

> A Negro is good enough to associate with a Negro. If not, why not? Why is not a 'Jim Crow' car good enough for a Negro to ride in if it is just as good as the cars used by white people? Why is not a colored church good enough for a colored congregation? Why is not a colored school good enough for colored children? To say that they are not is to join Governor Vardaman in declaring that Negroes are an inferior and criminal people.

A red-headed man is good enough to associate with red-headed men; all persons with bald heads might be made to ride in special coaches; all Irishmen could be forced to go to the Irish school; cripples might be
debarred from Grace Church---why not? Because the color of neither hair nor skin, no merely physical peculiarity and no merely racial difference, is sufficient to be made a basis of far-reaching and positive discrimination and segregation in a democratic government; it is silly, and dehumanizing.

If Scotch or Negro or Welsh people wish to unite in their own churches or schools that is their business; but to force them to do so is unchristian and uncivilized. If a separation on a basis of ignorance throws more Italians in one group than in another, that is a matter of learning, not of blood, and can be cured by schools. But for a sane, decent American here in the twentieth century to encumber his paper with a defense of caste and discrimination based on nothing more than race and color shows the moral plane on which a certain class of Americans are living.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Church and the Negro (1913)](/Volumes/06/06/church_negro.html)
* [Blessed Discrimination (1913)](/Volumes/05/04/blesseddiscrimination.html)
* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)
* [Education (1911)](/Volumes/01/04/education.html)
* [Employment (1932)](/Volumes/39/09/employment.html)

<!-- Similar articles end here -->