
---
title: 'The Flag'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 3
  page: 112
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Representatives from a number of organizations concerned with securing justice to the Negro---among them the N.A.A.C.P.---called upon President Taft the other day in regard to the recent lynchings in Kentucky, Florida, Georgia and Oklahoma. In view of the fact that Negroes had been murdered at an average of one a day, the committee respectfully asked that the President call the attention of Congress to this reign of lawlessness and that appropriate legislation be enacted. The President received the delegates with every courtesy, but assured them that the matter of lynching must be left entirely to the individual States.

There is a side to this doctrine of States rights not without interest. A black man finds his status in the United States safer if he is a British subject than if he is an American citizen. Thus, a colored woman, entering the country a year ago, was subjected to grave indignities until it was learned that her husband was a Britisher, when the attitude toward her at once changed and she was given due consideration. It would be a matter for Federal interference if black British subjects were taken from jail and used as quarry by hunting gentlemen, but black American citizens, unable to appeal to the Union Jack, are assured that the Stars and Stripes have no power to protect them from serving as living targets or from slowly burning at the stake.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Mr. Taft (1911)](/Volumes/02/06/taft.html)
* [Lynching (1926)](/Volumes/32/01/lynching.html)
* [Causes of Lynching (1931)](/Volumes/38/04/causes_of_lynching.html)
* [Lynching (1911)](/Volumes/02/04/lynching.html)
* [Lynching (1927)](/Volumes/33/04/lynching.html)

<!-- Similar articles end here -->