
---
title: 'The High School'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 3
  page: 113-114
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The city of St. Louis has recently built a new colored high school. The story of the accomplishment of this great work reads like a bit of intrigue at the court of the later kings of France---of so great difficulty is it for colored men to get the least public recognition.

For years the colored high school was housed in the worst part of St. Louis, in the midst of white prostitutes and liquor dives; for years the colored people had to be content with cast-off white schoolhouses and inferior accommodations. Finally, repeated appeals for a larger and better high school brought a decision on the part of the Board of Education to enlarge the old school.

A vigilance committee of six colored men, headed by Charles H. Dodge, was formed and they brought in so strong a petition that the board hesitated. They could not find or afford a site for a new school, they
complained. The committee of six found a site, but two small property owners would not yield. The committee of six sat up half the night with them and finally themselves paid the difference in price out of their own pockets.

Then the white neighbors rose in arms. The newspapers flamed, and meetings were held to keep the Negro schoolhouse out of decent quarters; finally it was planned to seize the proposed site for a park. The matter came to a vote, the Negroes rallied, and the project was defeated. (Does the black man need the ballot?)

At last all was arranged when the chairman of the committee of six was told confidentially that the board stood six to six on the project of the new Negro high school, and that unless a certain man was won over all was lost. Dodge went to see the man. The gentleman's secretary refused him admission. Dodge went to another man and got a letter. The vote stood seven to five, and black St. Louis got a one-hundred-thousand-dollar high school, the best-equipped school of its kind in the country.

Moral---Heaven and St. Louis help them who help themselves.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Reconstruction (1919)](/Volumes/18/03/reconstruction.html)
* [Education (1911)](/Volumes/01/04/education.html)
* [St. Louis (1916)](/Volumes/11/05/st_louis.html)
* [Segregation (1910)](/Volumes/01/01/Segregation.html)
* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)

<!-- Similar articles end here -->