
---
title: 'The Negro Politician'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 5
  page: 168
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



While I was in Chicago, a listener at Winnetka threw this question at
me, tensely, with evident deep resentment: "What have you to say to the
course of Negro politicians who are following Thompson in the municipal
campaign?" I answered the question indirectly and unsatisfactorily,
because its fuller answer would have called for a lecture in itself. I
said merely, "The Negro in Chicago and the Negro in New York has as
much right to ally himself to political graft as represented by Tammany
and Thompson, as have more respectable people, in allying themselves with
Insul and Vare and Frank Smith."

The whole matter, however, calls for deeper explanation and frank heart
searching on the part of the American Negro. What happens to us
continually is this: If we keep out of politics, we give the whip hand
to our enemies. They pass segregation laws; they curtail liberty of the
press and of speech; they hinder the right to organize; they
discriminate by law, not simply against color, but against ignorance and
poverty and the victims of any deep-seated public dislike. We have got
to vote or be enslaved.

When we vote, we do not have a chance to vote on the real merits of the
questions presented. We cannot consider the tariff, farm relief, war,
peace, municipal ownership, superpower, and a dozen other pressing
political questions. No, we have got to ask: Does Herbert Hoover believe
that Negroes are men or sub-men? What is the attitude of A1 Smith toward
the Negro problem? Does Reed of Missouri believe in education for
Negroes or is he part of the conspiracy that deprives Lincoln University
of decent buildings? Can any man born south of the Mason and Dixon Line
be for a moment considered as a man or must he always be put down as a
raging beast, in alliance with lynching, disfranchisement, "Jim Crow"
cars, and public insult?

Under such circumstances, intelligent voting on the part of colored men
in the United States becomes a disheartening farce. In Chicago, they can
choose between two things: on the one hand, open gambling, bootlegging,
prostitution, and Thompson; and on the other hand, segregation, denial
of representation, loss of decent jobs and public insult under Deneen or
the Democrats. What on earth is an honest black voter to do?

In New York, there is the same impossible dilemma. Tammany and a Mayor,
who is still unable to explain a certain incident in Italy; on the other
silk-stocking snobs, who refuse the Negroes representation and
gerrymander them out of the city Hall, the state
legislature and the United States Congress.

In the same way, the Philadelphia Negro can choose between Vare and
bribery, or graft, Pepper, snobbery, and "Jim Crow" schools.
Who can blame the American Negro if he votes for the worst, when it is
only in this sort of alliance that he can receive the semblance of
decent treatment?

On the other hand, it is perfectly clear that the Negroes who are
supporting graft and political machines in the chief cities of the
United States, are thereby incurring the distrust, enmity and active
opposition of the intelligent people of the United States; of those very
people who with all their vision, never, so far as the Negro is
concerned, see beyond their own noses.

