
---
title: 'Our Economic Future'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 5
  page: 169-170
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There can be no doubt but what the whole economic future of the Negro in America is ready for new thought and new planning. All the old slogans and old advice are worthless. To ask an individual colored man today to go into the grocery business or to open a drygoods shop or to sell meat, shoes, candy, books, cigars, clothes or fruit is competition with the Chain Store, is to ask him to commit slow but almost inevitable economic suicide, unless he has some unusual local or personal advantage. 

The individual shopkeeper is disappearing in the American world, and his place is being taken by great country-wide organizations which sell food, clothes, cars, coal, coffee, furniture and hundreds of other things to meet the needs of men; and sell them at a price which makes attempted competition futile. The managers of these stores are appointed, and usually no colored men need apply. The workers in the stores and factories are hired, either in agreement with unions that keep out Negroes, or on an open shop basis, where Negroes are admitted only at the lowest wages. 

In general industry, Negroes can become common laborers, underpaid and thereby ousting white competitors and thus engendering deep racial hatreds. Only in exceptional cases do Negroes get a chance in the higher ranks of skilled laborers or as Foreman or Managers. 

In the credit world Negroes get bank credit with much greater difficulty than white men of equal honesty and ability. Negro banks are small and in any crisis they are dependent on the white banks of the city, and, of course, on the great white banking ring of the country. If for any reason, any influential part of any community wishes to crush a Negro bank, the bank is worse than helpless. The story of Memphis confirms this. 

Nearly all of the old independent trades are now part of highly organized combinations, financed with large capital: like bakers, blacksmiths, firemen, jewelers, cigar-makers, painters, cabinetmakers, shoemakers, tailors, upholsters, tinsmiths, and any number of others. Men in the building trades are at the mercy of powerful trade unions, contractors backed endless bank credit and real estate combinations. In transportation, the Negro is absolutely excluded by the railroad unions and only has a desperate chance as longshoreman and laborer. 

In the whole realm of manufacturing under the factory system, the Negro is excluded by the trades union and the deliberate and wide spread agreement of employers. Outside the cigar-making factories and the needle trades, there are practically no Negro operatives in cotton mills, candy factories, furniture factories, grain mills, leather factories, brass, copper, lead and zinc mills, paper mills, textile mills and hundreds of the like. 

In the realm of personal service, the Negro has a chance as porter and servant, and in service for his own race. In professional service we have a first-rate record of desert in medicine, dentistry, literature, law, music and teaching, and a long tradition in the ministry; but these professions depend on a strong wage earning and income receiving mass and this we grievously lack. 

In agriculture, thirty years training by Hampton and Tuskegee has decreased the proportion of Negro farmers in the colored population, and so few of their graduates have become farmers that they refuse to publish the figures. Hampton and Tuskegee are not to blame for this. They attempted the impossible. Farming for white and black today in the United States is a failing, unprofitable business; and the efforts to help it---farm credits and farm relief,---are not for Negroes. 

In the face of this situation, there is no organized and thoughtful effort toward reform. The industrial school never accomplished the object which it had in mind, and which it widely advertised. It has not filled the land with Negro carpenters, bricklayers, wagon-builders, cooks and printers. Only to a limited extent are such schools training artisans today and all of the major industrial schools are being transformed into colleges. 

What is to be done? There is to my mind only one way out: Manufacturing and consumers co-operation among the major part of twelve million people on a wide and ever-increasing scale. There must be the slow, but carefully planned growth of manufacturing trusts, beginning with the raising of raw material on Negro farms; extending to its transportation on Negro trucks; its manufacture in Negro factories; its distribution to Negro cooperative stores, supported by intelligent and loyal Negro consumers.

Such an organization is above and beyond race prejudice and trust competition. Once established on the basis of the English, Scandinavian, German and Russian co-operatives, it would insure the economic independence of the American Negro for all time. 

Beside this could grow credit systems and co-operative banks which could bring the Negro-American group into carefully articulated co-operation with the West Indies and South America; with West Africa and South Africa. 

It is more than idiotic---it is criminal, for American Negroes to stagger blindly on, hugging the fond illusion that white philanthropy through industrial education, is going to furnish them with future steady employment and economic independence. It is equally idiotic to hope that white laborers will become broad enough or wise enough to make the cause of black labor their own. These things will never be done in our day. Our economic future lies in the hands of carefully trained thinkers, technical engineers, and the unswerving will to sacrifice on the part of intelligent masses. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Our Economic Peril (1930)](/Volumes/37/03/our_economic_peril.html)
* [Investments (1921)](/Volumes/22/05/investments.html)
* [The Boycott (1930)](/Volumes/37/03/boycott.html)
* [Blessed Discrimination (1913)](/Volumes/05/04/blesseddiscrimination.html)
* [Progress (1920)](/Volumes/21/01/progress.html)

<!-- Similar articles end here -->