
---
title: 'Brother Baptis'' on Woman Suffrage'
author: Jonas, Rosalie
date: Mar. 1912
categories: 
  - Woman Suffrage
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 5
  page: 247
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


When hit come ter de question er de female vote,       
De ladies an' de cullud folks is in de same boat.      
Ef de Boss feelin' good, an' we eats out his han',      
We kin shout fur freedom, an' foller de ban'.      
We kin play at freedom, so long's we play.      
But ef we gits thinkin', an' comes out an' say:      
Case one's borned a female, an' one's borned black,      
Is dat any reason fur sottin' way back?      
Is dat any reason fur sottin' da-put?      
You kin betcher bottom dollar dat de Boss's fut      
Gwine ter sprout big claws, till dey comes clar thoo,      
An' he climps hit heavy on bofe us two.      
Case de tears er de mudder, nur de sign er de cross,      
Ain't shame all de debbil yit, outen de Boss!      

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Woman Suffrage (1915)](/Volumes/11/01/woman_suffrage.html)
* [Woman''s Suffrage (1913)](/Volumes/06/01/womans_suffrage.html)
* [Votes for Women (1912)](/Volumes/04/05/votes_for_women.html)
* [Let us Reason Together (1919)](/Volumes/18/05/let_us_reason_together.html)
* [The Risk of Woman Suffrage (1915)](/Volumes/11/01/risk_of_woman_suffrage.html)

<!-- Similar articles end here -->