
---
title: 'Mr. Roosevelt'
author: Du Bois, W.E.B.
date: Mar. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 5
  page: 235-236
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



We are glad that at last there can be no doubt in any colored man's mind
concerning the attitude of Theodore Roosevelt toward his race. There
were many of us who were disposed, after time had dimmed the bitter
memory, to attribute the unjust dismissal of hundreds of colored
soldiers who were not even charged with wrongdoing, because of the
suspected but far from proven guilt of a few---there were some of us who
wished to attribute this official Brownsville "lynching" to the mistaken
but sincere impulse of a strong personality rather than to meaner
motive.

Since then, however, Theodore Roosevelt has been put to a greater test.
To explain the action of his progressive convention one must realize Mr.
Roosevelt's attitude toward black men. He does not respect them. It is
doubtful if ever in his life he has really known a colored man whom he
thought was wholly a man. The colored men with whom he has come in
contact have executed his orders, have taken his commands and his money,
but his association with them has been essentially that of master and
servant, not of man and man. Even when he has defended colored men his
motive may have been stubborn determination to have his own way rather
than a desire for real justice.

For this reason Mr. Roosevelt has been unreasonably irritated against
Negroes several times. It would be impossible for him to explain his own
feeling or altogether account for it. It has in it a certain Southern
flavor and is perhaps something like what one would feel if one's cat
should insist on argument and rights instead of purring obedience. How
else can we explain Mr. Roosevelt's irritation at the black soldiers who
saved his regiment in Cuba? His violence at Brownsville? His evident deep resentment at the action of the colored delegates at Chicago? With thousands of his white fellow Americans Mr. Roosevelt shares that half-conscious contempt for black men which arises because of an almost absolute lack of contact between the races on planes of equality and mutual respect.

Starting then with this there can be little doubt but that the mission
of Ormsby McHarg to the South was based on the assumption that the
buying up of Negro delegates was simply a matter of money. The sixty-six
colored delegates in the Republican convention held the balance of
power; if the bulk of them had been purchasable they could have sold
their votes for large sums of money, and there is little doubt but that
Mr. Roosevelt's agents offered them large sums.

There was, too, historic reason for Mr. Roosevelt's assumption: There
has always been a disgracefully large purchasable element among the
black delegates from the South. It has been a shame, but a shame the
cause of which is perfectly plain, and for which the Negro race could
not in justice be blamed.

Moreover, it happened that precisely that reform for which Mr. Roosevelt
and others had sometimes but not always asked was gradually coming;
never before had a Southern Negro delegation to the Republican
convention contained so large a proportion of self-respecting men who
could not be bribed. This fact Mr. Roosevelt and his agents discovered,
but the discovery seems again to have irritated rather than pleased;
just as in Reconstruction times, the one thing that the white South
seems to have feared more that bad Negro rule was good Negro rule, and
it was the reform governments of South Carolina and Mississippi that led
to the overthrow of Negro rule just at the moment when reform seemed
about to succeed.

So here is repetition of history: the sixty-six Negro delegates had many
politicians and "grafters," but it had also merchants, lawyers and
physicians, honest, straightforward, unpurchasable men, a body of
encouraging promise for better things. Not only that, but in the new
Progressive party sat several black delegates of high calibre, quite
fit, we are told by Mr. Roosevelt himself, to stand beside their white
fellows.

It was such men, who for themselves and as solemn trustees for the
rights and hopes of 10,000,000 human beings---10,000,000 men, women and children who have been wronged as few modern peoples have been wronged---asked the adoption of this plank by the New Crusaders:

> The Progressive party recognizes that distinctions of race or class in
political life have no place in a democracy. Especially does the party
realize that a group of 10,000,000 people who have in a generation changed from a slave to a free labor system, re-established family life, accumulated $1,000,000,000 of real property, including 20,000,000 acres of land, and reduced their illiteracy from 80 to 30 per cent., deserve and must have justice, opportunity and a voice in their own government. The party, therefore, dgmands for the American of Negro descent the repeal of unfair discriminatory laws and the right to vote on the same terms on which other citizens vote.

This is the exact wording of the original plank which was written in <span style="font-variant:small-caps;">The Crisis</span> office.

Such was the meagre declaration that black men asked. They did not get
this. Not only was this refused, but every suggested modification,
refinement and watering down was rejected, and the platform of the new
Progressive party of human rights appears absolutely silent on the
greatest question of human rights that ever faced America!

Furthermore, lest there should be any misinterpretation of this silence,
the party proceeded to bar practically every representative of 8,000,000
Southern Negroes and to recognize delegates chosen by Southern conventions open "to white people only." To seal this compact these Hosts at Armageddon stood and sang: 

> Mine eyes have seen the glory     
> &nbsp;    
> of the coming of the Lord!

Selah!

Now, Mr. Black Voter---you with 600,000 ballots in your hand, you with
the electoral vote of Illinois, Indiana, Ohio and New York in your
pocket--- WHAT ARE YOU GOING TO DO ABOUT IT?

