
---
title: 'Virginia Christian'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 5
  page: 236
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Virginia Christian was a product of Virginia far more than of the colored race. It was the social organization of white Virginia that made this girl what she was and then brutally killed for it. The State pushed her down into poverty despite the hard-earned pennies of her father; the State refused to educate her or even to let Northern philanthropy do it; the State put her as a servant, body and soul, into the hands of her mistress and constituted that mistress judge and jury over this ignorant, wayward child. At the age of sixteen—and, despite the attempt of Governor Mann to becloud the fact, the testimony as to the girl's tender age is incontrovertible---this child was convicted of murder, when there is not a white man in the nation who after impartial review of the facts would not have to admit that every circumstance shows lack of premeditation with a strong case for self-defense. Make this child as brutal, immoral and irresponsible as you will and the black fact remains that a civilized community made her and then murdered her for being herself. And that community was Christian Virginia!

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Truth (1911)](/Volumes/01/03/truth.html)
* [The White Primary (1911)](/Volumes/01/05/white_primary.html)
* [Pink Franklin (1911)](/Volumes/01/04/pink.html)
* [The Cause of Lynching (1914)](/Volumes/08/03/cause_of_lynching.html)
* [The Old Story (1911)](/Volumes/01/03/old_story.html)

<!-- Similar articles end here -->