
---
title: 'Votes for Women'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1912
categories: 
  - Woman Suffrage
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 5
  page: 234
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

Why should the colored voter be interested in woman's suffrage? There are three cogent reasons. First, it is a great human question. Nothing human must be foreign, uninteresting or unimportant to colored citizens of the world. Whatever concerns half mankind concerns us. Secondly, any agitation, discussion or reopening of the problem of voting must inevitably be a discussion of the right of black folk to vote in America and Africa. Essentially the arguments for and against are the same in the case of all groups of human beings. The world with its tendencies and temptations to caste must ever be asking itself how far may the governed govern? How far can the responsibility of directing, curbing and encouraging mankind be put upon mankind? When we face this vastest of human problems frankly, most of us, despite ourselves and half unconsciously, find ourselves strangely undemocratic, strangely tempted to exclude from participation in government larger and larger numbers of our neighbors. Only at one point, with disconcerting unanimity, do we pause, and that is with ourselves. That we should vote we cannot for a moment doubt even if we are willing to acknowledge, as most of us are, that we are neither all wise nor infinitely good.

This fact should give us pause; if we in our potent weakness and shortcomings see the vast necessity for the ballot not only for our own selfish ends, but for the larger good of all our neighbors, do not our neighbors see the same necessity? And is not the unanswerable cogency of the argument for universal suffrage regardless of race or sex merely a matter of the point of view? Merely a matter of honestly putting yourself in the position of the disfranchised, and seeing the world through their eyes? The same arguments and facts that are slowly but surely opening the ballot box to women in England and America must open it to black men in America and Africa. It only remains for us to help the movement and spread the argument wherever we may. Finally, votes for women mean votes for black women. There are in the United States three and a third million adult women of Negro descent. Except in the rural South, these women have larger economic opportunity than their husbands and brothers and are rapidly becoming better educated. One has only to remember the recent biennial convention of colored women's clubs with its 400 delegates to realize how the women are moving quietly but forcibly toward the intellectual leadership of the race. The enfranchisement of these women will not be a mere doubling of our vote and voice in the nation; it will tend to stronger and more normal political life, the rapid dethronement of the "heeler" and "grafter" and the making of politics a method of broadest philanthropic race betterment, rather than a disreputable means of private gain. We sincerely trust that the entire Negro vote will be cast for woman suffrage in the coming elections in Ohio, Kansas, Wisconsin and Michigan.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Woman Suffrage (1915)](/Volumes/09/06/womansuffrage.html)
* [Woman's Suffrage (1913)](/Volumes/06/01/womans_suffrage.html)
* [Woman Suffrage (1915)](/Volumes/11/01/woman_suffrage.html)
* [The Risk of Woman Suffrage (1915)](/Volumes/11/01/risk_of_woman_suffrage.html)
* [The Justice of Woman Suffrage (1912)](/Volumes/04/05/justice_of_woman_suffrage.html)

<!-- Similar articles end here -->