
---
title: 'Beside the Still Water'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1931
categories: 
  - ""
  - The Arts
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 38
  issue: 5
  page: 168-169
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


*This is the speech made by the Editor of The Crisis when the Lieutenant Governor of the State of New York bestowed the 17th Spingarn Medal on Richard B. Harrison.*

*The investiture took place in Mansfield Theatre, New York, where "The Green Pastures" is beginning its second year's run. There were present, the author and producer of the play, four Spingarn Medalists, the founder of the Medal and an audience of one thousand.*

*Most of the audience applauded the speech, but there was a grim and critical group who quite evidently did not like it. What do you say?*

This is peculiarly the occasion to say a word of the relationship between the theatre and the American Negro. The stage still retains among us something of freedom and the forward gaze. Behind the footlights one is permitted to examine and discuss Truth under circumstances where literature is stifled, painting inarticulate, sculpture choked of convention, architecture drowned in weaves of monstrosity and music fettered by death.

But this continuing freedom of dramatic art is due to no courage of managers nor merit of dramatists, and is threatened not only by the well recognized fat degeneration of musical comedy, but by that secret, internal and devastating malady which attacks an art which is free to treat in truth, and yet afraid to look it fair in the face. This is the present attitude of the American theatre as it faces the Negro.

<hr/>

The stranger from the stars bursting in upon earth today would, without shadow of a doubt or moment of hesitancy, fasten upon the plight of the black man in America as the most dramatic stuff of the modern world. Convict this harsh and heavy thrust of the dark and primitive peoples, out of the soft green and gold and clan tradition of the tropics, into the anarchy of the Reformation and French Revolution and the punishment of Victoria's African territories fed on flesh across the whole Atlantic. The isles of the Caribbean shrieked to Boston and New Orleans; the Mississippi swept the white labor on black slavery and fought valley of black lowlands and Appalachians.

Nothing escaped it---neither religion nor philosophy, literature nor art, science nor government. Across a continent, across a world, the horror and tragedy and farce of this stupendous drama flew, and beside it men and women danced, and above it rolled a nerve-to-forgotten song. The souls of stricken millions descended into Hell and the third century arose again from the dead---with what blood and pricking pain---with such exquisite horror of hurt, as humanity has seldom known.

Every known element of human drama, every device of theatrical effect was here---the crucifixion of motherhood, the murder of children, the rape of homes; piteous debasement and nameless exaltation of the spirit of man. There was lacking no impudence of wealth nor depths of uttermost pits of poverty. There was the ding of whips, the fangs of dogs, the laughter of power, the refinement of cruelty and the sobbing abasement of the lowliest of the low---dragged slowly and bitterly and relentlessly out over endless years. This is the thing that today America makes merry over. It is our major amusement. It is material for clowns and braying jokes. It is our national perennial issue.

Yet for four hundred years of the fury fire and blood of this land's history, wars black and crimson thread of a madcap hand wove end every pattern, and not the double tongues of all the Donnius and Charles Beard shall alter the red record of one jot of it.

<hr/>

Before this mightiest of human dramas, save here and there a lucid interval, the American theatre has sat distraught, dumb and stupid, with a vacant grin on its face: afraid of the truth, cowed by the tragedy, aghast at the very intricacy and endless implications of the plots. American playwrights have strained their inwards to submerge this drama into farce; to turn the piteous tragedy of the Negro into cheap pornographic bathos; to paint this all too human life into a degenerate reflection of their own sadistic desires. Until today on stage and in literature, in painting, in all art, save alone in music, the souls of black folk have been submerged in fetid filth and white pimps who finance and exploit black prostitutes in "Nigger Heaven" have quite concealed the blazing Hell beneath; and persuaded a complacent world that Harlem has no light of common day; that underneath our sale of laughter lie no pools of bitter tears.

Not only has the American theatre refused to face the drama of the Negro problem, but it has opposed every effort of the Negro himself to find dramatic expression on the stage. It is not enough, in this great and free commonwealth of the spirit of man, that most training schools of drama and art are closed to black folk; it is not enough that in the annual nationwide radio audition no voice of an angel in a black skin may be heard; it is not enough that the American schools at Fontainbleau, supported by the leaders in American painting, sculpture and architecture, have sought to extend the American color line across France---all this perhaps must be tolerated and even awaited in arts dominated by money, by the private profit ideal and by cheap and smug convention. But in the freer air of the drama, despite its all too evident pandering to monopoly and the intellectual mob, it is astonishing to realize the fight which the black actor has had to gain the merest shadow of foothold on Broadway. No one is child enough to believe that a black skin makes an actor, or that the suffering of a people creates of itself the delicate art to portray it. But when the artist does appear, proven and clear, it is almost unbelievable that his fellow white artists would so long and so persistently deny him full recognition.

<hr/>

When Europe of the early 19th Century recognized the great Jewess, Rachel, and the great Negro, Aldridge, as the two outstanding leaders of the stage, whom governments and science and art delighted to honor, that black man could not put foot on a single legitimate stage in the land of his birth. But even after slavery, and from 1870 down nearly to our day, the Negro actor could appear at Court only as the king's fool, with cap and bells, with quip and joke, ready over his own heartbreak to guffaw lustily and dance fantastically for the massed amusement of morons. Even when the unchangeable logic of a particular plot demanded black characters, up until yesterday, even these parts must be taken by white folk with
blackened faces, unknown dialect and an unusually dumb mental equipment. This nonsense in time went beyond the limit of New York complacency and today not even burnt cork could save a miserable play, although supported by the bad acting of the royal family.

This hesitancy of our freest form of art really to be free; this refusal of managers, playwrights and players to use normally and intelligently, the abundant stuff of dramatic material and the not infrequent genius in acting which a nation within a nation furnishes---a black nation greater than Ireland, Belgium, Austria or Portugal---a nation equal in numbers to Egypt, Persia, Czechoslovakia and all Scandinavia---this studied neglect of the most dramatic material in America, has already reacted and will react on the theatre in the United States. A freedom unused is perverted or lost. If the stage dare not frankly and fully portray the Negro problem because of fear and snobbery---because of a provincial mentality born of the slave oligarchy, spawned south of the Mason and Dixon line and transplanted to the congenial concrete sidewalks of New York---the American theatre will find itself with all the greater ease and easier logic denied the right to discuss sex and war, socialism and Russia, liquor and wealth, and anything which at any time an entrenched autocracy or a prurient puritanism or a Nordic impudence may guard with the shackles of censorship.

<hr/>

The abiding refuge of our optimism is the slow growth of normal dramatic instinct among us even anent the Negro; the slow expansion of a national receptive audience unafraid of racial problems. True it is that the fear still lurks; for the stage is still slow and the effective audience too small---and already something may have been eternally lost in creative genius, dramatic ability and the unhampered critical spirit; but "*The Green Pastures*" has helped our hope, and it has helped not so much in form and word and authorship as in the deft and subtle marvel of its interpretation. For skillful as the written play may be, the secret of its triumph lies in its interpretation by Negro actors, and above all in the high and delicate genius of Richard Berry Harrison.

Even here an abundant satisfaction is haunted by a bleak memory. I have known Richard Harrison for thirty-five years. He stands before you tonight with smiling lips and the tranquil courage of a high heart. But I know---I know what crucifixion this man has suffered. Here is a white man of singular capacity and noble beauty who had a black great-grandfather. And who because of that fact and that alone---because of a truth he saw no reason to deny or conceal,---he has been given in this land of the free and home of the brave, from 1864-1930, sixty-six years, no real opportunity, no fair chance, no liberty for the genius that always lay in him, until 1930 and even then almost by accident.

What the author of this play expected in its presentation, I do not know; but you and I know full well and of a certainty what the first audiences expected---what any average American audience expects when Negro actors appear in a Negro play. They expected amusement; they expected slap-stick and broad farce; they expected filth. They licked dry lips, for "The Green Pastures" of their imagination would be gaudy with food and fun, and of the Still Waters beneath they recked nothing.

If Richard Harrison had learned to dance clog and make faces in his youth, he might have riches now. But his demand for sincere drama, for the sting of tragedy and the high humor of true comedy, had led him long years face to face with hunger and poverty, straight on toward careless neglect. He was not one to complain. He has the high and African gift of laughter. He too has looked at death and smiled.

<hr/>

Atlast the closed gate opened, so casually, so carelessly, that Harrison himself was not sure of what he saw---not sure it was The Gate. Someone was needed to portray God as a "nigger" minstrel on Broadway. But it had to be delicately done. There were churches and censors to avoid, there were susceptibilities to be soothed and creeds to be mollified. The audience must surely be tickled and amused, but its mirth must be in bounds, subdued to something like decorum at least in spots.

This called for subtlety in interpretation and understanding---for a deep and human knowledge of mankind, especially of that manner of men who live behind the veil of color, yet are men. Human beings, whether dark and singing slaves or white and bored seekers of Broadway pleasure, must on this stage, see God and live. Who could do this miracle of acting?

When manager and playwright turned to find such a man they faced a wall. They knew few Negro actors. To Broadway the Negro was not an actor, he was a vaudeville turn. True it was that Charles Gilpin, by the tragedy of his own damnation had, with dying flair of genius and clairvoyance of O'Neill, forced the Negro defeatist psychology partially across the footlights. Half willingly thereafter, Broadway endured patronizingly Robeson and Rose McClendon for limited periods and with the clearly expressed proviso, that the author engage in the climax to kill the black hero, or destroy him or rend his soul from his body. Then the white audience could depart secure in the knowledge that all Negro aspiration and effort, by the very constitution of the universe, must ever end in annihilation and defeat, frustration and death.

But this climax would not suit "The Green Pastures." Even on the American stage, God must be reasonably successful; and Richard Harrison almost as a last resort was offered the opportunity to try this role.

<hr/>

What he accomplished, the nation knows. By the breadth of a hair and half-turn of a phrase---by a gesture and a silence, he guided a genial comedy into a great and human drama. Small wonder that only those who see the miracle, can gauge the genius of its doing or realize the rare perfection of its detailed accomplishment. The south, the west, which have not seen the actor and the play are curious and skeptical concerning it. With puzzled frown they inquire into its impression and results and shake vague heads. One can clearly understand how England, reading the text alone, can not escape the feeling that its content must either be blasphemy or farce. And yet no human soul witnessing a performance can doubt the lure of its human kindliness and the mighty tragedy beneath the deep and reverent guidance of a great actor.

What you then as audience and two as authors have unleashed and unbound in this great soul---what you have freed and unfettered in a man and a race, is but earnest of what actors you may see and what drama you may evoke, if instead of hiding your heads in the sand and scurrying abroad to borrow for the American stage the second-hand situations of Paris and Vienna, you open purblind eyes and glance about you.

This meeting tonight is a tribute to Richard Harrison---a tribute belated and artificial, but none the less sincere. He is in his charm and courtesy, his tact and tolerant philosophy, one to be emulated and envied. Toward this distracting problem of race, he is far finer than many of his darker friends, for he walks without plaint or protest even in his hurt; while I, by God, front earth and high Heaven with insistent and unceasing clamor against this throttling of the Art of beauty, against this enchaining of the human spirit---against, to be sure, its cruelty and pain,---but even more, against its crass stupidity.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Precept and Practice (1910)](/Volumes/01/02/precept_and_practice.html)
* [DePriest (1929)](/Volumes/36/02/depriest.html)
* [The Chicago Debate (1929)](/Volumes/36/05/chicago_debate.html)
* [The Negro Politician (1928)](/Volumes/35/05/negro_politician.html)
* [Our Special Grievances (1918)](/Volumes/16/05/our_special_greivances.html)

<!-- Similar articles end here -->