
---
title: 'The Slaughter of the Innocents'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 16
  issue: 6
  page: 267
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Again the rolling of the years brings us to the annual Children's Number. Attention has been called this year especially to the child and the United States Government has been spreading widely the gospel of the preservation of child life. The death of some ten million men who would have been fathers of unborn children has made the world think of the horrors of peace as well as the horrors of war. And the greatest of the horrors of peace is the unnecessary and persistent slaughter of little children. It is a crime of every civilization and of every race, but we Negroes are among the guiltiest, among us from two hundred to five hundred of every thousand of our babies born die before they reach one year of age. We have pleaded poverty, prejudice and slavery as excuse, but the time is come not to excuse but to combat with our own available weapons this murder.

The remedy is, first, care and forethought in bringing children into the world and, second, pure food and air for them when they come. We persist in keeping windows shut and living indoors; we persist in buying food carelessly and feeding all kinds of food indiscriminately to children. Outdoor life and simple, pure foods regularly fed would save the lives of a quarter million Negro children each year. Look on these pages. Are not these little lives worth the saving?

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Of Children (1912)](/Volumes/04/06/of_children.html)
* [Thirteen (1918)](/Volumes/15/03/thirteen.html)
* [Murder (1914)](/Volumes/09/02/murder.html)
* [The True Brownies (1919)](/Volumes/18/06/true_brownies.html)
* [Let us Reason Together (1919)](/Volumes/18/05/let_us_reason_together.html)

<!-- Similar articles end here -->