
---
title: 'If I Had a Million Dollars: A Review of the Phelps Stokes Fund'
author: Du Bois, W.E.B.
date: Nov. 1932
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 39
  issue: 11
  page: 347
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



If someone should give you a million dollars to spend in the settlement of the Negro problem over a period of twenty years, how would you spend it? 

One piquant answer to this question is furnished by the Twenty Year Report of the Phelps stokes Fund, showing its activities from 1911 to 1931. During that time, the Fund has disbursed $1,244,447.55. If we subtract from this the expenses of administration and certain sums spent exclusively for white folk and American Indians, we have a net sum of $929,010 spent for Negroes. 

The exact figures, omitting the cents, and with some re-classification of items from the published report, are as follows:

  
|  |  || |
|------------------------------------|-----------|-----------|-----------|
| Total Funds Expended ||| $1,244,447|
| Subtract from these: | |
| Administration Expense | $107,628 |
| Housing for Whites | $195,059 |
| For Indians | $12,750 | | $315,437 |
| | | | $929,010 |
| Net Expenditure for Negroes: | |
| 1. Educational Services and Research | $200,543 |
| Surveys, United States | $49,984 |
| Surveys, Africa | $121,977 |
|||  $372,504 |
| 2. Negro Schools | |
| United States | |
| Gifts | $190,585 |
| Scholarships | $6,015 |
| Educational Organizations | $25,168 |
| Africa | |
| Scholarships | $18,426 |
| Colored Schools and Teachers | $6,489 |
| || $246,683 |
| 3. Race Relations | |
| United States, General | $97,803 |
| White Schools and Scholarships | $41,000 |
| Africa, General | $47,122 |
| White Schools and Scholarships | $27,905 |
|| | $213,830 |
| 4. Colored Y. M. C. A. Dormitories, New York City || $75,000 |
| 5. Liberia || $20,993 |
| 
| Total | | | $925,246 |

Nearly 40% of the money has been spent for ascertaining the facts concerning the Negro, and especially his educational status. This has involved the setting up of an educational office with experts at an expense of $200,000, through which surveys were made costing nearly $50,000 in the United States, and over $120,000 in Africa.

Of the value of the facts brought together in these surveys there can be no doubt. On the other hand <span style="font-variant:small-caps;">The Crisis</span> has had frequent occasion to disagree with conclusions drawn from these facts.

The expenditure for Negro schools has taken nearly $250,000.—a modest sum, when one considers the needs of Negro education. Of this amount, half has gone to Hampton and Tuskegee, the Penn School, and schools of that type. Recognized colleges, like Howard, Fisk and Tuskegee have received only $42,000. The rest has gone in small amounts to small schools. The education of Negroes of Africa has been directly helped only by $18,000 worth of scholarships and about $7,000 in grants. The rest of the money has gone mainly to white people working more or less directly for the education of Africans or of white public opinion.

Race relations has loomed large in the Phelps Stokes program, involving $41,000 worth of scholarships and endowment for white folks in America to induce them to study the Negro problem and $97,000 for general work in race relations. In Africa, most of this money has gone to white experts, who have been persuaded to visit America and make comparisons between the Negro here and in Africa. For this they have been paid $23,450 in honoraria alone. Beside this, $21,000 has gone to Liberia, chiefly for education, and $75,000 for Y. M. C. A. dormitory facilities in New York City. Several valuable conferences have been promoted and helped-$10,000 for the Le Zoute Conference of 1926; $3,000 for the Jerusalem Conference and $14,000
for conferences on native education.

Without doubt we have here the record of effort and the expenditure of a public trust for great human objects which has accomplished much for the Negro race, and which deserves our thanks and appreciation. At the same time, it would be unfair if we did not express your candid criticism. First of all, we think that the relative proportion of expenditures might have been improved. We believe that at least half the fund should have gone for Negro education and for gifts and scholarships, rather than so largely for educational surveys. Especially are scholarships and fellowships needed for Negro students in the United States and Africa, and we wish instead of $25,000, $100,000 had been spent in this line.

The expenditure of $200,000 for race relations seems to us also excessive, especially as it has been spent very largely for the education of white people and only partially for developing black folk. We are sure that such education is needed, but the training of white folk in racial attitudes is most effective if it arises from a real desire for knowledge rather than the artificial encouragement of a gift. If Southern white colleges do not see the necessity of studying the American Negro, is it really effective to endow such study? Can white South Africans learn as much about the American race problem on a well-remunerated trip here, rather than on visits which South Africa itself sees the necessity of financing? And finally, in all work for race relations, should not opportunity be made for the development and discovery of the best among Negroes, rather than for encouraging whites to think that Negro advancement is entirely dependent upon them.

We admit that in all these matters there is room for argument and that specific cases always alter general principles; and that after all the proof of this past effort lies largely in future results.

We particularly dissent from the thesis which the Phelps Stokes Fund and others have repeatedly put forth: Namely, that education based on the Hampton-Tuskegee idea has been the real cause of the success of Negro education in the United States. We firmly believe that the contrary is true and that with all that Hampton and Tuskegee have done, and they have done much, nevertheless their peculiar program of industrial education has not been successful and has been given up, while the essential soundness of the Atlanta, Fisk and Howard program of general and higher education and teacher training has with all its omissions proved the salvation of the Negro race.

Notwithstanding this criticism, we thank the Phelps Stokes Fund for its work, and we venture to believe that the greatest accomplishment of the trustees of the Fund has been the education which they and their friends have received by which they have gradually advanced from a point of view which looked for the salvation of the Negro race chiefly in intelligent white philanthropic leadership, to a height where they recognized that Negro leadership is indispensable for the uplift of the Negro race and that race relations are only of real value as they bring together equals to strive for mutual advancement.

