
---
title: 'Education'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 2
  page: 64-65
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The talented, systematic, hard-headed youth of our nation are put into business. We tell them that the object of business is to make money. Our dull, soft-headed, unsystematic youth we let stray into philanthropy to work for the good of men. Then we wonder at our inability to stop stealing. This is the great American paradox.

Small wonder that we see in our world two armies: one large and successful, well dressed and prosperous. They say bluntly:	"We are not in
business for our health---business pays!" The other army is seedy and diffident and usually apologetic. It says: "There are things that ought
to be done, and we are trying to do them---philanthropy begs."	Between
the business men, pure and simple, and the professional philanthropists waver the world's hosts---physicians, lawyers, teachers, and servants, some regarding their work as philanthropy, most of them looking at it as business and testing its success by its pay. Business pays.

Philanthropy begs.

Business is reality, philanthropy is dream: business first, philanthropy afterward---is this true? No, it is not. It is the foundation falsehood of our perverted social order.

In reality it is business enterprise that continually tends to defeat its own ability to pay and it is philanthropy that works to preserve a social order that will make the larger and
broader and better business enterprises pay.

What is meant when we say a business pays? Simply this: that for the service rendered or the thing given, the public will to-day pay a valued equivalent in services or goods. Men do this because of their present wants. Given a people wanting certain things and corresponding business enterprises follow. Will this demand continue? That depends: if the satisfaction of these wants minister to the real health and happiness of the community, the demand will continue and grow; if not, eventually either the business or the nation will die. The fact then that a business pays to-day is no criterion for the future. The liquor traffic pays and so does the publishing of school books; houses of prostitution pay and so do homes for renting purposes: and yet alcoholism and prostitution mean death while education and homes mean life to this land.

The amount then that a business pays is no test of its social value. It may pay and yet gradually destroy the larger part of all business enterprise. Here enters philanthropy. Its object is to do for men not what they want done, but that which, for their own health, they ought to want done. Will such service pay? Possibly it will: possibly the people will want the service as soon as they learn of it and lo! "Philanthropy and five per cent." appears. More often, however, the people do not recognize the value of the new thing---do not want it; will not use baths or have anything to do with coffee rooms. Will they pay, then? If they perform a service necessary to human welfare and if the people are gradually learning what is really for their good, then sometimes such philanthropy pays. If it does not pay then the service offered was really unnecessary or the people to whom it was offered have ceased to advance toward betterment and are in danger of death.

The test, then, of business is philanthropy: that is, the question as to how far business enterprise is doing
for men the things they ought to have done for them, when we consider not simply their present desires, but their future welfare. Just here it is that past civilizations have failed. Their economic organization catered to fatal wants and persisted in doing so, and refused to let philanthropy guide them. Just so to-day. Whenever a community seats itself helplessly before a dangerous public desire, or an ingrained prejudice, recognizing clearly its evil, but saying, "We must cater to it simply because it exists," it is final; change is impossible. Beware; the epitaph of that people is being written.

It is just as contemptible for a man to go into the grocery business for personal gain as it is for a man to go into the ministry for the sake of the salary.

There is not a particle of ethical difference in the two callings. The legitimate object of both men is social service. The service of one is advice, inspiration and personal sympathy; the service of the other is fresh eggs and prompt delivery. Thus "from the blackening of boots to the whitening of souls" there stretches a chain of services to be done for the comfort and salvation of men.

Those who are doing these things are doing holy work, and the work done, not the pay received, is the test of the working. Pay is simply the indication of present human appreciation of the work, but most of the world's best work has been, and is being done, unappreciated.

"Ah, yes," says the cynic, "but do you expect men will work for the sake of working?" Yes, I do. That's the reason most men work. Men want work. They love work. Only give them the work they love and they will ask no pay but their own soul's "Well done!" True it is that it is difficult to assign to each of the world's workers the work he loves; true it is that much of the world's drudgery will ever be disagreeable; but pay will never destroy inherent distaste, nor (above the starvation
line) will it form a greater incentive than social service, if we were but trained to think so.

These things are true, fellow-Americans; therefore, let us, with one accord, attack the bottom lie that supports graft and greed and selfishness and race prejudice: namely, that any decent man has at any time any right to adopt any calling or profession for the sole end of personal gain.

"Surely," gasp the thrifty, "the first duty of man is to earn a living!" This means that a man must at least do the world a service such as men, constituted as they are to-day, will requite with the necessities of life. This is true for some men always; perhaps for most men to-day. We pray for some sweet morning when it will be true for all men. But it was not true for Socrates, nor for Jesus Christ.

