
---
title: 'Food'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 16
  issue: 4
  page: 165
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



War necessities may teach the Negro some salutary lessons. For a long time it has been known that as a race we eat too much meat, especially pork, and are ruining our digestions with hot bread made daily. Frugal peoples have long since learned that risen bread thoroughly baked and kept until stale is not only the most economical, but the most nutritious of dietaries. Modern physicians have long urged us to decrease our meat rations and increase our consumption of vegetables. The war comes now to enforce our common sense. The Hot Biscuit is a lovely institution, but it is too costly in work and money and too dangerous for the digestion to come oftener than once a week. The deceitful Pork Chop must be dethroned in the South and yield a part of its sway to vegetables, fruits and fish. Food---reasonable food---will not only win the war, but will win health and efficiency if we learn the lesson of the present emergency aright.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Dodging the Issue (1933)](/Volumes/40/02/dodging_the_issue.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [The Fruit of the Tree (1913)](/Volumes/06/05/fruit_of_tree.html)
* [The Immediate Program of the  American Negro (1915)](/Volumes/09/06/immediate_program.html)
* [Blessed Discrimination (1913)](/Volumes/05/04/blesseddiscrimination.html)

<!-- Similar articles end here -->