
---
title: 'A Philosophy in Time of War'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 16
  issue: 4
  page: 164-165
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




FIRST, This is Our Country:

We have worked for it, we have suffered for it, we have fought for it; we have made its music, we have tinged its ideals, its poetry, its religion, its dreams; we have reached in this land our highest modern development and nothing, humanly speaking, can prevent us from eventually reaching here the full stature of our manhood. Our country is at war. The war is critical, dangerous and worldwide. If this is OUR country, then this is OUR war. We must fight it with every ounce of blood and treasure.

SECOND, Our country is not perfect. Few countries are. We have our memories and our present grievances. This nation has sinned against the light, but it has not sinned as Germany has sinned. Its continued existence and development is the hope of mankind and of black mankind, and not its menace. We must fight, then, for the survival of the Best against the threats of the Worst.

THIRD, But what of our wrongs, cry a million voices with strained faces and bitter eyes. Our wrongs are still wrong. War does not excuse Disfranchisement, "Jim-Crow" cars and social injustices, but it does make our first duty clear. It does say deep to the heart of every Negro American: We shall not bargain with our loyalty. We shall not profiteer with our country's blood. We shall not hesitate the fraction of a second when the God of Battles summons his dusky warriors to stand before the armposts of His Throne. Let them who call for sacrifice in this awful hour of Pain fight for the rights that should be ours; let them who make the laws write beneath each enactment that oppresses us,---but we? Our duty lies inexorable and splendid before us, and we shall not shirk.

FOURTH, Calm and with soul serene, unflurried and unafraid we send a hundred thousand black sons and husbands and fathers to the Western Front and behind them rank on rank stand hundreds of thousands more.

We are the Ancient of Days, the First of Races and the Oldest of Men. Before Time was, we are. We have seen Egypt and Ethiopia, Babylon and Persia, Rome and America, and for that flaming Thing, Crucified Right, which survived all this staggering and struggling of men---for that we fight today in and for America---not for a price, not for ourselves alone, but for the World.

FIFTH, Protest, my brother, and grumble. I have seen the Vision and it shall not fade. We want victory for ourselves---dear God, how terribly we want it---but it must not be cheap bargaining, it must be clean and glorious, won by our manliness, and not by the threat of the footpad. In the day of our lowest travail we did not murder children and rape women to bring our freedom nearer. We played the game and freedom came. So, too, today our souls are ours, but our bodies belong to our country.

Patience, then, without compromise; silence without surrender; grim determination never to cease striving until we can vote, travel, learn, work and enjoy in peace---all this, and yet with it and above it all the tramp of our armies over the blood-stained lillies of France to show the world again what the loyalty and bravery of black men means.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Close Ranks (1918)](/Volumes/16/03/close_ranks.html)
* [Forward (1920)](/Volumes/20/05/forward.html)
* [Peace (1933)](/Volumes/40/12/peace.html)
* [Thirteen (1918)](/Volumes/15/03/thirteen.html)
* [Returning Soldiers (1919)](/Volumes/18/01/returning_soldiers.html)

<!-- Similar articles end here -->