
---
title: 'Tillman'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 16
  issue: 4
  page: 165
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



It can hardly be expected that any Negro would regret the death of Benjamin L. Tillman, Senator from South Carolina. His attacks on our race have been too unbridled and outrageous for that. And yet it is our duty to understand this man in relation to his time. He represented the rebound of the unlettered white proletarist of the South from the oppression of slavery to new industrial and political freedom. The visible sign of their former degradation was the Negro. They kicked him because he was kickable and stood for what they hated; but they must as they grow in knowledge and power come to realize that the Negro far from being the cause of their former suffering was but a co-sufferer with them. Some day a greater than Tillman, Blease and Vardaman will rise in the South to lead the white laborers and small farmer, and he will greet the Negro as a friend and helper and build with him and not on him. This leader is not yet come, but the death of Tillman foretells his coming and the real enfranchisement of the Negro will herald his birth.*

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Blease, Vardaman, Hardwick and Company (1918)](/Volumes/16/06/blease.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Suffrage (1920)](/Volumes/21/01/suffrage.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)

<!-- Similar articles end here -->