---
title: 'Atlanta'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 20
  issue: 1
  page: 5
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

We go to Atlanta in May. We go there because Atlanta is near the center of the problems of 12 million Negroes, which we seek to solve.

We do not go truculently or with braggadocio --- not as irrational extremists or as fire-brands --- but simply to say to the South plainly and earnestly, without pretense or equivocation:

We want to vote

We want lynching stopped

We want schools

We want "Jim-Crow" cars abolished

We want labor peonage ended

We want decent conditions of wage and labor and a cessation of insult and slander

In return for this we promise to use our vote for the common good and not for venal traffic. We propose to continue to increase in intelligence and good manners, to work hard with head and hand and heart, to own our homes and to protect them, and as far as is humanly possible to abolish crime and poverty among us and among our neighbors.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Votes (1919)](/Volumes/19/02/votes.html)
* [Dodging the Issue (1933)](/Volumes/40/02/dodging_the_issue.html)
* [How Shall We Vote (1920)](/Volumes/20/05/how_shall_we_vote.html)
* [Brothers, Come North (1920)](/Volumes/19/03/brothers_come_north.html)
* [Education (1930)](/Volumes/37/02/education.html)

<!-- Similar articles end here -->