
---
title: 'Get Ready'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 20
  issue: 1
  page: 5--6
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Woman Suffrage is coming. Make no mistake about that. This month possibly, this year certainly will see sex discrimination in voting swept away from the United States. Are we getting ready for this mighty change? Are we consulting and laying plans? The white South is. There is already some open discussion among newspapers and a feverish discussion in secret societies and behind closed doors after the servants retire. The South proposes to keep colored women from voting in exactly the same way in which it has disfranchised colored men. Can it do it? Are we going to let it do it?

The Southerners will be handicapped by the "Grandfather" decision of the Supreme Court, but they will rely upon our apathy and the policy of "Sh! Don't agitate---we are your friends!" They will marshall every black Judas and traitor to "advise" us to remain slaves.

Get ready, fellow Negroes, and set your faces like flint. Resolve on two things: (1) to call no man Friend, white or black, who advises you not to exercise the right to vote; (2) if by force and fraud a new disfranchisement is fastened on the South, to publish the facts to the civilized world, to choke the courts with case upon case, to appeal, agitate and protest and to let no threat of poverty, riot or murder turn you from a determination to cast your vote according to law.

Get ready! Know the law. Obey the law. If the law says that only intelligent women may vote, let the intelligent colored women register and vote. If voting is restricted by property, let those who have property register and vote. But if the South attempts in 1920 and after the Great War to disfranchise women illegally for "race, color or previous condition of servitude," show it that it cannot be done.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Woman''s Suffrage (1913)](/Volumes/06/01/womans_suffrage.html)
* [Our Program (1930)](/Volumes/37/05/our_program.html)
* [Votes for Women (1912)](/Volumes/04/05/votes_for_women.html)
* [How Shall We Vote (1920)](/Volumes/20/05/how_shall_we_vote.html)
* [Votes for Women (1918)](/Volumes/15/01/votes_for_women.html)

<!-- Similar articles end here -->