
---
title: 'Close Ranks'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 16
  issue: 3
  page: 111
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




This is The Crisis of the world.

For all the long years to come men will point to the at year 1918 as the great Day of Decision, the day when the world decided whether it would submit to military despotism and an endless armed peace---if peace it could be called---or whether they would put down the menace of German militarism and inaugurate the United States of the World.



We of the colored race have no ordinary interest in the outcome. That which the German power represents today spells death to the aspirations of Negroes and all darker races for equality, freedom and democracy. Let us not hesitate. Let us, while this war lasts, forget our special grievances and close our ranks shoulder to shoulder with our own white fellow citizens and the allied nations that are fighting for democracy. We make no ordinary sacrifice, but we make it gladly and willingly with our eyes lifted to the hills.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [A Philosophy in Time of War (1918)](/Volumes/16/04/philosophy_in_time_of_war.html)
* [The Present (1917)](/Volumes/14/04/present.html)
* [Just Like---Folks (1920)](/Volumes/19/05/just_like_folks.html)
* [Help Us to Help (1918)](/Volumes/16/04/help_us.html)
* [Returning Soldiers (1919)](/Volumes/18/01/returning_soldiers.html)

<!-- Similar articles end here -->