
---
title: 'The Common School'
author: Du Bois, W.E.B.
date: Jan. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 16
  issue: 3
  page: 112-13
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Much mist and misunderstanding has been consciously and unconsciously put in the colored public mind by recent discussions of the schools. We colored people must, however, keep one thing clearly before us: the first fours years' of a child's life, no matter what his race or condition, must be devoted by every modern country which wishes to survive and grow to a very simple program of study: (1) The child must learn to read so as to be able easily to understand what men have written; (2) the child must learn to write so as to be able to communicate with his fellow men; (3) the child must learn to count so as to be able to handle the extraordinary multiplicity of the world's things. To read, to write, to cipher---this is the program and the only program of the first four years of a child's school life. The neglect to do this work then means, in practically all cases, the fatal crippling of the child. This program of study is a matter of technique and difficult technique. It must be learned early and thoroughly or it may not be learned at all. It must be carefully drilled in and be made second nature to the child.

Whenever any person, country or age seeks to substitute for this work anything else, they are either themselves deceived or deliberately deceiving. Other things may appear in the program of the primary school but they are simply subsidiary to the main program and designed to make the main program more easily acquired. Play, for instance, is there as a matter of health and recreation; moral habits are always to be indirectly acquired in home and in school, but the technical business of the primary school is to teach the child to read, to write and to cipher.

No vocational training has any place in a primary school. Any attempt to turn the primary school into a place for teaching trades or teaching agriculture or teaching housework as such is absolutely wrong and should be fought bitterly by everyone of democracy and human uplift. This does not mean that for recreation or as discipline little children may not sew and wash dishes and cultivate school gardens, but this work must not be vocational---it must be simply a means of interesting the child in this main work of learning to read, to write and to cipher.

The next four years of grammar grades are also mainly the carrying out of the work of the first four years, teaching the child to read for information as well as exercise; to write for self-expression as well as for mere communication; and to reason more clearly with mathematical correctness. It may be necessary at some times and places that a child from ten to fourteen be compelled to take some vocational work for self-support, but no country as rich as the United States or as enlightened can afford to make this necessary. It is becoming more and more fixed in our national thought that it is the business of a nation to educate a child up to fourteen years, that is through the grammar grades; and in addition to the three R's and the geography, history and language study that go with them we should add nothing to the curriculum which is not primarily for the helping of these students in this main work either directly or indirectly through inciting interest and correct habits of health and application.

After fourteen there comes an entirely different question---whether the child is to be trained directly for self-supporting work, as most children should be, or whether his talents are sufficient for him to be trained to greater service by longer methods of education.

## NATIONAL AID

The nation will face after this war a tremendous and righteous demand for national aid to common school training. We must no longer allow our educational system to be a thing of shreds and patches and especially so far as colored people are concerned we must get rid of the menace of ignorance. Colored children under fourteen years must have good schools to which they can go and are compelled to go. Anything less than this is unworthy of the Land and the Day.

On the boards which control the administration of funds for the colored public schools the colored race must be represented. They must have a voice in their own education.

