
---
title: 'Philanthropy and Self Help'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 16
  issue: 3
  page: 113-114
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



## Philanthropy

The Negro race in America owes a mighty debt, first, to that army of teachers that followed the emancipating hosts of the Civil War and taught the colored people until they were able in a measure to teach themselves; secondly, to the many millions of people, some rich and some poor, who now for a half-century have been giving monies to support Negro education. It is not strange that the time is approaching and practically is upon us when the stream of financial help from this source is beginning to cease. We must frankly face the prospect that after the war when new calls for help and rehabilitation pour in from all sides and ask aid and succor from an impoverished world that the flow of Northern wealth to Southern colored schools will definitely diminish.

This is natural. No system of higher education for twelve million people can expect to be supported indefinitely by charity. If turning from individual donors we look to the great educational boards, foundations and endowments there is little to hope for. For the most part these foundations are either such as are hard-pressed for funds, as in the case of the church boards, or have ideas with regard to the education of Negroes with which thinking Negroes do not agree.

What, then, is the future of higher education among Negroes to be? Three universities, Howard, Fisk and Lincoln, are probably upon an assured basis; the last two by reason of small endowments, the first because the Negro vote in the United States will probably insure continued appropriations by Congress. Three universities, however, are ridiculously inadequate. We may then turn to those colleges under the control of the various denominational boards.---The Congregationalists can, if they wish, use enough of their endowment funds to support Talladega and Straight as higher institutions, and they may do so. The colored constituency of the Methodist Episcopal Church will probably compel the maintenance at a fair state of efficiency of some schools like Claflin, Bennett and Clark. The Baptists are in a more debatable condition. Their Negro constituency has for the most part withdrawn to itself and is supporting its own schools, leaving the white Baptists with a small Negro constituency to support schools like Morehouse, Shaw and Virginia Union.

## Self-Help

Negro universities and schools of higher training have got to be supported by Negroes or, for the most part, they will not be supported at all. If we black folk want college training for our children, we have got to furnish it out of our own pockets. This is a harsh conclusion and in many respects an unfair burden. If men were wise and if sociology were a science, it would be easy for Negroes to show the people of the United States that the safest and greatest investment that this country could make of a thousand millions of dollars during the next decade would be the establishment of a series of Negro universities and higher technical schools throughout the United States. But the nation does not see it and it will not see it for one hundred years. Human beings today have been educated to the point where they recognize the need of philanthropy for the hungry, the cripple, the grossly ignorant. Many have been educated also to see the just demand of philanthropy for the diseased, the weak and the half-trained. Beyond this, however, it is difficulty to get philanthropy to go. Thorough education and higher training still seem to most people a luxury and an indulgence and we must recognize these facts. We ourselves, however, know that if the Negro is to survive in this world as a man of thought and power, a co-worker with the leading races in civilization, a free, independent citizen of a modern democracy, then the foundations for this future must be laid in the Negro university. This much we know, but hitherto we have not realized that we have got to pay the bill for this education.

## Awake, Put on Thy Strength, O Zion

We can support our own universities. We must do it. One little school in Virginia, supported simply by poor Negro Baptists, refused the help of philanthropists, paid back with interest the money that had been given to it, bought its own land and put up its own buildings, hired its own teachers and last year gave $25,000 cash to run the institution. The Virginia Theological Seminary and College is not a perfect institution. It does not meet the approval of all educators, but it does meet the approval of every independent, right-thinking colored man who believes that the day of passing the hat for Negro education is nearing a close and who is thanking God for it.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Negro Education (1918)](/Volumes/15/04/negro_education.html)
* [White Charity (1922)](/Volumes/24/02/whitecharity.html)
* [Education (1930)](/Volumes/37/02/education.html)
* [Schools (1917)](/Volumes/13/03/schools.html)
* [Education (1911)](/Volumes/01/04/education.html)

<!-- Similar articles end here -->