---
title: 'Peonage'
description: "Condemns a Hoover-appointed probe for likely whitewashing peonage in the Mississippi Valley and demands enforcement of rights"
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Nov. 1927
subjects:
  - Debt peonage
  - Enforcement of the 13th, 14th, and 15th Amendments
  - Disaster relief and flood response
  - Humanitarian aid accountability (American Red Cross)
people:
  - Herbert Hoover
  - W. E. B. Du Bois
places:
  - Mississippi Valley (United States)
  - Mississippi (United States)
organizations:
  - American Red Cross
  - Hoover administration (United States federal government)
events:
  - Great Mississippi Flood (1927)
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 9
  page: 311
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display

categories:
  - "Labor & Economics"
  - "The South"
---

WE have grave suspicions that the colored committee recently appointed by Mr. Hoover to investigate flood conditions and peonage in the Mississippi Valley will be sorely tempted to whitewash the whole situation, to pat Mr. Hoover loudly on the back, and to make no real effort to investigate the desperate and evil conditions of that section of our country. Slavery still exists in the Mississippi Valley and this Committee knows it. Will they dare say so? The 13th Amendment is not enforced, much less the 14th and 15th. This Committee has the chance of a generation to make a thorough investigation and tell the truth or to stand up and let it be known that they are not permitted to make an investigation. The one fatal thing for them to do, and the thing for which the American Negro will never forgive them, is spineless surrender to the Administration and flattery for the guilty Red Cross.

P.S.: This was written in August. Friends said: "Don't prejudge. Wait. Give them a chance." We have waited. Next month we shall have more to say.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The White Primary (1911)](/Volumes/01/05/white_primary.html)
* [The Next Step (1913)](/Volumes/06/02/next_step.html)
* [The Flag (1911)](/Volumes/02/03/flag.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [The Truth (1911)](/Volumes/01/06/truth.html)

<!-- Similar articles end here -->