
---
title: 'Smith'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Nov. 1927
categories: 
  - 1928 Presidential Election
  - Al Smith
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 9
  page: 311-312
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


We are filled with delight at the prospect that Governor Smith will be nominated by the Democrats. The South does not want Smith because he is a Catholic; because he is a "Wet"; and because he is not "an aristocrat!" But if he is nominated, they have got to take him. No matter what they say, they would not dare to vote against him. If they did, their vote would break up the Solid South and usher in real democracy in the United States and that is the last thing that the South dares face. The dilemma of the white South in 1928 is as delicious as the dilemma of the black North when it was asked to choose between Calvin Coolidge and John Davis.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Election (1928)](/Volumes/35/12/election.html)
* [Houston (1928)](/Volumes/35/09/houston.html)
* [On the Fence (1928)](/Volumes/35/11/on_the_fence.html)
* [The Presidential Campaign (1916)](/Volumes/12/06/presidential_campaign.html)
* [The Campaign of 1928 (1928)](/Volumes/35/12/campaign_of_1928.html)

<!-- Similar articles end here -->