
---
title: 'Social Equals'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Nov. 1927
categories: 
  - Social Equality
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 9
  page: 312
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



This is a typical Negro American story which my friend told me the other night. He is a law examiner in one of the departments in Washington. Recently, together with three other professional men, he made a trip to the biennial meeting of a colored fraternity in Detroit. They took the "Red Arrow" all Pullman train out of Washington. As they were talking in the smoking room, a porter came in.

"A doctor, a doctor," he cried. "There is a lady dying in my car! Is there a doctor in here?"

My friend pointed to Dr. Dumas of Washington, one of his companions. Dr. Dumas is tall and handsome, with a smooth, dark-brown face. He is a skilled physician and surgeon. He rose immediately, got his medicine case and went into the next Pullman. An elderly Southern white woman had eaten too much and had a dangerous attack of acute indigestion. A hypodermic relieved her and Dr. Dumas came back to his companions. The next morning, he sauntered back to the car and found the woman quite recovered. She thanked him; then she reached down in her valise, took out a ten dollar bill. Dr. Dumas bowed courteously.

"O, no, Madam," he said. "This is my vacation and yours was an emergency case. I cannot think of taking a fee."

The woman insisted and got quite excited about it. But Dr. Dumas firmly refused and went back to his car. After a while a young white man came in. He said: "I am the son of Senator ---, of ---. I want to thank you very much for refusing to take that fee. The old woman in there is raising a great deal of excitement and is very angry. Of course you know what the trouble is. She thinks your refusal of a fee makes you assume to be her social equal and she is angry at any such assumption on your part. I am glad you did it. Some of the older generation of us Southerners are just plain fools. We younger people cannot, of course, get rid of all our prejudice, but we are certainly going to get rid of some." He bowed and went out.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Precept and Practice (1910)](/Volumes/01/02/precept_and_practice.html)
* [Social Equality (1911)](/Volumes/02/05/social_equality.html)
* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)
* [Consolation (1916)](/Volumes/12/02/consolations.html)
* [Separation (1911)](/Volumes/01/04/separation.html)

<!-- Similar articles end here -->