
---
title: 'A Matter of Manners'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 12
  page: 292-293
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There was a time when the Negro race in America had a right to boast that its manners were better than those of its white neighbors. They were insistently courteous and soft-voiced. Their experience of public insult gave them a sort of social sense of what was due the individual in personal deference and of the good policy and kindliness that lay behind: "Excuse me," "I thank you," "Please."

It was perhaps inevitable that this phase should pass. No group of people who have been so persistently insulted as American Negroes, can be expected to preserve their manners; but it is worthwhile that they should at least regret the loss and not forget what is after all due themselves. There is a story, probably apocryphal, that George Washington was rebuked for raising his hat to a colored person and simply said that he could not let anyone outdo him in politeness. Nothing of this older ideal of a Southern gentleman remains.

The other day in Atlanta five persons in succession entered and left an elevator. On the first floor, two ladies entered, both teachers; one a Master of Arts from the University of Cincinnati, and the other trained in an excellent Northern institution. At the next floor, two boys entered, perhaps eight and twelve years of age. They kept their hats on. At the next floor, another lady entered. Both boys removed their hats. At the next floor, the last lady got out. The boys put their hats back on. The two first ladies and the boys left the elevator at the last floor.

To the stranger this would be inexplicable; but to one who knows the South and also knows that the two first ladies were colored, the magnificent training of these young white Southern gentlemen is evident.

Or again, every once in a while a journal, like the Atlanta *Constitution*, will commission its office boy to write the regular editorial about Negroes returning South after unfortunate experiences in Harlem and after realizing that the "Southern white people are the Negroes best friends." The Constitution does not allow for an occurrence like this, which is not exactly a matter of life and death or even of bread and butter:

The daughter of a colored teacher was entertaining some young friends in the dining room, when the agent of the electric company appeared at the front door to examine the meter. The mother went to the door. In order to get to the meter, he must walk through the house. He started in. The mother said: "You'll have to remove your hat." He gave her to understand that he was not used to removing his hat in houses of "niggers." She refused to let him come in with his hat on, and he thereupon went to the curb and turned out all the lights in the house.

This sort of thing has sad effect upon the manners of colored people. They visit vicariously the insults of ignorant boors and savages, North and South, upon the mass of people, white and colored, with whom they come in contact. They push their way through crowds carelessly; their methods of salutations are crude; they ask pardon of no one, and they assert themselves offensively. Some how and in some way our younger generation must learn that courtesy and manners are not solely for the benefit of the other person; they are tributes to our own self-respect.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Politeness (1911)](/Volumes/01/05/politeness.html)
* [A Matter of Manners (1920)](/Volumes/19/04/matter-of-manners.html)
* [Veiled Insults (1914)](/Volumes/07/06/veiled_insults.html)
* [Jim Crow (1919)](/Volumes/17/03/jim_crow.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)

<!-- Similar articles end here -->