
---
title: 'Peace'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 12
  page: 292-293
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


To one who does not comprehend the reasons, the present attitude of the civilized world toward peace would be incomprehensible. Here is a world which is literally wasting most of its taxes on war; preparing incredible machines for murder, arson and theft.

 Giving of its time, devoting its energy and its brains to destruction and hurt. It is the greatest single threat to civilization. We have just come through a time when war put human culture in ever greater danger than when the barbarians descended upon Rome.

And yet we are quite complacent. We laugh gently at the disarmament conference in Geneva. We do not even treat the matter seriously. We see no threat in the failure of this conference to our own flesh and blood, to our comfort, to our dreams, to literature and art. It is a thing apart from us. To some it is a matter of fanatics and foolish optimists.

Why is all this? It is because of the way we have been taught and the way we are being taught. Our textbooks are full of the laudation of war. Our newspapers make war inevitable. Our pictures glorify war. Our ears hear martial music. Our eyes with delight behold men made into machines and imitating machine-like rhythm. Our movies picture West Point and Annapolis and the glory of battleships shooting away hundreds of dollars a shot in practicing murder.

It is this propaganda that has got us war-minded and keeps us war-minded; and the moment we try to turn from it and disclose its foolishness, along come Madison Grant and Lothrop Stoddard and Adolph Hitler and a dozen other brass-mouthed agitators and tell us that we must look out for the goblins will get us. These goblins are black and yellow and brown. They are Latin and Negro and Asiatic, "lesser breeds without the law." They threaten everything good. They threaten civilization. We must keep ourselves armed against them and practice on each other while anticipating the time when we will wipe out the majority of men in blood.

The Pacifists today who takes his job seriously and sees war for what it really is, will roll up his sleeves first and attack race prejudice; and then he will attack all generals, colonels, captains, and ammunition makers; and then he will attack military schools and cadets; and finally, he may get us to the place where the world will realize that war is hell.
