
---
title: 'Browsing Reader - The American Race Problem'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Sep. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 7
  page: 226
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


E. B. Reuter's "The American Race Problem" (Thomas Y. Crowell and Company) 448 pages, is a book designed for schools and colleges and is a characteristic piece of current academic writing. Reuter has read all the chief books on the Negro and a large amount of periodical literature. He knows current prejudices. He has collected in his book the opinions and statements on which most authorities agree; in matters where there is no standard opinion Reuter features his own. The result is that one finds here a good compendium of what other people have said, but no conclusions from Mr. Reuter that are worth repeating. Most of his conclusions are, in accordance with dominating prejudices, correctly pessimistic. "The presence of Negroes perverted the democratic social institutions"; (page 118.) "The race is not at present in need of or in a position to support a greatly increased number of professionals" (page 249.) "The total number of real educated Negroes in the country is not sufficient to make a faculty for one first class college" (page 289.) "The body of artistic accomplishment to date is small and for the most part not of a high order" (page 306.) "The masses of the race are uneducated and the majority grossly ignorant and backward" (page 335.) And finally, "Prejudice is a reality in the racial situation. It is not less real and probably not less permanent than the physical marks of race!" (page 432.)

As a partial balance to this sort of talk, Reuter acknowledges that there is no proof of the racial inferiority of the Negro; that there is great cultural diversity among them; that poverty has decreased; that their health has improved and that their sex standards and moral life show "remarkable" advance.

The trouble, of course, with a book of this sort is that the writer is not a human being and is not acquainted with human beings. He is studying books and statistics with the usual result.

