
---
title: 'Prejudice'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 1
  page: 19-20
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There is a class of Americans who are coming to regard race prejudice as a divine thing against which it is perfectly useless to strive. If such persons will consider the news of the month they will easily realize that race prejudice in the United States is a deliberately cultivated and encouraged state of mind. In Chicago that which was heralded the world over as "racial" antipathy and called even a "race war" in an art class was proven to be merely a lie, made by a sensation monger. In Delaware a "mob of Negroes" dissolves itself into the rioting of liquor-soaked white toughs. In Texas, the white city of San Antonio went so wild over the excellence of Negro troops that a demagogue in
Congress thought it was time for another Brownsville, and our amiable President hastened to comply---with three contradictory orders in 24 hours. Is it not time that reasonable Americans refuse to be stampeded by nonsense and lies?

There is some evidence of awakening on this point. Hysterical schoolgirls at Cornell, who ought to know better than to yield to cheap snobbery, have been quietly but firmly rebuked by the President. In Boston last year certain impudent Southerners stampeded the managing committee of the Boston Floating Hospital into refusing to appoint colored nurses. The result was that this year one white Southern woman and four white Northern women held up the New England Hospital for women and children for daring to admit a colored interne. These chivalrous and devoted ladies threatened to leave the sick and dying to their fate unless the directors yielded; but the directors calmly declared by a vote of 17 to 4 that they proposed to run the hospital themselves. What has been the result? Has the world ended, or the South seceded? Is the "supremacy" of the white race threatened? It is incomprehensible when we conceive of the ease with which the average American can be stampeded, if you say "Prejudice" to him. Thank God, there are still some who refuse to run.

