
---
title: 'The Strategy of the Negro Voter'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 6
  page: 140-142
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Usually, <span class = "small-caps">The Crisis</span> has discussed voting among Negroes during elections and sought to give specific advice concerning the action of black voters.

In the discussion today, however, it is perhaps better that in the calm that succeeds a presidential election, we should more carefully ask ourselves, what the object of our voting is, and by what methods and strategy we are going to be able to accomplish it?

A generation ago, we assumed that democratic methods of social reform in the United States were properly established and working toward their goal, and that the major problem of the American Negro was to share effectively in the machinery of government, and to be counted according to his numbers as one of the objects of uplift. We did not question then but what universal suffrage was able to bring to all, popular education, industrial efficiency and economic justice, by slow but progressive reform movements. And as Negroes, we asked only for the right to vote on the same terms that other persons voted, and the right to share in the benefits of reform.

## Universal Suffrage

 Since then, and particularly in these post-war days, we have with some difficulty and searching of soul, come to the conclusion that the program of reform through universal suffrage is not moving as it should and might. That on the contrary, the economic and industrial organization of the world is such that democracy, even among the more advanced white nations, is singularly ineffective. And that if the masses are going to achieve incomes adequate to a decent livelihood, and the economic justice which is the only basis of a broad human culture, a revolution in the control and method of our present political activities must come.

If this conviction is true, and it is shared by so large a proportion of the best and keenest thought of the world, that it can hardly today be questioned, then the problem of the Negro voter becomes dynamic rather than static, and relative rather than absolute; that is, he has to ask himself: What am I going to do with my vote and my work and my other activities, so that I may not simply escape racial and class discrimination, but may also help the world in its progress toward human emancipation?

Manifestly, this is no easy task, particularly in a country like the United States, where the Negro forms a decided minority, and is discriminated against in almost every particular, by all  the elements of the population,---the artist and the religious worker; especially by the employer and organizer of industry; and last but not least by the whole of the white laboring class.

## 2,000,000 Votes

We are asking, here particularly under these circumstances, what is the Negro going to do with the right to vote which he possesses now to the extent of at least 2,000,000 votes, and which through determined court action, the attack on the "white primary," the attack on the jury system, and careful use of his balance of power, is destined greatly to increase within the next decade.

The Negro faces two major political parties: the Democrats and the Republicans. They stand essentially for the same thing. They represent a dictatorship of organized industry which is running the United States for the benefit of the owners of wealth. Perhaps the most characteristic thing of our present era is the frankness with which this truth is today openly admitted. What difference does it make, then, whether the Negro votes the Republican or Democratic ticket? He is voting for the same essential dictatorship. Both parties agree in a policy which nullifies the popular vote, limits the wages of common labor, monopolizes capital and land, supports the state mainly by taxes upon the poor, and increases the income of the rich by privilege and administration.

Third parties of various kinds bid for the Negro vote; reform movements, Populist and Socialist parties, and today, the Communists. The ability of any of these parties to carry elections according to present conditions is from the very start hindered and made almost impossible by the rotten boroughs of the South, based on Negro disfranchisement. This fact, from time to time, the Negro has impressed upon Third Parties. But from the day of the Bull Moose, down to that of the L. I. P. A., no effective attack upon this situation has been even initiated, while the more radical parties openly ask the Negro to join white labor in mass action to gain their ends by force.

## White Labor

But as <span class = "small-caps">The Crisis</span> has continually pointed out, the white laboring class and the middle class of clerks and merchants and engineers are the bitterest and most implacable enemies of Negroes. It is to no purpose that thoughtful observers remind Negroes that the Negro prejudice of laborers and clerks is the result of ignorance and often of the machination of the employing and investing classes. That fact, of which the Negro is perfectly aware, can have no essential effect upon his actions, because in the present organization or industry he must get his living mainly as  a concession from the employer and the capitalist and this will remain true in his case so long as his fellow white laborer will not permit him to enter industry on equal terms, or consent to fight with him for higher wages and more decent conditions of work. Thus the Negro worker has absolutely no choice but to accept what the employers offer, or starve. There are today among Negroes:

| <!-- -->    | <!-- -->    |
|-------------|-------------|
| 57,000       | Coal Miners.         |
| 12,000       | Masons.         |
| 32,000       | Carpenters.         |
| 18,000       | Stationary firemen.         |
| 26,000       | Mechanics.         |
| 13,000       | Plasterers.         |
| 130,000       | In iron and steel industries.         |
| 100,000       | Railway Laborers.         |
| 5,000       | Plumbers.         |
| 8,000       | Molders.         |

All these black men and thousands of others have gotten their jobs and are keeping them by fighting the effort of white labor to keep bread and butter from their mouths. In most of the more highly skilled and better paid branches of labor and industry, the white workers have been successful, and today, no matter what the skill of a colored locomotive engineer might be, or a colored telegrapher, or a chemist, or an engraver, or an electrician, or a business manager, the doors of most industrial organizations are slammed fast in his face, simply and solely on account of his color.

In those semi-skilled and unskilled jobs which he holds, he has gotten them only by scabbing and underbidding the white worker. And where he is a member of a trade union, he is tolerated only to keep him from working for less wages than the whites, and he is subjected to every discrimination within the Union that the Union dare apply. Naturally, there are exceptions to these sweeping general statements, but in the main, they are true.

When, therefore, Third Parties appeal to the clerks and laborers of the land, they appeal to potential enemies of the black man as things are today. Or if, as in the case of the Communists, an appeal is made on the basis of no racial discrimination, white labor does not give the slightest response to the appeal, and the Communist vote is less than negligible.

## Opportunism

Under these circumstances, how is a Negro to vote? Manifestly, his voting program has got to be purely opportunist. In the long run, and in the end, he wants his vote to help in the re-organization of society, and particularly the re-organization of the economic basis of society upon which social development depends. From this great end, he must never swerve. But in approaching it, he must see to it that his interests, his essential rights and his well being are not deliberately sacrificed, in so far as they are not inconsistent with the well being of mankind. No one has a right to make the black man a bloody sacrifice on the altar of advance simply because he is weak and unable to defend himself, and when such sacrifice is absolutely uncalled for. Recognizing then that political action seeking reform movements are just and necessary steps toward the realization of permanent betterment of man, the Negro can carefully follow such a program of reform as Karl Marx laid down in his Communist Manifesto, recognizing that such steps may prove pitably inadequate to the great end of re-making this world, but, nevertheless, for a minority they are steps forward and as such, better than inaction or retreat.

Such a program for American Negroes includes universal education of youth, adult education, the taxation of the rich with the avowed purpose of redistributing income, the appropriation by the state of the unearned increment on land values and other monopoly, the reduction of the tariff on imports, the protection of the ballot and proportional representation for minorities, the prevention of crime and reform of criminals, minimum wage standards, limitation of the right of inheritance, state control of banking and credit, increasing state ownership of industry, especially of railroads and public service corporations,

Whenever and wherever there is a chance for the Negro to cast his vote in favor of such measures, he should do so, only insisting that in their application there be no discrimination on account of color or race. Beyond this, when a Third Party asks for his vote, he should insist upon specific promises to attack and abate color discrimination throughout the country and in every particular, and in the absence of such promises, he should refuse categorically any political support. When such promises are made his next step is to see whether those who promise have the power to fulfill.

 ## Communists

It makes no difference how much the Communist Party may promise the Negro, so long as the white people of the country refuse support, it is idiotic for the colored people to throw their votes away. Moreover, in the case of the Communists there is acute danger that the Negro vote will be deliberately sacrificed to ulterior purposes. For instance, there are in the United States 700,000 Negro farm tenants. Some of them rent land on a money basis and are as well off or as poorly off as the corresponding class of whites. But at least 400,000 of these tenants are share croppers, and their economic condition, under the laws and usages of the South, is but little removed from slavery. Moreover, there is naturally a much larger number of white share croppers whose situation is practically almost as bad as that of the Negroes.

Without plan or apparent forethought, the Communists sent agitators down into a rural county of northern Alabama, and induced the wretched Negro sharecroppers to form a "Union." The result was an immediate clash with the authorities; the Communist organizers ran away, and a half-dozen black men face a term in the penitentiary.

If the object of this maneuver was simply to stir up trouble, it succeeded, but at bitter expense to deluded Negroes. If its object was to organize the victims of the share crop system, in order to resist exploitation, and to lead to steps for betterment, then the whole thing was doomed to failure from the beginning because the white sharecroppers of that particular part of Alabama would rather starve than unite in an organization with Negroes. It may well be that this attitude on their part is the result of silly ignorance and instigated directly or indirectly by the land holders and capitalists. But whatever its cause may be, it is a fact, and to ignore such a fact is stupid and wrong.

## Our Goal

These incidents illustrate the avowedly opportunist program of the intelligent Negro voter. Keeping his eye upon ideals, and measures which make for the uplift of mankind, and particulary for the establishment of a state ruled by the working classes for the benefit of all the workers, his object is so to use his vote as to accomplish any and all reforms leading toward the great goal, so long as he is able, simultaneously and in the same degree to break down color caste. No matter how fair the promises or programs of parties may be, Negroes will refuse to support them unless they can show an object compatible with the Negro's survival and reasonable power to carry this out. He will tell both Socialists and Communists that their first job is to make the American working classes free from color prejudice. And that until they do this, the Negro refuses to give up his chance to make a living, in order to put bread and butter into the mouths of his enemies.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Votes (1919)](/Volumes/19/02/votes.html)
* [The Negro in Politics (1929)](/Volumes/36/11/negro_in_politics.html)
* [The Oath of the Negro Voter (1918)](/Volumes/15/01/oath_of_the_negro_voter.html)
* [The Presidential Campaign (1916)](/Volumes/12/06/presidential_campaign.html)
* [Votes for Women (1918)](/Volumes/15/01/votes_for_women.html)

<!-- Similar articles end here -->