
---
title: 'Jim Crow'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 3
  page: 112-13
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


We  colored folk stand at the parting of ways, and we must take counsel. The objection to segregation and "Jim-Crowism" was in other days the fact that compelling Ne­groes to associate only with Negroes meant to exclude them from contact with the best culture of the day. How could we learn manners or get knowledge if the heritage of the past was locked away from us?

Gradually, however, conditions have changed. Culture is no longer the monopoly of the white nor is pov­ erty and ignorance the sole heritage of the black. Many a colored man in our day called to conference with his own and rather dreading the con­ tact with uncultivated people even though they were of his own blood has been astonished and deeply grati­fied at the kind of people he has met---at the evidence of good manners and thoughtfulness among his own.

This together with the natural human love of herding like with like has in the last decade set up a tre­ mendous current within the colored race against any contact with whites that can be avoided. They have wel­comed separate racial institutions.

They have voluntarily segregated themselves and asked for more seg­regation. The North is full of in­ stances of practically colored schools which colored people have demanded and, of course, the colored church and social organization of every sort are ubiquitous.

Today both these wings of opinion are getting suspicious of each other and there are plenty of whites to help the feeling along. Whites and Blacks ask the Negro who fights separation: "Are you ashamed of your race?" Blacks and Whites ask the Negro who welcomes and encourages separation: "Do you want to give up your rights? Do you acknowledge your inferi­ority?"

Neither attitude is correct. Segregation is impolitic, because it is impossible. You can not build up a logical scheme of a self-sufficing, sep­arate Negro America inside America or a Negro world with no close rela­tions to the white world. If there are relations between races they must be based on the knowledge and sym­pathy that come alone from the long and intimate human contact of indi­viduals.

On the other hand, if the Negro is to develop his own power and gifts; if he is not only to fight prejudices and oppression successfully, but also to unite for ideals higher than the world has realized in art and indus­try and social life, then he must unite and work with Negroes and build a new and great Negro ethos.

Here, then, we face the curious paradox and we remember contradictory facts. Unless we had fought segregation with determination, our whole race would have been pushed into an ill-lighted, unpaved, un-sewered ghetto. Unless we had built great church organizations and manned our own southern schools, we should be shepherdless sheep. Unless we had welcomed the segregation of Fort Des Moines, we would have had no officers in the National Army. Unless we had beaten open the doors of northern universities, we would have had no men fit to be officers.

Here is a dilemma calling for thought and forbearance. Not every builder of racial co-operation and solidarity is a "Jim-Crow" advocate, a hater of white folk. Not every Negro who fights prejudice and segregation is ashamed of his race.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Tragedy of ''Jim Crow'' (1923)](/Volumes/26/04/tradgedy_of_jim_crow.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Correspondence (1926)](/Volumes/31/05/correspondence.html)
* [Separation (1911)](/Volumes/01/04/separation.html)
* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)

<!-- Similar articles end here -->