
---
title: 'Social Equality'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1922
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 24
  issue: 1
  page: 8
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Do I want Social Equality? Certainly I do. Every normal decent human being wants to associate with his fellowmen on terms of equality. We like to be invited out. We want people to want us. We are unhappy if we are ostracised and ignored and despised and forgotten. Booker T. Washington wanted social equality and got it. R.R. Moton accepts it whenever and wherever it is offered. I, he, they, everybody wants men to want us.

If they do not want us---if they hate and despise us, very well. There may be little or nothing which we can do to change their attitude. But one thing we can do: we can refuse to hate and despise them or to say that we think hatred and contempt are fine human habits.

We will surely never stultify our souls by seeking those who despise us, but equally we will refuse to lie and say that we *wish* to be despised. 

The despising of men, regardless of gift and character, is a cruel crime. It must be abolished with other crimes and barbarities. Of course, we want it abolished. Of course, we want social equality and we know that we will never be real men until we get it.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Social Equality (1919)](/Volumes/19/01/social_equality.html)
* [Again, Social Equality (1920)](/Volumes/19/05/again_social_equality.html)
* [Social Equality (1911)](/Volumes/02/05/social_equality.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [President Harding and Social Equality (1921)](/Volumes/23/02/president-harding.html)

<!-- Similar articles end here -->