
---
title: 'Dr. Du Bois Resigns'
author: National Association for the Advancement of Colored People
date: Aug. 1934
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 41
  issue: 8
  page: 245-246
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


 **The full text of his letter and the resolution of the N.A.A.C.P. Board accepting his resignation**

The Board of Directors of the National Association for the Advancement of Colored people at the June meeting took no action upon the resignation of Dr. Du Bois, tendered as of June 11, but named a committee to confer with Dr. Du Bois and see if some satisfactory settlement of differences could not be arranged.

Under date of June 26, however, Dr. Du Bois addressed the following letter to the Board and released it to the press as of July 1, eight days before it came officially to the notice of the Board at its regular meeting July 9:

> In deference to your desire to postpone action on my resignation of June 11, I have allowed my nominal connection with <span class="crisis-title">The Crisis</span> to extend to July 1, and have meantime entered into communication with the Chairman of the Board, and with your Committee on Reconciliation. <p> I appreciate the good will and genuine desire to bridge an awkward break which your action indicated, and yet it is clear to me, and I think to the majority of the Board that under the circumstances my resignation must stand. I owe it, however, to the Board and to the public to make clear at this time the deeper reasons for my action, lest the apparent causes of my resignation seem inadequate. <p> Many friends have truthfully asserted that the segregation argument was not the main reason for my wishing to leave this organization. It was an occasion and an important occasion, but it could have been adjusted. In fact, no matter what the Board of the National Association for the Advancement of Colored People says, its action towards segregation has got to approximate, in the future as in the past, the pattern which it followed in the case of the separate camp for Negro officers during the World War and in the case of the Tuskegee Veterans' Hospital. In both instances, we protested vigorously and to the limit of our ability the segregation policy. Then, when we had failed and we had failed, we bent every effort toward making the colored camp at Des Moines the best officers' camp possible, and the Tuskegee Hospital, with its Negro personnel, one of the most efficient in the land. This is shown by the 8th and 14th Annual Reports of the National Association for the Advancement of Colored People. <p> The only thing, therefore, that remains for us is to decide whether we are openly to recognize this procedure as inevitable, or be silent about it and still pursue it. Under these circumstances, the argument must be more or less academic, but there is no essential reason that those who see different sides of this same shield should not be able to agree to live together in the same house. <p> The whole matter assumed, however, a serious aspect when the Board peremptorily forbade all criticism of the officers and policies in <span class="crisis-title">The Crisis</span>. I had planned to continue constructive criticism of the National Association for the Advancement of Colored People in <span class="crisis-title">The Crisis</span> because I firmly believe that the National Association for the Advancement of Colored People faces the most gruelling of tests which come to an old organization: founded in a day when a negative program of protest was imperative and effective, it succeeded so well that the program seemed perfect and unlimited. Suddenly, by World War and chaos, we are called to formulate a positive program of construction and inspiration. We have been thus far unable to comply. <p> Today this organization, which has been great and effective for nearly a quarter of a century, finds itself in a time of crisis and change, without a program, without effective organization, without executive officers, who have either the ability or disposition to guide the National Association for the Advancement of Colored People in the right direction. <p> These are harsh and arresting charges. I make them deliberately, and after long thought, earnest effort, and with infinite writhing of spirit. To the very best of my ability, and every ounce of my strength, have since the beginning of the Great Depression, tried to work inside the organization for its realignment and readjustment to new duties. I have been almost absolutely unsuccessful. My program for economic readjustment has been totally ignored. My demand for a change in personnel has been considered as mere petty jealousy, and my protest against our mistakes and blunders has been looked upon as disloyalty to the organization. <p> So long as I sit by quietly consenting, I share responsibility. If I criticize within, my words fall on deaf ears. If I criticize openly, I seem to be washing dirty linen in public. There is but one recourse, complete and final withdrawal, not because all is hopeless nor because there are no signs of realization of the possibilities of reform and of the imperative demand for men and vision, but because evidently I personally can do nothing more. <p> I leave behind me in the organization many who have long thought with me, and yet hesitated at action; many persons of large ideals who see no agents at hand to realize them, and who fear that the dearth of ability and will to sacrifice within this organization, indicates a similar lack within the whole race. I know that both sets of friends are wrong, and while I desert them with deep reluctance, it is distinctly in the hope that the fact of my going may arouse to action and bring a great and gifted race to the rescue, with a re-birth of that fine idealism and devotion that founded the National Association for the Advancement of Colored People. <p> Under these circumstances, there is but one thing for me to do, and that is to make the supreme sacrifice of taking myself absolutely and unequivocably out of the picture, so that hereafter the leaders of the National Association for the Advancement of Colored People, without the distraction of personalities and accumulated animosities, can give their whole thought and attention to the rescuing of the greatest organization for the emancipation of Negroes that America has ever had. <p> I am, therefore, insisting upon my resignation, and on July 1st, whether the Board of Directors acts or does not act, I automatically cease to have any connection whatsoever in any shape or form with the National Association for the Advancement of Colored People. I do not, however, cease to wish it well, to follow it with personal and palpitating interest, and to applaud it when it is able to rescue itself from its present impossible position and reorganize itself according to the demands of the present crisis. <p> Very respectfully yours,  
> (Signed) W. E. B. Du Bois.

 At its meeting July 9, the Board adopted the following resolution:

RESOLVED, That it is with the deepest regret that we hereby accept the resignation of Dr. W. E. B. Du Bois as editor of The Crisis, as a member of the Board of Directors, as Director of Publications and Research, as a member of the Board of The Crisis Publishing Company, and as a member of the Spingarn Medal Award Committee; and we desire at the same time to record our sense of the loss which his resignation will bring not only to the members of this Board but to every loyal member of the Association.

Dr. Du Bois joined the Association in 1910 as Director of Publications and Research. The Association was then a few months old. He was already a distinguished teacher, scholar and man of letters, Professor of Sociology in Atlanta University, and author of "Souls of Black Folk" and other works which had deeply moved the white world as well as the black. The ideas which he had propounded for a decade were the same ideas that had brought the Association into being.

He founded the <span class="crisis-title">Crisis</span> without a cent of capital, and for many years made it completely self-supporting, reaching a maximum monthly circulation at the end of the World War of 106,000. This is an unprecedented achievement in American journalism, and in itself worthy of a distinguished tribute. But the ideas which he propounded in it and in his books and essays transformed the Negro world as well as a large portion of the liberal white world, so that the whole problem of the relation of black and white races has ever since had a completely new orientation. He created, what never existed before, a Negro intelligentsia, and many who have never read a word of his writings are his spiritual disciples and descendants. Without him the Association could never have been what it was and is.

The Board has not always seen eye to eye with him in regard to various matters, and cannot subscribe to some of his criticism of the Association and its officials. But such differences in the past have in no way interfered with his usefulness, but rather the contrary. For he had been selected because of his independence of judgment, his fearlessness in expressing his convictions, and his acute and wide-reaching intelligence. A mere yes-man could not have attracted the attention of the world, could not even have stimulated the Board itself to further study of various important problems. We shall be the poorer for his loss, in intellectual stimulus, and in searching analysis of the vital problems of the American Negro; no one in the Association can fill his place with the same intellectual grasp. We therefore offer him our sincere thanks for the services he has rendered, and we wish him all happiness in all that he may now undertake.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [A Momentous Proposal (1918)](/Volumes/16/05/momentous_proposal.html)
* [Our Special Grievances (1918)](/Volumes/16/05/our_special_greivances.html)
* [Inter-Racial Comity (1922)](/Volumes/22/01/inter-racial_comity.html)
* [The N.A.A.C.P. and Parties (1924)](/Volumes/28/05/naacp_and_parties.html)
* [A Correspondence (1914)](/Volumes/09/01/correspondence.html)

<!-- Similar articles end here -->