
---
title: 'Africa for the Africans'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 23
  issue: 4
  page: 154-155
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The Associated Press in a Paris dispatch, put into the mouth of the editor a statement that a colored Americans could not withstand the African climate, could not oust the Europeans, and did not desire to do so.

It ought to go without saying that the editor never made any such statement. The American Negro is just as able to withstand the African climate as American white men and no more able. The climate is severe and trying, but a healthy man who follows the rules of tropical hygiene can live there. There is, therefore, no necessary barrier of climate to keep American Negroes out of Africa.

On the other hand, it would be foolish for colored folk to assume that because their great grandfathers were Africans that the climate of Africa would have no terrors for them. It has its terrors for all men and these terrors can be overcome. 

The present opportunity for emigration to Africa is, however, exceedingly limited. There is absolutely no chance for colored laborers. Men with capital, education and some technical or agricultural skill, who have the courage of pioneers, good health, and are willing to rough it, can find a career in Liberia, in some parts of French, Portuguese and Egyptian Africa (if they speak the language), and in some parts of British West Africa, if they are British subjects. They will be objects of suspicion in British West Africa and will suffer some caste restrictions. 

On the other hand, in the Belgian Congo, in British East and South Africa and in Rhodesia, an American Negro would hardly be allowed to enter, much less settle. Black merchants and traders have chances in West Africa but they are at the mercy not only of the governments who are not eager to help them, but also of the great banks, corporations and syndicates who are in position to skim the cream of all profits. 

Again the editor distinctly believes that Africa should be administered for the Africans and, as soon as may be, by the Africans. He does not mean by this that Africa should be administered by West Indians or American Negroes. They have no more right to administer Africa for the native Africans than native Africans have to administer America.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)
* [The Name Negro (1928)](/Volumes/35/03/name_negro.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [Violations of Property Rights (1911)](/Volumes/02/01/violations.html)

<!-- Similar articles end here -->