
---
title: 'Again, Pullman Porters'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1926
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 31
  issue: 6
  page: 271
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


As a class Pullman porters are gentlemen in the best sense of that overworked word. They are courteous, silent and of infinite patience. Nowhere in the traveling world can one find a set of public servants who do their work so thoroughly and so well.

The porters are men of unusual skill. Let the doubter try to keep house and make and unmake beds and even serve meals, and at the same time satisfy the exacting and querulous tastes of two or three dozen persons, in a room 36 by 10 feet. In addition to that they have the most delicate duties and responsibilities. The womanhood of America rides undressed under their care and service and not in one case in a million have the porters even been impolite much less impertinent. The porters must decide difficult problems as to men and women, young and old, rich and poor, noisy and nervous, gamblers and prohibitionists, white and black.

Particularly in the service of their own race have the porters done an unforgetable service. Without stirring racial animosities, with infinite tact and with sympathetic courtesy they have made it possible for twelve million insulted people to travel with a minimum of insult and inconvenience. I have travelled 50,000 miles in every state in the union and without the ministrations of the Pullman Porter I should today be dead of exhaustion and shame.



As it is the Pullman Company, relying on indifferent public opinion, can buy directly and indirectly the silence of the press black and white, the connivance of the United States Department of Justice and the halfhearted slobbering of white union labor so as to block the belated effort of Pullman porters to form a real and effective labor union. And in order more completely to befuddle the men who are at their economic mercy, the company is offering them, with wide gestures of benevolence, a "company union" where hand-picked lackeys "representing" the porters will smother complaints and take orders meekly. And, says this rich corporation, take this, shut up or lose your jobs.

Well, perhaps it is better to lose this job. Perhaps we have served as porters long enough. We were good slaves; but we outgrew the job. We were good cheap servants; we are outgrowing that job. We are good porters. But if being porters means being driven slaves and alms-taking servants, then God haste the day when we outgrow that job.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Pullman Porters (1927)](/Volumes/34/10/pullman_porters.html)
* [Pullman Porters (1926)](/Volumes/31/03/pullman_porters.html)
* [The Black Man and Labor (1925)](/Volumes/31/02/black_man_and_labor.html)
* [A Matter of Manners (1920)](/Volumes/19/04/matter-of-manners.html)
* [Labor Omnia Vincit (1919)](/Volumes/18/05/labor_omnia_vincit.html)

<!-- Similar articles end here -->