
---
title: 'Lynching'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1926
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 32
  issue: 1
  page: 10
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Every 23 days a man is lynched in America and we say lynching is over because once we lynched two men every three days. The situation is still intolerable and uncivilized. The Southern states are still incapable of punishing lynchers. Even men whom the courts have declared innocent have been seized by mobs and lynched and then those same courts were unable to punish the lynchers.

The Dyer Anti-Lynching Bill is before the Congress. The South is cowering and complaining. The Galveston *News* calls it "legislation by revenge." The Columbia, S. C. *State* calls it "rotten politics" to "incite race feeling." The Houston, Texas *Post* sees an "invasion" of state rights. The New Orleans *Picayune* declares it "unconstitutional," etc.

Is it revenge to stop public murder? Is it politics to stop lynching? Is it unconstitutional to enforce Section 1 of the 14th Amendment which says that no state shall "deny to any person within its jurisdiction the equal protection of the laws"?

If any Southern state does not want its rights "invaded," let it stop lynching or punish the lynchers. If it cannot do this the United States government must and will. If the men like Dyer and McKinley who have pushed this bill are playing petty politics then the Negro voter answers simply that that is precisely the kind of petty politics he wants played; that he doesn't care a rap whether the senators and representatives who are pushing this legislation love him or hate him, are actuated by the highest patriotism or the lowest selfishness. What he wants is that they should push the Dyer Anti-Lynching Bill and he is going to vote for any man who does it and against any man who doesn't.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Lynching (1927)](/Volumes/33/04/lynching.html)
* [Crime and Lynching (1912)](/Volumes/03/03/crime_and_lynching.html)
* [Lynching (1911)](/Volumes/02/04/lynching.html)
* [The Flag (1911)](/Volumes/02/03/flag.html)
* [Anti-Lynching Legislation (1922)](/Volumes/22/01/anti-lynching_legislation.html)

<!-- Similar articles end here -->