
---
title: 'Loyalty'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 1
  page: 8
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Nothing better illustrates the attitude of the Bourbon South than the recent tales about German propaganda among Negroes.

Slowly, but surely the Negro is winning his fight. Despite wretchedly inadequate schools, peonage, low wages and public insult, the Negro is getting education, buying land and homes and migrating slowly but surely to a land of liberty.

The slave-thinking South is beset by fear of losing these peons either by migration or by their regaining their lost franchise. Any tale or propaganda by which the Bourbon South can get the country to believe the Negro is a menace would play straight into the hands of the slave-holders. Martial law would be declared in the South and this is what the reactionaries want: to stop migration.

They are playing with fire! The Negro is far more loyal to this country and its ideals than the white Southern American. He never has been a disloyal rebel. He never fought for slavery in a land of Liberty. He never nullified the basic principles of democracy because he hated the people whom he had hurt! Enslaved, raped and despised though he has been and is, the Negro knows that this is his country because he helped found it, fought for its liberties and ever upheld its ideals.

No temptation to trust German race-hatred has ever been offered and if offered would not for a moment have been considered. Back of the German mask is the grinning skeleton of the Southern slave driver.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Votes for Negroes (1921)](/Volumes/21/03/votes-for-negroes.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [Heroes (1919)](/Volumes/19/01/heroes.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [We Should Worry (1917)](/Volumes/14/02/we_should_worry.html)

<!-- Similar articles end here -->