
---
title: 'The Migration'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 1
  page: 8
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The migration of Negro laborers from South to North continues as it should. Southern white papers are filled with contradictory statements; to-day, with editorials ridiculing the exodus, painting fearsome pictures of the awful condition of the emigrants and chronicling their wholesale return; tomorrow come editorials bewailing the loss of labor and crying for drastic measures to enslave the black peons.

Meantime the truth is clear: the demand for black workers in the North is unprecedented; after the war the demand will continue because not for a generation will immigration from Europe rise to appreciable figures. There are not jobs for everybody; there is no demand for the lazy and casual, but trained, honest colored laborers are welcome in the North at good wages, just as they are lynched in the South for impudence. Take your choice!

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Migration of Negroes (1917)](/Volumes/14/02/migration_of_negroes.html)
* [Our Economic Peril (1930)](/Volumes/37/03/our_economic_peril.html)
* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)
* [Brothers, Come North (1920)](/Volumes/19/03/brothers_come_north.html)
* [Loyalty (1917)](/Volumes/14/01/loyalty.html)

<!-- Similar articles end here -->