
---
title: 'A Moral Void'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 1
  page: 9
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There can be no doubt bit that the South is lacking in certain moral stamina which must be found among successful, forward-striving people. Recently, for instance, the press of the country went wild over the brave action of Governor Stanley of Kentucky. What then? This same Governor Stanley is apparently going to allow the rescued victim of that mob to be lynched by court under forms of law. There would seem to be no reasonable doubt but that Lube Martin killed Guthrie Diuguid in self-defense after Diuguid had followed him for a year and sworn to kill him. 

Yet Martin is sentenced to death and the Governor dares not raise his voice. So too in South Carolina. A  man is lynched because he is a self-respecting, wealthy Negro citizen who refuses to let a dirty mob publicly whip him. Governor Manning makes brave professions and sends them out through the associated press yet to-day every single lyncher  is free and unindicted. The Governor does nothing and will do nothing. How different is the tale at  Lima, Ohio! There a mob attempted to lynch a Negro but was foiled by the brave sheriff. The ring leaders of the mob were arrested and the sheriff writes us: 

> We have one serving time in the Ohio Penitentiary, three serving time in the Mansfield Reformatory, one locked up in Ottawa Jail waiting return of Court of Appeals, one out on $1,500 bond waiting answer from Court of Appeals, for a new trial, several that we could not get the strongest of evidence against that came in and pleaded guilty that got suspended sentences by paving costs which amounted anywhere from $25 to $50, and are under our watch for one year to see that they don't drink and do anything bad, and we surely have our eyes on them and will continue so. locked in the county jail yet awaiting his trial, several to try yet, and about four who were indicted that we have not been able to locate yet. We have them whipped here and I hope pray that our steps here in this will have its effect everywhere.

