
---
title: 'Naval Ruler'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 1
  page: 9
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



When the United States takes possession of foreign territory it sends to govern it a naval officer. But, naval officers are not trained to govern. They are trained to fight! They have made no study of social organization, of human development, of industrial organization; if they are not quite unsympathetic, it is no fault of their training or of the traditions of their caste; yet, today they are well-nigh absolute masters in Nicaragua, San Domingo, Hayti and the erstwhile Danish West Indies. It would be impossible to conceive a more dangerous or foolhardy experiment.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Haiti (1920)](/Volumes/19/06/haiti.html)
* [Haiti (1915)](/Volumes/11/02/haiti.html)
* [Haiti (1921)](/Volumes/22/06/haiti.html)
* [The History of Haiti (1920)](/Volumes/20/05/history-of-haiti.html)
* [The World and Us (1921)](/Volumes/23/04/world-and-us.html)

<!-- Similar articles end here -->