
---
title: 'The White Church'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 1
  page: 10
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Several white ministers of New York City have recently been assailing the Negro "invasion of Harlem." The 
color question," they say, "is a great  menace to us." 
In something the 
same way, we take it, the Gentiles were "a menace to the Jews" until Jesus Christ preached a new and very unpopular gospel which the reverend doctors of that day stopped by a timely crucifixion. The same spirit is evident in the Chicago *Standard*, a Baptist publication. The *Standard* is exercised because the editor of <span class="small-caps">The Crisis</span> told the students of Morehouse College that lying about their ambitions and aspirations was no way to settle the race problem. He says: 
 
>  Some of Dr. DuBois' hearers could not help admiring his passion for honesty while at the same time wondering whether this fundamental virtue might not be so accentuated as to delay indefinitely the solution of the great race problems confronting the nation. <p> We believe that Professor DuBois, in his passion for frankness, is perhaps in danger of forgetting the injunction of Paul to speak the truth in love.

We would like to overhear St. Paul explain to this gentleman that truth with love is not truth with lies. It is precisely here that the white church is failing. It dare not listen to the truth about present conditions. It dare not inveigh against the thief who is at the bottom of modern industrial organization. It dare not say of the Negro "love your neighbor as yourself." Compelled to be dumb on these great matters of morality and decency it turns to Hell and Damnation and summons Billy Sunday to preach it. This is the course that is spelling moral bankruptcy for white Christianity. 

Is there not a spirit of moral leadership in this powerful aggregation of men that can touch with mighty hands our real problems of modern life and lead us? And if there is not, does the editor of the *Standard* and do the white ministers of Harlem believe that their brand of religion can endure? Awake! put on thy strength, O Zion!

