
---
title: 'Football'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1930
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 37
  issue: 1
  page: 30
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The right of a football coach to bench a player is granted. But the reason must be the good of the team. The benching of one of the best players on the New York University team in a game with Georgia students, was indefensible because it was a despicable yielding to sheer race prejudice. The student body resented it. They were ready to refuse to attend the game. The city resented it. The N.A.A.C.P. stood ready with help and cooperation. A group of colored Harlem men were ready to pay this black boy for what he would lose by resenting the insult. The only person who had no complaint was the black player himself. He refused in any way to communicate with the officials of the N.A.A.C.P. The reason given for his failure to play was an alleged injury, which proved, in fact, to be nothing serious, and finally he went back and played out the season. We have much sympathy for the struggle of the younger Negro between the prejudice of whites and the selfish conservatism of blacks, but for this colored football player, we have nothing but contempt.

_____________
*Citation:* Du Bois, W.E.B. 1930. "Football." *The Crisis*. 37(1):30.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Precept and Practice (1910)](/Volumes/01/02/precept_and_practice.html)
* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)
* [The Immediate Program of the  American Negro (1915)](/Volumes/09/06/immediate_program.html)
* [Education (1930)](/Volumes/37/02/education.html)
* [The Negro Public School (1916)](/Volumes/11/05/negro_public_school.html)

<!-- Similar articles end here -->