
---
title: 'Our Class Struggle'
author: Du Bois, W.E.B.
date: Jul. 1933
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 40
  issue: 7
  page: 164-165
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


In the Marxist patois, the "class struggle" means the natural antagonism and war between the exploiter and the exploited; that is, between those persons who own capital in the form of machines, raw material and money, and who can command credit, and that other large mass of people who have practically nothing to sell but their labor. Between these two classes, there can be no peace because the profit of the capitalist depends on the amount of surplus value he can extract from the work of the laborer.

One no sooner states this than the expert would say immediately that there is no trace of such class struggle among American Negroes. On second thought, however, he might modify this and say that the occupational differences of American Negroes show at least the beginnings of differentiation into capitalists and laborers.

Of Negroes, 10 years of age and over in gainful occupations, there are:

| <!-- -->    | <!-- -->    |
|-------------|-------------|
| Skilled laborers | 331,839 |
| Semi-Skilled laborers | 734,951 |
| Farmers | 873,653 |
| Common laborers | 3,374,545 |
| Trade and Business | 52,957 |
| Professional | 119,827 |
| Civil Service | 15,763 |
| Total | 5,503,535 |

Of the farmers, 181,016 were owners. The others were tenants. We may, therefore, say that the capitalistic class among Negroes would be among the following:

| <!-- -->    | <!-- -->    |
|-------------|-------------|
| Trade and Business | 52,957 |
| Professional | 119,827 |
| Farm Owners | 181,016 |
| Civil Service | 15,763 |
| Total | 369,563 |

Most of these however depend for their income on labor rather than capital. Those in trade and business, include clerks, as well as about 30,000 investors of capital. And the professional men are not capitalists, except as some of them have saved money. The same thing can be said of the civil servants. The farm owners are by vast majority peasant proprietors, most of whom hire a little or no labor outside the family.

The most that can be said is that many of the people in this group have the American ambition to become rich and "independent;" to live on income rather than labor, and thus their ideology ranks them on the side of the white capitalists. On the other hand, the laborers, skilled and semi-skilled, and the tenants, are all a proletariat, exploited by white capital. One has, therefore, a rather curious arrangement, with the real class struggle not between colored classes, but rather between colored and white folk.

There is, however, an inner division that calls for attention because it emphasizes and foreshadows class distinctions within the race. And that is the existence of delinquency and dependency, of criminals and paupers. What is the extent of this class among American Negroes and what is the relation of the class to the workers and the more prosperous elements who have begun to accumulate property?

During the earlier history of the colored race, there was a natural social and class difference that came through the existence of mulattoes. In the West Indies, by French law, these mulattoes were free and often inherited wealth from their fathers. In many cases, they were carefully educated and formed a distinct social class, whose rank depended upon wealth, education and personal freedom. In the later history of the French colonies, and even more in Spanish and American colonies, persistent effort reduced this class to a semi-servile position, and it was the resentment against this that led the mulattoes to unite with the blacks in the Haitian Revolution and overthrow the whites.

In the United States, this color caste was dealt a death blow by the law that made children follow the condition of the mother, so that white fathers sold their colored children into slavery, and the mulatto ceased to be, in most cases, a free man. He inherited no property from his father and lost his right to education; although so far as he was free, he promoted schools, in centers like Washington, Charleston and New Orleans.

The color caste idea persisted after Emancipation, but was gradually driven out by the new economic organization. In this new economy there arose the criminals and paupers;---the direct result of the poverty of a suddenly emancipated class who had little or no capital.



 The apparent criminality, however, of the Negro race is greatly exaggerated for two reasons: First, accusation of crime was used systematically in the South to keep Negroes in serfdom after the Civil War; and secondly, Negroes receive but scant justice in the courts. Most writers, today, have assumed on the basis of statistics, that because the Negro population in jails and penitentiary is proportionately much larger than the white population, that, therefore, the Negro is unusually criminal. But as Thorsten Sellin has pointed out in his note on the Negro criminal, "The American Negro lacks education and earthly goods. He has had very little political experience and industrial training. His contact with city life has been unfortunate, for it has forced him into the most dilapidated and vicious areas of our great cities. Like a shadow over his whole existence lies the oppressive race prejudice of his white neighbor, restricting his activities and thwarting his ambitions. It would be extraordinary, indeed, if this group were to prove more law-abiding than the white, which enjoys more fully the advantages of a civilization the Negro has helped to create."*

On the other hand, the peculiar result of the assumed fact that Negroes are criminal is that within the race, a Negro accused or convicted of a crime immediately suffers a penalty, not only of ostracism, but lack of sympathy. Negroes make comparatively little effort to defend the accused; they do not systematically look after them; the churches take little interest in delinquents, and the general attitude of the race is one of irritation toward these members of their groups who have brought the whole race into disrepute. This makes a peculiarly bitter feeling among the unfortunate of the race and the more successful.

So far as dependents are concerned, again the material which we have to measure the amount of dependents is inconclusive and unsatisfactory. There are such differences in policy in various states, such difference in treatment that it is hard to say what the condition is. It would seem, by a study of states where there is a substantial uniform  policy toward the feeble-minded and paupers, regardless of race, that there is a higher rate of institutionization among Negroes than among whites. And this would be natural unless corrected by taking into account the unequal economic and social condition.

Here again within the race, there is a certain resentment against a colored person who fails to progress as rapidly as the Negro thinks a black man must. When, therefore, such a person becomes a subject of charity and must be put into an institution, he is regarded not so much as unfortunate as in some vague way blame worthy. He hinders the general advance and even if he is not at fault, his existence is a misfortune. The real question, then, in the Negro race, is how far the group can and should assume responsibility for its delinquents and dependents, and cultivate sympathy and help for these unfortunates, and how far in this way differentiation into class can keep economic exploitation from becoming a settled method of social advance.

