
---
title: 'The Colored Voter'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 1
  page: 8-9
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


This is the month of elections. The colored people have long had the habit of considering that the so-called "off-year" in elections is of little importance, and that the important thing is the Presidential election. No greater mistake could well be made. One might almost say that in normal times it makes no difference who is President of the United States, but it makes every difference to every single American who is his Alderman, who is Mayor, who is his member of the Legislature, and his Governor, and above all, who is his Congressman. Let every colored man and woman who can vote see to it that they know the records of the persons who are candidates for these local offices and that they vote for no man who is not demonstrably and unequivocally loyal to the Government and loyal to the rights of American citizens of Negro descent. For instance: the Second Congressional District of New York, covering the large Negro populations of Flushing and Jamaica, is represented in Congress by Charles Pope Caldwell. Mr. Caldwell was born in Texas. When a delegation of colored women, including the widow of a former United States Senator, the wife of a United States Consul in France, and the wife of a Municipal Judge, asked for a hearing before a congressional committee in order to urge the appointment of Negro officers in the army, this man Caldwell "contemptuously threw down their cards; which he had been holding in his hand, and emphatically said he would *never vote for a colored man to be an officer;*" whereupon he angrily turned upon his heel and strode away. It does not make an iota of difference what party Caldwell represents, he must be defeated.

On the other hand, in New York State colored voters have to choose between Whitman and Smith. Both of them have excellent records so far as the colored people are concerned, and a choice calls for thoughtful consideration along lines outside of racial matters.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Political Rebirth and the Office Seeker (1921)](/Volumes/21/03/political-rebirth.html)
* [The Election (1910)](/Volumes/01/02/election.html)
* [Politics (1912)](/Volumes/04/04/politics.html)
* [The Woman Voter (1921)](/Volumes/21/05/woman_voter.html)
* [The Negro Party (1916)](/Volumes/12/06/negro_party.html)

<!-- Similar articles end here -->