---
title: 'Flaming Arrows'
description: "In The Crisis (1919) W.E.B. Du Bois argues Wilson's rhetoric of democracy and justice exposes U.S. racial hypocrisy toward Black and colonized peoples."
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
subjects:
  - Colonialism and self-determination
  - U.S. racial hypocrisy and double standards
  - Jim Crow laws and white supremacy in the American South
  - Presidential rhetoric on democracy and international justice (Woodrow Wilson)
  - Race and international justice concerning colonized peoples
people:
  - W. E. B. Du Bois
  - Woodrow Wilson
  - James K. Vardaman
places:
  - Mississippi
  - Kamerun (Cameroon)
  - New York City
organizations:
  - The Crisis
  - United States government
events:
  - Woodrow Wilson New York speech (1918)
  - World War I (1914-1918)
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 1
  page: 7
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display

categories:
  - "War & Military"
  - "Pan-Africanism & Empire"
---

It was a tremendous speech that Woodrow Wilson made in New York City, September 27, 1918. On one point alone was its meaning vague to us of the darker world, who listened with bated breath. Listen to these words:

> Shall the military power of any nation or group of nations be suffered to determine the fortunes of peoples over whom they have no right to rule, except the right of force?    
> &nbsp;
> Shall strong nations be free to wrong nations and make them subject to their purpose and interest?    
> &nbsp;
> Shall peoples be ruled and dominated, even in their own internal affairs, by arbitrary and irresponsible force, or by their own will and choice?    
> &nbsp;
> Shall there be a common standard of right and privilege for all peoples and nations, or shall the strong do as they will and the weak suffer without redress?

Is it possible that these flaming arrows were not aimed at the Vardamans in Mississippi as well as at Huns in Europe? Is it thinkable that President Wilson did not have clearly in mind Kamerun as well as Serbia? It is neither possible nor thinkable if English is English and Justice is Justice, and with this true, Mr. Wilson's speech is one of the half dozen significant utterances of human history.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Leadership (1920)](/Volumes/19/04/leadership.html)
* [Close Ranks (1918)](/Volumes/16/03/close_ranks.html)
* [The Black Man and the Wounded World (1924)](/Volumes/27/03/black_man_and_the_wounded_world.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [A Philosophy in Time of War (1918)](/Volumes/16/04/philosophy_in_time_of_war.html)

<!-- Similar articles end here -->