
---
title: 'Letters'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 1
  page: 9
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Letters

A young southern white woman writes us:

> Several influential women of the South of my acquaintance have decided to write the President concerning the things we hope to see won for the Negro in our national government in the near future. This, we feel, may do something in creating through Mr. Wilson's influence the state of affairs we hope to see. Would you mind outlining for me the questions that most need to have attention given?

To which The Crisis has replied:

1. Disfranchisement of educated Negroes in the South.
2. The "Jim-Crow" car system by which we are compelled to pay first-class fares for third-class accommodations, and usually denial of Pullman car accommodations.
3. The neglect of Negro education, including inadequate school facilities and lack of adequate attention to high schools and colleges.
4. The double standard of justice in the courts, and especially lynch law.
5. The denial of industrial opportunity and the double standard of wages.
6. The lack of protection for colored women, girls and children.
7. The neglect of sanitation and public health measures, physical and moral, particularly in Negro residential sections.

We trust that you may be able to get a strong statement from southern white women in opposition to some or all of these grievances.

It will be a glad day for America when southern white women recognize their clear duty toward the Negro.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Education (1913)](/Volumes/06/02/democrats.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [The Newest South (1913)](/Volumes/06/03/newest_south.html)
* [Another Open Letter to Woodrow Wilson (1913)](/Volumes/06/05/open_letter.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)

<!-- Similar articles end here -->