
---
title: 'Patriotism'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 1
  page: 10
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Curious, indeed, has been the transformation in the souls of most Americans during this war. Before the war nobody loved America. The very phrase seemed maudlin and unintelligent. We loved Justice and Freedom; we sought reform and uplift in politics, health protection; a nobler and less class distinction race hatred; art, we hoped for universal education; but our country? We scarcely had a country—we willed a whole world. And yet, beneath all this, logically we did love our country because we deemed it capable of realizing our dreams and inspiring the greater world. Else one would no longer have dreamed or worked here. We would have sought a Land of Promise. But did American Socialists emigrate to Germany? No, German Socialists came to America, and worked and believed that here the injustices of private wealth could best and most quickly be remedied. But again Reactionists found here no Utopia but at least a sanctuary and though which they could not find in Russia, Mexico, or the West Indies, or for Did Negroes leave America because Africa? No, they became insulted at the mere suggestion. Despite horror-stories, they believed it eventually possible to realize here in America all their highest hopes and aspirations. So with every man who has toiled in this land for higher and better things—even those who longed for the Peace of God, which in these heavy days passed understanding—not all loved but what passionately not America, and loved America might be the Real America, as we sometimes said.

Men work and fight and sweat for a dream only because they believe it possible. Are the dreams of America less possible now that we fight for common decency in international affairs than before when we strove for highest things within the nation? If leaving the arena of the heart and intellect, we are forced to contend like very beasts, is the fighting any less necessary? Rather is the call of duty infinitely higher when with gun and knife and clenched hand, we are compelled to strive not simply for the higher life, but for life itself. On some such foundation is building the new Patriotism in America and in the World.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Returning Soldiers (1919)](/Volumes/18/01/returning_soldiers.html)
* [Close Ranks (1918)](/Volumes/16/03/close_ranks.html)
* [Help Us to Help (1918)](/Volumes/16/04/help_us.html)
* [A Philosophy in Time of War (1918)](/Volumes/16/04/philosophy_in_time_of_war.html)
* [Roosevelt (1917)](/Volumes/14/04/roosevelt.html)

<!-- Similar articles end here -->