
---
title: 'Soldiers'
author: Du Bois, W.E.B.
date: May 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 1
  page: 8
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Slowly but surely the effort of the Government to satisfy just Negro public opinion increases: The registration card for the selective draft omits the inexcusable discrimination attached to the first registration; a colored correspondent has been sent to the front by the Public Information Bureau; a loan to Liberia has been announced; Haiti and Liberia were prominently featured among the Allies during Liberty Loan weeks; colored colleges have been designated as official military training schools, and there will be a colored man on the War Service Commission soon to go abroad.

There still remains a number of matters which we are hopeful that the Government will soon notice: First, is the wasteful practice of inducting numbers of trained and experienced colored physicians into the army as privates; and, secondly, there are the points so ably brought out by the Thirkield Committee and published elsewhere in this issue. They have to do chiefly with the military training of service battalions, the appointment of more colored commissioned and non-commissioned officers, and the question of illiteracy.

Meaning, the Negro race can take peculiar pride, not only in its unfaltering loyalty, but in the recognition that its troops are gaining abroad.

The 349th Field Artillery Regiment, composed of colored men, on its departure from a French city received the following letter from the Mayor:

> From the very day of its arrival, your regiment by its behavior and its military appearance, excited the admiration of us all. Of the sojourn of yourself and your colored soldiers amongst us, we will keep the best memory and remember your regiment as a picked one. From the beginning a real brotherhood was established between your soldiers and our people who are glad to welcome the gallant Allies of our France. Having learned to know them, the whole population holds them in great esteem and we all join in saying the best of them. I hope that the white troops replacing your regiment will give us equal satisfaction, but whatever their attitude may be, they cannot surpass your 349th Field Artillery.

It is natural to remember that Captain Roy Nash, formerly secretary of the N. A. A. C. P., is with this regiment, together with a number of colored officers.

