
---
title: 'The Ballot'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 2
  page: 62
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


We hail as prophetic the swan-song of Senator Thomas William Hardwick, of Georgia. He entered Congress in 1903, on a platform calling for the repeal of the Fifteenth Amendment. He leaves the Senate in 1919, at the special request of President Wilson, on account of his disloyalty,---not simply to his party leader and his country, but to the foundation principles of democratic government.

He said in helping to defeat Woman's Suffrage:

> What will be the result, when tens of thousands, yes, hundreds of thousands, of Negroes come home from this war with a record of honorable military service? I can conceive that a new agitation may arise as strong and bitter as the agitation for Negro suffrage which swept the North after the Civil war. I can see that this agitation will have a strong basis of right to the minds of people who do not understand the white man's burden as it is borne in the South.

That the number of people who are no longer willing to view with understanding minds the present suffrage conditions in the South will diminish and dwindle away is the chief and compelling reason back of the loyalty of the Negro race in the war. Now that war is over, we have but one word and one thought—the Ballot.

We want that ballot safeguarded by every reasonable and decent limitation, impartially applied; but it can no longer be limited by race and sex.

In the great new day of coming Reconstruction we demand:

A vote for every adult American who can read and write.
Schools where every American child must learn to read and write.
After the record of 350,000 black men in the World War, is there any American, black or white, who can oppose this program? If so, we have but to put to him and Hardwick, in parallel columns, the words of Woodrow Wilson in defense of Woman's Suffrage and our own paraphrase in defense of Negro Suffrage:

| The President said | <span class="crisis-title">The Crisis</span> says |
|--------------------|-----------------|
| Are we alone to ask and take the utmost that our women can give—service and sacrifice of every kind—and still say we do not see what title that gives them to stand by our sides in the guidance of the affairs of their nation and ours? We have made partners of the women in this war. Shall we admit them only to a partnership of suffering and sacrifice and toil, and not to a partnership of privilege and right? | Are we alone to ask and take the utmost that our black fellow citizens can give—service and sacrifice of every kind—and still say we do not see what title that gives them to stand by our sides in the guidance of the affairs of their nation and ours? We have made partners of the Negroes in this war. Shall we admit them only to a partnership of suffering and sacrifice and toil, and not to a partnership of privilege and right? |

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Campaign of 1928 (1928)](/Volumes/35/12/campaign_of_1928.html)
* [Blease, Vardaman, Hardwick and Company (1918)](/Volumes/16/06/blease.html)
* [Woman Suffrage (1915)](/Volumes/09/06/womansuffrage.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [Votes (1919)](/Volumes/19/02/votes.html)

<!-- Similar articles end here -->