---
title: 'The Flight into Egypt'
author: Du Bois, W.E.B.
date: Jun. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 2
  page: 59
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

You remember, do you not?---the beautiful Bible story in the simple words of Matthew, telling of the departure of the Three Wise Men:

> And when they were departed, behold, the angel of the Lord appeareth to Joseph in a dream, saying, Arise, and take the young child and his mother, and flee into Egypt, and be thou there until I bring thee word: for Herod will seek the young child to destroy him.    
> When he arose, he took the young child and his mother by night, and departed into Egypt:    
> And was there until the death of Herod: that it might be fulfilled which was spoken of the Lord by the prophet, saying, Out of Egypt have I called my son.

They were poor, humble, ignorant people,—albeit the blood of kings burned in their veins. They were ragged and unkempt and black. Long years they had plodded faithfully to earn their daily bread in sweat and pain; then one night, beneath the stars, came Three Strangers, crying: "Where is He that is Born?" The mother lifted Him up tenderly and they gave him gifts,—Candy and a Fairy-tale and a piece of Gold.

Joseph and Mary looked at the gold-piece in amazement. Never had they seen so much money before, and as they looked they dreamed. Egypt! the Land of Freedom; Egypt! the Haven of the Oppressed; Egypt! where there was Learning and Wages and Honor. While here? Here there brooded a Shadow and a Fear.

Stealthily they arose by night and took the old lantern and walked and ran till they crossed the river. The dawn found them wet and weary, crouching in the moss-swept underbrush of the swamp; but their faces were set North—that it might be fulfilled which was spoken of the Lord by the prophet,—that the fairy-tale might come true.