---
title: 'Peace'
description: "In a 1919 essay in The Crisis, W.E.B. Du Bois calls for a postwar reckoning—after WWI's blood and terror, nations must choose peace, healing, and democracy."
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1919
subjects:
  - World War I aftermath
  - Peace and reconciliation
  - International democracy and governance
  - Postwar social reconstruction
people:
  - W. E. B. Du Bois
places:
  - Europe
  - United States
events:
  - World War I (1914-1918)
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 2
  page: 59
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display

categories:
  - "War & Military"
  - "Religion & Morality"
---

The nightmare is over. The world awakes. The long, horrible years of dreadful night are passed. Behold the sun! We have dreamed. Frightfully have we dreamed unimagined, unforgettable things—all lashed with blood and tears. Bound and damned we writhed and could not stir. The contortions of our hated souls stifled our hunted bodies. We were cold and numb and deaf and blind, and yet the air was visioned with the angels of Hell; the earth was a vast groan; the sea was a festering sore, and we were flame.

And now suddenly we awake! It is done. We are sane. We are alive. Behold the Heavens and its stars; and this blood,—this warm and dripping blood from our mad self-laceration—What of it? Can we not staunch it? Will we not? Hail, then, Holy Christmastime, Nineteen Hundred and Eighteen Years after the Birth, and five since the last Crucifixion.

*On Earth, Peace, Good Will Toward Men.*

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Curtains of Pain (1917)](/Volumes/13/04/curtains_of_pain.html)
* [The Christmas Prayers of God (1914)](/Volumes/09/02/christmas_prayers_of_god.html)
* [Forward (1920)](/Volumes/20/05/forward.html)
* [The Burden of Black Women (1914)](/Volumes/09/01/burden_of_black_women.html)
* [Peace (1933)](/Volumes/40/12/peace.html)

<!-- Similar articles end here -->