---
title: 'Steve'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 2
  page: 62-63
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

He was a lank puppy when he came—long, and dull gold on his crinkly hair, furtive and frightened, but his eyes were the eyes of the Crucified Christ. The Girl took him in and plead for him—fed him when she thought of it and overfed him after she forgot. He was wild with the joy of a home and bounded in shooting leaps across the meadows. The Woman, who was wiser than we and knew that dogs are more than human, looked on him coldly at first, for she had loved dogs before, and love is a terrible thing. Once he was lost and I and the Girl sought him as the sun died in the west, sought him east and west and north—calling and whistling—till at last he came darting like an arrow out of the unknown dark to leap and fawn upon us and bark triumphantly. Once he was stolen, but after two nights he crept back to us, dirty and bedraggled, with the accusing rope tied around him. Ah! but we were glad, and to celebrate we bought a collar and set his name brightly upon it.

Then of a certain Sunday morning catastrophe threatened us—two Russians stood without the gate and said, "It is our dog," and "Larrabee!" they called and he went, wagging his tail. But the Woman came quietly to the door and said, "Steve!" and he leapt back in joy and wriggled on her and kissed her. Then there was parleying and tales of his beautiful wolf-hound mother and—"But will you take him?" asked the Woman, her voice soft with fear. The Russian wife patted him tenderly and said, "No, we go back to Russia, now that Revolution has brought Freedom, and leave him with you, for he loves you and you are kind." So then the Girl left her hiding and her tears and clasped her treasure, and the Russians went back—Great God! to what?

And the dog waxed strong and mighty, golden and beautiful. Men feared his very sight, and his seldom bark was a forest of sound; but he loved the Woman with an endless love—following her every footstep, harkening to her every word, guarding her every movement. The Girl he liked next; and me he tolerated good-naturedly. To our guests he was studiously polite, with the grave courtesy of the greatly born; to all children he was humble servant—but the Woman was God!

Then came the end. After two years of delights, after the wonder of a new home, after a summer by the sounding sea and winters in snows; after great dreamful naps and terrifying forays; after evenings of strange, weird music—after all this came slow steps and pain and the great frightened look of love in his eyes grew more and more wistful as he followed the Woman whither his palsied legs could not go. So they came and took him away and gave him strange medicine to eat, but the light died in his eyes and in mercy they put him to sleep. The Woman wept.

He is gone. Last night, meseems, he slept beside the werwolves who guard the angels of the throne of God. At dawn I saw his soul flashing in golden flame across the northern skies; and now at noon behold him, leaping with mighty bounds across the broad steppes of his fathers. I hear his great voice sounding above the chaos of the beautifullest dream of two centuries, when the Christ of the Bolsheviki cried in God-begotten faith to the boiling, angry, fear-mad waters, "Peace!" and there was no peace. I feel his golden fleece bristling with almighty curses and his fangs dripping blood above the Huns who would destroy, not alone the flesh, but the spirit of a great people. On, Steve, on! rend and tear and kill and die that the sweet, good earth may live again and that Russia may not die.

All this I see (for I am Seer), but in our deserted home the Girl is silent and the Woman weeps, while I? Oh, I, always, beneath the hand of fate, write—and write—and write.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Gospel According to Mary Brown (1919)](/Volumes/19/02/gospel.html)
* [Curtains of Pain (1917)](/Volumes/13/04/curtains_of_pain.html)
* [A Mild Suggestion (1912)](/Volumes/03/03/mild_suggestion.html)
* [''Ezekielism'' (1911)](/Volumes/03/01/ezekielism.html)
* [Of the Children of Peace (1914)](/Volumes/08/06/of_children_of_peace.html)

<!-- Similar articles end here -->