
---
title: 'Migration'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 4
  page: 190
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The Oklahoma movement for migration to Africa is a poorly conceived idea and we warn our readers against it. Migration to-day is a serious matter and should be planned and financed on a large scale. It is foolish for individuals with small sums of money and no knowledge of the country to go to Africa. Africa needs capital, not labor; it needs technical knowledge and executive ability and not small farmers.

Ordinary inexperienced farmers and laborers migrating from America to Africa would succumb to the trying climate in very short time.

Let the migration idea stop at present. Fight out the battle in Oklahoma and protect the masses against the charlatan who is stealing their money.

There is no steamship in New York building for the African trade and owned by Negroes, and the alleged African chief traveling in Oklahoma is nothing but a common cheat who belongs in jail.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Migration (1917)](/Volumes/14/01/migration.html)
* [The Migration of Negroes (1917)](/Volumes/14/02/migration_of_negroes.html)
* [Flood (1927)](/Volumes/34/05/flood.html)
* [Tulsa (1921)](/Volumes/22/06/tulsa.html)
* [The Future of Africa (1919)](/Volumes/17/03/future-of-africa.html)

<!-- Similar articles end here -->