
---
title: 'The Negro and the Land'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 4
  page: 189-190
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



"Disfranchise the Negro, give him an education and full rights of work and
property. This will settle the Negro problem." Such was the argument put
forward in 1890 when Mississippi began the nullification of the United
States Constitution.

What has been the result? The Negro problem is not settled despite the
fact that nine-tenths of the colored men, 21 years of age and over, have
lost their votes in the Gulf States. Education has been restricted,
cheapened and lowered in efficiency, and most Negro children of school
age are out of school. Low wages and caste restrictions hamper the Negro
worker and show little abatement.

And the right to hold property? Even this is being openly attacked. In
Southern and border cities a half dozen ordinances are making it
difficult or impossible for Negroes to purchase city homes.

But there is the rural South, the haven of refuge for all true black
men, if they read the Gospel according to our best friends correctly.
And yet listen to this, by Clarence Poe, of North Carolina, editor of
the widely read *Progressive Farmer:*

> I have received hundreds and hundreds of letters, representing fifteen
States, endorsing the plan of race segregation I advocated on this page,
August 30. ...    
> &nbsp;    
> The law I advocated August 30, it will be remembered, was just this:
'Whenever the greater part of the land acreage in any given district that may be laid off is owned by one race, a majority of the voters in such a district may say, if they wish, that in future no land shall be sold to a person of a different race; provided such action is approved or allowed (as being justified by considerations of the peace, protection and social life of the community) by a reviewing judge or board of county commissioners.'    
> &nbsp;    
> Such a board, as I have said, could be used by any white community to
keep itself white, but the Negro would almost never be able to use it to
make a community wholly Negro. If you are in favor of such a plan and
want to know more about it, send me a postal card or letter at once.

What is the reason of all this? This is the reason in North Carolina:

|                            | Colored   | Farmers    |
|----------------------------|----------:|-----------:|
|                            | 1900      | 1910       |
| Farms owned                | 17,520    | 21,443     |
| Land in farms owned        | 965,452   | 1,197,496  |
| Per cent. of improved land | 40.9      | 42.8       |
| Value of property owned    | 8,828,581 | 27,448,410 |
| Value of land              | 5,351,290 | 17,063,588 |

Increase of value of all farm property, 1900-1910, 130 per cent.; of
land and buildings, 134 per cent.

This is the reason in the United States:
|                                                  |             |               |                  |                     |
|--------------------------------------------------|-------------|---------------|------------------|---------------------|
|                                                  | 1900        | 1910          | Increase Percent | Increase for whites |
| Value of farm property farmed by colored farmers | 546,723,508 | 1,279,234,245 | 132              | 99.6                |
| Value of farm property owned by colored farmers  | 179,796,639 | 440,922,439   | 145.2            | 93.2                |
| Value land of owners                             | 102,022,601 | 277,391,441   | 171.9            | 109.2               |
| Value buildings of owners                        | 28,662,167  | 69,354,013    | 142              | 74.1                |
| Value implements of owners                       | 8,352,975   | 15,852,814    | 89.8             | 69                  |
| Value livestock of owners                        | 40,758,896  | 78,324,171    | 92.2             | 59.1                |

Here we are then: Advance toward property and independent farm ownership
and a movement among our "best friends" to stop it.

We confess to some bewilderment in this development, and we are waiting
for enlightenment from those wise statesmen who have been volubly
leading us out of the wilderness in these last ten years.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The White Primary (1911)](/Volumes/01/05/white_primary.html)
* [An Open Letter (1915)](/Volumes/10/03/an_open_letter.html)
* [Disenfranchisement (1925)](/Volumes/30/02/disenfranchisement.html)
* [Education (1930)](/Volumes/37/02/education.html)
* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)

<!-- Similar articles end here -->