
---
title: 'The South in the Saddle'
author: Du Bois, W.E.B.
date: Feb. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 4
  page: 188
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



> Should I become President of the United States, they (the colored
people) may count on me for absolute fair dealing and for everything by
which I could assist in advancing the interests of their race in the
United States.

These were Mr. Wilson's words October 16, 1912. Why has the President failed to keep them?

It is not because he did not mean them. He did mean what he said. But
Mr. Wilson is seeking to keep his party intact for carrying through
certain legislation. That party in Congress consists to-day of 290
Representatives and 51 Senators, against an opposition of 127
Representatives and 45 Senators. Moreover, the President's party of 341
includes 115 Senators and Representatives from former slave States.

If these 115 members withdrew their support Mr. Wilson's party would be
a minority of 226 votes against 287. For his policies, therefore, Mr.
Wilson must have the solid South, and the solid South has but one
political tenet: "Down with Niggers!"

But how is it that the solid South is numerically so strong in Congress?
Because it represents not simply 16,000,000 white Southerners, but 8,000,000 disfranchised blacks. Thus the disfranchisement of blacks gives
the Southern whites a club to beat them with.

Not only that, but it gives the Southern whites an abnormal advantage
over the Northern voters. This is easy to prove:

In ten Southern States it took, in 1912, 1,110,034 votes to elect 94
Congressmen. In the rest of the United States it took 13,926,508 votes
to elect 323 Congressmen. In other words, 43,116 ignorant and low-down
Northerners and Westerners are necessary to elect a representative to
Congress, but only 11,808 aristocratic and wise white Southerners are
needed to seat a Negro hater in our highest legislature. No wonder the
South is in the saddle when it wields four times the political power of the North!

