
---
title: 'The Christmas Prayers of God'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 2
  page: 83-84
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



<div class="poem">
<p class = "verse">Name of God&rsquo;s Name!  
<p class = "verse">Red murder reigns;  
<p class = "verse">All Hell is loose;  
<p class = "verse">On gold autumnal air  
<p class = "verse">Walk grinning devils barbed and hoofed,
<p class = "verse">While high on hills of hate,  
<p class = "verse">Black-blossomed, crimson sky&rsquo;d,  
<p class = "verse">Thou sittest, dumb.
</div>

<div class="poem">
<p class = "verse">Father Almighty!  
<p class = "verse">This earth is mad!  
<p class = "verse">Palsied, our cunning hands;  
<p class = "verse">Rotten, our gold;  
<p class = "verse">Our argosies reel and stagger  
<p class = "verse">Over empty seas;  
<p class = "verse">All the long aisles  
<p class = "verse">Of Thy great temples, God,  
<p class = "verse">Stink with the entrails  
<p class = "verse">Of our souls.  
<p class = "verse">And Thou art dumb.
</div>

<div class="poem">
<p class = "verse">Above the thunder of Thy thunders, Lord,  
<p class = "verse">Lightening Thy lightnings,  
<p class = "verse">Rings and roars  
<p class = "verse">The dark damnation  
<p class = "verse">Of this Hell of war.  
<p class = "verse">Red piles the pulp of hearts and heads,  
<p class = "verse">And little children&rsquo;s hands.
</div>

<div class="poem">
<p class = "verse">Allah!  
<p class = "verse">Elohim!  
<p class = "verse">Death is here!  
<p class = "verse">Dead are the living, deep dead the dead.  
<p class = "verse">Dying are earth&rsquo;s unborn&mdash;
</div>

<div class="poem">
<p class = "verse">The babes&rsquo; wide eyes of genius and of joy;  
<p class = "verse">Poems and prayers, sun-glows and earth-songs;  
<p class = "verse">Great pictured dreams,  
<p class = "verse">En-marbled phantasies,  
<p class = "verse">Hymns of high Heaven,  
<p class = "verse">All fade, in this dread night,  
<p class = "verse">This long ghost night&mdash; 
<p class = "verse">While Thou art dumb.
</div>

<div class="poem">
<p class = "verse">Have Mercy!  
<p class = "verse">Have mercy upon us, miserable sinners!  
<p class = "verse">Stand forth, unveil Thy face,  
<p class = "verse">Pour down the light  
<p class = "verse">That seethes above Thy throne,  
<p class = "verse">And blaze this devil&rsquo;s dance to darkness!  
<p class = "verse">Hear!  
<p class = "verse">Speak!  
<p class = "verse">In Christ&rsquo;s great name&mdash;
</div>
<hr/>
<div class="poem">
<p class = "verse">I hear.  
<p class = "verse">Forgive me, God.  
<p class = "verse">Above the thunder I hearkened;  
<p class = "verse">Beneath the silence, now,  
<p class = "verse">I hear.
</div>
<hr/>
<div class="poem">
<p class = "verse">(Wait, God, a little space.  
<p class = "verse">It is so strange to talk with Thee&mdash;
<p class = "verse">Alone!)
</div>
<hr/>
<div class="poem">
<p class = "verse">This gold?  
<p class = "verse">I took it.  
<p class = "verse">Is it Thine?  
<p class = "verse">Forgive; I did not know.
</div>

<div class="poem">
<p class = "verse">Blood? Is it wet with blood?  
<p class = "verse">&rsquo;Tis from my brother&rsquo;s hands.  
<p class = "verse">(I know; his hands are mine.)  
<p class = "verse">It flowed for Thee, O Lord.
</div>

<div class="poem">
<p class = "verse">War? Not so, not war:  
<p class = "verse">Dominion, Lord, and over black, not white.  
<p class = "verse">Black, brown and fawn,  
<p class = "verse">And not Thy chosen brood, O God,  
<p class = "verse">We murdered.
</div>

<div class="poem">
<p class = "verse">To build Thy kingdom,  
<p class = "verse">To drape our wives and little ones,  
<p class = "verse">And set their souls a&rsquo; glitter&mdash;  
<p class = "verse">For this we killed these lesser breeds  
<p class = "verse">And civilized their dead,  
<p class = "verse">Raping red rubber, diamonds, cocoa, gold.
</div>

<div class="poem">
<p class = "verse">For this, too, once, and in Thy name  
<p class = "verse">I lynched a Nigger&mdash;
</div>

<div class="poem">
<p class = "verse indent">(He raved and writhed,  
<p class = "verse indent">I heard him cry,  
<p class = "verse indent">I felt the life light leap and lie,  
<p class = "verse indent">I watched him crackle there, on high,  
<p class = "verse indent">I saw him wither!)
</div>
<hr/>
<div class="poem">
<p class = "verse">Thou?  
<p class = "verse">Thee?  
<p class = "verse">I lynched Thee?
</div>
<hr/>
<div class="poem">
<p class = "verse">Awake me, God, I sleep!  
</div>

<div class="poem">
<p class = "verse">What was that awful word Thou saidst?  
<p class = "verse">That black and riven Thing--was. it Thee?
<p class = "verse">That gasp&mdash;was it Thine?  
<p class = "verse">This pain&mdash;is it Thine?  
<p class = "verse">Are then these bullets piercing Thee?  
<p class = "verse">Have all the wars of all the world,  
<p class = "verse">Down all dim time, drawn blood from Thee?
<p class = "verse">Have all the lies, and thefts, and hates&mdash;
<p class = "verse">Is this Thy crucifixion, God,  
<p class = "verse">And not that funny little cross,  
<p class = "verse">With vinegar and thorns?
</div>
<hr/>
<div class="poem">
<p class = "verse">Help!  
<p class = "verse">I sense that low and awful cry—  
<p class = "verse">Who cries?  
<p class = "verse">Who weeps  
<p class = "verse">With silent sob that rends and tears—  
<p class = "verse">Can God sob?
</div>
<hr/>
<div class="poem">
<p class = "verse">Who prays?  
<p class = "verse">I hear strong prayers throng by,  
<p class = "verse">Like mighty winds on dusky moors—  
<p class = "verse">Can God pray?
</div>
<hr/>
<div class="poem">
<p class = "verse">Prayest Thou, Lord, and to me?  
<p class = "verse"><em>Thou</em> needest me?  
<p class = "verse">Thou <em>needest</em> me?  
<p class = "verse">Thou needest <em>me</em>?  
<p class = "verse">Poor wounded Soul!  
<p class = "verse">Of this I never dreamed. I thought&mdash;  
<p class = "verse"><em>Courage, God</em>,  
<p class = "verse"><em>I come!</em>
</div>

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Unrest (1920)](/Volumes/19/05/unrest.html)
* [Peace (1919)](/Volumes/17/02/peace.html)
* [In God's Gardens (1912)](/Volumes/03/06/in-gods-gardens.html)
* [Curtains of Pain (1917)](/Volumes/13/04/curtains_of_pain.html)
* [The Drama Among Black Folk (1916)](/Volumes/12/04/drama_among_black_folk.html)

<!-- Similar articles end here -->