
---
title: 'The Congressmen and the NAACP'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 2
  page: 85-87
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Mr. Peter Ten Eyke, representative from the 28th district, New York, writes: "It is my advice to you to drop agitating the things which you have outlined in your letter until such time as you find that the wild rumors are liable to become a reality." This, of course, he says "in all sympathy with your race," and it expresses exactly the attitude which the National Association for the Advancement of Colored People is fighting and which its questionnaire addressed to congressional candidates seems to prove is the right fight for us to make.

First, of course, and foremost, we have come across the men who do not care. George Nicholas, of Kentucky, says: "I do not desire your support. I am indifferent to your opposition."

Other congressmen are angry at the threat of non-support at the polls: Congressman Bathrick considers this "distinctly obnoxious and, I believe, liable to injure instead of help, the cause of the colored people." 

Others in considerable numbers seek to dodge the issue. Charles F. Wilcox, of New York, a Republican candidate, gives this remarkable excuse: "I have relatives now at the head of colored schools in the South. Under these circumstances I think you will understand my attitude sufficiently so that you will pardon my declining to answer specific questions at this time!" Griest, of Pennsylvania, draws himself up indignantly and is "surprised that a successor to the seat of Thaddeus Stevens should be subjected to this cross-examination."

Of course, we encounter the breezy optimist: "Nobody is thinking," of abrogating the Fourteenth and Fifteenth Amendment, says a Pennsylvania Democrat. There need be no antagonism between the races and "there is none," says a Pennsylvania Progressive. Then right on top of these answers comes an Indiana Democrat who wants segregation and "Jim-Crow" cars in the District of Columbia, and a Texan who wants not only this but the Fourteenth and Fifteenth Amendments repealed and the whole Negro race put out of the country. He adds gayly: "No Negroes vote in the Texas Democratic primaries, and very few Republicans vote in the general elections." He also sends a clipping from a Dallas paper entitled "Jump Up Nigger En Crack Yo' Heels." A native of North Carolina, running in Montana, also refuses to pledge himself as to the Fourteenth and Fifteenth Amendments, wants segregation and "will not oppose making invalid marriages of colored and white people."

All this indicates clearly the present problem, and it is pleasant to note that some politicians have clear ideas at least as to the general justice of our position. Phelan, of Massachusetts, says frankly: "I do not favor segregation, not 'Jim-Crow' cars nor anything of the sort. I believe the colored people should have the rights which our Constitution and laws give them." Osgood, a Massachusetts Progressive, is in favor "of equal social, legal and political rights for colored citizens." Niles, a New York candidate, says: "I shall in the future, as I have always in the past, on every occasion public or private, social or political, assail ANY and EVERY measure, of whatever kind or nature, or description, that is inspired by hatred for, or opposition to, ANY race, nationality or creed." And Murray Hulbert, of New York, says: "Talent knows no race or creed and I would accord to every man the full measure of reward which he merits."

Radicals like the Socialists and others speak strongly but not always with full comprehension of what they are saying. Thus, a Socialist of Minnesota declares "there is no race problem," and a candidate of the Socialist Labor Party in Maryland, is fighting for a society "where economic equality will be for all irrespective of race, creed or color." Weinstock, a Pennsylvania Progressive, says flatly: "The Fourteenth and Fifteenth Amendments are not enforced if social liberty as well as political liberty is not given to all our citizens irrespective of color or creed."

A Pennsylvania Socialist stands squarely for the right but complains that colored voters always vote for the "common enemy." John Burt, of Pennsylvania, voices the same thing and says feelingly: "Oh, how I wish your organization could guide aright the large population of colored people in this First Congressional District against the gang organization who has used them as so much merchandise for their own personal ends." 

What is it that makes colored people, and intelligent colored people, so often vote for bosses? It is undoubtedly the canny stand of men like Boise Penrose. Mr. Penrose stands right up and tersely says that he will support war amendments, that he is opposed to segregation and "Jim-Crow" cars, that he will vote against anti-intermarriage laws, and that he never justifies lynching.

It is interesting to note, however, that there is disagreement among our political leaders even in such fundamental matters as lynching. A Montana man confesses that he has sometimes justified lynching. An Ohio Republican is in favor of it in "some cases." A Pennsylvania Progressive who lives on a "college campus" wants it "very, very seldom;" and Edward Hart, a professor in Lafayette College, justifies it under certain "exceptional" circumstances! With such leaders can we blame the mob?

Perhaps the most striking thing about all these answers is the number of people who frankly say that they are not informed on the Negro problem; that they simply "do not know the facts." This is the severest condemnation of the past attitude of the colored people and their friends that could possibly be made. It is the business of people who want wrongs righted to let the world know just what the wrongs are. A Michigan man is "not at all familiar with these questions." Congressman Good has "not studied" segregation. A Pennsylvania man says his "information is too limited." An Illinois Progressive is "not sure about his attitude." A Michigan Democrat is "not informed." An Ohio Republican has not "fully considered the matter." A Minnesota Progressive wants "to know more," and so on through dozens of answers.

Naturally, the greatest wavering is on the question of intermarriage and the wavering shows how remiss the colored people have been in not making their attitude perfectly clear. It is a delicate and unpleasant subject which no one wants to argue and yet the results of not arguing it are so frightful that honest men are forced to state their opinion. The real problem is illustrated by a piece of news that comes to us this month from California:

A white policeman, F. A. Winter of Los Angeles, has been clandestinely meeting Juanita Nelson, an orphan colored girl. She has a child. The policeman, run to earth, acknowledges his fault and offers to marry the girl but THE LAWS OF CALIFORNIA PREVENT THIS!

Here, then, is the problem: Did the colored people want this girl to have a white husband? They most certainly did not. Did the white people want the policeman to have a colored wife? Evidently not. But the fact remains that these people wanted each other and what is a civilized world going to do about it? Of course, the first answer that rushes to the mouth of Gibbons, an Illinois Progressive, is "I am opposed to intermarriage on ethnological grounds as it deteriorates both races and is a stock process of extermination."

This is absolutely false, as anyone may learn by reading Dr. Loeb's article in this number of <span class="small-caps">The Crisis.</span> We have a perfect right to oppose racial intermarriage, but we have no right, consciously or unconsciously, to lie about the reasons.

Despite our predilections, the answer of Paxton Hibben, of Indiana, is absolutely the only decent answer: "*I shall vote to make no woman's children illegitimate*." It is not enough here to rely on general philanthropy. Linden Bates, of New York, states that "it is a basic Progressive policy" to protect women and children of "all races." But Gulley, just as good a Progressive, from Indiana, says: "I will not oppose a law making such marriages invalid."

Here, again, a large number of answers waver. Some think it is sufficient to say that they are "opposed to anti-racial marriage" but are not clear as to how it is to be stopped. Others want to stop it by law but would not have the law retroactive. What they would do in the California case they do not say.

Lee, of Colorado, expresses the attitude of a man who needs enlightenment: "I oppose racial intermarriage. It would seem to me, without having an opportunity to examine the matter pro and con, that a law making such marriage invalid is not a proper means of preventing the same and my present belief is that I would oppose it." There are some men, however, who are square and clear. Hobart, of Ohio, says: "There should be no different rule when white and colored marry than when white and white or black and black marry." A native-born southerner from Tennessee adds: "I am opposed to annulling any marriages anywhere by law." And C.R. Lawrence, a Massachusetts Progressive, has this clear word: "One cannot look upon many of the faces of our citizens and be blind to the blending to a more or less degree between the colored and white people and I would rather see this inevitable tendency accomplished rightfully than criminally. I fear no more affinity as to marriage between the white and colored people with the marriage bars down than up."

Finally, a few, but a very few people, perceive that the fight that this Association is making is not simply "for colored people." It is for the whole nation. As Representative Focht, of Pennsylvania, says: "Fifty or more members of Congress from southern states are there illegally;" and an Indiana Progressive adds, "The creation of rotten boroughs in this country is a negation of Republican government."

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Muddle (1916)](/Volumes/13/02/muddle.html)
* [The Next Step (1913)](/Volumes/06/02/next_step.html)
* [N.A.A.C.P. (1910)](/Volumes/01/02/NAACP.html)
* [Presidential Candidates (1916)](/Volumes/13/01/presidential_candidates.html)
* [An Open Letter to Woodrow Wilson (1913)](/Volumes/05/05/open_letter.html)

<!-- Similar articles end here -->