
---
title: 'The Election'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 2
  page: 82
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The chief matter of comfort to colored folk in the late election is the more evenly balanced power of the two great parties resulting from it. Neither Republicans nor Democrats can afford to defy 500,000 Negro voters in the next two years. The Republicans have disfranchised them in party councils and the Democrats have segregated them. With such a record both parties must do a lot of explaining.

We see the decline of Progressivism with regret. It had some splendid personalities and high ideals; but on the greatest human problem of the day it went at the very beginning violently and inexcusably wrong.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Political Straws (1923)](/Volumes/26/03/political_straws.html)
* [The Negro in Politics (1929)](/Volumes/36/11/negro_in_politics.html)
* [The Campaign of 1928 (1928)](/Volumes/35/12/campaign_of_1928.html)
* [Political Rebirth and the Office Seeker (1921)](/Volumes/21/03/political-rebirth.html)
* [The Negro Party (1916)](/Volumes/12/06/negro_party.html)

<!-- Similar articles end here -->