
---
title: 'Murder'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 2
  page: 80
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



We are preening ourselves as a nation because we are now at peace while civilized Europe is at war; but we must remember that the wars of peace are often quite as horrible as the murder of war. The United States has the unenviable and shameful notoriety of being the country where murder is more prevalent than in any other civilized land. There are in this country at least six times as many murders each year as in England, France and Germany; while Berlin has two murders for every hundred thousand of population, New York has six, Chicago has nine, Atlanta has twenty-three and Memphis has fifty-eight. The influence of the race problem can be directly traced by comparing southern and northern cities. Memphis, Charleston, Savannah, New Orleans, Atlanta, Nashville, Louisville, St. Louis and Cincinnati are hot-beds of homicide. It is not merely the murder of black men by white men in these cities, but also the murder of white men by black men, of white men by white men and of black men by black men. It is the atmosphere of violence and hatred and these things grow in the miasma of race prejudice.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Murder (1926)](/Volumes/32/03/murder.html)
* [Homicides (1921)](/Volumes/23/05/homicides.html)
* [Crime (1920)](/Volumes/19/04/crime.html)
* [Lynching (1927)](/Volumes/33/04/lynching.html)
* [Triumph (1911)](/Volumes/02/05/triumph.html)

<!-- Similar articles end here -->