---
title: 'Negro'
description: "In 1914 W.E.B. Du Bois in The Crisis argues that capitalizing Negro asserts racial respect and public recognition against dismissive usage."
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1914
subjects:
  - Capitalization of racial names (use of "Negro")
  - Racial nomenclature and respectful usage
  - Journalism editorial policy and style
  - Press standards (Associated Press practice)
people:
  - W.E.B. Du Bois
  - Lester A. Walton
places:
  - United States
organizations:
  - Associated Press
  - The Crisis
  - The New York Age
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 2
  page: 28-30
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display

categories:
  - "Art & Culture"
---

There are indications that the custom of extending courtesy to 150,000,000 of human beings by capitalizing the racial name which is most in use, is slowly increasing. The manager of the  Associated Press writes us:

> We have a broad rule to the effect that the word 'Negro' should be capitalized in our service, but we do not control the typographical appearance of the word as it appears in the newspapers.

> A little more than a year ago we sent out 900 copies of a letter from Mr. Lester A. Walton, of the Age, to the newspapers in the Associated Press, and I think the practice of capitalizing the word Negro is very general so far as I have been able to observe.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [That Capital 'N' (1916)](/Volumes/11/04/that_capital_n.html)
* [The Capital N (1930)](/Volumes/37/05/capital_n.html)
* [That Capital 'N' (1930)](/Volumes/37/02/that_capital_n.html)
* [Veiled Insults (1914)](/Volumes/07/06/veiled_insults.html)
* [The Name Negro (1928)](/Volumes/35/03/name_negro.html)

<!-- Similar articles end here -->