---
title: William Monroe Trotter
description: W.E.B. Du Bois in The Crisis (1914) praises William Monroe Trotter’s fearless defense of Black equality and criticizes Wilson’s paternalistic race views.
author:
- name:
    given: W.E.B.
    family: Du Bois
date: Jun. 1914
subjects:
- Racial segregation
- Racial equality
- Race relations
- Racial paternalism
people:
- William Monroe Trotter
- Woodrow Wilson
- W. E. B. Du Bois
places:
- United States
citation:
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 2
  page: 82
google-scholar: true
format:
  html:
    toc: false
    appendix-cite-as: display

categories:
  - "Segregation"
  - "Internal Debate"
---

William Monroe Trotter is a brave man. Of his fearlessness and his unselfish devotion to the highest interests of the Negro race there can be no doubt. 

President Woodrow Wilson is a keenly sensitive man. He has high ideals and he is following them. On one subject alone he is by birth and education unfitted for largeness of view or depth of feeling. His attitude on the Negro problem is essentially the attitude of the old philanthropic South of fifty years ago. He feels "kindly" toward Negroes, he wants to "help" them, he would not knowingly hinder them; but when it comes to treating black men as independent human beings, the equals of other citizens in the United States, the thing is simply beyond Mr. Wilson's conception. 

When two men like this come together to discuss segregation, granting them both honesty, good will and earnestness, as indeed we must, there is going to be trouble, if not anger and positive discourtesy. 

One thing is certain: Mr. Trotter voiced the feelings of nine-tenths of the thinking Negroes of this country. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The President (1915)](/Volumes/09/04/president.html)
* [William Monroe Trotter (1934)](/Volumes/41/05/trotter.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Another Open Letter to Woodrow Wilson (1913)](/Volumes/06/05/open_letter.html)
* [Mr. Taft (1911)](/Volumes/02/06/taft.html)

<!-- Similar articles end here -->