
---
title: 'Y.M.C.A'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 2
  page: 77, 80
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



We gave last month considerable space to the wonderful work of the colored Y.M.C.A. It is an extraordinary growth and the colored secretaries like Mr. Hunton and Mr. Mooreland, and white philanthropists like Julius Rosenwald, together with the governing heads of the whole movement deserve undoubtedly great credit. At the same time it must be remembered that directly in questions of this sort lurk the most baffling difficulties of our race problem.

The Y.M.C.A. movement in America is not acting in a Christian manner toward colored folk. In most cities colored people are, as in New York, excluded from all the well-equipped branches of the Y.M.C.A. and herded in a poorly equipped "colored" branch. In other cities like Boston and Providence recent attempts have been frustrated to do the same thing. In still other cities the Negroes are segregated but as we showed last month splendid new accommodations have been erected for them. What now should be the attitude of colored people and their friends toward this movement? Manifestly, here is a case for niceness of judgment but unerring adherence to principle. It is a fine thing that the colored people have such well-equipped Y.M.C.A. buildings in Chicago and Washington and Philadelphia, but it is an unchristian and unjust and dangerous procedure which segregates colored people in the Y.M.C.A. movement. However much we may be glad of the colored Y.M.C.A. movement on the one hand, on the other hand we must never for a single moment fail to recognize the injustice which has made it an unfortunate necessity.

