
---
title: 'Join or Die'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 3
  page: 133-134
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


<span class="crisis-title">The Crisis</span> exists for one great purpose.

<span class="crisis-title">The Crisis</span> seeks to entertain its readers, and entertainment is a legitimate object for a popular magazine. Our pictures, our stories and our ornamentation are for entertainment. But the object of <span class="crisis-title">The Crisis</span> is not simply to entertain.

<span class="crisis-title">The Crisis</span> seeks to inform. It is in the large sense a newspaper. It deals not so much with immediate news as with forgotten, neglected and concealed news. This is its great and notable
function, and gives <span class="crisis-title">The Crisis</span> a peculiar place among American periodicals.

But <span class="crisis-title">The Crisis</span> is not merely an entertaining newspaper.

<span class="crisis-title">The Crisis</span> entertains and informs its readers for the one object and the sole object of arousing their fighting blood. <span class="crisis-title">The Crisis</span> means fight and fight for Right.

More than that, <span class="crisis-title">The Crisis</span> stands for a definite method of fighting. <span class="crisis-title">The Crisis</span> does not simply protest or simply tell the unpalatable truth or simply cry fight wildly and crazily.

<span class="crisis-title">The Crisis</span> cries fight and adds: Here are weapons, and here is the battle line:

Join or die!

What are the weapons? Organized publicity, advertisement, public meetings, petitions, arrest, law suits, protest, investigation, research, resistance---every way in which the civilized world has fought and must fight and will fight wrong.

Where is the battle line?

The battle line is the <span class = "small-caps">National Association for the Advancement of Colored People</span>.

There are individual sharpshooters fighting their own effective guerrilla warfare. We greet them and give them all credit.

There are a few organizations here and there with some activity. We would not detract a moment from the value of their work.

But the flat fact remains:

There is in the United States but one organization with permanent headquarters, paid officials, active nation­wide membership, live local branches, a national organ, law officers and traveling organizers, all organized and prepared to make a front forward fight on racial prejudice in this land.
Here is the organization.

Here is the work to do.

Here are twenty local branches and over 2,100 members already banded for the warfare.
What are you doing?

Join or die!

Join the <span class = "small-caps">National Association for the Advancement of Colored People</span> or be strangled to a slow and awful death by growing prejudice.

There is no excuse.

The cost? It costs but a dollar.

The need? We need 200,000 members instead of a paltry 2,000.

The use? Merciful God! does a drowning man ask the USE of struggles? No, he struggles, he fights. He wins the shore or dies fighting.

Black men of America, are you men? Dare you fight?

Join us and fight, then.

Join or die!

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Crisis (1910)](/Volumes/01/01/TheCrisis.html)
* [We Come of Age (1915)](/Volumes/11/01/we_come_of_age.html)
* [Truth and Beauty (1922)](/Volumes/25/01/truth_and_beauty.html)
* [The Second Birthday (1912)](/Volumes/05/01/second_birthday.html)
* [The Gall of Bitterness (1912)](/Volumes/03/04/gail_of_bitterness.html)

<!-- Similar articles end here -->