
---
title: 'Free, White and Twenty One'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 3
  page: 134
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



We will suppose, dear reader, that you are "Free, white and twenty-one;" that you are reasonably patriotic and would rather the world grew
better than worse.

What should be your first duty? Will you pardon us for suggesting
membership in the National Association for the Advancement of Colored
People as your first and greatest duty?

Does the advice sound in your ears a bit grotesque and certainly myopic?

Pause, then, and consider:

Freedom is a state of mind: a spiritual unchoking of the wells of human power and superhuman love. Is
there anything in America that is so strangling brotherhood and
narrowing humanity and encouraging hatred, lust and murder as race
prejudice? Is there any conceivable crime that it does not daily excuse?
Any conceivable inhumanity that it may not deify? If you want freedom,
then join this association and fight race hatred.

You are "white." You want to remain "white." You want your children to
be "white." Very well. Your wish on this point may seem to some of us of
slightly less than infinite importance and yet this is your wish, and
the wish of any human being must be respected.

But do you realize that the one certain way to insure a future mulatto
world is to despise black folk? Do you realize that if you make this
world a hell for Africans and Chinese and Malays that
the result will be the rapid disappearance of race differentiation and
that, too, largely and predominantly by amalgamation?

If then you want to preserve the special characteristics of white
peoples, make it possible for darker peoples to preserve their racial
characteristics without loss of freedom and self-respect.

You are twenty-one---*i. e.,* you can vote. Or at least you think you
can. Or if you are really wise you know what a farce voting is in this
land. Why? Because a Southern voter has from twice to seven times the
power of a Northern voter and South Carolina far outweighs Illinois in
political significance. Because political democracy cannot be linked
with industrial despotism, else the result is the rule of the rich.
Now industrial despotism is founded on slavery and peonage, rack rent
and low wages. Negroes were slaves, they are peons, they are rack rented
and receive less than can support them in decency. Against them white
workingmen must compete and the votes stolen from Negroes are used by
white capitalists to keep the laborer in bondage. Is your vote safe then
as long as disfranchisement and peonage are in the land?

Wherefore, as one who, is "Free, white and twenty-one," come and join us
and help accomplish freedom, safeguard legitimate pride of being and
make democracy real.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Awake America (1917)](/Volumes/14/05/awake_america.html)
* [Freedom of Speech (1930)](/Volumes/37/08/freedom.html)
* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)
* [White Co-Workers (1920)](/Volumes/20/01/white_coworkers.html)
* [The Present (1917)](/Volumes/14/04/present.html)

<!-- Similar articles end here -->