
---
title: 'The Song of the Smoke'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 3
  page: 132
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



<div class="poem">
<p class = "verse">I am the smoke king,</p>
<p class = "verse">I am black.</p>
<p class = "verse indent">I am swinging in the sky,</p>
<p class = "verse indent">I am ringing worlds on high;</p>
<p class = "verse indent">I am the thought of the throbbing mills,</p>
<p class = "verse indent">I am the soul of the Soul toil kills,</p>
<p class = "verse indent">I am the ripple of trading rills.</p>
<p class = "verse">Up I'm curling from the sod,</p>
<p class = "verse">I am whirling home to God.</p>
<p class = "verse">I am the smoke king,</p>
<p class = "verse">I am black.
</div>

<div class="poem">
<p class = "verse">I am the smoke king,
<p class = "verse">I am black.
<p class = "verse indent">I am wreathing broken hearts,
<p class = "verse indent">I am sheathing devils' darts;
<p class = "verse indent">Dark inspiration of iron times,
<p class = "verse indent">Wedding the toil of toiling climes,
<p class = "verse indent">Shedding the blood of bloodless crimes,
<p class = "verse">Down I lower in the blue,
<p class = "verse">Up I tower toward the true.
<p class = "verse">I am the smoke king,
<p class = "verse">I am black.
</div>

<div class="poem">
<p class = "verse">I am the smoke king,
<p class = "verse">I am black.
<p class = "verse indent">I am darkening with song,
<p class = "verse indent">I am hearkening to wrong;
<p class = "verse indent">I will be black as blackness can,
<p class = "verse indent">The blacker the mantle the mightier the man,
<p class = "verse indent">My purpl'ing midnights no day dawn may ban. 
<p class = "verse">I am carving God in night,
<p class = "verse">I am painting Hell in white.
<p class = "verse">I am the smoke king,
<p class = "verse">I am black.
</div>

<div class="poem">
<p class = "verse">I am the smoke king,
<p class = "verse">I am black.
<p class = "verse indent">I am cursing ruddy morn,
<p class = "verse indent">I am hearsing hearts unborn;
<p class = "verse indent">Souls unto me are as mists in the night,
<p class = "verse indent">I whiten my black men, I blacken my white, 
<p class = "verse indent">What's the hue of a hide to a man in his might!
<p class = "verse">Hail, then, gritty, grimy hands,
<p class = "verse">Sweet Christ, pity toiling lands!
<p class = "verse">Hail to the smoke king,
<p class = "verse">Hail to the black!
</div>

(Original version first published in the *Horizon*)

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Burden of Black Women (1914)](/Volumes/09/01/burden_of_black_women.html)
* [Joseph Pulitzer (1911)](/Volumes/03/02/joseph_pulitzer.html)
* [Curtains of Pain (1917)](/Volumes/13/04/curtains_of_pain.html)
* [The Drama Among Black Folk (1916)](/Volumes/12/04/drama_among_black_folk.html)
* [In God's Gardens (1912)](/Volumes/03/06/in-gods-gardens.html)

<!-- Similar articles end here -->