
---
title: 'The Strength of Segregation'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 2
  page: 84
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



When the American people in their carelessness and impudence have finally succeeded in welding 10,000,000 American Negroes into one great self-conscious and self-acting mass they will realize their mistake.

At present it is still possible to make Negroes essentially Americans with American ideals and instincts. In another generation, however, at the present rate we will have in this country a mass of people of colored blood acting together like one great fist for their own ends, with secret understanding, with pitiless efficiency and with resources for defense which will make their freedom incapable of attack from without.

The actual organization of this group is progressing by leaps and bounds. It needs now but to be knit together into one great unity. This can be done---it is being done. Those who advise "race pride" and "self-reliance" do not realize the Frankenstein which they are evoking. The Negro cannot be beaten in this line by any present methods. The physical intimidation of lynching cannot be kept up; the economic intimidation of exclusion from work cannot, with the present organization of Negro industry, be kept up after ten years. Continual social insult is powerless against those who refuse to be insulted. After this---what? What can America do against a mass of people who move through their world but are not of it and stand as one unshaken group in their battle? Nothing. The yell of the segregationist is the last scream of beaten prejudice. After that American civilization will be compelled through long centuries to tear down the walls which they are now building around the finest and most gifted single group in its polyglot population.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Unity (1924)](/Volumes/28/03/unity.html)
* [The Immediate Program of the  American Negro (1915)](/Volumes/09/06/immediate_program.html)
* [Crime (1920)](/Volumes/19/04/crime.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)

<!-- Similar articles end here -->