
---
title: 'Hayti'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 6
  page: 291
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The United States has violated the independence of a sister state. With absolutely no adequate excuse she has made a white American Admiral sole and irresponsible dictator of Hayti. The anarchy in Hayti is no worse than the anarchy in the United States at the time of our Civil War, and not as great as the anarchy today in Europe. The lynching and murder in Port-au-Prince is no worse than, if as bad as, the lynching in Georgia. Hayti can, and will, work out destiny and is more civilized today than Texas. 

Here, then, is the outrage of uninvited American intervention, the shooting and disarming of peaceful Haytian citizens, the seizure of public funds, the veiled, but deliberate design to alienate Haytian territory at the Mole St. Nicholas, and the pushing of the monopoly claims of an American corporation which holds a filched, if not a fraudulent railway charter. SHAME ON AMERICA! And what are we ten million Negroes going to do about it? Can you not at least do this? Write to President Wilson and protest; ask for a distinct, honest statement of our purposes in Hayti and an American Commission of white and colored men to point the way of Honor instead of Graft. WRITE NOW and let the Editor of <span class = "small-caps">The Crisis</span> have a copy of your letter.

______
*Citation:* Du Bois, W.E.B. 1915. "Hayti." *The Crisis*. 10(6):291.