
---
title: 'Coffeeville, Kanasas'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jul. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 5
  page: 167
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Two white high school girls in a Kansas city of 20,000 inhabitants claim to have been raped by Negroes on March 17. Blood hounds are brought. They lead to the Negro quarter and three Negroes are arrested. Two of them are discharged but the other is held. On March 18 a mob of 2,000 attack the City Hall in order to lynch this black man. The mob damages the City Hall, loots stores and chases Negroes. Twenty or more Negroes arm themselves and gather in a pool room. Two of their leaders, Anderson and Ford, shoot into the mob and check it, although themselves desperately wounded. They are now under arrest and on trial for "inciting to riot." Finally, the National Guard of the state is called out to guard the frenzied town. Eighteen white persons are arrested for rioting but all are discharged except one.

Meantime, the colored man arrested is released when the girls declare he was not guilty. Then the city awakes from its orgy. Colored people offer rewards aggregating $423 to find the rapists. Afterward, the white officials offer $2,200 in rewards. Forty-five thousand dollars in damage suits are filed against the city and others are still to come.

Then the truth begins to leak out. The white people try to hush the matter up but the Negroes petition for a Grand Jury. The Coffeeville *Daily Journal* acknowledges, May 30, that white men and not Negroes were the bedfellows of the two girls and one white man is today in jail charged with rape while one of the girls is also in jail as accessory. What comment is adequate?

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Mob Tactics (1927)](/Volumes/34/06/mob_tactics.html)
* [The Challenge of Detroit (1925)](/Volumes/31/01/challenge_of_detroit.html)
* [Lynchings and Mobs (1921)](/Volumes/22/04/lynchings.html)
* [Crime (1920)](/Volumes/19/04/crime.html)
* [Prejudice (1911)](/Volumes/02/01/prejudice.html)

<!-- Similar articles end here -->