
---
title: 'Flood'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jul. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 5
  page: 169
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


We hope that every Negro that can
escape from the slave camps guarded
by the National Red Cross for the
benefit of the big planters of Mississippi
and Louisiana and the lynchers
of Arkansas will leave this land of
deviltry at the first opportunity. Let
them ride, run and crawl out of this
hell. There is no hope for the black
man there today. Relief funds are
being used to pamper white folk
and in some cases are actually being
sold to black folk as the basis of contracts 
for their compulsory services in
the future. Fully 75 per cent of the
refugees have been Negroes and we
doubt if they have received 25 per cent
of the relief funds.

We do not know where the refugees
from the Mississippi bottoms can go,
but we are frank to say it would be
better for them to starve in Memphis
and Chicago than to be slaves in
Arkansas and Mississippi. Even if eventually
they have to return, they can
make better terms than by staying.

And they can expect no help from
Coolidge or Hoover. Mr. Hoover is
too busy having his picture taken and
Mr. Coolidge, when the Arkansas
mob burns the body of an imbecile,
feeding the bonfire with lumber torn
from a Negro church, while the
Mayor of the city keeps the Negro
leaders imprisoned in their own 
business block---Mr. Coolidge tells the
world of the privileges of American
civilization.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Migration of Negroes (1917)](/Volumes/14/02/migration_of_negroes.html)
* [The Migration (1917)](/Volumes/14/01/migration.html)
* [Brothers, Come North (1920)](/Volumes/19/03/brothers_come_north.html)
* [Peonage (1927)](/Volumes/34/09/peonage.html)
* [Slavery (1922)](/Volumes/24/01/slavery.html)

<!-- Similar articles end here -->