
---
title: 'On the Fence'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Nov. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 11
  page: 381
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


In this presidential campaign <span class="crisis-title">The Crisis</span> is sitting squarely on the fence, naked and unashamed and without apology. It is certain that either Herbert Hoover or Al Smith is going to be elected President of the United States, and in our humble opinion, it does not matter a tinker's damn which of these gentlemen succeed. With minor exceptions, they stand for exactly the same thing: oligarchy in the South; color caste in national office holding; and recognition of the rule of organized wealth. We do not believe that there is a jot or tittle of difference between these two men in their attitude toward these fundamental matters, and we sincerely advise our readers to vote for neither of them.

On the other hand, we repeat advice which we have given many times before: it is of the utmost importance that Negro voters register and vote for Congressmen who are the friends of Industrial Democracy and who do not believe in the color bar. A Congress filled with men of this sort will do much to curb the Bourbon South led by Al Smith, or entrenched plutocracy represented by Herbert Hoover.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Houston (1928)](/Volumes/35/09/houston.html)
* [The Election (1928)](/Volumes/35/12/election.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [Muddle (1916)](/Volumes/13/02/muddle.html)
* [Political Rebirth and the Office Seeker (1921)](/Volumes/21/03/political-rebirth.html)

<!-- Similar articles end here -->