
---
title: 'Marcus Garvey'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 21
  issue: 3
  page: 112-115
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


*An article in the December <span style="small-caps">Crisis</span> gave Mr. Garvey's personal history. This article considers his industrial enterprises and the feasibility of his general plans.*

When it comes to Mr.Garvey's industrial and commercial enterprises there is more ground for doubt and misgiving than in the matter of his character. First of all, his enterprises are incorporated in Delaware, where the corporation laws are loose and where no financial statements are required.[^fn2] So far as I can find, and I have searched with care, Mr. Garvey has never published a complete statement of the income and expenditures of the Negro Improvement Association or of the Black Star Line or of any of his enterprises, which really revealed his financial situation. A courteous letter of inquiry sent to him July 22, 1920, asking for such financial data as he was willing for the public to know, remains to this day unacknowledged and unanswered.

[^fn2]: Mr. Garvey boasts Feb. 14, 1920: "This week I present you with the Black Star Line Steamship Corporation recapitalized at ten million dollars. They told us when we incorporated this corporation that we could not make it, but we are now gone from a $5,000,000 corporation to one of $10,000,000." This sounds impressive, but means almost nothing. The fee for incorporating a $5,000,000 concern in Delaware is $350. By *paying $250 more the corporation may incorporate with $10,000,000 authorized capital without having a cent of capital actually paid in!* Cf. "General Corporation Laws of the State of Delaware," edition of 1917. 

Now a refusal to publish a financial statement is no proof of dishonesty, but it *is* proof that either Garvey is ill-advised and unnecessarily courting suspicion, or that his industrial enterprises are not on a sound business basis; otherwise he is too good an advertiser not to use a promising balance sheet for all it is worth. 

There has been one balance sheet, published July 26, 1920, purporting to give the financial condition of the Black Star Line after one year of operation; neither profit or loss is shown, there is no way to tell the actual cash receipts or the true condition of the business. 
Nevertheless it does make some interesting revelations. 

The total amount of stock subscribed for is $590,860. Of this $118,153.28 is not yet paid for, leaving the actual amount of paid-in capital charged against the corporation, $472,706.72. Against this stands only $355,214.59 of assets (viz.: $21,985.21 in cash deposits and loans receivable; $12,975.01 in furniture and equipment, $288,515.37 which is the alleged value of his boats, $26,000 in real estate and $5,739 of insurance paid in advance). To offset the assets he has $152,264.14 of other liabilities (accrued salaries, $1,539.30; notes and accounts payable, $129,224.84; mortgages due $21,500). In other words, his capital stock of $472,706.72 is after a year's business impaired to such extent that he has only $202,950.45 to show for it. 

Even this does not reveal the precariousness of his actual business condition. Banks before the war in lending their credit refused to recognize any business as safe unless for every dollar of current liabilities there were *two* dollars of current assets. Today, since the war, they require *three* dollars of current assets to every *one* of current liabilities. The Black Star Line had July 26, $16,485.21 in current assets anc $130,764.14 in current liabilities, when recognition by any reputable bank called for $390,000 in current assets. 

Moreover, another sinister admission appears in this statement: the cost of floating the Black Star Line to date has been $289,066.27. In other words, it has cost nearly $300,000 to collect a capital of less than half a million. Garvey has, in other words, spent more for advertisement than he has for his boats! 

This is a serious situation, and even this does not tell the whole story: the real estate, furniture, etc., listed above, are probably valued correctly. But how about the boats? The *Yarmouth* is a wooden steamer of 1,452 gross tons, built in 1887 It is old and unseaworthy; it came near sinking a year ago and it has cost a great deal for repairs. It is said that it is now laid up for repairs with a large bill due. Without doubt the inexperienced purchasers of this vessel paid far more than it is worth, and it will soon be utterly worthless unless rebuilt at a very high cost.[^fn3]

[^fn3]: Technically the Yarmouth does not belong to the Black Star Line of Delaware, but to the "Black Star Line of Canada, Limited," incorporated in Canada, March 23, 1920, with one million dollars capital. This capital consists of $500 cash and $999,500 "assets." Probably the Black Star Line of Delaware controls this corporation, but this is not known. 

The cases of the *Kanawha* (or *Antonio Maceo*) and the *Shadyside* are puzzling. Neither of these boats is registered as belonging to the Black Star Line at all. The former is recorded as belonging to C. L. Dimon, and the latter to the North and East River Steamboat Company. Does the Black Star Line really own these boats, or is it buying them by installments, or only leasing them? We do not know the facts and have been unable to find out. Under the circumstances they look like dubious "assets." 

The majority of the Black Star stock is apparently owned by the Universal Negro Improvement Association. There is no reason why this association, if it will and can, should not continue to pour money into its corporation. Let us therefore consider then Mr. Garvey's other resources. 

Mr. Garvey's income consists of (a) dues from members of the U.N.I. Association; (b) shares in the Black Star Line and other enterprises, and (c) gifts and "loans" for specific objects. If the U.N.I. Association has "3,000,000 members" then the income from that source alone would be certainly over a million dollars a year. If, as is more likely, it has under 300,000 paying members, he may collect $150,000 annually from this source. Stock in the Black Star Line is still being sold. Garvey himself tells of one woman who had saved about four hundred dollars in gold: "She brought out all the gold and bought shares in the Black Star Line." Another man writes this touching letter from the Canal Zone: "I have sent twice to buy shares amounting to $125, (numbers of certificates 3752 and 9617). Now I am sending $35 for seven more shares. You might think I have money, but the truth, as I stated before, is that I have no money now. But if I'm to die of hunger it will be all right because I'm determined to do all that's in my power to better the conditions of my race."[^fn4]

[^fn4]: P.N. Gordon

In addition to this he has asked for special contributions. In the spring of 1920 he demanded for his coming convention in August, "a fund of two million dollars ($2,000,000) to capitalize this, the greatest of all conventions." In October he acknowledged a total of something over $16,000 in small contributions. Immediately he announced "a constructive loan" of $2,000,000, which he is presumably still seeking to raise.[^fn5]

[^fn5]: "The Universal Negro Improvement Association is raising a constructive loan of two million dollars from its members. Three hundred thousand dollars out of this two million has been allotted to the New York Local as its quota, and already the members in New York have started to subscribe to the loan, and in the next *seven days* the three hundred thousand dollars will be oversubscribed. The great divisions of Pittsburgh, Philadelphia, Boston, Chicago, Cleveland, Wilmington, Baltimore and Washington will also over subscribe their quota to make up the two million dollars." <br> Constructive work will be started in January 1921, when the first ship of the Black Star Line on the African trade will sail from New York with materials and workmen for this constructive work." <br> Eleven days later, November 6th, the *Negro World* is still "raising the loan" but there is no report of the amount raised. 

From these sources of income Mr. Garvey has financed his enterprises and carried on a wide and determined propaganda, maintained a large staff of salaried officials, clerks and agents, and published a weekly newspaper. Notwithstanding this considerable income, there is no doubt that Garvey's expenditures are pressing hard on his income, and that his financial methods are so essentially unsound that unless he speedily revises them the investors will certainly get no dividends and worse may happen.[^fn6] He is apparently using the familiar method of "Kiting"---*i.e.*, the money which comes in as investment in stock is being used in current expenses, especially in heavy overhead costs, for clerk hire, interest and display. Even his boats are being used for advertisement more than for business---lying in harbors as exhibits, taking excursion parties, etc. These methods have necessitated mortgages on property and continually new and more grandiose schemes to collect larger and larger amounts of ready cash. Meantime, lacking business men of experience, his actual business ventures have brought in few returns, involved heavy expense and threatened him continually with disaster or legal complication. 

[^fn6]: It might be argued that it is not absolutely necessary that the Black Star Line, etc., should pay financially. It is quite conceivable that Garvey should launch a business philanthropy, and that without expectation of return, colored people should contribute for a series of years to support Negro enterprise. But this is not Garvey's idea. He says plainly in a circular: <br> The Black Star Line corporation presents to every Black Man, Woman and Child the opportunity to climb the great ladder of industrial and commercial progress. If you have ten dollars, one hundred dollars, or one or five thousand dollars to invest for profit, then take out shares in The Black Star Line, Inc. This corporation is chartered to trade on every sea and all waters. The Black Star Line will turn over large profits and dividends to stockholders, and operate to their interest even whist they will be asleep." 

On the other hand, full credit must be given Garvey for a bold effort and some success. He has at least put vessels manned and owned by black men on the seas and they have carried passengers and cargoes. The difficulty is that he does not know the shipping business, he does not understand the investment of capital, and he has few trained and staunch assistants. 

The present financial plight of an inexperienced and headstrong promoter may therefore decide the fate of the whole movement. This would be a calamity. Garvey is the beloved leader of tens of thousands of poor and bewildered people who have been cheated all their lives. His failure would mean a blow to their faith, and a loss of their little savings, which it would take generations to undo. 

Moreover, shorn of its bombast and exaggeration, the main lines of the Garvey plan are perfectly feasible. What he is trying to say and do is this: American Negroes can, by accumulating and ministering their own capital, organize industry, join the black centers of the south Atlantic by commercial enterprise and in this way ultimately redeem Africa as a fit and free home for black men. This is true. It is feasible. It is, in a sense, practical; but it will take for its accomplishment long years of painstaking, self-sacrificing effort. It will call for every ounce of ability, knowledge, experience and devotion in the whole Negro race. It is not a task for one man or one organization, but for co-ordinate effort on the part of millions. The plan is not original with Garvey but he has popularized it, made it a living, vocal ideal and swept thousands with him with intense belief in the possible accomplishment of the ideal. 

This is a great, human service; but when Garvey forges ahead and almost single-handed attempts to realize his dream in a few years, with large words and wild gestures, he grievously minimizes his task and endangers his cause. 

To instance one illustrative fact: there is no doubt but what Garvey has sought to import to America and capitalize the antagonism between blacks and mulattoes in the West Indies. This has been the cause of the West Indian failures to gain headway against the whites. Yet Garvey imports it into a land where it has never had any substantial footing and where today, of all days, it is absolutely repudiated by every thinking Negro; Garvey capitalizes it, has sought to get the cooperation of men like R. R. Moton on this basis, and has aroused more bitter color enmity inside the race than has ever before existed. The whites are delighted at the prospect of a division of our solidifying phalanx, but their hopes are vain. American Negroes recognize no color line in or out of the race, and they will in the end punish the man who attempts to establish it. 

Then too Garvey increases his difficulties in other directions. He is a British subject. He wants to trade in British territory. Why then does he needlessly antagonize and even insult Britain? He wants to unite all Negroes. Why then does he sneer at the work of the powerful group of his race in the United States where he finds asylum and sympathy? Particularly, why does he decry the excellent and rising business enterprises of Harlem---intimating that his schemes alone are honest and sound when the facts flatly contradict him? He proposes to settle his headquarters in Liberia---but has he asked permission of the Liberian government? Does he presume to usurp authority in a land which has successfully withstood England, France and the United States,---but is expected tamely to submit to Marcus Garvey? How long does Mr. Garvey think that President King would permit his anti-English propaganda on Liberian soil, when the government is straining every nerve to escape the Lion's Paw? 

And, finally, without arms, money, effective organization or base of operations, Mr. Garvey openly and wildly talks of "Conquest" and of telling white Europeans in Africa to "get out!" and of becoming himself a black Napoleon!

Suppose Mr. Garvey should drop from the clouds and concentrate on his industrial schemes as a practical first step toward his dreams: the first duty of a great commercial enterprise is to carry on effective commerce. A man who sees in industry the key to a situation, must establish sufficient businesslike industries. Here Mr. Garvey has failed lamentably. 

The *Yarmouth*, for instance, has not been a commercial success. Stories have been published alleging its dirty condition and the inexcusable conduct of its captain and crew. To this Mr. Garvey may reply that it was no easy matter to get efficient persons to run his boats and to keep a schedule. This is certainly true, but if it is difficult to secure one black boat crew, how much more difficult is it going to be to "build and operate factories in the big industrial centers of the United States, Central America, the West Indies and Africa to manufacture every marketable commodity"? and also "to purchase and build ships of larger tonnage for the African and South American trade"? and also to raise "Five Million Dollars to free Liberia" where "new buildings are to be erected, administrative buildings are to be built, colleges and universities are to be constructed"? and finally to accomplish what Mr. Garvey calls the "Conquest of Africa!" 

To sum up: Garvey is a sincere, hard-working idealist; he is also a stubborn, domineering leader of the mass; he has worthy industrial and commercial schemes but he is an inexperienced business man. His dreams of Negro industry, commerce and the ultimate freedom of Africa are feasible; but his methods are bombastic, wasteful, illogical and ineffective and almost illegal. If he learns by experience, attracts strong and capable friends and helpers instead of making needless enemies; if he gives up secrecy and suspicion and substitutes open and frank reports as to his income and expenses, and above all if he is willing to be a co-worker and not a czar, he may yet in time succeed in at least starting some of his schemes toward accomplishment. But unless he does these things and does them quickly he cannot escape failure. 

Let the followers of Mr. Garvey insist that he get down to bed-rock business and make income and expense balance; let them gag Garvey's wilder words, and still preserve his wide power and influence. American Negro leaders are not jealous of Garvey---they are not envious of his success; they are simply afraid of his failure, for his failure would be theirs. He can have all the power and money that he can efficiently and honestly use, and if in addition he wants to prance down Broadway in a green shirt, let him---but do not let him foolishly overwhelm with bankruptcy and disaster one of the most interesting spiritual movements of the modern Negro world. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Marcus Garvey and the NAACP (1928)](/Volumes/35/02/marcus_garvey.html)
* [Marcus Garvey (1920)](/Volumes/21/02/garvey.html)
* [A Correction (1921)](/Volumes/21/05/correction.html)
* [Our Economic Peril (1930)](/Volumes/37/03/our_economic_peril.html)
* [A Lunatic or a Traitor (1924)](/Volumes/28/01/lunatic_or_a_traitor.html)

<!-- Similar articles end here -->