
---
title: 'Disenfranchisement'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1925
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 30
  issue: 2
  page: 62-63
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


How is the Negro disenfranchised? The process is so complicated that few Negroes themselves know definitely. Beginning with 1890 laws have been passed in various Southern states which today disfranchise approximately four million Negroes 21 years of age and over, over half of whom can read and write and who own property which runs into the hundreds of millions. The restrictions by which these have been accomplished are eight in number:
1. Illiteracy: The voter must be able to read and write.
2. Property: The voter must own a certain amount of property.
3. Poll Tax: The voter must have paid his poll tax for the present year or for a series of years.
4. Employment: The voter must have regular employment.
5. Army service: Soldiers in the Civil War and certain other wars, or their descendants, may vote.
6. Reputation: Persons of good reputation who understand the duties of a citizen may vote.
7. "Grandfather" clause: Persons who could vote before the freedmen were enfranchised or descendants of such persons may vote.
8. Understanding clause: Persons may vote who understand some selected clause of the Constitution and can explain it to the satisfaction of the registration officials.

The laws are often obscurely drawn and many of them have not had full judicial determination but apparently these restrictions are distributed as follows:

1890---Mississippi (1 or 8) +3.    
1895---South Carolina 1 or 2 or 8.    
1898---Louisiana (1+2) or 7.    
1901---North Carolina (1+3) or 7.    
1901---Alabama (1+4) or 2 or 5 or 6.    
1902---Virginia (1+3 or 5) or 8 or 2.    
1909---Georgia 1 or 2 or 5 or 6.    

That is, in Mississippi the voter must be able to read and write or he must understand and explain a section of the Constitution read to him and, in addition to that, he must have paid his poll tax, etc.

The Grandfather Clause, No. 7, has been declared unconstitutional but as it was in force for nearly a generation most illiterate white people were able to register under it.

The effect of these laws can be illustrated in the case of Louisiana where out of 147,348 colored men 21 years of age and over, of whom 57,000 were reported to be able to read and write, there were in 1908 only 1,743 voters.

But all this amounts to nothing as compared with the effect of the White Primary. The White Primary is based on law and custom and is legally the primary election of the Democratic Party. In fact, the Democratic Party admits to this primary any white person who wishes to vote on condition that he pledge himself to stand by the decision of the primary. On the other hand, no Negro is allowed to vote in the White Primary save in exceptional cases. The White Primary therefore becomes the real election and all over the country the newspapers report the results of primary elections in the South as the real decision. When the legal election takes place very few people vote. I lived 13 years in the city of Atlanta where in a population increasing from 100,000 to 200,000 people, usually 700 votes were cast in the legal election.

In addition to the power of disfranchisement thus held by the White Primary there is social and economic pressure. Colored men are continually told to keep out of politics or lose their jobs and it has become a point of honor with many Negroes of education and character not to vote nor even to attempt to vote. It is in this way that democratic government is made of no account in a large portion of the United States and it is against this that the N.A.A.C.P. is fighting in its latest judicial case against the White Primary of Texas.

