
---
title: 'Carrizal'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 4
  page: 165
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Carrizal was a glory and a blunder, a joke and a crucifixion; a blunder
on the part of a President who sent an army on a fool's errand and on
the part of a gay, young officer who needlessly risked human life on the
theory that Mexicans always run.

Carrizal was a glory for the Mexicans who dared to defend their country
from invasion and for Negro troopers who went singing to their death.
And the greater glory was the glory of the black men, for Mexicans died
for a land they love, while Negroes sang for a country that despises,
cheats and lynches them. Even across the sunlit desert as they died came
the last wild shriek of a human bon-fire in Texas where Southern
"gentlemen" and "ladies" capered in glee---brave, filthy Texas. Laugh?
Why shouldn't they laugh at simple death and grim duty? Have they not
faced harsher and more horrible things? "Jim Crow" cars, helpless
disfranchisement and organized insult? Why should they not laugh at
death for a country which honors them dying and kicks and buffets them
living? God laughed. It was a Joke.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [To the Rescue (1916)](/Volumes/12/01/rescue.html)
* [Officers (1917)](/Volumes/14/02/officers.html)
* [Dodging the Issue (1933)](/Volumes/40/02/dodging_the_issue.html)
* [Prejudice (1911)](/Volumes/02/01/prejudice.html)
* [The Immediate Program of the  American Negro (1915)](/Volumes/09/06/immediate_program.html)

<!-- Similar articles end here -->