
---
title: 'Ireland'
author: Du Bois, W.E.B.
date: Feb. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 4
  page: 166-167
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Few colored people know or realize what Ireland has suffered at the hands of England. On the other hand, the open dislike of Irish and colored people in the United States has given the Irish cause little or no sympathy so far as Negroes are concerned.

It happened unfortunately that the first Irish immigration to the United States took place just as the free Negroes of the North were making their most impressive forward movement. Irishmen and black men came, therefore, in bitter industrial competition in such cities as Boston, New York and Philadelphia. Riots and street fights ensued. Irishmen hanged Negroes during the draft riots in New York City, and drove them off the streets in Philadelphia.

But all this is past. Today we must remember that the white slums of Dublin represent more bitter depths of human degradation than the black slums of Charleston and New Orleans, and where human oppression exists there the sympathy of all black hearts must go. The recent Irish revolt may have been foolish, but would to God some of us had sense enough to be fools!

