
---
title: 'Marcus Garvey and the NAACP'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 2
  page: 51
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Many persons are under the impression that the N.A.A.C.P. has been the persistent enemy of Marcus Garvey. This is due to repeated accusations published in the *Negro World* without the slightest basis of fact. For the sake of the truth, it may be well to recall certain matters of clear record.

The Crisis has published five articles on Marcus Garvey. The first two articles, March 1920 and January 1921 ended with this summary:

> To sum up: Garvey is a sincere, hard-working idealist; he is also stubborn, domineering leader of the mass; he has worthy industrial and commercial schemes but he is an inexperienced business man. His dreams of Negro industry, commerce and the ultimate freedom of Africa are feasible; but his methods are bombastic, wasteful, illogical and ineffective and almost illegal. If he learns by experience, attracts strong and capable friends and helpers instead of making needless enemies; if he gives up secrecy and suspicion and substitutes open and frank reports as to his income and expenses, and above all if he is willing to be a co-worker and not a czar, he may yet in time succeed in at least starting some of his schemes toward accomplishment. But unless he does these things and does them quickly he cannot escape failure.

No more prophetic word was ever written about Marcus Garvey! The third and fourth articles dealt with the Black Star Line and the Universal Negro Improvement Association and were based on published documents with little comment.

It was not until September, 1922, that The Crisis had a sharp word of criticism. This was based on Garvey's threats against his critics, his connection with the Ku Klux Klan and his distribution of pamphlet propaganda against American Negroes. We quoted, among other things, this:

> The white race can best help the Negro by telling him the truth, and not by flattering him into believing that he is as good as any white man.

Concerning this we said:

> Not even Tom Dixon or Ben Tillman or the hatefulest enemies of the Negro have ever stooped to a more vicious campaign than Marcus Garvey, sane or insane, is carrying on. He is not attacking white prejudice, he is grovelling before it and applauding it; his only attack is on men of his own race who are striving for freedom; his only contempt is for Negroes; his only threats are for black blood.

On the other hand Garvey's attacks on the N. A. A. C. P. have been continuous, preposterous and false. He has claimed:

1. That we kept his representative from activity in Paris in 1919.
2. That Moorfield Storey came from Boston to secure his conviction in 1924.
3. That the collapse of the Black Star Line came about "because men were paid to make this trouble by certain organizations calling themselves Negro Advancement Associations. They paid men to dismantle our machinery and otherwise damage it so as to bring about the downfall of the movement."
4. That the N.A.A C.P. was responsible for his incarceration and deportation.

Every single statement in these and dozens of similar charges are absolutely false and without any basis of fact whatsoever. As The Crisis said in May, 1924:

> No Negro in America ever had a fairer and more patient trial than Marcus Garvey. He convicted himself by his own admissions, his swaggering monkey-shines in the court room with monocle and long tailed coat and his insults to the judge and prosecuting attorney.    
> &nbsp;    
> Marcus Garvey was long refused bail, not because of his color, but because of the repeated threats and cold-blooded assaults charged against his organization. He himself openly threatened to 'get' the District Attorney. His followers had repeatedly to be warned from intimidating witnesses and one was sent to jail therefor. One of his former trusted officials after being put out of the Garvey organization brought the long concealed cash account of the organization to this office and we published it. Within two weeks the man was shot in the back in New Orleans and killed.    
> &nbsp;    
> Everybody, including the writer, who has dared to make the slightest criticism of Garvey has been intimidated by threats and threatened with libel suits. Over fifty court cases have been brought by Garvey in the last two years.

We are reminding our readers of all this not to revive forgotten rancor but for the sake of historical accuracy. When Garvey was sent to Atlanta, no word or action of ours accomplished the result. His release and deportation was a matter of law which no deed or wish of ours influenced in the slightest degree. We have today, no enmity against Marcus Garvey. He has a great and worthy dream. We wish him well. He is free; he has a following; he still has a chance to carry on his work in his own home and among his own people and to accomplish some of his ideals. Let him do it. We will be the first to applaud any success that he may have.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Marcus Garvey (1921)](/Volumes/21/03/marcus_garvey.html)
* [Socialism and the Negro (1921)](/Volumes/22/06/socialism_and_the_negro.html)
* [A Lunatic or a Traitor (1924)](/Volumes/28/01/lunatic_or_a_traitor.html)
* [Our Economic Peril (1930)](/Volumes/37/03/our_economic_peril.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)

<!-- Similar articles end here -->