
---
title: 'Don''t Be Bitter'
author: Du Bois, W.E.B.
date: Feb. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 8
  issue: 4
  page: 180-181
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Is it not singular that so many white folk in advising black folk---and the ancient industry of advising blacks is booming just now---are careful to say, first and last: "Don't be bitter!" Why is there this insistence on the necessity of a sweet and even temper as an asset in life? Manifestly it is because most Americans who know or who begin faintly to realize the difficulties, complications and insults of a dark man's life today cannot imagine themselves suffering such wrongs without resorting to dynamite or suicide.

With the best will, therefore, they hasten to say: " Don't be bitter---don't mind---look on the bright side---and---and---"---then they trail off helplessly and look you rather miserably and apologetically in the face.

Recently in Atlanta five hundred colored college students met to consider the student volunteer movement. They had been invited, after several years' hesitation, by Mr. John R. Mott, who has been making a desperate attempt for twenty-five years to avoid the "Negro Problem" in his missionary enterprises. He found five hundred earnest, thoughtful young people and he selected among others a southern white man to tell them not to be "bitter!" The white man sailed into his task jauntily. He told of the mission of the races---"strength" from one race, "enterprise" from another, "aggression" from a third and from Negroes "submission"—then he looked into one thousand eyes and he paused. The sweat began to ooze out on his forehead and his sentences got mixed. Did he see "bitterness" in those eyes? No! but he did not see submission. "At least," he stammered, "your fathers and mothers—I don't know about you all" and he tried a pleasant little interlude which faded to a sickly grin. When at last he sat down even his white friends in the audience knew that he had missed his opportunity. They knew still more when a black man, William Pickens, stood up and with unanswerable logic told Mr. Mott and his friends that Christianity for black men started with the right to vote and nothing less.

If our friends mean by bitterness, the futile, impatient gestures of disgust, the wildly boastful word and dumb despair, let them save their advice. Colored Americans are not gesticulating nor yelling, nor committing suicide in numbers large enough to be alarming. But they are looking this nation more and more squarely in the eyes. They are asking in calm, level voice: "How long do you expect to keep up this foolishness and how long do you expect us to submit to it?" That is all. We are just asking. Do you suggest duties for us to attend to? Very good, we shall try to attend to them; we have tried in the past, as you may remember, and we are trying now, as the Census reports prove, but at the same time we keep asking the question: "How long? How much more? What next?" This is what we are doing; if this be bitterness, we are bitter.

