
---
title: 'The Prize Fighter'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 8
  issue: 4
  page: 181
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Boxing is an ancient sport. It is mentioned in Homer's Iliad and Virgil's
Aeneid and was a recognized branch of the celebrated Olympic games.
During the middle age boxing went out of style among most nations, the
preference being given to various sorts of encounters with weapons. In
England it was revived in the Seventeenth Century, and fighting with
bare fists became a national sport in the Eighteenth Century. Boxing
gloves were invented late in that century, and in the beginning of the
Nineteenth Century, John Jackson (note the prophecy!) became champion
and teacher of Lord Byron and other great and titled personages.

Gradually the more brutal features of the sport were eliminated and the
eighth Marquess of Queensberry drew up a set of rules in the sixties
which have since prevailed.

There is still today some brutality connected with boxing, but as
compared with football and boat racing it may be seriously questioned
whether boxing deserves to be put in a separate class by reason of its
cruelty. Certainly it is a highly civilized pastime as compared with the international game of war which produces so many "heroes" and national monuments.

Despite all this, boxing has fallen into disfavor---into very great
disfavor. To see publications like the New York *Times* roll their eyes
in shivery horror at the news from Paris (to which it is compelled to
give a front page) makes one realize the depths to which we have fallen.

The cause is clear: Jack Johnson, successor of the Eighteenth Century
John Jackson, has out-sparred an Irishman. He did it with little
brutality, the utmost fairness and great good nature. He did not "knock"
his opponent senseless. Apparently he did not even try. Neither he nor
his race invented prize fighting or particularly like it. Why then this
thrill of national disgust? Because Johnson is black. Of course, some
pretend to object to Mr. Johnson's character. But we have yet to hear,
in the case of white America, that marital troubles have disqualified
prize fighters or ball players or even statesmen. It comes down, then,
after all to this unforgivable blackness. Wherefore we conclude that at
present prize fighting is very, very immoral, and that we must rely on
football and war for pastime until Mr. Johnson retires or permits
himself to be "knocked out."

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [About Pugilists (1921)](/Volumes/22/05/about_pugilists.html)
* [The Third Battle of Bull Run (1912)](/Volumes/04/03/third_battle_of_bull_run.html)
* [McSwiney (1920)](/Volumes/21/02/mcswiney.html)
* [Violence (1934)](/Volumes/41/05/violence.html)
* [England, Again (1920)](/Volumes/19/05/england_again.html)

<!-- Similar articles end here -->