
---
title: 'Votes for Women'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 8
  issue: 4
  page: 179-180
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



This fall the voters of six states certainly, and possibly eight, will vote on woman's suffrage. In North and South Dakota, Montana, Nevada, Missouri and Nebraska elections are scheduled and attempts are being made to include this question in the fall elections of Oklahoma and Ohio. The Negro population of these eight states is 552,054. Assuming that the black voters of Oklahoma will be largely disfranchised it is, nevertheless, probable that 80,000 Negro voters will be asked to vote for or against the extension of the right of suffrage to women. How should they vote? A colored woman writes us from New Haven: 

> May I ask if through your columns you will answer some questions regarding Woman Suffrage and the colored woman? Our white friends come and tell us that we can do so much for ourselves when we get the ballot. Please tell me how we are going to do so much for ourselves? Will not the proportionate vote be the same as now? Should not the white women consider the betterment of the colored people as well as the foreigner who comes to our shores, because conditions are better here than in his own country? I attended a meeting a short time ago and the speaker invited questions. She had spoken of almost everything possible except the problems that vitally concern the people addressed. I asked her why the women were silent on the lynching of colored people in the South and on the unjust marriage laws and other laws discriminating against the Negro. She replied: "We have to take up the most important subjects, we cannot bother with everything under the sun and there are so many other things more important than lynching. As for marriage laws, we have to have some laws regulating marriage between races. For my part, I do not believe in marriage between Americans and Europeans." Now, Mr. Editor, this woman is a highly educated woman, but does not that sound like shallow reasoning? Are not Americans made up of all nations of Europe? Now what are we trying to do for ourselves if that is the way that the women who are working for votes for women feel towards the problem of the colored woman? Have we any right to believe that they will work for our cause after they get the ballot, if they do not feel willing to take up such questions now? Has the past history of our race anything to give us such encouragement? 

Let us answer frankly, there is not the slightest reason for supposing that white American women under ordinary circumstances are going to be any more intelligent, liberal or humane toward the black, the poor and unfortunate than white men are. On the contrary, considering what the subjection of a race, a class or a sex must mean, there will undoubtedly manifest itself among women voters at first more prejudice and petty meanness toward Negroes than we have now. It is the awful penalty of injustice and oppression to breed in the oppressed the desire to oppress others. The southern white women who form one of the most repressed and enslaved groups of modern civilized women will undoubtedly, at first, help willingly and zealously to disfranchize Negroes, cripple their schools and publicly insult them.

Nevertheless, votes for women must and ought to come and the Negroes should help bring this to pass for these reasons: 
1. Any extension of democracy involves a discussion of the fundamentals of democracy. 
2. If it is acknowledged to be unjust to disfranchise a sex it cannot be denied that it is absurd to disfranchise a color. 
3. If the North enfranchises women, the proportion of unselfish intelligent voters among Negroes will be increased, and the proportion of Negro voters whom white politicians have trained to venality will be decreased. 
4. If when the North enfranchises women the South refuses, or enfranchises only the whites, then the discrepancy between North and South in the votes cast will be even greater than now; at present the southern white voter has from five to seven times the power of the northern voter. How long would the nation endure an increase or even a doubling of this power? It would not take long before southern representatives in Congress would be cut down or colored women enfranchised. 
5. Granting that first tendencies would make the woman voter as unfair in race rights as the man, there would be in the long run a better chance to appeal to a group that knows the disadvantage and injustice of disfranchisement by experience, than to one arrogant and careless with power. And in all cases the broader the basis of democracy the surer is the universal appeal for justice to win ultimate hearing and sympathy. 

Therefore: Votes for Women.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Ohio (1912)](/Volumes/04/04/ohio.html)
* [Woman Suffrage (1915)](/Volumes/09/06/womansuffrage.html)
* [Votes for Women (1918)](/Volumes/15/01/votes_for_women.html)
* [The Negro Voter (1928)](/Volumes/35/08/negro_voter.html)
* [Votes for Women (1912)](/Volumes/04/05/votes_for_women.html)

<!-- Similar articles end here -->