
---
title: 'Forward'
author: Du Bois, W.E.B.
date: Mar. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 20
  issue: 5
  page: 213
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The reaction of war is upon us. For two terrible years and for four
others the world has been raised to heights of intense spiritual and
physical turmoil amounting at times to wild hysteria. We black folk have
been whirled up with the tide. The inevitable reaction born of sheer
physical law is now upon us. We sit back exhausted, depressed. What is
the use? we groan. What has this world madness meant to us? We are still
in bonds; wages lag behind the mounting costs of life; lynching
flourishes---what's the use of it all!

Steady, comrades, you have seized from the Hell of War, Self Knowledge
and Self Control. These are priceless. They are worth all. We know that
there is no royal road to our emancipation. It lies rather in grim,
determined, everyday strife. The strife cannot be wild and erratic and
individual. It must be ordered and continuous and carefully considered
---the campaign of an army and not the tactics of picturesque but
ineffective guerrillas.

We have the army in the 90,000 members of the N.A.A.C.P. and
hundreds of thousands of their friends and sympathizers. This army has a
new leader in its Secretary, *James Weldon Johnson.* Let us now sit up,
come to life and despite war-weary reaction and economic harassment,
let us see that the N.A.A.C.P. has a budget of $50,000 to continue
the war on lynching, to defend the defenseless in Arkansas, to 
inaugurate a great drive for the ballot, to combat "Jim-Crow" legislation,
and open America and the world to efficient self-respecting Negro
citizens.

Let every member rally to a renewed vitality in the N.A.A.C.P. Let
every member in every branch get his shoulder to the wheel.

