---
title: Murder Will Out
description: In 1920 in The Crisis, W.E.B. Du Bois exposes how Southern race and class power undermine labor and democracy, exploiting both Black and white workers.
author:
- name:
    given: W.E.B.
    family: Du Bois
date: Mar. 1920
categories: []
subjects:
- Labor organizing
- State repression of labor strikes (martial law)
- Employment discrimination
- Disfranchisement
- Lynching
people:
- W. E. B. Du Bois
- T. W. O'Connor
places:
- Southern United States
- Galveston, Texas
organizations:
- International Longshoremen's Association
- The Crisis (magazine)
citation:
  type: article-journal
  container-title: The Crisis
  volume: 20
  issue: 5
  page: 215
google-scholar: true
format:
  html:
    toc: false
    appendix-cite-as: display
---

Slowly, too slowly, and yet with inevitable sureness the meaning of the
South in American civilization is becoming clear to the blindest. T.W.
O'Connor, President of the International Longshoremen's Association, has
just said:

> The South has been utterly reactionary in its attitude toward labor. It
is completely out of step with modern attitudes toward such questions as
women in industries, child labor, limited hours of labor, employers'
liability and the like. In Texas recently a Democratic State
administration declared martial law in Galveston, where there was a
strike, against the protest of every city official, at a time when there
was not a sign of disorder and no arrest was made from the beginning to
the end of the strike. Yet troops were brought in and martial law
proclaimed.

For long years American laborers have been bamboozled by the South.
Southern white laborers have thought that they could raise themselves by
disfranchising, lynching and insulting black laborers. Northern white
laborers have thought that their salvation lay in forcing black workers
to be scabs or to starve. Black laborers have been convinced that their
salvation lay in close communion with the "aristocratic" southern
landlords and capitalists and with rich northern "philanthropy" against
the "poor white trash". All were wrong. There is no color line in labor.
To entrenched Privilege the underpaid day's work of black and white all looks alike, and entrenched Privilege
finds the South its finest, freest dwelling place.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The A.F. of L. (1933)](/Volumes/40/12/af_of_l.html)
* [Prejudice (1911)](/Volumes/02/01/prejudice.html)
* [Southern Civilization (1916)](/Volumes/13/01/southern_civilization.html)
* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)
* [Loyalty (1917)](/Volumes/14/01/loyalty.html)

<!-- Similar articles end here -->