
---
title: 'The Proper Way'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 5
  issue: 5
  page: 238-239
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The editor of the Cleveland *Gazette* names three main points of attack for any national association which aims to help colored people:

1. Disfranchisement.
2. Interstate "Jim Crow"
3. Lynchings.



This is perfectly true, and the National Association for the Advancement of Colored People recognizes this and is straining every nerve to attack these evils. As to disfranchisement we are making every effort to get the proper case before the Supreme Court. We have already helped by briefs and contributions the Oklahoma case, and when it comes before the court we have offered the services of two of the most eminent lawyers in the United States. We are represented on the counsel of the Mississippi "Jim Crow" case; the briefs are being examined by our lawyers, and we are making every effort to get the question before the court in the right way.

But the *Gazette* should know that cases before the Supreme Court are delicate matters. It does not do to rush into court with any haphazard ease. If anyone has a case or knows of a case which will bring out the proper points we should be glad to have it. Theoretically, it would seem very easy to settle such matters. Practically, it is very hard, but we propose to keep at it.



As to lynching, there are four things to do: Publish the facts, appeal to the authorities, agitate publicity and employ detectives. Every one of these things we have done. <span class="crisis-title">The Crisis</span> publishes the facts monthly over the protest of sensitive readers. We have sent telegrams and appeals to governors, sheriffs and the President; we have held mass meetings: we have sent distinguished writers and: investigators; we have secured publicity in prominent magazines, and we spent thousands of dollars in putting Burns' detectives on the Coatesville matter.

What else can we do? We want suggestions. Meantime we shall keep up our present agitation.

Some folk seem to imagine that the walls of caste and prejudice in America will fall at a blast of the trumpet, if the blast be loud enough. Consequently, when an association like the National Association for the Advancement of Colored People does something, they say querulously: "But nothing has happened." They ought to say: Nothing has yet happened, for that is true and that is expected. If in fifty or a hundred years <span class="crisis-title">The Crisis</span> can point to a distinct lessening of disfranchisement, and an undoubted reduction of lynching, and more decent traveling accommodations, this will be a great, an enormous accomplishment. Would God all this could be done to-morrow, but this is not humanly possible.

What is possible to-day and tomorrow and every day is to keep up necessary agitation, make unfaltering protest, fill the courts and legislatures and executive chambers, and keep ever lastingly at the work of protest in season and out of season. The weak and silly part of the program of those who deprecate complaint and agitation is that a moment's let up, a moment's acquiescence, means a chance for the wolves of prejudice to get at our necks. It is not that we have too many organizations; it is that we have too few effective workers in the great cause of Negro emancipation in America. Let us from this movement join in a frontal attack on disfranchiseemnt, "Jim Crow" cars and lynching. We shall not win today or to-morrow, but some day we shall win if we faint not.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Supreme Court (1914)](/Volumes/09/02/supreme_court.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Jim Crow (1919)](/Volumes/17/03/jim_crow.html)
* [The "Jim Crow" Argument (1913)](/Volumes/05/06/jim_crow_argument.html)
* [N.A.A.C.P. (1910)](/Volumes/01/02/NAACP.html)

<!-- Similar articles end here -->