
---
title: 'Exclusion'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 1
  page: 23
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



In Czarist Russia the number of Jews admitted to universities was strictly limited. In Hungary they are mobbing and beating the Jews to keep them out of college. In the United States at Harvard, Columbia and such institutions underground methods are used to limit the number of Jews and Negroes admitted. But Butler College, Indianapolis, goes back to the open and honest methods of Czarist Russia. Butler is "conceived by Christian influences and dedicated to the dispensation of a religious education, fitting men for Christian living." A few years ago it had practically no Negro students. Then as the number of Negroes increased in the high schools of Indianapolis a considerable number of them went to Butler. Last year Butler graduated twelve Negro students. This seems to have alarmed the authorities and this year they have announced that only ten colored students will be received each year. One can understand racial reactions due to crime, poverty and laziness, but the exclusion of ambitious, young students from institutions of learning, supported by public benevolence and "Christianity," merely on account of race and color, is a contradiction of every known principle of democracy and religion.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Pechstein and Pecksniff (1929)](/Volumes/36/09/pechstein_and_pecksniff.html)
* [The Negro College (1933)](/Volumes/40/08/negro_college.html)
* [Schools (1917)](/Volumes/13/03/schools.html)
* [The Negro Public School (1916)](/Volumes/11/05/negro_public_school.html)
* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)

<!-- Similar articles end here -->