
---
title: 'Hail Columbia'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 5
  issue: 6
  page: 289-290
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Hail Columbia, Happy Land! Again the glorious traditions of Anglo-Saxon
manhood have been upheld! Again the chivalry of American white men has
been magnificently vindicated. Down on your knees, black men, and hear
the tale with awestruck faces: Learn from the Superior Race. We do not
trust our own faltering pen and purblind sight to describe the reception
of the suffragists at the capital of the land. We quote from the
Southern reporters of the Northern press:

> Five thousand women, marching in the woman-suffrage pageant yesterday,
practically fought their way foot by foot up Pennsylvania Avenue,
through a surging mass of humanity that completely defied the Washington
police, swamped the marchers, and broke their procession into little
companies. The women, trudging stoutly along under great difficulties,
were able to complete their march only when troops of cavalry from Fort
Myer were rushed into Washington to take charge of Pennsylvania Avenue.
No inauguration has ever produced such scenes, which in many instances
amounted to little less than riots.    
> &nbsp;     
> More than 100 persons, young and old, of both sexes, were crushed and
trampled in the uncontrollable crowd in Pennsylvania Avenue yesterday,
while two ambulances of the Emergency Hospital came and went constantly
for six hours, always impeded and at times actually opposed, so that doctor and driver literally had to fight their way to give succor to the injured.    
> &nbsp;     
> Hoodlums, many of them in uniform, leaned forward till their
cigarettes almost touched the women's faces while blowing smoke in their
eyes, and the police said not a word, not even when every kind of insult
was hurled.    
> &nbsp;     
> To the white-haired women the men shouted continuously: 'Granny!
granny! We came to see chickens, not hens! Go home and sit in the
corner!' To the younger women they yelled: 'Say, what you going to do
to-night? Can't we make a date?' and the police only smiled. The
rowdies jumped on the running boards of the automobiles and snatched the
flags from the elderly women, and they attempted to pull the girls from
the floats.

Wasn't it glorious? Does it not make you burn with shame to be a mere
black man when such mighty deeds are done by the Leaders of
Civilization? Does it not make you "ashamed of your race?" Does is not
make you "want to be white?"

And do you know (we are almost ashamed to say it) the Negro again lost a
brilliant opportunity to rise in his "imitative" way. Ida Husted Harper
says:

> We made the closest observation along the entire line and not in one
instance did we hear a colored man make a remark, although there were
thousands of them.

Another white woman writes:

> I wish to speak a word in favor of the colored people during the
suffrage parade. Not one of them was boisterous or rude as with great,
difficulty we passed along the unprotected avenue. The difference
between them and those insolent, bold white men was remarkable. They
were quiet and respectable and earnest, and seemed sorry for the
indignities which were incessantly heaped upon us. There were few
policemen to protect us as we made our first parade in Washington, and the dignified silence of the colored people and the sympathy in their faces was a great contrast to those who should have known better. I thank them in the name of all the women for their
kindness.

Now look at that! Good Lord! has the Negro *no* sense? Can he grasp no
opportunity?

But let him not think to gain by any such tactics. The South sees his
game and is busy promoting bills to prevent his marrying any wild-eyed
suffragette who may be attracted by his pusillanimous decency. Already
the Ohio legislature has been flooded by forged petitions from a "Negro
advancement society of New York" to push the intermarriage bill!

No, sir! White men are on the firing line, and if they don't want white
women for wives they will at least keep them for prostitutes. Beat them
back, keep them down; flatter them, call them "visions of loveliness" and tell them that the place for woman is in the home, even if she hasn't got a home. If she is homely or poor or made the mistake of being
born with brains, and begins to protest at the doll's house or the bawdy
house, kick her and beat her and insult her until in terror she slinks
back to her kennel or walks the midnight streets. Don't give in; don't
give her power; don't give her a vote whatever you do. Keep the price of
women down; make them weak and cheap.

Shall the time ever dawn in this Land of the Brave when a free white
American citizen may not buy as many women as his purse permits? Perish
the thought and Hail Columbia, Happy Land!

