
---
title: 'The "Jim Crow" Argument'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 5
  issue: 6
  page: 291-292
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The chairman of the committee in the Missouri legislature which is
engineering the "Jim Crow" car bill has
evolved this unanswerable syllogism:

1.  Negroes should not object to being separated on the trains by "just a small railing."
2.  If they do object it shows that they are averse to associating with themselves.
3.  If they insist on associating with whites, it shows that they want
    "social equality!"

The argument of our learned and astute solon not only proves his case,
but it proves so much in addition as to destroy his argument.

If poor people object to being separated from rich people, does it prove
a wild desire for the society of Mrs. Ponsonby de Thompkyns or simply
righteous indignation at having manhood measured by wealth?

If Jews object to the Ghetto and the pale, does it prove them ashamed of
themselves or afraid of those oppressors who find oppression easier when
the victims are segregated and helpless?

The modern fight for human freedom is the fight of the individual man to
be judged on his own merits and not saddled with the sins of a class for
which he is not responsible. The favorite device of the devil, ancient
and modern, is to force a human being into a more or less artificial
class, accuse the class of unnamed and unnamable sin, and then damn any
individual in the alleged class, however innocent he may be.

This is the medieval tyranny which the South has revived in "Jim Crow"
legislation and which Missouri is striving for. The South fulminates
against dirt, crime and bad manners and then herds in the "Jim Crow" car
the clean and unclean and the innocent and guilty and
the decent and indecent. Separation is impossible in a democracy. It
means segregation, subordination and tyranny.

Social equality? Of course we want social equality. Social equality is
the right to demand the treatment of men from your fellow man. To ask
less is to acknowledge your own lack of manhood.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Jim Crow (1919)](/Volumes/17/03/jim_crow.html)
* [Blessed Discrimination (1913)](/Volumes/05/04/blesseddiscrimination.html)
* [The Proper Way (1913)](/Volumes/05/05/proper_way.html)
* [The Fruit of the Tree (1913)](/Volumes/06/05/fruit_of_tree.html)
* [The Tragedy of ''Jim Crow'' (1923)](/Volumes/26/04/tradgedy_of_jim_crow.html)

<!-- Similar articles end here -->