---
title: 'Martyrs'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: December 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 21
  issue: 2
  page: 57
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

Three years ago December 11, at 7:17 in the morning, thirteen American Negro soldiers were murdered on the scaffold by the American government to satisfy the bloodlust of Texas on account of the Houston riot. This was bad enough; but in addition to this there are today languishing in the United States Penitentiary at Leavenworth, Kan., 56 colored men sentenced to life imprisonment and 5 men sentenced to imprisonment for 15 years, all for the same alleged offence. This shameful injustice is a trumpet call to every American Negro and we should never rest until these men are pardoned and freed,---

<div class="poem">
  <div class="verse">Lord, these are Thine who pay the price</div>
  <div class="verse indent">For what a freeman’s soul is worth,---</div>
  <div class="verse">Whose madness is their sacrifice</div>
  <div class="verse indent">That what they love may live on earth!</div>
  <div class="verse big-indent">Lord these are Thine!</div>
</div>

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Houston (1918)](/Volumes/16/06/houston.html)
* [Thirteen (1918)](/Volumes/15/03/thirteen.html)
* [Houston (1917)](/Volumes/14/06/houston.html)
* [Courts and Jails (1932)](/Volumes/39/04/courts_and_jails.html)
* [Houston and East St. Louis (1918)](/Volumes/15/06/houston_and_east_st_louis.html)

<!-- Similar articles end here -->