
---
title: 'The Unreal Campaign'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 21
  issue: 2
  page: 54-56
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Never have the American people endured such a Presidential campaign. It is true that in no campaign are the great issues always distinct and clear and the alignments definite and understandable. But surely in no campaign has there ever been such a lack of alignment and such deliberate smearing of issues. One may, as one is constituted, regard voting as a test of conscience and principle or as a practical make-shift. In the first, the land may easily go to the dogs while the Dreamer walks his high and isolated path. In the other case, we may too easily forget our dreams.

But both sorts of Voters on November 2, 1920, were in maddening puzzlement. The League of Nations? There was no real difference between the parties; between Johnson and Wilson there was a world of argument; but Taft and Holt, Hoover and Cox? It was all a matter of punctuation and style. No man then could vote either the Republican or the Democratic ticket because he favored or opposed the League. And outside the League, What? Imperialism, labor and wage, the power of capital, the marketing of farm products, the building of homes, the training of children, the ownership of land, the freedom of suffrage---in these and all else the major parties were mere fog or reaction. Indeed the only real, stinging, fighting questions in the whole campaign were President Wilson and the Negro.

## The Family Tree

The allegation was that the President-elect had a black man somewhere among his remote ancestors. Can you conceive how real a fury this query roused? How else could it be with our deliberate cultivation of race hate and with Pat Harrison of Mississippi heading one of the Speakers' Bureaus?

Suppose President Harding is colored---What of it? He would be but one of hundreds of distinguished Americans who served their country well from the day of Alexander Hamilton to that of Lew Wallace. Nefertari and Amenhotep, Candace and Terence, Askia and Tamuramaro, Browning and Lafcadio Hearn---how many of the world's heroes have shared the black blood of Africa! It is an ancient and noble lineage; as high and deserving as that of any race on earth, until Ethiopia was raped and murdered and despoiled by Europe. God knows that all of us---black, white, red and yellow, are low enough in ancestry and service, but "Pure White America" excels most lands in being able to boast an ancestry which includes far more jails, asylums and gutters and far fewer palaces than most nations. Is this her shame or glory? And which was worse: the shrieking whispers of the Democrats, or the vociferous denials of the Republicans of the taint! Taint, forsooth! what could taint America?

Ohio, once the home of freedom, led in Anti-Negro propaganda, egged on by Cox and the new white southern immigration. "Timely warnings" to white folk were distributed by the hundred thousand declaring, "Ohioans should remember that the time has come when we must handle this problem in somewhat the same way as the South is handling it!" As a result many of the colored candidates for the legislature were defeated, but more were elected than ever before and many friends like Governor Davis, formerly Mayor of Cleveland, triumphed.

## Third Parties

The third parties have made a singularly spiritless campaign. As residual legatees of all protest and unrest they did almost nothing to answer the searching query of desperate strivers for light. Not the ultimate dogma of Marxian socialism or the undigested hodge-podge of Farmer-Laborers sufficed. Men asked and were not answered: What is the next step and how does it lead to a definite, clearmarked way? The great mass of laboring people, the thrifty, hardworking farmers and small capitalists, lacked dismally here that leadership which through the great Labor party of England and the right wing Socialists of Italy are hewing, waveringly but stubbornly, a real path, leaving on the one side intransigeant communism and on the other, organized and reactionary theft. Not so America. We, the burden-bearers, could not even agree to disagree and delivered the masses bound into the hands of the Phillistines.

And the Black Man. He had no chance. He was less than free and more than a slave. He was a machine---an automatic registration mark for the Republican party. He could not be otherwise. From the day Woodrow Wilson shamelessly betrayed his black supporters of 1912 to the day when the flippant Cox of Ohio built his Ohio campaign on the cheapest brand of "nigger"-hatred, the black American had but one political choice or mission: to defeat the South-ridden Democratic party. He could not even think of taking an off-shot at the Millenium by voting Socialist or Farmer Labor---he must defeat the Democrats.

And he did his bit.

And so the great farce ends. The People have spoken---and said nothing.

