
---
title: 'Education'
author: Du Bois, W.E.B.
date: Jun. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 2
  page: 74-76
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Consider this argument: Education is the training of men for life. The best training is experience, but if we depended entirely upon this each generation would begin where the last began and _ civilization could not advance. 

We must then depend largely on oral and written tradition and on such bits of typical experience as we can arrange for the child's guidance to life. 

More than that, children must be trained in the technique of earning a living and doing their part of the world's work. 

But no training in technique must forget that the object of education is the child and not the things he makes. 

Moreover, a training simply in technique will not do because general intelligence is needed for any trade. and the technique of trades changes. 

Indeed, by the careful training of intelligence and ability, civilization is continually getting rid of the hardest and most exhausting toil, and giving it over to machines, leaving human beings freer for higher pursuits and  self-development. 

Hence, colored people in educating their children should be careful: 

First: To conserve and select ability, giving to their best minds higher college training. 

Second: They should endeavor to give all their children the largest possible amount of general training and intelligence before teaching them the technique of a particular trade, remembering that the object of all true education is not to make men carpenters, but to make carpenters men. 

Is not this reasoning sound? Could you imagine an educator of any experience who would take material exception to it? Would you call it revolutionary or in the nature of a "personal" attack? 

Certainly not. 

Yet this very argument, with illustrations and emphasis delivered to some seven hundred apparently well-pleased folk in Indianapolis, has had the most astounding results. The Indianapolis *Star* in a leading editorial denounced it as "dangerous!" 

A leading white philanthropist of abolition forbears considered it not only "misleading" and "mischievous" but a covert and damaging personal attack! 

The supervisor of the colored schools of Indianapolis wrote to express regret that the lecture had seemed to attack his school curriculum and ideals, and the assistant superintendent of schools in the District of Columbia hastens to give advice! 

Yet where is the flaw in the argument? 

There is no flaw, but there are serious flaws in the thinking of some of these critics. 

The first flaw is the naive assumption that the paraphernalia of a school shows the education it is imparting. If some people see a Greek book and a cap and gown, they conclude that the boy between them is receiving higher education. But is he? That depends. If other people see a hammer, a saw and a cook book, they conclude that the boy who uses them is being trained in intélligence, ability and the earning of a living. But is he? That depends. 

When the proud principal of a school shows workshop and kitchen, table and pie, one may be interested, but one is no more convinced than when another shows an array of Greek roots and rounded phrases. One must merely remark: The end of education is neither the table nor the phrase—it is the boy; what kind of boys are you training here? Are they boys quickened in intelligence, with some knowledge of the world they live in? Are they trained in such ways as to discover their true bent and ability, and to be intelligently guided to the choice of a life work? Then your system is right. Otherwise it is wrong, and not all the gingham dresses in Indiana will justify it. 

The second flaw is the more or less conscious determination of certain folk to use the American public-school system for the production of laborers who will do the work they want done. To them Indianapolis exists for the sake of its factories and not the factories for the sake of Indianapolis. They want dinners, chairs and motor cars, and they want them cheap; therefore use the public schools to train servants, carpenters and mechanics. It does not occur to them to think of workingmen as existing for their own sakes. What with impudent maids, and half-trained workingmen, they are tired of democracy; they.want caste; a place for everybody and everybody in his father's place with themselves on top, and "Niggers" at the bottom where they belong. To such folk the problem of education is strikingly simple. To teach the masses to work; show them how to do things; increase their output; give them intelligence, of course; but this as a means, not as an end, and be careful of too much of it. Of course, if a meteoric genius bursts his birth's invidious bar, let him escape, but keep up the bars, and as most men are fools, treat them and train them as such. 

It was such darkened counsels as these that brought the French Revolution. It is such mad logie as this that is at the bottom of the social unrest to-day. 

The lecturer came to Indianapolis not to criticise, but to warn—not to attack, but to make straight the way of the Lord. He is no despiser of common humble toil; God forbid! He and his fathers before him have worked with their hands at the lowliest occupations and he honors any honest toilers at any task; but he makes no mistake here. It is the toilers that he honors, not the task —the man and not the Thing. The Thing may or may not be honorable— the man always is. 

Yet the despising of men is growing and the caste spirit is rampant in the land; it is laying hold of the public schools and it has the colored public schools by the throat, North, East, South and West. Beware of it, my brothers and dark sisters; educate your children. Give them the broadest and highest education possible; train them to the limit of their ability, if you work your hands to the bone in doing it. See that your child gets, not the highest task, but the task best fitted to his ability, whether it be digging dirt or painting landscapes; remembering that our recognition as common folk by the world depends on the number of men of ability we produce—not great geniuses, but efficient thinkers and doers in all lines. Never forget that if we ever compel the world's respect, it will be by virtue of our heads and not our heels. 

