
---
title: 'Reconstruction'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 3
  page: 130-131
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


This is a program of reconstruction within the Negro race in America, after the the revolution of world war. In *Education* we must take up the problem of the colored child in the white school. At present the tendency is to accept and even demand separate schools because our children so often are neglected, mistreated and humiliated in the public schools. This is a dangerous and inadvisable alternative and a wicked surrender of principle for which our descendants will pay dearly. Our policy should be to form in connection with each school and district effective Parents' Associations, composed of the fathers, mothers and friends of colored pupils; these associations should establish friendly relations with teachers and school authorities, urge parents to wash and dress their children properly, help look after truancy and poverty, arrange for home work and tuition for the backward, curb delinquency and be, in fine, a vigilance committee to keep the public school open to all and fit the Negro child for it.

In *Religion* we must, in the larger cities, stop building and purchasing new church edifices and begin to invest the money of the church in homes, land and business, and philanthropic enterprises for the benefit of the people. Individual home ownership in most large cities is today difficult; but a group of people who can buy and pay for a hundred thousand dollar church can purchase a hundred thousand dollar apartment house and run it. It is a simple business proposition and requires only elementary honesty and ordinary executive ability. Churches can easily begin co-operative buying of coal, bread and meat, using their own premises for distribution; churches in the country and small towns can buy farms and rent or run them; the church can purchase automobile trucks and help the Negro farmer market his produce independent of the railroads and thieving commission merchants; even simple manufacturing, sewing and building are not beyond the reasonable activities of church bodies. Indeed, unless the church extends its economic functions beyond the simple program of building bigger and finer edifices---unless it organizes the Negro laborer so that his entire wage will not go in rent and supporting storekeepers who despise and cheat him---unless it thus helps the laborer, it will lose the laborer. The hope of the Negro church is character-building through economic co-operation.

In *Business* the Negro must branch out into certain new lines where he has long and foolishly hesitated: We must open drygoods and haberdashery shops, meat markets and clothing stores, shoe stores and hat stores. We must gradually but persistently get into manufacturing. The deft fingers of our young people are as easily adapted to machinery as the fingers of whites. We are denied opportunity by white trade unions and by lack of pioneering courage among colored capitalists and business men. Let us wake up. The era of manufactures in the United States is just begun. The expansion of domestic and foreign trade is going to be enormous. We raise the cotton---why not spin and weave it? We dig the iron---why not weld it? We mine the coal---why not turn it to steam and power? Do we lack brains and capital? No, we lack experience and courage. Get them.

In *Politics* the colored woman is going to vote. This is our chance. Away with the old regime, the pothouse politician and white bribery. Let us form clubs and study government in city, county, state and nation. Let us know the law and the officials and their duties. Let us keep continual and rigid tabs on every candidate. Away with parties---what we want is men. Away with promises---what we want is deeds. Study, learn, register and vote. Vote at every election and see that every friend of yours votes. Pay your poll taxes and register. Do not vote for a party. Never vote a straight ticket. Vote for men and measures---not for parties. But above all, vote! Let every Negro man and woman, always and everywhere, vote.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Segregation (1910)](/Volumes/01/01/Segregation.html)
* [Education (1911)](/Volumes/01/04/education.html)
* [Negro Education (1918)](/Volumes/15/04/negro_education.html)
* [College Education (1914)](/Volumes/08/03/college_education.html)
* [Lynchings and Mobs (1921)](/Volumes/22/04/mixed.html)

<!-- Similar articles end here -->