
---
title: 'Florida'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1923
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 26
  issue: 5
  page: 200-201
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



> I am writing to you to-day to 
ask you for some information 
regarding transportation to 
Liberia, Africa. I want to know if there is any free transportation whereby one can go from here over there. If so, please let me know. Also please let me know just how I could get over there. There are several persons who desire to go over there. 
<p>I am awaiting your reply.

My dear Sir:

You might write the American Colonization Society. They have, I believe, a fund to help migration to Liberia. 

I realize why the colored folk of Lakeland have turned their eyes toward some land of refuge, but do not think of migrating to Africa unless: (1) You know exactly where you are going; whether you will be welcome; and how you are going to make a living. (2) Unless you have capital. You should have at least $1,000 above your expenses, and $5,000 would be better. (3) Do not go under any circumstances if you are not young, strong and healthy. 

Africa is an immense land, three times the size of these vast United States. It has all kinds of climate, all sorts of government and conditions of society. It is under the almost absolute military control of white European nations except in the case of Liberia. 

Liberia welcomes immigrants but only immigrants of a certain sort. She has no place for empty-handed laborers. There are more laborers in Africa to-day than can be profitably put to work. She has no place for sick people, or old people or orators or agitators. She wants men with capital, skill, education and health. Such men, if they have grit and determination and can withstand the trying climate may, if they work hard, succeed---no others can. 

