
---
title: 'Votes for Women'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 15
  issue: 1
  page: 8
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Some 75,000 Negro voters in the State of New York will be asked to decide this month as to whether or not they are willing that women should have the vote in this State. It is an unpleas­ant but well-known fact that hither­ to American Negro voters have, in the majority of cases, not been favor able to woman suffrage. This attitude has been taken for two main reasons: *First*, the Negro, still imbued by the ideals of a past genera­tion, does not realize the new status of women in industrial and social life. Despite the fact that within his own­ group women are achieving economic independence even faster than whites, he thinks of these as excep­tional and abnormal and looks for­ ward to the time when his wages will be large enough to support his wife and daughters in comparative idleness at home.

*Secondly*, the American Negro is particularly bitter at the attitude of many white women: at the naive assumption that the height of his am­bition is to marry them, at their arti­ficially-inspired fear of every dark face, which leads to frightful accusa­tions and suspicions, and at their sometimes insulting behavior toward him in public places.

Notwithstanding the undoubted weight of these two reasons, the American Negro must remember, *First*, that the day when women can be considered as the mere appendages of men, dependent upon their bounty and educated chiefly for their pleasure, has gone by; that as an in­telligent, self-supporting human be­ing a woman has just as good a right to a voice in her own government as has any man; and that the denial of this right is as unjust as is the denial of the right to vote to American Negroes.

Secondly, two wrongs never made a right. We cannot punish the insolence of certain classes of American white women or correct their ridicu­lous fears by denying them their un­ doubted rights.

It goes without saying that the women's vote, particularly in the South, will be cast almost unanimously, at first, for every reactionary Negro-hating piece of legislation that is proposed; that the Bourbons and the demagogs, who are today sitting in the Natural Legislature by the reason of stolen votes, will have additional backing for some years from the votes of white women.

But against this consideration it must be remembered that these same women are going to learn political justice a great deal more quickly than did their men and that despite their prejudices their very emergence into the real, hard facts of life and out of the silly fairy-land to which their Southern male masters beguile them is going to teach them sense in time.

Moreover, it is going to be more difficult to disfranchise colored women in the South than it was to disfranchise colored men. Even southern "gentlemen," as used as they are to the mistreatment of colored wom­en, cannot in the blaze of present publicity physically beat them away from the polls. Their economic power over them will be smaller than their power over the men and while you can still bribe some pauperized Negro laborers with a few dollars at election time, you cannot bribe Negro women.



It is, therefore, of the utmost importance that every single black voter in the State of New York should this month cast his ballot in favor of woman suffrage and that every black voter in the United States should do the same thing whenever and as often as he has opportunity.

It is only in such broad-minded willingness to do justice to all, that the black man can prove his right not only to share, but to help direct modern culture.

__________
*Citation:* Du Bois, W.E.B. 1918. "Votes for Women." *The Crisis*. 15(1):8.