
---
title: 'Of Children'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 6
  page: 287
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



This is the Children's Number, and as it has grown and developed in the
editor's hesitating hands, it has in some way come to seem a typical
rather than a special number. Indeed, there is a sense in which all
numbers and all words of a magazine of ideas must point to the
child---to that vast immortality and wide sweep and infinite possibility
which the child represents. Such thought as this it was that made men
say of old as they saw baby faces like these that adorn our pages this
month:

> And whosoever shall offend one of these little ones... it is better for him that a millstone were hanged about his neck, and he were cast into the sea.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The True Brownies (1919)](/Volumes/18/06/true_brownies.html)
* [The Slaughter of the Innocents (1918)](/Volumes/16/06/slaughter.html)
* [We Come of Age (1915)](/Volumes/11/01/we_come_of_age.html)
* [The New Crisis (1925)](/Volumes/30/01/new_crisis.html)
* [The Boy Over There (1918)](/Volumes/16/06/boy_over_there.html)

<!-- Similar articles end here -->