
---
title: 'A University Course in Lynching'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1923
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 26
  issue: 2
  page: 55
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


We are glad to note that the University of Missouri has opened a course in Applied Lynching. Many of our American Universities have long defended the institution, but they have not been frank or brave enough actually to arrange a mob murder so that the students could see it in detail.


The University of Georgia did, to be sure, stage a lynching a few years ago but this was done at night and the girls did not have a fair chance to see it. At the University of Missouri the matter was arranged in broad daylight with ample notice, by five hundred men and boys who were "comparatively orderly," and it was viewed by some fifty women most of whom we understand were students of the University. We are very much in favor of this method of teaching 100 percent Americanism; as long as mob murder is an approved institution in the United States, students at the universities should have a first hand chance to judge exactly what a lynching is.

In the case of James T. Scott everything was as it should be. He was a janitor at the University who protested his innocence to his last breath. He was charged with having "lured" a fourteen year old girl in broad daylight far from her home and "down the railroad tracks." He was "positively identified" by the girl, and while the father deprecates violence he has "no doubt" of the murdered man's guilt.

Here was every element of the modern American lynching. We are glad that the future fathers and mothers of the West saw it, and we are expecting great results from this course of study at one of the most eminent of our State Universities.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Lynching (1927)](/Volumes/33/04/lynching.html)
* [Causes of Lynching (1931)](/Volumes/38/04/causes_of_lynching.html)
* [Lynching (1914)](/Volumes/07/05/lynching.html)
* [Lynchings (1932)](/Volumes/39/02/lynchings.html)
* [Lynchings and Mobs (1921)](/Volumes/22/04/mixed.html)

<!-- Similar articles end here -->