---
title: 'For What'
description: "Contrasts Parisian decency with U.S. racism and urges Black Americans to join European democracy."
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1919
subjects:
  - Racial discrimination — United States
  - Race relations — France
  - African American expatriation — Europe
  - Interracial social relations
  - Democracy — Europe
people:
  - Du Bois, W. E. B. (William Edward Burghardt)
places:
  - Paris, France
  - United States
  - Europe
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 17
  issue: 6
  page: 268
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display

categories:
  - "Segregation"
  - "Art & Culture"
---

My God! For what am I thankful this night? For nothing. For nothing but the most commonplace of commonplaces; a table of gentlewomen and gentlemen---soft-spoken, sweet-tempered, full of human sympathy, who made me, a stranger, one of them. Ours was a fellowship of common books, common knowledge, mighty aims. We could laugh and joke and think as friends---and the Thing---the hateful, murderous, dirty Thing which in America we call "Nigger-hatred" was not only not there---it could not even be understood. It was a curious monstrosity at which civilized folk laughed or looked puzzled. There was no elegant and elaborate condescension of---"We once had a colored servant"---"My father was an Abolitionist"---"I've always been interested in your people"---there was only the community of kindred souls, the delicate reference for the Thought that led, the quick deference to the guests you left in quiet regret, knowing they were not discussing you behind your back with lies and license. God! It was simply human decency and I had to be thankful for it because I am an American Negro and white America, with saving exceptions, is cruel to everything that has black blood---and this was Paris, in the year of salvation, 1919. 

Fellow blacks, we must join the democracy of Europe. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Again, Social Equality (1920)](/Volumes/19/05/again_social_equality.html)
* [Our Book Shelf (1926)](/Volumes/31/03/book_shelf.html)
* [Votes for Negroes (1921)](/Volumes/21/03/votes-for-negroes.html)
* [Negro Writers (1920)](/Volumes/19/06/negro_writers.html)
* [Counsels of Despair (1934)](/Volumes/41/06/counsels_of_despair.html)

<!-- Similar articles end here -->