
---
title: 'Our Book Shelf'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1925
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 31
  issue: 1
  page: 31-32
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



<h2>The Book of American Negro Spirituals</h2> 

James Weldon Johnson has edited, with an introduction, a book of Negro spirituals containing musical arrangements chiefly by his brother, J. Rosamond Johnson, and with other arrangements by Lawrence Brown. The result is peculiarly satisfying. 

It is one thing for a race to produce artistic material; it is quite another thing for it to produce the ability to interpret and criticize this material. This is particularly true when the artistic gift is a matter of primitive development in the rich childhood of a people. For a long time the Negro had to depend upon white critics for the presentation of his folk songs, and while Allen and White and Krehbiel did excellent work, they lacked the inner knowledge and inspiration which would make their word authoritative. The authors of this book bring these essential things. 

Mr. Johnson's introduction, which runs over forty large pages, is in itself a most entertaining comment on the folk song. He characterizes "this noble music," defends the Negro as its original creator, examines the origin and "miracle" of its production. He then speaks of our late discovery of African art in various lines both in the Motherland and in other parts of the world. He has a notable explanation of the way in which the new Christian religion came to modify African music in America and make the Negro folk song possible. The process of folk song making is explained with interesting references to "Ma" White and "Singing" Johnson. 

There is a study of variations in solo and chorus singing, in the use of melody and rhythm and the curiously difficult art of rendering them, and the many methods of approach. Mr. Johnson discusses the difficulty of recording these spirituals because of the "curious turns and twists and quavers and the intentional striking of certain notes just a shade off the key." The rhythm of the work songs is analyzed and that too of the "shout" songs and of the dance which has so largely disappeared now from the Negro churches. There is a special attention paid to the fact that the folk songs were harmonized by the singers and not sung in unison as some have assumed, and Mr. Rosamond Johnson and Mr. Brown have especially brought this out in their renditions, with a great deal of care and with notable success. 

The poetry of the folk songs is illustrated by many quotations, such as "De blood came twinklin' down," "Sometimes I feel like a motherless child" and others. There are several pages on Negro dialect and generous acknowledgment of the credit due those who have helped preserve the Negro spiritual. "The credit for the first introduction of spirituals to the American public and the world belongs to Fisk University." The book has words and music of 61 songs. "The collection here presented is not definitive but we have striven to make it representative of this whole field of music, to give examples of every variety of spiritual." 

The musical setting as done in this book one-must hear to appreciate the peculiarly high and unique quality of the work. Never before have the "Spirituals" had just this sort of original and yet true musical accompaniment. It is as though something unknown and wild and yet sensed in the song of black folk had been caught and caged forever. 

The book is published by the Viking Press and it is hoped that it will have wide use and vogue. <span class="right">--W. E. B. D.</span>

<h2> The Basis of Racial Adjustment </h2>

Thomas Jackson Woofter, Jr., has written and published a book called "The Basis of Racial Adjustment" which is far and away the best thing on the relations of the races in the South, that has come from a Southern white writer in our day. It is singularly fair and thoughtful; so eminently fair indeed, that after glancing at the first pages and noting the catholicity of treatment I was compelled to go through the rest of the book with a fine-tooth comb to find the lurking surrender to Southern race hate. I did not find it. 

There were some few statements to which I might take exception: his treatment of the Dyer bill for instance, and possibly some parts of his chapter on the Negro in Government; but even here my criticism would be very, very slight. 

I know of no book by a Southern white man with which I so thoroughly and heartily agree. Take for instance, this statement: "The taxation of colored people to pay a bond issue which is spent entirely for the erection of white public schools is just as dishonest in a community as the activity of the highwayman who, with the aid of a bludgeon, converts your cash to his own uses. These are the types of action to be avoided by interracial codes." Or this: "To assume that every member of an advantaged group is superior to every member of a disadvantaged group is a blind error, and the assumption that group differences are fixed and ineradicable for all time is equally as mistaken." Or again this: "If all men were exactly alike, specialization would not be so effective as it is when special abilities can be developed and put to work for special ends: To argue, therefore, that the Negro and the white man are very different, is a point in favor of, rather than against, their cooperation." And finally this: "For the white South, what is needed above all is fairness, a determination to enforce suffrage tests equitably on white and black alike, and a resolve to break away from the one-party system and to regain preéminence in the national forums of political action by building a political system around the live national issues and forgetting the more or less dead issue of Negro domination."

The book is in 12 chapters and treats Racial Coöperation, Occupations, Law and Order, Government, Education, Religion and Race Contacts. It is published by Ginn and Company. <span class="right">--W. E. B. D.</span>

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Mencken (1927)](/Volumes/34/08/mencken.html)
* [The Browsing Reader (1928)](/Volumes/35/05/browsing_reader.html)
* [Our Book Shelf (1926)](/Volumes/31/03/book_shelf.html)
* [Negro Art (1922)](/Volumes/23/03/negro-art.html)
* [Negro Writers (1920)](/Volumes/19/06/negro_writers.html)

<!-- Similar articles end here -->