
---
title: 'The Burden of Black Women'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 1
  page: 31
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



<div class="poem">
<p class = "verse">Dark daughter of the lotus leaves that watch the Southern sea,</p>
<p class = "verse">Wan spirit of a prisoned soul a-panting to be free;</p>
<p class = "verse indent">The muttered music of thy streams, the whispers of the deep</p>
<p class = "verse indent"> Have kissed each other in God&rsquo;s name and kissed a world to sleep.</p>

<div class="poem">
</div>
<p class = "verse">The will of the world is a whistling wind sweeping a cloud-cast sky,
<p class = "verse">And not from the east and not from the west knelled its soul-searing cry;
<p class = "verse">But out of the past of the Past&rsquo;s grey past, it yelled from the top of the sky;
<p class = "verse indent">Crying: Awake, O ancient race! Wailing: O woman arise!
<p class = "verse indent">And crying and sighing and crying again as a voice in the midnight cries;
<p class = "verse indent">But the burden of white men bore her back, and the white world stifled her sighs.

<div class="poem">
</div>
<p class = "verse">The White World&rsquo;s vermin and filth:
<p class = "verse indent">All the dirt of London,
<p class = "verse indent">All the scum of New York;
<p class = "verse indent">Valiant spoilers of women
<p class = "verse indent">And conquerors of unarmed men;
<p class = "verse indent">Shameless breeders of bastards
<p class = "verse indent">Drunk with the greed of gold,
<p class = "verse indent">Baiting their blood-stained hooks
<p class = "verse indent">With cant for the souls of the simple,
<p class = "verse indent">Bearing the White Man&rsquo;s Burden
<p class = "verse indent">Of Liquor and Lust and Lies!
<p class = "verse indent">Unthankful we wince in the East,
<p class = "verse indent">Unthankful we wail from the westward,
<p class = "verse indent">Unthankfully thankful we sing,
<p class = "verse indent">In the un-won wastes of the wild:
<p class = "verse big-indent">I hate them, Oh!
<p class = "verse big-indent">I hate them well,
<p class = "verse big-indent">I hate them, Christ!
<p class = "verse big-indent">As I hate Hell,
<p class = "verse big-indent">If I were God
<p class = "verse big-indent">I&rsquo;d sound their knell
<p class = "verse big-indent">This day!
</div>

<div class="poem">
<p class = "verse indent">Who raised the fools to their glory
<p class = "verse indent">But black men of Egypt and Ind?
<p class = "verse indent">Ethiopia&rsquo;s sons of the evening,
<p class = "verse indent">Chaldeans and Yellow Chinese?
<p class = "verse indent">The Hebrew children of Morning
<p class = "verse indent">And mongrels of Rome and Greece?
<p class = "verse big-indent">Ah, well!
</div>

<div class="poem">
<p class = "verse">And they that raised the boasters
<p class = "verse">Shall drag them down again:
<p class = "verse">Down with the theft of their thieving
<p class = "verse">And murder and mocking of men,
<p class = "verse">Down with their barter of women
<p class = "verse">And laying and lying of creeds,
<p class = "verse">Down with their cheating of childhood,
<p class = "verse">And drunken orgies of war&mdash;
<p class = "verse big-indent">down,
<p class = "verse bigger-indent">down,
<p class = "verse biggest-indent">deep down,
</div>

<div class="poem">
<p class = "verse">Till the Devil&rsquo;s strength be shorn,
<p class = "verse">Till some dim, darker David a-hoeing of his corn,
<p class = "verse">And married maiden, Mother of God,
<p class = "verse">Bid the Black Christ be born!
</div>

<div class="poem">
<p class = "verse">Then shall the burden of manhood,
<p class = "verse">Be it yellow or black or white,
<p class = "verse">And Poverty, Justice and Sorrow&mdash;
<p class = "verse">The Humble and Simple and Strong,
<p class = "verse">Shall sing with the Sons of Morning
<p class = "verse">And Daughters of Evensong:
</div>

<div class="poem">
<p class = "verse">Black mother of the iron hills that guard the blazing sea,
<p class = "verse">Wild spirit of a storm-swept soul a-struggling to be free,
<p class = "verse">Where &rsquo;neath the bloody finger marks, thy riven bosom quakes,
<p class = "verse">Thicken the thunders of God&rsquo;s voice, and lo! a world awakes!
</div>

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Unrest (1920)](/Volumes/19/05/unrest.html)
* [In God''s Gardens (1912)](/Volumes/03/06/in-gods-gardens.html)
* [The Christmas Prayers of God (1914)](/Volumes/09/02/christmas_prayers_of_god.html)
* [The Song of the Smoke (1914)](/Volumes/07/03/song_of_smoke.html)
* [The Quadroon (1911)](/Volumes/03/01/quadroon.html)

<!-- Similar articles end here -->