
---
title: 'A Correspondence'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 1
  page: 30
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The General Federation of (white) Women's Clubs sent a representative to
the meeting of the National Association of Colored Women at Wilberforce, and the magazine of the General Federation published an
excellent article concerning that meeting. On the strength of this the
magazine has evidently obtained the mailing list of the colored
organization and is sending this letter broadcast:

> GENERAL FEDERATION MAGAZINE
> &nbsp;    
> Only official organ of the General Federation of Women's Clubs   
> &nbsp;        
> New York, N. Y, Sept. 22, 1914.    
> &nbsp;    
> My dear Madam:   
> &nbsp;    
> Your name has been sent to me by Miss Zona Gale, formerly Chairman of
Civics of the General Federation of Women's Clubs, who recently spoke
before your Colored Women's Convention, as being one of the prominent
colored women in this country who would without doubt be interested in
the *General Federation Magazine*, which is the official organ of the
General Federation of Women's Clubs.       
> &nbsp;    
> I am using this month an account of your Convention by Miss Zona Gale
and I know you will be interested to see that in this important
Magazine. May I not hope for your support in the way of at least one
subscription to the Magazine? I would like to add this also: If one
woman could be appointed in each club or organization to take
subscriptions, she might find it profiable for herself or her
organization to make a business of this matter. The price of the
Magazine is $1.00 a year and we allow a discount of 25% on each
subscription. Can we not join our forces in some way? We should be glad
to give you publicity in the Magazine whenever you desire.       
> &nbsp;    
> We are sending you a sample copy of our Biennial number.       
> &nbsp;    
> Very cordially yours,
> &nbsp;    
> Harriet Bishop Waters,
> &nbsp;    
> *General Federation Magazine.*

This letter has received the following reply from <span class="crisis-title">The Crisis</span>

> Dear Madam:       
> &nbsp;    
> I have your circular concerning a subscription to the *General
Federation Magazine.*       
> &nbsp;    
> Do you think it is fair to ask a colored person to subscribe to the
official organ of an organization which discriminates against them so
outrageously as yours does?       
> &nbsp;    
> Very sincerely yours, etc.

We trust that similar letters will go from every colored woman
approached. This is not a matter of hatred or complaint. It is a matter
of self-respect. The General Federation of Women's Clubs has insulted
every black woman in America. They have deliberately and openly put a
brand on her. Clubs composed of every race and nation in America are
welcome to this federation except those of black women. Against this
contemptible action taken by northern white women to placate the petty
spite of southern white women colored women cannot and do not wish to
take any action. They are quietly and effectively doing their own club
work. But they refuse to forget the insult or condone it.

Above all they resent on the part of these narrow-minded white women the
assumption that-the exclusion of colored women's clubs from the General
Federation has "helped" the colored organization. The stealing of my
purse may make me careful and saving but I owe little gratitude to the
thief, and at all events for the thief to demand gratitude is adding
insult to injury.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Our Special Grievances (1918)](/Volumes/16/05/our_special_greivances.html)
* [Suffering Suffragettes (1912)](/Volumes/04/02/suffering_suffragettes.html)
* [White Co-Workers (1920)](/Volumes/20/01/white_coworkers.html)
* [The Next Step (1913)](/Volumes/06/02/next_step.html)
* [A Question (1920)](/Volumes/20/03/a-question.html)

<!-- Similar articles end here -->