
---
title: 'China'
author: Du Bois, W.E.B.
date: Feb. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 4
  page: 156
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



To most folk the wonder of the Chinese revolution is not in the revolution but in the fact that Chinamen show themselves so human. There was a time when everything bizarre, curious and topsyturvy was quite as a matter of course attributed to China. When it came to rational modern thought we calmly omitted China. Histories of the world omitted China; if a Chinaman invented compass or movable type or gunpowder we promptly "forgot it" and named only their European inventors. In short, we regarded China as a sort of different and quite inconsequential planet.

Suddenly now China looms as a modern nation seeking in the blood-lust of revolution the freedom to think and be. Shall we welcome Chinese rebirth with salvos of applause? Why---er---yes; yes, of course; but say, look here: what kind of a world is this going to be, full of civilized Japs, Chinks, dagoes and darkies? Isn't it high time for Desperate Desmond Hobson to wind his golden trumpet and hail us to war for the salvation of "white" civilization?

Soberly, is not the world face to face with an enlarged, broadened, endless "race" and "color" problem, and what are those folk to do who cannot conceive a world where black, brown and white are free and equal?

