
---
title: 'The Durbar'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 4
  page: 156
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The greatest concession wrung from an arrogant modern nation by a dark-skinned people has just been gained by the Indians from the English. The Durbar was not simply a ceremonial---it was a concession. For a long time England has been trying to conciliate India by social deference to her princes. Few of the great drawing rooms of London have not been graced in recent years by these Eastern potentates, and every public honor has been shown them. All this is an old method with rulers. Even with the American Negro the experiment is continually tried locally and nationally of extravagantly honoring leaders who can be depended on to do the tyrant's will unquestioningly.

The rank and file, however, soon learn to discriminate between such empty honors and the real good of the people. Ground down by ignorance and poverty, India demands education and political autonomy. Oppressed by color prejudice they demand the treatment of men.

The Durbar brought concessions in all these lines. Its political significance lay in the actual crowning of an English monarch in India. No longer is George V a foreign monarch ruling this land beyond the sea---he is an emperor crowned on Indian soil; moreover, his capital will be hereafter the ancient Indian capital of Delhi, and not the more English Calcutta, where a fierce native agitation has opened the eyes of England to the determination of young India to be free.

The Durbar marked the establishment of the first great fund for popular education in India, and finally it brought one curious concession, a concession which England must have been almost ashamed to announce: hereafter the Victoria Cross for bravery on the field of battle will be given to brown men as well as white! Thus ends a discrimination almost as disgraceful as the discrimination against colored candidates for Rhodes scholarships in the Southern United States.

How have these concessions been secured? By agitation---persistent and long-continued agitation, by unrest and protest which is not yet satisfied, and will not be until India is a free autonomous nation.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [India (1930)](/Volumes/37/08/india.html)
* [Gandhi and India (1921)](/Volumes/23/05/india_and_gandhi.html)
* [Egypt and India (1919)](/Volumes/18/02/egypt_and_india.html)
* [The Freeing of India (1947)](/Volumes/54/10/freeing_of_india.html)
* [West Indian Immigration (1924)](/Volumes/29/02/west_indian_immigration.html)

<!-- Similar articles end here -->