
---
title: 'The Gall of Bitterness'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 4
  page: 153
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Many people object to the policy of <span class="small-caps">The Crisis</span> because, as they usually put it, <span class="small-caps">The Crisis</span> is "bitter." Some add that our news is depressing or that we are determined to look on the dark side, and so forth. 

It may be acknowledged at the outset that <span class="small-caps">The Crisis</span> does not try to be funny. Not that we object to fun: our office is a cheerful place, with bits of sunshine and eager young lives and high joyful purpose. But our stock in trade is not jokes. We are in earnest. This is a newspaper. It tries to tell the Truth. It will not consciously exaggerate in any way, but its whole reason for being is the revelation of the facts of racial antagonism now in the world, and these facts are not humorous. 

True it is that this country has had its appetite for facts on the Negro problem spoiled by sweets. In earlier days the Negro minstrel who "jumped Jim Crow" was the typical black man served up to the national taste. It was the balmy day when slaves were "happy" and "preferred" slavery to all other possible states. Then came the sobering of abolition days and war, when for one horrified moment the world gazed on the hell of slavery and knew it for what it was. 

In the last fifteen years there has come another campaign of Joy and Laughter to degrade black folk. We have been told that all was well or if aught was wrong the wrong was with the colored man. We have had audiences entertained with "nigger" stories, tales of pianos in cabins, and of the general shiftlessness of the freedman, and concerted effort to make it appear that the wrongs of color prejudice are but incidental and trivial, while the shortcomings of black men are stupendous, if not fatal. 

This is the lie which <span class="small-caps">The Crisis</span> is here to refute. It is a lie, a miserable and shameful lie, which some black men have helped the white South to spread and been well paid for their pains. 

It is not easy to impress the real truth after this debauch of defamation, but we must try. In so trying we realize that the mere statement of the facts does not always carry its message. Often the lighter touch, the insinuation and the passing reference are much more effective. We know this, and yet so often the grim awfulness of the bare truth is so insistent we feel it our duty to state it. Take those stark and awful corpses, men murdered by lynch law, in last month's issue: it was a gruesome thing to publish, and yet---could the tale have been told otherwise? Can the nation otherwise awaken to the enormity of this beastly crime of crimes, this rape of law and decency? Could a neat joke or a light allusion make this nation realize what 2,500 murders such as these look like?

We trust that the Gall of Bitterness will not spoil the pages of <span class="small-caps">The Crisis</span> or make its readers to shudder at ill-timed frankness. But God forbid that mere considerations of pleasantry and sweetness should ever make us withhold insistence, in season and out, upon that which a Southern white correspondent of ours calls "the barbarous treatment accorded an unfortunate people by the strong and arrogant Caucasian. When Truth shall have come into her own, through the medium of education, the color line will be swept into oblivion of a dark and disgraceful past. Men will shudder at the deeds of their fathers, even as we shudder at the horrors of the Inquisition." 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Join or Die (1914)](/Volumes/07/03/fightordie.html)
* [Truth and Beauty (1922)](/Volumes/25/01/truth_and_beauty.html)
* [The Second Birthday (1912)](/Volumes/05/01/second_birthday.html)
* [The Crisis (1910)](/Volumes/01/01/TheCrisis.html)
* [The Truth (1912)](/Volumes/05/02/truth.html)

<!-- Similar articles end here -->