
---
title: 'Light'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 4
  page: 152-153
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


When the trustees of the Phelps-Stokes fund gave two Southern universities $12,500 each to endow a fellowship for the study of the Negro they did well. For many decades there has been a venerable tradition that the South "knows" the Negro better than others. Gradually, however, it is dawning even on the white South that	there	is nothing in mere physical distance half so separating as the artificial social, economic and racial barriers erected in the South since the war, and that the ignorance of the white South as to the life, hurts and dreams of the darker half of their world is, in some respects, both phenomenal and disgraceful. Take, for instance, this letter from a Southern woman who has read The Crisis:

> The Negro is a child, incompetent to right his own wrongs, but wonderfully susceptible to inspirational teaching. As a race he has a childlike conceit and thoroughly enjoys being 'in the limelight.' He has the untutored's love of the morbid, revels in the sensational, and under praise wisely ad­ministered gives forth his best efforts. Some of the crime committed by the Negro is undoubtedly due to the de­sire to attract public attention. 'If fame cannot be won, infamy can,' is the subconscious conclusion of some Negro criminals---as it is with some white criminals. It seems to me that the best and most practical philan­thropy that can be performed for the race is to cease discussing him as a problem and consider him as child whose future career is to be shaped and molded by wise disciplin­ary educational methods.

Consider for a moment this extraordinary judgment: "The Negro" and "A Child!" Ten million people tossed nonchalantly into one mold with one estimate, one final and eternal judg­ment. One could not find ten million dogs, much less ten million men, whom one definition would fit.

The difficulty is, of course, that this honest woman knows and can know but one or few types of Negro. Her observation is confined to her kitchen, the almshouse and the chances of the street. Of the black man as a man, of the black woman as a woman, she has almost no experience, and by grace of the color line can have no experience. Her ignorance is all the greater because it is not known to be ignorance, but parades as deep and subtle knowl­edge. The world-old phenomenon of the childishness, laziness and crimi­nality of the ignorant and oppressed becomes in her blindness purely a racial, a "Negro" trait. If the gift to the University of Virginia will do something to shake the appalling con­fidence of such wild judgments the money will be well spent.



Of course, the scientific result will be small. For many years these young students will record not the observed facts, but their preconceived prejudices. This is inevitable with persons who start despising and not revering human souls simply because of their humanity. Gradually, however, truth will triumph.	Gradually it will not be possible to assert unchallenged in the University of Geor­gia that "niggers are lazy." It will be explained by some perverse per­son that this laziness has somehow accumulated a thousand millions in fifty years---although, of course, those who did this are "exceptions." In time this center of learning will cease to talk of "the" Negro and begin to talk of men---some rich, some poor; some good, some bad; some undeveloped "children" and some children of the Kingdom of God.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Newer South (1926)](/Volumes/31/04/newer_south.html)
* [The Liberal South (1921)](/Volumes/21/06/liberal-south.html)
* [The Unfortunate South (1920)](/Volumes/19/04/unfortunate_south.html)
* [Votes for Negroes (1921)](/Volumes/21/03/votes-for-negroes.html)
* [Education (1911)](/Volumes/01/04/education.html)

<!-- Similar articles end here -->