
---
title: 'Heroes'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 1
  page: 337
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


We stand with uncovered heads before the tens of thousands of black men and women of the South who are fighting the real battle of Freedom. They are striking no blows — they are using no violence — they are uttering no threats — in most cases they are speaking no word. But they are standing with bleeding souls and streaming eyes, silently, steadfastly, before the altar of their own beliefs and aspirations. Not one by word, deed or gesture do they flinch.

They believe themselves the equals of any man, and not all the mobs of the bourbon South — not even death and torture — can make them deny it. Neither by money nor fear can they be induced to betray their race, either by the cringing deed of or by the lying admission; in the face of the slobbering "white folks' nigger" with his soothing syrup of false flattery and lies, they stand unmoved. They seek peace and self-respect, but before everything, they insist upon respect in themselves.

Their white neighbors know and secretly honor them. They wonder how such souls can live and endure the lot of the Negro in the South. Yet they do live, they do endure, and in God's good time such martyrdom must and shall win.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Votes for Negroes (1921)](/Volumes/21/03/votes-for-negroes.html)
* [The Liberal South (1921)](/Volumes/21/06/liberal-south.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [Light (1912)](/Volumes/03/04/light.html)

<!-- Similar articles end here -->