
---
title: 'The League of Nations'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 1
  page: 336-337
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The colored folk want the League of Nations. The proposed League is not the best conceivable---indeed, in some respects it is the worst. But the worst International is better than the present anarchy in international relations. This anarchy has just cost civilization two hundred thousand millions of dollars, eight million corpses, twenty million maimed pieces of men and untold and unmeasurable waste, destruction, sorrow, misery and crime.

To save human culture from a repetition of the Great War, a government of governments is proposed. In its present form it is oligarchic, reactionary, restricted and conservative, and it gives Imperialism, particularly Imperial England, unwarranted preponderance. Nevertheless, it has a democratic Assembly, it recognizes no color line, and it can enforce peace.

No opponent of the League offers anything better that has the slightest chance of adoption. Most opponents want no League at all. They want a swashbuckling anarchy, with a Jingo United States yelling in chorus with Jingoes of all Europe.

What boots it to complain now that Wilson did not stand to his moral guns at Paris, or that Egypt, India and Ireland are not free? Will they be any freer or the world any safer without some international bond of reason and sanity? No. Let us have the League with all its autocracy and then in the League let us work for Democracy of all races and men.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [League of Nations (1927)](/Volumes/33/03/league_of_nations.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [Close Ranks (1918)](/Volumes/16/03/close_ranks.html)
* [Just Like---Folks (1920)](/Volumes/19/05/just_like_folks.html)
* [Leadership (1920)](/Volumes/19/04/leadership.html)

<!-- Similar articles end here -->