
---
title: 'Social Equality'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
categories: 
  - Social Equality
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 1
  page: 337
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Every time the American Negro seeks reasonably and earnestly to bring his case before the white South and the nation the bourbons proceed to throw dust in the eyes of the public by screaming frantically, "Social Equality."

That bogey can be easily met: If "Social Equality" means the right to vote, the abolition of "Jim-Crow" cars, the stoppage of lynching, universal education and civil rights, then social equality is exactly what we want and what eventually we will and must have.

If, on the other hand, "Social Equality" involves the denial of the social right of any individual of any race or color to choose his own marital mate, his own friends and his own dinner companions---in fine, to be master of his own home, then no sane person ever dreamed of demanding the slightest interference with such an obvious right, and any one who accuses Negroes of such a demand writes himself down as an ass or a deliberate liar.

