
---
title: 'A Statement'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 1
  page: 335
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


At no previous period in the history of the Negro in America has he been confronted with a more critical situation than today. The forces of prejudice against which we are fighting seem determined to keep twelve millions of Americans in that bondage of prejudice because of race, while those twelve millions are determined as never before to achieve the status of citizens---full and unlimited by caste or color. When two forces of such magnitude meet, a critical situation is inevitable and such a one is upon us today.

There are those who are attempting to becloud the issue by declaring that the present unrest and discontent is due to influences other than natural resentment against wrong. Such persons are making such absurd statements either through ignorance of the facts or because they know the facts and are attempting to shift the responsibility for the half-century of lynching, disfranchisement, peonage, "Jim-Crowism" and injustice of every sort practiced on the Negro. We do not countenance violence. Our fight is against violence. We are fighting---as we always have fought---for the reign of law over the reign of the mob. No sane man or woman
can for a minute advise any group to use the torch or the gun to right the wrong of violence. Only in self defense can such a course ever be considered justifiable.

But we must fight and we are going to fight in every legitimate and lawful way until our problem is entirely settled. To do this we need greater organization, energy, funds and courage than ever before. The call is to you to rally to the support of the National Association for the Advancement of Colored People and help in the fight to make America safe for the colored man.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Liberal South (1921)](/Volumes/21/06/liberal-south.html)
* [The Truth (1912)](/Volumes/05/02/truth.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [Heroes (1919)](/Volumes/19/01/heroes.html)
* [Freedom of Speech (1930)](/Volumes/37/08/freedom.html)

<!-- Similar articles end here -->