
---
title: 'So the Girl Marries'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 6
  page: 192-193, 207-209
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The problem of marriage among our present American Negroes, is a difficult one. On the one hand go conflicting philosophies: should we black folk breed children or commit biological suicide? On the other, should we seek larger sex freedom or closer conventional rules? Should we guide and mate our children like the French or leave the whole matter of sex intermingling to the chance of the street, like Americans? These are puzzling questions and all the more so because we do not often honestly face them. 

I was a little startled when came father of a girl. I scented far-off difficulties. But she became soon a round little bunch of Joy: plump and jolly, full of smiles and fun---a flash of twinkling legs and bubbling mischief. Always there on the broad campus of Atlanta University she was in scrapes and escapades---how many I never dreamed until years, after: running away from her sleepy nurse; riding old Billy, the sage and dignified draft horse; climbing walls; bullying the Matron; cajoling the cooks and becoming the thoroughly spoiled and immeasurably loved Baby of the Campus. How far the spoiling had gone I became suddenly aware one summer, when we stopped a while to breathe the salt sea air at Atlantic City. This tot of four years marched beside me down the Boardwalk amid the unmoved and almost unnoticing crowd. She was puzzled. Never before in her memory had the world treated her quite so indifferently. 

"Papa," she exclaimed at last, impatiently, "I guess they don't know I'm here!" 

&nbsp;

As the Girl grew so grew her problems: School; Multiplication Tables; Playmates; Latin; Clothes---Boys! No sooner had we faced one than the other loomed, the last lingered---the next threatened. She went to Kindergarten with her playmates of the Campus---kids and half-grown-ups. The half-grown-ups, Normal students, did me the special courtesy of letting the Girl dawdle and play and cut up. So when she came at the age of ten to the Ethical Culture School in New York there loomed the unlearned Multiplication Table; and a time we had! For despite all proposals of "letting the Child develop as it Will!," she must learn to read and count; and the school! taught her---but at a price! Then came the days of gawky growth; the impossible children of the street; someone to play with; wild tears at going to bed; excursions, games---and far, far in the offing, the shadow of the Fear of the Color Line. 

I had a Grand Idea. Before the time loomed---before the Hurt pierced and lingered and festered, off to England she should go for high school and come back armed with manners and knowledge, cap-a-pie, to fight American race hate and insult. Off the Girl went to Bedale's, just as war thundered in the world. As a professor of Economics and History, I knew the war would be short---a few months. So away went Mother and Girl. Two mighty years rolled turbulently by and back came both through the Submarine Zone. The Girl had grown. She was a reticent stranger with whom soul-revealing converse was difficult. I found myself groping for continual introductions.

&nbsp;

Then came Latin. The English teacher talked Latin and his class at Bedale's romped with Caesar through a living Gallia. The American teacher in the Brooklyn Girl's High did not even talk English and regarded Latin as a crossword puzzle with three inches of daily solution. "Decline Stella!"; "Conjugate Amo"; "What is the subject of 'Gallia est omnis divisa------'." "Nonsense," said the Girl (which was quite true) "I've dropped Latin." 

"But the colleges haven't, I moaned. "Why college?" countered the Girl. 

Why indeed? I tried Cicero "pro Archia Poeta." The Girl was cold. Then I pleaded for my own spiritual integrity: "I have told 12 millions to go to college---what will they say if you don't go?" The Girl admitted that that was reasonable but she said she was considering marriage and really thought she knew about all that schools could teach effectively. I, too, was reasonable and most considerate, despite the fact that I was internally aghast. This baby---married---My God!---but, of course, I said aloud: Honorable state and all that; and "Go ahead, if you like---but how about a year in college as a sort of, well, introduction to life in general and for furnishing topics of conversation in the long years to come? How about it?" "Fair enough," said the Girl and she went to college. 

&nbsp;

Boys! queer animals. Hereditary enemies of Fathers-with-daughters and Mothers! Mother had chaperoned the Girl relentlessly through High School. Most Mothers didn't bother. It was a bore and one felt like the uninvited guest or the veritable Death's Head. The Girl didn't mind much, only---"Well, really Mother you don't need to go or even to sit up." But Mother stuck to her job. I've always had the feeling that the real trick was turned in those years, by a very soft-voiced and persistent Mother who was always hanging about unobtrusively. The boys liked her, the girls were good-naturedly condescending; the Girl laughed. It was so funny. Father, of course, was busy with larger matters and weightier problems, including himself. 

Clothes. In the midst of high school came sudden clothes. The problem of raiment. The astonishing transformation of the hoyden and hiker and basketball expert into an amazing butterfly. We parents had expressed lofty distain for the new colored beauty parlors---straightening and bleaching, the very idea! But they didn't straighten, they cleaned and curled; they didn't whiten, they delicately darkened. They did for colored girls' style of beauty what two sophisticated centuries had been doing for blonde frights. When the finished product stood forth all silked and embroidered, briefly skirted and long-limbed with impudent lip-stick and jaunty toque---well, Thrift hung its diminished head and Philosophy stammered. What shall we do about our daughter's extravagant dress? The beauty of colored girls has increased 100% in a decade because they give to it time and trouble. Can we stop it? Should we? Where shall we draw the line, with good silk stockings at $1.95 per pair? 

"Girl! You take so long to dress! I can dress in fifteen minutes." 

"Yes---Mamma and you look it!" came the frankly unfilial answer. 

&nbsp;

College. College was absence and premonition. Empty absence and occasional letters and abrupt pauses. One wondered uneasily what they were doing with the Girl; *who* rather than what was educating her. Four years of vague uneasiness with flashes of hectic and puzzling vacations. Once with startling abruptness there arose the Shadow of Death---acute appendicitis; the hospital---the cold, sharp knife; the horror of waiting and the namelessly sweet thrill of recovery. Of course, all the spoiling began again and it literally rained silk and gold. 

Absence, too, resulted in the unexpected increase in Parent-valuation. Mother was enshrined and worshipped by the absent Girl; no longer was she merely convenient and at times in the way. She was desperately adored. Even Father took on unaccustomed importance and dignity and found new place in the scheme of things. We both felt quite set up. 

Then graduation and a Woman appeared in the family. A sudden woman---sedate, self-contained, casual, grown; with a personality---with wants, expenses, plans. "There will be a caller tonight."---"Tomorrow night I'm going out." 

It was a bit disconcerting, this transforming of a rubber ball of childish joy into a lady whose address was at your own house. I acquired the habit of discussing the world with this stranger---as impersonally and coolly as possible: teaching---travel---reading---art---marriage. I achieved quite a detached air, letting the domineering daddy burst through only at intervals, when it seemed impossible not to remark---"It's midnight, my dear," and "when is the gentleman going? You need sleep!" 

&nbsp;

My part in Mate-selection was admittedly small but I flatter myself not altogether negligible. We talked the young men over---their fathers and grandfathers; their education; their ability to earn particular sorts of living; their dispositions. All this incidentally mind you---not didactically or systematically. Once or twice I went on long letter hunts for facts; usually facts were all too clear and only deductions necessary. What was the result? I really don't know. Sometimes I half suspect that the Girl arranged it all and that I was the large and solemn fly on the wheel. At other times I flatter myself that I was astute, secret, wise and powerful. Truth doubtless lurks between. So the Girl marries. 

I remember the Boy came to me somewhat breathlessly one Christmas eve with a ring in his pocket. I told him as I had told others. "Ask her---she'll settle the matter; not I." But he was a nice boy. A rather unusual b0y with the promise of fine manhood. I wished him luck. But I did not dare plead his cause. I had learned---well, I had learned. 

Thus the world grew and blossomed and changed and so the Girl marries. It is the end of an era---a sudden break and beginning. I rub my eyes and readjust my soul. I plan frantically. It will be a simple, quiet ceremony------ 

"In a church, father!" 

"Oh! in a church? Of course, in a church. Well, a church wedding would be a little larger, but------" 

"With Countée's father and the Reverend Frazier Miller assisting." 

"To be sure---well, that is possible and, indeed, probable." 

"And there will be sixteen bridesmaids." 

One has to be firm somewhere---"But my dear! who ever heard of sixteen bridesmaids!' 

"But Papa, there are eleven Moles and five indispensables and Margaret------" 

&nbsp;

Why argue? What has to be, must be; and this evidently had to be 
I struggled faintly but succumbed 
Now with sixteen bridesmaids and ten 
ushers must go at least as many invited guests. 

You who in travail of soul have struggled with the devastating puzzle of selecting a small bridge party out of your total of twenty-five intimate friends, lend me your sympathy! For we faced the world-shattering problem of selecting for two only children, the friends of a pastor with twenty-five years service in one church; and the friends of a man who knows good people in forty-five states and three continents. I may recover from it but I shall never look quite the same. I shall always have a furtive feeling in my soul. I know that at the next corner I shall meet my Best Friend and remember that I forgot to invite him. Never in all eternity can I explain. How can I say: "Bill, I just forgot you!" Or "My *dear* Mrs. Blubenski, I didn't remember where on earth you were or indeed if you were at all or ever!" No, one can't say such things. I shall only stare at them pleadingly, in doubt and pain, and slink wordlessly away. 

Thirteen hundred were bidden to the marriage and no human being has one thousand three hundred friends! Five hundred came down to greet the bride at a jolly reception which I had originally planned for twenty-five. Of course, I was glad they were there. I expanded and wished for a thousand. Three thousand saw the marriage and a thousand waited on the streets. It was a great pageant; a heart-swelling throng; birds sang and Melville Charlton let the organ roll and swell beneath his quivering hands. A sweet young voice sang of Love; and then came the holy: 

"Freudig gefuert, Ziehet dahin!" 

&nbsp;

The symbolism of that procession 
was tremendous. It was not the mere marriage of a maiden. It was not simply the wedding of a fine young poet. It was the symbolic march of young and black America. America, because there was Harvard, Columbia, Smith, Brown, Howard, Chicago, Syracuse, Penn and Cornell. There were three Masters of Arts and fourteen Bachelors. There were poets and teachers, actors, artists and students. But it was not simply conventional America---it had a dark and shimmering beauty all its own; a calm and high restraint and sense of new power; it
was a new race; a new thought; a new thing rejoicing in a ceremony as old as the world. (And after it all and before it, such a jolly, happy crowd; some of the girls even smoked cigarettes!) 

Why should there have been so much of pomp and ceremony---flowers and carriages and silk hats; wedding cake and wedding music? After all marriage in its essence is and should be very simple: a clasp of friendly hands; a walking away together of Two who say
"Let us try to be One and face and fight a lonely world together!" What more? Is that not enough? Quite; and were I merely white I should have sought to make it end with this. 

&nbsp;

But it seems to me that I owe 
something extra to an Idea, a Tradition. We who are black and panting up hurried hills of hate and hindrance---we have got to establish new footholds on the slipping by-paths through which we come. They must at once be footholds of the free and the eternal, the new and the enthralled. With all of our just flouting of white convention and black religion, some things remain eternally so---Birth, Death, Pain, Mating, Children, Age. Ever and anon we must point to these truths and if the pointing be beautiful with music and ceremony or bare with silence and darkness---what matter? The width or narrowness of the gesture is a matter of choice. That one will have it stripped to the essence. It is still good and true. This soul wants color with bursting cords and scores of smiling eyes in happy raiment. It must be as this soul wills. The Girl wills this. So the Girl marries. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Correspondence (1926)](/Volumes/31/05/correspondence.html)
* [Intermarriage (1927)](/Volumes/33/03/intermarriage.html)
* [Inter-Marriage (1924)](/Volumes/29/06/inter-marriage.html)
* [It is a Girl (1933)](/Volumes/40/02/its_a_girl.html)
* [Intermarriage (1913)](/Volumes/05/04/intermarriage.html)

<!-- Similar articles end here -->