
---
title: 'Sunny Florida'
author: Du Bois, W.E.B.
date: Jun. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 6
  page: 203-204
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There is probably no modern play-ground whose social foundation is more
utterly false and criminal than Florida. Before the boom, Florida was a
lovely, sleepy semi-tropical land with a working class predominantly Negro and with unusually cordial
relations between the races, albeit based on the old slave paternalism.
Then came fruit culture, land exploitation, fashion propaganda, easy
liquor and open gambling. The demand for labor and service brought a
mass of immigrants from the neighboring poor whites of Georgia and
Alabama and even further away. A bitter rivalry arose between the white
and black workers and the black workers, deprived of political power,
went further and further to the wall. The white workers were debauched
by the chances of high wage, graft and illegitimate methods of making
money of all sorts.

The results of all this could be illustrated in a hundred ways, but let
us take one recent case:

July 15, 1925. In Miami, Police Sergeant Tibbits is shot. The police
have no clue.

July 16, 1925. A Negro, H. Kier, was found shot to death in the
Northwest part of the city near the ball park.

July 17, 1925. Tibbits will recover. Chief of Police, H. L. Quigg,
offers a reward of $500 for the arrest and conviction of his unknown
assailant.

March, 1928. Tibbits, now Lieutenant, together with a city detective,
are arrested. The Grand Jury investigating alleged police brutalities,
returned indictments against Tibbits and others, charging them with the
murder of Kier. A police detective testifying declares that Kier, a
bellboy, was accused of carrying a message for a white man to a white
woman asking the woman to meet the man. The woman's mother complained to
the hotel proprietor and identified Kier as the messenger. The police
were called. Kier denied his guilt but was knocked to the floor by a
policeman's club. When he was able to get up, he said that he was
guilty. The proprietor asked the detective "not to murder the boy in my
hotel." They took the Negro to police headquarters where the Chief of
Police, H. L. Quigg, told them not to enter any charge against him. The
policemen took Kier in an automobile out to the Northwestern part of the
city. Then they threw him out and tried to shoot him. The first shot
went wild and struck Tibbits. They continued shooting and when Kier was
dead they left the body on the highway and carried Tibbits to the
hospital. Chief of Police Quigg called and advised them to agree on a
story. He asked the officers to go and hide the body, but they refused.
They agreed, however, to say that the Negro had grabbed Tibbits' gun and
that the other officers fired in self-defense, in case the matter ever
came to court.

March 24, 1928. H. L. Quigg, Miami Chief of Police, is charged with
first degree murder, together with Tibbits and others.

April 17, their trial begins.

April 29, Quigg and his co-defendants are acquitted.

There was, of course, no chance that Quigg and his colleagues would
suffer any severe punishment. It is alleged that for years they have
been at the head of the ring which sells the privilege to gamble and
import liquor in the city of Miami, and that Quigg is a very rich man.

