
---
title: 'Woman Suffrage'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 6
  page: 57
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




In the fall of 1915 the colored voters of Massachusetts, New York, New Jersey and Pennsylvania are going to be asked for their opinion on the enfranchisement of women. There were in 1910, 151,341 Negro voters in these states. The number is probably near 200,000 today. It is safe to say that in an electorate of over 5,000,000 these 200,000 votes may easily hold a balance of power and certainly would be a valuable asset. Undoubtedly among Negro voters there is a good deal of indifference and lack of knowledge concerning woman suffrage. We tend to oppose the principle because we do not like the reactionary attitude of most white women toward our problems. We must remember, however, that we are facing a great question of right in which personal hatreds have no place. Every argument for Negro suffrage is an argument for woman's suffrage; every argument for woman suffrage is an argument for Negro suffrage; both are great movements in democracy. There should be on the part of Negroes absolutely no hesitation whenever and wherever responsible human beings are without voice in their government. The man of Negro blood who hesitates to do them justice is false to his race, his ideals and his country.

*Citation:* Du Bois, W.E.B. 1915. "Woman Suffrage." *The Crisis*. 9(6):57.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Votes for Women (1918)](/Volumes/15/01/votes_for_women.html)
* [Ohio (1912)](/Volumes/04/04/ohio.html)
* [Votes for Women (1914)](/Volumes/08/04/votes_for_women.html)
* [Votes for Women (1912)](/Volumes/04/05/votes_for_women.html)
* [Votes (1919)](/Volumes/19/02/votes.html)

<!-- Similar articles end here -->