
---
title: 'Aiken'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 1
  page: 34
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




Does America thoroughly realize Aiken? Citizens declared by South Carolina courts of law to be either entirely innocent of crime or of unproven guilt have been openly murdered by persons well-known to the public. The authorities so far have refused to indict or arrest these murderers or to make any real inquiry into their guilt. These red-handed assassins walk the streets of Aiken today free, impudent and unafraid. And the city of Aiken is advertised in the public press as an "attractive" winter resort!

What shall we do? The Constitution of the United States guarantees each state "A republican form of government." Blease, the lynchers' United States Senator, was elected by less than one-tenth of the qualified voters of the state. The lynchers and the Ku Klux Klan rule the city of Aiken and its county.

Is it possible that we the people of the United States, 120 millions strong, with a great army of 120,000 men and a navy costing $300,000,000 a year; with 47 million Christians in hundreds of thousands of churches; with millionaire Foundations for Uplift, Art and Charity; with missionaries in China, India and Africa; we who in spotless holiness refuse to recognize Russia and curse the Grand Turk; we who in absolute and impeccable fairness and justice forgive no single foreign debtor a red cent if we can squeeze it from his bankrupt soul; this "Land of the Free and Home of the Brave," that boasts before God its Fundamental Righteousness---is it possible that in Aiken we can do nothing, nothing, NOTHING?

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Lynching (1911)](/Volumes/02/04/lynching.html)
* [Anti-Lynching Legislation (1922)](/Volumes/22/01/anti-lynching_legislation.html)
* [Lynching (1926)](/Volumes/32/01/lynching.html)
* [Lynching (1914)](/Volumes/07/05/lynching.html)
* [Scottsboro (1934)](/Volumes/41/01/scottsboro.html)

<!-- Similar articles end here -->