
---
title: 'About Pugilists'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 5
  page: 198-199
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Before 1914 our minds were made up and pugilism was generally discredited as a disreputable, if not immoral, occupation. We were especially strengthened in this attitude because Mr. Jack Johnson became champion heavyweight in those days. As pugilists went, he was voted a good one, good-natured and fair in his tactics, and could only be criticised for his color and his wretched taste in the matter of women. Then came the War and as a result pugilism became The Manly Art. Society and Government encouraged it and witnessed the bout of Mr. Dempsey and M. Carpentier; and then, lo! and unfortunately, Mr. Johnson appears upon the
scene and our moral indignation begins again; but it is directed now not against pugilism but against Mr. Johnson, the reason being that Mr. Johnson has just come out of jail. That he was sent to Leavenworth on a technical charge which would put hundreds of thousands of Americans in the same place if the law were rigidly enforced, matters little. He must be kept from contaminating pugilism, which has grown reputable since he was incarcerated.

All this is rather funny now, but before America becomes a leader of civilization it must cease to be funny and our Moral Indignations must be made to square with the facts. Is it Pugilism or Color which calls for a throb of Christian Endeavor? And where is the correspondingly greater throb for lynching and mob violence? And if ministers and Sunday Schools are silent at the burning of human beings alive, how shocked and indignant can they get at the public blows of Mr. Dempsey? And if Mr. Dempsey is a gentleman who deserves the concentrated attention of the civilized world, how much less so is Mr. Johnson, and why?

