
---
title: 'Of Boards'
author: Du Bois, W.E.B.
date: Mar. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 5
  page: 197-198
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Graceful interlude at Detroit was the quite unexpected presentation of a loving cup to Miss Ovington, Chairman of the Board, and of a travelling bag to the Secretary, Mr. Johnson, as a token of appreciation by the Branches of their work for the Association.

The writer has spent all his life working for boards—boards of trustees, boards of directors and committees—during which time he himself has usually been a member of some board, some committee or some faculty. He appreciates vividly, therefore, the advantages and disadvantages and the difficulties of this mode of human government, for such it is. In the future, in increasing degree, industry, social control and political government are going to be carried on by this method of democracy, and perhaps we ought to be more seriously preparing for it and adjusting our canons of praise and blame; especially when it is as conspicuously successful as in the case of the N.A.A.C.P. and its two chief executive officers, Miss Ovington and Mr. Johnson.

We should examine the reasons for success and the pitfalls of failure. Board members rather easily and obviously differentiate themselves into the quite careless and the over-zealous classes. The one regards his membership on the board as an indiscretion or a joke; the other mistakes himself for the executive officer whom the board is supposed to control.

If the board inclines to the first type and the executive officer is strong and resourceful, your organization becomes a kind of successful monarchy with the board as a sort of honorary Privy Council. In the other case the executive officer becomes a chief clerk and the board a real executive, working usually through committees. However successful this method may be for a time, it suffers from lack of continuity in policy, lack of foresight, and it usually ends in the rather curt dismissal of the unoffending executive officer.

Between these extremes stretch the usual boards of directors, and the success of the organization depends upon the relationship that comes to be established between the board and its executives.

Most often the board fails in efficiency because through absences different boards really meet in the different months and, with curious insouciance, one meeting will inaugurate a policy which the other meeting will entirely overturn. Or again, boards naturally dislike responsibility and indeed can only with difficulty carry responsibility, especially for the raising of funds and the laying down of principles and future lines of work. They are apt to fail in prescience, in the far look ahead and especially in their reception of new and unusual ideas. They naturally seek quickly a fixed program of work and a routine.

Opposed to these tendencies, in a sense, stand the executives, and, because they are thus opposed, their position and tenure of office are apt to be in jeopardy. They see through a thousand eyes new calls, new changes, new ideas, exceedingly difficult to explain in the routine of an hour's meeting. They find responsibilities thrust upon them which they dare not evade and yet have insufficient power to bear; however, out of all this, if the organization is successful, there comes the kind of balance which is the ideal of real democracy; an executive trusted, free within wide bounds, unhampered and yet in the end controlled by sympathetic men of less technical but more general knowledge than the executives, who are kept in constant touch with his problems and form real counselors, willing at his word to assume even great personal responsibility.

For some such accomplishment as this the loving cup was given "To Mary White Ovington, Chairman of the Board of Directors, the National Association for the Advancement of Colored People, from the Branches in token of their love for her and in appreciation of her loyal and courageous service to the cause of Social Justice and Democracy."

Miss Ovington's task has been doubly difficult because she is white, a woman, and an unsalaried worker. It is becoming difficult for colored and white people to work together in the modern world because they are beginning to meet upon a different plane. The old plane of Giver and Beggar, while still with us, is passing in its dominance and significance. The new plane of equal social co-worker is hard to establish, because, on the one hand, it is difficult for any white person born in America to think of the Negro as his equal, and on the other hand, it is difficult for a Negro to approach a white person without suspicion and bad manners.

Add to this the fact that men do not easily work with women as equals, that the usual volunteer worker is anathema in a real executive office, and Miss Ovington's accomplishment in the last few years has been extraordinary.

Mr. Johnson's work calls for no less praise. Trained as a poet and literary man, but turned in his manhood to important diplomatic work for his country, he found himself in the midst of life suddenly checked in his career because of the race prejudice of the politically dominant South. With the somewhat uneasy acquiescence of his friends and the criticism of others, he then took up an executive work involving tedious details, constant attendance and hard labor. He did this too in succession to one of the best trained social workers in the United States, and at a time of collapse and reconstruction throughout the world. To have pulled the N.A.A.C.P. through this morass into a higher and stronger position was an accomplishment deserving the highest praise. In addition to this, Mr. Johnson has kept up his literary work and accomplished a piece of diplomacy in Haiti which stands as one of the greatest single achievements done in colored America.

Loving cups and travelling bags are very little things, but they mean a lot to the servants of boards of directors.

