---
title: 'Girls'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar.. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 5
  page: 200
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

I attended the East Central Field School Girls' Conference at the Germantown Y.W.C.A. It was not only a wonderful thing to see these hundreds of bright and pretty colored high school girls, but the finest thing about it was that they were noisy, happily noisy. One gets, particularly in southern colored schools, an impression of portentous silence and primness on the part of young students. New England discipline, long dead in its own home, has descended curiously to the colored missionary schools of the South so that one seldom gets the spontaneous ebullition of the frank and glorious animal spirits which youth has a right to have. But at the Germantown conference, with girls from all the eastern cities of the Middle States, and with white and colored workers, there was a joy and abandon, a blending of team work, art, laughter and music which was more than uplifting. It was big with hope.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Balls (1919)](/Volumes/18/06/balls.html)
* [College Education (1914)](/Volumes/08/03/college_education.html)
* [The High School (1911)](/Volumes/02/03/high_school.html)
* [The Technique of Race Prejudice (1923)](/Volumes/26/04/technique.html)
* [Reconstruction (1919)](/Volumes/18/03/reconstruction.html)

<!-- Similar articles end here -->