---
title: 'Railroad Unions'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 5
  page: 200
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


In the fight against predatory capital the railroad unions richly deserve defeat. They have been head and foot of a contemptible monopoly of labor, and by the open exclusion of Negroes, of Italians, of Jews and of any weak or disadvantaged group, they have deliberately and ruthlessly built up their own high wages and exclusive privileges, on the starvation, unemployment, sickness and destitution of the common laborer. They deserve defeat. They deserve to have their unions smashed. They cannot look for votes or sympathy from the mass of the laboring whites, and especially the blacks.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Does Organization Pay? (1914)](/Volumes/07/06/does_organization_pay.html)
* [Organized Labor (1912)](/Volumes/04/03/organized_labor.html)
* [To the American Federation of Labor (1924)](/Volumes/28/04/american_federation_of_labor.html)
* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)
* [The A.F. of L. (1933)](/Volumes/40/12/af_of_l.html)

<!-- Similar articles end here -->