
---
title: 'The Spread of Socialism'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 5
  page: 199-200
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Readers of headlines in the daily press may, if they live in the United States, be lead to think that Socialism is on its last legs and was quite discredited by the Great War. It is a singular comment upon our newspapers to know that exactly the opposite is true. Never before was Socialism so widespread and so powerful. Today Socialists rule Russia, Germany, Czechoslovakia, Jugo-Slavia, Italy, France, and Belgium. In nearly every other leading nation they are strong, except in the United States and Japan.

This, of course, brings up the question as to what is meant by Socialism and here is room for intricate argument. But in general one means to say by Socialism the assertion by the community of its right to control business and industry; the denial of the old assumption that public business can ever be a private enterprise. Everywhere in the world Socialism in this broad sense is dominating and it is growing fast in the United States. Quite characteristically, many of those who recognize and exploit it deny that the new idea is Socialistic and try to fasten on Socialism every crazy scheme that any radical ever advocated. Colored Americans, however, need to think straight. Business is no longer "private" and in the future will be less so. Income is increasingly a matter of public control. Democracy will succeed only in so far as it gains intelligent control of industry. This is the future which the world faces and its success is the success of civilization.

