
---
title: 'In God''s Gardens'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 6
  page: 235
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



<div class="poem">
<p class = "verse">O mist-blown Lily of the north,
<p class = "verse">A-bending southward in thy bloom,
<p class = "verse">And bringing beauty silver sown
<p class = "verse">And pale blue radiance of snows&mdash;
</div>

<div class="poem">
<p class = "verse">O fair white ily, bowing low,
<p class = "verse">Above the dream-swept poppy&rsquo;s mouth,
<p class = "verse">Athwart the black and crimson South&mdash;
<p class = "verse">Why dost thou fear&mdash;why dos thou fear?
</div>

<div class="poem">
<p class = "verse">Lo! sense its sleep-sown subtle breath,
<p class = "verse">Where wheel in passioned whirl above
<p class = "verse">All lingering, luring love of love&mdash;
<p class = "verse">All perfume born of dole and death.
</div>

<div class="poem">
<p class = "verse">Cold ghost-wreathed Lily of the North,
<p class = "verse">When once thy dawning darkens there,
<p class = "verse">Come then with sunlight-sifted hair
<p class = "verse">And seek the haunting heaven of Night.
</div>

<div class="poem">
<p class = "verse">Where, over moon-mad shadows whirled,
<p class = "verse">The star-tanned mists dim swathe the sky
<p class = "verse">In phantasy to dream and die&mdash;
<p class = "verse">A wild sweet wedding of the World.
</div>

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Burden of Black Women (1914)](/Volumes/09/01/burden_of_black_women.html)
* [The Christmas Prayers of God (1914)](/Volumes/09/02/christmas_prayers_of_god.html)
* [Curtains of Pain (1917)](/Volumes/13/04/curtains_of_pain.html)
* [The Gospel According to Mary Brown (1919)](/Volumes/19/02/gospel.html)
* [Easter-Emancipation 1863-1913 (1913)](/Volumes/05/06/easter-emancipation.html)

<!-- Similar articles end here -->