
---
title: 'My Mission'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 1
  page: 7-9
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


I went to Paris because today the destinies of mankind center there. Make no mistake as to this, my readers. Podunk may easily persuade itself that only Podunk matters and that nothing is going on in New York. The South Sea Islander may live ignorant and careless of London. Some Americans may think that Europe does not count, and a few Negroes may argue vociferously that the Negro problem is a domestic matter, to be settled in Richmond and New Orleans.

But all these careless thinkers are wrong. The destinies of mankind for a hundred years to come are being settled today in a small room of the *Hotel Crillon* by four unobtrusive gentlemen who glance out speculatively now and then to Cleopatra's Needle on the Place de la Concorde.

You need not believe this if you do not want to. They do not care what you believe. They have the POWER. They are settling the world's problems and you can believe what you choose as long as they control the ARMIES and NAVIES, the world supply of CAPITAL and the PRESS.

Other folks of the world who think, believe and act;---THIRTY-TWO NATIONS, PEOPLES and RACES, have permanent headquarters in Paris. Not simply England, Italy and the Great Powers are there, but all the little nations; not simply little nations, but little groups who want to be nations, like the Letts and Finns, the Armenians and Jugo-Slavs, Irish and Ukrainians. Not only groups, but races have come---Jews, Indians, Arabs and All-Asia. Great churches, like the Greek Orthodox and the Roman Catholic, are watching on the ground. Great organizations, like the American Peace Society, the League to Enforce Peace, the American Federation of Labor, the Woman's Suffrage Association and a hundred others are represented in Paris today.

In fine, not a single great, serious movement or idea in Government, Politics, Philanthropy or Industry in the civilized world has omitted to send and keep in Paris its Eyes and Ears and Fingers! And yet some American Negroes actually asked WHY I went to help represent the Negro world in Africa and America and the Islands of the Sea.

But why did I not explain my reasons and mission before going? Because I am not a fool. Because I knew perfectly well that any movement to bring the attention of the world to the Negro problem at this crisis would be stopped the moment the Great Powers heard of it. When, therefore, I was suddenly informed of a chance to go to France as a newspaper correspondent, I did not talk---I went.

What did I do when I got there? First, there were certain things that I did NOT do. I did not hold an anti-lynching meeting on the Boulevard des Italiens. I would to God I could have, but I knew that France is still under martial law,---*that no meeting can be held today in France, anywhere or at any time, without the consent of the Government; no newspaper can publish a line without the consent of the Censor and no individual can stay in France unless the French consent.*

But it did not follow that because I could not do everything I could do nothing. I first went to the American Peace Commission and said frankly and openly: "I want to call a Pan-African Congress in Paris." The Captain to whom I spoke smiled and shook his head. "Impossible," he said, and added: "The French Government would not permit it." "Then," said I innocently: "It's up to me to get French consent!" "It is!" he answered, and he looked relieved.

With the American Secret Service at my heels I then turned to the French Government. There are six colored deputies in the French Parliament and one is an under-secretary in the War Department. "Of course, we can have a Pan-African Congress," he said---"I'll see Clemenceau." He saw Clemenceau, and there was a week's pause. Clemenceau saw Pichon, and there was another pause. Meantime, our State Department chuckled and announced that there would be no Congress and refused Negroes passports. England followed suit and refused to allow the Secretary of the Aborigines Protection Society even to visit Paris, while the South African natives were not allowed to sail.

But there are six Negroes in the French House and Clemenceau needs their votes. There were 280,000 black African troops in the war before whom France stands with uncovered head. The net result was that Clemenceau, Prime Minister of France, gave us permission to hold the Pan-African Congress in Paris.

What could a Pan-Afrian Congress do? I could not agitate the Negro problem in any particular country, except in so far as that problem could be plausibly shown to be part of the problem of the future of Africa. The problem of the future of Africa was a difficult and delicate question before the Peace Conference---so difficult and so delicate that the Conference was disposed to welcome advice and co-operation.

 If the Negroes of the world could have maintained in Paris during the entire sitting of the Peace Conference a central headquarters with experts, clerks and helpers, they could have settled the future of Africa at a cost of less than $10,000.

As it was the Congress cost $750. Yet with this meagre sum a Congress of fifty-eight delegates, representing sixteen different Negro groups, was assembled. This Congress passed resolutions which the entire press of the world has approved, despite the fact that these resolutions had two paragraphs of tremendous significance to us:

> Wherever persons of African descent are civilized and able to meet the tests of surrounding culture, they shall be accorded the same rights as their fellow citizens; they shall not be denied on account of race or color a voice in their own Government, justice before the courts and economic and social equality according to ability and desert.    
&nbsp;    
> Whenever it is proven that African natives are not receiving just treatment at the hands of any State or that any State deliberately excludes its civilized citizens or subjects of Negro descent from its body politic and cultural, it shall be the duty of the League of Nations to bring the matter to the attention of the civilized world,

Precisely the same principles are being demanded today by the Jews  and the Japanese. And despite the enormous significance of these demands, Colonel House of the American Peace Commission received me and assured me that he wished these resolutions presented to the Peace Conference. Lloyd George wrote me that he would give our demands "his careful consideration." The French Premier offered to arrange an audience for the President and Secretary of the Conference. Portugal and Belgium, great colonial powers, offered complete co-operation.

The League for the Rights of Man, which freed Dreyfus, appointed a special commission to hear not only of the African, but the facts as to the American Negro problem.

We got, in fact, the ear of the civilized world and if it had been possible to stay longer and organize more thoroughly and spread the truth,---what might not have been accomplished?

As it was, we have organized the "Pan-African Congress" as a permanent body, with M. Diagne as president and myself as secretary, and we plan an international quarterly BLACK REVIEW to be issued in English, French and possibly in Spanish and Portuguese.

The world-fight for black rights is on!

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Our Book Shelf (1926)](/Volumes/31/03/book_shelf.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [London (1911)](/Volumes/02/04/london.html)
* [Violations of Property Rights (1911)](/Volumes/02/01/violations.html)
* [The White Church (1917)](/Volumes/14/01/white_church.html)

<!-- Similar articles end here -->