
---
title: 'Robert R. Moton'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 1
  page: 9
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Neither R. R. Moton nor W. E. B. Du Bois had the slightest idea that the other was planning to sail for France, December 1, until they met in Washington on a quest for passports, November 30. They sailed together on the Orizaba and frankly discussed their agreements and disagreements. When they reached France, each went about his own business. 

Dr. Moton was sent by the President of the United States and the Secretary of War to see and talk to Negro troops. Dr. Du Bois was sent by the N.A.A.C.P. and <span class="small-caps">The Crisis</span> to gather the historical facts concerning Negro troops and to call a Pan-African Congress. 

On the night before Dr. Moton started out a colored man of national reputation and unquestioned integrity who had been in France six months took him aside and told him frankly the situation: the rampant American prejudice against black troops and officers and the bitter resentment of the victims. Dr. Mton's letters gave him every opportunity. A special Army Order preceded him, which read: 

> Dr. R. R. Moton, President of Tuskegee University, will be present in the Divisional area for the next few days. The Division Commander directs that commanding officers render all possible assistance in any visit or inspection Dr. Moton desires to make. They will also see that he is accorded every opportunity to make any observation he may wish to make. 

What did Dr. Moton do? He rushed around as fast as possible. He took with him and had at his elbow every moment that evil genius of the Negro race, Thomas Jesse Jones, a white man. Dr. Moton took no time to investigate or inquire. He made a few speeches, of which one is reported by a hearer as follows: 

> The address delivered by Dr. Moton to the men consisted of one or two jokes by a colored preacher, the assurance that the people at home were proud of them and the manner in which they should act upon their return to the United States, dwelling almost entirely upon the phrase "Not to be arrogant." After he had spoken to the men the Major informed the officers that Dr. Moton desired to hold secret conference with them.  All officers congregated in the office. After being presented to the officers Dr. Moton stated that he had been sent to France by President Wilson and Mr. Baker for the purpose of speaking to the colored troops. He also stated that he had just left Paris where he had been in conference with President Wilson and had asked the President his views as to the practical application of democracy toward the colored man in the United States, but ending by saying: "I was very much pleased with his reply; but, gentlemen, I cannot quote the President.    <p> After Dr. Moton finished his talk no opportunity was given to the officers to inform him of the conditions that had existed in France, and he did not seek any information relative to same from any of the officers after the conference ended, 

Dr. Moton then returned to Paris and met Colonel House, General Pershing and others. Colonel House told the writer that he urged Dr. Moton to remain in Paris and that if he would, Colonel House would give him an opportunity to appear in person before the Peace Conference to speak for the black world. Dr. Moton refused to stay, but promised to return. He then went to England and secured an audience with Lloyd George, Prime Minister of England. The destiny of the black race today is in the hands of England and the destiny of England is in the hands of Lloyd George. Yet, Dr. Moton did not keep his appointment; but rushed to catch his boat in order to be present at the Tuskegee Conference. He sailed, with Thomas Jesse Jones still watching him, and did not return to Paris or to the Pan-African Congress, which he said he favored and promised to support. 

No one questions the personal integrity of Robert Russa Moton or his kindly disposition, but no one, friend or foe, can look these facts in the face and not feel bitter disappointment.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Black Man in the Revolution of 1914-1918 (1919)](/Volumes/17/05/the_black_man_in_the_revolution_of_1914_1918.html)
* [The Negro Soldier (1919)](/Volumes/19/02/negro_soldier.html)
* [Inter-Racial Comity (1922)](/Volumes/22/01/inter-racial_comity.html)
* [A Momentous Proposal (1918)](/Volumes/16/05/momentous_proposal.html)
* [Muddle (1916)](/Volumes/13/02/muddle.html)

<!-- Similar articles end here -->