
---
title: 'To Mr. Emmett Scott'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1919
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 18
  issue: 1
  page: 10
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The Negro world and you will bear us witness that The Crisis and its Editor has given you loyal and unselfish co-operation, even at the cost of suspicion and criticism. We have done this, **first**, because the war demanded, and had a right to demand, an unswerving loyalty and unity on the part of the Nation and its constituent groups; and, **secondly**, because we believed that you were doing all that was possible under very difficult circumstances. A visit to Europe has, however, revealed to the Editor a state of affairs in regard to Negro troops which is simply astounding! Some of these facts we are publishing this month and others we shall reveal later. Meantime, we are withholding judgment in your case and simply asking you publicly three questions:

1. *Did you know the treatment which black troops were receiving in France?*
2. *If you did **not** know, why did you not find out?*
3. *If you **did** know, what did you do about it?*

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Allies (1911)](/Volumes/02/03/allies.html)
* [Officers (1917)](/Volumes/14/02/officers.html)
* [The Negro Soldier (1919)](/Volumes/19/02/negro_soldier.html)
* [Baker (1917)](/Volumes/15/02/baker.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)

<!-- Similar articles end here -->