
---
title: 'Frank'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 4
  page: 177
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The Frank case only offers illustration of the truth that in the South
all things may be brought about by an appeal to prejudice. This case
differs from similar cases principally in that the victim was a Jew
instead of a Negro and that a governor had courage enough at the last to
resist the popular clamor for his blood and base his decision on the
evidence in the case. The case also illustrates strikingly the
inadequacy of our legal machinery in solving questions of justice. Frank
escaped a legal lynching by the narrowest possible margin. His sentence
was commuted by Governor Slaton only a few hours before the time
appointed for his death. His appeal had been carried to the Supreme
Court of the United States. The majority of the body like that of the
State Supreme Court based its adverse decision entirely on points of
law. It practically said that Frank had had a fair trial in law, if not
in fact.

It is also difficult, it seems, for Boards of Pardon and Governors to
deal with an "atmosphere"---say such an atmosphere as that of Atlanta,
during the hours in which Frank's life hung in the balance. Perhaps that
is the real reason for the logical decision that a man of whose guilt
there is too grave a doubt to hang him, may still be found guilty with
enough certainty to spend his life in a Georgia convict camp. At all
events it is very like the law.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Supreme Court (1914)](/Volumes/09/02/supreme_court.html)
* [The Sweet Trial (1926)](/Volumes/31/03/sweet_trial.html)
* [Brandeis (1916)](/Volumes/11/05/brandeis.html)
* [A Moral Void (1917)](/Volumes/14/01/moral_void.html)
* [Justice (1917)](/Volumes/14/03/justice.html)

<!-- Similar articles end here -->