
---
title: 'The Negro and Labor'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1922
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 25
  issue: 6
  page: 248-249
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The usual American attitude toward Negroes in industrial countries like this is two-fold. On the one hand, the white laboring man excludes the Negro from work just as far as possible, particularly in the skilled trades; this is because, as he says, the Negro will work for lower wages and does not deserve the consideration of white labor. The employer, on the other hand, will employ Negroes when he can get them more cheaply than white men, but he considers them less efficient and their presence raises problems. They are, nevertheless, always a possible substitute when white labor becomes too exorbitant in its demands. 

Neither party is apt to consider the point of view of the colored man. He needs work and being usually excluded from the union, gets his chance to labor by underbidding the white laborer, and is compelled often to regard the man who hires "scab" labor as his benefactor. On the other hand, being compelled to live somewhere, being poor and ignorant, he brings to such employers and their friends problems in housing and other social matters. 

To most people these problems are a sort of perpetual American condition and show no particular change. On the contrary, this problem of Negro labor is part and parcel of the whole world problem of industry,---before, during and after the war. When there came to Europe four comparatively new crops: sugar, rice, tobacco, and later cotton, they transformed the industry and commerce of the modern world. Before that local industry had supplied the wants of the poor, but commerce was primarily to satisfy the desires and whims of the rich. It had, therefore, during the Middle Ages many of the characteristics of gambling. 

When, however, there came from overseas great crops which ministered to the wants of the mass of men, then commerce became more stabilized, the demand was steadier and the amount of goods handled was much larger; so commerce expanded tremendously. Then, too, the discovery of America gave the laboring class, for the first time in modern days, free, rich land. All that was needed was labor, and labor was procured by seizing white men in Europe and black men in Africa. There was in the 15th Century no great difference between the best civilization of Africa and the best civilization of Europe; but while Africa had to protect herself against barbarians, Europe was protected by natural physical barriers, so that in Africa the slave trade came to be a defense against barbarians and therefore expanded, while in Europe certain classes of laborers began to gain political power. 

There arose then in Europe the modern labor movement, and when this labor movement struck America, it found African slavery established here. At first it endured slavery because it was the slavery of an alien race; then it began to conceive that these black aliens might become laborers and free citizens, like the whites. This movement, which culminated after the Negroes had helped free America from England, was finally nearly halted by the increase of the new cotton crop, which made slave labor more valuable than ever. 

However, by the middle of the 19th Century the white laborers realized that black slavery was encroaching upon their free land and must be confined to certain limits, while the white slave owners knew that they must have more and more free land or slavery would not pay. The results were the Civil War and the legal emancipation of Negroes. 

This brings us to the modern world. The situation is that the mass of European and American white laborers have gained political power and are beginning to know how to use it. They are, therefore, demanding a larger share of the profits of industry; but, on the other hand, the controllers of industry and commerce have found that by investing in tropical and semi-tropical lands, they have a new chance to get cheap labor and valuable raw material of the sort which is increasingly in demand in modern industry. They have induced the laboring class to vote large appropriations for armies and navies. With this they seized control of Africa, Asia and the islands of the sea. 

You would think that there would have come, for this reason, revolt on the part of the yellow, brown and black laborers, and particularly of those black laborers in the United States who are legally free but still largely disfranchised both in politics and by the labor movement. Such revolt was indeed foreshadowed, but before this came the World War, which was caused by the jealousy of the nations who sought to dominate the darker world and who fell out in the division of the spoils. They fought a terrible war with each other for four years, and the result is that since the war the darker nations are revolting. In China, Japan and India, in Egypt and South and West Africa, in the West Indies and in America, there is a growing determination on the part of colored laborers that they are not going to remain the victims of modern industrial development. The greatest post-war problem is whether white laborers are going to recognize the demand of these dark laborers for equal consideration, or whether white capitalists and employers are going to continue to play off black and white labor against each other and thus seek to exploit and develop Asia and Africa, simply for the benefit of the privileged classes of the white world.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)
* [To the American Federation of Labor (1924)](/Volumes/28/04/american_federation_of_labor.html)
* [Our Economic Peril (1930)](/Volumes/37/03/our_economic_peril.html)
* [Eugene Debs (1926)](/Volumes/33/02/debs.html)
* [Organized Labor (1912)](/Volumes/04/03/organized_labor.html)

<!-- Similar articles end here -->