
---
title: 'Lusitania'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 2
  page: 81
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The last horror of a horrible war is come! It puts a period to what we
have already said: European civilization has failed. Its failure did not
come with this war but with this war it has been made manifest. Whatever
of brutality and inhumanity, of murder, lust and theft has happened
since last summer is but counterpart of the same sort of happenings
hidden in the wilderness and done against dark and helpless people by
white harbingers of human culture. But when Negroes were enslaved, or
the natives of Congo raped and mutilated, or the Indians of the Amazon
robbed, or the natives of the South Seas murdered, or 2,732 American
citizens lynched---when all this happened in the past and men knew it
was happening and women fatted and plumed themselves on the ill-gotten
gains, and London and Berlin and Paris and New York flamed with orgies
of extravagance which the theft of worlds made possible, when all this
happened, we civilized folk turned deaf ears. We explained that these
"lesser breeds without the law" were given to exaggeration and had to be
treated this way. They could not understand civilization but as for the
White World, there humanity and Christianity and loving kindness
reigned. This was a lie and we know it was a lie. The Great War is the
lie unveiled. This world is a miserable pretender toward things which it
might accomplish if it would be humble and gentle and poor and honest.
It is a great privilege in the midst of this frightful catastrophe to
belong to a race that can stand before Heaven with clean hands and say:
we have not oppressed, we have been oppressed; we are not thieves, we
are victims; we are not murderers, we are lynched!

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Lynching (1914)](/Volumes/07/05/lynching.html)
* [Preparedness (1915)](/Volumes/11/05/preparedness.html)
* [Awake America (1917)](/Volumes/14/05/awake_america.html)
* [Triumph (1911)](/Volumes/02/05/triumph.html)
* [Crime (1920)](/Volumes/19/04/crime.html)

<!-- Similar articles end here -->