
---
title: 'Christmas Gift'
author: Du Bois, W.E.B.
date: Jun. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 2
  page: 68
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The November elections come as a sort of Christmas gift to black folk. First, the Digges amendment to disfranchise colored people has been defeated in Maryland by a decisive majority of 20,551 votes. This is the third time that the Democratic machine has attempted to get rid of the colored vote. Secondly, the Democratic Legislature that neglected to amend and reconsider the colored regiment bill in New York has been sent home; but Cuvillier, the Democrat who introduced the bill, has been retained in his seat by the black voters of Harlem. It may easily be granted that Cuvillier is no ideal statesman, but is it not significant that he was the only man in this or former legislatures willing to do his colored constituents' demand? May we not respectfully assure Governor Dix that he himself will need the black vote soon and that this vote "follows the regiment?" Third, the Socialists, the only party which openly recognizes Negro manhood, has been signally triumphant. Is it not time for black voters to carefully consider the claims of this party? Fourth, we call the attention of contented lovers of democratic government in this land to the fact that while 400,000 votes were cast for governor in the little State of Massachusetts, it took only 40,000 votes to elect the governor of Mississippi, the pioneer State of disfranchisement. How long will democracy stand in America with one white man in Mississippi casting the equivalent of ten votes?

Finally, there is every indication that the election of 1912 will be a close election. If Mr. Taft succeeds himself after his tariff record, his silence on lynching and his treatment of colored officials, it will be by a margin that will call for every black vote in the North. Will he get these votes? Maybe---perhaps.

