
---
title: 'The Cost of Education'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 2
  page: 69
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



A favorite argument in the South is that the white people "pay for" the education of colored children. For instance, an alderman in Lexington, Ky., argues this way, in answer to a complaint about poor colored schools:

The Negroes of Lexington hold $774,735 worth of property, on which the school tax is $4,415.99. The white people pay taxes on $22,000,000, on which the school tax is $77,000. The colored schools cost $24,971.35. "These," concludes the *Richmond Times-Despatch*, "are very striking figures and dispose of the complaint made by the Negro leaders."

Let us see. In the first place the alderman gracefully includes in the "white" property all the property of corporations and public-service companies, because their stockholders are mostly white. In addition to this, it credits to the white taxpayer all property rented to colored tenants. But who pays the taxes on rented property? To settle this point let us turn to the criticism of the New York City Budget Exhibit made by the Committee on Congestion of Population.

> The budget exhibit fails to show the fact that the assessed value of tenements and buildings used for dwelling purposes in New York is about $1,250,000,000, and that the taxes on these buildings, at the average tax rate of $1.75, amount to $21,875,000 this year. New York is the great 'tenant' city.    
> &nbsp;
> Nor is the fact shown that these taxes on buildings are paid by the tenants, and that a good tenement apartment unit of four rooms is worth at least $1,250, and that taxes on this at a rate of $1.75 per $100, full value, amount to $21.87, or more than a month's rent. Approximately this amount is paid in taxes by the poorest of the poor, the sick and consumptives, and those families trying to exist on from $100 to $300 less than the recognized standard of living.

What is true in New York is mere than true in Lexington, Ky. Indeed, throughout the South, in most cities outside of Texas, the Negro in direct and indirect taxation is not only paying for his own wretched schooling accommodations, but is also contributing to the schools of the rich whites and then double-taxing himself by contributions to decent colored private schools.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Negro Education (1918)](/Volumes/15/04/negro_education.html)
* [Education (1930)](/Volumes/37/02/education.html)
* [Education (1911)](/Volumes/01/04/education.html)
* [Reconstruction (1919)](/Volumes/18/03/reconstruction.html)
* [Segregation (1910)](/Volumes/01/01/Segregation.html)

<!-- Similar articles end here -->