
---
title: 'The Sin Against the Holy Ghost'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 2
  page: 68-69
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



"He doesn't really believe what he says---he wants the same things that you want, but you see he has to talk this way." 

"Tillman? Oh, Tillman is a good friend of Negroes---his anti-Negro talk is just for political effect." And so forth. The young man then sits back and eyes us pleasantly. He considers that what he says is explanation and excuse. Is it not perfectly clear that men are often "in a position" where they must say what they do not for a moment believe? Well, does not this fact explain and excuse their actions and utterances?

It does not. Such action is the one unforgiven and unforgivable sin. It is the sin against the Holy Ghost for which neither the world nor the makers of the world ever forgive a human soul, and (what is far more important) for which in the end a man never forgives himself.

What is this strange, lightly tossed doctrine which young black men and young white men are to-day so easily handling? Done into plain English it is this:	Whenever a man considers
that it is to his advantage to deceive the public he is at liberty to do so. Whenever a lie serves a gentleman's purpose better than the truth, he may lie. And if at any time thereafter he is accused of deception or charged with lying it is a good and sufficient answer for him to allege that his interests required a falsehood, or his position in the world demanded deception, or that his bread and butter called for a lie.

This is a counsel of destruction. It is a doctrine of death. It will, if persisted in, damn any individual and it
will utterly destroy any race. The individual may escape visible punishment, for life is short. But the immortal race cannot escape.

The Negro race in America is today being offered every inducement to lie and deceive. It is asked to lie about its desires and ambitions. It is asked to lie about its own human feelings. It is asked to give lying testimony as to the goodness of its neighbors. If it will consent to lie, there are money, position and applause for the chief liars and winks and promises for the fools that follow. Yet the end is death. The end is first bewilderment among honest people. My God! they say, if a people who have had twenty-five hundred of their fellows lynched without trial in twenty-five years; who have seen nine-tenths of their voters disfranchised; who cannot travel, sit or walk without danger of public insult---if such a people do not believe in "complaint" or "agitation" and merely are ambitious to be "useful" to their neighbors, why should we strive to help them? No sooner have they reached this conclusion than some obsequious colored gentleman explains in lowered tones: "We are not really satisfied, we are just lying to appease our enemies and keep our jobs." What is the result? Contempt and suspicion. Contempt for a people who place their jobs above their souls, and well-grounded suspicion that the man who will lie under such circumstances will lie under others.

Thus the result of the sin against the Holy Ghost is suspicion and contempt from others and lack of faith in one's self. What black man in America to-day who is preaching contentment to ten million slaves does not in his heart despise himself for doing it?

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Darrow (1928)](/Volumes/35/06/darrow.html)
* [The Truth (1912)](/Volumes/05/02/truth.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Heroes (1919)](/Volumes/19/01/heroes.html)
* [Jesus Christ in Georgia (1911)](/Volumes/03/02/jesus_christ.html)

<!-- Similar articles end here -->