---
title: Clothes
description: In a 1920 Crisis essay, W.E.B. Du Bois flips racist assumptions, arguing whites' fears about Black laundry reveal public-health harms and racial hypocrisy.
author:
- name:
    given: W.E.B.
    family: Du Bois
date: Feb. 1920
subjects:
- Public health and sanitation
- Racial prejudice and hypocrisy
- Laundry work — African Americans
- Domestic service and occupational health
- Race relations
people:
- W. E. B. Du Bois
places:
- Southern United States
organizations:
- The Crisis (magazine)
citation:
  type: article-journal
  container-title: The Crisis
  volume: 20
  issue: 4
  page: 166
google-scholar: true
format:
  html:
    toc: false
    appendix-cite-as: display

categories:
  - "The South"
  - "Labor & Economics"
---

It was in a Southern city and the white people were on the one and
favorite subject---the "Nig-ra." This time it was health, a safe and
absorbing subject. They were told of the horrible danger of having their
clothes washed in Negro cabins and of their consequent personal interest
in the Negroes' health.

There ensued that succession of little purrs and squeals which some
ladies consider evidence of the highest breeding.

But one Southern white woman rose and said calmly, "Yes, there is
danger, but there's more danger to the Negroes in your dirty clothes
than to you from the clean and sterilized washing which they return."

Then followed the eloquent silence that does not need words.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Africa for the Africans (1921)](/Volumes/23/04/africa_for_the_africans.html)
* [From a Traveller (1932)](/Volumes/39/12/from_a_traveler.html)
* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [Crime (1921)](/Volumes/22/02/crime.html)

<!-- Similar articles end here -->