
---
title: 'Agility'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 3
  page: 133
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Mrs. O.H.P. Belmont is coming in for considerable praise on account of her facile answer to a disturbing question while she was campaigning for suffrage in the South. At Chattanooga she was asked if her movement meant the giving of votes to colored women. Mrs. Belmont was most adroit. The expectant hush fell on the audience and instead of standing up like a frank woman and saying "Yes," Mrs. Belmont quibbled and twisted after the most approved southern fashion. "We want," she said, "the same voting privileges for colored women as are given colored men." And there the adroitness stands naked and unashamed.

It will undoubtedly attract the support of those southerners who want aristocratic white women to vote and to vote their narrow-headed prejudices into a new southern oligarchy. But there are people whom such dishonesty will not attract. It will not, for instance, attract the tens of thousands of black voters who are going to cast their ballots in certain states this fall where the suffrage question will come up. They will not be satisfied in having their black sisters of the South disfranchised like their black brothers and they will hold in frank and logical suspicion a party that is working for that kind of democracy.

Moreover, there are thousands of white people in this country whom this kind of quibbling disgusts. Everybody knows what desperate effort has been made by certain elements among the suffragists to dodge the Negro problem, to try and work for democracy for white people while being dumb before slavery for blacks. This element has been squelched several times in the counsels of the party but it continually bobs up. Let the suffrage movement beware! In the turnings of time Mrs. Belmont may not be as adroit as she at present con­ceives herself.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Woman Voter (1921)](/Volumes/21/05/woman_voter.html)
* [Votes for Women (1918)](/Volumes/15/01/votes_for_women.html)
* [Suffering Suffragettes (1912)](/Volumes/04/02/suffering_suffragettes.html)
* [Suffrage and Women (1915)](/Volumes/09/04/suffrage_women.html)
* [Woman's Suffrage (1913)](/Volumes/06/01/womans_suffrage.html)

<!-- Similar articles end here -->