
---
title: 'The Alleged Failure of Democracy'
author: Du Bois, W.E.B.
date: Jan. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 3
  page: 131-132
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The following editorial on "The Alleged Failure of Democracy" was written by the editor of The Crisis and printed in the Boston *Sunday Globe*:

We are becoming more democratic, but not easily, not without struggle and misgivings. Our progress seems even slower than it is because we have really experienced so little real democracy in the past. We founded a republic in 1787 which was in reality an aristocracy of the most pronounced tendencies. The democracy ushered in by Andrew Jackson was the beginning of that system of government by deception where "the people" are congratulated on the possession of all powers of government, while the real rulers hide in the background so effectually that their very existence often is not sensed. Since the Civil War we have driven these rulers into the open, and frankly acknowledged, weighed and studied their power.

From this knowledge we have started well on the way toward dethroning the ward heeler and the petty boss, and are hammering at the strongholds of the greater bosses. Our real difficulty comes in settling in our own minds a proper, permanent repository for the power thus regained. In other words, we are facing to-day still the elementary problem of democracy: How far do we dare trust the mass of the people, not with sham power and sounding phrases, but with real power?

Those on the one hand who call for commission government, and those on the other hand who ask for the initiative and the recall represent the two different answers to this problem. True it is, that there are those far-sighted ones who combine both demands. For the most part, however, we may distinguish those who would deposit the power won from the bosses with one or more strong men for safekeeping; and those who would try and place that power just as far as possible in the hands of the masses.

There can be no doubt that the former type of thinkers gains great strength and support from the supposed failure of certain democratic experiments in the past, particularly in the case of the foreign vote in our cities and of the Negro vote during reconstruction times. The alleged failure of democracy in reconstruction times especially has been used in the past and is still used as a tremendous argument against democracy in the nation and in the world. The argument runs something like this: "Ignorant freedmen failed as voters. This proves that democratic government cannot rest on ignorance." But how much learning is necessary to a share in the government? Immediately our ideas enlarge: "Government is for the educated and the expert. It is a reward, not a right. Democracy is an evolution that may come to fruition in a thousand years. To-day we need the strength and efficiency found only in a few." In the face of such argument it is high time that the people of this country asked themselves seriously two questions: What is democracy? Did democracy fail in reconstruction?

Democracy is not a gift of power, but a reservoir of knowledge. Only the soul that suffers knows its suffering. Only the one who needs knows what need means. Ignorance may vitiate the expression of needs and vice may deceive, but it remains true that despotism and aristocracy have displayed far more ignorance of the real needs of the people than the most ignorant of democracies. The people alone are the sources of that real knowledge which enables a State to be ruled for the best good of its inhabitants. And only by putting power in the hands of each inhabitant can we hope to approximate in the ultimate use of that power the greatest good to the greatest number.

Seldom in the history of the world has this great truth been so well proved as in the experience of the American Negro. Without civil or political rights, and admitting every claim of benevolence on the part of his master, he became a slave, whose very existence threatened the industrial and spiritual life of the nation. Emancipated and given a vote, despite his ignorance and inexperience, he gave the South three gifts, so valuable that no one to-day would dream of giving them up:

1. The public-school system.
2. The enfranchisement of the poor whites.
3. The beginning of modern social legislation in land reform, eleemosynary institutions and social uplift.

The Negro was not disfranchised because he had failed in democratic government, but because there was every reason to believe that he would succeed, and it was his success which the beaten masters feared more than his failure.

Having disfranchised him with this fiction of failure, that same fiction is being used to-day to discredit democracy throughout the nation, to stop the just enfranchisement of women, to curtail the power of the foreign born and their descendants, and to support the argument in the twentieth century that the democratic ideals of the nineteenth century were in vain.

To the help of this program comes the wholesale exploitation and despising of colored races and the suicidal career of universal conquest to which Europe stands committed.

But the march of real democracy goes on. Slowly but surely the masses of men will become the great depositors of the bulk of both political and economical power, for their own good. Only democratic government can be both enlightened and selfish, both bond and free.

