
---
title: 'Brazil'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 6
  page: 286-287
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


As a magnificent essay in valiant timidity we recommend Mr. Theodore Roosevelt's "Brazil and the Negro" in the <i>Outlook</i>. The story which he has to tell is simple: There are in Brazil 8,300,000 Negroes and mulattoes; 3,700,000 Indian and mixed Indian-whites and 8,000,000 persons of European descent. All these elements are fusing into one light mulatto race. 

These are the simple facts. Mr. Roosevelt has hitherto rather ostentatiously avoided them. He visited Rio Janeiro, with a Negroid population in the hundred thousands, and almost overlooked them; he visited Bahia, if we mistake not, which has more Negroes than any city in the world, and quite forgot them. 

At last, however, Mr. Roosevelt coyly approaches his subject. The editors warn away the frivolous with these protesting italics: "It may be noted that in this article Mr. Roosevelt is not attempting to justify or condemn the Brazilian attitude toward the Negro as contrasted with that of the United States, but simply to set forth clearly what the Brazilian attitude is in fact." 

Mr. Roosevelt then, in characteristic fashion, states three facts and two falsehoods. 

The facts are: 

1.	Brazil is absorbing the Negro race. 
2. There is no color bar to advancement. 
3. There is no social bar to advancement, but the mass of full-blooded Negroes are still in the lower social class. 

Then come the falsehoods: 
1. The best men in the United States believe "in treating each man of whatever color absolutely on his worth as a man, allowing him full opportunity to achieve the success warranted by his ability and integrity, and giving to him the full measure of respect to which that success entitles him." This is not so and Mr. Roosevelt knows it is not so. The best men in the United States believe that their "civilization" can only be maintained by compelling all persons of Negro descent to occupy an inferior place. The exceptions to this belief are negligible. 
2. That the Brazilians regard the Negro element in their blood as "a slight weakening." What do Brazilians say as to this "slight weakening"? We quote from Dr. Jean Baptiste de Lacerda, director of the National Museum of Rio Janeiro: 

> The <i>metis</i> of Brazil have given birth down to our own time to poets of no mean inspiration, painters, sculptors, distinguished musicians, magistrates, lawyers, eloquent orators, remarkable writers, medical men and engineers, who have been unrivaled in the technical skill and professional ability. * * *      <p> The co-operation of the <i>metis</i>  in the advance of Brazil is notorious and far from inconsiderable. They played the chief part during many years in Brazil in the campaign for the abolition of slavery. I could quote celebrated names of more than one of these <i>metis</i>  who put themselves at the head of the literary movement. They fought with firmness and intrepidity in the press and on the platform. They faced with courage the greatest perils to which they were exposed in their struggle against the powerful slave owners, who had the protection of a conservative government. They gave evidence of sentiments of patriotism, self-denial and appreciation during the long campaign in Paraguay, fighting heroically at the boarding of the ships in the canal battle of Riachuelo and in the attacks of the Brazilian army, on numerous occasions in the course of this long South American war. It was owing to their support that the republic was erected on the ruins of the empire.

And what of all this? Is it not a plea for intermarriage of whites and blacks in the United States? It is not. It is a plea for truth. It is a denial that lying will settle any human problem. Most white people in the United States prefer to marry white people. That is perfectly proper and defensible. Most colored people prefer to marry colored people. This is perfectly logical and commendable. These facts need no defense and need no proof. They are the easily understandable desire of both races. 

But a vast number of people are not satisfied with such bare facts. They want to bolster them up with scientific lies and social insult. They want to scare and beat people into doing precisely what people would do without bogies and force, and the result is that they not only accomplish what they wish, but they also accomplish poverty, crime, prostitution, ignorance, lynching, mob violence and the ruin of democratic government for the unfortunate victims of their lies. All this is clear, but to expect Theodore Roosevelt to say it plainly without twistings and equivocation is to expect the millennium. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)
* [The Rise of the West Indian (1920)](/Volumes/20/05/rise_of_the_west_indian.html)
* [Our Book Shelf (1926)](/Volumes/31/03/book_shelf.html)
* [Africa for the Africans (1921)](/Volumes/23/04/africa_for_the_africans.html)
* [Light (1912)](/Volumes/03/04/light.html)

<!-- Similar articles end here -->