
---
title: 'Veiled Insults'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 6
  page: 287-288
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



We have spoken before of the custom in the United States of refusing to capitalize the word "Negro."

Before 1850 the use of the capital letter was practically universal, but with the determined onslaught upon the Negro-American in the decade previous to the war, the present insulting custom was fixed. Note for a moment the quite unconscious result:

The Kansas City *Journal* publishes an admirable little lay sermon on a certain much heralded experiment in racial culture. We abstract three paragraphs:

> The imagination readily responds to the effort to bring up representatives of half a dozen or more races---American, Chinese, Indian, negro, Japanese, Jew, Russian, etc.—in an environment which shall be uniform, which shall be directed to the task of permitting human nature, rather than any of its racial subdivisions, to take its course, subject to the modifications of a universal environment. ...

> Will the little American, the little Jew, the little Italian, the little Chinese, the little negro and all the other little ones grow up to be men and women who conform to a uniform standard of intellectual and spiritual measurement, forgetting in the new knowledge of proper training all the heritage of their racial origin and all the evils of an undesirable environment? ...

> In still other words, is not one good citizen just as good as any other good citizen, regardless of whether he is an American, a Jew, an Italian, a negro, a Chinese, a Japanese or what not? ...

In substance nothing could be better than these statements; but can anyone read them and for a moment think of the Negro race as equal to other races? Yet some of the best friends of colored people persist in this species of insult.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Negro (1914)](/Volumes/09/02/negro.html)
* [That Capital ''N'' (1916)](/Volumes/11/04/that_capital_n.html)
* [The Capital N (1930)](/Volumes/37/05/capital_n.html)
* [Prejudice (1911)](/Volumes/02/01/prejudice.html)
* [The Name Negro (1928)](/Volumes/35/03/name_negro.html)

<!-- Similar articles end here -->