
---
title: 'Consolation'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 2
  page: 169-173
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Colored folk can always get a dubious sort of consolation in knowing that they have not always had a monopoly of the attentions of the discourteous and the cruel. At a recent dinner given to the oldest woman doctor in the United States, Dr. Anna Manning Comfort told of the indignities which she suffered at Bellevue Hospital in 1865 for the unforgivable crime of being female: 

> We had to go to Bellevue Hospital for our practical work, and the indignities we were made to suffer are beyond belief. There were five hundred young men students taking post-graduate courses, and we were jeered at and catcalled, and the 'old war horses,' the doctors, joined the younger men.   <p> We were considered aggressive. They said women did not have the same brains as men and were not trustworthy. All the work at the hospital was made as repulsively unpleasant for us as possible. There were originally six in the class, but all but two were unable to put up with the treatment to which we were subjected and dropped out. I trembled whenever I went to the hospital, and I said once that I could not bear it. Finally the women went to the authorities, who said that if we were not respectfully treated they would take the charter from the hospital.    <p> As a physician there was nothing that I could do that satisfied people. If I wore square-toed shoes and swung my arms they said I was mannish, and if I carried a parasol and wore a ribbon in my hair they said I was too feminine. If I smiled they said I had too much levity, and if I sighed they said I had no sand.<p> They tore down my sign when I began to practice; the drug stores did not like to fill my prescriptions, and the older doctors would not consult with me. But that little band of women made it possible for the other women who have come later into the field to do their work. When my first patients came and saw me they said I was too young, and they asked in horrified tones if I had studied dissecting just like the men. They were shocked at that, but they were more shocked when my bills were sent in to find that I charged as much as a man. 

Remember this is the story of the treatment of a white woman by chivalrous American white men, the same men who tremble with indignation lest a black man look at one of these beautiful creatures. 

