
---
title: 'Deception'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jun. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 2
  page: 81-82
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



One of the unforgivable things about the southern white press is the
way in which it deliberately deceives its readers as to the attitude of civilized communities toward Negroes. Even
the Columbia, S. C., *State* stoops to this petty deception. The *State*
records the facts that hoodlums chased a Negro in Boston, and argues
that the lynching spirit so far as Negroes are concerned is just as bad
in Boston as in South Carolina, only that there are more policemen in
Boston, and southern men are more "sensitive." This is nonsense. The
fact of the matter is that Boston is more law-abiding, and that an
accused black man there even in the midst of a mob can appeal to law-
abiding bystanders and receive protection. In South Carolina the well-
known innocence of a black man could only in exceptional cases appeal to
the white bystander. The Atlanta, Ga. *Constitution* assumes that the
appointment of Miss Bosfield to a position among white clerks in a
hospital in Massachusetts was something exceptional ard that they revolted against it just as Georgia would have. This is untrue and the
*Constitution* probably knows that it is. There are dozens of colored
clerks, male and female, working with their white fellows in all parts
of Massachusetts. Just as long as the South receives from its daily
press the silly impression that other parts of the world are as crazy
and unreasonable in their racial hatreds as are the southern United
States, just so long there will be no appeal to reason in those half
civilized districts.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Anarchism (1912)](/Volumes/04/04/anarchism.html)
* [Scottsboro (1933)](/Volumes/40/05/scottsboro.html)
* [A Moral Void (1917)](/Volumes/14/01/moral_void.html)
* [Prejudice (1911)](/Volumes/02/01/prejudice.html)
* [Lynchings and Mobs (1921)](/Volumes/22/04/lynchings.html)

<!-- Similar articles end here -->