
---
title: 'Interracial Love in Texas'
author: Du Bois, W.E.B.
date: Feb. 1930
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 37
  issue: 2
  page: 64-65
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The Houston, Texas *Post-Dispatch* says in a recent editorial:

> In announcing the annual convention of the Texas Commission on Inter-racial Co-operation in Dallas for November 1-2, Dr. R. M. Woods, instructor in sociology in Sam Houston State Teachers' college at Huntsville, director of the commission in this State, makes it clear that attainment of social equality between the races is not the aim of the organization. Friendliness between the white and colored people is promoted, but there is no thought of bringing them together on an equal social plane, he states. <p> With this aim of the commission thoroughly understood, the commission should attract the interest and support of the white people generally and of the more intelligent and better element of the colored people throughout the State.

All of which is interesting nonsense. How are these folks going to meet together without social equality? Are they going to refuse to speak to each other? Can they shake hands? Would a cup of tea and a biscuit overthrow the universe? Is there any chance for sympathetic friendship? May not some of them fall in love and get married? And if any of these things, where is the line going to be drawn?

What is the use of people talking like idiots just because they are trying to solve a human problem? The inter-racial movement in Texas is going to follow the same lines as human contacts the world over. If the movement is successful, white people and black people are going to get acquainted with each other. If this acquaintanceship and understanding increases, so will their social intermingling increase. And nothing that the Editor of the Houston *Post-Dispatch* can do it will stop it, or ought to.

