
---
title: 'Smuts'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1930
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 37
  issue: 2
  page: 63
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




Jan Smuts, former Prime Minister of the Union of South Africa, has been traveling in England and is now in the United States. He is a man whom many regard as a great international statesman, but for us American Negroes, he has one intolerable defect which we more clearly than other peoples can see will forever keep him from true greatness.

He was born and trained into the ingrained prejudice of the white South African against black folk. His whole conception of the world is that of a world not necessarily composed entirely of white people, but certainly organized, directed and established for white people. When he says that he wants white civilization to triumph in Africa, he does not mean simply that he wants civilization to triumph, it must be civilization owned by white people. The black people must share it only insofar as they cater to white peoples wants and even whims. Smuts is not so provincial as Hertzog. He does not want to face the conscience of the world with actual laws to keep Negroes from being artisans or from any real economic or political rights, or from any social status. But he wants to accomplish exactly the same thing that Hertzog wants to accomplish: that is, to put the black man back "in his place" and to keep him there. Beyond this, none of the liberalism of Jan Smuts has ever been able to stir a single step.

Is this judgment unfair? Does it seem harsh when compared with what Mr. Smuts says in America? If it does, remember that in the Union of South Africa, nine-tenths of the natives are illiterate because of lack of school facilities; that taxation without representation is the rule in their political life, and that even in the one province where they have the right to vote, they can not vote for a Negro representative; social ostracism extends to excluding them from white churches, from getting mail at the same Post Office window, and often from walking on the sidewalks. They must carry passes when they travel; they ride in Jim Crow cars; they are kept by law from pursuing most of the profitable lines of work; they can not buy land, save in a few restricted areas; and against all this zenith of race discrimination, Jan Smuts, as Prime Minister and leading statesman, has raised no effective voice and merely calls them patient asses.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Patient Asses (1930)](/Volumes/37/03/patient_asses.html)
* [To The World (1921)](/Volumes/23/01/to_the_world.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)
* [The Drive (1922)](/Volumes/22/01/drive.html)

<!-- Similar articles end here -->