
---
title: 'That Capital ''N'''
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1930
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 37
  issue: 2
  page: 63
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The Raleigh, North Carolina *Times* tells Antonio M. Roper, a student at St. Augustine's College, that it will not capitalize "Negro" because it does not capitalize "white." This logic is beneath contempt. The word corresponding to "white" is "black" or "colored," while the words corresponding to Negro are Caucasian, Mongolian, Nordic, Indian, Jewish, European, African, American, and similar words referring to great groups of people. This, of course, will not influence the Editor of the Raleigh *Times*. He spells it "negro," because that is the way he thinks. 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Negro (1914)](/Volumes/09/02/negro.html)
* [That Capital ''N'' (1916)](/Volumes/11/04/that_capital_n.html)
* [The Capital N (1930)](/Volumes/37/05/capital_n.html)
* [The Name Negro (1928)](/Volumes/35/03/name_negro.html)
* [Veiled Insults (1914)](/Volumes/07/06/veiled_insults.html)

<!-- Similar articles end here -->