
---
title: 'Anti-Lynching Legislation'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1922
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 1
  page: 8-9
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


During the last five years the N.A.A.C.P. has carried on a campaign against lynching, conducted in accordance with the most approved methods of public­ity. This campaign has been financed by philanthropists North and South, and black and white, and by wide-spread popular subscription. We have never heard any serious criticism of our campaign save, naturally, from those who oppose any effort to defend and emancipate black folk.

Our accomplishment from all our effort may thus be summarized:

1. Investigated more than a score of lynchings and race riots
2. Kept an accurate record of lynchings
3. Published the only statistical study of lynchings ever compiled
4. Sent 4,462,899 copies of the <span class = "small-caps">Crisis</span> to every state in the Union and to every country on the globe
5. Sent out hundreds of news releases. During the year of 1920 alone 131 press stories were sent out from the National Office
6. Held more than 2,000 public meetings, attended by more than 3,000,000 people, at which speak­ ers acquainted the audiences with the facts about lynchings
7. Sent literature on lynching, with actual photographs of lynchings and burnings at the stake, all over the civilized world
8. Fought successfully three notable extradition cases when attempts were made to carry colored men accused of crimes from Northern States back to sections of the South where the men would probably have been lynched
9. Held in New York City in May, 1919, a great and successful conference against lynching. The call for this conference was signed by 120 of the leading citizens of the country, 20 of them from Southern States. The number included 5 governors, 4 ex-governors, members of Congress, judges of the higher courts, members of the President's cabinet, and other men and women prominent in the nation's affairs
10. Issued the "Address to the Nation"
11. Raised and expended since 1911 in the fight against lynching $33,928.56 this amount being spent for investigations, printing and publicity of all kinds, meetings and conferences
12. Secured the passage of a law in Kentucky providing for the punishment of any peace officer who allows a prisoner to be taken from him and lynched
13. Secured the introduction of anti-lynching bills in both houses of Congress. For the first time the House Committee on the Judiciary reported favorably on such a bill during the second ses­sion of the 66th Congress
14. Presented to committees of both the Senate and the House of Representatives of Congress, through its representatives, evidence and testimony showing the necessity of a Federal law against lynching
15.  Furnished lawyers to defend colored men in lynching cases; secured the acquittal, for example, of 12 of 13 colored men arrested in connection with the lynchings at Duluth, Minn., in June 1920, totally disproving the charge that criminal assault on a young girl had been com­mitted by any of the three men lynched; de­ fended since October, 1919, 12 men sentenced to death and 67 to prison terms, thus preventing a legal lynching in Phillips County, Ark.

In addition to these things we have freely given help and information to other organizations, and when the colored Republican campaign committee asked the aid of our legal department in drawing an anti-lynching bill, we freely and gladly gave it.

We are surprised and disappointed, therefore, to receive from Perry Howard an appeal for funds to finance a new organization to push an anti-lynching bill. This move is defensible only if the methods and aims of the N.A.A.C.P. in the anti-lynching campaign were failing. But this new organization is pushing practically the same bill by identical methods.

Is not this move, therefore, the same futile division of effort and clouding of issues which continually misleads and discourages the Negroes, and gives joy to the Bourbon South? Would not these gentlemen convince the public of their disinterested efforts if they supported established agencies and proven work rather than attempt­ ed to build on new lines and to risk all that has been gained without hope of doing more?

The strength of the N.A.A.C.P. has been its singleness of aim. We did not rescue Haiti in order to annex the $10,000 salary of the Haitian Minister; we are not fighting lynching in order to become Recorder of Deeds; and our promotion of business enterprise has no string on the Registry of the Treasury. This does not mean that we are unmindful of the right of competent black men to hold office,---indeed we strongly emphasize and maintain this right---but we in­sist that this is subordinate and un­ important beside our fight for freedom, and we refuse to have our most sacred right played with as pawns to official preferment.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Lynching (1914)](/Volumes/07/05/lynching.html)
* [Causes of Lynching (1931)](/Volumes/38/04/causes_of_lynching.html)
* [Lynchings (1932)](/Volumes/39/02/lynchings.html)
* [Lynching (1927)](/Volumes/33/04/lynching.html)
* [The Lynching Industry (1915)](/Volumes/09/04/lynching_industry.html)

<!-- Similar articles end here -->