
---
title: 'The Drive'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1922
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 1
  page: 8
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Again the pendulum has swung: it is no longer a question of educating the Negro to his just demands as an American citizen. He has ceased to be beguiled by the silly philosophy that a voteless, spineless suppliant who owns a three-story brick house is going to command anybody's respect.

But today comes the question of practical, efficient means of getting the rights which he has at last been persuaded he wants.

Into the field have jumped a hoard of scoundrels and bubble-blowers, ready to conquer Africa, join the Russian revolution, and vote in the Kingdom of God tomorrow. It is without doubt certain that Africa will some day belong to the Africans; that steamship lines and grocery stores, properly organized and run, are excellent civilizers; and that we are in desperate need today of organized industry and organized righteousness. But what are the practical steps to these things? By yelling? By pouring out invective and vituperation against all white folk? By collecting the pennies of the ignorant poor in shovelsful and refusing to account for them, save with bombast and lies?

Or is it reason and decency to unite on a program which says: the battle of Negro rights is to be fought right here in America; that here we must unite to fight lynching and "Jim-Crow" cars, to settle our status in the courts, to put our children in school and maintain our free ballot.

Far from being discouraged in the light, we are daily more and more triumphant. Yesterday 1,650 Negro women voted in New Orleans. Never since 1876 have so many Negroes voted in the South as in the last election. Our fight for right has the enemy on the run. He has had to retreat to mob violence, secret and silly mummery, clumsy and hypocritical promises. Twenty-five years more of the intelligent fighting that the N.A.A.C.P. has led will make the black man in the United States free and equal.

Our enemies know this. They are scared. They are hastening to lay down a barrage of suspicion and personal bickering. They are encouraging and advertising any and all crazy schemes, to cut and run from the hard and bloody battle here, to Africa and the South Seas. Africa needs her children, but she needs them triumphant, victorious, and not as poverty-
stricken and cowering refugees.

Are we going to be misled fools, or are we going to put a quarter of a million level-headed, determined and unwavering black men and women back of the N.A.A.C.P. to continue the battle so nobly and successfully be­ gun? Answer, black folk of America, this month!

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Violations of Property Rights (1911)](/Volumes/02/01/violations.html)
* [Votes (1919)](/Volumes/19/02/votes.html)
* [Smuts (1930)](/Volumes/37/02/smuts.html)
* [The Future of Africa (1919)](/Volumes/17/03/future-of-africa.html)
* [The Simple Way (1913)](/Volumes/07/01/simple_way.html)

<!-- Similar articles end here -->