
---
title: 'Inter-Racial Comity'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1922
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 1
  page: 6-7
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There are persons who assume that the N.A.A.C.P. and particularly <span class = "small-caps">The Crisis</span> are opposed to the Inter-racial Committees in the South and to any efforts of white Southerners to settle the problems of race. This is a singu­lar misapprehension. On the contrary, we count it as one of the great results of the N.A.A.C.P., that its persistent fight in the last ten years has aroused and even compelled the South to attempt its own internal reform. Can we not remember the day, but 20 years since, when conferences on the Negro were confined to white men because white Southerners would not sit with Negroes? That day is gone and gone forever, and the N.A.A.C.P. prepared its passports.

The Inter-racial movement sprang from the fight we have made. If it accomplishes anything, it will be because of our continued and persistent fighting. If it fails, it will show the need of redoubled effort on our part. If lulled by false hope and vague promises, we cease our vigilant effort, the Inter-racial movement would drop dead before the cry: "The Negroes are satisfied; why stir up trouble."

This has been the history of all such movements in the past. If the present movement succeeds (and God grant it may) it will be because the N.A.A.C.P. neither slumbers nor sleeps but keeps to its God-appointed task of making every black slave in the United States dissatisfied with his slavery, and every white slave-driver conscious of his guilt.

Meantime, may we not advise our Inter-racial friends,---do not fill your committees with "pussy footers" like Robert Moton or "white-folks' Nigger" like Isaac Fisher. Get more real black men who dare to look you in the eye and speak the truth and who refuse to fawn and lie. An ounce of truth outweighs a ton of impudence. Do not seek to mislead or lull the Negro with ancient platitudes and generalities. Let your "black mam­my" sleep and show your "best friendship" by deeds and not words. Do something. Do not dodge and duck. Face the fundamental problems: the Vote, the "Jim-Crow" car, Peonage and Mob-law.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Newest South (1913)](/Volumes/06/03/newest_south.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [The N.A.A.C.P. and Race Segregation (1934)](/Volumes/41/02/naacp_and_race_segregation.html)
* [The Macon Telegraph (1920)](/Volumes/19/03/macon_telegraph.html)
* [The Name Negro (1928)](/Volumes/35/03/name_negro.html)

<!-- Similar articles end here -->