
---
title: 'The Tuskegee Resolutions'
author: Du Bois, W.E.B.
date: Mar. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 13
  issue: 5
  page: 219
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



As to the resolutions of the Tuskegee conference touching the migration of Negro labor to the North the <span style="font-variant:small-caps;">Crisis</span> confesses itself to have been in a quandary for the simple reason that we did not know what the resolutions said. A telegram to Tuskegee has brought the full text just as we go to press.

The southern white papers assert editorially and in their news columns that the chief burden of the Tuskegee resolutions is advice to the Negro not to migrate from the South. From this advice, it goes without saying, that the <span style="font-variant:small-caps;">Crisis</span> absolutely dissents. On the other hand, certain spokesmen for Tuskegee assert that the resolutions simply deprecate any mass movement of Negro labor and call for better treatment on the part of the South.

As a matter of fact, the Tuskegee resolutions may be thus analyzed: out of fifteen inches of printed matter the following subjects are treated:

The Boll-Weevil and Floods, one inch; "Advice to remain in the South," five inches; "Diversified Farming," one and one-half inches; "A Plea to the South in Behalf of the Negro," two and one-half inches; "Lack of Enforcement of the Law," one-half inch; "Congratulating the South and Urging Co-operation of Races," three and one-half inches.

With the subject matter of the various resolutions we have no quarrel. In few cases do we dissent from the statements, taken by themselves; but we do solemnly believe that any system of Negro leadership that today devotes ten times as much space to the advantages of living in the South as it gives to lynching and lawlessness is inexcusably blind.

