
---
title: 'The Non-Partisan Conference'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1932
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 39
  issue: 2
  page: 58-59
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There was held in December in Washington a "Non-Partisan Negro Conference" called by Congressman Oscar De Priest. It brought together speakers of all sorts and kinds, and speeches good, bad and indifferent. The general spirit, however, seemed excellent and the independence of thought, knowledge of subjects discussed and general morale were commendable.

I was invited to discuss "The Economic Condition of the Negro." When I had finished, the Chairman of the Committee on Findings, Kelly Miller, asked me if I had prepared an "economic plank." I replied that I had not known I was expected to, but that I would gladly write one, even then, if I could have a stenographer. No stenographer was forthcoming, so I returned to New York and early next morning dispatched a proposed plank by air mail, offering at the same time by telegram to send the plank by wire if necessary. I had no reply.

Below in parallel columns are my proposed plank and the planks actually adopted.

## **The Planks Adopted**

>We warn members of the race against the specious pleas of Communism, whose basic principles are vitally at variance with our received ideals of free institutions, While no underprivileged minority may be expected te be incurious to the experiments of aggrieved groups in other parts of the world, struggling to throw off the shackles of oppression, yet the American Negro must rely for relief upon the American ideal. In the modified language of Frederick Douglas, "The Constitution is the ship, all else is the sea."  <p> A. In this day of deep depression and unemployment, of which the Negro sustains the heaviest brunt, we urge Our people everywhere to be thrifty, frugal and industrious, reliable and dutiful in the performance of any task which their hands may find to do.   <p> B. We urge the white labor world, feeling the effect of the common depression, to lay aside their customary intolerance against their Negro laborers and fellow-workers, and to evince a willingness to share with him the limited opportunities, rather than strive to exclude him on the ungenerous plea, "les there be not enough for you and us."   <p>C. We urge the capitalists and masters of industry to apportion fairly among black and white workers alike, both work and pay in this dark day of industrial uncertainty.

## **My Proposed Planks**

> Voted that the political power of the Negro in the future should be used mainly for his economic emancipation as follows:    
> &nbsp;    
A. To secure a more equitable distribution of the national income among those, white and black, who do the world's work and make the world's wealth.     
> &nbsp;      
B.  To replace privilege and monopoly in the ownership and direction of capital by state control and greater democratic direction of industry.    
> &nbsp;    
C. To encourage, especially among our own people, such co-operative organization of consumers as will offset and balance the present power of producers and help secure between production and consumption a new plan of organized industry for the benefit directly of the working classes and indirectly of all men.     <p> For the intelligent carrying out of this industrial program, we earnestly recommend that American Negroes give attention and thought to all movements toward social reform: to Communists and Socialists, to laborers and capitalists, and to all those who are sincerely seeking to remedy the present depression and to break down the economic color line.

In most other respects, the Findings, although inexcusably prolix, were admirable in content: Non-Partisan voting, Southern disfranchisement, the Negro in the Civil Service, Lynching, and National Aid to Education were well and sanely treated.

But the economic plank should have been the most important of all, since it treated a question paramount in pressing interest and logical weight to all others. It should have been the key plank of the conference, adopted after thought, research and long discussion. And it should have expressed the real and only reason this conference had for being: the relation of the ballot to work and wages.

The plank which I proposed was my own sincere thought, but I had no silly pride of authorship and I was sure it would be too strong medicine for some of the queasy stomachs present.

But in the name of a Merciful Heaven, why O why! did it seem necessary even to the jaded digestive system of Kelly Miller to feed the race on this one subject and at its hungriest moment, the thinnest economic flap-doodle?

