
---
title: 'A Little Play'
author: Du Bois, W.E.B.
date: Mar. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 5
  page: 241
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Time: Now.

Place: Here.

Enter the Pale One and the Brown One, dressed alike, speaking English, but coming from opposite entrances.

The Pale One: "Colored people are dirty, ignorant, lazy, poor and rude. Until they become clean, intelligent, thrifty, well to do and polite they must expect to be treated badly."

The Brown One: "Are all colored people dirty, ignorant, lazy and rude? If so, I am colored and therefore I must be---"

The Pale One: "Oh, no! I mean most colored people; or at any rate some colored people."

The Brown One: "And therefore should all colored people be treated badly, or only the dirty and ignorant and lazy and poor and rude?"

The Pale One: "Only the dirty and ignorant and---"

The Brown One: "And is it only dirty, ignorant, lazy, poor and rude *colored* folk who are to be badly treated?"

The Pale One: "Certainly not. All people who are dirty, ignorant, lazy, poor and rude must expect bad treatment."

The Brown One: "And has history proven that 'bad treatment' is the best cure for dirt, ignorance, poverty and rudeness, or is bad treatment their cause?"

The Pale One: "I can't go into that. At present they are treated badly."

The Brown One: "They surely are. And now, finally, how shall I be treated?"

The Pale One: "You shan't marry my sister."

The Brown One: "I don't want to; but to return to the subject---"

The Pale One: "You are seeking social equality!"

The Brown One: "If that means I'm seeking decent treatment---"

The Pale One: "You belong to an inferior race!"

The Brown One: "For Heaven's sake---"

The Pale One: "Oh, bother!"

Exit the Pale One in anger.

Exit the Brown One in thought.

