
---
title: 'Booming The Crisis'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 5
  page: 239-240
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The Washington *Bee,* a weekly colored periodical has been stirred to its
vitals by the fear that the money collected in Washington and elsewhere
for the National Association for the Advancement of Colored People is
going to be used for the support of <span class="crisis-title">The Crisis</span> We assure
the editor that not a single cent of such moneys goes to the support of
<span class="crisis-title">The Crisis</span>. <span class="crisis-title">The Crisis</span> supports itself, and has from the
beginning, with the single exception that the association provides an
editor for it.

Even this, however, does not apparently suit the nimble *Bee.* "But the
National Association for the Advancement of Colored People ignores the
splendid, vitalizing work of the race newspapers already established,
and established and financed by their editors, while concentrating its
efforts and giving of its funds exclusively to make <span class="crisis-title">The Crisis</span> a very late comer, the real and only organ of the race." Here again the editor is mistaken. Far from displacing the colored weekly newspapers, <span class="crisis-title">The Crisis</span> is giving them all
possible publicity and full and careful credit for everything which it
reprints.

<span class="crisis-title">The Crisis</span> regrets, however, that the amount of matter published in the *Bee* and in many other papers, which is worth, reprinting or even reading, is not nearly as large as it ought to be. Moreover, <span class="crisis-title">The Crisis</span> is convinced that more careful attention to some of the very things which this editor denounces would bring larger success to the colored weekly papers.

First: *Facts.* Of the newspapers mentioned only one, the *Afro-American Ledger,* makes a careful and valuable attempt to present the facts concerning the Negro. The others present some of the facts, but in a partial and incomplete way.

Second: *English.* Some of the best of colored papers are so wretchedly
careless in their use of the English language and sense of the value of
words that when they see English they are apt to mistake it for
something which the *Bee* mysteriously characterizes as "Oscar Wilde
atomized sentences," whatever that may be.

But third and most important: Few of the colored weekly papers have
stood staunch for *principle.* Outside the *Guardian* and the Cleveland
*Gazette* there have not been more than one or two colored papers from
whom the Negro people could expect year in and year out strong, staunch
advocacy of the fundamental principles of freedom and justice. Small
wonder that they welcome a periodical which (whatever its many faults
may-be) at least tries to give the facts, talk English and stand as an
unpurchasablc advocate of justice and right.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Our Special Grievances (1918)](/Volumes/16/05/our_special_greivances.html)
* [Other Organizations (1915)](/Volumes/10/05/other_organizations.html)
* [The Crisis (1910)](/Volumes/01/01/TheCrisis.html)
* [We Come of Age (1915)](/Volumes/11/01/we_come_of_age.html)
* [The New Crisis (1925)](/Volumes/30/01/new_crisis.html)

<!-- Similar articles end here -->