
---
title: 'Lynching'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 5
  page: 239
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


We do not blame the people of the United States for being ashamed of lynching, but we have serious doubts if recent methods of curing the evil are going to be really efficacious. We do not refer now to the unjust and dangerous hastening of the trials of accused persons, nor even to the proposed lessening of the penalty for mob murder; but rather to an attempt, deliberate or unintentional, to suppress the truth concerning the present extent of lynching in this land.

<span class = "small-caps">The Crisis</span>noted this last year. The first reports suggested that only thirty-four persons had been lynched during 1912. The second report published in other papers raised the amount to fifty or more while <span class = "small-caps">The Crisis</span>' record was "sixty-three, possibly sixty-eight."

As this, however, was our first attempt to keep a record, we let the matter go without comment; but we note for the year 1913 precisely the same phenomena, namely, an early syndicated report in certain papers with thirty-odd lynchings; next comes the Chicago *Tribune*, which has hitherto been looked upon as an authority on lynching statistics, and reports forty-four lynchings for the year. Then comes Mr. B. T. Washington's report saying there were fifty-one.

God knows <span class = "small-caps">The Crisis</span> is not anxious to increase the red record nor to revel in the spread of this most disgraceful blot upon our civilization. But nevertheless <span class = "small-caps">The Crisis</span> has counted during the year 1913 seventy-nine and possibly eighty lynchings. There is, of course, much difficulty in determining just the number of lynchings. News agencies in the South often deliberately suppress  these reports and in nearly all cases are vague as to names, places and details. It is always possible, therefore, that the same lynching may be reported twice; then, too, there is evident difficulty in determining what constitutes a lynching. Ordinary murders, even though by mobs, have usually not been included. Making all due allowances for these things, <span class = "small-caps">The Crisis</span> is unable to see any reason for believing that lynching decreased last year. On the contrary, the evidence of a substantial increase seems very strong. We would be only too glad to have our conclusions disproved.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Anti-Lynching Legislation (1922)](/Volumes/22/01/anti-lynching_legislation.html)
* [Lynching (1927)](/Volumes/33/04/lynching.html)
* [Crime and Lynching (1912)](/Volumes/03/03/crime_and_lynching.html)
* [Lynchings (1932)](/Volumes/39/02/lynchings.html)
* [The Lynching Industry (1915)](/Volumes/09/04/lynching_industry.html)

<!-- Similar articles end here -->