
---
title: 'Taxation without Representation'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 7
  issue: 5
  page: 240
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Negroes form 40 per cent. of the population of Memphis, Tenn. The city laid the following taxes during the year 1912:

|                                |               |
|--------------------------------|--------------:|
| For General Purposes           | $1.32 on $100 |
| For Public Schools             |   .25 on $100 |
|      Total City Rate           | 1.57          |
| State Levy for Parks           |   .15 on $100 |
| State Levy for Cossett Library |   .03 on $100 |
|      Total Rate for City       | $1.75 on $100 |

| State and County Taxes          |             |
|---------------------------------|------------:|
| State                           | .35 on $100 |
| County                          | .21 on $100 |
| Schools                         | .32 on $100 |
| High Schools                    | .01 on $100 |
| Bolton College                  | .01 on $100 |
| Industrial School               | .01 on $100 |
| Industrial School Apportionment | .01 $\frac{1}{2}$ on $100 |
| M. & O.R.R. Sinking Fund        | .01 on $100 |
| County Bonds Sinking Fund       | .01 on $100 |
| Levee Bonds Sinking Fund        | .01 on $100 |
| Interest                        | .05 on $100 |
| Bridge                          | .08 on $100 |
| Turnpike                        | .15 on $100 |
| Normal School                   | .01 on $100 |

From this taxation the Negroes get less than half their proportionate share for public schools and not one-fourth their share of public improvements; they cannot enter the parks for which they paid, but in 1913 they were given a small plot of land for a park. They are denied all access whatsoever to the following places which they support by taxation: 

The Cossett Library. 

The high school. 

Bolton College. 

The industrial school. 

The normal school. 

And Negroes have not a single representative in the city government. 

Not only this, but they are large renters of real estate. Everybody knows that the renter of real estate pays the taxes on it because the owner invariably charges him enough to pay the taxes and repairs and a reasonable (or unreasonable) return in addition.

Who is supporting Memphis? 

Who is supporting the South? 

Taxation without representation is tyranny.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Cost of Education (1911)](/Volumes/03/02/cost_of_education.html)
* [Muddle (1914)](/Volumes/08/04/muddle.html)
* [The Negro and the Land (1914)](/Volumes/07/04/negro_land.html)
* [If I Had a Million Dollars: A Review of the Phelps Stokes Fund (1932)](/Volumes/39/11/million_dollars.html)
* [Disenfranchisement (1925)](/Volumes/30/02/disenfranchisement.html)

<!-- Similar articles end here -->