
---
title: 'The Younger Literary Movement'
author: Du Bois, W.E.B. and Alan Locke
date: Feb. 1924
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 27
  issue: 4
  page: 161-163
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



<h2>I</h2>

There have been times when we writers of the older set have been afraid that the procession of those who seek to express the life of the American Negro was thinning and that none were coming forward to fill the footsteps of the fathers. Dunbar is dead; Chesnutt is silent; and Kelly Miller is mooning after false gods while Brawley and Woodson are writing history rather than literature. But even as we ask "Where are the young Negro artists to mold and weld this mighty material about us?"---even as we ask, they come. 

There are two books before me, which, if I mistake not, will mark an epoch: a novel by Jessie Fauset and a book of stories and poems by Jean Toomer. There are besides these, five poets writing: Langston Hughes, Countée Cullen, Georgia Johnson, Gwendolyn Bennett and Claude McKay. Finally, Negro men are appearing as essayists and reviewers, like Walter White and Eric Walrond. (And even as I write comes the news that a novel by Mr. White has just found a publisher.) Here then is promise sufficient to attract us. 

 We recognize the exquisite abandon of a new day in Langston Hughes' "Song For a Banjo." He sings: 

<div class="poem">
<p class="verse">Shake your brown feet, Liza, 
<p class="verse">Shake &rsquo;em Liza, chile, 
<p class="verse">Shake your brown feet, Liza,
<p class="verse indent"> (The music's soft and wile). 
<p class="verse">Shake your brown feet, Liza,
<p class="verse indent">(The Banjo's sobbin' low), 
<p class="verse">The sun's goin' down this very night&mdash;
<p class="verse">Might never rise no mo'. 
</div>

Countée Cullen in his "Ballad of the Brown Girl" achieves eight lyric lines that are as true as life itself. There is in Claude McKay's "If We Must Die" a strain martial and mutinous. There are other echoes---two from dead poets Jamison and Cotter who achieved in their young years long life if not immortality. But this essay is of two books. 

The world of black folk will some day arise and point to Jean Toomer as a writer who first dared to emancipate the colored world from the conventions of sex. It is quite impossible for most Americans to realize how straight-laced and conventional thought is within the Negro World, despite the very unconventional acts of the group. Yet this contradiction is true. And Jean Toomer is the first of our writers to hurl his pen across the very face of our sex conventionality. In "Cane" (Boni & Liveright, New York), one has only to take his women characters seriatim to realize this: Here is Karintha, an innocent prostitute; Becky, a fallen white woman; Carma, a tender Amazon of unbridled desire; Fern, an unconscious wanton; Esther, a woman who looks age and bastardy in the face and flees in despair; Louise, with a white and a black lover; Avey, unfeeling and unmoral; and Doris, the cheap chorus girl. These are his women, painted with a frankness that is going to make his black readers shrink and criticize; and yet they are done with a certain splendid, careless truth. 

Toomer does not impress me as one who knows his Georgia but he does know human beings; and, from the background which he has seen slightly and heard of all his life through the lips of others, he paints things that are true, not with Dutch exactness, but rather with an impressionist's sweep of color. He is an artist with words but a conscious artist who offends often by his apparently undue striving for effect. On the other hand his powerful book is filled with felicitous phrases---Karintha, "carrying beauty perfect as the dusk when the sun goes down,"--- 

<div class="poem">
<p class="verse">Hair—
<p class="verse">Silver-grey 
<p class="verse">Like streams of stars
</div>

Or again, "face flowed into her eyes---flowed in soft creamy foam and plaintive ripples." His emotion is for the most part entirely objective. One does not feel that he feels much and yet the fervor of his descriptions shows that he has felt or knows what feeling is. His art carries much that is difficult or even impossible to understand. The artist, of course, has a right deliberately to make his art a puzzle to the interpreter (the whole world is a puzzle) but on the other hand I am myself unduly irritated by this sort of thing. I cannot, for the life of me, for instance see why Toomer could not have made the tragedy of Carma something that I could understand instead of vaguely guess at; "Box Seat" muddles me to the last degree and I am not sure that I know what "Kabnis" is about. All of these essays and stories, even when I do not understand them, have their strange flashes of power, their numerous messages and numberless reasons for being. But still for me they are partially spoiled. 

Toomer strikes me as a man who has written a powerful book but who is still watching for the fullness of his strength and for that calm certainty of his art which will undoubtedly come with years. 

It had been my intention when I began this essay to discuss also Miss Fauset's novel. But Mr. Locke has sent us such an admirable and discriminating disquisition on this book that I gladly yield to him. 
<span class="right">--W. E. B. D.</span>

<h2>II</h2> 

The novel that the Negro intelligentzia have been clamoring for has arrived with Jessie Fauset's first novel, "There is Confusion" (Boni & Liveright, New York). What they have been wanting, if I interpret rightly, is not merely a race story told from the inside, but a cross section of the race life higher up the social pyramid and further from the base-line of the peasant and the soil than is usually taken. We scarcely realize how by reaction to social prejudice we have closed our better circles physically and psychologically: it is not always the fault of the novelist that he can depict only the peasant type and his urban analogue, the Negro of the slums. But here in refreshing contrast with the bulk of fiction about the Negro, we have a novel of the educated and aspiring classes. Miss Fauset has, however, not made the error of growing rootless flowers or exploring detached levels. Indeed she has sketched a Negro group against a wide social background of four generations---almost as much perspective as can be gotten on any social group in America, and moreover has not glossed over the slave régime, its ugly facts and its uglier consequences, though she has treated it incidentally as part of the genealogy and heredity of her characters. It is essentially a novel of blood and ancestry such as might be expected to come from the Philadelphia tradition which the author shares, and the Philadelphia scene which is part of her story. Yet it is too contemporary, not merely in incident, but in the phase of the race problem which it reflects, to be a period novel, a resurrection of the past. On the contrary it throbs with some of the latest reactions of the race situation in this country upon the psychology and relations of colored and white Americans of the more intelligent classes. It is this delineation of the problem as seen from the heights of respectability and from at least a plateau of culture that sharply differentiates Miss Fauset's novel from others. 

Joanna Marshall---more a heroine than most heroines, since she actually focusses and dominates in turn the life of her family, the estrangements and marriages of her brother and of her lover---is a strange character at war against herself. One part stoic, one part artistic, one part human with an emotional intensity and sincerity that is not Caucasian, she achieves success in her art at the very instant of her greatest disillusionment; but not before she has played unconscious havoc with several lives by her ambition and unswerving devotion to the ideals of success. 

Complicated as these lives are at almost every turn by the peculiar handicaps and confusions of color, it is well for the artistry and the worth of the book that the *primary confusions are those more universal ones of human nature and its type-psychologies*. The atmosphere of the book is that of Quaker faith and sober optimism, and its constructive suggestion is that of an eventual mutual understanding and coöperation through the discipline of experience. It is as though two antithetic sides of life, male and female, white and black, had each to work out its own chastening and enlargement through sorrow and disillusionment to find itself, late but not always too tragically late, able to rise from the level of confusion to the level of coöperation and understanding: 

The book has what I maintain is the prime essential for novels with such subject matter---social perspective, social sanity. A problem novel without this is either a raw and brutal cross-sectioning or medicated and unpalatable propaganda. From these two evils, the book happily and skillfully escapes. Of the style, one may say, that it fits the subject---and in this day of the confusion and compounding of styles, what can be better said? Certainly it sustains with interest a story that is more heavily ballasted with truth than two or three of the usual run of social novels that sail on a breezy style to the heavens of "six best sellers." So that it can be confidently commended to that increasing band who, thank God, want truth with their fiction, and who will welcome especially upon the race question and its reactions on the best types and classes of colored folk, a social document of sterling and intimate character. <span class="right">--A. L.</span>

<h2>III</h2>

These, then, are the two books of the younger Negro Movement; read them and enjoy them as I have done and spread the glad tidings. <span class="right">--W. E. B. D.</span>

_____
*Citation:* Du Bois, W.E.B. and Alan Locke. 1924. "The Younger Literary Movement." *The Crisis*. 27(4):161&ndash;163.