
---
title: 'The Durham Conference'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 10
  page: 348
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The Conference meeting this month at Durham, North Carolina, is unusual. It is not an attempt to unite existing organizations in an impossible federation for which there is neither demand nor need. It is not an attempt to form a new organization. It is a simple, straight-forward effort to ascertain facts and to take stock. 

There has been too little of this kind of meeting. We are so anxious to right our wrongs that we usually do not have time to find out just what the wrongs are. We want more work and better wages, but what work are we doing and what wages are we receiving? We want to go into business, but what business are we conducting at present and how successfully? We want to spread banking and insurance, but what is the condition of our banks and insurance societies today? We complain of the lack of religious belief, but what are our churches doing to foster it? We inveigh against disfranchisement, but how far are we really disfranchised? We demand education, but what chances for education have we now? We periodically "die out," but what is the real condition of our health? We are astonished at Negro crime, but how much Negro crime is there? 

All these questions, this Conference seeks to answer: first by hearing a documentory report on present conditions, prepared by an expert; and second, by hearing just what organized work is doing to better conditions; and then with these facts, the Conference is debating the question of improving the work of existing organizations; of indicating further work; and pointing out the necessity, if any, of further organization. 

Such a conference is distinctly worth-while. 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Races in Conference (1910)](/Volumes/01/02/races_in_conference.html)
* [Does Organization Pay? (1914)](/Volumes/07/06/does_organization_pay.html)
* [The National Interracial Conference (1929)](/Volumes/36/02/national_interracial_conference.html)
* [The Possibility of Democracy (1928)](/Volumes/35/09/possiblity_of_democracy_i.html)
* [Co-Operation (1918)](/Volumes/15/01/cooperation.html)

<!-- Similar articles end here -->