
---
title: 'Pullman Porters'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 10
  page: 348
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Despite bribes which have been directly and indirectly distributed in the effort to kill off the Union movement among Pullman Porters, we are pleased to see that they are fighting on. It is pitiable to note how some colored papers rejoice at every setback which the porters experience, and to see others discouraged because the union is not immediately successful. But what did we expect? Did any sane man think that the cause of collective bargaining in the case of Pullman Porters, with all the wealth and influence of the Pullman Company against them, and with organized white labor less than neutral, was going to triumph in a day? The porters have a fight of a generation before them. They are going to be beaten again and again, but they are going to win some day, if they eternally stick to it; if they twist and turn, attack now here and now there, return to the attack when beaten and insist that public almsgiving for the support of skilled labor is nothing less than stealing, foisted by the Pullman Car Company on a public which is too inert and short-sighted to stop it. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Black Man and Labor (1925)](/Volumes/31/02/black_man_and_labor.html)
* [Pullman Porters (1926)](/Volumes/31/03/pullman_porters.html)
* [Railroad Unions (1921)](/Volumes/22/05/railroad_unions.html)
* [Does Organization Pay? (1914)](/Volumes/07/06/does_organization_pay.html)
* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)

<!-- Similar articles end here -->