
---
title: 'Ten Years'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 10
  page: 348
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


It is astonishing to see the determination with which those who believe in the industrial methods of America and Western Europe are spreading misinformation concerning the Russian experiment. The central thing which has happened in Russia is this: the rotten, horrible, inexpressibly brutal and silly tyranny of the Czar, has been definitely and finally overthrown. No such travesty on decent government has existed elsewhere in Europe in modern days. It was a stench in the nostrils of humanity. It was flamboyant and impudent with murder and cruelty, on a foundation of ignorance and poverty and with flaming towers of ostentation and show which completely captivated the organized snobbery of the world. To be presented at the Russian Imperial Court was the last round in the ladder of ambition for every social climber in Europe and America. 

The rottenness of the Czar's Government was repeatedly exposed to the liberal world. Not a finger was raised to help. On the contrary, when in desperation Russia rose in 1905 to shake off medieval despotism and establish modern democracy, Western Europe poured its treasure into the hands of the Czar to beat the wretched Revolutionists back. Now finally, when of their own strength and determination, and their own vast will to sacrifice, the Russian people have buried Czarism and tried to establish a new government that frankly faces the economic problem which the world fears to face, there is scarcely a newspaper in America that will give this experiment even decent hearing. Yet the Union of Socialist Soviet Republics is celebrating today its Tenth Anniversary, and here's hoping that this is but the first decade toward its hundred years. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Negro and Communism (1931)](/Volumes/38/09/negro_and_communism.html)
* [Russia, 1926 (1926)](/Volumes/33/01/russia_1926.html)
* [Judging Russia (1927)](/Volumes/33/04/judging_russia.html)
* [The Negro and Radical Thought (1921)](/Volumes/22/03/negro_and_radical_thought.html)
* [Prejudice (1927)](/Volumes/34/09/prejudice.html)

<!-- Similar articles end here -->