---
title: 'The Liberal South'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: April 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 21
  issue: 6
  page: 247-248
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The white Executive Secretary of the Mississippi Welfare League, J.C. Wilson, writes thus to Moorfield Storey:

> The attitude of <span class="crisis-title">The Crisis</span>, which claims to be working in the interest of the Negro race to bring about better relations between the races in the United States, is, on the other hand, endeavoring to help the situation by using tactics which never bring peace, but war inevitably. And unless such radical papers change their attitudes and cease to abuse and defame the characters of the leading white people of the South who are earnestly and sincerely endeavoring to help the black man, the gulf will be widened between them.
>    
> The attempt of Du Bois to be sensational and vicious in his defamations is causing the Negro readers of his paper to hate white people more and more, and is unquestionably stirring the spirit of resentment in the minds of the white people. If this continues, it takes no prophet to predict the ultimate end. The terrible and bloody riot which occurred in Chicago last August was but a hint of what will occur.
>    
> We are wondering why this man Du Bois pursues this course. Is it possible that he hopes by such methods to increase the circulation of his paper and get for himself a certain kind of notoriety? Would he bring on war that would slaughter his race for personal gain? There are one of three things very evident: either Du Bois does not know the spirit of the white race, he is a fool, or is playing the game for loaves and fishes.

Josiah Morse, of the University of South Carolina, and a moving spirit of the white Southern University Race Commission, writes to J.E. Spingarn:

> If Du Bois is an element of moderation and self-control, then I need to begin all over again and learn the meaning of words. Of course everything is relative and dependent upon the viewpoint, but even then it is difficult to see how you can characterize him as you do. I think you should know that none of us here have any confidence in him; his influence, as we see it, is vicious and dangerous, and his connection with anything is sufficient to damn it forthwith. He sees red too much. The Negro who is going to be of service to his race must be able to look forward and backward an hundred years and maintain a philosophic poise and calm. Firebrands won't do; we'll extinguish them as often as we can. We need peacemakers, not ministers of hate.
>    
> I wonder if you know of the work which the Inter-racial Committee is doing throughout the South, upon which approximately $25,000 a month is being spent, and which has already accomplished many very gratifying results through the inter-racial committees that have been established in almost every county in every Southern State. Those of us who are giving the best we have to the cause of better race relationship feel that Du Bois, more than any other person or influence, is counteracting our efforts.

Similar statements have reached us from time to time from Bolton Smith, of Memphis, and other leading white Southerners.

The answer to these gentlemen and all who think like them is clear: Whether Negroes, like the editor of <span class="crisis-title">The Crisis</span>, are self-seeking scoundrels, or unconscious voices of a race ground-swell, or unselfish and farsighted patriots---in any case, the duty of the leaders of the white South is clear:

Lead the colored people. Grant their legitimate demands. Show them that they need look neither to demagogues nor dreamers but to *you* for all that is vitally necessary to their best development.

Get the confidence of black folk by deeds, not by promises or charity. Do not merely talk---DO!

The demands of the mass of Negroes are not radical---they are the irreducible minimum below which no modern group can drop and live:

- The right to vote
- The abolition of "Jim-Crow" travel
- Free compulsory public school education
- The abolition of lynching and mob law.

These are the demands of Negroes. They are the demands of every peasantry, every labor group, every race and nation in the civilized and semi-civilized worlds.

If the liberal white South secures these rights for black men and women, they will put every colored demagogue out of business; they will close the mouth of every agitator; they will gain the willing, eager support of every honest Negro patriot.

Here is your chance, Gentlemen. Will you take it?

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [The Macon Telegraph (1920)](/Volumes/19/03/macon_telegraph.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [Dodging the Issue (1933)](/Volumes/40/02/dodging_the_issue.html)

<!-- Similar articles end here -->