
---
title: 'The Negro Church'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 1
  page: 24-25
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



It happens that during this month, in the North, West and South, there
are meeting the ruling Methodist ecclesiastical bodies representing a
membership of 1,175,000 colored Americans. Later, in midsummer, the
Baptist conventions, which represent 2,300,000 members, will meet. These
three and a half millions of people represent the great middle class of
colored Americans. The lowest class of outcasts have never been reached;
the highest class of the educated and thoughtful are being gradually
lost. The great middle mass remains, and in 35,000 churches holding
\$57,000,000 worth of property they form a peculiar organized government
of men. Under some fifty powerful leaders and thirty thousand salaried
local preachers they raise and expend over seven millions of dollars a
year.

Before such an organization one must bow with respect. It has
accomplished much. It has instilled and conserved morals, it has helped
family life, it has taught and developed ability and given the colored
man his best business training. It has planted in every city and town of
the Union, with few exceptions, meeting places for colored folk which
vary from shelters to luxurious and beautiful edifices.

Notwithstanding this, all is not well with the colored church. First,
its fifty leaders are in too many cases not the men they should be. This
is not peculiar
to the Negro church, but it is true to a larger degree than is
healthful. We can point to pure-minded, efficient, unselfish prelates
like the late Bishop Paine, the present Bishop Lee and J W. White. We
have men of scholarship and standing like Bishop J. Albert Johnson, and
we have efficient men of affairs like John F. Hurst, M.C.B. Mason and
R.H. Boyd.

The trouble is, however, this: there are too few such men. The paths and
the higher places are choked with pretentious ill-trained men and in far
too many cases with men dishonest and otherwise immoral. Such men make
the way of upright and businesslike candidates for power extremely
difficult. They put an undue premium upon finesse and personal
influence.

Having thus a partially tainted leadership, small wonder that the
\$30,000 colored ministers fall as a mass far below expectations. There
are among them hustling business men, eloquent talkers, suave companions
and hale fellows, but only here and there does one meet men like Henry
L. Phillips of Philadelphia---burning spiritual guides of a troubled,
panting people, utterly self-forgetful, utterly devoted to a great ideal
of righteousness.

Yet this is precisely the type for which the church---the white church
as well as the black church---is crying. This is the only type which
will bold thoughtful, reasonable men to membership with this
organization. To-day the tendencies are not this way. To-day the church
is still inveighing against dancing and theatre-going, still blaming
educated people for objecting to silly and empty sermons, boasting and
noise, still building churches when people need homes and schools, and
persisting in crucifying critics rather than realizing the handwriting
on the wall.

Let us trust that these great churches in conference, remembering the
leaders of the past and conscious of all that the church has done well,
will set their faces to these deeds:

1.  Electing as bishops and leaders only men of honesty, probity and
efficiency and rejecting the noisy and unclean leaders of the
thoughtless mob.

2.  Weeding out the ministry so as to increase the clean apostles of
service and sacrifice.

3.  Initiating positive programs of education and social uplift and
discouraging extravagant building and mere ostentation.

4.  Bending every effort to make the Negro church a place where colored
men and women of education and energy can work for the best things
regardless of their belief or disbelief in unimportant dogmas and
ancient and outworn creeds.

