
---
title: 'Lynchings and Mobs'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 22
  issue: 4
  page: 150-151
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



> We anticipate agitation looking towards the establishment of separate High Schools in Indianapolis. In order to discuss the matter intelligently, we are asking you to be so kind as to give us the benefit of your observation, experience and judgment.

The theory of the public school is that it should be the foundation of the democracy of the land. To separate children usually means their virtual separation through life. This means misunderstanding, friction, group, class and racial hatred. So far then as possible we should strive in every way to keep the public schools open to all citizens, white and black, Jew and Gentile, rich and poor, native and foreign.

In some parts of the land, however, and in some cases, racial feeling is so strong that it would be impossible to carry on schools of this sort. But the community suffers from this and must, if it will keep down riot and race hatred, substitute other bonds of social sympathy to take the place of public school common training.

In a few cities it has been found possible while maintaining separate graded schools to have common high schools.

In these cities, above all others in the United States, there is the greatest opportunity for real national service. If it is impossible for children of high school age to work together at common knowledge and human training for four years, then it is impossible for white and colored people to live together in the United States and for different races to live together in the world. The test of the possibility of democracy lies in a certain very real sense in the mixed high schools of Indianapolis.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Reconstruction (1919)](/Volumes/18/03/reconstruction.html)
* [Segregation (1910)](/Volumes/01/01/Segregation.html)
* [School (1918)](/Volumes/16/06/school.html)
* [Segregation (1934)](/Volumes/41/01/segregation.html)
* [Public Schools (1916)](/Volumes/12/01/salutations.html)

<!-- Similar articles end here -->