
---
title: 'The Campaign of 1928'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 12
  page: 418
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



For the American Negro this has without doubt been the most humiliating presidential campaign through which he has passed. The agreement and accord of the two leading parties in regard to him has at last become perfect and complete. 

Tentative gropings toward accord date back to 1876 when under the plea of healing the wounds of Civil War, the Federal Government decided to give up all attempt at supervising national elections. This put the nation in the humiliating position of having almost no control over the voters who elect its officials. From this compromise, we moved forward during a long period when it was the recognized function of the Republican Party to deplore disfranchisement and assert stoutly its intention to defend the rights of American Negroes in all ways. The Democratic Party, on the other hand, took a position which accepted responsibility for Negro disfranchisement and made it the declared enemy of Negro advancement. 

As time went on, the indignation of Republican platforms cooled to a perfunctory declaration against the most outrageous of abuses, lynching, while the Democratic platform became silent because of the bid of Northern and Border state Democrats for Negro votes. The Republicans, however, proceeded to disfranchise Southern representatives in the party convention, and made repeated effort to transfer the control of the Republican Party in the South entirely to the hands of white men. The Democratic party, in the South by indirect and sometimes by positive action, aided and abetted these so-called Lily-White Republicans and threatened revolt if Northern Democrats treated with Negroes. 

Complete understanding came in the campaign of 1928. So far as possible Hoover overthrew every Negro political leader in the South, and made statements which the South interpreted as A promise to appoint no Negroes to office. The Democrats, on the other hand, even in the North, refrained sedulously from making any bid for the Negro vote. 

The result of this is that the political strategy which thoughtful Negro voters have been pursuing for sixteen years comes to naught. Their ideal was political independence, which involved breaking away from customary subserviency to the Republicans, and placing their votes at the disposition of either party, which bade fair from its record and its promises to secure them the largest increase of citizenship rights. 

When, now, neither party makes any promises whatsoever, or any bid for the Negro vote; when both parties acquiesce in attacks of racial bigotry and assertions which show their utter contempt and indifference to the Negro voter, the Negro is compelled to seek a new political program. 

He may as well give up immediately any thought of inducing either the Republicans or Democrats to favor any administrative action or legislation which will decrease the exploitation of Negro labor, the disfranchisement of Negro political power, or which will condemn the use of race hatred to influence and sway the ignorant proletariat and the self-satisfied snobs of the nation. With unswerving determination and careful planning, the Negro must prepare to throw his whole political influence with a Third Party. 

The Negro must ask as the price of his support of such a party: (1) the enforcement of the 13th, 14th and 15th Amendments, (2) Federal supervision of Federal elections, (3) the distribution of political power, based on the number of votes actually cast, and not simply on the population, (4) the socialization of wealth and income, so as to protect the interests of the poor laborer against the political power of the rich investor. 

Two incidents in this campaign give hope of success for this new political alignment. The first is the number of other groups who find themselves politically homeless: the women, the liberal white South, organized Labor, the Pacifists, and the Farmers are all politically dressed up with nowhere to go. They cannot even get a chance to vote against the thing they fear and hate. The second note of encouragement which comes is the unity of opinion shown by the Appeal to America which was sent out during the campaign. Never before in the history of the United States have American Negro leaders shown so great uniformity on matters fundamental to their civilization and advance. Starting with this and leaving the Valley of Humiliation behind us, let us climb forward to real and definite political power for twelve million Americans of Negro descent. 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [How Shall We Vote (1920)](/Volumes/20/05/how_shall_we_vote.html)
* [Political Straws (1923)](/Volumes/26/03/political_straws.html)
* [Young Voters (1932)](/Volumes/39/09/young_voters.html)
* [The Election (1914)](/Volumes/09/02/election.html)
* [The Election (1912)](/Volumes/05/02/the_election.html)

<!-- Similar articles end here -->