
---
title: 'The Election'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 12
  page: 418, 427
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Herbert Hoover and our only hope lies in the smashed and riven "white primary" of the lower South and the faint but heartening promise of the Socialist Third Party. 

Meantime, we congratulate Oscar DePriest, the first Negro Congressman from the North and the first Negro in Congress for a generation. He represents a vicious political machine, but he cannot be nearly as bad as the white men who run that machine and have been elected to rule Chicago. Moreover, unless Tammany, Thompson and Vare give us a political chance, who will? Not Hoover. Not Smith. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Negro Politician (1928)](/Volumes/35/05/negro_politician.html)
* [The Negro in Politics (1929)](/Volumes/36/11/negro_in_politics.html)
* [The Republican Party (1918)](/Volumes/15/06/republican_party.html)
* [The Presidential Campaign (1916)](/Volumes/12/06/presidential_campaign.html)
* [Education (1913)](/Volumes/06/02/democrats.html)

<!-- Similar articles end here -->