
---
title: 'Segregation'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1928
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 35
  issue: 12
  page: 418
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Very slowly but with unexpected success, the fight against governmental segregation in the departments at Washington has reached a stage where a record of achievement can be made and a new alignment of forces for the future planned. 

Beginning with the administration of Woodrow Wilson, and recurring under President Harding, efforts were made to segregate Negro clerks in Washington as follows: 

1. To establish separate Negro sections. 
2. To segregate clerks in the same sections in different rooms, 
3. To give separate service in cafeterias, lockers and restrooms, 
4. To curtail the appointment of Negro clerks. 

As a result of 15 years recurring opposition on the part of the National Office of the N.A.A.C.P. and its branch in Washington, with the cooperation of other branches, and of other organizations, segregation has stopped as follows: 

1. No new segregated sections have been established. 
2. Segregation in rooms by race has practically disappeared, the few remaining instances being not easily proven cases. The discrimination in cafeterias, except in two cases, has been absolutely repudiated by the heads of departments over their own signature. 

There remains, therefore, three things to be done: 

1. Clerks who are discriminated against in the future must be ready and willing to test the legality of the discrimination. 
2. Legal action must be taken against two cafeterias, one of which is in the Congressional Library, where deliberate and illegal discrimination is well-known. 
3. Effort must be made to see how far clerks of Negro descent are being kept from appointment and from promotion simply because of color. 

The N.A.A.C.P. will now address itself to these last two matters. 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Inter-Racial Comity (1922)](/Volumes/22/01/inter-racial_comity.html)
* [The N.A.A.C.P. and Race Segregation (1934)](/Volumes/41/02/naacp_and_race_segregation.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [Mr. Taft (1911)](/Volumes/02/06/taft.html)
* [Segregation in the North (1934)](/Volumes/41/04/segregation_in_the_north.html)

<!-- Similar articles end here -->