
---
title: 'Credit'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 1
  page: 31
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Again and again when men unite to some great end and accomplish all or a part of that toward which they aim, there arises an astonishing and often disreputable scramble for the honor and credit of the accomplishment. In a sense this is natural. Independent enthusiasts striving for a great end often forget or are ignorant of others striving for the same end and are indignant or incredulous when they do not receive what they think is due credit. Something of this unfortunate feeling is creeping into recent movements in which this Association has been interested. An extraordinary campaign has been carried on to prevent Congress from passing discriminatory legislation. That the Sixty-Third Congress has actually adjourned without the enactment of such laws, and with some things like the Howard University appropriation to its credit, is an extraordinary tribute to the organized fighting strength of American Negroes. To whom should the credit for this accomplishment be given? Manifestly to no one person or to no one organization. The National Association for the Advancement of Colored People would be the last to claim sole and entire credit for the accomplishment. Individuals unconnected with it and organizations not affiliated have from time to time joined enthusiastically in these campaigns. Two things the Association has an undoubted right to claim; first:---that through its widespread organization and continual vigilance it has been able to keep the colored people warned, and secondly, that through its continual insistence upon the value of agitation it has brought almost a revolution in the attitude of the colored people during the last five years. But after all what difference does it make as to who did the deed so long as the deed is done? so long as the Negroes fight aggression, advance their interests and rescue the spirit of democracy in the United States? Away with littleness and jealousy, and on with the fight!
______
*Citation:* Du Bois, W.E.B. 1915. "Credit." *The Crisis*. 10(1):31.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Inter-Racial Comity (1922)](/Volumes/22/01/inter-racial_comity.html)
* [The Congressmen and the NAACP (1914)](/Volumes/09/02/congressmen_and_the_naacp.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [The Next Step (1913)](/Volumes/06/02/next_step.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)

<!-- Similar articles end here -->