
---
title: 'Peace'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 1
  page: 28
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


The various efforts toward peace show with singular unanimity either the utter inability or the determined refusal of the peace advocates to consider race prejudice as the prime cause of the present world war. The Holland Peace Movement, founded October 8th, notes ten points of proposed agreement for the overthrow of war. These points include closer co-operation among "European" powers, arbitration among "civilized" states, and the suppression of animosity between "nations." But not a word about race hatred and the rulership of the colonies for the profit of Europe. So too, the American Truth Society in Munich protests against the introduction of Japan to this European war which, as it says, "involves a menace to the supremacy of the white race!"

______
*Citation:* Du Bois, W.E.B. 1915. "Peace." *The Crisis*. 10(1):28.
<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Peace (1913)](/Volumes/06/01/peace.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [Close Ranks (1918)](/Volumes/16/03/close_ranks.html)
* [Just Like---Folks (1920)](/Volumes/19/05/just_like_folks.html)
* [Listen, Japan and China (1933)](/Volumes/40/01/listen_japan_and_china.html)

<!-- Similar articles end here -->