
---
title: 'The Republicans'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 1
  page: 128
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Very quietly and on tiptoe the Republican Party has completed its disfranchisement of Negro delegates in the South. On February 1st Mr. James B. Reynolds, secretary of the Republican National Committee, announced that the disfranchisement proposed by the Republican National Committee had been approved by the requisite number of states. Under this new provision, each state is entitled to four delegates at large and one delegate from each congressional district; also an additional delegate for each congressional district in which the Republican vote was not less than 7,500. In this way the Republican Party hopes to get rid of the majority of its Negro representatives from the South in the National Convention. We have been pausing for sometime to hear the comment of colored Republicans on this procedure.

_____
*Citation:* Du Bois, W.E.B. 1915. "The Republicans." *The Crisis*. 10(1):128.
<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Election (1910)](/Volumes/01/02/election.html)
* [How Shall We Vote (1920)](/Volumes/20/05/how_shall_we_vote.html)
* [Every Four Years (1920)](/Volumes/19/06/every_four_years.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [The Negro Party (1916)](/Volumes/12/06/negro_party.html)

<!-- Similar articles end here -->