
---
title: 'An Old Folks'' Home'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 9
  issue: 5
  page: 242-243
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


It is noticeable that the number of colored people asking charity in hard times like the present is much less than the great poverty of the race would lead one to expect. The reason for this is the large amount of unrecorded and personal charity that takes place inside the race lines: the cheerful helping of neighbors, the adoption of children and the care of the old. In the latter work Negro charity has become institutional and the old folks' home is perhaps the most characteristic Negro charity.

There are today in the United States not less than one hundred homes supported and conducted very largely by colored people. One of them, the Home for Aged and Infirm Colored Persons at Philadelphia, was endowed by a colored man in 1864 with a capital of about $100,000. Philanthropic whites have added to this until the Home's property now is worth $400,000. In other cases, as in Springfield, Mass., a colored man, Primus Mason, founded a home for all races; and in New Bedford, a colored woman, Miss Elizabeth C. Carter, has a home for which she has collected over $35,000.

This article refers primarily to the Home for Aged Colored People in Cleveland, Ohio. It was founded by Mrs. Eliza Bryant in 1893 and incorporated in 1896. The present property containing eleven rooms and all improvements was purchased in 1901, burned down soon after, but reoccupied in 1902. The home is valued at $11,725, with a mortgage indebtedness of $4,000. The home collects through donations, entertainments and the like about $2,200 a year. There is a house furnishing committee which collected $373 worth of furniture last year; there is a $15,000 campaign committee which is hard at work. The institution is conducted by a board of trustees consisting of twenty persons of whom four are men and the rest women. The home is a member of the Cleveland Federation for Charity and Philanthropy and thus receives advice and co-operation in the latest philanthropic methods. This institution together with dozens of similar institutions throughout the United States call for the sympathy and co-operation of all right-minded people.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [White Charity (1922)](/Volumes/24/02/whitecharity.html)
* [Tenements (1916)](/Volumes/12/02/tenements.html)
* [Muddle (1914)](/Volumes/08/04/muddle.html)
* [Philanthropy and Self Help (1918)](/Volumes/16/03/philanthropy_and_self_help.html)
* [Homes (1912)](/Volumes/03/05/homes.html)

<!-- Similar articles end here -->