
---
title: 'Presidential Candidates'
author: NAACP
date: May 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 13
  issue: 1
  page: 16-17
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


*The following letter was sent to Honorable Charles Evans Hughes, September 28, 1916:*

Sir: 

As an organization representing the Negro race and thousands of its friends we are deeply interested in the presidential election. 

During the last campaign, believing firmly that the Republican Party and its leaders had systematically betrayed the interests of colored people, many of our members did what they could to turn the colored vote toward Mr. Wilson. We received from him a promise of justice and sincere endeavor to forward their interests. We need scarcely to say that Mr. Wilson grievously disappointed us. 

We find ourselves again facing a presidential campaign with but indifferent choice. We have waited for some time to gather from your writings and speeches something of your attitude toward the colored people. We have seen little. We are told, of course, in general that you have no race policy and propose to treat all Americans squarely. If Negroes were Americans---if they had a reasonable degree of rights and privileges we could ask no more than this; but being as they are, members of a segregated class and struggling against tremendous prejudices, disabilities and odds, we must for their own salvation and the salvation of our country ask for more than such treatment as is today fair for other races. We must continually demand such positive action as will do away with their disabilities. Lynching is a national evil of which Negroes are the chief victims. It is perhaps the greatest disgrace from which this country suffers, and yet we find you and other men of influence silent in the matter. A republic must be based upon universal suffrage or it is not a republic; and yet, while you seem anxious to do justice toward women, we hear scarcely a word concerning those disfranchised masses of the South whose stolen votes are used to make Rotten Boroughs of a third of the nation and thus distort and ruin the just distribution of political power. Caste restrictions, fatal to Christian civilization and modern conceptions of decency, are slowly, but forcibly, entering this land and making black folk the chief victims. There should be outspoken protest against segregation by race in the civil service, caste in public travel and in other public accommodations. As Negroes and as their friends; as Americans; as persons whose fathers have striven for the good of this land and who ourselves have tried unselfishly to make America the land of just ideals, we write to ask if you do not think it possible to make to the colored and white people of America some statement of your attitude toward this grievous problem such as will allow us at least to vote with intelligence. 

It seems to us that we have a right to know your attitude toward lynching, disfranchisement, caste and race hatred, and that without this knowledge it will be impossible for us to cast a discriminating vote. We are especially anxious to know how far the possession of a dark face or a drop of Negro blood will in your administration act as a bar to appointment to office and how far the inherited prejudice of many Americans shall veto the rights and civil privileges of others. 

We trust, Sir, that you will not regard this statement and request as beyond the courtesy due you or as adding too much to the burdens of a public man. 

We beg to remain, Sir,<br>
&nbsp; &nbsp;&nbsp;Very respectfully yours, 

<ul style="list-style: none;">
<li> <span class="small-caps">National Association for the Advancement of Colored People</span>.
<li> (Signed) J. E. <span class="small-caps">Spingarn</span>, Chairman of the Board of Directors.
<li> (Signed) Oswald Garrison <span class="small-caps">Villard</span>, Treasurer
<li> (Signed) W. E. Burghardt <span class="small-caps">Du Bois</span>, Director of Publications and Research.
<li> (Signed) A. H. <span class="small-caps">Grimké</span>, President, District of Columbia Branch. 
</ul>

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The President (1915)](/Volumes/09/04/president.html)
* [Mr. Hughes (1916)](/Volumes/13/01/mr_hughes.html)
* [An Open Letter to Woodrow Wilson (1913)](/Volumes/05/05/open_letter.html)
* [The Presidential Campaign (1916)](/Volumes/12/06/presidential_campaign.html)
* [The Congressmen and the NAACP (1914)](/Volumes/09/02/congressmen_and_the_naacp.html)

<!-- Similar articles end here -->