
---
title: 'Southern Civilization'
author: Du Bois, W.E.B.
date: May 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 13
  issue: 1
  page: 11-12
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The new Encyclopedia Britannica has listed the States of the Union
according to the number of sets of that monumental work which have been
sold in proportion to population. Where is the South in this list? Where
would you expect it to be? At the end, of course, with Mr. Vardaman's
State leading the rear and Mr. Tillman's State next to it and Georgia,
Alabama and Texas, of lynching fame, ranking close to the end. This is
not only the natural fruit of slavery; it is the fruit of present
political and legal conditions in the South. We have it out of the
South's own mouth. The Macon *Telegraph* writes of the recent Primary in
Georgia: "The 'red shirt' days in South Carolina; the rottenest days
during the period of the Hamburg riot; the slime of the most nauseating
politics ever known in Georgia---none of it even nearly borders on to
the method of campaigning now going on in behalf of Hugh M. Dorsey."

The Primary in South Carolina was just as bad if not worse. It is this
kind of oligarchy that the South wants perpetuated; it is for this
reason that the Southern women in the Suffrage convention at Atlantic
City were so strenuously opposed to a National Suffrage Amendment.
Suffrage based on National law will eventually be enforced by the
National Government; but Suffrage based on Georgia law will be enforced
as Georgia is now enforcing it. Yet the Northern women in the Suffrage
convention were blind as bats as to
the real animus behind the fight of Laura Clay and Kate Gordon. The
woman correspondent of the *New Republic* grows enthusiastic, shrill and
almost inarticulate over one of them: "We gloried in her. We revelled in
her!"

Of course we did, and if some poor, old black woman, disfranchised and
deprived of her rightful support by a lyncher's mob which had made a
mistake, had happened into that convention "we" would not have "gloried"
or "revelled" in her. We would have passed the hat and told her to go
home and not agitate for the "Impossible."

