
---
title: 'The Higher Friction'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1927
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 34
  issue: 2
  page: 70
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Let us take courage from certain present aspects of the Negro problem. Friction there has always been between black and white since 1619. Friction there will probably be still in 2019. But the friction rises in the scale; it touches, decade by decade, higher levels---higher interests, higher sensibilities, even while the lower friction persists. To illustrate our meaning consider this table.

1860---Physical freedom  
1870---Crime and poverty  
1880---Right to hold property  
1890---Reading and writing  
1900---Voting  
1910---Lynching  
1920---Homes

There was freedom for some Negroes before 1860 but that year it became a problem for all. The crime and degradation incident to emancipation was critical in 1870. By 1880 we had to answer the query if Negroes could own property. By 1890 the Negroes' right to some education was won. By 1900 the Negro had been disfranchised in fact but in law he was a legal voter. Before 1900, lynching was defensible and met with little opposition and until this decade there was almost no wide-spread problem of Negroes living in desirable homes next to whites because black folk were too poor to buy such homes. Thus even in the record of discrimination we are pressing on and up. The founding stones still waver, far from fast, but the trembling walls reach up to higher friction.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Violations of Property Rights (1911)](/Volumes/02/01/violations.html)
* [Our Economic Peril (1930)](/Volumes/37/03/our_economic_peril.html)
* [Work for Black Folk in 1914 (1914)](/Volumes/07/04/work_for_black_folk.html)
* [The Negro and the Land (1914)](/Volumes/07/04/negro_land.html)
* [Our Book Shelf (1926)](/Volumes/31/03/book_shelf.html)

<!-- Similar articles end here -->