
---
title: 'Haiti'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 6
  page: 297-298
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The United States is at war with Haiti. Congress has never
sanctioned this war. Josephus Daniels has illegally and unjustly
occupied a free foreign
land and murdered its inhabitants by the thousands. He has deposed its
officials and dispersed its legally elected representatives; He is
carrying on a reign of terror, brow-beating, and cruelty, at the hands
of southern white naval officers and marines. For more than a year this
red-handed deviltry has proceeded, and today the Island is in open
rebellion. The greatest single question before the parties at the next
election is the Freedom of Haiti.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Haiti (1921)](/Volumes/22/06/haiti.html)
* [Haiti (1915)](/Volumes/11/02/haiti.html)
* [Naval Ruler (1917)](/Volumes/14/01/naval_ruler.html)
* [The History of Haiti (1920)](/Volumes/20/05/history-of-haiti.html)
* [Two Columns (1916)](/Volumes/12/04/_two-columns.html)

<!-- Similar articles end here -->