
---
title: 'Hyde Park'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 6
  page: 298
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



A crowed of white profiteers in the Hyde Park division of the city of
Chicago publish a *Property Owners' Journal* and are moving heaven and
earth to get Negroes voluntarily to segregate themselves. They have even
had the impudence to quote  <span class="crisis-title">The Crisis</span> in their own
defense, when we asserted "the right of any individual of any race or
color to choose his own marital mate, his own friend, and his own dinner
companion,---in fine, to be the master of his home." What these real
estate agents want is not only to be masters of their own homes, but
also of ours. They may buy property where they please, but we must not
buy where we please. They claim the right not only to occupy their own
houses, but to determine who shall live next door. We hope that the
Chicago Negroes will buy just as much property in Hyde Park as they can
pay for, and proceed to live therein.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Homes (1912)](/Volumes/03/05/homes.html)
* [Divine Right (1912)](/Volumes/03/05/divine_right.html)
* [Real Estate in New York (1914)](/Volumes/08/03/real_estate_in_new_york.html)
* [Work for Black Folk in 1914 (1914)](/Volumes/07/04/work_for_black_folk.html)
* [Violations of Property Rights (1911)](/Volumes/02/01/violations.html)

<!-- Similar articles end here -->