
---
title: 'Negro Writers'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 6
  page: 298-299
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Since its founding, <span class="crisis-title">The Crisis</span> has been eager to discover ability among Negroes, especially in literature and art. It remembers with no little pride its covers by Richard Brown, William Scott, William Farrow, and Laura Wheeler; and its cartoons by Lorenzo Harris and Albert Smith; it helped to discover the poetry of Roscoe Jamison, Georgia Johnson, Fenton Johnson, Lucian Watkins, and Otto Bohanan; and the prose of Jessie Fauset and Mary Effie Lee. Indeed, <span class="crisis-title">The Crisis</span> has always preferred the strong matter of unknown names, to the platitudes of well-known writers; and by its Education and Children numbers, it has shown faith in the young.

One colored writer, Claude McKay, asserts that we rejected one of his poems and then quoted it from Pearson's; and intimates that colored editors, in general, defer to white editors' opinions. This is, of course, arrogant nonsense. But it does call our attention to the need of encouraging Negro writers. We have today all too few, for the reason that there is a small market for their ideas among whites, and their energies are being called to other and more lucrative ways of earning a living. Nevertheless we have literary ability and the race needs it. A renaissance of American Negro literature is due; the material about us in the strange, heartrending race tangle is rich beyond dream and only we can tell the truth and sing the song from the heart.

From the beginning, the editor has read with care every manuscript sent us, which explains the unconscionable delay in returning many; and yet for three years the editor was editor, business manager, and chief clerk, and only this last year has <span class="crisis-title">The Crisis</span> been able to hire an editorial staff even approximately adequate to the work.

 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Younger Literary Movement (1924)](/Volumes/27/04/younger_movement.html)
* [The Name Negro (1928)](/Volumes/35/03/name_negro.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [The Macon Telegraph (1920)](/Volumes/19/03/macon_telegraph.html)
* [An Open Letter to Robert Russa Moton (1916)](/Volumes/12/03/open_letter.html)

<!-- Similar articles end here -->