
---
title: 'Remember'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 6
  page: 297
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The foundations of the present political South are built upon sand.
It requires only a resolute executive in the White House and a free
House of Representatives; then when the Representatives from the
Southern South knock at the door, the House of Representatives has
simply to say---Who votes in Mississippi, in South Carolina, in
Alabama?---and to declare that upon such a basis of franchise, the
so-called members of Congress have not been legally elected.

This is all. The deed is done. And the Negro is a free man.

Nor is the possibility of this so far away. A little more southern
arrogance in Washington, a little more greed in the expenditure of
public funds, such as occurred during the war; a little larger
assumption that the South owns the United States, and the nation may
awake to real Democracy.

Or, again,---suppose the "dirty foreigners" and the disfranchised
Socialists and the disfranchised blacks should get together and vote
together at the next election!

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Newest South (1913)](/Volumes/06/03/newest_south.html)
* [Votes (1919)](/Volumes/19/02/votes.html)
* [The White Primary (1911)](/Volumes/01/05/white_primary.html)
* [The Truth (1911)](/Volumes/01/03/truth.html)
* [The Negro in Politics (1929)](/Volumes/36/11/negro_in_politics.html)

<!-- Similar articles end here -->