
---
title: 'The Fruit of the Tree'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 5
  page: 232
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Let no one for a moment mistake that the present increased attack on the
Negro along all lines is but the legitimate fruit of that long campaign
for subserviency and surrender which a large party of Negroes have
fathered now some twenty years. It is not necessary to question the
motives of these men nor to deny that their insistence on thrift and
saving has had its large and beneficent effect. But, on the other hand,
only the blind and foolish can fail to see that a continued campaign in
every nook and comer of this land, preaching to people white and
colored, that the Negro is chiefly to blame for his condition, that he
must not insist on his rights, that he should not take part in politics,
that "Jim Crowism" is defensible and even advantageous, that he should
humbly bow to the storm until the lordly white man grants him
clemency---the fruit of this disgraceful doctrine is disfranchisement,
segregation, lynching, and that last straw, the cowardly and unspeakable
Patterson. Fellow Negroes, is it not time to be men? Is it not time to
strike back when we are struck? Is it not high time to hold up our heads
and clench our teeth and swear by the Eternal God we will NOT be slaves,
and that no aider, abetter and teacher of slavery in any shape or guise
can longer lead us?

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Dodging the Issue (1933)](/Volumes/40/02/dodging_the_issue.html)
* [Education (1913)](/Volumes/06/02/democrats.html)
* [Jim Crow (1919)](/Volumes/17/03/jim_crow.html)
* [Work for Black Folk in 1914 (1914)](/Volumes/07/04/work_for_black_folk.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)

<!-- Similar articles end here -->