
---
title: 'Another Open Letter to Woodrow Wilson'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Nov. 1913
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 6
  issue: 7
  page: 339-341
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Sir: On the occasion of your inauguration as President of the United States, <span class = "small-caps">The Crisis</span> took the liberty of addressing to you an open letter. <span class = "small-caps">The Crisis</span> spoke for no inconsiderable part of ten millions of human beings, American born, American citizens. <span class = "small-caps">The Crisis</span> said in that letter, among other things: 

> The only time when the Negro problem is insoluble is when men insist on settling wrong by asking absolutely contradictory things. You cannot make 10,000,000 people at one and the same time servile and dignified, docile and self-reliant, servants and independent leaders, segregated and yet part of the industrial organism, disfranchised and citizens of a democracy, ignorant and intelligent. This is impossible and the impossibility is not factitious; it is in the very nature of things.    <p> On the other hand, a determination on the part of intelligent and decent Americans to see that no man is denied a reasonable chance for life, liberty and happiness simply because of the color of his skin is a simple, sane and practical solution of the race problem in this land.

Sir, you have now been President of the United States for six months and what is the result? It is no exaggeration to say that every enemy of the Negro race is greatly encouraged; that every man who dreams of making the Negro race a group of menials and pariahs is alert and hopeful. Vardaman, Tillman, Hoke Smith, Cole Blease and Burleson are evidently assuming that their theory of the place and destiny of the Negro race is the theory of your administration. They and others are assuming this because not a single act and not a single word of yours since election has given anyone reason to infer that you have the slightest interest in the colored people or desire to alleviate their intolerable position. A dozen worthy Negro officials have been removed from office, and you have nominated but one black man for office, and he, such a contemptible cur, that his very nomination was an insult to every Negro in the land. 

To this negative appearance of indifference has been added positive action on the part of your advisers, with or without your knowledge, which constitutes the gravest attack on the liberties of our people since emancipation. Public segregation of civil servants in government employ, necessarily involving personal insult and humiliation, has for the first time in history been made the policy of the United States government. 

In the Treasury and Postoffice Departments colored clerks have been herded to themselves as though they were not human beings. We are told that one colored clerk who could not actually be segregated on account of the nature of his work has consequently had a cage built around him to separate him from his white companions of many years. Mr. Wilson, do you know these things? Are you responsible for them? Did you advise them? Do you not know that no other group of American citizens has ever been treated in this way and that no President of the United States ever dared to propose such treatment? Here is a plain, flat, disgraceful spitting in the face of people whose darkened countenances are already dark with the slime of insult. Do you consent to this, President Wilson? Do you believe in it? Have you been able to persuade yourself that national insult is best for a people struggling into self-respect? 

President Wilson, we do not, we cannot believe this. <span class = "small-caps">The Crisis</span> still clings to the conviction that a vote for Woodrow Wilson was NOT a vote for Cole Blease or Hoke Smith. But whether it was or not segregation is going to be resented as it ought to be resented by the colored people. We would not be men if we did not resent it. The policy adopted, whether with your consent or knowledge or not, is an indefensible attack on a people who have in the past been shamefully humiliated. There are foolish people who think that such policy has no limit and that lynching, "Jim Crowism," segregation and insult are to be permanent institutions in America. 

We have appealed in the past, Mr. Wilson, to you as a man and statesman; to your sense of fairness and broad cosmopolitan outlook on the world. We renew this appeal and to it we venture to add some plain considerations of political expediency. 

We black men still vote. In spite of the fact that the triumph of your party last fall was possible only because Southern white men have, through our disfranchisement, from twice to seven times the political power of Northern white men---notwithstanding this, we black men of the North have a growing nest egg of 500,000 ballots, and ballots that are counted, which no sane party can ignore. Does your Mr. Burleson expect the Democratic party to carry New York, New Jersey, Pennsylvania, Ohio, Indiana, Illinois, by 200,000 votes? If he does will it not be well for him to remember that there are 237,942 black voters in these States. We have been trying to tell these voters that the Democratic party wants their votes. Have we been wrong, Mr. Wilson? Have we assumed too great and quick a growth of intelligence in the party that once made slavery its cornerstone? 

In view of all this, we beg to ask the President of the United States and the leader of the Democratic party a few plain questions: 

1. Do you want Negro votes? 
2. Do you think that a "Jim Crow" civil service will get these votes? 
3. Is your Negro policy to be dictated by Tillman and Vardaman? 
4. Are you going to appoint black men to office on the same terms that you choose white men? 

This is information, Mr. Wilson, which we are very anxious to have. 

<span class = "small-caps">The Crisis</span> advocated sincerely and strongly your election to the Presidency. <span class = "small-caps">The Crisis</span> has no desire to be compelled to apologize to its constituency for this course. But at the present rate it looks as though some apology or explanation was going to be in order very soon. 

We are still hoping that present indications are deceptive. We are still trying to believe that the President of the United States is the President of 10,000,000, as well as of 90,000,000, and that though the 10,000,000 are black and poor, he is too honest and cultured a gentleman to yield to the clamors of ignorance and prejudice and hatred. We are still hoping all this, Mr. Wilson, but hope deferred maketh the heart sick. Very respectfully yours, 

<span class = "small-caps">The Crisis</span>. 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Letters (1919)](/Volumes/17/01/letters.html)
* [An Open Letter to Robert Russa Moton (1916)](/Volumes/12/03/open_letter.html)
* [The President (1915)](/Volumes/09/04/president.html)
* [The Truth (1912)](/Volumes/05/02/truth.html)
* [Education (1913)](/Volumes/06/02/democrats.html)

<!-- Similar articles end here -->