
---
title: 'Consecration'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 6
  page: 285
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



In the patois of his very religious speech the Negro is about to lose the real significance of a fine word---Consecration; and back of it all a finer idea. As it is, we have come to look upon consecration as a negative, spineless, namby-pamby thing, the incarnation of the "mustn't" idea, the fear of the "Thou shalt not." The consecration that is needed today has all the thunders of "Thou shalt." It is action, doing, deeds. Better in this awful era of bitter want that we should sin by over-action, by overdoing, rather than die by the cowardice of inertia.

Look upon these little faces that broider our pages. Think of the millions that are not here---just as lovely and alluring---and remember that it is our present business to write in on the souls that look through these dark eyes wishes, wills, determinations, consecration.

But consecration to what? Not to religion, because religion is a method and not a thing. Not to one particular kind of work, but rather to the work that leads to things of greatest importance, the work for which the universe today pants. That work is business, industry, the making and fashioning of things. Consecration to business must be the slogan that follows the present outburst of Hell, else civilization is doomed.

The first duty of man is to earn a living. The earning of a living today is business and industry. Unless we put unselfish, consecrated men into the doing of this work, we turn it over to thieves and scoundrels. If sharpers and gamblers run the business and industry of the world, the result is the crop of mad jealousies that have made this present war. Consecration to business, then, must be the work of the future.

We must go into business for our health. We must oust the idea of selfish gain. We must try to teach the nations to earn a living by honesty, by efficiency, and along the paths of beauty. We can do this only by means of the children. The fine ideal of the Socialistic state is absolutely impossible until we get the consecrated business man. So long as business is in the hands of social scoundrels whose business ideal is to be millionaires, just so long modern industrial organization will always find itself impossible, will always end in chaos. Lift up your heads, O ye gates, and let the little children enter. Children upon whose hearts we who know, we who have suffered hatred, degradation and poverty, we, the people of the future democracy, have written---*Consecrated to Business.*

Does the ideal sound cheap? The cheapness is in your own perverted soul, O Reader.

