
---
title: 'Houston'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 6
  page: 284-285
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


It is difficult for one of Negro blood to write of Houston. Is not the ink within the very wells crimsoned with the blood of black martyrs? Do they not cry unavenged, saying:---Always WE pay; always WE die; always, whether right or wrong, it is SO MANY NEGROES killed, so many NEGROES wounded. But here, at last, at Houston is a change. Here, at last, white folk died. Innocent, adventitious strangers, perhaps, as innocent as the thousands of Negroes done to death in the last two centuries. Our hands tremble to rise and exult, our lips strive to cry.

And yet our hands are not raised in exultation; and yet our lips are silent, as we face another great human wrong.

We did not have to have Houston in order to know that black men will not always be mere victims. But we did have Houston in order to ask, Why? Why must this all be? At Waco, at Memphis, at East St. Louis, at Chester, at Houston, at Lexington, and all along that crimsoned list of death and slaughter and orgy and torture.

This, at least, remember, you who jump to judgment---Houston was not an ordinary outburst. Just before the riot the acting chaplain of the regiment writes us: "The battalion has made good and all doubts as to the conduct of the Negro soldier have been dissipated. We are striving to add another page to the glorious record of our regiment."

What it was they had to stand, we learn only in tortuous driblets from sources bitterly prejudiced. These facts, at least, are clear: Contrary to all military precedent the Negro provost guard had been disarmed and was at the mercy of citizen police who insulted them until blood ran. At last, they stole their own arms and turned and fought. They were not young recruits; they were not wild and drunken wastrels; they were disciplined men who said---"This is enough; we'll stand no more!" That they faced and faced fearlessly the vision of a shameful death, we do not doubt. We ask no mitigation of their punishment. They broke the law. They must suffer. But before Almighty God, if those guiltless of their black brothers' blood shot the punishing shot, there would be no dead men in that regiment.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Houston (1918)](/Volumes/16/06/houston.html)
* [Houston and East St. Louis (1918)](/Volumes/15/06/houston_and_east_st_louis.html)
* [Houston: An N.A.A.C.P. Investigation (1918)](/Volumes/15/01/houston.html)
* [Prejudice (1911)](/Volumes/02/01/prejudice.html)
* [Heroes (1919)](/Volumes/19/01/heroes.html)

<!-- Similar articles end here -->