
---
title: 'Advertising'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1922
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 25
  issue: 4
  page: 152
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Most colored folk do not yet quite understand modern advertising. They still think of advertising as a species of bribery, hush-money or charity given to newspapers to secure their support or reward their faithfulness or pay their debts.

There is, of course, much of this sort of "advertising" still with us and in high places. But modern advertising of the efficient sort is far beyond this. It is an effort to carry a message to those who ought to get it; to tell people who use soap, about a new, good, cheap soap; to tell people who buy clothes, where they may buy a certain kind. 

The National Association for the Advancement of Colored People wishes to pass the Dyer Bill. The colored people were behind them in this to a man. The mass of the whites was indifferent. We wanted to arouse the whites to the enormity---the shame and disgrace of lynching. How could we best do this?

After long consideration and argument, we decided to advertise. But where? Not, most assuredly with our friends;---not with papers whose readers were converted, but we proposed to advertise in those periodicals which reached the largest number of indifferent white readers. 

We were not advertising in order to reward our friends or punish our enemies but in order to send our message to those who ought to have it. We therefore picked our advertising media with just one aim in mind: how many people can we reach not familiar with the facts about lynching? 

We reached at least five million readers in a day---the greatest single stroke of propaganda ever struck in behalf of justice for the Negro. The Bill was not passed but the effect of this advertisement is beyond estimate. It was copied all over the United States and in Europe, Asia and Africa.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Our Economic Future (1928)](/Volumes/35/05/our_economic_future.html)
* [Travel (1926)](/Volumes/33/02/travel.html)
* [White Charity (1922)](/Volumes/24/02/whitecharity.html)
* [Negro Art (1921)](/Volumes/22/02/negro_art.html)
* [Our Economic Peril (1930)](/Volumes/37/03/our_economic_peril.html)

<!-- Similar articles end here -->