
---
title: 'Homicides'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 23
  issue: 5
  page: 200-201
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


There is a species of propaganda going on against the Negro which is so subtle that most people do not notice it. For instance, *The Spectator*, an insurance magazine periodical, records from year to year all homicides,---that is all persons killed in the United States by criminal violence. It notes that for every million of population in 31 cities there are 85 homicides and that the rate is increasing. 

Then the statement, which is written by Frederick L. Hoffman, goes on to say (the italics are ours): "*Furthermore, it will be noted that the cities experiencing the highest rates are those having a large colored population.*" And comparing North and South, he says that the homicide rate among the whites in the South "is but little higher than for the New England and Middle Atlantic States and below that for the West. *For the colored race the incidence is shown to be four times as frequent as among the whites in the South.*" 

Now what is the inference that any number of papers quoting this passage have made? It is that the Negro is a murderer and causes the great murder rate in the South. And yet as a matter of fact, what is the truth? The truth is that the Negro is MURDERED four times as fast as the whites and that the unfortunate preëminence of the South in murder is because there are so many black folk there to be killed. 

In other words, a fact which is to the shame of the white race and pitiable for the colored race, is, we had almost said, deliberately so stated that nine people out of ten in the United States have twisted the facts to the discredit of the black South. 

<span class="small-caps">The Crisis</span> itself was so puzzled at the figures that it wrote Mr. Hoffman to be certain, and received from him a letter confirming the fact: "The term homicide as used in my articles … is strictly limited to deaths from homicide." He also adds: "I have always stood clearly upon the position that it was immaterial whether the persons killed were white or colored. The Negro's life economically as well as socially is as valuable and as worthy as that of a white man." All of which sounds very well and yet Mr. Hoffman has allowed an ambiguous statement to go out under his signature, and he may still be counted as he was when he published that vicious book "Race Traits and Tendencies of the American Negro,"---as one of the most persistent and subtle enemies of the Negro race.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Murder (1926)](/Volumes/32/03/murder.html)
* [Murder (1914)](/Volumes/09/02/murder.html)
* [Death Rates (1927)](/Volumes/34/08/death_rates.html)
* [Crime (1926)](/Volumes/32/01/crime.html)
* [The Old Story (1911)](/Volumes/01/03/old_story.html)

<!-- Similar articles end here -->