
---
title: 'Gandhi and India'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 23
  issue: 5
  page: 203-207
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


India has been called a land of saints, the home of religions, and, living up to her well earned reputation, she produces in our own time a man who from sheer impeccability of character, and extraordinary personality, and from loftiness and originality of doctrine and ideas, takes rank at once among the great men of the world whose mark is high enough to make for them a permanent niche in the repository of the benefactors of mankind. 

No man who is in the least interested in the throbbing mass of peoples of the earth can fail to take notice of this exceptional soul called forth by a great need and destined to make a significant contribution to the very human effort which man is putting forth to get himself out of the encircling gloom into the promised land. I say "destined," but that is to detract from the glory which already enshrines Mohandas Karamchand Gandhi. I should speak in the present instead of the future tense, for the man about whom I write, not only will be but is indeed he is so vital a factor that  he is called at once the most dangerous yet the most beloved man in India today. 

When Lord Reading, the newly appointed viceroy of India, reached that country, one of his first acts was a long heart to heart talk with Mr. Gandhi. Writing in the London *Nation*, a member of parliament says: 

> The saint, or Mahatma (Gandhi) has India at his feet. The 'intellegentsia' differ from him sometimes in private, rarely in public; property differs from him and trembles; the government---any government differs from him and thinks it is best to---wait. 

To ask who this man Gandhi is, is to ask more than one can properly answer. To many of his Indian countrymen he is Mahatma, or saint, a human being in touch with the divine, to bring relief to the suffering, food to the hungry, and satisfaction to the other physical wants of India; to enthusiastic and idealistic students and members of the educated class, and to many leaders in political life he is the embodiment of a great challenge, which, if answered, must lead out into the possession of not only that which the body needs and must have, but into that indefinable realm of the mind and spirit, the imponderable kingdom of the soul---a possession which may sound very theoretical and impracticable, yet one which is the very stuff that life, and living, human well being, and achievement are made of. 

Mr. Ben Spoor of the British Labor Party, who went to India to represent that organization at the Indian National Congress, writes: 

> The West has produced a Lenin, strong, masterful, relentless alike in logic and method. The East has given birth to a Gandhi, equally strong, masterful and relentless. But whilst the former pins his faith on force, the latter relies on non-resistance. One trusts the sword, the other the spirit. In an extraordinary manner these men appear to incarnate those fundamentally opposing forces that—behind all the surface struggle of our day—are striving for the mastery.

 A learned man of India writes that no one can understand Mr. Gandhi's crusade who does not know Mr. Gandhi. Let us dispose briefly of the common facts of his life and then undertake to see the man as he is. 

Mohandas Karamchand Gandhi was born of an old Bania family, resident in Kathiawar, India, October 2, 1869. Politics appears to be the heritage of his fathers. Through business enterprise they had accumulated some wealth. His mother, an orthodox Hindu lady, rigidly observing religious obligations, performing in the highest manner her duties as wife and mother, could be expected to demand of her children the most desirable qualities of character. From the records one reads, young Gandhi was no disappointment to her. Mohandas Gandhi received his early training in Kathiawar and his final academic instruction in London, where he qualified as a barrister-at-law. It is reported of him during his stay in London, that he was rich and clever, of a cultivated family, gentle and modest in manner. He dressed and behaved like other people. There was nothing particular about him to show that he had taken a Jain vow to abstain from wine, from flesh, and from sexual intercourse. He took his degree and became a successful  lawyer in Bombay, but he cared more for religion than for law. Gradually his asceticism began to show itself. He gave away all his money to good causes, except the most meagre allowance. He took vows of poverty. He gradually ceased a large part of his practice at law because his religion forbade him to take part in a system which tried to do right by violence. 

The beginning of Mr. Gandhi's larger life was in South Africa, whither he had been induced to go in connection with an Indian legal case of some difficulty. It is worth while to relate his first experience after disembarking at the port of Durban in Natal. Brought up in the British tradition of the equality of all British subjects, an honored guest in the capital of the Empire, he found that in the colony of Natal he was regarded as an outcast. When he applied for admission as an advocate of the supreme court of Natal, he was opposed by the law society on the ground that the law did not contemplate that a colored person should practice. Fortunately, the supreme court viewed the matter in another light and granted the application, but Mr. Gandhi received sudden warning of what awaited him in years to come. 

If this was the test of fire through which a great man was to pass, it was certainly not a fire which consumed, but rather one which kindled all the nobler qualities of his soul, and sent him forth purged of whatever dross he may have had---Mahatma Gandhi, both feared and loved. Professor Gilbert Murray, writing in the *Hibbert Journal*, relates the significant part of Mr. Gandhi's South African experience: 

> In South Africa, there are some 150,000 Indians, chiefly in Natal, and the South African government, feeling that the color question in its territories was quite sufficiently difficult already, determined to prevent the immigration of any more Indians and if possible to expel those who were already there. This could not be done. It violated a treaty; it was opposed by Natal, where much of the industry depended on Indian labor; and it was objected to by the Indian government and the home government. Then began a long struggle. The whites of South Africa determined to make life in South Africa undesirable, if not for all Indians, at least for all Indians above the coolie class. Indians were specially taxed; were made to register in a degrading way; their thumb prints were taken by the police as if they were criminals. If, owing to the scruples of the government, the law was in any case too lenient, patriotic mobs undertook to remedy the defect. Quite early in the struggle the Indians in South Africa asked Mr. Gandhi to come and help them. He came as a barrister in 1893; he was forbidden to plead; he proved his right to plead; he won his case against the Asiatic Exclusion Act on grounds of constitutional law and returned to India. <p>Gandhi came again in 1895. He was almost mobbed and nearly killed at Durban. I will not tell in detail how he settled down eventually in South Africa as a leader and counsellor to his people; how he began a settlement in the country outside Durban where the workers should live directly on the land and be bound by a vow of poverty. For many years he was engaged in constant passive resistance to the government and constant efforts to raise and ennoble the inward life of the Indian community. But he was unlike other strikers or resisters in this: that mostly the resister takes advantage of any difficulty of the government in order to press his claim the harder. Mr. Gandhi, when the government was in any difficulty that he thought serious, always relaxed his resistance and offered help. In 1899 came the Boer War. Gandhi immediately organized an Indian Red Cross Unit. There arose a popular movement for refusing it and treating it as seditious. But it was needed. The soldiers wanted it; it served throughout the war, and was mentioned in dispatches and thanked publicly for its skillful work and courage under fire. In 1904 there was an outbreak of plague in Johannesburg, and Mr. Gandhi had a private hospital opened before the government had begun to act. In 1906 there was a native rebellion in Natal. Gandhi raised and personally led a corps of stretcher bearers whose work seems to have proved particularly dangerous and painful. Gandhi was thanked by the governor of Natal and shortly afterward thrown in jail in Johannesburg.<p> Lastly, in 1913, when he was being repeatedly thrown into prison among prisoners of the lowest class and his followers in jail were to the number of 2,500; in the very midst of the general strike of Indians in the Transvaal and in Natal, there occurred the sudden and dangerous strike which endangered for a time the very existence of the organized society in South Africa. From the ordinary agitator's point of view, the game was in Gandhi's hands. He had only to strike his hardest. Instead, he gave orders for his people to resume work until the government should be safe again, I cannot say how often he was imprisoned, how often mobbed and assaulted, and what pains were taken to mortify and humiliate him in public. But by 1913 the Indian case had been taken up by Lord Hardinge and the government of India. An imperial commission reported in his favor on most of the points at issue and an act was passed entitled the Indian Relief Act.

Manifestly, a man of such lofty ideals, so perfectly displayed in practice is bound to exert no small influence in a country like India at this period of her life. In order to understand the man himself in relation to his country it is perhaps necessary to observe a few facts of the political history of India. 

India was the contemporary of great Egypt, ancient Assyria and Persia, but unlike her contemporaries of antiquity, she lives. They are dead. Through a continuous period running back to most archaic times, she has come with her literature, her religions, her customs---in short---with all that makes her justly proud today. One could go on and state what has become the classic theme of the demands of contemporary India. We cannot consider here the interesting facts of her kingdoms and empires, her wars and warriors, of which the Mahabharata so gloriously sings; nor of the coming of Islam and the great empires of the Moguls. It is certainly not possible to write here of Indian society----of caste; of poverty widespread and dazzling wealth; of the depth of illiteracy which grips the country octopus-like and a culture and education as noted for their literary and scholarly achievements as for their far reach back into the haze of unhistorical days; of marriage, home, and the family. 

India has for centuries been a land much desired by Europe. Every school boy remembers that it was this land that Columbus sought in 1492. The immense wealth of that country as it lured on the bold discoverer of America, in the same way was the object of expeditions of the Portuguese, Dutch, French, Austrians and Germans. The tragic results of their seeking, both to themselves and to India, form interesting yet harrowing reading. Intrigue, murder, robbery---wholesale pillage---all for the wealth of the Indies! 

In 1600 Queen Elizabeth granted a charter to what became known later as the East India Company. This company established in India trading-posts and settlements and built forts to protect its ports and settlements. It sent out governors and a governor-general and when it applied at London for charters and courts of justice, it got charters and courts of justice; then follows the sordid yet romantic periods of Warren Hastings, Lord Clive and others (see Macaulay and Burke), until the East India Company ceased to exist in the Sepoy War of 1857 and the British crown assumed the sovereignty of this country and its millions in 1858. Upon and out of this more than half-century of foreign rule, a rule of which one reads great good and much evil, comes what is today termed "Indian unrest," and upon the very crest of this wave Mohandas Karamchand Gandhi occupies his position. 

These 315,000,000 people, largely poor and illiterate, though with a highly cultured and educated leadership, what is it they want and in what is it that Gandhi is for many of them the spokesman? In the past the leaders have with their might protested against a bureaucratic government vested in a foreign civil service. Indian national gatherings of the past have recommended again and again that "measures be taken by government to organize and develop Indian industries," and also "that invidious distinctions here and abroad between his Majesty's Indian and other subjects be removed by redeeming pledges of provincial autonomy and recognizing India as a component part of a federated empire. At the December meeting of the National Liberal Federation the Hon. Mr. Srinivasa Sastri moved that in the opinion of the Federation, the inauguration of the new régime conferring a measure of self-government on the people of India must be signalized by a comprehensive measure abolishing all distinctions in law based merely on the race of an individual, and urged in particular that provisions in the criminal law of India conferring upon Europeans and Americans certain privileges and rights must be repealed at an early date." 

One could mention an almost unending list of complaints, demands, memorials and resolutions. Each year it appears the leaders of the people have become more bold and have given increased expression to their larger and national aspiration. A demand granted has only served to reveal their miserable weakness and the mighty strength of the power that granted it. Thus has a new state of mind come upon this country almost with the suddenness of the dawn of day but with the same surety of travel and background as that upon which dawn depends. Instead of a half loaf, the whole is desired. The same sort of patience is no longer advocated and a conditional loyalty to the British Empire is preached. 

Without doubt the war primarily and other subsequent developments have given the immediate impetus to the rising tide of new and popular thought. But it is possible for almost every Indian to name specifically definite overt acts and administrative measures which led an erstwhile patient and philosophic people into a state which an unfriendly reporter characterizes as "an atmosphere surcharged with heat and an horizon obscured by smoke screens of racial passion." Of the overt acts, the one which touched the very quick of the people's heart, was the Amritsar massacre whereby several hundred Indian men, women and children were shot dead under the order of a British general and hundreds of others were left wounded. And this because these unarmed people refused to obey the order of the British general to disperse! 

In the second place, the Moslems of India are dissatisfied over the turn events have taken during the past three years which, they claim, humiliate Islam and completely subjugates the Mohammedan world to the Christian. Their deepest feelings are stirred over what is to them a studied insult to their religion. The very heart of India's racial self-respect is stirred. But behind these two questions just referred to the New Republic states: "There is a greater and all embracing one, that of national wrong and shame of which every Indian is sensitive." 

Upon a governmental report on the Amritsar massacre. Mr. Gandhi writes: "The condonation of the Punjab atrocities has completely shattered my faith in the good intentions of the government and the nation supporting it." Writing on "the situation and the remedy," Mr. G. A. Natesan, an Indian, finishes with the remark, "The people of India have lost faith in British justice." 

Thus begins the newer attitude of Indian leaders towards Britain! New terms, or rather old terms with new meanings are now the order of the day. *Swaraj*, non-coöperation, non-violence, and Gandhism, are the terms which have turned the eyes of the world upon the man responsible for their use, and have won for him the devoted following of great masses of his own people. 

At the 35th session of the Indian National Congress, held at Nagpur, India, in December, 1920, Mr. Gandhi moved in the open Congress: "That the object of this Congress is the attainment of *Swaraj* by all legitimate and peaceful ends." The motion was opposed, but it was carried with a large majority and by its passage it made Mr. Gandhi the most powerful man in the Congress. Mr. Gandhi explains what is meant by Swaraj, or home rule or national rule as follows: 

> *Swaraj* means a state such that we can maintain our separate existence without the presence of the English. If it is to be a partnership, it must be a partnership at will. There can be no Swaraj without our feeling and being the equals of Englishmen. Today we feel that we are dependent upon them for our internal and external security, for our armed peace between Hindus and Mussulmans for our education, and for the supply of our daily wants. The Rajahs are dependent upon the British for their power, and the millionaires for their millions. The British know our helplessness … to get *Swaraj* then is to get rid of our helplessness.

But how is this great miracle to be wrought in India? Non-coöperation is the war-cry of Mr. Gandhi's non-violent crusade. It is his first and most powerful weapon. This is the general scheme of the principle of non-coöperation as proposed by the Indian National Congress: 

1. Giving up of all British titles and honorary offices 
2. Boycott of all official functions 
3. Withdrawal of all students from all government owned or aided schools, and the establishment of Indian National schools 
4. Boycott of British courts by Indian lawyers and litigants and the establishment of private courts of arbitration 
5. Refusal of Indians to be candidates for the new assemblies and the total abstinence from all voting 
6. Boycott of English-made goods. 

In commenting on the effectiveness of non-coöperation in Mr. Gandhi's program, Mr. B. K. Roy, a Hindu, writes in the *Independent*: 

> Mr. Gandhi has fired the imaginations of the people, and the non-coöperation movement is meeting with tremendous success. Many titleholders like Rabindranath Tagore have given up their titles. Women like Sarajina Neidee and Sarala Devi have given back their medals of honor for war-service, thousands of students have left British colleges and national institutions are being established.

The second outstanding factor in Mr. Gandhi's program is the idea and practice of non-violence or passive resistance. Like the principle of non-coöperation, it kills without striking its adversary. More than that, it disarms its enemies. 

Behold a man who has ancient and great India at his feet; whom a powerful government is afraid to arrest; who causes visiting members of royalty to be snubbed; who threatens as a last resort to lead his people in an anti-tax paying crusade, thus striking at the very root of government; a man who professes to love his enemies and who refuses to take advantage of or embarrass government in a crisis! 

