
---
title: 'Public Schools'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 1
  page: 32
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Our good friend, the decrepit Charleston *News and Courier* says: "DuBois would like to employ the schools for breaking down social lines, and that is a dream which will never be realized." If this is true then the public schools are a failure. For the business of the public schools, always recognized from the beginning, has been to break down social lines, to do away with silly distinctions not based on individual work, to be the melting pot out of which comes the great and dreamed of democracy. Of course the South opposes it because it opposes democracy. Of course the bourbon *Courier* waves its "nevers" and always has. Slavery would "never" be abolished, the Negro would "never" be educated, black men would "never" vote, and so on down through the whole gamut by those who, not contented to legislate and plan for time, are determined to arrange for eternity. As a matter of fact there is a determined attempt in the South to make the public school system so far as Negroes are concerned a method of training servants for the bourbon rich, and these same people are precisely the folk who have no business to have servants because they never have known and never will know apparently how to treat human beings.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Public Schools (1916)](/Volumes/12/01/public_schools.html)
* [Education (1911)](/Volumes/01/04/education.html)
* [The Negro Public School (1916)](/Volumes/11/05/negro_public_school.html)
* [Schools (1917)](/Volumes/13/03/schools.html)
* [School (1918)](/Volumes/16/06/school.html)

<!-- Similar articles end here -->