---
title: 'To the Rescue'
description: "In The Crisis (1916) W.E.B. Du Bois criticizes U.S. policy as Black troops fight to defend white liberties abroad, urging race-based self-defense and rights."
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: May 1916
categories: []
subjects:
  - African American military service
  - Military discrimination against African Americans
  - Armed self-defense (African Americans)
  - U.S. military intervention in Mexico (1916)
  - Civil rights of African Americans
people:
  - W. E. B. Du Bois
  - Woodrow Wilson
places:
  - Mexico
  - United States
  - Africa
organizations:
  - Tenth Cavalry (United States Army)
  - Twenty-fourth Infantry Regiment (United States Army)
  - Wilson administration
events:
  - Punitive Expedition into Mexico / Pancho Villa Expedition (1916)
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 12
  issue: 1
  page: 31
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

The colored troops are leading in the Mexican foray. It is a foolish venture. Just the kind of mistake that we are beginning to think is characteristic of the Wilson administration. Nevertheless "Theirs not to reason why," and consequently the Tenth Cavalry with Major Young in command of the Second Squadron is now in Mexico. As one report says: "Especial credit should be given the Tenth." Then, too, the Twenty-fourth, another colored regiment, has been called to support the movement. So in America, in Europe and in Africa black men are fighting for the liberties of white men and pulling their chestnuts out of the fire. One of these bright mornings black men are going to learn how to fight for themselves.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Officers (1917)](/Volumes/14/02/officers.html)
* [The Negro Soldier (1919)](/Volumes/19/02/negro_soldier.html)
* [The Present (1917)](/Volumes/14/04/present.html)
* [Soldiers (1920)](/Volumes/20/03/soldiers.html)
* [Soldiers (1919)](/Volumes/17/01/soldiers.html)

<!-- Similar articles end here -->