
---
title: 'Education'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 3
  page: 132-133, 136
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




## The Persistent Onslaught

The quiet insidious persistent attempt to keep the mass of the Negroes in America in just sufficient ignorance to render them incapable of realizing their power or resisting the position of inferiority into which the bulk of the nation is determined to thrust them was never stronger than to-day. Let us not be deceived. It is true that our illiteracy has decreased enormously and is decreasing and that the number of our children reported to be in school is larger than ever before. At the same time our illiteracy has not decreased as quickly as it might have and it is doubtful if the proportion of our population in school is as large to-day as it was ten or twenty years ago. As a race we are still kept in ignorance far below the average standard of this nation and of the present age, and the ideals set before our children in most cases are far below their possibilities and reasonable promise.

This is true not by accident but by design, and by the design not so much of the laboring white masses of the nation but rather by the design of rich and intelligent people, and particularly by those who masquerade as the Negroes' "friends." Their attack on real education for Negroes is in reality one with their attack on education for working men in general and this is part of the great modern attack upon democracy.

Of course, this movement masquerades as industrial and vocational training in an age which is preeminently industrial and busy. It is thus difficult for the average colored man to descry its persistent and tremendous dangers to our ultimate survival as a race and as American citizens.

## The Basic Injustice

 No one denies that beneath the basic demand for industrial and vocational training lies truth and fundamental truth, but that on this truth is being built to-day a superstructure of falsehood and injustice also too clear to the thinker. It is the duty of all men to work and this work usually renders a service to the community for which the community is willing to pay with services and materials in return. Sometimes, to be sure, the community does not recognize the value of valuable work; sometimes it pays ridiculous pittances for work of the very highest value and unfitted thereby from continuing his education at any recognized modern in-on the other hand it again and again pays extortionate returns for services that are negligible or even absolute disservice. Nevertheless the average man must be trained for work which the average community will reward with a living wage. In these days of intricate technique such training cannot be acquired by chance or as a side issue or as an after thought. It must form an integral part of every person's education. "Therefore," says the principal of the school with the largest Negro attendance in Harlem, "I am going to train these Negroes as cooks and gardeners."

## The Basic Fallacy

But wait; is work the object of life or is life the object of work? Are men to earn a living or simply to live for the sake of working? Is there any justice in making a particular body of men the drudges of society, destined for the worst work under the worst conditions and at the lowest pay, simply because a majority of their fellow men for more or less indefinite and superficial reasons do not like them? Manifestly life, and abundant life, is the object of industry and we teach men to earn a living in order that their industry may administer to their own lives and the lives of their fellows. If, therefore, any human being has large ability it is not only for his advantage but for the advantage of all society that he be put to the work that he can do best. To assume that ability is to be measured by so-called racial characteristics---by color, by hair or by stature is not only ridiculous but dangerous. To-day we can afford to look carefully day are for men and not men for machines, while on the other hand because of the mechanical and industrial age through which we have passed there is grave lack of deep intelligence and character. While then we teach men to earn a living, that teaching is incidental and subordinate to the larger training of intelligence in human beings and to the largest development of self-realization in men. Those who would deny this to the Negro race are enemies of mankind.

## The Result

The result of limiting the education of Negroes under the mask of fitting them for work is the slow strangulation of the Negro college. Howard to-day is dependent upon the precarious support of the majority in Congress; Fisk has an endowment which looks ridiculous beside that of Hampton and Tuskegee. Atlanta has almost no endowment. None of the five major Negro colleges have today any solid financial prospect for growth and development. Not only that but they are regularly sneered at by men who dare not raise their arguments above a sneer. We hear again and again repeated the usual lie that these colleges are persisting in the curriculum of fifty years ago. As a matter of fact practically all of these colleges are conforming to the standard of education as laid down by the highest authorities in this country. What they are really asked to do is to adopt a course of study which does not conform to modern standards, which no modern system of education will recognize and which condemns the student who takes it to end his education in a blind alley. It is the unforgivable sin of some of the greatest so-called industrial schools that the boy who is induced to take their course is absolutely unfitted thereby from continuing his education at a recognized modern institution. This is a crime against childhood for which any nation ought to be ashamed.

Who are the men who are planning the new Negro curriculum? Are they educational experts learned in the theory and practise of training youth? No, most of them never taught a child or held any responsible place in a school system or gave the subject any serious study. Are they friends of the Negro desiring his best interests and development? No, they are friends of the white South and stand openly committed to any demand of the white South.

The latest attack on Negro education comes from Philadelphia. Very adroitly and cunningly the Negroes have been massed in segregated schools. Now "industrial training" is to be introduced *in the Negro schools* and a representative of a leading southern industrial school is on hand to advise!

Do Negroes oppose this because they are ashamed of having their children trained to work? Certainly not. But they know that if their children are compelled to cook and sew when they ought to be learning to read, write and cipher, they will not be able to enter the high school or go to college as the white children are doing. It is a deliberate despicable attempt to throttle the Negro child before he knows enough to protest.

## The Excuse

 Even in industrial training the white authorities are persistently dishonest. They will not train our children in good paying trades and respectable vocations. They want them to be servants and menials. The excuse which is continually brought forward, particularly in the North, is that there is "no opening" for them in the higher ranges of the industrial world! For this reason opportunities even for the best industrial training are persistently denied colored students. Trade schools in many of the large cities have the habit of forcing colored students who apply into the courses for domestic service or sewing on the plea that millinery, carpentry and various lines of mechanical work offer no opportunity for colored folk. Surely this reduces the argument for industrial training to rank absurdity and the cause of real, honest industrial training deserves more sensible treatment than this.

## Our Attitude

In all these arguments and actions there blazes one great and shining light: the persistent army of Negro boys and girls pushing through high school and college continues to increase. Negro mothers and fathers are not being entirely deceived. They know that intelligence and self-development are the only means by which the Negro is to win his way in the modern world. They persist in pushing their children on through the highest courses. May they always continue to do so; and may the bright, fine faces on these pages be inspiration to thousands of other boys and girls in the coming years to resist the contemptible temptation so persistently laid before this race to train its children simply as menials and scavengers.

______
*Citation:* Du Bois, W.E.B. 1915. "Education." *The Crisis*. 10(3):132&ndash;133, 136.
<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Education (1911)](/Volumes/01/04/education.html)
* [Education (1911)](/Volumes/02/02/education.html)
* [Employment (1932)](/Volumes/39/09/employment.html)
* [Segregation (1910)](/Volumes/01/01/Segregation.html)
* [Reconstruction (1919)](/Volumes/18/03/reconstruction.html)

<!-- Similar articles end here -->