
---
title: 'Crime and Lynching'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 3
  page: 113-114
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



A favorite argument with shallow thinkers is: Stop
crime and lynching will cease. Such a statement is both historically and logically false. Historically, lynching leads to lynching, burning to burning; and lynching for great crimes to lynching for trivial offenses. Moreover, lynching as practised today in the Uited States is not the result of crime---it is a cause of crime, on account of the flagrant, awful injustice it inflicts in so many cases on innocent men. Take, for instance, the story of the lynching in Florida, as told by Governor Gilchrist. He says, in answer to a correspondent:

> As to the "black brute who received his deserts," I would state that I examined the evidence in this case. A certain man. accompanied by three others---all white---drove from a quarter to a half mile from the main road through the place of an old Negro, using an old road. This old Negro had five sons and sons-in-law living in his immediate vicinity. That morning there had been some lawsuit with one of these Negroes, the case having been tried at Mickosukie. The Negroes had returned to their home. This certain man and party drove through the old Negro's place. The old Negro opened the gate so they could drive through his place, going toward the public road. This certain man and the others got out of their buggies and returned to the gate. This man had a pistol in his hand, and commenced talking to the old darkey, more or less threatening him. All the evidence shows, and what I have heard of him, through white people, shows that he was a harmless old darkey. The old Negro ran. Shots were fired at him. Knowing there had been a lawsuit that day, and doubtless seeing this man and party driving through the field, this old Negro's sons and sons-in-law, on hearing the report of shots, naturally came to his house. The old Negro had a son who was sick and lying---my recollection is---on the porch. This man was talking to the sick son in front of the porch with his pistol in his hand, raising his arm up and down apparently as though he was going to shoot him. It appears, however, that it was probably not the intention of this man to shoot this darkey. In running up to the house, one of the old man's sons or sons-in-law, seeing this man with the pistol in his hand, and his arm up, shot this man in the side under the arm. He died instantly. This occurred within a few feet of the cabin of the old Negro. The old Negro and his five sons and sons-in-law were taken to jail and were sent to Lake City for safe keeping. A party of lynchers, with a forged telegram from the Governor, secured the Negroes from the jail under pretext of taking them to Jacksonville, claiming they were protecting them from a lynching party. The Negroes were bound, taken out on the edge of the town and shot to death.

What now must be the feeling of the Negroes thereabouts? Are they appalled at their own wickedness? Do they see that the wages of sin is death? Not they. They despise the white man's justice, hate him, and whenever they hear of Negro "crime" in the future they will say: "It's a white man's lie."

Not only this, but these people know how criminals are made and they pity rather than condemn them. Take, for instance, the cries throughout the South against "vagrants." It means the call for the State enslavement of
any man who does not work for a white man at the white man's price. The most outrageous laws and arrests are made under the excuse of vagrancy. In Atlanta, on October 15, thirty-seven laborers were arrested at night in their lodging house as "vagrants." In Texas five laborers were arrested as vagrants and proved their hard, steady jobs. "But," remarks the *Galveston Tribune* chirpily:

> The State chose to prosecute under a different portion of the law, alleging loitering about houses of ill-fame. The court explained, as he has done before, that a person can be a vagrant yet be steadily employed, the law being general in its effect and covering many points upon which a conviction can be had on a charge of vagrancy.

Suppose now a mischievous boy or a loiterer or a laborer out of work is thrown into jail as a vagrant, what happens to him?

From a thousand examples, let us choose but one from a Texas report on a local "chain gang":

> The day's program was invariably this: Up at 4:30 o'clock in the morning, trot two to five miles to the cane fields, work there in squads until noon, when fifteen to twenty minutes would be allowed for the eating of a cold dinner; driven hard during the afternoon and brought back by starlight at night in the same dog trot they went out in the morning. The weak must keep up with the strong in his work or be punished. Convicts slept in their underclothes or naked, as it happened to rain or shine during the day. If it rained they hung up their clothes to dry' and slept without. One convict testified that he had frequently taken his clothes from the nail frozen stiff. One man was on a farm a year, and during that time the bedclothes were not washed and were sunned but twice.

Thus desperate criminals are manufactured and turned out day by day.

Can we stop this by lynching? No. The first step toward stopping crime is to stop lynching. The next step is to treat black men like human beings.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Lynching (1927)](/Volumes/33/04/lynching.html)
* [Lynching (1914)](/Volumes/07/05/lynching.html)
* [Lynching (1926)](/Volumes/32/01/lynching.html)
* [Lynching (1928)](/Volumes/35/09/lynching.html)
* [Causes of Lynching (1931)](/Volumes/38/04/causes_of_lynching.html)

<!-- Similar articles end here -->