
---
title: 'A Mild Suggestion'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 3
  issue: 3
  page: 115-116
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The were sitting on the leeward deck of the vessel and the colored man was there with his usual look of unconcern, before the seasickness his presence aboard had caused some upheaval. The Woman, for instance, glancing at the Southerner, had refused point blank to sit beside him at meals, so she had changed places with the Little Old Lady. The Westerner, who sat opposite, said he did not care a ------,
then he looked at the Little Old Lady, and added in a lower voice to the New Yorker that there was no accounting for tastes. The Southerner from the other table broadened his back and tried to express with his shoulders both ancestors and hauteur. All this, however, was half forgotten during the seasickness, and the Woman sat beside the colored man for a full half hour before she noticed it. and then was glad to realize that the Southerner was too sick to see. Now again with sunshine and smiling weather, they all quite naturally reverted (did the Southerner suggest it?) to the Negro problem. The usual solutions had been suggested: education, work, emigration. etc.

They had not noticed the back of the colored man, until the thoughtless Westerner turned toward him and said breezily: "Well, now, what do you say? I guess you are rather interested." The colored man was leaning over the rail and about to light his cigarette---he had several such bad habits, as the Little Old Lady noticed. The Southerner simply stared. Over the face of the colored man went the shadow of several expressions; some the New Yorker could interpret, others he could not.

"I have," said the colored man, with deliberation, "a perfect solution." The Southerner selected a look of disdain from his repertoire, and assumed it. The Woman moved nearer, but partly turned her back. The Westerner and the Little Old Lady sat down. "Yes," repeated the colored man. "I have a perfect solution. The trouble with most of the solutions which are
generally suggested is that they aggravate the disease." The Southerner could not help looking interested. "For instance," proceeded the colored man, airily waving his hand, "take education; education means ambition, dissatisfaction and revolt. You cannot both educate people and hold them down."

"Then stop educating them," growled the Southerner aside.

"Or," continued the colored man. "if the black man works, he must come into competition with whites------"

"He sure will, and it ought to be stopped," returned the Westerner. "It brings down wages."

"Precisely," said the speaker, "and if by underselling the labor market he develops a few millionaires, how now would you protect your residential districts or your select social circles or---your daughters?"

The Southerner started angrily, but the colored man was continuing placidly with a far-off look in his eyes. "Now, migration is both costly and inhuman; the transportation would be the smallest matter. You must buy up perhaps a thousand millions' worth of Negro property; you must furnish some capital for the masses of poor; you must get some place for them to go; you must protect them there, and here you must pay not only higher wages to white men, but still higher on account of the labor scarcity. Meantime, the Negroes suddenly removed from one climate and social system to another climate and utterly new conditions would die in droves---it would be simply prolonged murder at enormous cost."

"Very well," continued the colored man, seating himself and throwing away his cigarette, "listen to my plan." looking almost quizzically at the Little Old Lady: "you must not be alarmed at its severity---it may seem radical, but really it is---it is---well, it is quite the only practical thing and it has surely one advantage: it settles the problem once, suddenly, and forever. My plan is this: "S ou now outnumber us nearly ten to one. I propose that on a certain date, shall we say next Christmas,
or possibly Easter, 1912? No, come to think of it, the first of January, 1913, would, for historical reasons, probably be best. Well, then, on the first of January, 1913, let each person who has a colored friend invite him to dinner. This would take care of a few; among such friends might be included the black mammies and faithful old servants of the South; in this way we could get together quite a number. Then those who have not the pleasure of black friends might arrange for meetings, especially in 'white' churches and Young Men's and Young Women's Christian Associations, where Negroes are not expected. At such meetings, contrary to custom, the black people should not be seated by themselves, but distributed very carefully among the whites. The remaining Negroes who could not be flattered or attracted by these invitations should be induced to assemble among themselves at their own churches or at little parties and house warmings."

"The few stragglers, vagrants and wanderers could be put under careful watch and ward. Now, then, we have the thing in shape. First, the hosts of those invited to dine should provide themselves with a sufficient quantity of cyanide of potassium, placing it carefully in the proper cups, and being careful not to mix the cups. Those at church and prayer meeting could choose between long sharp stilettoes and pistols---I should recommend the former as less noisy. Those who guard the colored assemblies and the stragglers without should carefully surround the groups and use Winchesters. Then, at a given signal, let the colored folk of the United States be
quietly dispatched; the signal might be a church bell or the singing of the national hymn; probably the bell would be best, for the diners would be eating."

By this time the auditors of the colored man were staring; the Southerner had forgotten to pose; the Woman had forgotten to watch the Southerner; the Westerner was staring with admiration; there were tears in the eyes of the Little Old Lady, while the New Yorker was smiling; but the colored man held up a deprecating hand: "Now don't prejudge my plan," he urged. "The next morning there would be ten million funerals, and therefore no Negro problem. Think how quietly the thing would be settled; no more bother, no more argument; the whole country united and happy. Even the Negroes would be a great deal happier than they are at present. Instead of being made heirs to hope by education, or ambitious by wealth, or exiled invalids on the fever coast, they would all be happily ensconced in Heaven. Of course, I admit that at first the plan may seem a little abrupt and cruel, and yet is it more cruel than present conditions, and would it not be well to be a little more abrupt in our social solutions? At any rate think it over," and the colored man dropped lazily into his steamer chair and felt for another cigarette.

The crowd slowly dispersed: the Southerner chose the Woman, but was heard to say something about fools. The Westerner turned to the New Yorker and said: "Now, what in hell do you suppose that darky meant?" But the Little Old Lady went silently to her cabin.

