
---
title: 'Murder'
author: Du Bois, W.E.B.
date: Jan. 1926
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 32
  issue: 3
  page: 112
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Few Americans realize how many homicides take place in the United States. During 1925, 10,100 murders were done in this country and our murder rate is 14 times the murder rate in England. There were more murders in Chicago last year with its population of 3,000,000 than took place in England and Wales with a population of 40,000,000. Our rate is six times the rate of Canada. In the South, and especially in Southern cities like Memphis, the murder rate is worse than the rate in Chicago. Life is cheap in the United States because we despise our neighbors, and we do not greatly care who is killed if it is not one of us or one of our friends. We have been killing Negroes, Italians, Hungarians, Indians and what not with such impunity that the habit of killing has grown upon us. In the South it is a species of public amusement to which certain back districts and city slums are regularly treated. Lynching is, of course, but one phase of this widespread phenomenon. War and Militarism contribute the state of mind. We are a nation of murderers.

