
---
title: 'Germany'
author: Du Bois, W.E.B.
date: Feb. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 4
  page: 186-187
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Someone writes to ask what the effect on the Negro will be if Germany should triumph in the present war. We do not for a moment pretend that the German people are ogres and the Allies saints, but we confess that based on unchallenged records there can be no doubt that Germany's attitude toward colored races is indefensible.

Lewis R. Freeman says in the *World's Work:* 

> In Damaraland between the years 1904 and 1907 as the consequence of the killing of a single child the Germans wantonly did to death 30,000 Hereros, a simple pastoral tribe of scant fighting capacity. Never since Nero and Attila had there been a parallel to Von Trotha's infamous order of extermination.    
> &nbsp;
> 'Within German borders' read the proclamation of this Teutonic barbarian 'every Herero with or without rifle, with or without cattle will be shot. I will take no more women or children. I will drive them back or have them fired on.'    
> &nbsp;
> For several years Germany seemed actually to be trying to make Damaraland a 'white man's country' by killing the blacks. It has reaped in failure the logical harvest of this sowing of brutality.

On the other hand the New York *Nation* has an article that tells us of the peculiar affection of the colored races for France:

> The brilliant success of the French in handling such soldiers is largely due to something entirely wanting to Germans in their dealings with subordinate races. It is something which even the Englishman's fair play does not altogether supply. It is the hand-to-hand comradeship of officers and men.

Small wonder that a black and wounded Senegalese writes from the hospital: 

> Next spring we blacks will give our lives again and show we are worthy to fight beside our white brothers for the defense of France. If I have been able to be somebody in my country, it is owing to the lessons of my French masters.

