
---
title: 'Lies Agreed Upon'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 4
  page: 187
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



To many men history is a matter of convention and prejudice. *Current Literature,* for instance, succeeds in writing two whole pages on "rag-time" without mentioning the Negro race. A Connecticut paper makes Coleridge-Taylor an Australian. Hundreds of men of Negro blood have had their achievements lost to the race because the matter of their color has been conveniently forgotten since their death. In this way one easily sees what a certain E.S. Cox, a "graduate student" of Vanderbilt University means when he announces jauntily that all human culture has risen from white folk; the colored races have contributed nothing to civilization and when white races become mixed with colored blood they "decline." It is hardly necessary to argue with such a man. One may simply say flatly that the thesis is absolutely false and can only be maintained by claiming as "white" every group and every individual that has given anything to human culture. With this method the Egyptians, the Abyssinians, the East Indians and three-fourths of the African peoples and all of Mediterranean races become "white." Such a definition is nonsense. Civilization started with colored races and colored races and colored men have always been among its greatest standard bearers, the "graduate student" to the contrary notwithstanding.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [Conduct, Not Color (1916)](/Volumes/12/05/conduct_not_color.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Correspondence (1926)](/Volumes/31/05/correspondence.html)

<!-- Similar articles end here -->