
---
title: 'That Capital ''N'''
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Feb. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 4
  page: 184
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


From time to time persons write us for a brief statement of the reasons for capitalizing the word *Negro*.

The ordinary rules of capitalization enjoin the use of a capital letter for all proper nouns, all names of tribes, races, sects or organized bodies of men.

For this reason the word Negro when referring to a race of men has always been capitalized until late in the Nineteenth Century. With the defense of Negro slavery in those days there grew up the custom of using the small letter for the word since Negroes were looked upon as "real estate" or as moveable property like horses, cows, etc.

At the same time the great increase in printing and use of printing machines led to a disuse of capital letters in many cases where they had formerly been used and a great distaste to resorting to them among printers of English. Consequently the rule books used in most printing offices today say that capitals shall be used for the names of all nations and races "except Negro." This has been defended by saying that Negro is not the name of a race but the description of the color of a people, being correlative with white, yellow, etc.

This argument is manifestly false. Black is the correlative of white and Negro does not describe color since all the persons designated as Negroes are by no means black, even in Africa. If,  therefore, we follow analogy we cannot refuse to capitalize Negro when we capitalize Caucasian, Malay, Indian, Chinese, etc. Not to capitalize Negro under such circumstances is a direct, and in these days a more and more conscious, insult to at least 150,000,000 human beings and no person or institution will persist in this insult if they realize that these people regard the usage as such.

*Citation:* Du Bois, W.E.B. 1916. "That Capital 'N.'" *The Crisis*. 11(4):184.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Negro (1914)](/Volumes/09/02/negro.html)
* [That Capital ''N'' (1930)](/Volumes/37/02/that_capital_n.html)
* [The Capital N (1930)](/Volumes/37/05/capital_n.html)
* [Veiled Insults (1914)](/Volumes/07/06/veiled_insults.html)
* [The Name Negro (1928)](/Volumes/35/03/name_negro.html)

<!-- Similar articles end here -->