
---
title: 'Our Book Shelf'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1926
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 31
  issue: 3
  page: 140-141
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



<h2><em>The New Negro</em>, edited by Alain Locke. Albert and Charles Boni, New York, 1925. 446 pages.</h2>

This extraordinary book in many ways marks an epoch. It is in many respects sprawling, illogical, with an open and unashamed lack of unity and continuity, and yet it probably expresses better than any book that has been published in the last ten years the present state of thought and culture among American Negroes and it expresses it so well and so adequately, with such ramification into all phases of thought and attitude, that it is a singularly satisfying and inspiring thing. 

It has, too, more than most books, a history. The well-known magazine, *The Survey*, which represents organized social reform in America, has always been traditionally afraid of the Negro problem and has usually touched it either not at all or gingerly. Even last year one of the editors at a great meeting of social workers in Los Angeles succeeded in talking over an hour on the social problems of America, dividing and examining them exhaustively both geographically and qualitatively, and yet said no word on the race problems.

Notwithstanding this *The Survey* has grown and developed tremendously in the last few years. I remember vividly being asked by *The Survey* to furnish it for the New Year 1914 a statement of the aims of the N.A.A.C.P. I did so and said among other things: 

> Sixth---Finally, in 1914, the Negro must demand his social rights. His right to be treated as a gentleman when he acts like one, to marry any sane, grown person who wants to marry him, and to meet and eat with his friends without being accused of undue assumption or unworthy ambition. 

No sooner had the editors of *The Survey* read this than they telephoned frantically to some of the directors of the N.A.A.C.P. and they found easily several who did not agree with this statement and one indeed who threatened to resign if it were published. *The Survey* therefore refused to publish my statement unless this particular paragraph were excised. The statement was not published. Since then much water has flowed under the bridge and it happened last year that the editor of *The Survey* was sitting next to Mr. A. G. Dill, our business manager, at a dinner given to Miss Fauset in honor of the appearance of her novel, "There Is Confusion." The editor looked at the company with interest and Mr. Dill began to tell him who they were. It occurred to the editor of *The Survey* that here was material for a *Survey Graphic*; still he hesitated and feared the "social uplifters" of the United States with a mighty fear. But he took one step which saved the day: He got a colored man to edit that number of the Graphic, Alain Locke, a former Rhodes scholar and a professor at Howard University. Locke did a good job, so good a job that this Negro number of the *Survey Graphic* was one of the most successful numbers ever issued by *The Survey*. It was a happy thought on the part of the Bonis to have the material thus collected, arranged and expanded, combined with the painting and decoration of Winold Reiss and issued as a book which states and explains the present civilization of black folk in America. Mr. Locke has done a fine piece of editing. The proof reading, the bibliographies and the general arrangement are all beyond criticism. 

With one point alone do I differ with the Editor. Mr. Locke has newly been seized with the idea that Beauty rather than Propaganda should be the object of Negro literature and art. His book proves the falseness of this thesis. This is a book filled and bursting with propaganda but it is propaganda for the most part beautifully and painstakingly done; and it is a grave question if ever in this world in any renaissance there can be a search for disembodied beauty which is not really a passionate effort to do something tangible, accompanied and illumined and made holy by the vision of eternal beauty. 

Of course this involves a controversy as old as the world and much too transcendental for practical purposes, and yet, if Mr. Locke's thesis is insisted on too much it is going to turn the Negro renaissance into decadence. It is the fight for Life and Liberty that is giving birth to Negro literature and art today and when, turning from this fight or ignoring it, the young Negro tries to do pretty things or things that catch the passing fancy of the really unimportant critics and publishers about him, he will find that he has killed the soul of Beauty in his Art. 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Younger Literary Movement (1924)](/Volumes/27/04/younger_movement.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [Socialism and the Negro (1921)](/Volumes/22/06/socialism_and_the_negro.html)
* [Toward a New Racial Philosophy (1933)](/Volumes/40/01/toward_a_new_racial_philosophy.html)
* [Our Book Shelf (1925)](/Volumes/31/01/our_bookshelf.html)

<!-- Similar articles end here -->