
---
title: 'The First Battle of Detroit'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1926
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 31
  issue: 3
  page: 114
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The first Sweet trial is over. By grace of the N.A.A.C.P. instead of eleven persons being railroaded to long penitentiary sentences and some to life imprisonment, there has been a mistrial and every one of the defendants is free on bail. 

This is what comes of fighting. This is what comes of organized intelligence, resistance and cash. There are a lot of people in the United States who one of these days are going to learn that when they touch an American Negro they touch Trouble; that we are a docile, long-suffering people; that we are used to having one cheek roundly slapped but as for that other cheek we are getting tired of presenting it to everybody always. 

In the Sweet trial we owe a great debt of gratitude to Clarence Darrow and we owe absolutely nothing to the white Christian church of Detroit. Walter White, our representative in Detroit, writes: 

> Clarence Darrow was yesterday denounced by the Presbyterian ministers of Detroit because of an address he delivered at the St. Antoine Street Branch of the Y.M.C.A. <p> Mr. Darrow is accused of being an infidel, an agnostic, a disbeliever in Christianity. Yet, he is here defending eleven people who have few friends and I have heard of no single word from any Christian minister of Detroit protesting against the mobbing of Dr. Sweet's home and those of many other self-respecting, lawabiding Negroes here in Detroit. Leaving orthodoxy aside, which action, Mr. Darrow's or the Christian ministers', most nearly coincides with the tenets of Christianity? <p>  Christianity which stops dead at the color line or the dollar mark is a pretty poor religion. The Presbyterian ministry of Detroit might more appropriately have assailed Mr. Darrow's ideas on religion and prohibition if they had, here in Detroit, done some definite thing towards the practice of their vaunted Christianity in the case of Dr. and Mrs. Sweet. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [A Soldier (1920)](/Volumes/19/05/a_soldier.html)
* [The Sweet Trial (1926)](/Volumes/31/03/sweet_trial.html)
* [Courts and Jails (1932)](/Volumes/39/04/courts_and_jails.html)
* [Crime (1920)](/Volumes/19/04/crime.html)
* [Martyrs (1920)](/Volumes/21/02/martyrs.html)

<!-- Similar articles end here -->