
---
title: 'The Sweet Trial'
author: White, Walter F.
date: Jan. 1926
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 31
  issue: 3
  page: 125-129
index: Detroit | Sweet, Ossian | White, Walter F.
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



***The Assistant Secretary of the N.A.A.C.P. "Covered" the Trial of the Negroes of Detroit Who Were Tried for Murder Because They Defended Their Home Against a Mob***



At half-past three in the afternoon of the day before Thanksgiving, Judge Frank Murphy of the Recorder's Court of Detroit finished reading his charge to the jury and turned over to that body for decision the now famous case of The People of the State of Michigan vs. Ossian H. Sweet *et al*.

Seldom in any court has a more impartial, learned or complete charge to a jury been heard. As was evidenced throughout the case, Judge Murphy was exerting every effort at his command to assure to the eleven defendants a completely fair trial. His charge to the jury reached its dramatic climax when in a voice filled with emotion and sincerity, he declared:

 > Dr. Sweet has the same right under the  law to purchase and occupy the dwelling house on Garland Avenue as any other  man. Under the law, a man's house is his castle. It is his castle, whether he is white or black, and no man has the right to assail or invade it. The Negro is now by the Constitution of the United States given full citizenship with the white man and all the rights and privileges of citizenship attend him wherever he goes.



The jury retired. All afternoon and far into the night anxious crowds thronged the court room and the corridors without. From the jury room could be heard the muffled voices of the jury raised in anger but the door remained closed. Shortly after midnight, a message was sent to Judge Murphy asking for further instructions. Out came the jury with haggard faces and listened to Judge Murphy as he re-read the parts of his charge referring to justifiable self-defense.



Back into the jury room filed the twelve men. Again voices were heard in argument. At 2:15 Thanksgiving morning, Judge Murphy summoned the jury to permit them to go to bed. The court room was so crowded that court attendants had to use force in getting enough space in front of the judge's dais to permit the jury to stand. Ninety-five per cent of the crowd was composed of Negroes, hope and fear and apprehension and questioning in their faces, asking if justice could be secured for eleven black defendants in a white man's court and at the hands of a white judge and a white jury.

Early on Thanksgiving morning, the jury resumed its deliberations. All day long the court room remained full, hundreds of people going without Thanksgiving dinner for fear that the jury's verdict might be rendered when they were away eating. Towards midnight of the second day, the jury, yet deadlocked, was allowed to retire.

At 1:30 in the afternoon of November 27th, the jury sent word again to Judge Murphy that there was no hope of their reaching a decision. At the end of forty-six hours of deliberation, Judge Murphy declared a mistrial and thanked and dismissed the jurors.

<p style="text-align:center"> ~~~~~~~~~~~~~~~ </p>

Thus ended the first trial of the case which has stirred Negro America as no other case has ever moved it. Within fifteen years, the Negro population of Detroit has been multiplied by ten, jumping from eight thousand in 1911 to 81,831 by 1925 as a result of the stoppage of immigration from Europe and increased activity on the part of Northern industries. Negroes during and after the war worked in the plants of Detroit, made money and saved it. As has been said many times, it is obvious that eighty-one thousand people cannot live in the homes which housed eight thousand people thirteen years ago. Since 1916 there has been gradual and necessary penetration by Negro home buyers of neighborhoods which hitherto have been occupied by white people. There has been practically no trouble attendant upon these so-called "invasions" until the last year or two. People in Detroit have been so busy earning money that they have not had time to nourish and develop racial or other prejudices. With the exception of a few minor clashes, Detroit has been without doubt one of the fairest cities in the country so far as its treatment of Negroes is concerned.

About two years ago, the Ku Klux Klan started a campaign to capture control of Detroit. This was a part of the movement to gain control of that city and, that purpose gained, make similar efforts to gain control of other Northern cities based upon success in Detroit. Whether a part of that campaign or not, fully ninety per cent of the policemen who have gained positions on the Detroit police force during the past two years have been Southern whites. Charles Bowles, an obscure attorney, was put up as the Klan candidate for Mayor. A little more than a year ago, he secured as the result of Klan support approximately one hundred thousand votes in a mayoralty primary, his name being written in on the ballots. In 1925, he was again a candidate, running against the present incumbent, John W. Smith, who is a Catholic. In the campaign which ended in November, out of approximately a quarter of a million votes, Bowles was defeated by Smith by a narrow margin of about thirty thousand votes.

In order to gain this strength, the Klan has capitalized and stirred up bitter racial and religious animosities. Early in 1925 there began a series of attacks on the homes of Negroes which reached its most serious stage up to that time in the attack last June upon the home of Dr. A. L. Turner, a respected Negro physician of Detroit. Dr. Turner was driven out of his house, forced to sign an agreement to sell his newly acquired home on Spokane Avenue, his furniture smashed, and he and Mrs. Turner attacked by the mob as they drove away.

Practically nothing was done by the police to prevent this attack.



Dr. Ossian H. Sweet, a young Negro physician who is a graduate of Wilberforce and Howard Universities and who has done post-graduate work in pediatrics and gynecology at the Universities of Vienna and Paris, bought a home on Garland Avenue last May. Because of threats against him, Dr. Sweet deferred moving into his new house for two months and a half. He did move in on September 8th, the day after Labor Day. That night a mob gathered but no attack was made on the house. The following evening a larger crowd gathered and stoned the house. In the excitement shots were fired and one member of the mob fell dead and one was wounded.



Police officers, including a deputy superintendent of police, an inspector, a lieutenant, a sergeant, and eight officers, were galvanized into action. They rushed into the house, arrested Dr. Sweet, his wife, Mrs. Gladys B. Sweet, mother of a fourteen months old baby, and nine other occupants of the house. In September, the eleven defendants were given a preliminary hearing before the late Judge John Faust. All were held without bail charged with murder in the first degree.

After remaining in jail for a month, Mrs. Sweet was finally released on bail. In her early twenties, weighing but little more than a hundred pounds, a well educated and intelligent young woman, certain elements in Detroit felt that she was so grave a menace to society that a number of threats were made against the judge for releasing her on bail. From this may be learned the intensity of feeling against the eleven defendants.

The N.A.A.C.P., realizing the very great issue involved and feeling that this case represented the dramatic high point of the nation-wide issue of segregation, entered the case, throwing all of its resources without stint into the defense. If the right of a Negro to defend his home against a mob is to be denied him, the N.A.A.C.P. felt that very grave consequences would follow. It was felt also that a successful defense would serve notice upon members of other mobs that decent white and colored people throughout the country had determined to put an end to the unwarranted attacks which had been made with impunity by other mobs upon the persons and property of Negroes. Again, a completely fair trial to Dr. and Mrs. Sweet and their co-defendants would give hope to Negroes throughout the country that their lot was not as hopeless as it sometimes appears to be.

For these reasons, the N.A.A.C.P. retained the most eminent array of counsel which, according to the general consensus of opinion, had ever been engaged for a trial in any Michigan court. Clarence Darrow of Chicago, generally regarded as the greatest criminal lawyer in America and perhaps in the world, was secured as chief counsel. Mr. Darrow, because of his great interest in the case and because of his broad humanitarianism, agreed to serve at a fee which was approximately one-tenth of what he would ordinarily receive in a case of this magnitude. Mr. Arthur Garfield Hays of New York, one of the eminent criminal attorneys of America who was associated with Mr. Darrow in the famous Evolution Case at Dayton, Tennessee, agreed also to enter the case at a nominal fee. Other attorneys secured were Mr. Walter M. Nelson, a prominent white attorney of Detroit, and Messrs. Julian Perry, Cecil Rowlette and Charles Mahoney, colored attorneys of Detroit. Mr. Herbert J. Friedman of Chicago volunteered his services and assisted in the trial without fee.

The trial began on October 30th. At the very outset, Mr. Hays demanded and secured a Bill of Particulars. Prosecutor Robert M. Toms thereupon filed a Bill which particularized as follows:

> The theory of the people in this case is that the defendants premeditatedly and with malice aforethought, banded themselves together and armed themselves with the common understanding and agreement that one or more of them would shoot to kill, in the event, first, of threatened or actual trespass on the property wherein they were assembled, or, second, of the infliction of any damage, real or threatened, however slight, to the persons or property of them or any of them. Further, that deceased came to his death by a bullet fired by one of the defendants, aided and abetted by all of the others, in furtherance of their common understanding as above set forth. Further, that such understanding and agreement was to commit an unlawful act, to wit, to shoot to kill without legal justification or excuse.

The purpose in demanding this Bill of Particulars was to force the State to confine its testimony to the proving of a specific thing rather than permit the State to Maintain at the conclusion of the trial that it had set out to prove whatever it had happened to prove during the trial.

Through nearly three weeks the State put on its witnesses. Man after man, woman after woman, went on the stand and declared that there were only twelve ~ fifteen people around the Sweet home on the night of September 9th. The contentions of these witnesses as to the number of persons actually present was somewhat amusing inasmuch as the State in filing names and addresses of the witnesses it intended to call listed seventy-one eye-witnesses to the shooting. The purpose of the testimony giving the figures of bystanders at so low a figure can be understood from the fact that the Michigan law provides that a mob consists of "twelve or more persons armed with clubs or other dangerous weapons or of thirty or more persons armed or unarmed."

The State's case began to crumble under the cross-examination of Mr. Darrow and Mr. Hays. For example, Dwight Morrow, a prosecution witness, was asked by Mr. Toms what he saw at Garland and Charlevoix Avenue on the night of September 9th. Morrow answered: "Well, there were---a great number of people and the officers---I won't say a great number---there were a large---there were a few people there and the officers---"

Under cross-examination by Mr. Darrow, this statement was recalled to Morrow's attention. Mr. Darrow asked Morrow:

Q. "You kind of forgot you were to say a few people, didn't you when you started in?"

A. "Yes, Sir" …

Again, Norton Schuknecht, Inspector of Police in charge of the Fifth Precinct, testified that he on the night of September 9th was standing at the corner of Charlevoix and Garland Avenues which location was in his precinct. Inspector Schuknecht testified there were no crowds congregated nor any disturbance but that there were around seventy-five people near Dr. Sweet's house, but he also declared that he had found it necessary to station two traffic officers near the house to divert traffic. Several days later, Deputy Superintendent of Police Sprott testified that he was present also on September 9th, that there were no people around the house, that there were four traffic officers and that he had stationed them there. These are but a few of the many contradictions on the part of prosecution witnesses which were brought out through cross-examination by the defense attorneys. By the time that the prosecution's testimony was in, it was clearly evident that there was a large crowd present and the prosecution itself introduced a number of stones which were taken from the inside and the roof of the Sweet home.

At the close of the prosecution's case, a motion was made by the defense for a directed verdict inasmuch as the State had wholly failed to prove the conspiracy which it had set forth to prove according to its Bill of Particulars. Judge Murphy denied the motion but granted the right to the defense to renew the motion at the conclusion of the presentation of the defense testimony.

Defense witnesses were then placed on the stand. A number of them told of the threats made against Dr. Sweet and Mrs. Smith from whom Dr. Sweet had purchased the house and of the actual attack upon the house. Four colored witnesses, who happened to be driving in the vicinity of the Sweet home on the night in question and who were attacked and beaten by the mob when they unwittingly drove near the Sweet home, told of their experiences.

The dramatic climax of the trial was reached when Dr. Ossian H. Sweet himself was placed on the stand. Over the objection of the prosecution, the entire background of Dr. Sweet was entered into the record. He told of his birth in a small Florida town, of his leaving home at the age of fourteen to go to Wilberforce University, of his arrival there only to find that the Scholarship Fund through which he had hoped to get an education had been exhausted. Simply, directly and convincingly, Dr. Sweet told of his efforts to gain an education. He told of the years he had worked as a bell boy, shoveling snow, waiting table, firing furnaces and at the same time carrying on his studies until he had finished the academic and college courses at Wilberforce. He then related how he had worked his way through Howard University Medical School and, though he was without funds, he had determined to go to Europe and there pursue his studies at the Universities of Vienna and Paris.

He told, too, how during a campaign for funds by the American Hospital at Paris he had given what he could to that hospital---some three hundred francs---a gift which meant certain privations for himself and wife; and then later when he made application for Mrs. Sweet to enter that hospital to give birth to a daughter, how she had been denied admission because of the colored blood within her veins.

Then there were brought out the things which had most definitely influenced Dr. Sweet's mind in its reactions toward American mobs. A race riot a few years ago at Orlando, Florida, where Dr. Sweet was born, in which several colored people were killed and the homes of a number of Negroes burned; of the Tulsa riot in 1921 when Dr. Jackson, eminent Negro surgeon, was shot and killed in cold blood after he had been guaranteed protection by the police force; of the Phillips County, Arkansas, Riots in 1919 when the four Johnson brothers, one of them a physician and another a dentist, had been ambushed through treachery and killed; of the Washington race riots in 1919 when Dr. Sweet had seen a colored man dragged from a street car and beaten to death; of the Chicago race riots of that same year when a cousin of Mrs. Sweet, a police officer, had been forced to go to trial when he in clear self-defense had killed a member of the mob which was attacking him; of the terrible riots at East St. Louis in 1917. All of these things were brought out through adroit questioning to show the state of mind of the eleven Negroes within the house on the night of September 9th at 2905 Garland Avenue, Detroit. As Mr. Darrow pointed out convincingly to the court, the theory of a reasonable man as propounded by the State could not possibly mean in this case the attitude of a white man but must necessarily be that of a Negro with a white mob outside and in the Negro's brain a picture of what similar mobs have done to Negroes during the last sixty years in America.

By the time the case was ready to go to the jury, it was freely predicted throughout Detroit that the case could not possibly end in anything other than acquittal for all eleven defendants. The newspapers of Detroit gave full and impartial reports of the trial, for thirty days featuring the story on the front page. As a result of this impartial reporting, the decent and fair minded element in Detroit had been informed to such an extent that sympathy had swung definitely toward the defendants---a very marked contrast to feeling in the city prior to the entry of the N.A.A.C.P. and Mr. Darrow into the case.

On the other hand, the anti-Negro sentiment, and especially that represented by such organizations as the Ku Klux Klan and the Waterworks Park Improvement Association which had been formed for the purpose of keeping Dr. Sweet from occupying his home, definitely became very bitter as the case went on. Because of the feeling on the part of the two groups just mentioned, it is reasonably certain that all eleven defendants would have been convicted had it not been for the work of the attorneys engaged and the efforts of the N.A.A.C.P. both in retaining these attorneys and in conducting the case and in the efforts of the N.A.A.C.P. in placing before the people of Detroit the actual facts in the case to displace the half truths and untruths which had stirred such hostility against the defendants.

The case has cost the N.A.A.C.P. upwards of $20,000. A new trial has been set for the first week in January. Mr. Darrow announced to the court that it was probable that the defense would ask for separate trials for the eleven defendants. With renewed vigor, the N.A.A.C.P. is going into the case again determined to see it through to the end and to secure complete justice for the defendants.



After the mistrial, Messrs. Darrow and Hays made a motion for the admission to bail of the defendants. Eight of them were freed on bail of $5,500 each while three others, Dr. Ossian H. Sweet, Henry Sweet and Leonard C. Morse, were freed on bail of $10,000 each. This bail has been almost entirely furnished by Negro property owners of Detroit.

