
---
title: 'Race Intelligence'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 20
  issue: 3
  page: 118-119
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



For a century or more it has been the dream of those who do not believe Negroes are human that their wish should find some scientific basis. For years they depended on the weight of the human brain, trusting that the alleged underweight of less than a thousand Negro brains, measured without reference to age, stature, nutrition or cause of death, would convince the world that black men simply could not be educated. Today scientists acknowledge that there is no warrant for such a conclusion and that in any case the absolute weight of the brain is no criterion of racial ability. 

Measurements of the bony skeleton followed and great hopes of the scientific demonstration of race inferiority were held for a while. But they had to be surrendered when Zulus and Englishmen were found in the same dolichocephalic class. 

Then came psychology: the children of the public schools were studied and it was discovered that some colored children ranked lower than white children. This gave wide satisfaction even though it was pointed out that the average included most of both races and that considering the educational opportunities and social environment of the races the differences were measurements simply of the ignorance and poverty of the black child's surroundings. 

Today, however, all is settled. "A workably accurate scientific classification of brain power" has been discovered and by none other than our astute army officers. The tests were in two sets for literates and illiterates and were simplicity itself. For instance, among other things the literates were asked in three minutes "to look at each row of numbers below and on the two dotted lines write the two numbers that should come next." 

<table>
<tbody>
  <tr>
    <td>3</td>
    <td>4</td>
    <td>5</td>
    <td>6</td>
    <td>7</td>
    <td>8</td>
    <td>...</td>
    <td>...</td>
  </tr>
  <tr>
    <td>8</td>
    <td>7</td>
    <td>6</td>
    <td>5</td>
    <td>4</td>
    <td>3</td>
        <td>...</td>
    <td>...</td>
  </tr>
  <tr>
    <td>10</td>
    <td>15</td>
    <td>20</td>
    <td>25</td>
    <td>30</td>
    <td>35</td>
        <td>...</td>
    <td>...</td>
  </tr>
  <tr>
    <td>81</td>
    <td>27</td>
    <td>9</td>
    <td>3</td>
    <td>1</td>
    <td>⅓</td>
        <td>...</td>
    <td>...</td>
  </tr>
  <tr>
    <td>1</td>
    <td>4</td>
    <td>9</td>
    <td>16</td>
    <td>25</td>
    <td>36</td>
        <td>...</td>
    <td>...</td>
  </tr>
  <tr>
    <td>16</td>
    <td>17</td>
    <td>15</td>
    <td>18</td>
    <td>14</td>
    <td>19</td>
        <td>...</td>
    <td>...</td>
  </tr>
  <tr>
    <td>3</td>
    <td>6</td>
    <td>8</td>
    <td>16</td>
    <td>18</td>
    <td>36 </td>
        <td>...</td>
    <td>...</td>
  </tr>
</tbody>
</table>

Illiterates were asked, for example, to complete pictures where the net was missing in a tennis court or a ball in a bowling alley! 

For these tests were chosen 4730 Negroes from *Louisiana* and *Mississippi* and 28,052 white recruits from *Illinois*. The result? Do you need to ask? M. R. Trabue, Director, Bureau of Educational Service, Columbia University, assures us that the intelligence of the average southern Negro is equal to that of a 9-year-old white boy and that we should arrange our educational program to make "waiters, porters, scavengers and the like" of most Negroes! 

Is it conceivable that a great university should employ a man whose "science" consists of such utter rot? 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Education (1915)](/Volumes/10/03/education.html)
* [Education (1911)](/Volumes/01/04/education.html)
* [Our Health (1933)](/Volumes/40/02/our_health.html)
* [Knowledge (1911)](/Volumes/02/06/knowledge.html)
* [Lies Agreed Upon (1916)](/Volumes/11/04/lies_agreed_upon.html)

<!-- Similar articles end here -->