
---
title: 'The N.A.A.C.P. and Parties'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1924
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 28
  issue: 5
  page: 199-200
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


A number of newspapers anxious to get in line for campaign funds have been throwing fits over the alleged endorsing of a Third Party by this Association. What the National Association for the Advancement of Colored People in annual conference actually said was printed in the plainest sort of English in the last <span class = "small-caps">Crisis</span>. The National Association for the Advancement of Colored People does not attempt to tell its members or anyone else how to vote. It does attempt to put the facts before them and to urge them to consider the facts and vote with their brains and not with their prejudices. It has said repeatedly and says again: Any black man who votes for the present Republican party out of gratitude or with any hope that it will do a single thing for the Negro that it is not forced to do, is a born fool. Equally no Negro democrat can for a moment forget that his party depends primarily on the lynching, mobbing, disfranchising South. Toward any Third Party advocates the intelligent Negro must be receptive, hoping they are not enemies, seeking to make them friends, and trying to balance the prospects oi good and ill in supporting them.

Facing such facts one Negro may decide to support Coolidge in the present campaign, not because he is so good but because others are so bad; another Negro considering the same facts may decide to support Davis because in his Negro attitude he represents the best of a bad crowd; or again a black man may well say: "LaFollette's industrial program will help me as a laborer more than his silence on the Negro problem hurts me."

All of these positions are understandable and the National Association for the Advancement of Colored People has on its Board of Directors and in its executive office persons who represent every one of these attitudes and we still co-operate and respect each other's reasons and decisions.

But some things we do not understand and bitterly resent: One is the old "Jim Crow," "Grand Old Party" jackass who brays every time the black man criticizes the mass of privilege, monopoly and condescension which now masquerades as the party of Abraham Lincoln.

Another is the gentleman who accuses everybody who differs with him of being a scoundrel. In every campaign the attempt of self-respecting Negroes to vote as men and not as puppets is met with a flood of filth and abuse from certain Negro newspapers which are either paid to support the Republicans or expect to be paid. Unless we overwhelm these venal editors by our discountenance and contempt we will but weld our political slavery on our children.

The base of our trouble is that still, to a large number of prominent Negroes, "politics" is simply a method of private gain. They sell their votes, their opinions, their influence; and they think that this is what voting means. They did not originate this sordid business, God knows, but they have proven apt scholars and even some of our new women voters from whom we expected so much are joining in the hunt for loot and bribes, for pay and petty place.

What we need in this campaign is non-partisan centers of discussion and information; debate, facts, statements and re-statements of the high function of the voter and the deep eternal significance of Democracy.

Let us in God's name vote next November with our heads and not with our heels, as freemen and not as slaves, for racial and human uplift and not for contributions from the party slush fund.

