
---
title: 'The Church'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 6
  page: 302
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



This is a critical day for the Christian church. The white church of Christ finds itself in a position which gives the lie to many of its finest professions. It is a church of
Peace; and its followers are at war. It is a church of the Masses in
theory while in practice it is a church of the Classes. It is an
organization which despises wealth and yet which finds wealth its only
modern weapon. In fine,---as a follower of Jesus, the Jew,---it
professes the sublimest of ethical codes and yet falls so far from
following it that some would deny that it is Christian.

The Negro church in America comes nearer to being built along the lines
of its Founder. It is a democratic church of the masses; it welcomes all
men despite race or color; and its wide activities touch every line of
human endeavor. Nevertheless, the Negro church today in all its branches
faces a peculiar crisis. The 3,000,000 Baptists, who represent more
nearly than any other branch the great rank and file of the colored
people, are torn asunder over a detail of organization. The African
Methodist church must put strong material in its leadership or it will
drift into sectional disruption, or personal feuds. The Colored
Methodist Episcopal church is passing through a regrettable ethical
slough of despond in high places; while the Zion church is having
financial troubles. The colored Congregationalists are still a remnant.
The colored Episcopalians are as babes overlaid by their none-too-loving
mother; while the colored Presbyterians are spiritually harassed. The
great Methodist Episcopal church has a strong element which is seeking to drive out its colored membership in order to welcome
the white South.

Facing such problems what shall we do? The appeal is first of all to the
mighty past. In slavery, in Reconstruction and in the days after the
Negro church made the Negro race in America. Today it can remake it if
it calls to the front its strong, honest men; if it puts aside petty
sectarianism and creed, and if it works for social uplift and individual
honor. Will the church do this? In the long run and after much travail
of soul we believe it will.

