
---
title: 'Intermarriage'
author: Du Bois, W.E.B.
date: Apr. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 6
  page: 306
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There are those who from time to time suggest that the National
Association for the Advancement of Colored People and <span style="font-variant:small-caps;">The Crisis</span> go far afield in opposing laws to prohibit
intermarriage between white and colored people. They argue that neither
race desires intermarriage; that it is a matter "purely social," and
that legalizing the prohibition simply puts stern custom into law. Every
now and then, however, there come cases which show the utter blindness
of the persons who thus argue and prove that anti-intermarriage laws are
simply cloaks for wrong and injustice. In Evansville, Ind., just across
the river from Kentucky, Clifford Yarborough, a wealthy white man of
Pulaski, Tenn., came into the Circuit Court the other day and asked
permission to adopt a seventeen-year-old mulatto girl. The girl might
easily pass for white; she is strikingly beautiful and talented in
music. Yarborough willingly admitted that the girl's mother was colored,
and that he was the father. He said, "I feel like I should rectify a
wrong." There is no law against intermarriage of races in Indiana, but
there is in Tennessee. Judge Givens, therefore, refused to permit the
adoption. He said that "if he legitimatized the daughter he would be
taking a step which would in practice have the same results as
permitting the intermarriage of races." Therefore let us piously ruin
the life of an innocent girl!

