
---
title: 'Three Churches'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1916
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 11
  issue: 6
  page: 312-313
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Nothing will better illustrate the exact work of the Negro church in America than three notable examples: the Dixwell Avenue Congregational Church of New Haven, Conn.; the St. John's A.M.E. Church of Norfolk, Va., and the St. Mark's M.E. Church of New York City.

Dixwell Avenue Congregational Church was established in 1820 when a white man, Simeon S. Jocelyn, gathered in New Haven twenty-four colored persons to teach them. He met much abuse and received many threats from the whites, but his congregation grew until in 1829 they became a regular Congregational Church.

This church called to its pastorate in 1836 the celebrated colored man, the Rev. J.W.C. Pennington. Pennington, who was born a slave, became one of the best educated men of his day, and had a degree of Doctor of Divinity conferred upon him by the University of Heidelberg, Germany.

Between 1838 and 1857 the little church built a modest brick structure, and received from one of its deceased members \$10,000, the income of which is still divided between the church and worthy colored students.

Steadily the church has grown until today it has a large, brick edifice, a pipe organ and a chapel, and has just celebrated its ninety-fourth anniversary. It has always been foremost in public movements; in helping the Underground Railway; in seconding the efforts of William Lloyd Garrison; in encouraging education, and now in various lines of social uplift. A course of lectures is maintained; industrial classes are carried on, and a gymnasium teacher is hired; the Boy Scout movement has a center here; a pure milk station is in its chapel; and a social survey of the neighborhood was recently made.

The present pastor is the Rev. Edward F. Goin, a graduate of Yale.

St. John's A.M.E. Church of Norfolk, Va., was organized about 1840, and first met in an old soap factory. Then the white Methodist church took care of the congregation, and gave them their first house of worship in 1848. In 1863, under the Military Government, the church secured colored trustees, and after the war was admitted to the A.M.E. church through Bishop Wayman.

From the first the church has had a hard struggle with debt. The present edifice, which is the third that the church has owned, was begun in 1888. A fine parsonage was added in 1907, and finally in August, 1915, the church stood free from debt with an unusually excellent plant.

Perhaps the pastor, the Rev. E.H. Hunter, is proudest of his Sunday School among all the branches of his work. This is one of the great Sunday Schools of the country with an enrollment of nine hundred in the main school, three hundred and fifty in the Home Department, and one hundred and twenty-five in the Cradle Roll, a total of 1,375. There are thirty-two classes in the main school, and twenty-six classes in the Home Department, each in charge of a visitor.

The Cradle Roll Department is one of the brightest features of the school. The superintendent has a committee of four women and twelve girls who serve as visitors. The singing is spirited, and assisted by an orchestra of twenty men, and a choir of thirty boys and girls. There are classes in sewing and basketry work; lawn tennis, basket ball and other sports are encouraged, and a company of fifty cadets, uniformed and equipped.

The Superintendent is Lieutenant James N. Collins, who is serving his twenty-fourth term.

St. Mark's M.E. Church, of New York City, dates from 1871, and first worshipped at Broadway between Thirty-seventh and Thirty-eighth Streets. In 1871 it removed to West Thirty-fifth Street; in 1882 to West Forty-eighth Street, and in 1895 to West Fifty-third Street, where it now remains.

The pastor. Dr. William H. Brooks, who has served since 1896, is an organizer of unusual ability. Not only does the church own its edifice, but in 1900 it purchased a parsonage for \$8,000; in 1911 an apartment house in Harlem for \$54,000, and in 1913 a dwelling in New Rochelle for \$6,000. This same year a house adjoining the church was bought and reconstructed as a Parish House at a cost of \$63,000. Negro architects, contractors and mechanics worked on it. There are about forty rooms for the various activities of the society, including a men's club room, shower bath, gymnasium, kitchen, rest and play rooms, and an assembly hall for moving pictures. On the second floor is the pastor's residence. All sorts of organizations have their headquarters here, and many books by and about Negroes have been collected. A day nursery is maintained, and fifteen of the church classes meet here regularly.

Branches of St. Mark's Church have grown up in Brooklyn, in Harlem, in the Bronx and in Williamsbridge, and despite this the Mother church has grown from a membership of eight hundred to nearly two thousand in eighteen years.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Methodist Church, North (1911)](/Volumes/01/05/methodist_church_north.html)
* [Jesus Christ in Baltimore (1911)](/Volumes/01/03/baltimore.html)
* [The White Church (1917)](/Volumes/14/01/white_church.html)
* [The Church and the Negro (1913)](/Volumes/06/06/church_negro.html)
* [The Church (1916)](/Volumes/11/06/church.html)

<!-- Similar articles end here -->