
---
title: 'Economic Disenfranchisement'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Aug. 1930
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 37
  issue: 8
  page: 281-282
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There is no universal suffrage in modern industry. So far as the government conducts industry, as in the case of the post office and, in some instances, the transportation system, universal political suffrage indirectly controls the industry. But there are great public services, like the railroad, the telephone, gas and electric lighting, the telegraph and others, where the industry, although public in nature, is private in ownership, and conducted by an autocracy, except insofar as public opinion and the granting of privileges and franchises gives remote control to the voters. 

The disfranchisement, therefore, of the mass of workers in this case is the most extraordinary and vital disfranchisement in the modern world. When we talk of industrial democracy, we mean the increased right of the working people to determine the policies of great public services, either through direct public ownership or by private negotiation in the shape of shop committees, working agreements and the like. 

What is the attitude of the Negro here? Most Negroes would have no attitude at all, so far as public ownership was concerned. They would not be interested; and yet, they are, or should be, tremendously interested. Take, for instance, the telephone service. It is well-nigh universal. The number of telephones in use by colored people runs into the millions. It is not possible that Negroes in the United States spend less than $10,000,000 a year for telephone service, and they may spend three times as much as this. In the organization of work and trade a balance is always assumed between a service rendered or goods delivered on one side and a reciprocal service rendered and goods. delivered, on the other. If the exchange is not direct, it must be indirect, or the whole industrial combination fails. Yet in the case of the colored people and the tele phone, there is no reciprocity. The Telephone Company in the North, almost without exception, employs no colored help whatsoever; no laborers, no telephone girls, no clerks, no officials. The whole service is absolutely closed to Negroes. In the South, a few colored men are employed as laborers and linemen, but not many. 

Here then is a situation where a quasi-public institution absolutely refuses to let millions of citizens earn a decent living, while taxing them along with other citizens for this public service. This compulsory exclusion is, of course, not confined to colored people. It is exercised against Jews; it is exercised against various groups of foreign-born; it is exercised even against certain social classes among American-born citizens. But in the case of the Negroes, we can see it openly, just as in those chemical experiments where an artificially colored liquid reveals diffusion and reaction.

What now must Negroes do? If this sort of thing goes on, then disfranchisement in industry is going to be a vital factor in their elimination from modern civilization. By consolidations and mergers, by holding companies and inter-locking directorates, the great industries of the world are becoming integrated into vast private organizations, which means that the work of the world,---the skilled work, the best paid work,---in the vast majority of the cases, is subject to this social and racial exclusion; to this refusal to allow certain classes of men to earn a decent living. 

It is an intolerable situation. Attempts have been made to correct it by appeal. In Chicago and in High Harlem, New York, these appeals have been effective in the case of small store chains, and even to a slight extent with a corporation like the Western Union Telegraph Company. But the Telephone Company remains adamant. The Gas Company is absolutely deaf and unsympathetic. 

In this case there is only one thing to do, and that is for the Negro voters, with intelligence and far-reaching memory, to see that by their votes no further privileges and franchises are granted to these public service companies; and to see that the work of these companies, just as far as possible and as soon as possible, is transferred to the government. Government ownership is the only solution for this present industrial disfranchisement of the Negro. 

There are, of course, many other reasons and arguments for public ownership beside this personal and racial reason. But all these arguments simply bring home to the mass of people the fact that public service cannot be carried on endlessly for private advantage and private profit.

