
---
title: 'Freedom of Speech'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Aug. 1930
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 37
  issue: 8
  page: 282
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There are an extraordinary number of intelligent people in the United States who have no conception of the meaning of the freedom of speech. They apparently assume that this is the right to express any opinion with which they agree, but that opinions with which they disagree or which they regard as unsound or dangerous, must be suppressed. Back of this willingness to silence those to whom men do not wish to listen, lies stupidity, cruelty, oppression and disaster. The South, in a desperate attempt to keep the wedge of race prejudice between white and black workers, is persecuting Communists. They have resurrected in Atlanta an old slave statute and are actually threatening with death two black and four white prisoners in Atlanta. This is a counsel of despair. Whenever a doctrine becomes so dangerous to the peace and quiet of a country that citizens dare not listen to its advocacy and explanation, that is just exactly the time when that doctrine is needed. Mob law against Communists is just as detestable as mob law against Abolitionists, against Fascists or against white Russia. How singular that those persons in the community who are the wildest vocal opponents of force, are the first ones to substitute force for reason. 

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [Separation (1911)](/Volumes/01/04/separation.html)
* [Heroes (1919)](/Volumes/19/01/heroes.html)
* [Our Own Consent (1913)](/Volumes/05/03/our_own_consent.html)

<!-- Similar articles end here -->