
---
title: 'India'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Aug. 1930
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 37
  issue: 8
  page: 281
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



We trust that the colored people of the United States are watching with bated breath the struggle in India. Our view of it is of course distorted by the deception and propaganda of English news agencies. But here is an unparalleled fight for righteousness; the determination of millions of people, who in the face of their own ignorance, poverty and inner divisions, are with increasing unity standing against the effort of a great modern country to use them, their land and their resources chiefly for its own private profit. And Indians are seeking to do this and succeeding to an unparalleled degree by the method of peaceful agitation. Nothing like this has occurred in the history of the world. If it fails, it will mark an epoch. If it succeeds, it will revolutionize civilization. Against it is being used all of the paraphernalia of modern imperialism: lies, imprisonment, murder, delay, propaganda and dry official reports. The Simon Report on India is a long and labored document. It shows thought and attention. Twenty-five years ago it would have been a landmark and a beacon. Ten years ago it would have staved off revolution. Today, it is the last refuge of reaction. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Gandhi and India (1921)](/Volumes/23/05/india_and_gandhi.html)
* [Egypt and India (1919)](/Volumes/18/02/egypt_and_india.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Listen, Japan and China (1933)](/Volumes/40/01/listen_japan_and_china.html)
* [The Durbar (1912)](/Volumes/03/04/durbar.html)

<!-- Similar articles end here -->