
---
title: 'A New Party'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Aug. 1930
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 37
  issue: 8
  page: 282
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The League for Independent Political Action, which has headquarters at 347 Madison Avenue, New York, is an association of individuals, committed personally and as a group, to the development of a new political party, based on the principle of increasing democratic social control as distinguished from the present policies of the Republican and Democratic parties. This League is going to gather information; make research; distribute literature; form local clubs; and eventually it will nominate and ask support for its candidates. 

What this League hopes for is to build up a party like the Labor Party of Great Britain. It maintains that the wage of common workers is still far below a decent standard of comfort; that one-third of the old people are dependent; income, wealth and power are concentrated into too few hands. The League, therefore, wants intelligent citizens to work for the rapid extension of public ownership of public utilities, of the coal industry, and for public control of super-power. 

It wants, by means of taxing large incomes, by inheritance taxes and by taxes on the increase of land values, to be able to devote larger sums of public money for health, education, child welfare and the socialization of industry. It wants to establish and increase pensions for unemployment and health insurance and old age. It wants a tariff for revenue only and not as a bonus to manufacturers, and it regards a low tariff as the most effective help for farmers; it wants to increase producers and consumers' co-operation.

The League wishes to restore political rights to Negroes and to foreign-born citizens where they are now disfranchised. It wants to eliminate the causes of war and to stop imperial domination of backward countries. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The A.F. of L. (1933)](/Volumes/40/12/af_of_l.html)
* [A Third Party (1928)](/Volumes/35/11/third_party.html)
* [The League of Nations (1919)](/Volumes/19/01/league.html)
* [The N.A.A.C.P. and Parties (1924)](/Volumes/28/05/naacp_and_parties.html)
* [How Shall We Vote (1920)](/Volumes/20/05/how_shall_we_vote.html)

<!-- Similar articles end here -->