
---
title: 'American Legion, Again'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 3
  page: 107
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The American Legion is a national organization destined to be one of the most powerful instruments of public opinion and action in the United States. It is absolutely necessary that Negro soldiers join it and maintain their membership and sit in its councils. 

This is now possible in three-fourths of the forty-five states of the Union. In a few states, notably South Carolina, Alabama, and Virginia, effort is still being made to exclude Negroes. This effort is contrary to the constitution of the League and in the long run it cannot stand. 

Yet some shortsighted Negroes are inclined to give up joining the American Legion because the Minneapolis convention did not compel the bourbon South to accept Negro legionaries. The convention ought to have done this. It was a burning shame that it did not; but since it did not, it is our duty to COMPEL the next convention to do so. We must not give up. We cannot give up. Shall we give up our right to vote in New York and Massachusetts because it is denied in Texas and Louisiana? No. Fight harder. Agitate, protest---join the American Legion and never give it one hour's peace until every black soldier is a member. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The American Legion (1919)](/Volumes/18/05/the_american_legion.html)
* [Soldiers (1920)](/Volumes/20/03/soldiers.html)
* [White Co-Workers (1920)](/Volumes/20/01/white_coworkers.html)
* [We Should Worry (1917)](/Volumes/14/02/we_should_worry.html)
* [Loyalty (1917)](/Volumes/14/01/loyalty.html)

<!-- Similar articles end here -->