
---
title: '"Our" South'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 3
  page: 106-107
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



One of the surprising self-deceptions of the white Southerners is illustrated by this story of the war: Because of its large Negro working population, a government shipbuilding yard was brought to Wilmington, N.C., during the late war. The city congratulated itself, but balked finally at providing Negro workingmen with adequate housing. At a public meeting they lauded the whites and their enterprise to the skies, but complained to the government agents of the "burden" of the Negro---the black half of their population, said one pompous orator, was a "liability and not an asset."

"Well," replied an unimaginative northern Colonel, who wanted ships built instead of talk, "if it wasn't for this liability, you wouldn't have gotten this ship-yard!"

The fundamental error of the white South thus shown is seen in the assumption that ALL property is WHITE property; that they benevolently "give" Negroes work; that they let them walk THEIR streets and "pay for" their schools.

In economic thought the South is 100 years behind the civilized world. In what civilized land today can a ruling aristocracy deny a mass of eight million laborers an absolute right to education, to public institutions, and even to a voice in the use and distribution of "private" property?

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [The Liberal South (1921)](/Volumes/21/06/liberal-south.html)
* [Dodging the Issue (1933)](/Volumes/40/02/dodging_the_issue.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [The Migration (1917)](/Volumes/14/01/migration.html)
* [We Should Worry (1917)](/Volumes/14/02/we_should_worry.html)

<!-- Similar articles end here -->