
---
title: 'Race Pride'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 3
  page: 107
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




Our friends are hard---very hard---to please. Only yesterday they were preaching fm! "Race Pride." "Go to!" they said, and be PROUD of your race. If we hesitated or sought to explain---"Away," they yelled; "Ashamed-of Yourself and Want-to-be-White!" Of course, the Amazing Major is still at it, but do you notice that others say less,---because they see that bullheaded worship of any "race," as such, may lead and does lead to curious complications?

For instance: Today Negroes, Indians, Chinese, and other groups, are gaining new faith in themselves; they are beginning to "like" themselves; they are discovering that the current theories and stories of "backward" peoples are largely lies and assumptions; that human genius and possibility are not limited by color, race, or blood. What is this new self-consciousness leading to? Inevitably and directly to distrust and hatred of whites; to demands for self-government, separation, driving out of foreigners,---"Asia for the Asiatics," "Africa for the Africans," and "Negro officers for Negro troops!"

No sooner do whites see this unawaited development than they point out in dismay the inevitable consequences: "You lose our tutelage," "You spurn our knowledge," "You need our wealth and technique." They point out how fine is the world role of Elder Brother.

Very well. Some of the darker brethren are convinced. They draw near in friendship; they seek to enter schools and churches; they would mingle in industry,---when lo! "Get out," yells the White World---"You're not our brothers and never will be"---"Go away, herd by yourselves'---"Eternal Segregation in the Lord!"

Can you wonder, Sirs, that we are a bit puzzled by all this and that we are asking gently, but more and more insistently: Choose one or the other horn of the dilemma:

1. Leave the black and yellow world alone. Get out of Asia, Africa, and the Isles. Give us our states and towns and sections and let us rule them undisturbed. Absolutely segregate the races and sections of the world.
2. Let the world meet as men with men. Give utter Justice to all. Extend Democracy to all and treat all men according to their individual desert. Let it be possible for whites to rise to the highest positions in China and Uganda and blacks to the highest honors in England and Texas.

Here is the choice. Which will you have, my masters?

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [A Statement (1919)](/Volumes/19/01/statement.html)
* [Heroes (1919)](/Volumes/19/01/heroes.html)
* [Races (1911)](/Volumes/02/04/races.html)
* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)
* [Resistance (1914)](/Volumes/07/04/resistance.html)

<!-- Similar articles end here -->