
---
title: 'Sex Equality'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1920
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 19
  issue: 3
  page: 106
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




The Department of Justice has discovered a new crime,---"Sex Equality." This is not, as one might presume, equality of men and women, but it is the impudence of a man of Negro descent asserting his right to marry any human being who wants to marry him. With bated breath, Mr. Palmer (who has no power to prevent or punish lynching and who permits peonage to flourish untouched in Arkansas) tells an astonished Senate of this new sign of "Red" propaganda among blacks. Nonsense! Mr. Palmer is mistaken in assuming that it took a world war to make the Negro conscious of such an elementary right. No Negro with any sense has ever denied his right to marry another human being, for the simple reason that such denial would be frank admission of his own inferiority. For a man to stand up and say: I am not physically or morally or mentally fit to marry this woman, who wishes to marry me, would be a horrible admission. No healthy, decent man,---white, black, red, or blue---could for a moment admit so monstrous a fact.

He could, naturally, say: I do not WANT to marry this woman of another race, and this is what 999 black men out of every thousand DO say. Or a woman may say: I do not want to marry this black man, or this red man, or this white man,---this she has the absolute and unquestionable right to say. But the impudent and vicious demand that all colored folk shall write themselves down as brutes by a general assertion of their unfitness to marry other decent folk is a nightmare born only in the haunted brain of the bourbon South and transmitted by some astonishing power to the lips of the Attorney General of the United States.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [Inter-Marriage (1924)](/Volumes/29/06/inter-marriage.html)
* [Our Program (1930)](/Volumes/37/05/our_program.html)
* [President Harding and Social Equality (1921)](/Volumes/23/02/president-harding.html)
* [Social Equality (1919)](/Volumes/19/01/social_equality.html)

<!-- Similar articles end here -->