---
title: 'President Harding and Social Equality'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: December 1921
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 23
  issue: 2
  page: 53-56
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---

For fifty years we who, *pro* and *con*, have discussed the Negro Problem, have been skulking behind a phrase --- "Social Equality." Today President Harding's speech, like sudden thunder in blue skies, ends the hiding and drives us all into the clear light of truth.

We had our excuses perhaps in the past: about every problem of human relations lurks a penumbra of shadowing possibilities, which we would not discuss. It seems unnecessary, inappropriate, beside the point. And so defenders of the higher training of women have hesitated to explore sex freedom for females; and lovers of democracy have declined to consider the possibility of the masses voting their own wages. It is not that we have denied the ensuing problems that shadow our main object, but we have said with a certain truth: sufficient unto the present tangle is the obvious evil thereof. Let us follow the clear light and afterward turn to other darknesses.

But sometimes this becomes suddenly impossible. Sometimes the so-considered minor problem is so tremendous and insistent that it leaps to the fore and demands examination and honest facing. This is particularly so when we have not simply ignored the problem but have deliberately and cynically lied about it, denied it, and said not that "Social Equality" was not a pertinent and pressing problem; but rather that it was no problem at all.

## The Birmingham Speech

And now comes President Harding's Birmingham speech when unwittingly or deliberately the President brings the crisis. We may no longer dodge nor hesitate. We must all, black or white, Northerner or Southerner, stand in the light and speak plain words.

The President must not for a moment be blamed because, when invited to the semi-centennial of a great southern city of industry, he talked of the Negro instead of the results of profitable mining. There is but one subject in the South. The Southerners themselves can speak no other, think no other, act no other. The eternal and inevitable southern topic is and has been and will be the Black Man.

Moreover, the President laid down three theses with which no American can disagree without a degree of self-stultification almost inconceivable, namely:

1. The Negro must vote on the same terms that white folk vote.
2. The Negro must be educated.
3. The Negro must have economic Justice.

The sensitive may note that the President qualified these demands somewhat, even dangerously, and yet they stand out so clearly in his speech that he must be credited with meaning to give them their real significance. And in this the President made a braver, clearer utterance than Theodore Roosevelt ever dared to make or than William Taft or William McKinley ever dreamed of. For this let us give him every ounce of credit he deserves.

## Social Equality

But President Harding did not stop here. Indeed he did not begin here. Either because he had no adequate view of the end of the fatal path he was treading or because, in his desire to placate the white South, he was careless of consequences, he put *first* on his program of racial settlement a statement which could have been understood and was understood and we fear was intended to be understood to pledge the nation, the Negro race and the world to a doctrine so utterly inadmissible in the twentieth century, in a Republic of free citizens and in an age of Humanity that one stands aghast at the motives and the reasons for the pronouncement.

It may to some seem that this statement is overdrawn. Some puzzled persons may say: but Negroes themselves have told me that they repudiate "Social Equality" and amalgamation of race; in fact, right there at Birmingham, Negro applause of the President was audible.

All this does not minimize --- rather it emphasizes the grave crisis precipitated by the President's speech. It emphasizes the fact of our mental skulking or transparent and deliberate dishonesty in dealing with the Negro.

Social equality may mean two things. The obvious and clear meaning is the right of a human being to accept companionship with his fellow on terms of equal and reciprocal courtesy. In this sense the term is understood and defended by modern men. It has not been denied by any civilized man since the French Revolution. It is the foundation of democracy and to bring it into being, the world went through revolution, war, murder and hell.

But there is another narrow, stilted and unreal meaning, that is sometimes dragged from these words, namely: Social Equality is the right to demand private social companionship with another.

Or to put it more simply: the real meaning of "social equality" is eligibility to association with men, and the forced and illogical meaning is the right to demand private association with any particular person. Such a demand as the latter is idiotic and was never made by any sane person; while on the contrary, for any person to admit that his character is such that he is physically and morally unfit to talk or travel or eat with his fellow-men, or that he has no desire to associate with decent people, would be an admission which none but a leper, a criminal or a liar could possibly make. It is the very essence of self-respect and human equality and it carries with it no jot of arrogance or assumption --- it is simply *Homo Sum*.

## Self-Deception

Despite this, for fifty years the Southern white man has said to the Negro: Do you mean to say that you consider yourself fit to associate with white people? And the Negro has answered; but the question which he answered was not the one asked, but rather the other totally different question: Do you mean to say that you want to force your friendship and company on persons who do not want them? The answer to this is obviously an emphatic and indignant *No*. But when the Negro said *No,* he knew that he was not answering the question the white man intended to ask and the white man knew that the Negro knew this, and that he himself had purposely asked a question of double and irreconcilable meaning, when he said, "Do you want Social Equality?"

And so this undeceiving deception has gone on for fifty years until the President of the United States, throwing caution to the winds, has either boldly or unwittingly announced as a national policy that "men of both races may well stand uncompromisingly against every suggestion of Social Equality."

Or in other words, that no man, no matter how civilized, decent or gifted he may be, shall be permitted to associate with his fellow men on terms of equality or want to associate with them, if he be a Negro or of Negro descent.

Let us sweep away all quibbling: Let us assume that the President was sane and serious and could not and did not mean by "social equality" anything so inconceivable as the right of a man to invite himself to another man's dinner table. No. Mr. Harding meant that the American Negro must acknowledge that it was a wrong and a disgrace for Booker T. Washington to dine with President Roosevelt!

The answer to this inconceivably dangerous and undemocratic demand must come with the unanimous ring of 12 million voices, enforced by the voice of every American who believes in Humanity.

Let us henceforward frankly admit that which we hitherto have always known; that *no system of social uplift which begins by denying the manhood of a man can end by giving him a free ballot, a real education and a just wage.*

## Race Equality

Let us confess that the pseudoscience to which the President unhappily referred as authority, and the guilty philanthropy which has greedily levelled racial barriers and now seeks with the bloodstained hands of a Lugard to rearrange them so that profit may emerge and manhood be dammed --- let us confess that all this is vain, wrong and hypocritical and that every honest soul today who seeks peace, disarmament and the uplift of all men must say with the Pan-African Congress:

> The absolute equality of races --- physical, political and social --- is the founding stone of world peace and human advancement. No one denies great differences of gift, capacity and attainment among individuals of all races, but the voice of science, religion and practical politics is one in denying the God-appointed existence of superior races, or of races naturally and inevitably and eternally inferior.

To deny this fact is to throw open the door of the world to a future of hatred, war and murder such as never yet has staggered a bowed and crucified humanity. How can a man bring himself to conceive that the majority of mankind --- Chinese, Japanese, Indians and Negroes are going to stand up and acknowledge to the world that they are unfit to be men or to associate with men, when they know they *are* men?

## Amalgamation

But President Harding does not stop even here. He declares "Racial amalgamation there cannot be."

What does the President mean? 

Does he mean that the White and Negro races in this land never have mixed? There are by census reports over two million acknowledged mulattoes in the United States today; and without doubt there are, in fact, no less than four million persons with white and Negro blood.

Does he mean that there is no amalgamation today? Between 1850 and 1921 the mulattoes have increased over 400 percent. Does he mean there will be no future amalgamation? How does he know?

Or does he mean that it would be better for Whites and Blacks not to amalgamate? If he meant that, why did he not say so plainly? And if he had said so, 99 percent of the Negroes would agree with him. We have not asked amalgamation; we have resisted it. It has been forced on us by brute strength, ignorance, poverty, degradation and fraud. It is the white race, roaming the world, that has left its trail of bastards and outraged women and then raised holy hands to heaven and deplored "race mixture." No, we are not demanding and do not want amalgamation, but the reasons are ours and not yours. It is not because we are unworthy of intermarriage --- either physically or mentally or morally. It is not because the mingling of races has not and will not bring mighty offspring in its Dumas and Pushkin and Coleridge-Taylor and Booker Washington. It is because no real men accept any alliance except on terms of absolute equal regard and because we are abundantly satisfied with our own race and blood. And at the same time we say and as free men must say that whenever two human beings of any nation or race desire each other in marriage, the denial of their legal right to marry is not simply wrong --- it is lewd.

## Segregation and Race Pride

And this brings us to the last word of President Harding: He says in one breath:

> Especially would I appeal to the self-respect of the colored race. I would inculcate in it the wish to improve itself as a distinct race with a heredity, a set of traditions, an array of aspirations all its own. Out of such racial ambitions and pride will come natural segregations.

> The one thing we must sedulously avoid is the development of group and class organizations in this country. There has been a time when we heard too much about the labor vote, the business vote, the Irish vote, the Scandinavian vote, the Italian vote, and so on. But the demagogues who would array class against class and group against group have fortunately found little to reward their efforts.

Is the President calling himself a demagogue? Does he not realize the logical contradictions of his thought? Can he not see his failure to recognize the Universal in the Particular, the menace of all group exclusiveness and segregation in the forced segregation of American Negroes? Can he not in this day of days with foreigners of every race flocking to Washington and the eyes of a blood-weary world strained after them --- can he not realize the vast, the awful implications of this appeal to the Frankenstein of race exclusiveness --- that hateful thing which has murdered peace and culture and nations? Does he not hear the answer that leaps to our lips? For when Warren Harding or any white man comes to teach Negroes pride of race, we answer that our pride is our business and not theirs, and a thing they would better fear rather than evoke: For the day that Black men love Black men simply because they are Black, is the day they will hate White men simply because they are White.

And then, God help us all!

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Social Equality (1919)](/Volumes/19/01/social_equality.html)
* [Our Program (1930)](/Volumes/37/05/our_program.html)
* [Social Equality (1916)](/Volumes/12/01/social_equality.html)
* [William Monroe Trotter (1914)](/Volumes/09/02/trotter.html)
* [Education (1913)](/Volumes/06/02/democrats.html)

<!-- Similar articles end here -->