
---
title: 'Organized Labor'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 3
  page: 131
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


<span class = "small-caps">The Crisis</span> believes in organized labor. It realizes that the standard of living among' workers has been raised in the last half century through the efforts and sacrifice of laborers banded together in unions, and that all American labor to-day, white, black and yellow, benefits from this great movement. 

For such reasons we carry on our front cover the printer's union label to signify that the printing and binding of this magazine is done under conditions and with wages satisfactory to the printers' union. 

We do this in spite of the fact, as well known to us as to others, that the "conditions satisfactory" to labor men in this city include the deliberate exclusion from decent-paying jobs of every black man whom white workingmen can exclude on any pretense. We know, and all men know, that under ordinary circumstances no black artisan can to-day work as printer, baker, blacksmith, carpenter, hatter, butcher, tailor, street or railway employee, boilermaker, bookbinder, electrical worker, glass blower, machinist, plumber, telegrapher, electrotyper, textile worker, upholsterer, stone cutter, carriage maker, plasterer, mason, painter---or at any other decent trade unless he works as a "scab," or unless in some locality he has secured such a foothold that the white union men are not able easily to oust him. 

This policy is not always avowed (although there are a dozen unions affiliated with the American Federation of Labor who openly confine admission to "white" men), but it is perfectly well understood. Some unions, like the printers and the carpenters, admit a lone colored man here and there so as to enable them the more easily to turn down the rest. Others, like the masons, admit Negroes in the South where they must, and bar them in the North where they can. 

Whatever the tactics, the result is the same for the mass of white workingmen in America; beat or starve the Negro out of his job if you can by keeping him out of the union; or, if you must admit him, do the same thing inside union lines. 

What then must be the attitude of the black man in the event of a strike like that of the white waiters of New York? The mass of them must most naturally regard the union white man as their enemy. They may not know the history of the labor movement, but they know the history of white and black waiters in New York, and when they take back the jobs out of which the white waiters have driven them, they do the natural and sensible thing, howsoever pitiable the necessity of such cutthroat policies in the labor world may be. So long as union labor fights for humanity, its mission is divine; but when it fights for a clique of Americans, Irish or German monopolists who have cornered or are trying to corner the market on a certain type of service, and are seeking to sell that service at a premium, while other competent workmen starve, they deserve themselves the starvation which they plan for their darker and poorer fellows. 

