
---
title: 'The Third Battle of Bull Run'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Jan. 1912
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 4
  issue: 3
  page: 132
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



It is just south of Manassas where Beauregard had his supplies, and east of the first two battlefields, with their ghastly relics and calm and guardian mountains.

This third battlefield is dotted with buildings green and red. A little flying engine pants continuously with its water burden, and to and fro pass dark graceful girls and sturdy brown-faced boys. There are green lawns and little trees, and westward in a hidden grotto, a grove green golden, echoing with the voices of new graduates long gone. The dull crimson building in the midst—Howland Hall—stands sturdily with a certain quietude, flinging a long, low wing modestly behind it, where sprites and gnomes and fairies dart in and out and to and fro in busy work.

Southward the girls are clustered, northward the boys, and round about are teachers' families often new founded with new and cunning babies, albeit one and the prettiest had fled, suddenly, and left a sorrow underneath the trees. Teachers there are, varicolored, sunny and sad, but quiet all, busy and happy, eager and glad. With them and not above them is the principal with his boy face and his wife who has wings—wings finely frayed with beating at the bars of life—but wings withal, and in her eyes dreams.

But the battle? Ah, yes, the battle, the third and blood-bought battle of this winding brook that whimpers &rsquo;twixt the mountains and the sea; the blood of wounded souls lies along the gold green of that campus—the hail of the iron that enters thuds through the thick dark skins. Now and then the bitter stifled wail of the dying breaks the sudden stillness, then the ranks close and the school moves on.

It's costly, this fighting. Costly in blood and men, costly in money, costliest in worry and apprehension. Each year, each month, the Forager goes North:

"A man to see you, sir."

"Who?" snorts Wall Street, wheeling in his chair.

"Colored man—begging, I think, sir."

"Another Nigger school! Give him $5 and send him on."

And the Forager pockets his shame and moves wearily to the West.

"Yes? Well, I'm giving so much to colored people already---what is this school?"

"Manassas Industrial School? Yes. And for colored youth? Yes? I never heard of it. I give to things I hear of—Battle? I thought the war was over; it isn't. How sad. Good-day."

Thus in drippings of the rich and pennies of the poor each year $18,000 is raised to dig the trench and fire the fuse and strengthen the soul in this third struggle at Manassas.

Who is fighting? North and South, black and white, rich and poor? Oh, no—more primal, more stupendous is this struggle of worlds; light and leading and industry against darkness and hate and the Devil-of-things-that-be. And who wins? God wins—or is ever about to win, if only the Forager staggers home with the food to feed the weary watchers in the trenches, the black-sweated fighters in the fields. Pity the Forager, my brothers, and hold up his hands!

Sunset on the battlefield, and the hard breathing of them that rest from their labors; to the West, glory; to the East, the moon; between, shadows of things that were and are to be; around, a rose-grown porch, the patter of little feet, Woman---with---wings, Man---who---is---ever-young, and laughter.

Up from the earth come voices, heavy with sorrow:

> *O brother you must bow so low,*    
> &nbsp;    
> *O brother you must bow so low,*
> &nbsp;    
> *For long is the way to the ever bright world,*
> &nbsp;    
> *Let the Heaven light shine on me!*

And so on till we sleep; in our ears the soft low panting of the engine catching its breath; in our eyes the everlasting stars.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Girls (1921)](/Volumes/22/05/girls.html)
* [Attention (1918)](/Volumes/15/06/attention.html)
* [The South (1917)](/Volumes/13/06/south.html)
* [In God''s Gardens (1912)](/Volumes/03/06/in-gods-gardens.html)
* [The Three Wise Men (1913)](/Volumes/07/02/three_wise_men.html)

<!-- Similar articles end here -->