
---
title: 'The Black Bastille'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 5
  page: 217
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There is in Paris a place where once a notorious prison stood---the Bastille. For many years from the beginning of its erection in 1369, it lowered, a stronghold of cruelty and despotism. But on one marvelous fourteenth of July, 1789, it was stormed by a furious and desperate populace, and not a stone is left to indicate what once had been. Instead, now on that spot, a lofty column, the Column of July, rears skyward its slender, beautiful length, a carven oriflamme of that liberty, fraternity and equality which is in verity the pride of France.

And so the Bastille perished. Moreover the key was brought to America and tendered by Lafayette to General Washington in gracious recognition by one democracy of another. But here the similarity between the two countries ceases. For since the fall of the French stronghold there has been building in this democracy a tower, a fortress fully as iniquitous in its purpose as the ill-famed Bastille of old. Throughout the length and breadth of this land, yes, in the Nation's very capital, are men bent on putting the crowning touch of infamy to this new and monstrous superstructure---the Black Bastille of Prejudice. How many victims have been thrust into its pitiless confines! Into it have gone the ideals of the Pilgrim Fathers, the dreams of the Abolitionists and President Lincoln, and during the week before the fourteenth of July---the very anniversary of the fall of its stone and mortar prototype---the democracy of a nation! The shadow of the Black Bastille lies always across the path of us Americans. Turn where we will we cannot escape its gloom. In those old unhappy, far-off days the French populace demolished their Bastille's frowning reality with every conceivable weapon, stones, maces, pick-axes, halberds and their poor naked hands. America's course must be as theirs. We have no choice but to bring to the annihilation of this structure---so insubstantial and yet so real our all---determination, effort---grim, unceasing---money, time, tears, our naked bleeding hearts.

