
---
title: 'East St. Louis'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 5
  page: 215-216
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Let no one fear that in the economic development of the American Negro East St. Louis is not a bubble. Its significance is simply the shame of American democracy and the utter impotence of its justice. Nevertheless, despite this pogrom, engineered by Gompers and his Trade Unions, the demand for Negro labor continues and will continue. Negro labor continues to come North and ought to come North. It will find work at higher wages than the slave South ever paid and ever will pay, and, despite the Trade Unions and the murderers whom they cover and defend, economic freedom for the American Negro is written in the stars. East St. Louis, Chester and Youngstown are simply the pools of blood through which we must march, but march we will.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [St. Louis (1916)](/Volumes/11/05/st_louis.html)
* [Our Economic Peril (1930)](/Volumes/37/03/our_economic_peril.html)
* [Memphis or East St. Louis? (1917)](/Volumes/14/03/memphis_or_east_st_louis.html)
* [Black and White Workers (1928)](/Volumes/35/03/black_and_white_workers.html)
* [The Migration (1917)](/Volumes/14/01/migration.html)

<!-- Similar articles end here -->