
---
title: 'More Suggestions'
author: Du Bois, W.E.B.
date: Mar. 1917
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 14
  issue: 5
  page: 215
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



We spoke last month of the great call for team work on the part of American Negroes and the pressing necessity of turning that team work toward helping us to earn a living.

Today the way is open for co-operation among 12,000,000 people on a scale such as we have never dreamed. What we can do is shown in little things. Ten thousand of us marched the other day in New York City. Everybody said it could not be done. The ways were lined with rabbits, afraid even to walk for freedom, and yet, solemnly and simply, the Negroes of New York told the other citizens of New York their grief and resentment. That is but a little thing. We can do infinitely more. We can organize for industrial co-operation and we can begin with co-operation in distribution. In every large city where 10,000 or more Negroes live, the business of buying groceries, food, clothing and fuel can, by a single determined effort, be put into the hands of colored people. This kind of distribution has been successful all over the world. Little is said about it because the leeches that have fattened on retail trade are too powerful with the newspapers. Distribution of the necessities of life can be easily done with a tremendous saving to the people and the employment of colored men and women. The only thing necessary is for us to start; and to start we simply require that the same spirit of devotion and sacrifice, coupled with brains and training, that has sent young men and women to the ministry and the Y.M. and Y.W.C.A. work should be turned now among us Negroes and be put into business.

White people are not in business for their health. We should be in business for our health and for the health of the world.

