
---
title: 'Of the Children of Peace'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1914
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 8
  issue: 6
  page: 289-290
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Come, all my father's children, and sit beside my knee, here with this
child of mine, and listen:

Have you ever seen a soldier? It is a brave sight, is it not? Once upon
a time, many, many years before your dear little curly heads were born,
I remember seeing an army that marched because a King was visiting an
Emperor. Berlin was joy mad. Houses streamed with color and music reeled
and rioted. Then came the army. Tall, handsome men, all gold and silver
and broadcloth, sworded, spurred and plumed, led on horses that
curvetted and tossed their shining bits. (Do you not love a horse with
his great, sweet eyes and quivery. shining softness?) Next came the
soldiers, erect, rigid, "Eyes left!" Pit-pat. pit-pat! Clasping their
little innocent guns. Next came the artillery: files of wildly prancing
horses dragging long leaden things. How the crowd roared. The King bowed
to the Emperor and the Emperor bowed to the King, and there rose a great
cry of pride and joy and battle from the people. With that cry I seemed
suddenly to awake. I somehow saw *through;* (you know sometimes how you
seem to sec, but arc? blind until something happens and you really see?)

I saw then what I see now. I saw and see the WAR that men said could not
be.

Gone was all the brave tinsel, the glitter, sheen and music. The men
trudged and limped, naked and dirty, with sodden, angry, distorted
faces; their eyes were sunken and bloodshot, with murder in them; they
staggered over corpses and severed arms and feet and dead horses and
they carried---not little innocent guns, but little innocent children;
they dragged, not pale and leaden guns, but pale and bounden women, and
before them staggered and crept old women and grandfathers, the sick and
the maimed, the weak and the half-grown boys and girls.

I heard the cry that hovered over this fearsome army: it was a wail of
hunger and crime, of thirst and pain and death, and the cry rose and met
an answering cry that came from beyond the forest to the West.

Two toddling children slipped from their fathers' arms and met in the
gloom of that forest, where the beasts cowered and livid, disbodied
hands seemed to creep in the darkness.

"Mother," they whispered.

"Mama," they cried.

"Mutterchen," they sobbed.

Wild with horror two bound mothers beat their naked hands against the
gun-carriages, groping and struggling through the gloom, as death flamed
through their hearts.

Then the armies met. Two fathers leapt from the two armies ahead and
each seized the other's child. They strangled and crushed and maimed and murdered it, till each baby lay pale, limp and dead.

(Nay, shrink not, my children; horrible as the tale may be, the truth is
worse and you must know it.)

Then War was loose. Then six million human beings left their fields of
golden grain and the busy hum of their factories and taking their own
children for weapons dashed them against the trees and the lampposts and
the churches and wallowed and gasped in their blood!

Come, all my father's children and hear how beyond the blue mists of the
Everlasting Sea, the-mothers mad with hunger, grief and pain, are
fronting the blood-stained heavens with bared and haunted breasts and
are shrieking: 

"Why?"

"Why?"

Their shriek is the booming of guns, and the booming of cannon is the
shriek of mothers.

And you must answer, Children of Peace, you must answer!

You must cry: "There is no why!" "The cause of War is Preparation for
War."

"The cause of Preparation for War is the Hatred and Despising of Men,
your and my Brothers."

"War is murder in a red coat."

"War is raped mothers and bleeding fathers and strangled children." 

"War is Death, Hate, Hunger and Pain!"

"Hell is War!"

And when you believe this with all your little hearts;

And when you cry it across the seas and across the years with all your
little voices---

Then shall the mothers of all dead children hear;

Then shall the Sisters of all dead Brothers hear; then shall the
Daughters of all dead Fathers hear; then shall the Women rise and say:

"War is done."

"Henceforward and forever there shall be no organized murder of men, for the children we bear shall be the Children of Peace, else there
shall be no children."

Amen!

But cry, little children, cry and cry loud and soon, for until you and
the Mothers speak, the men of the world bend stupid and crazed beneath
the burden of hate and death. Behold, this old and awful world is but
one slaughter-pen, one tale of innocent blood and senseless hate and
strife.

Look yonder! In the gloomy forest all is still, save here a red and
flickering flame and there a last trembling sob. Only one living thing
passes across the night: a horse---a gaunt, sweating horse, with bloody
nostrils, great pain-struck eyes, and bowels trailing on the earth. He
hears his Emperor bugling "Victory!" to the King. Turning he staggers
toward him and whimpers as he goes.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Thirteen (1918)](/Volumes/15/03/thirteen.html)
* [The Slaughter of the Innocents (1918)](/Volumes/16/06/slaughter.html)
* [Forward (1920)](/Volumes/20/05/forward.html)
* [A Philosophy in Time of War (1918)](/Volumes/16/04/philosophy_in_time_of_war.html)
* [Of Children (1912)](/Volumes/04/06/of_children.html)

<!-- Similar articles end here -->