
---
title: 'Forward Backward'
author: Du Bois, W.E.B.
date: Apr. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 6
  page: 243-244
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The nemesis of every forward movement in the United States is the Negro question. 

Witness Woman Suffrage, the Liquor Question, Political Reform, the various efforts to revivify the Christian Church, and Socialism. Mrs. Anna Shaw, president of the Woman's Suffrage Association of America, recently made the extraordinary statement that all Negroes were opposed to woman suffrage. This is, of course, a barefaced falsehood. But assuming that Mrs. Shaw believes it true, what is Mrs. Shaw's conclusion? The traveler from Altruria might assume that she would say: 

"Therefore let us work to enlighten these colored men and women and show them that disfranchisement, whether by sex or race, is wrong." Not so does the astute Mrs. Shaw advise. On the contrary, she says: "Do not touch the Negro problem. It will offend the South." This is the 
advice that is generally given to an organization which sings in its recently adopted hymn: 

> We the People! All the People! How it rings! 
> Justice broad and free, the living heart of things!
> Sisters working for the light,
> Brothers striving for the right, 
> We the People! All the People! How it rings! 

Such contradiction hurts the Woman's Suffrage movement far more than it hurts black folk. The strength of the woman's movement in England is that it is honest and unselfish, aristocrat and working woman working hand in hand. But in America, despite the brave effort of women like Mrs. Belmont and Mrs. Villard, the war cry is rapidly becoming "Votes for White Women Only." 

No wonder Europe sneers at American democracy. Small wonder that we ourselves lose the faith in ourselves which we so sorely need. We would like to believe that a great uplift movement of young people who profess to follow the precepts of Jesus Christ would first of all condemn murder, lynching and lawlessness in this land. As a matter of fact, the recent national meeting of the Christian Endeavorers refused even to consider such a resolution. Yet this was the organization that made the welkin ring last year to prevent the exhibit of a black man's victory in a prizefight  

Consider again the effort of the South to regulate the sale of liquor. "The Negroes oppose us," many Southerners complain. This is untrue. A very large proportion of the Negro vote can be counted on to oppose the liquor traffic. But suppose that many or all did oppose certain prohibitory laws, the remedy would be to educate and persuade those voters. But no, the "reformers," who for eleven months in the year take every opportunity to show their contempt for a black face, suddenly a few weeks before election order the Negro voters to vote for their measures on pain of further disfranchisement. When some Negroes refuse to do this, we are told in triumphant tones that Negroes are not worthy of the ballot! 

Of all recent forward movements the Socialists have rung truest on the race question in their theoretical statements. But here they have usually stopped. "Why do not Negroes join the Socialists?" they ask. They do not ask such silly questions of white folks: They go and see why they do not join. They teach, agitate and proselyte; while among ten million Negro Americans they have scarcely a single worker and are afraid to encourage such workers. All of which goes to show that the Negro problem is the door which bars progress in the United States and which makes us liars and hypocrites. Yet the unloosening of that door is the simplest thing on earth: Treat human beings according to their character and not according to their color. 

