
---
title: 'Hail, Columbia!'
author: Du Bois, W.E.B.
date: Apr. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 6
  page: 244-245
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



American civilization moves steadily and graciously forward. Consider this gem from a New York morning paper: 
> Fifth Avenue, near 114th Street, was well filled with men and women as well as crowds of children at play, about 10 o'clock last night, when a young girl accosted another of about her age, and as the latter suddenly darted off along 114th Street started in pursuit shouting: 'Stop her! She's a thief!'   
> &nbsp;
> Instantly there was a crowd of almost 100 men and women at the girl's heels. She ran to Lenox Avenue, the crowd behind her increasing in numbers, and then turned down toward 113th Street. She ran swiftly and was far ahead of her nearest pursuer when Policeman Bernstein of the East 104th Street Station grabbed her at 112th Street.

What of it? She was a thief---a nasty, God-forgotten thief, and perhaps worse. Moreover, she was a foreigner. Hail to the "almost 100 men and women" who ran the frightened thing like a rabbit to its warren. Behold our civilization at its highest and best; or at its lowest and worst. How shall we, the untutored groundlings, know? Where are our teachers in this day of lynching and lawlessness? What are they saying and doing?

Pick out the ten greatest men of America, beginning, of course, with the distinguished gentleman who has just declined the presidency, and coming to President Taft and the college presidents, captains of industry, professional men and leaders of culture. What have they said? Nothing. What should they say? Something---anything. The symptoms fly and spread. They shriek to Heaven. They mean something. If they mean the glorious fruition of the best of American democracy let the leaders of this people speak out and say so. If they mean Hell (and they do), where in Heaven's name is the moral courage of this land gone to?

The answer is not far to seek. I wrote to an American recently---one of the best specimens of American manhood, white and wealthy and philanthropic. I said: "Join us and fight lynching, lawlessness and race prejudice." He was resting in his pretty cottage by the blue waters of a beautiful lake with the sweet shadow of mountains, away from the city's fetid heat, daintily served by servants, surrounded bv his books and interests---and he wrote:

> With reference to your suggestion that I join your association, I am, of course, deeply interested, but have
been so much impressed with what seemed to me the bitterness and unchristian spirit I have observed in various comments from time to time that I have felt that only harm could come in the long run from that temper. I sympathize strongly with the dignified protests against the suppression of the vote of the Negroes, but I am myself profoundly against war in every aspect, and believe that Jesus Christ meant to turn the other cheek. I am sorry to say that it has seemed to me you definitely reject this aspect of Christ's teaching in any event. 

Angels and ministers of Grace, defend us!

