
---
title: 'Knowledge'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 6
  page: 245
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



One of the comfortable theories of the South is its intimate and careful knowledge of everything relating to black folk. Governor Donaghey of Arkansas, for instance, recently said to the Negro Business League:

> While you are said to be an imitative race, you never suicide or suffer from nervous trouble. I believe it was your chairman who tells us of the young Negro in Harvard University who specialized on nervous diseases with a view of practicing medicine in the Mississippi bottoms. He, of course, would never have had a patient.

As a matter of fact, in 1860 American Negroes were committing suicide at the rate of 330 a year; in 1900 at the rate of 510 a year, and to-day the rate is undoubtedly between 600 and 700. Again next to consumption and pneumonia no set of diseases is more fatal to Negroes than diseases of the nervous system. Over 30,000 Negroes die from this cause each year.

All these figures are from the United States census reports and go to show the ignorance of knowledge which will not learn.

It illustrates, too, how silly it is to try and draw great slashing lines of difference between races. Men. families, nations and races differ, but humanity is one.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Death Rates (1927)](/Volumes/34/08/death_rates.html)
* [Light (1912)](/Volumes/03/04/light.html)
* [Woofterism (1931)](/Volumes/38/03/woofterism.html)
* [Arkansas (1920)](/Volumes/19/04/arkansas.html)
* [Education (1911)](/Volumes/01/04/education.html)

<!-- Similar articles end here -->