
---
title: 'Mr. Taft'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Apr. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 6
  page: 243
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Mr. William Taft, President of these United States, shows a marvelous facility for getting on the right track and saying the wrong thing. The most glaring example of this is, of course, the tariff, but his attitude toward the American Negro is a . fatal second. Not only is Mr. Taft *particeps minims* with the late Mr. Roosevelt in the crime of Brownsville, but he added to that the Taft Doctrine of recognizing race prejudice, instead of fitness, in Federal appointments. On top of this, and in the face of a record of murder, lynching and burning in this country which has appalled the civilized world and loosened the tongue of many a man long since dumb on the race problem, in spite of this, Mr. Taft has blandly informed a deputation of colored men that any action on his part is quite outside his power, if not his interest.

Finally, Mr. Taft has several times expressed himself on Negro education. First he was quite enthusiastic for the education of the Negroes' hands. Then---on the eve of his nomination to the presidency---he discovered at Fisk University a few black brains that deserved cultivation, but sparingly---sparingly. He would not overdo this sort of thing. Lately, on the eve of his campaign of renomination to the presidency, Mr. Taft has again declared that the Negro "ought to come and is coming more and more under the guardianship of the South!" This statement is, to speak mildly, extraordinary; and it will make thinking black men carefully considerate as to whether they are willing to enthrone this policy in the White House for another four years.

Let us examine the dictum: When a guardian is appointed it is because he has shown in the past some capacity for the position. One would not
usually ask a murderer to guard life, nor a slave driver to direct labor, nor a libertine to protect girls. Or if by chance such an one is so appointed, it could only be that despite a forbidding past he had shown unmistakable signs of repentance, and will and ability to do right. We ask now in all charity and calmness: Have the Southern
States of this land in the past or in the present exhibited any desire or ability to settle the Negro problem in accordance with reason and justice? The answer lies in nine burning words: 

* Slavery
* Peonage 
* Mulattoes 
* Murder 
* Mobs 
* Lynching 
* Disfranchisement 
* Illiteracy 
* Prejudice

We submit to any unprejudiced judge that a people that have shown no greater capacity for dealing with a great social problem than these fearful words indicate are not fit to be given sole and exclusive charge of ten million cattle much less ten million human souls.

And we further declare that a man who in the light of the history of this land can stand up and deny to the conscience and ability of the North and West any right to help in the settlement of a problem which belongs to them just as much as it belongs to the South, if not more---we declare that such a man has no business to be President of the United States.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [The Election (1912)](/Volumes/05/02/the_election.html)
* [The Flag (1911)](/Volumes/02/03/flag.html)
* [Mr. Roosevelt (1912)](/Volumes/04/05/mr_roosevelt.html)
* [The President (1915)](/Volumes/09/04/president.html)
* [Education (1913)](/Volumes/06/02/democrats.html)

<!-- Similar articles end here -->