
---
title: 'Advice'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1910
categories: 
  - Lynching
  - Tactics
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 2
  page: 21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



There is a matter which calls for a solemn editorial in a metropolitan newspaper, namely, the pre-emptying of seats on suburban trains. The *New York Times* says:

> Very often the question, 'Is this seat taken?' which it is well enough to ask before sitting down beside a stranger, is answered with a gruff and resentful 'Yes,' though obviously it is not then 'taken' by anything more than a hat or a newspaper or a valise. This reply is impudent, and it ought to result in a 'scene,' more or less vivacious, every time it is made.

This is the advice to commuters: Make a scene "more or less vivacious" every time!

There is another serious matter which calls our attention: Two thousand five hundred colored men have been lynched in this land in the last 25 years. On this matter we have not been advised to make a scene "more or less vivacious," but on the contrary, a large number of good and influential men have united to deprecate complaint or agitation. Many colored men are disposed to accept this advice, but on the heels of it comes the action of Mexico. One---just one---Mexican was burned in Texas. "We thought no more of it," says the Associated Press dispatch naively, but the land of Mexico was moved from center to circumference; denunciation and even mob violence was threatened and all over *one* criminal.

Can we black men fail to contrast with this the recent interview with
a distinguished American in Vienna? He is reported in the columns of *Die Zeit* to say: "There was no race war in America over the Johnson-Jeffries fight. Not more than a dozen Negroes were killed and now the whole matter is forgotten."

All of which shows how advice may be tempered by race prejudice.

