
---
title: 'The Election'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1910
categories: 
  - Voting
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 2
  page: 20
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



For colored men the Congressional election of 1910 marked an event. Never before since Emancipation have so many colored voters cast the Democratic ticket.

The reason for this was fourfold:

1.	Mr. Roosevelt's blunder at Brownsville.
2.	The failure of the Republican party to redeem its reiterated pledges to colored men.
3.	The policy of ousting Negro officeholders inaugurated by Mr. Taft.
4.	The invitation extended by various Democratic candidates in the North and by the party in border States like Missouri.

Was it wise for colored men to vote the Democratic ticket? It is always wise for any voter to vote his honest convictions. Whether or not the colored people will be treated decently by the triumphant Democracy remains to be seen. On this point the appeal sent out to newly elected congressmen by the United Colored Democracy of New York is significant:

> The result places a heavy responsibility on us and, we venture to suggest, on you. Fair and honest as has been the treatment of Negroes by a large part of your party it is nevertheless unfortunately true that a reactionary branch is continually endeavoring through legislation and judicial decision to proscribe and degrade our people.
> &nbsp;
> In view of this fact we earnestly appeal to you to do all in your power to see that the forces of reaction and race hatred do not take advantage of this Democratic victory to pass oppressive legislation. Should this be done, our efforts for a series of years will be nullified, the Republicans will be able to say, 'I told you so,' and the growing Negro vote will be lost to the Democrats for a long time. As you know in a close contest the colored voters of several large Northern States hold the balance of power.
> &nbsp; We do not expect or ask for special legislation, but we do ask that your party stand up for progressive measures and refuse to be made responsible for any effort to degrade American citizens.

