
---
title: 'The Ghetto'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1910
categories: 
  - Discrimination
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 2
  page: 21--22
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


It is curious how old ideas recur and ancient ones persist. In earliest times the easiest way to prevent trouble was to separate the combatants---put space between them, herd them in separate sections and territories. So long as the world was wide this was feasible and often effective. As the world grows narrower, it is not so easy and as it grows more civilized it is less advisable. For after all culture is the meeting and learning of men.

For instance, one meets on street or car an impudent colored man. He has some education, he has good clothes and he feels his importance and asserts himself. Like a flash you rush to the conclusion: Such a man ought not to associate with white folks until he learns good manners. But hold; suppose all the ill-mannered white folk were segregated, would that improve the world's deportment? Certainly not. It would make it distinctly and dangerously worse. It is association with the well-bred that brings manners.

How has America come to improve the manners which justly shocked Dickens and Mrs. Martineau? By associating with gentlemen and ladies here and in Europe. It was and is a bit hard on Europe, but it is a great boon for the world.

In America by the accident of color it is possible roughly to separate much ignorance and bad manners by drawing the color line. But it is a barbarous and unjust and unwise expedient, and it leads to the extreme Ghetto idea. The half-trained white Baltimore tradesman reasons logically: If I can push black men out of my way in train and street car, in theatre and art gallery, in church and park, why can I not segregate them in a Ghetto? The Atlanta "cracker," newborn to good wages and political power, is jealous of ambitious black folk. If he can take a black man's vote away why can he not take his home and force him back to the alley, whence he came?

It is time that the thought and conscience of America took a firm stand on these matters and stopped now and forever such dangerous and undemocratic doctrine.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Jim Crow (1919)](/Volumes/17/03/jim_crow.html)
* [Segregation (1910)](/Volumes/01/01/Segregation.html)
* [The Strength of Segregation (1913)](/Volumes/07/03/strength_of_segregation.html)
* [Separation (1911)](/Volumes/01/04/separation.html)
* [Correspondence (1926)](/Volumes/31/05/correspondence.html)

<!-- Similar articles end here -->