
---
title: 'The Inevitable'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1910
categories: 
  - Discrimination
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 2
  page: 21
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



In the argument of the prejudiced there is a certain usual ending: "But this is inevitable." For instance, a crime is committed by you. I am lynched. "It is inevitable," cries the bystander, "they were both Negroes." A brown man is admitted to a theatre, misbehaves and is ejected.

I apply for a ticket and am refused. "It is inevitable," sighs the manager, "you are brown." A yellow man is a fool; therefore, Smith, who is also yellow, is treated like an idiot. "I am sorry," remarks the policeman, "but they are both yellow."

What is the real argument in these cases? It is this: "People who resemble each other in one important respect ought to resemble each other in all important respects and therefore be treated alike. If by any chance they do not so resemble each other, this is unfortunate, for the same treatment must be meted out. This is inevitable."

Is it? It is not inevitable. It is criminal injustice. It is inhuman treatment and it is socially dangerous. It is based on the unscientific assumption that human beings who resemble each other in one important particular, like color of skin, resemble each other in all particulars. This is patently false. Moreover, the social condemnation of an undesirable act or character loses all force or reason when it is directed against one who has not committed the act or has not the condemned character. To allow the mistreatment of such an innocent man---to condone it or defend it, is not inevitable; it is a crime.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [A Statement (1919)](/Volumes/19/01/statement.html)
* [The Truth (1912)](/Volumes/05/02/truth.html)
* [Logic (1913)](/Volumes/06/02/logic.html)
* [A Little Play (1914)](/Volumes/07/05/a_little_play.html)
* [Crime (1920)](/Volumes/19/04/crime.html)

<!-- Similar articles end here -->