
---
title: 'N.A.A.C.P.'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1910
categories: 
  - NAACP
  - Tactics
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 2
  page: 16-17
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


What is the National Association for the Advancement of Colored People? It is a union of those who believe that earnest, active opposition is the only effective way of meeting the forces of evil. They believe that the growth of race prejudice in the United States is evil. It is not always consciously evil. Much of it is born of ignorance and misapprehension, honest mistake and misguided zeal. However caused, it is none the less evil, wrong, dangerous, fertile of harm. For this reason it must be combatted. It is neither safe nor sane to sit down dumbly before such human error or to seek to combat it with smiles and hushed whispers. Fight the wrong with every human weapon in every civilized way.  

The National Association for the Advancement of Colored People is organized to fight the wrong of race prejudice:    

<ol type="A">
<li> By doing away with the excuses for prejudice.    
<li> By showing the unreasonableness of prejudice.    
<li> By exposing the evils of race prejudice.
</ol>

This is a large program of reform? It is, and this is because the evil is large. There is not to-day in human affairs a more subtle and awful enemy of human progress, of peace and sympathy than the reaction war and hatred that lurks in the indefinite thing which we call race prejudice. Does it not call for opposition---determined, persistent opposition? Aree rational beings justified in sitting silently, willingly dumb and blind to the growth of this crime? We believe not. We are organized, then to say to the world and our country:  

Negroes are men with the foibles and virtues of men.   

To treat evil as though it were good and good as though it were evil is not only wrong but dangerous, since in the end it encourages evil and discourages good.     

To treat all Negroes alike is treating evil as good and good as evil.     

To draw a crass and dogged undeviated color line in human affairs is dangerous---as dangerous to those who draw it as to those against whom it is drawn.     

We are organized to fight this great modern danger. How may we fight it?     

1. By the argument of the printed word in a periodical like this, and in pamphlets and tracts.    
2. By the spoken word in talk and lecture.    
3. By correspondence.    
4. By encouraging all efforts at social uplift.    
5. By careful investigation of the truth in matters of social condition and race contact---not the truth as we want or you want it, but as it really is.    
6. By individual relief of the wretched.

If you think such work is worth while aid us by joining our organization and contributing to it.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [Muddle (1916)](/Volumes/13/02/muddle.html)
* [A Statement (1919)](/Volumes/19/01/statement.html)
* [The Next Step (1913)](/Volumes/06/02/next_step.html)
* [The Congressmen and the NAACP (1914)](/Volumes/09/02/congressmen_and_the_naacp.html)
* [White Co-Workers (1920)](/Volumes/20/01/white_coworkers.html)

<!-- Similar articles end here -->