
---
title: 'Precept and Practice'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Dec. 1910
categories: 
  - Discrimination
  - White hipocrisy

citation: 
  type: article-journal
  container-title: The Crisis
  volume: 1
  issue: 2
  page: 27
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


A large audience was leaving New York's finest theatre. The play had been upon the Negro question, and one couple had been especially thrilled by the fine heroism of the white man, who, finding that he had a few drops of colored blood, allied himself with the despised race. "How magnificent," they were saying, "to dedicate oneself to the cause of the oppressed!"

Walking a few blocks they turned into a restaurant. After giving their order they noticed a man, a mulatto in coloring, enter and seat himself at a table. Presently a waiter came to him and whispered something. The man shook his head, and the waiter went to the proprietor.

 "I really believe," the couple said, watching curiously, "that they are going to ask that man to leave. What a shame, for he is quite light and very good looking."

The proprietor came to the man as he sat at the table, and after a few words, the couple amusing themselves guessing their import, the colored man rose and left.

"That was too bad, wasn't it," one said to the other, "and right here in our own city. Perhaps the poor fellow really needed a meal," and they went on placidly enjoying their own.

