
---
title: 'Crime'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1918
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 15
  issue: 5
  page: 215-216
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


Strong and ever stronger elements among the white Methodists are determined to consummate one of the greatest crimes against the Negro race since slavery. In order to unite the M. E. Church and the M. E. Church South, they are trying to get rid of 350,000 Negro members. Before the war the Methodists, by their meanness, drove a half million of their Negro members out into the wilderness, where they set up their own temples. Then repentant and remorseful, the church rose to its opportunity, damned slavery, spewed out the slave owners, and welcomed the slaves, even as their Master would have done. 

To-day, the dry rot of power and numbers and prestige has seized them. In the name of Christian "unity," Bishops and powerful laymen and strong periodicals are determined to kick 350,000 Negroes out of the church. Every other obstacle to union with the South is settled. Yet the secret conferences proceed. The oiliest of the church hypocrites, led by Zion's Herald, are urging the black "brethren" to "withdraw" before they are thrown out, and offering them thirty pieces of silver in the guise of church property and bishops' robes for their leaders. That body of death, the Methodist Church South, is stretching its lean and blood-stained hands for its pound of black flesh. God! for one modern Sermon to the Pharisees for these "Christians!"

*But woe unto you, scribes and Pharisees, hypocrites! for ye shut up the kingdom of heaven against men: for ye neither go in yourselves, neither suffer ye them that are entering to go in.*

*Woe unto you, scribes and Pharisees, hypocrites! for ye compass sea and land to make one proselyte; and when he is made, ye make him two-fold more the child of hell than yourselves.*

*Woe unto you, scribes and Pharisees, hypocrites! for ye pay tithe of mint and anise and cummin, and have omitted the weightier matters of the law, judgment, mercy, and faith: these ought ye to have done, and not to leave the other undone.*

*Ye blind guides, which strain at a gnat, and swallow a camel.*

*Woe unto you, scribes and Pharisees, hypocrites! because ye build the tombs of the prophets, and garnish the sepulchres of the righteous.*

*And say, "If we had been in the days of our fathers, we would not have been partakers with them in the blood of the prophets."*

*Wherefore ye be witnesses unto yourselves, that ye are the children of them which killed the prophets.*

*Fill ye up then the measure of your fathers.*

*Ye serpents, ye generation of vipers, how can ye escape the damnation of hell?*

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Methodist Church, North (1911)](/Volumes/01/05/methodist_church_north.html)
* [The Church and the Negro (1913)](/Volumes/06/06/church_negro.html)
* [The Negro Church (1912)](/Volumes/04/01/negro_church.html)
* [The Church (1916)](/Volumes/11/06/church.html)
* [The Episcopal Church (1913)](/Volumes/07/02/episcopal_church.html)

<!-- Similar articles end here -->