
---
title: 'The Grandfather Clause'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 5
  page: 231-232
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



The white southern oligarchy is laughing silently behind its hand.
Two decades' years ago it faced a dilemma. A wretched Negro public
school system (which has since grown worse in most southern states) made
it easy to disfranchise the mass of the Negro voters by a literacy test.
But how about the 100,000 southern white voters who could not read and
write? To cajole these the oligarchy, with a smile, concocted the
celebrated "Grandfather clause," impudently establishing hereditary
privilege in this republic. They did not expect the scheme to work. It
was a "gold brick" pure and simple for inducing the ignorant white
laborer to destroy the black labor vote and leave himself so much the
more at the mercy of the capitalist. To the amazement of the white South
itself this illegal, undemocratic and outrageous provision has actually
been allowed to stand on the statute books and be enforced for SEVENTEEN
YEARS!

Finally, when further evasion of the issues involved was humanly almost
impossible, the Supreme Court solemnly declares a law unconstitutional
which has already been in force a half a generation.

Considering, however, the inexcusable blows delivered on the body of the
prostrate black man by the Supreme Court from the Dred Scott case, of
infamous memory, to the emasculating of the Fourteenth Amendment, the
civil rights cases and the "Jim-Crow" decisions of our day, we have
cause to rejoice at the overthrow of the "Grandfather Clause." 

But there is much more than this in the late decision and the Bourbon South would do well to laugh neither loud nor too long. The Supreme Court has confirmed the *validity* of the Fifteenth Amendment. It has declared that *Negroes* have a *right* to vote on the same terms as other
citizens. This is a blow at all race discrimination in politics. This
will not give us our rights immediately but it puts us in the shadow of
the mightiest advance since 1863.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Supreme Court (1914)](/Volumes/09/02/supreme_court.html)
* [Education (1930)](/Volumes/37/02/education.html)
* [Votes (1919)](/Volumes/19/02/votes.html)
* [How Shall We Vote (1920)](/Volumes/20/05/how_shall_we_vote.html)
* [An Open Letter to Woodrow Wilson (1913)](/Volumes/05/05/open_letter.html)

<!-- Similar articles end here -->