
---
title: 'Hayti'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 5
  page: 232
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



Let us save Hayti. Hayti is a noble nation. It is a nation that has given the world one of its greatest names---Toussaint L'Ouverture. It is a nation that made slaves free. It is a nation that dared and dares to fight for freedom. This is no time or place for us American Negroes who seldom have had courage to fight, to point scornful fingers at our brothers.

Remember that in one respect Hayti leads the world. Out of a hell of slavery it has succeeded in placing on their own little farms the happiest peasants in the world. Not France, Germany, England nor Russia has done the like. Industrially Hayti has lagged because she lacks capital and capital is the present day monopoly of white nations. Finally stung by poverty and lured by European luxury a portion of Hayti's leaders have robbed her shamefully. She is struggling to rid herself of these grafters. Let us help and not hinder. Let us help Hayti rid herself of thieves and not try to fasten American thieves on her.

The time calls for a Haytian Commission of white and colored men appointed by the President to co-operate with Hayti in establishing permanent peace and in assuring our stricken sister that the United States respects and will always respect her political integrity.

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Hayti (1915)](/Volumes/10/06/hayti.html)
* [Work for Black Folk in 1914 (1914)](/Volumes/07/04/work_for_black_folk.html)
* [The Future of Africa (1919)](/Volumes/17/03/future-of-africa.html)
* [The League of Nations (1919)](/Volumes/19/01/league.html)
* [Close Ranks (1918)](/Volumes/16/03/close_ranks.html)

<!-- Similar articles end here -->