
---
title: 'Other Organizations'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 5
  page: 233
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



We have received in a number of cases recently complaint that in mentioning the work and protests of the National Association for the Advancement of Colored People we have not always mentioned other organizations engaged in similar work. Let us make our policy clear: When any action of any kind has in our judgment a real news value we mention it and mention therewith such names and places as will make it intelligible. We do not attempt, however, to chronicle the actions of organizations or persons which have no general news value *except in one case* and that is the case of the National Association for the Advancement of Colored People. As the special organ of this organization we chronicle for the benefit of its 7,500 members and tens of thousands of its friends and sympathizers its actions *in detail.* This obviously we do in the case of no other organization with such particularity.

On the other hand we never consciously suppress news of persons or organizations or fail to attempt to give due credit to all.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Booming The Crisis (1914)](/Volumes/07/05/booming_crisis.html)
* [Our Special Grievances (1918)](/Volumes/16/05/our_special_greivances.html)
* [Radicals (1919)](/Volumes/19/02/radicals.html)
* [A Correspondence (1914)](/Volumes/09/01/correspondence.html)
* [The Next Step (1913)](/Volumes/06/02/next_step.html)

<!-- Similar articles end here -->