
---
title: 'A Pageant'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1915
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 10
  issue: 5
  page: 230-231
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---



In 1913 and since there have been several celebrations of the Fiftieth
Anniversary of the Emancipation Proclamation. The Emancipation
Proclamation, however, only proclaimed freedom in parts of the United
States and it did not make the institution of slavery illegal. The
Thirteenth Amendment was the legal end of American slavery. This
Amendment passed Congress January 31, 1865, and became a part of the
Constitution December 18, 1865.

It is fitting that the jubilee of this great landmark in human culture
be celebrated, and celebrated in Washington by the descendants of the
chief beneficiaries of its provisions.

The celebration, too, should be unique and make a wide appeal. The
ordinary "exposition" idea with assembled exhibits has not only been
overworked but done so extraordinarily well at Paris, Chicago and St.
Louis that no small effort however commendable can be aught but
disappointing.

The Pageant, that new and rising form of art expression, seems
especially fitted for such a celebration as this. A pageant is not a
tableau or playlet or float. It is a great historical folk festival,
staged and conducted by experts with all the devices of modern
theatrical presentation and with the added touch of reality given by
numbers, space and fidelity to historical truth.

The great pageants of England and those at Philadelphia, Boston and St.
Louis in America are well known. Only one pageant has been attempted by
American Negroes. This formed the chief feature of the Emancipation
Celebration of the State of New York and repeatedly drew crowds beyond
the capacity of the large armory.

Many requests have been made for a repetition of this pageant but this
seemed impracticable. However, a partnership has finally been formed to
be known as the Horizon Guild, under the presidency of Dr. W.E.B. Du
Bois. The Horizon Guild, which will eventually be incorporated, proposes
to present pageants of Negro history in the principal centers of Negro
population during the next decade. It is hoped in this way to form a
sound basis for the dignified celebration of the adoption ot the
Fourteenth Amendment in 1916, the Ter-Centennary of the Landing of the
Negro in 1919 and the Jubilee of the Fifteenth Amendment in 1920.

The Guild is not a money making venture but a philanthropy on business
principles whose small initial capital has been contributed by persons
interested in the development of Negro dramatic art in America.
Furthermore, the Guild is entirely an independent venture with a single
object and unconnected with any other organization.

During the week of October tenth the Horizon Guild will present in
Washington, D.C., a pageant "The Jewel of Ethiopia" portraying the history of the Negro race for 5,000 years. The
pageant will be given under the auspices of a local committee of one
hundred citizens and will use one thousand participants chosen from
among the colored inhabitants of the district. The pageant will be given
in the open air. The
musical setting will consist of fifty-three pieces of Negro music by
Negro composers; the costumes will be historically accurate and the
scenery and properties will be simple but imposing. Altogether this will
be the greatest dramatic event ever attempted by colored Americans and
it will fitly celebrate the great Amendment which declared that
*"neither slavery nor involuntary servitude ... shall exist within the United States or any place subject to their jurisdiction."*

Persons interested in the work of the Horizon Guild may communicate with
the Editor of <span class="small-caps">The Crisis</span>.

<!-- Similar articles start here -->

<hr>
#### Related Articles:

* [Emancipation (1913)](/Volumes/05/03/emancipation.html)
* [An Open Letter to Woodrow Wilson (1913)](/Volumes/05/05/open_letter.html)
* [The Fourteenth Amendment (1915)](/Volumes/10/01/fourteenth_amendment.html)
* [Civil Rights (1913)](/Volumes/06/04/civil_rights.html)
* [Thirteen (1918)](/Volumes/15/03/efficiency.html)

<!-- Similar articles end here -->