
---
title: 'The Races in Congress'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 5
  page: 200-209
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




 ## I.---What Was the Races Congress? 

Several years ago at Eisenach, Germany, Dr. Felix Adler suggested a congress of the races of the world. No attempt was made to follow up this idea for several years; then the Ethical Culture Society permitted one of its best organizers, Gustave Spiller, to devote two years to the organizing of such a congress. It was planned to hold the congress in the summer of 1911. Extraordinary difficulties faced the organizer. He had' no funds; he had no special clientele to appeal to, and he was embarking upon what large numbers of practical people thought a fanciful, if not an impossible, attempt. Then, too, other people feared and opposed it for political and social reasons. Nevertheless, Mr. Spiller went to work.

Within two years he succeeded in enlisting the support of no less than fifty countries, over thirty presidents of parliaments, the majority of the members of the Permanent Court of Arbitration and of the delegates to the Second Hague Conference, twelve British governors and eight British premiers, over forty colonial bishops, some hundred and thirty professors of international law, the leading anthropologists and sociologists, the officers and the majority of the council of the Interparliamentary Union, and other distinguished personages. As writers of papers, Mr. Spiller secured representatives from over twenty civilizations, and every paper referring to a particular people was prepared by some one of high standing belonging to that people. 

As president of the congress, the Right Honorable Lord Weardale, a well-known figure in the World's Peace movement, was secured. Among the vice-presidents was the Prime Minister of England, Mr. Balfour, leader of the opposition, Viscount Morley of Blackburn, the speaker of the House of Commons, the Archbishop of York, and others. The general committee included some of the greatest names of the world. On Wednesday, July 26, when Lord Weardale opened the first session of the Congress, he looked into the faces of a thousand people representing fifty different races. 

## II.---The Object of the Congress. 

What after all was the object of assembling a congress of this character? To many people it seemed a visionary scheme; what practical outcome could there be? The Executive Committee stated the purpose of the Congress succinctly: "The object of the Congress will be to discuss, in the light of science and the modern conscience, the general relations subsisting between the peoples of the West and those of the East, between so-called white and so-called colored peoples, with a view to encouraging between them a fuller understanding, the most friendly feelings, and a heartier cooperation." Lord Weardale in his introduction to the volume of papers has enlarged upon this idea: 
> To those who regard the furtherance of international good will and peace as the highest of all human interest', the occasion of the First Universal Races Congress opens a vista of almost boundless promise.    
>  &nbsp;
> No impartial student of history can deny that in the case of nearly all recorded wars, whatever the ostensible reasons assigned, the underlying cause of conflict has been the existence of race antipathies---using the word race in its broad and popular acceptation---which particular circumstances, often in themselves of trivial moment, have fanned into flame.        
>  &nbsp;
> In the earliest times it took the form of one race attempting to subjugate and indeed enslave another; but even in modern wars, while questions of frontier, the ambitions of rulers, or the rivalries of commercial policies, may have provoked the actual crisis, it will be found, in almost every instance, that the pre-existence of social and racial enmity has in reality determined the breach which particular incidents had merely precipitated.     
>  &nbsp;
> As civilization progresses and the western world more fully recognizes its ethical responsibilities, it may be hoped that such influences will become an ever diminishing force; but the modern con science has to-day, in addition, other and quite new problems to solve in face of the startling and sudden appearance of new factors in the Eastern Hemisphere.     
>  &nbsp;
> In less than twenty years we have witnessed the most remarkable awakening of nations long regarded as sunk in such depths of somnolence as to-be only interesting to the western world because they presented a wide and prolific field for commercial rivalries, often greedy, cruel, and fraught with bloodshed in their prosecution, but which otherwise were an almost negligible quantity in international concerns.    
>  &nbsp;
> How great is the change in the lifetime of a single generation, when, to select two instances alone, we contemplate the most remarkable rise of the power of the Empire of Japan, the precursor, it would seem, of a similar revival of the activities and highly developed qualities of the population of the great Empire of China!    
>  &nbsp;
> Nearer and nearer we see approaching the day when the caste population of the East will assert their claim to meet on terms of equality the nations of the West, when the free institutions and the organized forces of the one hemisphere will have their counterbalance in the other, when their mental outlook and their social aims will be in principle identical; when, in short, the color prejudice will have vanished and the so-called white races and the so-called colored races shall no longer merely meet in the glowing periods of missionary exposition, but, in very fact, regard one another as in truth men and brothers.     
>  &nbsp;
> Are we ready for this change? Have we duly considered all that it signifies, and have we tutored our minds and shaped our policy with a view of successfully meeting the coming flood? It is in order to discuss this question of such supreme importance that the First Universal Races Congress is being held.

## III.---The Program of the Congress. 

The program, as laid down, sought first to take up fundamental considerations concerning the meaning of race. Then there followed certain general matters of racial progress like government, political conditions, language, religion and miscegenation. The third session began with the special racial problems in China, Japan, Turkey, Persia, India, Egypt, Haiti, etc. Then the matter of interracial contact was spoken of: first, the economic side, and then the bonds of science, art and technique. The fifth session turned to the question of the social conscience in relation to racial questions, and took up the problems of the Jew, and of the Negro in Africa and America,  and also the question of indentured labor and drink. The last two sessions were given up to positive suggestions for permitting interracial friendliness. 

The really astounding thing about this program was the amount of agreement and sympathy among papers from widely different sources. Seldom has there been an international congress where there was so much unity in the underlying thought and where the enthusiasm for the central idea was so manifest and so well expressed. Of course in the very multiplicity of the problems, and the large number of speakers, there were manifest disadvantages; practically all the speakers were limited to seven minutes, and yet there must have been at least 150 speakers. Then, too, the speeches were in different languages, including a good deal of broken English. The acoustics of the hall were not good and the heat was intense. Under such conditions it would have been natural to have had a large number of people in bad temper and a great many misunderstandings. This, however, was not so, and every one attending the sessions came away with a distinct feeling of uplift and hope. 

##  IV.---The Men Who Were There. 

The personnel of the Congress was marvelous. First, there was the natural difference in color, from the jet black of General Légitime, of Haiti, to the blond Germans and Norwegians. The infiltration of Negro blood was particularly noticeable; the two Egyptian Beys were evidently negroid, the Portuguese was without a doubt a mulatto, and the Persian was dark enough to have trouble in the South. Next came the difference in language: English, French, German and Italian were heard and used continually in speeches, in discussion and in conversation. I remember at one dinner party at the beautiful home of Felix Moscheles there were eight people present and they were talking four languages nearly all the time. After all this came the difference of dress and the many other subtle differences of civilizations; the turban, the fez, the ceremonies of greeting, all gave a peculiar picturesqueness to the assembly. 

The personalities which made the most impression upon me were: Mr. Spiller, the creator of the Congress, the indefatigable worker, unselfish and devoted; Dr. Seal, the Indian scholar, tall and brown, with a flowing white beard, full of simple but wholesome enthusiasm; Watanabe, the Japanese parliamentarian, a sweet-tempered scholar; Rubasana, the only Negro member of the Cape Colony Parliament; Hadji Mirza Yahya, the leader of the Persian revolutionists; General Légitime, of Haiti, and his interesting daughter; the Secretary of State of Liberia. Among the most forceful speakers were the Englishmen Robertson and Hobson, and Mrs. Annie Besant. In the audience at various times were many distinguished persons: Prince Kropotkin, of Russia; Schreiner, of South Africa; Finot, of France; the Prince di Cassano; Israel Zangwill, who was listened to with great attention. Wilberforce University sent four popular persons---President Scarborough, Mr. Finch and Chaplain and Mrs. Steward. To all these one must add a large part of learned and philanthropic London, as, for instance, the Ranee of Sarawak, who is the daughter-in-law of Rajah Brooke; Frederic Harrison, Sir Percy Bunting, since deceased; Travers Buxton, and others. 

##  V.---Some of the Papers. 

<em>[Paper abstracts omitted.]</em>

Dr. W. E. B. Du Bois, United States.--- The Negroes number about ten millions in the United States. Most of them descend from former slaves. They live at the present time under a system of theoretical liberty, but it is restricted in practice by certain legal dispositions and by custom. They are well disposed toward family life, in so far as they are enabled to enjoy it, and to education. They have churches of their own. About two hundred thousand of them are farmers, and fifty thousand are engaged in commerce and the liberal professions. Their situation is most distressing in the South, where they suffer civic incapacity, injustice in the courts of law, economic restrictions, discourtesy in public, etc. And 75 per cent. of the Negroes live in the South. One theory proposes that they should emancipate themselves by acquiring wealth, but it would seem that intellectual emancipation should proceed hand in hand with economic independence. 

<em>[Paper abstracts omitted.]</em>

 VI.---The Race Problems. 

When fifty races look each other in the eye, face to face, there rises a new conception of humanity and its problems. For four days these representatives of the world walked and sat and ate side by side and heard speech after speech. There were few set expository talks. Men did not explain their problems as to some third person---rather they expressed their own inner feeling at this contact of soul. Some objected to this. They said: "There are fine phrases after phrases and endless allusions to human brotherhood, but after all there is little scientific ordered explanation. We find our thoughts and sympathies aroused but unsatisfied." 

This was inevitable. To explain means double knowledge: knowledge of the problem, knowledge of the world to whom the problem is being explained. Strangers, therefore, cannot easily reveal themselves to each other and the delegates to the Races Congress were largely strangers. 

Yet in the continual meeting of strangers comes gradual illumination and what the formal speeches failed to do, informal intercourse accomplished to a wonderful degree. First, perhaps, the problem of racial and national integrity stepped to the fore: "We built a great wall once," said the keen Chinese representative, "to keep out the world; a wall so vast that it has been said to be the only work of man capable of being seen from the moon; now you are building a wall against us'---but in either case the clear implication was, China stands and must stand as an independent nation. So with the Turks and the Persians there was a certain frank appeal to the fair judgment of men. We are a congeries of races, said the Turks repeatedly, united in political bonds, and thus we typify the future of the world; and the Persians appealed to a great past as earnest for a greater future. Yet it was significant that while they were speaking Austria was moving all her influence to force European interference in Albania, the ex-Shah landed in Persia and the Times was publishing articles to show England's neglected interests in the Persian gulf. 

 Next to questions of integrity came problems of autonomy among the great subject nations of India and Egypt. How long are these to be held in leading strings? How far can people not "European" govern themselves? How dangerous has been the rise of Japan? The clear unanswerable argument of John Robertson, M.P., was but reason above foaming waters, and one felt the repression of those who talked on these subjects. 

The next great question discussed, not so much directly as by implication, was that of religion. What right has one religion to discredit another and force itself on men, especially when it does not pretend to practice what it preaches? This was the repeated implication in conversation and speech. It was a hard thing to answer in face of the tolerance of the Mohammedan and the Buddhist. Perhaps its best answer was the Races Congress itself.

After this the questions came nearer home and the color line appeared. Who and what are these black and brow: men? Are they really men? And, in the same breath, is their ability due to white blood or is white blood fatal to them? One could, after all, think one's way through the political integrity ot the East and the gradual freedom of India and Egypt, but could black men be free---were they worth freedom? The answer from the United States was sharp and strong and perhaps the most arresting thing in the whole Congress. If America is trying to treat civilized men as uncivilized simply on account of color what effect will this have on the world and on Africa? 

Africa was to the Congress as to the world, the land of the Sphinx. It said little that was articulate, but all knew that it was the land of that new forced and exploited labor on which London and the world waxes luxurious, and that this exploitation is spread over Mexico and South America; is it not one with the economic exploitation of women and children and the mass of laborers generally? 

The question of the status of women leaped continually to the front. If we speak of China, what of Chinese women? It was the women of India and child marriage that created the keenest interest and no paper was more eagerly listened to than that which told of the up struggling of the Negro women of the United States. 

On the other hand, the labor question was hardly touched in its main modern phases, although a strong, masterly argument was made to show that the economic foundations of imperialism were as weak as those of the slave barons of the South and as wicked. 

 On the whole the view of the race problems of the world as revealed in the Congress was strongly reassuring; but the reason of this was clear. It was because the men themselves were there.  In their, absence a terrible indictment against "lazy" Negroes, "dishonest" Chinese and "incompetent" Asiatics could have been framed; but in the face of gentlemen from various human races of all shades and cultures, the fatal exceptions to sweeping rules of fitness continually occurred. The Southerner from the United States was forced to explain that all Negroes were not like this one; the Englishman was forced to show that Indians, fine as they might be personally, had fearful caste hatreds The wretchedness of the fellaheen had to be balanced against the culture of the Egyptian delegates, and everywhere men found themselves facing old and familiar human problems which but helped to  make the essential world humanity plausible It seems no exaggeration to say that few world congresses like this would do more for the unity mankind and reasonable sympathy between races, would do more for the stopping of war, slavery and oppression than any other single movement.

## VII.---The Social Side. 

The social side of a congress is usually the most interesting and this was true of the Races Congress. The opening reception was given July 25 at Fishmonger's Hall. There were fully a thousand guests and it was a gorgeous sight. Or the day before Mr. and Mrs. Milholland gave an interesting reception. Lord Weardale entertained the writers of papers the following night, and on Thursday there were two receptions; one at the Lyceum Club and one at Claridge's Hotel. On Friday there was an official dinner, and on Monday the Countess of Warwick entertained the Congress at Warwick castle. Beside these official occasions there was an endless succession of luncheons, teas and dinners, all given quite regardless of the color line or racial lines, and in all cases the genuine courtesy of the English hosts was noticeable 

## VIII.---Results of the Congress. 

The tangible result of the Congress s the forming an international committee. This international committee has the following nine objects:

1.	To urge the establishing of harmonious relations between the various divisions of mankind is an essential condition precedent to any serious attempt to diminish warfare and extend the practice of arbitration.
2.	To commend to individuals of different races coming into passing or permanent contact with one another which shall be courteous and respectful.
3.	To induce each people to study sympathetically the customs and civilizations of other peoples, since even the lowliest civilizations have much to teach, and since every civilization should be reverenced as having deep historic roots.
4.	To emphasize that difference in civilization does not, as is often supposed, necessarily connote either inferiority or superiority. 
5.	To study impartially and on a broad basis the physical and social effects of race blending and the cases which promote or hinder it, to request governments to compile statistics on the subject and to discourage hasty and crude generalizations on the subject. 
6.	To point out the irreconcilability of the contention prevalent among the various peoples of the world that their customs, their civilizations and their physiques are superior to those of other peoples, and also to deprecate the loose manner in which the term "race" is popularly employed.
7.	To urge the paramount importance of providing in all lands a universal and efficient system of education---physical, intellectual and moral---as one of the principal means of promoting cordial relations within, and among, all divisions of mankind. 
8.	To respect, or to endeavor to assimilate or change, the economic, hygienic, educational and moral standards of immigrants, rather than to regard them as indefensible or fixed.
9.	To collect records of experiments showing the successful uplifting of relatively backward peoples by the application of humane methods, and to urge the application of such methods universally. 

It is also charged with the duty of holding future Races Congresses at least once in four years with the following leading object: "To promote cordial relations among all divisions of mankind, without regard to race, color or creed, and, in particular, to encourage a good understanding between East and West." 

It is finally asked to establish an international institution whose object shall be to investigate and publish as well as form local organizations throughout the world 

