
---
title: 'Social Equality'
author: Du Bois, W.E.B.
date: Mar. 1911
categories: 
  - Social Equality
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 5
  page: 197
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




A colored physician of Kansas City has made a speech at a large meeting in Denver in which he protests that he does not want "social equality." It happens, however, that social equality is precisely what this gentleman does want and we can prove it; if our readers will turn to the March number of <span style="font-variant:small-caps;">The Crisis</span> they will learn that this same physician got on a Pullman car to ride into Texas and was ejected. He protested vigorously, as he ought to have done, and brought suit. Now, riding on a Pullman car is social equality and there is no use in pretending that it is not. Equal civil rights are impossible without social equality. Equal political rights are impossible without social equality. When American Negroes recently sent a protest to England complaining of civil and political degradation what did the South retort? Practically all the Southern white papers said this is "demanding social equality;" and it was. Social equality is simply the right to be treated as a gentleman when one is among gentlemen and acts like a gentleman. No person who does not demand such treatment is fit for the society of gentlemen. Of course, what the speaker meant to say was that he had no desire to force his company on people unnecessarily if they objected to him, but such a right does not imply "equality" but "superiority," and this speaker knows or ought to know that every time a black man says publicly that he is willing to be treated as a social pariah, he is forging the chains of his social slavery. Let intelligent black men stop this sort of talk. If they are afraid to demand their rights as men, they can, at least, preserve dignified silence.

