
---
title: 'Triumph'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 5
  page: 195
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




Let the eagle scream! Again the burden of upholding the best traditions of Anglo-Saxon civilization has fallen on the sturdy shoulders of the American republic. Once more a howling mob of the best citizens in a foremost State of the Union has vindicated the self-evident superiority of the white race. The case was perfectly clear; it was not that murder had been done, for we Americans are not squeamish at mere murder. Off and on we do more of that kind of thing than most folk. Moreover, there was not much of a murder---only the crazed act of a drunken man quite unpremeditated. The point is he was black.

Blackness must be punished. Blackness is the crime of crimes, as the opera-bouffe senator-elect from Mississippi has amply proven. Why is it a crime? Because it threatens white supremacy. A black might---why, civilization might be black! It is therefore necessary, as every white scoundrel in the nation knows, to let slip no opportunity of punishing this crime of crimes. Of course, if possible, the pretext should be great and overwhelming---some awful stunning crime made even more horrible by reporters' imaginations. Failing this, mere murder, arson, barn burning or impudence may do; indeed, must do. 

Once the pretext given, then let loose the majesty of American culture. It must warm the hearts of every true son of the republic to read how the brawn and sinew of Coatesville rallied to the great and glorious deed. It deserves a poem; think of the hoary farmers, toilworn with the light of a holy purpose in their eyes and pitchforks in their hands. "The churches were nearly deserted," say the papers. Splendid! Was it not fitting that Coatesville religion should lend its deacons and Sunday-school superintendents to the holy crusade? Did they not choose a noble day? Sunday, the festival of the risen Prince of Peace. 

Ah, the splendor of that Sunday night dance. The flames beat and curled against the moonlit sky. The church bells chimed. The scorched and crooked thing, self-wounded and chained to his cot, crawled to the edge of the ash with a stifled groan, but the brave and sturdy farmers pricked him back with the bloody pitchforks until the deed was done. 

Let the eagle scream! 

Civilization is again safe. 

"Oh, say, can you see by the dawn's early light" that soap box of blackened bones and dust, standing in the dew and sunlight on the King's highway to the City of Brotherly Love, while, as the press reports, "all day long, not only from Coatesville, but from all Chester County, and even from Philadelphia, people walked and drove out to the scene of the burning. Men and women poked the ashes and a shout of glee would signalize the finding of a blackened tooth or mere portions of unrecognizable bones. By noon the black heap had been leveled and only the scorched ground was left to tell what had happened there." 

Some foolish people talk of punishing the heroic mob, and the Governor of Pennsylvania seems to be real provoked. We hasten to assure our readers that nothing will be done. There may be a few formal arrests, but the men will be promptly released by the mob sitting as jury---perhaps even as judge. 

America knows her true heroes. 

Again, let the eagle scream! 

But let every black American gird up his loins. The great day is coming. We have crawled and pleaded for justice and we have been cheerfully spit upon and murdered and burned. We will not endure it forever. If we are to die, in God's name let us perish like men and not like bales of hay. 

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Crime (1920)](/Volumes/19/04/crime.html)
* [The Old Story (1911)](/Volumes/01/03/old_story.html)
* [Murder (1914)](/Volumes/09/02/murder.html)
* [Courts and Jails (1932)](/Volumes/39/04/courts_and_jails.html)
* [Lynching (1911)](/Volumes/02/04/lynching.html)

<!-- Similar articles end here -->