
---
title: 'The World in Council'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1911
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 2
  issue: 5
  page: 196
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---




The greatest event of the twentieth century so far was the First Universal Races Congress. It was more significant than the Russian-Japanese war, the Hague Conference or the rise of Socialism. It was significant not on account of the size of its meetings, well attended as they were; not on account of the weight of its utterances, weighty as they were; not on account of the publicity it received or the influence it spread.

The Universal Races Congress was great because it marked the first time in the history of mankind when a world congress dared openly and explicitly to take its stand on the platform of human equality---the essential divinity of man.

For the first time in history the representatives of a majority of all the nations of the earth met on a frankly equal footing to discuss their relations to each other, and the ways and means of breaking down the absurd and deadly differences that make men hate and despise each other simply because they do not look and think and act alike.

Other world congresses there have been, and they have not dared to attack this problem openly and honestly. The Church has repeatedly dodged and temporized with race prejudice. The State has openly used it for conquest, murder and oppression Great reform movements like the Peace and Labor movement have again and again refused to see in race prejudice their greatest obstacle, their subtlest and deadliest enemy.

Here at last is a full fair frontal attack on the nastiest modern survival of ancient barbarism. It was a great day for humanity. It was a great day even in the light of the expected criticisms that the Congress accomplished nothing. It accomplished wonders. It met successfully in peace and concord and yet with unusual freedom of speech. It secured the co-operation of many of the leading people of the world and induced them to stand openly on its platform not simply of.

"Peace," but of "Good Will Toward Men." Finally it took steps toward the perfection of a world organization for interracial concord, investigation and co-operation.

Every word uttered, every step taken by this Congress is in direct opposition to the dominant philosophy of race hatred, suppression and lynching current in the United States. The sooner sane and honest Americans realize that the present policy of America toward the Negro race is directly contrary to Christian, Mohammedan and Buddhist ethics, and is a disintegrating and degrading force which the best thought and conscience of the world condemns, the sooner will such people join the National Association for the Advancement of Colored People and fight for true liberty and decency.

Can anyone doubt the ripeness of the time? Awake, put on thy strength, O Zion!

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>
<hr>
#### Related Articles:

* [The Races in Conference (1910)](/Volumes/01/02/races_in_conference.html)
* [The Races in Congress (1911)](/Volumes/02/05/races_congress.html)
* [Resolutions of the Washington Conference (1917)](/Volumes/14/02/resolutions.html)
* [Races (1911)](/Volumes/02/04/races.html)
* [Inter-Racial Comity (1922)](/Volumes/22/01/inter-racial_comity.html)

<!-- Similar articles end here -->