
---
title: 'Correspondence'
author:
  - name:
      given: W.E.B.
      family: Du Bois
date: Mar. 1926
categories: 
  - ""
citation: 
  type: article-journal
  container-title: The Crisis
  volume: 31
  issue: 5
  page: 218
google-scholar: true

format:
  html:
    toc: false
    appendix-cite-as: display
---


> *Broken Bow, Nebraska.* <p> As president of a woman's club I am writing you for information in regard to your views on race assimilation, intermarriage of Negroes and whites. We have just completed a two weeks' study of your book "Souls of Black Folk" and are unable to arrive at a definite conclusion as to your attitude toward this question. I am asking you to please let me know your honest convictions along this line and greatly oblige,  
>&nbsp;
> Dr. Elizabeth Leonard

---

69 Fifth Ave., New York.

 1. I believe that from time to time the groups of human beings, which we call races, assimilate and again differentiate. No race is permanent in its physical or mental characteristics.

2. I believe that individuals usually will find the greatest happiness and the greatest chance to do their best work if they marry within their own racial group. There are, of course, exceptions to this and many marriages between persons of different races have turned out happily. But usually, for obvious reasons, marriages within the group are most likely to be happy.

3. Despite the above I maintain the perfect right of any individual of any race, who is sane and normal, to marry the person who wishes to marry him. Any denial of this fundamental right of human intercourse always results in more evil than the denial seeks to prevent.

4. Specifically and in regard to the intermarriage of Negroes and whites in the United States, I believe that when any group is disliked and ostracized, for historical and other reasons, its self-respect demands that it seek to minimize as far as possible any intermarriage with the group that assumes superiority.

5. Finally, I have no doubt that in large numbers of cases groups of persons working together and intermarrying have been enabled to make peculiar contributions to civilization and to preserve and hand down these gifts; and any group that has done this or wishes to do it has a right to confine its marriages to its own members so far as it does not seek also to insult or degrade other groups or deny them the same rights.

*W. E. B. Du Bois*

<!-- Similar articles start here -->
<div  class="clear-wrap"></div>

#### Related Articles

* [Unity (1924)](/Volumes/28/03/unity.html)
* [Color Caste in the United States (1933)](/Volumes/40/03/color_caste_in_the_united_states.html)
* [Pan-Africa and New Racial Philosophy (1933)](/Volumes/40/11/panafrica_and_new_racial_philosophy.html)
* [Intermarriage (1913)](/Volumes/05/04/intermarriage.html)
* [The Negro Citizen (1929)](/Volumes/36/05/negro_citizen.html)

<!-- Similar articles end here -->